using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using ValoraPesquisa.Application.Contracts; using ValoraPesquisa.Domain.Entities;
namespace ValoraPesquisa.Api.Controllers;
[ApiController,Authorize,Route("organizations")] public sealed class OrganizationsController(IOrganizationRepository repo,IAuditService audit):ControllerBase{ [HttpGet] public Task<IReadOnlyList<Organization>> Get()=>repo.ListAsync(); [HttpPost] public async Task<IActionResult> Post(OrganizationInput i){ var org=new Organization(Guid.NewGuid(),i.Name,i.PublicName,i.Slug,i.Document,i.Email,i.Phone,"active",i.PlanCode??"free",DateTimeOffset.UtcNow,null,null,null,false); var saved=await repo.CreateAsync(org); await audit.RecordAsync(saved.Id,null,"organization_created","organization",saved.Id,Cid(HttpContext),new{saved.Slug}); return Ok(saved);} static string Cid(HttpContext c)=>c.Items["CorrelationId"]?.ToString()??""; }
public record OrganizationInput(string Name,string PublicName,string Slug,string? Document,string Email,string? Phone,string? PlanCode);
[ApiController,Authorize,Route("users")] public sealed class UsersController(IUserRepository repo,IPasswordHasher hasher,IAuditService audit):ControllerBase{ [HttpGet] public Task<IReadOnlyList<User>> Get()=>repo.ListAsync(Current()); [HttpPost] public async Task<IActionResult> Post(UserInput i){ var u=new User(Guid.NewGuid(),i.OrganizationId,i.Name,i.Email,hasher.Hash(i.Password),i.Role,"active",i.Phone,null,DateTimeOffset.UtcNow,null,false); var saved=await repo.CreateAsync(u); await audit.RecordAsync(saved.OrganizationId,saved.Id,"user_created","user",saved.Id,Cid(HttpContext),new{saved.Email,saved.Role}); return Ok(new{saved.Id,saved.OrganizationId,saved.Name,saved.Email,saved.Role,saved.Status,saved.Phone}); } CurrentUser Current()=>new(Guid.Parse(User.FindFirst("user_id")!.Value),Guid.TryParse(User.FindFirst("organization_id")?.Value,out var o)?o:null,User.FindFirst("role")!.Value,User.FindFirst("email")!.Value); static string Cid(HttpContext c)=>c.Items["CorrelationId"]?.ToString()??""; }
public record UserInput(Guid? OrganizationId,string Name,string Email,string Password,string Role,string? Phone);
[ApiController,Authorize,Route("forms")] public sealed class FormsController:ControllerBase{ [HttpGet] public IActionResult List()=>Ok(new{ok=true,items=Array.Empty<object>()}); [HttpGet("{id:guid}")] public IActionResult Get(Guid id)=>Ok(new{ok=true,id}); [HttpPost] public IActionResult Post()=>Ok(new{ok=true,action="form_created"}); [HttpPut("{id:guid}")] public IActionResult Put(Guid id)=>Ok(new{ok=true,id}); }
[ApiController,Authorize,Route("surveys")] public sealed class SurveysController:ControllerBase{ [HttpGet] public IActionResult List()=>Ok(new{ok=true,items=Array.Empty<object>()}); [HttpGet("{id:guid}")] public IActionResult Get(Guid id)=>Ok(new{ok=true,id}); [HttpPost] public IActionResult Post()=>Ok(new{ok=true,action="survey_created"}); [HttpPut("{id:guid}")] public IActionResult Put(Guid id)=>Ok(new{ok=true,id}); [HttpPatch("{id:guid}/status")] public IActionResult Status(Guid id)=>Ok(new{ok=true,id}); [HttpGet("{surveyId:guid}/links")] public IActionResult Links(Guid surveyId)=>Ok(new{ok=true,items=Array.Empty<object>()}); [HttpPost("{surveyId:guid}/links")] public IActionResult CreateLink(Guid surveyId)=>Ok(new{ok=true,surveyId,publicUrl=$"/pesquisa/responder?survey={surveyId}&token=return-on-create-only&org=valora-group"}); }
[ApiController,Authorize,Route("survey-links")] public sealed class SurveyLinksController:ControllerBase{ [HttpPatch("{linkId:guid}/status")] public IActionResult Status(Guid linkId)=>Ok(new{ok=true,linkId}); }
[ApiController,Route("public")] public sealed class PublicSurveysController:ControllerBase{ [HttpGet("surveys/validate")] public IActionResult Validate(Guid surveyId,string token,string org)=>Ok(new{ok=true,surveyId,org,form=new{questions=Array.Empty<object>()}}); [HttpPost("surveys/{surveyId:guid}/responses")] public IActionResult Respond(Guid surveyId)=>Ok(new{ok=true,surveyId,resultToken="return-on-create-only"}); [HttpGet("results/{responseId:guid}")] public IActionResult Result(Guid responseId,string token)=>string.IsNullOrWhiteSpace(token)?Unauthorized(new{ok=false,code="INVALID_RESULT_TOKEN",message="Token de resultado inválido."}):Ok(new{ok=true,responseId,level="Inicial"}); }
[ApiController,Authorize,Route("audit")] public sealed class AuditController:ControllerBase{ [HttpGet("events")] public IActionResult Events()=>Ok(new{ok=true,items=Array.Empty<object>()}); }
