using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ValoraPesquisa.Application.Contracts;
using ValoraPesquisa.Application.DTOs;
using ValoraPesquisa.Application.Services;
using ValoraPesquisa.Domain.Entities;
using ValoraPesquisa.Domain.Enums;
namespace ValoraPesquisa.Api.Controllers;
public abstract class ApiBase:ControllerBase{ protected CurrentUser Current()=>new(Guid.Parse(User.FindFirstValue("user_id")!),Guid.TryParse(User.FindFirstValue("organization_id"),out var o)?o:null,User.FindFirstValue("role")!,User.FindFirstValue("email")!); protected string Cid=>HttpContext.Items["CorrelationId"]?.ToString()??""; protected Guid OrgOrThrow(CurrentUser u,Guid? input=null)=>u.IsAdminValora?(input??throw new ArgumentException("organizationId obrigatório.")):(u.OrganizationId??throw new UnauthorizedAccessException("Organização não definida.")); }
[ApiController,Authorize,Route("organizations")] public sealed class OrganizationsController(IOrganizationRepository repo,IAuditService audit):ApiBase{
 [HttpGet] public Task<IReadOnlyList<OrganizationDto>> Get()=>repo.ListAsync(Current());
 [HttpGet("{id:guid}")] public async Task<IActionResult> Get(Guid id)=>await repo.FindByIdAsync(id,Current()) is { } o?Ok(o):NotFound();
 [HttpPost] public async Task<IActionResult> Post(OrganizationInput i){ if(!Current().IsAdminValora) return Forbid(); if(!i.Email.Contains('@')) throw new ArgumentException("E-mail inválido."); if(await repo.FindBySlugAsync(i.Slug)!=null) throw new ArgumentException("Slug já cadastrado."); var org=new Organization(Guid.NewGuid(),i.Name,i.PublicName,i.Slug,i.Document,i.Email,i.Phone,"active",i.PlanCode??"free",DateTimeOffset.UtcNow,null,Current().Id,null,false); var saved=await repo.CreateAsync(org); await audit.RecordAsync(saved.Id,Current().Id,"organization_created","organization",saved.Id,Cid,new{saved.Slug}); return Ok(saved);}
 [HttpPut("{id:guid}")] public async Task<IActionResult> Put(Guid id,OrganizationInput i){ var saved=await repo.UpdateAsync(id,i.Name,i.PublicName,i.Slug,i.Document,i.Email,i.Phone,"active",i.PlanCode??"free",Current()); await audit.RecordAsync(id,Current().Id,"organization_updated","organization",id,Cid,new{saved.Slug}); return Ok(saved);} }
public record OrganizationInput(string Name,string PublicName,string Slug,string? Document,string Email,string? Phone,string? PlanCode);
[ApiController,Authorize,Route("users")] public sealed class UsersController(IUserRepository repo,IPasswordHasher hasher,IAuditService audit):ApiBase{
 static readonly string[] Roles={Roles.AdminValora,Roles.EmpresaAdmin,Roles.GestorPesquisa,Roles.Participante};
 [HttpGet] public Task<IReadOnlyList<UserDto>> Get()=>repo.ListAsync(Current()); [HttpGet("{id:guid}")] public async Task<IActionResult> Get(Guid id){var u=await repo.FindByIdAsync(id); if(u==null)return NotFound(); if(u.OrganizationId.HasValue) ValoraPesquisa.Infrastructure.Repositories.Scope.DemandOrg(Current(),u.OrganizationId.Value); return Ok(new UserDto(u.Id,u.OrganizationId,u.Name,u.Email,u.Role,u.Status,u.Phone,u.LastLoginAt,u.CreatedAt,u.UpdatedAt));}
 [HttpPost] public async Task<IActionResult> Post(UserInput i){ var cur=Current(); if(!Roles.Contains(i.Role)) throw new ArgumentException("Perfil inválido."); var org=cur.IsAdminValora?i.OrganizationId:cur.OrganizationId; if(!cur.IsAdminValora && i.Role==Roles.AdminValora) return Forbid(); var u=new User(Guid.NewGuid(),org,i.Name,i.Email,hasher.Hash(i.Password),i.Role,"active",i.Phone,null,DateTimeOffset.UtcNow,null,false); var saved=await repo.CreateAsync(u); await audit.RecordAsync(saved.OrganizationId,cur.Id,"user_created","user",saved.Id,Cid,new{saved.Email,saved.Role}); return Ok(saved);}
 [HttpPut("{id:guid}")] public async Task<IActionResult> Put(Guid id,UserUpdateInput i){var saved=await repo.UpdateAsync(id,i.Name,i.Email,i.Phone,i.Role,i.OrganizationId,Current()); await audit.RecordAsync(saved.OrganizationId,Current().Id,"user_updated","user",id,Cid,new{saved.Email,saved.Role}); return Ok(saved);} [HttpPatch("{id:guid}/status")] public async Task<IActionResult> Status(Guid id,StatusInput i){await repo.SetStatusAsync(id,i.Status,Current()); await audit.RecordAsync(Current().OrganizationId,Current().Id,"user_status_changed","user",id,Cid,new{i.Status}); return Ok(new{ok=true,id,status=i.Status});}}
public record UserInput(Guid? OrganizationId,string Name,string Email,string Password,string Role,string? Phone); public record UserUpdateInput(Guid? OrganizationId,string Name,string Email,string Role,string? Phone); public record StatusInput(string Status);
[ApiController,Authorize,Route("forms")] public sealed class FormsController(IFormRepository repo,IAuditService audit):ApiBase{ [HttpGet] public Task<IReadOnlyList<FormDto>> List()=>repo.ListAsync(Current()); [HttpGet("{id:guid}")] public async Task<IActionResult> Get(Guid id)=>await repo.GetAsync(id,Current()) is { } f?Ok(f):NotFound(); [HttpPost] public Task<IActionResult> Post(FormInput i)=>Save(Guid.NewGuid(),i); [HttpPut("{id:guid}")] public Task<IActionResult> Put(Guid id,FormInput i)=>Save(id,i); async Task<IActionResult> Save(Guid id,FormInput i){var org=OrgOrThrow(Current(),i.OrganizationId); var qs=i.Questions.Select((q,idx)=>new Question(q.Id??Guid.NewGuid(),id,q.Text,q.Type,idx+1,q.Required,q.Weight,q.MaxScore,q.Options.Select((o,j)=>new QuestionOption(o.Id??Guid.NewGuid(),q.Id??Guid.Empty,o.Text,o.Score,j+1)).ToList())).ToList(); qs=qs.Select(q=>q with {Options=q.Options.Select(o=>o with {QuestionId=q.Id}).ToList()}).ToList(); var saved=await repo.SaveAsync(new Form(id,org,i.Title,i.Description,i.Status??"active",DateTimeOffset.UtcNow,null,false,qs),Current()); await audit.RecordAsync(org,Current().Id,"form_saved","form",id,Cid,new{saved.Title}); return Ok(saved);} }
public record FormInput(Guid? OrganizationId,string Title,string? Description,string? Status,IReadOnlyList<QuestionInput> Questions); public record QuestionInput(Guid? Id,string Text,string Type,bool Required,decimal Weight,decimal MaxScore,IReadOnlyList<OptionInput> Options); public record OptionInput(Guid? Id,string Text,decimal Score);
[ApiController,Authorize,Route("surveys")] public sealed class SurveysController(ISurveyRepository repo,IFormRepository forms,ISurveyLinkRepository links,ITokenHasher tokens,IAuditService audit):ApiBase{
 [HttpGet] public Task<IReadOnlyList<SurveyDto>> List()=>repo.ListAsync(Current()); [HttpGet("{id:guid}")] public async Task<IActionResult> Get(Guid id)=>await repo.GetAsync(id,Current()) is { } s?Ok(s):NotFound();
 [HttpPost] public Task<IActionResult> Post(SurveyInput i)=>Save(Guid.NewGuid(),i); [HttpPut("{id:guid}")] public Task<IActionResult> Put(Guid id,SurveyInput i)=>Save(id,i); async Task<IActionResult> Save(Guid id,SurveyInput i){var org=OrgOrThrow(Current(),i.OrganizationId); var s=new Survey(id,org,i.FormId,i.Title,i.Description,i.Status??SurveyStatuses.Draft,i.StartsAt,i.ExpiresAt,i.ShowResult,i.AllowRepeat,DateTimeOffset.UtcNow,null,false); var saved=await repo.SaveAsync(s,Current()); await audit.RecordAsync(org,Current().Id,"survey_saved","survey",id,Cid,new{saved.Title,saved.Status}); return Ok(saved);} 
 [HttpPatch("{id:guid}/status")] public async Task<IActionResult> Status(Guid id,StatusInput i){await repo.SetStatusAsync(id,i.Status,Current()); await audit.RecordAsync(Current().OrganizationId,Current().Id,"survey_status_changed","survey",id,Cid,new{i.Status}); return Ok(new{ok=true,id,status=i.Status});}
 [HttpGet("{surveyId:guid}/links")] public Task<IReadOnlyList<SurveyLinkDto>> Links(Guid surveyId)=>links.ListAsync(surveyId,Current());
 [HttpPost("{surveyId:guid}/links")] public async Task<IActionResult> CreateLink(Guid surveyId,CreateLinkInput i){var s=await repo.GetAsync(surveyId,Current())??throw new ArgumentException("Pesquisa não encontrada."); if(s.Status!=SurveyStatuses.Published) throw new ArgumentException("Link só pode ser criado para pesquisa publicada."); var token=tokens.NewToken(); var publicUrl=$"/Survey/Responder?surveyId={surveyId}&token={Uri.EscapeDataString(token)}&org={i.OrgSlug}"; var link=new SurveyLink(Guid.NewGuid(),surveyId,s.OrganizationId,tokens.Hash(token),publicUrl,"active",i.ExpiresAt,null,DateTimeOffset.UtcNow,null); var saved=await links.CreateAsync(link,token); await audit.RecordAsync(s.OrganizationId,Current().Id,"survey_link_created","survey_link",saved.Id,Cid,new{surveyId}); return Ok(saved);} }
public record SurveyInput(Guid? OrganizationId,Guid FormId,string Title,string? Description,string? Status,DateTimeOffset? StartsAt,DateTimeOffset? ExpiresAt,bool ShowResult,bool AllowRepeat); public record CreateLinkInput(string OrgSlug,DateTimeOffset? ExpiresAt);
[ApiController,Authorize,Route("survey-links")] public sealed class SurveyLinksController(ISurveyLinkRepository repo,IAuditService audit):ApiBase{ [HttpPatch("{linkId:guid}/status")] public async Task<IActionResult> Status(Guid linkId,StatusInput i){await repo.SetStatusAsync(linkId,i.Status,Current()); await audit.RecordAsync(Current().OrganizationId,Current().Id,"survey_link_status_changed","survey_link",linkId,Cid,new{i.Status}); return Ok(new{ok=true,linkId,status=i.Status});}}
[ApiController,Route("public")] public sealed class PublicSurveysController(ISurveyRepository surveys,IFormRepository forms,ISurveyLinkRepository links,IResponseRepository responses,SurveyResultCalculator calc,ITokenHasher tokens,IAuditService audit):ControllerBase{
 string Cid=>HttpContext.Items["CorrelationId"]?.ToString()??"";
 [HttpGet("surveys/validate")] public async Task<IActionResult> Validate(Guid surveyId,string token,string org){var link=await links.FindValidAsync(surveyId,org,token); if(link==null)return Unauthorized(new{ok=false,code="INVALID_PUBLIC_LINK",message="Link inválido ou expirado.",correlationId=Cid}); var s=await surveys.GetAsync(surveyId); if(s==null)return NotFound(); var f=await forms.GetPublicAsync(s.FormId,s.OrganizationId); if(f==null)return NotFound(); var pub=new PublicSurveyDto(s.Id,s.Title,s.Description,s.ShowResult,f.Questions.Select(q=>new PublicQuestionDto(q.Id,q.Text,q.Type,q.Position,q.Required,q.Options)).ToList()); await audit.RecordAsync(s.OrganizationId,null,"public_survey_validated","survey",surveyId,Cid,new{org}); return Ok(new PublicSurveyValidationDto(true,surveyId,org,pub));}
 [HttpPost("surveys/{surveyId:guid}/responses")] public async Task<IActionResult> Respond(Guid surveyId,SubmitSurveyResponseRequest r){var link=await links.FindValidAsync(surveyId,r.Org,r.Token); if(link==null)return Unauthorized(new{ok=false,code="INVALID_PUBLIC_LINK",message="Link inválido ou expirado.",correlationId=Cid}); var s=await surveys.GetAsync(surveyId); if(s==null)return NotFound(); var f=await forms.GetPublicAsync(s.FormId,s.OrganizationId)??throw new ArgumentException("Formulário não encontrado."); foreach(var q in f.Questions.Where(q=>q.Required)) if(!r.Answers.Any(a=>a.QuestionId==q.Id && (!string.IsNullOrWhiteSpace(a.AnswerValue)||!string.IsNullOrWhiteSpace(a.AnswerText)))) throw new ArgumentException($"Pergunta obrigatória sem resposta: {q.Text}"); var responseId=Guid.NewGuid(); var answers=r.Answers.Select(a=>new ResponseAnswer(Guid.NewGuid(),responseId,a.QuestionId,a.AnswerValue,a.AnswerText)).ToList(); var domainQuestions=f.Questions.Select(q=>new Question(q.Id,f.Id,q.Text,q.Type,q.Position,q.Required,q.Weight,q.MaxScore,q.Options.Select(o=>new QuestionOption(o.Id,q.Id,o.Text,o.Score,o.Position)).ToList())); var score=calc.Calculate(responseId,domainQuestions,answers); var resultToken=tokens.NewToken(); var resp=new SurveyResponse(responseId,s.OrganizationId,surveyId,s.FormId,r.ParticipantName,r.ParticipantEmail,"completed",DateTimeOffset.UtcNow,tokens.Hash(resultToken),DateTimeOffset.UtcNow,answers); var saved=await responses.CreateAsync(resp,score,resultToken); await audit.RecordAsync(s.OrganizationId,null,"public_response_created","response",responseId,Cid,new{surveyId}); return Ok(saved);}}
[ApiController,Route("public/results")] public sealed class PublicResultsController(IResponseRepository repo,IAuditService audit):ControllerBase{ [HttpGet("{responseId:guid}")] public async Task<IActionResult> Result(Guid responseId,string token){var r=await repo.GetResultAsync(responseId,token); if(r==null)return Unauthorized(new{ok=false,code="INVALID_RESULT_TOKEN",message="Token de resultado inválido.",correlationId=HttpContext.Items["CorrelationId"]}); await audit.RecordAsync(null,null,"public_result_viewed","response",responseId,HttpContext.Items["CorrelationId"]?.ToString()??"",new{responseId}); return Ok(r);}}
[ApiController,Authorize,Route("audit")] public sealed class AuditController(IAuditService audit):ApiBase{ [HttpGet("events")] public Task<IReadOnlyList<AuditEventDto>> Events()=>audit.ListAsync(Current()); }
[ApiController,Authorize,Route("responses")] public sealed class ResponsesController(IResponseRepository repo):ApiBase{ [HttpGet] public Task<IReadOnlyList<ResponseDto>> List()=>repo.ListAsync(Current()); [HttpGet("{id:guid}")] public async Task<IActionResult> Get(Guid id)=>await repo.GetDetailAsync(id,Current()) is { } r?Ok(new{r.Id,r.OrganizationId,r.SurveyId,r.FormId,r.ParticipantName,r.ParticipantEmail,r.Status,r.CompletedAt,r.CreatedAt,r.Answers}):NotFound(); }
