using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ValoraPesquisa.Application.Contracts;
using ValoraPesquisa.Application.DTOs;
using ValoraPesquisa.Application.Services;
using ValoraPesquisa.Domain.Entities;
using ValoraPesquisa.Domain.Enums;

namespace ValoraPesquisa.Api.Controllers;
[ApiController,Route("public")] public sealed class PublicSurveysController(ISurveyRepository surveys,IFormRepository forms,ISurveyLinkRepository links,IResponseRepository responses,SurveyResultCalculator calc,ITokenHasher tokens,IAuditService audit):ControllerBase{
 string Cid=>HttpContext.Items["CorrelationId"]?.ToString()??"";
 [HttpGet("surveys/validate")] public async Task<IActionResult> Validate(Guid surveyId,string token,string org){var link=await links.FindValidAsync(surveyId,org,token); if(link==null)return Unauthorized(new{ok=false,code="INVALID_PUBLIC_LINK",message="Link inválido ou expirado.",correlationId=Cid}); var s=await surveys.GetAsync(surveyId); if(s==null)return NotFound(); var f=await forms.GetPublicAsync(s.FormId,s.OrganizationId); if(f==null)return NotFound(); var pub=new PublicSurveyDto(s.Id,s.Title,s.Description,s.ShowResult,f.Questions.Select(q=>new PublicQuestionDto(q.Id,q.Text,q.Type,q.Position,q.Required,q.Options)).ToList()); await audit.RecordAsync(s.OrganizationId,null,"public_survey_validated","survey",surveyId,Cid,new{org}); return Ok(new PublicSurveyValidationDto(true,surveyId,org,pub));}
 [HttpPost("surveys/{surveyId:guid}/responses")] public async Task<IActionResult> Respond(Guid surveyId,SubmitSurveyResponseRequest r){var link=await links.FindValidAsync(surveyId,r.Org,r.Token); if(link==null)return Unauthorized(new{ok=false,code="INVALID_PUBLIC_LINK",message="Link inválido ou expirado.",correlationId=Cid}); var s=await surveys.GetAsync(surveyId); if(s==null)return NotFound(); var f=await forms.GetPublicAsync(s.FormId,s.OrganizationId)??throw new ArgumentException("Formulário não encontrado."); foreach(var q in f.Questions.Where(q=>q.Required)) if(!r.Answers.Any(a=>a.QuestionId==q.Id && (!string.IsNullOrWhiteSpace(a.AnswerValue)||!string.IsNullOrWhiteSpace(a.AnswerText)))) throw new ArgumentException($"Pergunta obrigatória sem resposta: {q.Text}"); var responseId=Guid.NewGuid(); var answers=r.Answers.Select(a=>new ResponseAnswer(Guid.NewGuid(),responseId,a.QuestionId,a.AnswerValue,a.AnswerText)).ToList(); var domainQuestions=f.Questions.Select(q=>new Question(q.Id,f.Id,q.Text,q.Type,q.Position,q.Required,q.Weight,q.MaxScore,q.Options.Select(o=>new QuestionOption(o.Id,q.Id,o.Text,o.Score,o.Position)).ToList())); var score=calc.Calculate(responseId,domainQuestions,answers); var resultToken=tokens.NewToken(); var resp=new SurveyResponse(responseId,s.OrganizationId,surveyId,s.FormId,r.ParticipantName,r.ParticipantEmail,"completed",DateTimeOffset.UtcNow,tokens.Hash(resultToken),DateTimeOffset.UtcNow,answers); var saved=await responses.CreateAsync(resp,score,resultToken); await audit.RecordAsync(s.OrganizationId,null,"public_response_created","response",responseId,Cid,new{surveyId}); return Ok(saved);}}
