namespace ValoraPesquisa.Domain.Entities;
public record Organization(Guid Id,string Name,string PublicName,string Slug,string? Document,string Email,string? Phone,string Status,string PlanCode,DateTimeOffset CreatedAt,DateTimeOffset? UpdatedAt,Guid? CreatedBy,Guid? UpdatedBy,bool IsDeleted);
public record User(Guid Id,Guid? OrganizationId,string Name,string Email,string PasswordHash,string Role,string Status,string? Phone,DateTimeOffset? LastLoginAt,DateTimeOffset CreatedAt,DateTimeOffset? UpdatedAt,bool IsDeleted);
public record Form(Guid Id,Guid OrganizationId,string Title,string? Description,string Status,DateTimeOffset CreatedAt,DateTimeOffset? UpdatedAt,bool IsDeleted,List<Question> Questions);
public record Question(Guid Id,Guid FormId,string Text,string Type,int Position,bool Required,decimal Weight,decimal MaxScore,List<QuestionOption> Options);
public record QuestionOption(Guid Id,Guid QuestionId,string Text,decimal Score,int Position);
public record Survey(Guid Id,Guid OrganizationId,Guid FormId,string Title,string? Description,string Status,DateTimeOffset? StartsAt,DateTimeOffset? ExpiresAt,bool ShowResult,bool AllowRepeat,DateTimeOffset CreatedAt,DateTimeOffset? UpdatedAt,bool IsDeleted);
public record SurveyLink(Guid Id,Guid SurveyId,Guid OrganizationId,string TokenHash,string PublicUrl,string Status,DateTimeOffset? ExpiresAt,DateTimeOffset? RevokedAt,DateTimeOffset CreatedAt,DateTimeOffset? UpdatedAt);
public record SurveyResponse(Guid Id,Guid OrganizationId,Guid SurveyId,Guid FormId,string? ParticipantName,string? ParticipantEmail,string Status,DateTimeOffset CompletedAt,string ResultTokenHash,DateTimeOffset CreatedAt,List<ResponseAnswer> Answers);
public record ResponseAnswer(Guid Id,Guid ResponseId,Guid QuestionId,string? AnswerValue,string? AnswerText);
public record ResultScore(Guid Id,Guid ResponseId,decimal TotalScore,decimal MaxScore,decimal Percentage,decimal Normalized5,string Level,string ResultJson,DateTimeOffset CreatedAt);
public record AuditLog(Guid Id,Guid? OrganizationId,Guid? UserId,string Action,string Entity,Guid? EntityId,string CorrelationId,string Metadata,DateTimeOffset CreatedAt);
