namespace ValoraPesquisa.Domain.Entities;
public record Organization(Guid Id,string Name,string PublicName,string Slug,string? Document,string Email,string? Phone,string Status,string PlanCode,DateTimeOffset CreatedAt,DateTimeOffset? UpdatedAt,Guid? CreatedBy,Guid? UpdatedBy,bool IsDeleted);
public record User(Guid Id,Guid? OrganizationId,string Name,string Email,string PasswordHash,string Role,string Status,string? Phone,DateTimeOffset? LastLoginAt,DateTimeOffset CreatedAt,DateTimeOffset? UpdatedAt,bool IsDeleted);
public record Form(Guid Id,Guid OrganizationId,string Title,string? Description,string Status,DateTimeOffset CreatedAt,DateTimeOffset? UpdatedAt,bool IsDeleted,List<Question> Questions);
public record Question(Guid Id,Guid FormId,string Text,string Type,int Position,bool Required,decimal Weight,decimal MaxScore,List<QuestionOption> Options);
public record QuestionOption(Guid Id,Guid QuestionId,string Text,decimal Score,int Position);
public record Survey(Guid Id,Guid OrganizationId,Guid FormId,string Title,string? Description,string Status,DateTimeOffset? StartsAt,DateTimeOffset? ExpiresAt,bool ShowResult,bool AllowRepeat,DateTimeOffset CreatedAt,DateTimeOffset? UpdatedAt,bool IsDeleted);
public record SurveyLink(Guid Id,Guid SurveyId,Guid OrganizationId,string TokenHash,string PublicUrl,string Status,DateTimeOffset? ExpiresAt,DateTimeOffset? RevokedAt,DateTimeOffset CreatedAt,DateTimeOffset? UpdatedAt);
public record SurveyResponse(Guid Id,Guid OrganizationId,Guid SurveyId,Guid FormId,string? ParticipantName,string? ParticipantEmail,string Status,DateTimeOffset CompletedAt,string ResultTokenHash,DateTimeOffset CreatedAt,List<ResponseAnswer> Answers);
public record ResponseAnswer(Guid Id,Guid ResponseId,Guid QuestionId,string? AnswerValue,string? AnswerText);
public record ResultScore(Guid Id,Guid ResponseId,decimal TotalScore,decimal MaxScore,decimal Percentage,decimal Normalized5,string Level,string ResultJson,DateTimeOffset CreatedAt);
public record AuditLog(Guid Id,Guid? OrganizationId,Guid? UserId,string Action,string Entity,Guid? EntityId,string CorrelationId,string Metadata,DateTimeOffset CreatedAt);
public record Plan(Guid Id,string Code,string Name,string? Description,decimal MonthlyPrice,decimal AnnualPrice,string Status,int DisplayOrder,DateTimeOffset CreatedAt,DateTimeOffset? UpdatedAt,bool IsDeleted);
public record PlanLimit(Guid Id,Guid PlanId,int ActiveSurveys,int ResponsesPerMonth,int Users,int Managers,int Forms,int PublicLinks,int EmailInvitesPerMonth,int StorageMb,DateTimeOffset CreatedAt,DateTimeOffset? UpdatedAt);
public record PlanCapability(Guid Id,Guid PlanId,string CapabilityCode,bool Enabled);
public record Module(Guid Id,string Code,string Name,string? Description,string Category,string Status,int DisplayOrder,string? MinimumPlanCode,DateTimeOffset CreatedAt,DateTimeOffset? UpdatedAt,bool IsDeleted);
public record OrganizationModule(Guid Id,Guid OrganizationId,Guid ModuleId,bool Enabled,string Source,DateTimeOffset CreatedAt,DateTimeOffset? UpdatedAt);
public record Subscription(Guid Id,Guid OrganizationId,Guid PlanId,string Status,string BillingStatus,DateTimeOffset StartsAt,DateTimeOffset? ExpiresAt,DateTimeOffset? TrialEndsAt,DateTimeOffset? CancelledAt,DateTimeOffset CreatedAt,DateTimeOffset? UpdatedAt);
public record UsageMonthly(Guid Id,Guid OrganizationId,DateTime Month,int ActiveSurveysCount,int ResponsesCount,int UsersCount,int ManagersCount,int FormsCount,int PublicLinksCount,int EmailInvitesCount,int StorageMbUsed,DateTimeOffset UpdatedAt);
