BEGIN;

-- Valora Methodology Studio™: catálogo oficial versionado e governado.
ALTER TABLE valorapesquisa.methodology_versions ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE valorapesquisa.methodology_versions ADD COLUMN IF NOT EXISTS version_number integer;
ALTER TABLE valorapesquisa.methodology_versions ADD COLUMN IF NOT EXISTS is_official boolean NOT NULL DEFAULT false;
ALTER TABLE valorapesquisa.methodology_versions ADD COLUMN IF NOT EXISTS published_by_user_id uuid;
ALTER TABLE valorapesquisa.methodology_versions ADD COLUMN IF NOT EXISTS metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE valorapesquisa.methodology_versions ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE valorapesquisa.methodology_versions ADD COLUMN IF NOT EXISTS deleted_at timestamptz;
UPDATE valorapesquisa.methodology_versions SET version_number=COALESCE(version_number,version,1),status=CASE status WHEN 'active' THEN 'published' WHEN 'retired' THEN 'archived' ELSE status END;
ALTER TABLE valorapesquisa.methodology_versions ALTER COLUMN version_number SET NOT NULL;
ALTER TABLE valorapesquisa.methodology_versions ALTER COLUMN effective_from DROP NOT NULL;
ALTER TABLE valorapesquisa.methodology_versions DROP CONSTRAINT IF EXISTS methodology_versions_status_check;
ALTER TABLE valorapesquisa.methodology_versions ADD CONSTRAINT methodology_versions_status_check CHECK(status IN('draft','published','archived')) NOT VALID;

CREATE TABLE IF NOT EXISTS valorapesquisa.methodology_publications(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),methodology_version_id uuid NOT NULL REFERENCES valorapesquisa.methodology_versions(id),publication_number integer NOT NULL,published_at timestamptz NOT NULL DEFAULT now(),published_by_user_id uuid,justification text NOT NULL,snapshot_json jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(methodology_version_id,publication_number));
ALTER TABLE valorapesquisa.methodology_concepts ADD COLUMN IF NOT EXISTS description text NOT NULL DEFAULT '';
ALTER TABLE valorapesquisa.methodology_concepts ADD COLUMN IF NOT EXISTS methodology_version_id uuid REFERENCES valorapesquisa.methodology_versions(id);
ALTER TABLE valorapesquisa.methodology_concepts ADD COLUMN IF NOT EXISTS concept_type varchar(40) NOT NULL DEFAULT 'organizational';
ALTER TABLE valorapesquisa.methodology_concepts ADD COLUMN IF NOT EXISTS parent_concept_id uuid REFERENCES valorapesquisa.methodology_concepts(id);
ALTER TABLE valorapesquisa.methodology_concepts ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;
ALTER TABLE valorapesquisa.methodology_concepts ADD COLUMN IF NOT EXISTS metadata_json jsonb NOT NULL DEFAULT '{}';
CREATE TABLE IF NOT EXISTS valorapesquisa.methodology_concept_relationships(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),methodology_version_id uuid NOT NULL REFERENCES valorapesquisa.methodology_versions(id),source_concept_id uuid NOT NULL REFERENCES valorapesquisa.methodology_concepts(id),target_concept_id uuid NOT NULL REFERENCES valorapesquisa.methodology_concepts(id),relationship_type varchar(50) NOT NULL,influence_weight numeric(6,4) NOT NULL DEFAULT 1 CHECK(influence_weight>0),rationale text NOT NULL,metadata_json jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz,UNIQUE(methodology_version_id,source_concept_id,target_concept_id,relationship_type));
CREATE TABLE IF NOT EXISTS valorapesquisa.methodology_dimensions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),methodology_version_id uuid NOT NULL REFERENCES valorapesquisa.methodology_versions(id),code varchar(80) NOT NULL,name varchar(160) NOT NULL,description text NOT NULL,default_weight numeric(8,4) NOT NULL DEFAULT 1 CHECK(default_weight>0),status varchar(20) NOT NULL DEFAULT 'active',metadata_json jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz,UNIQUE(methodology_version_id,code));
CREATE TABLE IF NOT EXISTS valorapesquisa.methodology_indices(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),methodology_version_id uuid NOT NULL REFERENCES valorapesquisa.methodology_versions(id),code varchar(20) NOT NULL,name varchar(180) NOT NULL,description text NOT NULL,scale_min numeric(8,2) NOT NULL DEFAULT 0,scale_max numeric(8,2) NOT NULL DEFAULT 100,level_1_label varchar(60) NOT NULL,level_1_min numeric(8,2) NOT NULL,level_1_max numeric(8,2) NOT NULL,level_2_label varchar(60) NOT NULL,level_2_min numeric(8,2) NOT NULL,level_2_max numeric(8,2) NOT NULL,level_3_label varchar(60) NOT NULL,level_3_min numeric(8,2) NOT NULL,level_3_max numeric(8,2) NOT NULL,level_4_label varchar(60) NOT NULL,level_4_min numeric(8,2) NOT NULL,level_4_max numeric(8,2) NOT NULL,calculation_strategy varchar(80) NOT NULL,metadata_json jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz,UNIQUE(methodology_version_id,code),CHECK(scale_max>scale_min));
CREATE TABLE IF NOT EXISTS valorapesquisa.methodology_index_rules(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),methodology_index_id uuid NOT NULL REFERENCES valorapesquisa.methodology_indices(id),code varchar(80) NOT NULL,rule_type varchar(40) NOT NULL,rule_json jsonb NOT NULL,weight numeric(8,4) NOT NULL DEFAULT 1 CHECK(weight>0),purpose text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz,UNIQUE(methodology_index_id,code));
CREATE TABLE IF NOT EXISTS valorapesquisa.methodology_question_bank(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),methodology_version_id uuid NOT NULL REFERENCES valorapesquisa.methodology_versions(id),code varchar(100) NOT NULL,question_text text NOT NULL,description text NOT NULL DEFAULT '',question_type varchar(40) NOT NULL,answer_scale jsonb NOT NULL DEFAULT '{}',default_weight numeric(8,4) NOT NULL DEFAULT 1 CHECK(default_weight>0),is_required boolean NOT NULL DEFAULT true,is_official boolean NOT NULL DEFAULT true,status varchar(20) NOT NULL DEFAULT 'active',metadata_json jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz,UNIQUE(methodology_version_id,code));
CREATE TABLE IF NOT EXISTS valorapesquisa.methodology_question_mappings(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),methodology_version_id uuid NOT NULL REFERENCES valorapesquisa.methodology_versions(id),question_id uuid NOT NULL REFERENCES valorapesquisa.methodology_question_bank(id),concept_id uuid REFERENCES valorapesquisa.methodology_concepts(id),dimension_id uuid REFERENCES valorapesquisa.methodology_dimensions(id),index_id uuid REFERENCES valorapesquisa.methodology_indices(id),weight numeric(8,4) NOT NULL DEFAULT 1 CHECK(weight>0),mapping_type varchar(30) NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz,CHECK(concept_id IS NOT NULL OR dimension_id IS NOT NULL OR index_id IS NOT NULL));
CREATE TABLE IF NOT EXISTS valorapesquisa.methodology_inference_rules(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),methodology_version_id uuid NOT NULL REFERENCES valorapesquisa.methodology_versions(id),code varchar(100) NOT NULL,name varchar(160) NOT NULL,origin text NOT NULL,purpose text NOT NULL,condition_json jsonb NOT NULL,result_json jsonb NOT NULL,minimum_evidence integer NOT NULL DEFAULT 1 CHECK(minimum_evidence>0),status varchar(20) NOT NULL DEFAULT 'active',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz,UNIQUE(methodology_version_id,code));
CREATE TABLE IF NOT EXISTS valorapesquisa.methodology_output_schemas(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),methodology_version_id uuid NOT NULL REFERENCES valorapesquisa.methodology_versions(id),code varchar(100) NOT NULL,name varchar(160) NOT NULL,schema_json jsonb NOT NULL,status varchar(20) NOT NULL DEFAULT 'active',version_number integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz,UNIQUE(methodology_version_id,code,version_number));
CREATE TABLE IF NOT EXISTS valorapesquisa.methodology_guardrails(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),methodology_version_id uuid NOT NULL REFERENCES valorapesquisa.methodology_versions(id),code varchar(100) NOT NULL,name varchar(160) NOT NULL,description text NOT NULL,severity varchar(20) NOT NULL DEFAULT 'blocking',rule_json jsonb NOT NULL DEFAULT '{}',is_active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz,UNIQUE(methodology_version_id,code));
CREATE TABLE IF NOT EXISTS valorapesquisa.methodology_prompt_templates(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),methodology_version_id uuid NOT NULL REFERENCES valorapesquisa.methodology_versions(id),code varchar(100) NOT NULL,name varchar(160) NOT NULL,purpose text NOT NULL,system_prompt text NOT NULL,user_prompt_template text NOT NULL,output_schema_code varchar(100) NOT NULL,guardrail_code varchar(100) NOT NULL,status varchar(20) NOT NULL DEFAULT 'active',version_number integer NOT NULL DEFAULT 1,metadata_json jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz,UNIQUE(methodology_version_id,code,version_number));
CREATE TABLE IF NOT EXISTS valorapesquisa.methodology_report_templates(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),methodology_version_id uuid NOT NULL REFERENCES valorapesquisa.methodology_versions(id),code varchar(100) NOT NULL,name varchar(160) NOT NULL,purpose text NOT NULL,template text NOT NULL,output_schema_code varchar(100) NOT NULL,status varchar(20) NOT NULL DEFAULT 'active',version_number integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz,UNIQUE(methodology_version_id,code,version_number));
CREATE TABLE IF NOT EXISTS valorapesquisa.methodology_change_log(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),methodology_version_id uuid NOT NULL REFERENCES valorapesquisa.methodology_versions(id),entity_type varchar(80) NOT NULL,entity_id uuid,operation varchar(30) NOT NULL,before_json jsonb,after_json jsonb,justification text NOT NULL,changed_by_user_id uuid,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS valorapesquisa.organization_methodology_settings(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES valorapesquisa.organizations(id),methodology_version_id uuid NOT NULL REFERENCES valorapesquisa.methodology_versions(id),allowed_settings_json jsonb NOT NULL DEFAULT '{}',is_active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz,UNIQUE(organization_id,methodology_version_id));
DO $diagnostic_methodology$ BEGIN IF to_regclass('valorapesquisa.surveys') IS NOT NULL THEN ALTER TABLE valorapesquisa.surveys ADD COLUMN IF NOT EXISTS question_version integer NOT NULL DEFAULT 1; ALTER TABLE valorapesquisa.surveys ADD COLUMN IF NOT EXISTS scoring_strategy varchar(80) NOT NULL DEFAULT 'weighted_average_v1'; ALTER TABLE valorapesquisa.surveys ADD COLUMN IF NOT EXISTS prompt_template_version integer NOT NULL DEFAULT 1; END IF; END $diagnostic_methodology$;
CREATE INDEX IF NOT EXISTS ix_methodology_versions_official ON valorapesquisa.methodology_versions(is_official,status) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS ix_methodology_questions_version ON valorapesquisa.methodology_question_bank(methodology_version_id,status) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS ix_methodology_mappings_question ON valorapesquisa.methodology_question_mappings(question_id) WHERE deleted_at IS NULL;

CREATE OR REPLACE FUNCTION valorapesquisa.validate_methodology_version(p_version_id uuid) RETURNS TABLE(code text,severity text,entity text,message text) LANGUAGE sql STABLE AS $$
 SELECT 'QUESTION_WITHOUT_CONCEPT','critical','question',q.code||' não possui conceito.' FROM valorapesquisa.methodology_question_bank q WHERE q.methodology_version_id=p_version_id AND q.is_official AND q.deleted_at IS NULL AND NOT EXISTS(SELECT 1 FROM valorapesquisa.methodology_question_mappings m WHERE m.question_id=q.id AND m.concept_id IS NOT NULL AND m.deleted_at IS NULL)
 UNION ALL SELECT 'QUESTION_WITHOUT_INDEX_OR_DIMENSION','critical','question',q.code||' não possui índice ou dimensão.' FROM valorapesquisa.methodology_question_bank q WHERE q.methodology_version_id=p_version_id AND q.is_official AND q.deleted_at IS NULL AND NOT EXISTS(SELECT 1 FROM valorapesquisa.methodology_question_mappings m WHERE m.question_id=q.id AND (m.index_id IS NOT NULL OR m.dimension_id IS NOT NULL) AND m.deleted_at IS NULL)
 UNION ALL SELECT 'INVALID_WEIGHT','critical','question',q.code||' possui peso inválido.' FROM valorapesquisa.methodology_question_bank q WHERE q.methodology_version_id=p_version_id AND q.deleted_at IS NULL AND q.default_weight<=0
 UNION ALL SELECT 'INDEX_WITHOUT_LEVELS','critical','index',i.code||' possui faixas inválidas.' FROM valorapesquisa.methodology_indices i WHERE i.methodology_version_id=p_version_id AND i.deleted_at IS NULL AND NOT(i.level_1_min<=i.level_1_max AND i.level_2_min<=i.level_2_max AND i.level_3_min<=i.level_3_max AND i.level_4_min<=i.level_4_max)
 UNION ALL SELECT 'PROMPT_WITHOUT_GUARDRAIL','critical','prompt',p.code||' não possui guardrail válido.' FROM valorapesquisa.methodology_prompt_templates p WHERE p.methodology_version_id=p_version_id AND p.deleted_at IS NULL AND NOT EXISTS(SELECT 1 FROM valorapesquisa.methodology_guardrails g WHERE g.methodology_version_id=p.methodology_version_id AND g.code=p.guardrail_code AND g.is_active AND g.deleted_at IS NULL)
 UNION ALL SELECT 'PROMPT_WITHOUT_SCHEMA','critical','prompt',p.code||' não possui schema válido.' FROM valorapesquisa.methodology_prompt_templates p WHERE p.methodology_version_id=p_version_id AND p.deleted_at IS NULL AND NOT EXISTS(SELECT 1 FROM valorapesquisa.methodology_output_schemas s WHERE s.methodology_version_id=p.methodology_version_id AND s.code=p.output_schema_code AND s.deleted_at IS NULL)
 UNION ALL SELECT 'INFERENCE_WITHOUT_PROVENANCE','critical','inference',r.code||' não informa origem e finalidade.' FROM valorapesquisa.methodology_inference_rules r WHERE r.methodology_version_id=p_version_id AND r.deleted_at IS NULL AND (btrim(r.origin)='' OR btrim(r.purpose)='') $$;
CREATE OR REPLACE FUNCTION valorapesquisa.publish_methodology_version(p_version_id uuid,p_actor_id uuid,p_justification text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN
 IF EXISTS(SELECT 1 FROM valorapesquisa.validate_methodology_version(p_version_id) WHERE severity='critical') THEN RAISE EXCEPTION 'Versão metodológica inconsistente'; END IF;
 IF NOT EXISTS(SELECT 1 FROM valorapesquisa.methodology_versions WHERE id=p_version_id AND status='draft' AND deleted_at IS NULL) THEN RAISE EXCEPTION 'Somente versões draft podem ser publicadas'; END IF;
 UPDATE valorapesquisa.methodology_versions SET status='archived',is_official=false,updated_at=now() WHERE is_official AND status='published' AND id<>p_version_id;
 UPDATE valorapesquisa.methodology_versions SET status='published',is_official=true,published_at=now(),published_by_user_id=p_actor_id,updated_at=now() WHERE id=p_version_id;
 INSERT INTO valorapesquisa.methodology_publications(methodology_version_id,publication_number,published_by_user_id,justification,snapshot_json) SELECT id,COALESCE((SELECT max(publication_number)+1 FROM valorapesquisa.methodology_publications WHERE methodology_version_id=p_version_id),1),p_actor_id,p_justification,metadata_json FROM valorapesquisa.methodology_versions WHERE id=p_version_id;
 INSERT INTO valorapesquisa.methodology_change_log(methodology_version_id,entity_type,entity_id,operation,after_json,justification,changed_by_user_id) VALUES(p_version_id,'version',p_version_id,'publish',jsonb_build_object('status','published'),p_justification,p_actor_id); END $$;

-- Base oficial inicial: índices, conceitos, perguntas mapeadas, guardrails, schemas e prompts.
UPDATE valorapesquisa.methodology_versions SET is_official=true,status='published',description=COALESCE(description,'Metodologia oficial Valora Group.'),metadata_json=metadata_json||'{"owner":"Valora Group","immutable":true}'::jsonb WHERE code='VALORA-2026.1';
WITH v AS(SELECT id FROM valorapesquisa.methodology_versions WHERE code='VALORA-2026.1'), x(code,name) AS(VALUES ('IMO','Índice de Maturidade Organizacional'),('ICS','Índice de Clareza Sistêmica'),('IIO','Índice de Inteligência Organizacional'),('IGO','Índice de Governança Organizacional'),('ICO','Índice de Cultura Organizacional'),('ILI','Índice de Liderança'),('IPO','Índice de Pessoas'),('IDO','Índice de Desenvolvimento Organizacional'),('IAC','Índice de Accountability'),('IAR','Índice de Autonomia Responsável'),('IIS','Índice de Integração Sistêmica'),('ISO','Índice de Sustentabilidade Organizacional')) INSERT INTO valorapesquisa.methodology_indices(methodology_version_id,code,name,description,level_1_label,level_1_min,level_1_max,level_2_label,level_2_min,level_2_max,level_3_label,level_3_min,level_3_max,level_4_label,level_4_min,level_4_max,calculation_strategy) SELECT v.id,x.code,x.name,'Índice oficial Valora™, calculado exclusivamente por evidências versionadas.','Inicial',0,25,'Estruturante',26,50,'Integrado',51,75,'Maduro',76,100,'weighted_evidence_v1' FROM v CROSS JOIN x ON CONFLICT(methodology_version_id,code) DO UPDATE SET name=excluded.name,updated_at=now();
WITH v AS(SELECT id FROM valorapesquisa.methodology_versions WHERE code='VALORA-2026.1'), x(code,name) AS(VALUES ('clarity','Clareza'),('governance','Governança'),('leadership','Liderança'),('culture','Cultura'),('people','Pessoas'),('systems','Sistemas'),('organizational_intelligence','Inteligência organizacional'),('organizational_development','Desenvolvimento organizacional'),('sustainability','Sustentabilidade'),('accountability','Accountability'),('responsible_autonomy','Autonomia responsável'),('systemic_integration','Integração sistêmica'),('organizational_learning','Aprendizagem organizacional'),('decision_making','Tomada de decisão'),('key_person_dependency','Dependência de pessoas específicas'),('organizational_maturity','Maturidade organizacional')) INSERT INTO valorapesquisa.methodology_concepts(methodology_version_id,code,name,definition,description,pillar,strategic_purpose,evolution_guidance,methodology_version,status,version,display_order) SELECT v.id,x.code,x.name,'Conceito canônico da metodologia Valora™.','Conceito canônico da metodologia Valora™.','Metodologia Oficial','Orientar diagnóstico sistêmico baseado em evidências.','Evoluir por ciclos verificáveis.','VALORA-2026.1','active',1,row_number() over() FROM v CROSS JOIN x ON CONFLICT(code) DO UPDATE SET methodology_version_id=excluded.methodology_version_id,name=excluded.name,updated_at=now();
WITH v AS(SELECT id FROM valorapesquisa.methodology_versions WHERE code='VALORA-2026.1'), x(code,name,description) AS(VALUES ('no_fabrication','Não inventar dados','Nunca completar lacunas com fatos inventados.'),('evidence_required','Não interpretar sem evidência','Toda interpretação deve apontar evidências.'),('comparison_basis','Não comparar sem base','Comparações exigem base compatível.'),('no_blame','Não culpar pessoas','Interpretar o sistema, não buscar culpados.'),('no_moral_judgment','Não emitir julgamento moral','Evitar julgamento moral ou individual.'),('human_decision','Não substituir decisão humana','Recomendações apoiam decisão humana.'),('insufficient_evidence','Indicar limitação','Declarar evidência insuficiente.'),('systemic_logic','Preservar lógica sistêmica','Manter contexto e relações sistêmicas.'),('privacy','Preservar privacidade','Não expor dados individuais indevidos.')) INSERT INTO valorapesquisa.methodology_guardrails(methodology_version_id,code,name,description,rule_json) SELECT v.id,x.code,x.name,x.description,jsonb_build_object('required',true) FROM v CROSS JOIN x ON CONFLICT(methodology_version_id,code) DO UPDATE SET description=excluded.description,updated_at=now();
WITH v AS(SELECT id FROM valorapesquisa.methodology_versions WHERE code='VALORA-2026.1') INSERT INTO valorapesquisa.methodology_output_schemas(methodology_version_id,code,name,schema_json) SELECT id,'insight_v1','Insight Valora v1','{"type":"object","required":["evidence","limitations","recommendations"]}' FROM v ON CONFLICT(methodology_version_id,code,version_number) DO NOTHING;
WITH v AS(SELECT id FROM valorapesquisa.methodology_versions WHERE code='VALORA-2026.1'), x(code,name,purpose) AS(VALUES ('diagnostic','Diagnóstico','Interpretar diagnóstico'),('evidence','Evidências','Consolidar evidence pack'),('insights','Insights','Gerar insights'),('executive_report','Relatório executivo','Gerar síntese executiva'),('action_plan','Plano de ação','Propor evolução'),('benchmark','Benchmark','Comparar bases compatíveis'),('heatmap','Heatmap','Explicar concentrações'),('one_on_one','One-on-One','Apoiar conversa humana')) INSERT INTO valorapesquisa.methodology_prompt_templates(methodology_version_id,code,name,purpose,system_prompt,user_prompt_template,output_schema_code,guardrail_code) SELECT v.id,x.code,x.name,x.purpose,'Você é a IA Valora. Use somente evidências fornecidas e preserve a lógica sistêmica.','Analise {{evidence_pack}} conforme {{methodology_version}}.','insight_v1','evidence_required' FROM v CROSS JOIN x ON CONFLICT(methodology_version_id,code,version_number) DO UPDATE SET system_prompt=excluded.system_prompt,updated_at=now();
WITH v AS(SELECT id FROM valorapesquisa.methodology_versions WHERE code='VALORA-2026.1'), pairs(concept,index_code) AS(VALUES ('clarity','ICS'),('governance','IGO'),('leadership','ILI'),('culture','ICO'),('people','IPO'),('systems','IIS'),('organizational_intelligence','IIO'),('organizational_development','IDO'),('sustainability','ISO'),('accountability','IAC'),('responsible_autonomy','IAR'),('systemic_integration','IIS'),('organizational_learning','IIO'),('decision_making','IGO'),('key_person_dependency','IMO'),('organizational_maturity','IMO')), ins AS(INSERT INTO valorapesquisa.methodology_question_bank(methodology_version_id,code,question_text,description,question_type,answer_scale) SELECT v.id,'OFFICIAL_'||upper(p.concept),'Em que medida '||lower(c.name)||' é uma prática observável, recorrente e revisada com evidências?','Pergunta basal oficial vinculada ao mapa cognitivo.','scale_1_5','{"min":1,"max":5}' FROM v JOIN pairs p ON true JOIN valorapesquisa.methodology_concepts c ON c.code=p.concept ON CONFLICT(methodology_version_id,code) DO UPDATE SET question_text=excluded.question_text RETURNING id,methodology_version_id,code) INSERT INTO valorapesquisa.methodology_question_mappings(methodology_version_id,question_id,concept_id,index_id,weight,mapping_type) SELECT q.methodology_version_id,q.id,c.id,i.id,1,'primary' FROM ins q JOIN pairs p ON q.code='OFFICIAL_'||upper(p.concept) JOIN valorapesquisa.methodology_concepts c ON c.code=p.concept JOIN valorapesquisa.methodology_indices i ON i.methodology_version_id=q.methodology_version_id AND i.code=p.index_code WHERE NOT EXISTS(SELECT 1 FROM valorapesquisa.methodology_question_mappings m WHERE m.question_id=q.id AND m.concept_id=c.id AND m.index_id=i.id AND m.deleted_at IS NULL);

INSERT INTO valorapesquisa.permissions(code,name,description,module_code) VALUES
('methodology.publish','Publicar metodologia','Publica versão validada e imutável.','organizational_intelligence'),('methodology.clone','Clonar metodologia','Cria draft a partir de versão rastreável.','organizational_intelligence'),('methodology.validate','Validar metodologia','Executa consistência pré-publicação.','organizational_intelligence'),('methodology.concepts.read','Consultar conceitos metodológicos','Consulta dicionário oficial.','organizational_intelligence'),('methodology.concepts.manage','Gerenciar conceitos metodológicos','Gerencia conceitos em draft.','organizational_intelligence'),('methodology.indexes.read','Consultar índices metodológicos','Consulta índices oficiais.','organizational_intelligence'),('methodology.indexes.manage','Gerenciar índices metodológicos','Gerencia índices em draft.','organizational_intelligence'),('methodology.questions.read','Consultar perguntas metodológicas','Consulta banco oficial.','forms'),('methodology.questions.manage','Gerenciar perguntas metodológicas','Gerencia perguntas em draft.','forms'),('methodology.prompts.read','Consultar prompts metodológicos','Consulta prompts versionados.','organizational_intelligence'),('methodology.prompts.manage','Gerenciar prompts metodológicos','Gerencia prompts em draft.','organizational_intelligence'),('methodology.guardrails.read','Consultar guardrails','Consulta proteção metodológica.','organizational_intelligence'),('methodology.guardrails.manage','Gerenciar guardrails','Gerencia guardrails em draft.','organizational_intelligence') ON CONFLICT(code) DO UPDATE SET name=excluded.name,description=excluded.description,module_code=excluded.module_code,updated_at=now();
INSERT INTO valorapesquisa.role_permissions(role_id,permission_id,created_at) SELECT r.id,p.id,now() FROM valorapesquisa.roles r CROSS JOIN valorapesquisa.permissions p WHERE r.code='admin_valora' AND r.deleted_at IS NULL AND p.code LIKE 'methodology.%' ON CONFLICT(role_id,permission_id) DO NOTHING;

COMMIT;
