const { test, expect } = require('@playwright/test');
const fs = require('node:fs');
const path = require('node:path');
const script = fs.readFileSync(path.join(__dirname, '../../backend/Valora.Web/wwwroot/js/executive-workspace.js'), 'utf8');
const priority={id:'11111111-1111-1111-1111-111111111111',title:'Prioridade operacional',description:'Entrega',status:'active',priority:'high',progressPercent:25,updatedAt:'2026-09-10T10:00:00Z',itemType:'priority'};
function shell(mode){return `<!doctype html><html><body><main><input name="__RequestVerificationToken" value="t"><button id="new-priority">Nova</button><form id="priority-filters"><select name="status"><option value=""></option></select><select name="priority"><option value=""></option></select><select name="due"><option value=""></option></select></form><div id="workspace-feedback" tabindex="-1" hidden></div><section id="workspace-loading"></section><section id="workspace-content" hidden></section><section id="workspace-empty" hidden><h2></h2><p></p><button class="retry"></button></section><dialog id="priority-dialog"><form id="priority-form"><h2 id="priority-form-title"></h2><div class="form-errors" tabindex="-1" hidden></div><input name="id"><input name="expectedUpdatedAt"><label><input name="title" required><span class="field-error"></span></label><label><textarea name="description"></textarea><span class="field-error"></span></label><label><select name="priority"><option value="medium"></option></select><span class="field-error"></span></label><input name="ownerSearch"><label><select name="ownerUserId"><option value=""></option></select><span class="field-error"></span></label><input name="sourceSearch"><label><select name="source"><option value=""></option></select><span class="field-error"></span></label><label><input name="dueAt"><span class="field-error"></span></label><button class="dialog-close" type="button">Cancelar</button><button type="submit">Salvar</button></form></dialog><dialog id="priority-details"></dialog><dialog id="priority-command"><form id="priority-command-form"><h2 id="priority-command-title"></h2><p id="priority-command-consequence"></p><p class="priority-name"></p><div class="form-errors" tabindex="-1" hidden></div><label class="progress-field"><input name="progressPercent" type="number"><span class="field-error"></span></label><label><textarea name="note"></textarea><span class="field-error"></span></label><button class="command-close" type="button">Cancelar</button><button type="submit">Confirmar</button></form></dialog></main><script>window.valoraWorkspaceMode='${mode}'</script></body></html>`}
async function boot(page,mode,response,requests=[]){await page.route('**/bff/workspace/**',async route=>{requests.push(route.request().url());const url=route.request().url();if(url.includes('/priorities/'+priority.id))return route.fulfill({json:{priority,history:[],allowedActions:{canEdit:true,canUpdateProgress:true,canComplete:true,canCancel:true,canReopen:false}}});return route.fulfill({json:response})});await page.setContent(shell(mode));await page.addScriptTag({content:script})}
test('listagem específica usa o contrato explícito de prioridade e HTML semântico',async({page})=>{await boot(page,'priorities',{items:[priority],page:1,pageSize:20,total:1,hasMore:false});await expect(page.locator('li[data-kind="priority"]')).toHaveCount(1);await expect(page.locator('ul > div')).toHaveCount(0);await page.getByRole('button',{name:'Abrir detalhes'}).click();await expect(page.locator('#priority-details h2')).toHaveText(priority.title)});
test('Meu Dia distingue prioridade de outro recurso pelo itemType',async({page})=>{await boot(page,'my-day',[priority,{...priority,id:'22222222-2222-2222-2222-222222222222',itemType:'approval',title:'Aprovação',route:'/Approvals'}]);await expect(page.locator('[data-kind="priority"]')).toHaveCount(1);await expect(page.locator('[data-kind="resource"]')).toHaveCount(1)});
test('visão geral mantém prioridade, fixado, recente e ação com tipos distintos',async({page})=>{await boot(page,'overview',{myDay:[],priorities:[priority],pinned:[{...priority,itemType:'evidence',isPinned:true}],recent:[{...priority,itemType:'approval'}],quickActions:[{code:'create',label:'Criar ação',route:'/Create'}]});await expect(page.locator('[data-kind="priority"]')).toHaveCount(1);await expect(page.locator('[data-kind="resource"]')).toHaveCount(2);await expect(page.locator('[data-kind="action"]')).toHaveCount(1)});
test('cancelar diálogo operacional não envia comando',async({page})=>{const requests=[];await boot(page,'priorities',{items:[priority],page:1,pageSize:20,total:1,hasMore:false},requests);await page.getByRole('button',{name:'Abrir detalhes'}).click();await page.getByRole('button',{name:'Registrar progresso'}).click();const before=requests.length;await page.locator('#priority-command .command-close').first().click();expect(requests).toHaveLength(before)});
