@echo off
cd /d C:\DBBACK\valoregrouppesquisa
echo [1/50] Subindo ambiente local live...
call npm run local:live:up
if errorlevel 1 goto erro
echo [2/50] Aplicando migrations...
call npm run local:migrations:apply
if errorlevel 1 goto erro
echo [3/50] Build API...
call npm run backend:build
if errorlevel 1 goto erro
echo [4/50] Testes API...
call npm run backend:test
if errorlevel 1 goto erro
echo [5/50] Build Valora.Web...
call npm run web:build
if errorlevel 1 goto erro
echo [6/50] Projeto Valora.Web...
call npm run web:validate
if errorlevel 1 goto erro
echo [7/50] Sem binarios...
call npm run web:no-binaries
if errorlevel 1 goto erro
echo [8/50] Sem placeholders...
call npm run web:no-placeholders
if errorlevel 1 goto erro
echo [9/50] Formularios reais...
call npm run web:real-forms
if errorlevel 1 goto erro
echo [10/50] Uso real da API...
call npm run web:real-api-usage
if errorlevel 1 goto erro
echo [11/50] ResultToken seguro...
call npm run web:result-token-safety
if errorlevel 1 goto erro
echo [12/50] Certificado binario/fallback...
call npm run web:certificate-binary
if errorlevel 1 goto erro
echo [13/50] JQuery AJAX...
call npm run web:jquery
if errorlevel 1 goto erro
echo [14/50] Contrato API...
call npm run web:api-contract
if errorlevel 1 goto erro
echo [15/50] Telas...
call npm run web:screens
if errorlevel 1 goto erro
echo [16/50] Erros...
call npm run web:errors
if errorlevel 1 goto erro
echo [17/50] Mobile...
call npm run web:mobile
if errorlevel 1 goto erro
echo [18/50] CORS...
call npm run web:cors
if errorlevel 1 goto erro
echo [19/50] Docker Web...
call npm run web:docker
if errorlevel 1 goto erro
echo [20/50] Fluxo funcional Web...
call npm run web:functional-flow
if errorlevel 1 goto erro
echo [21/50] Health API...
call npm run backend:health
if errorlevel 1 goto erro
echo [22/50] API E2E...
call npm run api:e2e
if errorlevel 1 goto erro
echo [23/50] SaaS E2E...
call npm run prod:saas-e2e
if errorlevel 1 goto erro
echo [24/50] Web E2E...
call npm run web:e2e
if errorlevel 1 goto erro
echo [25/50] Frontend SaaS antigo...
call npm run prod:frontend-saas
if errorlevel 1 goto erro
echo [26/50] Security check...
call npm run security:check
if errorlevel 1 goto erro
echo [27/50] Logs sensiveis...
call npm run api:no-sensitive-logs
if errorlevel 1 goto erro
echo [28/50] Readiness...
call npm run prod:saas-readiness
if errorlevel 1 goto erro
echo [29/50] No legacy...
call npm run prod:no-legacy
if errorlevel 1 goto erro
echo [30/50] No pending...
call npm run prod:no-pending
if errorlevel 1 goto erro
echo [31/50] Billing...
call npm run prod:billing
if errorlevel 1 goto erro
echo [32/50] Email...
call npm run prod:email-flow
if errorlevel 1 goto erro
echo [33/50] Certificado...
call npm run prod:certificate-flow
if errorlevel 1 goto erro
echo [34/50] Performance...
call npm run prod:performance
if errorlevel 1 goto erro
echo [35/50] Security live...
call npm run prod:security-live
if errorlevel 1 goto erro
echo [36/50] Cutover dry run...
call npm run prod:cutover-dry-run
if errorlevel 1 goto erro
echo [37/50] Rollback ready...
call npm run prod:rollback-ready
if errorlevel 1 goto erro
echo [38/50] Docker build...
docker compose build
if errorlevel 1 goto erro
echo [39/50] Build producao...
call npm run build:prod
if errorlevel 1 goto erro
echo [40/50] Release final...
call npm run prod:final-gate
if errorlevel 1 goto erro
echo [41/50] Login nao generico...
findstr /C:"Executar ação" backend\Valora.Web\Views\Account\Login.cshtml && goto erro
echo [42/50] Login sem form.id.value...
findstr /C:"form.id.value" backend\Valora.Web\wwwroot\js\pages\login-page.js && goto erro
echo [43/50] Valora.Web csproj existe...
if not exist backend\Valora.Web\Valora.Web.csproj goto erro
echo [44/50] Layout existe...
if not exist backend\Valora.Web\Views\Shared\_Layout.cshtml goto erro
echo [45/50] AJAX client existe...
if not exist backend\Valora.Web\wwwroot\js\api\ajax-client.js goto erro
echo [46/50] Relatorio Web existe...
if not exist ASPNET_WEB_VALIDATION_REPORT.md goto erro
echo [47/50] Auditoria Sprint 36 existe...
if not exist SPRINT_36_VALORA_WEB_REAL_UX_AUDIT.md goto erro
echo [48/50] API gaps existe...
if not exist ASPNET_WEB_API_GAPS.md goto erro
echo [49/50] Encerrando ambiente...
call npm run local:live:down
if errorlevel 1 goto erro
echo [50/50] Valora.Web sem placeholders validado.
echo VALORA.WEB ASP.NET API-FIRST COM UX REAL VALIDADO.
pause
exit /b 0
:erro
echo FALHA NA VALIDACAO DO VALORA.WEB SEM PLACEHOLDERS.
call npm run local:live:down
pause
exit /b 1
