@echo off
set PGPASSWORD=%VALORA_POSTGRES_PASSWORD%
if "%VALORA_POSTGRES_DB%"=="" set VALORA_POSTGRES_DB=valora_hml
if "%VALORA_POSTGRES_USER%"=="" set VALORA_POSTGRES_USER=valora_hml
if "%VALORA_POSTGRES_HOST%"=="" set VALORA_POSTGRES_HOST=localhost
if "%VALORA_POSTGRES_PORT%"=="" set VALORA_POSTGRES_PORT=5432
psql -h %VALORA_POSTGRES_HOST% -p %VALORA_POSTGRES_PORT% -U %VALORA_POSTGRES_USER% -d %VALORA_POSTGRES_DB% -v ON_ERROR_STOP=1 -f database/postgresql/scriptbd_completo.sql
for %%f in (database\postgresql\0*.sql) do psql -h %VALORA_POSTGRES_HOST% -p %VALORA_POSTGRES_PORT% -U %VALORA_POSTGRES_USER% -d %VALORA_POSTGRES_DB% -v ON_ERROR_STOP=1 -f %%f
