'use strict';
const admin=require('firebase-admin');
const {onCall,HttpsError}=require('firebase-functions/v2/https');
const {sha256,timingSafeEqualHex,createToken}=require('./utils/hash');
const {required,asObject,asBoolean,validateParticipant}=require('./utils/validation');
const {auditLog}=require('./utils/audit');
admin.initializeApp();
const db=admin.firestore();
const TS=admin.firestore.FieldValue.serverTimestamp;
function ip(req){return req.rawRequest?.headers?.['x-forwarded-for']?.split(',')[0]?.trim()||req.rawRequest?.ip||'';}
function ua(req){return req.rawRequest?.headers?.['user-agent']||'';}
async function rateLimit(key,limit,windowMs){const ref=db.collection('rateLimits').doc(key);const now=Date.now();let allowed=false;await db.runTransaction(async tx=>{const s=await tx.get(ref);const d=s.exists?s.data():{};let count=d.resetAt?.toMillis?.()>now?Number(d.count||0):0;if(count>=limit)throw new HttpsError('resource-exhausted','Muitas tentativas. Aguarde e tente novamente.');count++;tx.set(ref,{count,resetAt:new Date(now+windowMs),updatedAt:TS()},{merge:true});allowed=true;});return allowed;}
function isBetween(s){const now=Date.now(),start=s.startsAt?.toMillis?.()||Date.parse(s.startsAt||0)||0,end=s.expiresAt?.toMillis?.()||Date.parse(s.expiresAt||0)||0;return (!start||start<=now)&&(!end||end>=now);}
async function loadValidSurvey({surveyId,token,req,action}){await rateLimit(`${action}:${ip(req)||'unknown'}:${surveyId}`,action==='submit'?10:60,15*60*1000);const snap=await db.collection('surveys').doc(surveyId).get();if(!snap.exists)throw new HttpsError('not-found','Pesquisa não encontrada.');const survey={id:snap.id,...snap.data()};if(survey.status!=='active'||survey.revokedAt||survey.revoked===true)throw new HttpsError('failed-precondition','Pesquisa indisponível.');if(!isBetween(survey))throw new HttpsError('failed-precondition','Pesquisa fora do período de validade.');if(!survey.tokenHash||!timingSafeEqualHex(sha256(token),survey.tokenHash))throw new HttpsError('permission-denied','Token inválido.');const [companySnap,formSnap]=await Promise.all([db.collection('companies').doc(survey.companyId).get(),db.collection('forms').doc(survey.formId).get()]);if(!companySnap.exists||companySnap.data().status!=='active')throw new HttpsError('failed-precondition','Empresa indisponível.');if(!formSnap.exists)throw new HttpsError('failed-precondition','Formulário indisponível.');const company={id:companySnap.id,...companySnap.data()},form={id:formSnap.id,...formSnap.data()};const plan=company.planId?(await db.collection('plans').doc(company.planId).get()).data():null;if(plan?.participationEnabled===false)throw new HttpsError('failed-precondition','Plano não permite participação.');if(Number.isFinite(survey.maxResponses)&&survey.responseCount>=survey.maxResponses)throw new HttpsError('resource-exhausted','Limite de respostas da pesquisa atingido.');if(Number(plan?.maxResponsesMonth)>=0){const month=new Date();month.setUTCDate(1);month.setUTCHours(0,0,0,0);const qs=await db.collection('responses').where('companyId','==',survey.companyId).where('createdAt','>=',month).count().get();if(qs.data().count>=Number(plan.maxResponsesMonth))throw new HttpsError('resource-exhausted','Limite mensal de respostas do plano atingido.');}
return {survey,company,form};}
function publicPayload({survey,company,form}){return {survey:{id:survey.id,title:survey.title,description:survey.description||'',companyId:survey.companyId,formId:survey.formId,requireIdentification:survey.requireIdentification!==false,lgpdRequired:survey.lgpdRequired!==false,allowRepeat:survey.allowRepeat===true,anonymous:survey.anonymous===true,showResult:survey.showResult!==false},company:{name:company.name},form:{id:form.id,name:form.name,description:form.description||'',timeMin:form.timeMin||5,scoringMethod:form.scoringMethod,dimensions:form.dimensions||[],questions:(form.questions||[]).map(q=>({id:q.id,text:q.text,help:q.help||'',dimensionId:q.dimensionId,dimensionName:q.dimensionName,type:q.type,required:q.required===true,options:(q.options||[]).map(o=>({id:o.id,text:o.text}))})),resultBands:form.resultBands||[]},lgpd:{text:form.lgpdText||survey.lgpdText||'',required:survey.lgpdRequired!==false},identification:{required:survey.requireIdentification!==false,anonymous:survey.anonymous===true}};}
function calc(form,answers){let rawScore=0,maxScore=0;const byDimension={},ratios=[],qualitative=[];for(const q of form.questions||[]){const a=answers[q.id];let raw=0,max=Number(q.maxScore||0);if(q.type==='scale'){const n=Math.max(0,Math.min(5,Number(a||0)));max=max||5;raw=n/5*max;}else if(q.type==='single'||q.type==='singleCorrect'){const o=(q.options||[]).find(x=>x.id===a);max=max||Math.max(1,...(q.options||[]).map(x=>Number(x.score||0)));raw=q.type==='singleCorrect'?(o?.correct?max:Number(o?.score||0)):Number(o?.score||0);}else if(q.type==='multiple'){const arr=Array.isArray(a)?a:(a?[a]:[]);raw=(q.options||[]).filter(o=>arr.includes(o.id)).reduce((s,o)=>s+Number(o.score||0),0);max=max||(q.options||[]).filter(o=>Number(o.score)>0).reduce((s,o)=>s+Number(o.score||0),0);}else{const text=String(a||'').trim();qualitative.push({question:q.text,answer:text});raw=text?Number(q.scoreWhenFilled||0):0;max=max||Number(q.scoreWhenFilled||0);}const weight=Math.max(0,Number(q.weight||1)),wr=raw*weight,wm=max*weight;rawScore+=wr;maxScore+=wm;ratios.push({ratio:max>0?raw/max:0,weight});const dim=q.dimensionName||'Geral';byDimension[dim]??={rawScore:0,maxScore:0,count:0};byDimension[dim].rawScore+=wr;byDimension[dim].maxScore+=wm;byDimension[dim].count++;}let normalized5=maxScore?rawScore/maxScore*5:0;if(form.scoringMethod==='weightedAverage'){const w=ratios.reduce((s,x)=>s+x.weight,0);normalized5=w?ratios.reduce((s,x)=>s+x.ratio*x.weight,0)/w*5:0;}normalized5=Math.max(0,Math.min(5,normalized5));Object.values(byDimension).forEach(d=>{d.normalized5=d.maxScore?Math.max(0,Math.min(5,d.rawScore/d.maxScore*5)):0;d.percentage=d.normalized5/5*100;});const level=(form.resultBands||[]).find(b=>normalized5>=Number(b.from)&&normalized5<=Number(b.to))||null;return {rawScore,maxScore,normalized5,percentage:normalized5/5*100,scoringMethod:form.scoringMethod,byDimension,level,qualitative};}
exports.validateSurveyLink=onCall(async req=>{const surveyId=required(req.data,'surveyId'),token=required(req.data,'token');const ctx=await loadValidSurvey({surveyId,token,req,action:'validate'});await auditLog(db,{action:'validateSurveyLink',actorType:'public',companyId:ctx.survey.companyId,entity:'survey',entityId:surveyId,ip:ip(req),userAgent:ua(req)});return publicPayload(ctx);});
exports.submitSurveyResponse=onCall(async req=>{const data=asObject(req.data,'payload'),surveyId=required(data,'surveyId'),token=required(data,'token');const ctx=await loadValidSurvey({surveyId,token,req,action:'submit'});const answers=asObject(data.answers,'answers'),participant=validateParticipant(data.participant||{});if(!participant.name||!participant.email)throw new HttpsError('invalid-argument','Nome e e-mail são obrigatórios.');if(ctx.survey.lgpdRequired!==false&&!asBoolean(data.lgpdConsent))throw new HttpsError('failed-precondition','Aceite LGPD obrigatório.');for(const q of ctx.form.questions||[]){const v=answers[q.id];if(q.required&&(v===undefined||v===null||v===''||(Array.isArray(v)&&!v.length)))throw new HttpsError('invalid-argument',`Pergunta obrigatória não respondida: ${q.id}`);}if(!ctx.survey.allowRepeat){const dup=await db.collection('responses').where('surveyId','==',surveyId).where('participant.email','==',participant.email).limit(1).get();if(!dup.empty)throw new HttpsError('already-exists','Participante já respondeu esta pesquisa.');}const result=calc(ctx.form,answers),resultToken=createToken(24);const ref=db.collection('responses').doc();const response={surveyId,formId:ctx.form.id,companyId:ctx.survey.companyId,participant:{...participant,lgpdConsent:asBoolean(data.lgpdConsent),communicationConsent:asBoolean(data.communicationConsent)},answers,lgpdConsent:{accepted:asBoolean(data.lgpdConsent),acceptedAt:TS(),textVersion:ctx.survey.lgpdVersion||ctx.form.lgpdVersion||'default'},communicationConsent:asBoolean(data.communicationConsent),ip:ip(req),userAgent:ua(req),resultTokenHash:sha256(resultToken),createdAt:TS(),...result};await db.runTransaction(async tx=>{tx.set(ref,response);tx.update(db.collection('surveys').doc(surveyId),{responseCount:admin.firestore.FieldValue.increment(1),updatedAt:TS()});});await auditLog(db,{action:'submitSurveyResponse',actorType:'public',companyId:ctx.survey.companyId,entity:'response',entityId:ref.id,after:{surveyId},ip:ip(req),userAgent:ua(req)});return {responseId:ref.id,resultToken,accessToken:resultToken,score:{rawScore:result.rawScore,maxScore:result.maxScore,normalized5:result.normalized5,percentage:result.percentage},level:result.level,message:result.level?.recommendation||'Resposta registrada com sucesso.'};});
exports.getPublicResult=onCall(async req=>{const responseId=required(req.data,'responseId'),resultToken=required(req.data,'resultToken');await rateLimit(`result:${ip(req)||'unknown'}:${responseId}`,60,15*60*1000);const snap=await db.collection('responses').doc(responseId).get();if(!snap.exists)throw new HttpsError('not-found','Resultado não encontrado.');const r={id:snap.id,...snap.data()};if(!r.resultTokenHash||!timingSafeEqualHex(sha256(resultToken),r.resultTokenHash))throw new HttpsError('permission-denied','Token de resultado inválido.');await auditLog(db,{action:'getPublicResult',actorType:'public',companyId:r.companyId,entity:'response',entityId:responseId,ip:ip(req),userAgent:ua(req)});return {id:r.id,surveyId:r.surveyId,companyId:r.companyId,participant:{name:r.participant?.name,email:r.participant?.email},createdAt:r.createdAt,rawScore:r.rawScore,maxScore:r.maxScore,normalized5:r.normalized5,percentage:r.percentage,byDimension:r.byDimension,level:r.level,qualitative:r.qualitative||[]};});
exports.hashSurveyToken=onCall(async req=>({tokenHash:sha256(required(req.data,'token'))}));
