(function(){
'use strict';
const SENT_STATUSES=new Set(['sent','opened','answered','resent']);
const DONE_STATUSES=new Set(['completed','finished','answered','done','concluida','concluída']);
const n=v=>Number.isFinite(Number(v))?Number(v):0;
const avg=a=>a.length?a.reduce((s,x)=>s+n(x),0)/a.length:0;
const pct=(a,b)=>b?Math.round((a/b)*100):0;
const dateOf=v=>v?.toDate?v.toDate():(v?.seconds?new Date(v.seconds*1000):new Date(v||Date.now()));
const monthKey=v=>{const d=dateOf(v);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;};
const uniqueBy=(items,keyFn)=>{const m=new Map();items.forEach(x=>{const k=keyFn(x);if(k&&!m.has(k))m.set(k,x);});return [...m.values()];};
function completedResponses(state,filters={}){return uniqueBy((state.responses||[]).filter(r=>{
  const status=String(r.status||'completed').toLowerCase();
  return DONE_STATUSES.has(status)&&(!filters.companyId||r.companyId===filters.companyId)&&(!filters.surveyId||r.surveyId===filters.surveyId)&&(!filters.from||dateOf(r.createdAt)>=dateOf(filters.from))&&(!filters.to||dateOf(r.createdAt)<=dateOf(filters.to));
}),r=>r.id||`${r.surveyId}:${String(r.participant?.email||r.email||'').toLowerCase()}`);}
function sentInvitations(state,filters={}){return uniqueBy((state.invitations||[]).filter(i=>SENT_STATUSES.has(String(i.status||'').toLowerCase())&&(!filters.companyId||i.companyId===filters.companyId)&&(!filters.surveyId||i.surveyId===filters.surveyId)),i=>i.id||`${i.surveyId}:${String(i.email||i.participantEmail||i.userEmail||'').toLowerCase()}`);}
function planById(state,id){return (state.plans||[]).find(p=>p.id===id)||null;}
function isSurveyActive(s){const now=new Date();return String(s.status||'active')==='active'&&(!s.startsAt||dateOf(s.startsAt)<=now)&&(!s.expiresAt||dateOf(s.expiresAt)>=now);}
function getDimensionMetrics(responses){const bag={};completedResponses({responses}).forEach(r=>Object.entries(r.byDimension||{}).forEach(([dimension,v])=>{(bag[dimension]||(bag[dimension]=[])).push(n(v.normalized5));}));return Object.entries(bag).map(([label,values])=>{const normalized5=avg(values);return {label,normalized5,percentage:normalized5/5*100,count:values.length};}).sort((a,b)=>b.normalized5-a.normalized5);}
function getResponseMetrics(state,filters={}){const responses=completedResponses(state,filters);const dimensions=getDimensionMetrics(responses);const distribution=[{label:'Crítico (<2,5)',min:0,max:2.49},{label:'Atenção (2,5-3,4)',min:2.5,max:3.49},{label:'Bom (3,5-4,2)',min:3.5,max:4.24},{label:'Excelente (4,25+)',min:4.25,max:5}].map(b=>({...b,value:responses.filter(r=>n(r.normalized5)>=b.min&&n(r.normalized5)<=b.max).length}));const normalized5=avg(responses.map(r=>n(r.normalized5)));return {responses,totalCompleted:responses.length,normalized5,percentage:normalized5/5*100,dimensions,bestDimension:dimensions[0]||null,criticalDimension:dimensions[dimensions.length-1]||null,distribution};}
function getInvitationMetrics(state,companyId){const invitations=sentInvitations(state,{companyId});const completed=completedResponses(state,{companyId});return {sent:invitations.length,completed:completed.length,responseRate:pct(completed.length,invitations.length),pending:Math.max(0,invitations.length-completed.length),failed:(state.invitations||[]).filter(i=>(!companyId||i.companyId===companyId)&&String(i.status)==='failed').length};}
function getPlanUsageMetrics(state,companyId){const c=(state.companies||[]).find(x=>x.id===companyId),p=planById(state,c?.planId)||{};const activeSurveys=(state.surveys||[]).filter(s=>s.companyId===companyId&&isSurveyActive(s)).length;const month=monthKey(new Date());const monthResponses=completedResponses(state,{companyId}).filter(r=>monthKey(r.createdAt)===month).length;const employees=(state.users||[]).filter(u=>u.companyId===companyId&&u.role!=='empresa_admin').length;const metrics=[['Pesquisas ativas',activeSurveys,p.maxActiveSurveys],['Respostas no mês',monthResponses,p.maxResponsesMonth],['Funcionários',employees,p.maxEmployees??p.maxRespondents]];return {plan:p,activeSurveys,monthResponses,employees,items:metrics.map(([label,used,limit])=>({label,used,limit:n(limit)<0?-1:n(limit),percentage:n(limit)<0?0:pct(used,limit),nearLimit:n(limit)>0&&used/limit>=0.8}))};}
function getOnboardingMetrics(state,companyId){const c=(state.companies||[]).find(x=>x.id===companyId);const users=(state.users||[]).filter(u=>u.companyId===companyId);const employees=users.filter(u=>u.role!=='empresa_admin');const admins=users.filter(u=>u.role==='empresa_admin'&&u.status!=='inactive');const surveys=(state.surveys||[]).filter(s=>s.companyId===companyId);const activeSurveys=surveys.filter(isSurveyActive);const inv=sentInvitations(state,{companyId});const res=completedResponses(state,{companyId});const checks=[!!c?.name,!!planById(state,c?.planId),admins.length>0,employees.length>0,activeSurveys.length>0,inv.length>0,res.length>0];const percent=Math.round(checks.filter(Boolean).length/checks.length*100);const inactiveDays=Math.floor((Date.now()-dateOf(c?.updatedAt||c?.createdAt).getTime())/86400000);const status=inactiveDays>14&&percent<80?'travado':percent>=100?'implantado':res.length?'com_respostas':inv.length?'convites_enviados':activeSurveys.length?'pesquisa_criada':employees.length?'funcionarios_cadastrados':'configurando';return {company:c,percent,status,employees,admins,surveys,activeSurveys,invitations:inv,responses:res};}
function getSurveyMetrics(state,surveyId){const survey=(state.surveys||[]).find(s=>s.id===surveyId);return {survey,...getInvitationMetrics(state,survey?.companyId),...getResponseMetrics(state,{surveyId})};}
function getTimeSeriesMetrics(state,filters={}){const groups={};completedResponses(state,filters).forEach(r=>{const k=monthKey(r.createdAt);(groups[k]||(groups[k]={label:k,value:0,sum:0})).value++;groups[k].sum+=n(r.normalized5);});return Object.values(groups).sort((a,b)=>a.label.localeCompare(b.label)).map(x=>({label:x.label,value:x.value,normalized5:x.value?x.sum/x.value:0}));}
function recommendationMetrics(state,companyId){const inv=getInvitationMetrics(state,companyId),res=getResponseMetrics(state,{companyId}),usage=getPlanUsageMetrics(state,companyId);const alerts=[];if(inv.sent&&inv.responseRate<40)alerts.push({type:'response',label:'Baixa taxa de resposta',text:'A taxa de resposta está baixa. Reenvie convites ou amplie o prazo da pesquisa.',cta:'Ver respostas'});if(res.criticalDimension&&res.criticalDimension.normalized5<2.5)alerts.push({type:'dimension',label:'Dimensão crítica',text:`A dimensão ${res.criticalDimension.label} está em nível crítico. Priorize um plano de ação específico.`,cta:'Gerar relatório'});usage.items.filter(i=>i.nearLimit).forEach(i=>alerts.push({type:'plan',label:'Alto uso do plano',text:`${i.label} está acima de 80% do limite. Avalie upgrade.`,cta:'Revisar plano'}));return alerts;}
function getCompanyDashboardMetrics(state,companyId){const onboarding=getOnboardingMetrics(state,companyId),responses=getResponseMetrics(state,{companyId}),invites=getInvitationMetrics(state,companyId),usage=getPlanUsageMetrics(state,companyId),series=getTimeSeriesMetrics(state,{companyId});return {onboarding,responses,invites,usage,series,recommendations:recommendationMetrics(state,companyId)};}
function getGlobalDashboardMetrics(state){const companies=state.companies||[],active=companies.filter(c=>c.status==='active'),responses=getResponseMetrics(state),plans=(state.plans||[]).map(p=>({label:p.name,value:companies.filter(c=>c.planId===p.id).length,mrr:companies.filter(c=>c.status==='active'&&c.planId===p.id).reduce((s,c)=>s+n(planById(state,c.planId)?.price),0)}));const onboarding=companies.map(c=>getOnboardingMetrics(state,c.id));const inv=getInvitationMetrics(state);return {totalClients:companies.length,activeClients:active.length,inactiveClients:companies.length-active.length,mrr:active.reduce((s,c)=>s+n(planById(state,c.planId)?.price),0),topPlan:[...plans].sort((a,b)=>b.value-a.value)[0]||null,activeSurveys:(state.surveys||[]).filter(isSurveyActive).length,responses,invites:inv,plans,onboarding,stuck:onboarding.filter(o=>['travado','configurando'].includes(o.status)),nearLimit:companies.filter(c=>getPlanUsageMetrics(state,c.id).items.some(i=>i.nearLimit)),series:getTimeSeriesMetrics(state)};}
window.ValoraAnalytics={getGlobalDashboardMetrics,getCompanyDashboardMetrics,getSurveyMetrics,getResponseMetrics,getPlanUsageMetrics,getOnboardingMetrics,getDimensionMetrics,getInvitationMetrics,getTimeSeriesMetrics,completedResponses,sentInvitations};
})();
