(function(){
'use strict';
const ENABLE_AI_CHATBOT=false;
const WHATSAPP_SUPPORT='+55 91 99254-5353';
const ROLE_LABELS={admin_valora:'Admin Valora',consultor_valora:'Consultor Valora',empresa_admin:'Administrador da Empresa',gestor_pesquisa:'Gestor de Pesquisa',analista_resultados:'Analista de Resultados',gestor_area:'Gestor de Área',participante:'Participante',convidado_externo:'Convidado Externo',public:'Visitante'};
const INTENTS={
 greeting:['oi','ola','olá','bom dia','boa tarde','boa noite'],
 planos_precos:['plano','planos','preço','preco','quanto custa','gratis','grátis','essencial','profissional','corporativo','enterprise','assinatura','contratar'],
 recomendacao_plano:['qual plano','melhor plano','plano ideal','recomendar plano','500 respostas','respostas por mes'],
 diagnostico_valora_insight:['valora insight','diagnostico','diagnóstico','maturidade organizacional','125','pontuacao','pontuação','dimensoes','dimensões','perguntas tem'],
 resultado_devolutiva:['interpretar','resultado','devolutiva','estruturação','estruturacao','governanca','governança','verdade estrategica','verdade estratégica','proximo nivel','próximo nível'],
 certificado_relatorio:['certificado','relatorio','relatório','baixar pdf','download','baixar relatório','baixar certificado'],
 como_responder_pesquisa:['responder pesquisa','pesquisa','link expirou','não recebi','nao recebi','abrir pesquisa','responder de novo','criar conta'],
 acesso_login:['login','entrar','senha','esqueci','conta','acesso','meu login'],
 admin_plataforma:['criar pesquisa','ver respostas','cadastrar usuario','cadastrar usuário','criar formulario','criar formulário','relatorios','relatórios','plano de acao','plano de ação','clientes','importação','importacao'],
 privacidade_lgpd:['lgpd','privacidade','dados','consentimento','senha','token','cpf','documento'],
 suporte_humano:['falar com pessoa','falar com uma pessoa','atendente','suporte humano','especialista','quero contratar','preciso de suporte','humano','whatsapp'],
 duvida_desconhecida:[]
};
const SENSITIVE=/\b(cpf|senha|password|token|rg|documento|cart[aã]o|cvv)\b|\d{3}\.?\d{3}\.?\d{3}-?\d{2}/i;
function norm(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();}
function uid(p='chat'){return `${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;}
function state(){return window.ValoraState||{};}
function currentUser(){const st=state();return st.users?.find(u=>u.id===st.session?.userId)||null;}
function route(){return location.hash.replace('#','')||'home';}
function getSession(){const st=state();st.chatbotSession=st.chatbotSession||{messages:[],lastIntent:'',collectedAnswers:{},startedAt:new Date().toISOString(),updatedAt:new Date().toISOString()};return st.chatbotSession;}
function getValoraBotContext(){const st=state(),user=currentUser(),r=route(),company=st.companies?.find(c=>c.id===user?.companyId)||null,plan=st.plans?.find(p=>p.id===(company?.planId||company?.subscription?.planId))||null;const params=new URL(location.href).searchParams;const surveyId=params.get('survey')||params.get('s')||'';const resultId=params.get('result')||params.get('response')||'';const currentSurvey=(st.surveys||[]).find(s=>s.id===surveyId||s.token===surveyId)||null;const currentResponse=(st.responses||[]).find(x=>x.id===resultId||x.resultToken===resultId)||null;const role=user?.role||(surveyId?'convidado_externo':'public');return {isLoggedIn:!!user,role,roleLabel:ROLE_LABELS[role]||role,userName:user?.name||'',user:user?{id:user.id,name:user.name,email:user.email,role:user.role,companyId:user.companyId}:null,companyId:company?.id||user?.companyId||'',companyName:company?.publicName||company?.name||'',company:company?{id:company.id,name:company.publicName||company.name}:null,currentRoute:r,route:r,isPublicPage:!user,isPublicSurvey:!!surveyId||/survey|pesquisa/.test(r),isPublicResult:!!resultId||/result|resultado/.test(r),currentSurvey,currentResponse,currentPlan:plan,plan:plan?{id:plan.id,name:plan.name}:null,firebaseMode:window.ValoraConfig?.FIREBASE_ENABLED?'firebase':'local',firebasePlan:window.ValoraConfig?.FIREBASE_PLAN||'Spark/local',cloudFunctionsEnabled:window.ValoraConfig?.ENABLE_CLOUD_FUNCTIONS!==false,hasResponses:(st.responses||[]).some(x=>!company||x.companyId===company.id),hasSurveys:(st.surveys||[]).some(x=>!company||x.companyId===company.id),hasForms:(st.forms||[]).some(x=>!company||x.companyId===company.id||x.global),hasActionPlans:(st.actionPlans||[]).some(x=>!company||x.companyId===company.id)};}
function localArticles(ctx){const publicKb=(state().knowledgeBase||[]).filter(a=>a.published!==false);const built=(window.CHATBOT_KNOWLEDGE_BASE||[]).map(a=>({id:a.id,title:a.title,category:a.category||'geral',content:a.answer||a.content||'',summary:a.summary||a.answer||'',tags:a.intents||a.tags||[],actions:a.actions||[]}));return publicKb.concat(built).filter(a=>a.published!==false).filter(a=>!a.roles?.length||a.roles.includes(ctx.role)||a.audience==='public');}
function detectIntent(message,ctx=getValoraBotContext()){const t=norm(message);let best={intent:'duvida_desconhecida',confidence:.15,entities:{}};Object.entries(INTENTS).forEach(([intent,words])=>{let score=0;words.forEach(w=>{const nw=norm(w);if(t.includes(nw))score=Math.max(score,.45+Math.min(.45,nw.length/40));});if(score>best.confidence)best={intent,confidence:score,entities:{keywords:words.filter(w=>t.includes(norm(w))).slice(0,4)}};});if(/\b\d{2,5}\b/.test(t)&&/(respostas|pessoas|participantes)/.test(t))best={intent:'recomendacao_plano',confidence:.9,entities:{volume:Number(t.match(/\d{2,5}/)?.[0]||0)}};if(best.intent==='duvida_desconhecida'){const hit=localArticles(ctx).find(a=>(a.tags||[]).some(k=>t.includes(norm(k)))||t.includes(norm(a.title)));if(hit)best={intent:hit.category||hit.id,confidence:.62,entities:{articleId:hit.id}};}return best;}
function recommendPlanFromAnswers(answers={}){const volume=Number(answers.volume||answers.respondents||0);const recurring=!!answers.recurring||/recorrente|acompanhar|mensal|continuo/.test(norm(answers.goal));const units=Number(answers.units||1);const executive=!!answers.executive||/relatorio|executivo|plano de acao|ação/.test(norm(answers.needs));if(volume<=10&&!recurring&&!executive)return 'Grátis';if(volume<=150&&units<=1&&!executive)return 'Essencial';if(volume<=1000&&units<=1)return 'Profissional';if(volume<=10000&&units>1)return 'Corporativo';if(volume>10000||units>5||/consultoria|implantacao|várias empresas|varias empresas/.test(norm(answers.needs)))return 'Enterprise';return executive?'Profissional':'Essencial';}
function planAnswer(message){const t=norm(message),volume=Number(t.match(/\d{2,5}/)?.[0]||0);if(/qual|melhor|recom/.test(t)||volume){const rec=recommendPlanFromAnswers({volume,executive:/relatorio|plano de acao|executivo/.test(t),units:/unidades|areas|áreas|filiais/.test(t)?2:1,goal:t});return {text:`Depende do momento da sua empresa.\n\nSe você quer apenas testar a metodologia, comece pelo Grátis. Se precisa rodar diagnósticos com equipe pequena, o Essencial atende. Se quer acompanhar maturidade com relatórios e plano de ação, o Profissional é o mais indicado. Se possui múltiplas áreas ou unidades, o Corporativo faz mais sentido. Se envolve consultoria, implantação assistida ou várias empresas, o Enterprise é o caminho.\n\nPelo que você informou${volume?` (${volume} respostas aproximadas)`:''}, minha indicação inicial é: ${rec}. Posso refinar com 3 perguntas rápidas: quantidade de respondentes, recorrência e necessidade de relatório executivo/plano de ação.`,intent:'plan_recommendation'};}
return {text:'Os planos do Valora Pulse™ foram pensados por estágio de uso:\n\n• Grátis: testar a metodologia em pequena escala.\n• Essencial: pesquisas com equipe pequena e devolutiva inicial.\n• Profissional: relatórios executivos, maturidade e plano de ação.\n• Corporativo: múltiplas áreas/unidades e consolidação.\n• Enterprise: projeto consultivo, implantação assistida e cenários com várias empresas.\n\nSe você me disser quantas pessoas vão responder e se precisa de relatório executivo, eu recomendo o caminho mais adequado.',intent:'plans_pricing'};}
function explainResult(ctx){const r=ctx.currentResponse||{};const vi=r.valoraInsight||r.result||{};const score=vi.totalScore||vi.score||r.score||'';const level=vi.maturityLevel||vi.level||r.level||'estruturação';const dims=vi.dimensions||r.dimensions||[];const sorted=Array.isArray(dims)?dims.slice().sort((a,b)=>(a.score||0)-(b.score||0)):[];const weak=sorted[0]?.name||'Gestão e Governança';const strong=sorted.at(-1)?.name||'uma dimensão com melhor desempenho';return `Seu resultado indica maturidade em ${level}${score?` (${score})`:''}.\n\nIsso significa que já existe movimento e intenção de organização, mas ainda pode faltar previsibilidade, rotina e clareza de decisão. O ponto mais sensível é ${weak}; quando essa dimensão fica baixa, a empresa tende a depender demais de pessoas específicas para decidir e manter a operação funcionando. O ponto mais forte é ${strong}.\n\nA verdade estratégica é transformar o diagnóstico em prioridade: escolher poucas ações, definir responsáveis e acompanhar evolução. O próximo passo é revisar a devolutiva, baixar o relatório/certificado quando disponível e criar um plano de ação enxuto.`;}
function answerFor(intent,message,ctx){if(SENSITIVE.test(message))return {answer:'Por segurança, não envie senhas, tokens ou documentos completos por aqui. Para suporte, posso abrir um atendimento com dados mínimos.',shouldOfferHumanSupport:true};
 switch(intent.intent){
 case 'greeting':return {answer:'Olá, eu sou o ValoraBot. Posso te ajudar a entender o diagnóstico, os planos, sua pesquisa, seus resultados ou direcionar você para atendimento humano.'};
 case 'planos_precos':case 'recomendacao_plano':{const p=planAnswer(message);return {answer:p.text,intent:p.intent==='plan_recommendation'?'recomendacao_plano':'planos_precos',routeSuggestion:'plans'};}
 case 'diagnostico_valora_insight':return {answer:'O Valora Insight™ é o diagnóstico de maturidade organizacional do Valora Pulse™. Ele organiza 25 perguntas em 5 dimensões oficiais — Cultura e Propósito, Gestão e Governança, Liderança, Pessoas e Talentos, Resultados e Crescimento — consolidando uma pontuação máxima de 125 pontos.\n\nA pontuação não deve ser lida como “nota escolar”, e sim como um retrato de maturidade: onde a empresa já tem práticas consistentes, onde depende de improviso e qual próximo nível precisa ser construído. Depois do diagnóstico, o ideal é transformar os achados em devolutiva estratégica e plano de ação.'};
 case 'resultado_devolutiva':return {answer:explainResult(ctx),routeSuggestion:ctx.isPublicResult?'resultado':'empresa/responses'};
 case 'certificado_relatorio':return {answer:'Para baixar certificado ou relatório, abra a página do resultado permitido e procure os botões de download em PDF/PNG ou relatório. Se o botão não aparecer, normalmente a pesquisa não liberou resultado público, seu perfil não tem permissão ou o link expirou.\n\nSe você estiver logado como participante, consulte também o portal do participante. Se estiver como empresa, use Respostas/Relatórios.'};
 case 'como_responder_pesquisa':return {answer:'Para responder uma pesquisa, abra o link seguro recebido, confira a empresa responsável, leia o termo LGPD quando aparecer, responda as perguntas obrigatórias e envie. Em geral, participante não precisa criar conta para responder por link público.\n\nSe o link expirou, não abriu ou você não recebeu e-mail, peça um novo envio à empresa responsável ou use atendimento humano para validarmos o contexto sem expor token completo.',shouldOfferHumanSupport:/expirou|não|nao|erro/.test(norm(message))};
 case 'acesso_login':return {answer:'Se você não consegue entrar, confira primeiro se está usando o e-mail correto e redefina a senha quando a opção estiver disponível. Se seu acesso foi criado pela empresa, o administrador pode revisar status, perfil e vínculo com a empresa.\n\nNão envie sua senha aqui. Posso abrir um atendimento com seu nome, e-mail e descrição do problema.',shouldOfferHumanSupport:true};
 case 'admin_plataforma':return {answer:`Pelo seu contexto (${ctx.roleLabel}), posso orientar a operação. Para empresa: crie formulários, publique pesquisas, acompanhe respostas, gere relatórios e desdobre planos de ação. Para Admin Valora: gerencie clientes, planos, módulos, base de conhecimento, importações e diagnóstico PRD.\n\nSe você não enxergar uma tela, provavelmente é permissão do perfil ou módulo do plano contratado.`,routeSuggestion:ctx.role==='admin_valora'?'admin/dashboard':'empresa/dashboard'};
 case 'privacidade_lgpd':return {answer:'A LGPD é tratada com finalidade informada, consentimento quando necessário, segregação por empresa, permissões por perfil e cuidado com dados sensíveis. O bot não precisa de CPF, senha, token completo ou documento integral para ajudar.\n\nPara solicitações de titular, correção ou exclusão, abra atendimento com dados mínimos de identificação.',shouldOfferHumanSupport:true};
 case 'suporte_humano':return {answer:'Posso direcionar você para atendimento humano. Se você estiver logado, abro um ticket com perfil, empresa e rota atual. Se não estiver logado, peça nome, e-mail e mensagem; se o Firestore não estiver disponível, abrimos o WhatsApp.',shouldOfferHumanSupport:true,shouldCreateTicket:ctx.isLoggedIn};
 default:return {answer:'Não quero te dar uma resposta genérica. Posso te ajudar por um destes caminhos:\n1. Planos e preços\n2. Pesquisa ou link de acesso\n3. Resultado e certificado\n4. Suporte humano',shouldOfferHumanSupport:true};}}
function actionsFor(res,ctx){const a=[];if(res.routeSuggestion)a.push({label:'Abrir caminho sugerido',type:'route',value:res.routeSuggestion});if(['planos_precos','recomendacao_plano'].includes(res.intent))a.push({label:'Ver planos',type:'route',value:'plans'});a.push({label:'Falar com atendente',type:'support'});return a;}
function generateAnswer(message,context=getValoraBotContext()){const session=getSession();let intent=detectIntent(message,context);if(session.lastIntent==='recomendacao_plano'&&/\d+|recorrente|uma|varias|várias|relatorio|executivo|plano de acao/i.test(message))intent={intent:'recomendacao_plano',confidence:.82,entities:{flow:'plan'}};const base=answerFor(intent,message,context);const finalIntent=base.intent||intent.intent;const result={intent:finalIntent,confidence:intent.confidence,answer:base.answer,actions:actionsFor({...base,intent:finalIntent},context),relatedArticles:localArticles(context).filter(a=>norm(base.answer).includes(norm(a.title))||norm(message).includes(norm(a.title))).slice(0,3),shouldOfferHumanSupport:!!base.shouldOfferHumanSupport||finalIntent==='duvida_desconhecida',shouldCreateTicket:!!base.shouldCreateTicket,routeSuggestion:base.routeSuggestion||''};session.lastIntent=finalIntent;session.messages.push({sender:'user',text:String(message).slice(0,1000),intent:finalIntent,createdAt:new Date().toISOString()},{sender:'bot',text:result.answer,intent:finalIntent,createdAt:new Date().toISOString()});session.updatedAt=new Date().toISOString();if(finalIntent==='recomendacao_plano')logEvent('chatbot_plan_recommended',{intent:finalIntent});if(finalIntent==='duvida_desconhecida')logEvent('chatbot_unknown_intent',{question:String(message).slice(0,200)});return result;}
function logEvent(action,metadata={}){window.ValoraLogger?.info?.({category:'chatbot',action,message:'Evento do ValoraBot.',metadata,user:getValoraBotContext().user});}
function createBotMessage(text,extras={}){return {id:uid('bot'),sender:'bot',text:String(text||''),answer:String(text||''),actions:extras.actions||[],intent:extras.intent||'',confidence:extras.confidence||0,createdAt:new Date().toISOString()};}
function sendMessage(text){logEvent('chatbot_question_sent');const ctx=getValoraBotContext();const r=generateAnswer(text,ctx);logEvent('chatbot_answer_sent',{intent:r.intent,confidence:r.confidence});return createBotMessage(r.answer,{actions:r.actions,intent:r.intent,confidence:r.confidence});}
function startConversation(){const ctx=getValoraBotContext();let g='Olá! Posso te ajudar a entender os planos, o Valora Insight™ ou como iniciar um diagnóstico.';if(['participante','convidado_externo'].includes(ctx.role)||ctx.isPublicSurvey||ctx.isPublicResult)g='Olá! Posso te ajudar a responder a pesquisa, entender seu resultado ou baixar seu certificado.';if(['empresa_admin','gestor_pesquisa'].includes(ctx.role))g='Olá! Posso ajudar com pesquisas, respostas, relatórios, usuários e plano de ação.';if(['admin_valora','consultor_valora'].includes(ctx.role))g='Olá! Posso apoiar na administração da plataforma, clientes, planos, formulários, importação e diagnóstico PRD.';logEvent('chatbot_opened');return createBotMessage(g,{intent:'greeting',confidence:1});}
function openWhatsappSupport(subject='atendimento'){const msg=encodeURIComponent(`Olá, estou usando o Valora Pulse™ e preciso de ajuda com: ${subject}`);const number=WHATSAPP_SUPPORT.replace(/\D/g,'');const url=`https://wa.me/${number}?text=${msg}`;window.open?.(url,'_blank','noopener,noreferrer');return url;}
function createSupportTicketFromBot(extra={}){const ctx=getValoraBotContext(),st=state();const ticket={id:uid('ticket'),subject:extra.subject||'Atendimento aberto pelo ValoraBot',origin:'valorabot',status:'open',priority:'medium',companyId:ctx.companyId,requesterUserId:ctx.user?.id||'',requesterName:ctx.userName||extra.name||'Visitante',requesterEmail:ctx.user?.email||extra.email||'',message:extra.message||'Solicitação criada pelo ValoraBot.',context:{route:ctx.currentRoute,role:ctx.role,companyName:ctx.companyName},createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};st.supportTickets=st.supportTickets||[];st.supportTickets.push(ticket);st.supportConversations=st.supportTickets;logEvent('chatbot_ticket_created',{ticketId:ticket.id});return ticket;}
function getSuggestedQuestions(ctx=getValoraBotContext()){if(ctx.isPublicResult)return ['Como interpretar meu resultado?','Como baixar certificado?','O que significa em estruturação?','Falar com atendimento'];if(ctx.isPublicSurvey)return ['Como responder a pesquisa?','Meu link expirou','Meus dados estão seguros?','Falar com atendimento'];if(['empresa_admin','gestor_pesquisa'].includes(ctx.role))return ['Como criar pesquisa?','Como ver respostas?','Como acompanhar plano de ação?','Falar com atendimento'];if(['admin_valora','consultor_valora'].includes(ctx.role))return ['Como gerir base de conhecimento?','Como configurar planos?','Como validar diagnóstico PRD?','Falar com atendimento'];return ['Como funciona o diagnóstico?','Qual plano escolher?','Como interpretar meu resultado?','Como baixar certificado?','Falar com atendimento'];}
window.getValoraBotContext=getValoraBotContext;
window.ValoraChatbot={ENABLE_AI_CHATBOT,WHATSAPP_SUPPORT,INTENTS,getValoraBotContext,getChatContext:getValoraBotContext,detectIntent,generateAnswer,buildAnswer:(m,c)=>{const r=generateAnswer(m,c);return createBotMessage(r.answer,r);},buildBotAnswer:(m,c)=>{const r=generateAnswer(m,c);return createBotMessage(r.answer,r);},sendMessage,startConversation,getSuggestedQuestions,recommendPlanFromAnswers,createSupportTicketFromBot,openWhatsappSupport,escalateToHuman:createSupportTicketFromBot,getConversationHistory:()=>getSession().messages};
})();
