(function(){
'use strict';
const ROLE_LABELS={admin_valora:'Admin Valora',consultor_valora:'Consultor Valora',empresa_admin:'Administrador da Empresa',gestor_pesquisa:'Gestor de Pesquisa',analista_resultados:'Analista de Resultados',gestor_area:'Gestor de Área',participante:'Participante',convidado_externo:'Convidado Externo',public:'Visitante'};
const INTENTS={
 greeting:{keywords:['oi','olá','ola','bom dia','boa tarde','boa noite']},help:{keywords:['ajuda','manual','como usar','dúvida','duvida']},how_to_start:{keywords:['começar','comecar','primeiro passo','implantação','implantacao','dashboard vazio']},create_company:{keywords:['cadastrar cliente','criar cliente','novo cliente','empresa nova']},create_employee:{keywords:['cadastrar funcionário','cadastrar funcionario','funcionários','funcionarios','importar funcionários']},choose_role:{keywords:['qual perfil','escolher perfil','permissão','permissao','quem pode']},create_form:{keywords:['criar formulário','criar formulario','criar questionário','criar questionario']},create_question:{keywords:['criar pergunta','alterar pergunta','editar pergunta']},question_types:{keywords:['tipo de pergunta','escala','multipla','múltipla','radio','checkbox','texto']},scoring:{keywords:['pontuação','pontuacao','peso','nota','calculo','cálculo']},dimensions:{keywords:['dimensão','dimensao','dimensões','dimensoes']},create_survey:{keywords:['criar pesquisa','nova pesquisa','publicar pesquisa']},send_invites:{keywords:['enviar pesquisa','enviar convite','convites','email','e-mail','mandar questionário','mandar questionario']},answer_survey:{keywords:['responder pesquisa','como respondo','responder por link','enviar resposta']},lgpd:{keywords:['lgpd','privacidade','dados seguros','consentimento','excluir meus dados','exclusão']},view_results:{keywords:['ver resultado','resultado','ver respostas','respostas']},reports:{keywords:['relatório','relatorio','exportar','pdf','excel','csv']},dashboard:{keywords:['dashboard','indicadores','gráficos','graficos']},action_plan:{keywords:['plano de ação','plano de acao','ações de melhoria','acoes de melhoria','ação vencida']},notifications:{keywords:['notificação','notificacao','alerta','sino']},billing:{keywords:['financeiro','cobrança','cobranca','fatura','pagamento']},plans:{keywords:['plano','assinatura','limite','upgrade']},white_label:{keywords:['marca','logo','white label','cores','personalizar']},logs:{keywords:['logs','auditoria','monitorar']},telegram:{keywords:['telegram']},integrations:{keywords:['integração','integracao','api','webhook']},support_human:{keywords:['falar com atendente','quero suporte','humano','não resolveu','nao resolveu','preciso de ajuda','erro','não consigo','nao consigo','travou','link expirou']},error_help:{keywords:['erro','falha','travou','não abre','nao abre','expirou']}}
function norm(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();}
function uid(p='chat'){return `${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;}
function state(){return window.ValoraState||{};}
function currentUser(){const st=state();return st.users?.find(u=>u.id===st.session?.userId)||null;}
function getChatContext(){const st=state(),user=currentUser(),company=st.companies?.find(c=>c.id===user?.companyId)||null,route=location.hash.replace('#','')||'home',role=user?.role||(route.includes('survey')?'convidado_externo':'public'),surveys=st.surveys||[],forms=st.forms||[],invs=st.invitations||[],resp=st.responses||[],actions=st.actionPlans||[],notifs=st.notifications||[],plan=st.plans?.find(p=>p.id===(company?.planId||company?.subscription?.planId));return {isLoggedIn:!!user,user:user?{id:user.id,name:user.name,role:user.role,companyId:user.companyId}:null,role,roleLabel:ROLE_LABELS[role]||role,company:company?{id:company.id,name:company.publicName||company.name}:null,companyId:company?.id||'',route,currentPage:route.split('/').pop()||'home',plan:plan?{id:plan.id,name:plan.name}:null,enabledModules:plan?.enabledModules||st.modules?.filter(m=>m.enabled).map(m=>m.id)||[],onboardingStatus:'local',hasEmployees:!!st.users?.some(u=>u.companyId===company?.id&&u.id!==user?.id),hasForms:!!forms.some(f=>!company||f.companyId===company.id||f.global),hasSurveys:!!surveys.some(s=>!company||s.companyId===company.id),hasInvitations:!!invs.some(i=>!company||i.companyId===company.id),hasResponses:!!resp.some(r=>!company||r.companyId===company.id),hasActionPlans:!!actions.some(a=>!company||a.companyId===company.id),hasOverdueActions:!!actions.some(a=>a.companyId===company?.id&&a.dueDate&&new Date(a.dueDate)<new Date()&&!['done','closed'].includes(a.status)),hasNotifications:!!notifs.length,isPublicSurvey:location.href.includes('survey='),isPublicResult:location.href.includes('result='),environment:(window.ValoraConfig?.FIREBASE_ENABLED?'firebase':'local_demo')};}
function getKnowledgeBase(context=getChatContext()){const role=context.role||'public',kb=window.CHATBOT_KNOWLEDGE_BASE||[];return kb.filter(x=>(x.audience||[]).includes(role)||(role==='public'&&(x.audience||[]).includes('convidado_externo')));}
function detectIntent(message,context=getChatContext()){const text=norm(message);let best={intent:'unknown',confidence:0,entities:{},originalMessage:message};Object.entries(INTENTS).forEach(([intent,cfg])=>{let score=0;(cfg.keywords||[]).forEach(k=>{if(text.includes(norm(k)))score=Math.max(score,Math.min(.95,.45+norm(k).length/45));});if(score>best.confidence)best={intent,confidence:score,entities:{keywords:cfg.keywords.filter(k=>text.includes(norm(k))).slice(0,3)},originalMessage:message};});if(best.intent==='unknown'){const hit=getKnowledgeBase(context).find(k=>(k.intents||[]).some(x=>text.includes(norm(x))));if(hit)best={intent:hit.id,confidence:.65,entities:{knowledgeId:hit.id},originalMessage:message};}return best;}
function matchKnowledge(intent,message,context){const text=norm(message),kb=getKnowledgeBase(context);return kb.find(k=>k.id===intent.intent||k.intents?.some(x=>text.includes(norm(x))))||kb.find(k=>k.intents?.some(x=>intent.intent.includes(x)))||null;}
function permissionNote(intent,ctx){const r=ctx.role;if(['participante','convidado_externo','public'].includes(r)&&['create_form','create_question','create_survey','send_invites','create_employee'].includes(intent.intent))return `Pelo seu perfil de ${ctx.roleLabel}, você não tem permissão para executar essa ação. Você pode responder pesquisas e consultar resultados permitidos; para criar ou enviar, procure o Administrador da Empresa ou Gestor de Pesquisa.`;if(r==='analista_resultados'&&['create_form','create_question','create_survey','send_invites'].includes(intent.intent))return 'Seu perfil é de análise: você pode ver dashboards, respostas e relatórios permitidos, mas não editar questionários, criar pesquisas ou enviar convites.';if(r==='gestor_area'&&['create_form','create_survey','send_invites'].includes(intent.intent))return 'Seu perfil de Gestor de Área é restrito ao acompanhamento da área e planos de ação permitidos. Solicite alterações ao Administrador da Empresa.';return '';}
function createBotMessage(text,extras={}){return {id:uid('bot'),sender:'bot',text:String(text||''),actions:extras.actions||[],intent:extras.intent||'',confidence:extras.confidence||0,createdAt:new Date().toISOString()};}
function createUserMessage(text,extras={}){return {id:uid('usr'),sender:'user',text:String(text||'').slice(0,1000),intent:extras.intent||'',confidence:extras.confidence||0,createdAt:new Date().toISOString()};}
function saveHistory(message,context=getChatContext()){const st=state();st.chatbotConversations=st.chatbotConversations||[];const conversationId=sessionStorage.getItem('valoraBotConversationId')||uid('conv');sessionStorage.setItem('valoraBotConversationId',conversationId);st.chatbotConversations.push({...message,conversationId,route:context.route,userRole:context.role,companyId:context.companyId});if(st.chatbotConversations.length>300)st.chatbotConversations=st.chatbotConversations.slice(-300);window.ValoraLogger?.info({category:'chatbot',action:message.sender==='user'?'question_sent':'answer_sent',message:'Evento do ValoraBot registrado.',metadata:{intent:message.intent,confidence:message.confidence,route:context.route},user:context.user});}
function logUnknown(question,ctx,intent){const st=state();st.chatbotUnansweredQuestions=st.chatbotUnansweredQuestions||[];st.chatbotUnansweredQuestions.push({id:uid('unk'),question:String(question||'').slice(0,500),role:ctx.role,route:ctx.route,status:'open',createdAt:new Date().toISOString()});window.ValoraLogger?.info({category:'chatbot',action:'unknown_question',message:'Pergunta sem resposta pelo ValoraBot.',metadata:{intent:intent.intent,confidence:intent.confidence,route:ctx.route},user:ctx.user});}
function buildAnswer(message,context=getChatContext()){const intent=detectIntent(message,context),note=permissionNote(intent,context);let hit=matchKnowledge(intent,message,context),text='',actions=[];if(intent.intent==='greeting')text=`Olá! Sou o ValoraBot. Posso orientar você como ${context.roleLabel} sobre pesquisas, convites, resultados, LGPD, manual e suporte humano.`;else if(note){text=`Entendi. ${note}\n\nSe quiser, posso abrir atendimento com o contexto desta conversa.`;actions=[{label:'Falar com atendente',type:'support'}];}
else if(hit){text=`Entendi. ${hit.answer}`;actions=[...(hit.actions||[])];if(window.ValoraManuals&&context.isLoggedIn)actions.push({label:'Abrir manual',type:'manual',value:intent.intent});}
else {text='Ainda não tenho certeza da melhor resposta para isso. Posso te mostrar a ajuda geral, abrir o manual do seu perfil ou encaminhar para um atendente.';actions=[{label:'Abrir manual',type:'manual',value:'help'},{label:'Falar com atendente',type:'support'}];logUnknown(message,context,intent);}
if(context.hasOverdueActions&&['dashboard','action_plan','how_to_start'].includes(intent.intent))text+='\n\nNotei que existem ações vencidas no seu contexto. Vale revisar o Plano de ação.';
return createBotMessage(text,{actions,intent:intent.intent,confidence:intent.confidence});}
function getSuggestedQuestions(context=getChatContext()){if(context.isPublicSurvey||!context.isLoggedIn)return ['Como respondo a pesquisa?','Meus dados estão seguros?','O que é LGPD?','Meu link expirou?','Quero falar com suporte'];return ({admin_valora:['Como cadastrar cliente?','Como configurar planos?','Como ver logs?','Como acompanhar implantação?'],empresa_admin:['Como cadastrar funcionários?','Como criar pesquisa?','Como enviar convites?','Como ver respostas?'],gestor_pesquisa:['Como criar questionário?','Como configurar pesos?','Como enviar pesquisa?','Como acompanhar pendentes?'],analista_resultados:['Como filtrar respostas?','Como gerar relatório?','Como interpretar dimensões?'],participante:['Como responder?','Como ver resultado?','Como baixar certificado?','Como solicitar exclusão de dados?']}[context.role]||['Como usar esta página?','Quais são minhas permissões?','Como falar com suporte?']);}
function startConversation(){const ctx=getChatContext(),msg=createBotMessage(`Olá! Sou o ValoraBot. Vou considerar seu perfil (${ctx.roleLabel}), a página atual e as permissões antes de responder.`,{intent:'greeting',confidence:1});saveHistory(msg,ctx);return msg;}
function sendMessage(text){const ctx=getChatContext(),intent=detectIntent(text,ctx),u=createUserMessage(text,{intent:intent.intent,confidence:intent.confidence});saveHistory(u,ctx);const answer=buildAnswer(text,ctx);saveHistory(answer,ctx);return answer;}
function escalateToHuman(extra={}){const ctx=getChatContext(),st=state(),conversation={subject:'Atendimento aberto pelo ValoraBot',origin:'bot_escalation',companyId:ctx.companyId,requesterUserId:ctx.user?.id||'',requesterName:ctx.user?.name||extra.name||'Visitante',requesterEmail:ctx.user?.email||extra.email||'',context:{route:ctx.route,role:ctx.role,conversationId:sessionStorage.getItem('valoraBotConversationId')}};window.ValoraLogger?.info({category:'support_chat',action:'conversation_escalated',message:'ValoraBot encaminhou para atendimento humano.',metadata:{route:ctx.route,role:ctx.role},user:ctx.user});return conversation;}
function getConversationHistory(){const id=sessionStorage.getItem('valoraBotConversationId'),st=state();return (st.chatbotConversations||[]).filter(x=>x.conversationId===id);}
window.ValoraChatbot={getChatContext,getKnowledgeBase,detectIntent,buildAnswer,buildBotAnswer:buildAnswer,getSuggestedQuestions,createBotMessage,createUserMessage,startConversation,sendMessage,escalateToHuman,getConversationHistory,INTENTS};
})();
