(function(){
'use strict';
window.ValoraConfig=Object.freeze({
  APP_VERSION:'8.6.8',
  RUNTIME_ENV:'production',
  STORAGE_MODE:'firebase',
  FIREBASE_ENABLED:true,
  FIREBASE_PLAN:'spark',
  ENABLE_CLOUD_FUNCTIONS:false,
  REQUIRE_AUTH_SERVER_VALIDATION:false,
  LOCAL_API_ENABLED:false,
  LOCAL_API_BASE_URL:'',
  EMAIL_TRANSPORT:'external-api',
  WHATSAPP_TRANSPORT:'external-api',
  EXTERNAL_API_BASE_URL:'https://api.valoragroup.mnsoft.com.br',
  observability:{enabled:true,consoleEnabled:false,consoleLevel:'warn',persistLogs:true,remoteLogsEnabled:false,telegramEnabled:false,legacyTraceEnabled:false,maskSensitiveData:true,maxLocalLogs:3000,environment:'production'},
  FIREBASE_CONFIG:{projectId:'gestordepesquisa',authDomain:'gestordepesquisa.firebaseapp.com',storageBucket:'gestordepesquisa.appspot.com'},
  STORE_KEY:'valoraPulseFinal800'
});
})();
