services:
  valora-postgres:
    image: postgres:16
    container_name: valora-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: valoradb
      POSTGRES_USER: valora
      POSTGRES_PASSWORD: valora_dev_123
    ports:
      - "5434:5432"
    volumes:
      - valora_postgres_data:/var/lib/postgresql/data
  valora-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: valora-api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=valora-postgres;Port=5432;Database=valoradb;Username=valora;Password=valora_dev_123;Pooling=true;Maximum Pool Size=50;Timeout=30;Command Timeout=60;Application Name=ValoraPulse
      Jwt__Issuer: ValoraPulse
      Jwt__Audience: ValoraPulse
      Jwt__Secret: trocar-por-segredo-forte-em-producao
      Jwt__ExpiresMinutes: 480
    ports:
      - "5080:8080"
    depends_on:
      - valora-postgres
volumes:
  valora_postgres_data:
