(function(){
'use strict';
const LEVELS=['debug','info','warn','error','critical','audit','security','test'];
const CATEGORIES=['system','auth','user','company','profile','permission','plan','module','form','survey','invitation','response','report','action_plan','notification','billing','integration','api','webhook','chatbot','support_chat','manual','firebase','telegram','security','test'];
const LOG_PRIORITY={debug:10,info:20,audit:25,warn:30,error:40,critical:50,security:40,test:20};
function shouldWriteConsole(level,cfg){if(cfg.consoleEnabled!==true)return false;const configuredLevel=cfg.consoleLevel||'warn';return (LOG_PRIORITY[level]||20)>=(LOG_PRIORITY[configuredLevel]||30);}
const DEFAULT_CONFIG={enabled:true,consoleEnabled:true,consoleLevel:'debug',persistLogs:true,remoteLogsEnabled:false,telegramLevels:['critical','error','security'],telegramCategories:['system','security','billing','integration','firebase'],maskSensitiveData:true,maxLocalLogs:3000,environment:'local'};
function uid(p='log'){return `${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,9)}`;}
function maskEmail(email){const [name,domain]=String(email||'').split('@');if(!domain)return '';return `${name.slice(0,2)}***@${domain}`;}
function maskDocument(v){const d=String(v||'').replace(/\D/g,'');if(d.length<=4)return d?'***':'';return `${d.slice(0,2)}***${d.slice(-2)}`;}
function maskToken(v){const s=String(v||'');return s.length>10?`${s.slice(0,4)}***${s.slice(-4)}`:'***';}
function sanitizeValue(k,v){const key=String(k||'').toLowerCase();if(/password|senha|token|secret|api.?key|authorization|cookie/.test(key))return maskToken(v);if(/cpf|cnpj|document/.test(key))return maskDocument(v);if(/email/.test(key))return maskEmail(v);return v;}
function sanitizeLogMetadata(obj,depth=0){if(obj==null||depth>4)return obj;if(typeof obj!=='object')return obj;if(Array.isArray(obj))return obj.slice(0,50).map(v=>sanitizeLogMetadata(v,depth+1));const out={};Object.entries(obj).forEach(([k,v])=>{out[k]=typeof v==='object'?sanitizeLogMetadata(v,depth+1):sanitizeValue(k,v);});return out;}
function sanitizeTelegramMessage(log){const safe=sanitizeLogMetadata(log);delete safe.stack;return safe;}
function config(){return {...DEFAULT_CONFIG,...(window.ValoraConfig?.observability||{}),...(window.ValoraState?.settings?.observability||{})};}
function shouldTelegram(log,cfg){if(log.isTest&&log.action==='telegram_test')return true;if(!cfg.telegramEnabled)return false;return (cfg.telegramLevels||[]).includes(log.level)||(cfg.telegramCategories||[]).includes(log.category);}
async function persistRemote(log){const capabilities=window.ValoraRuntime?.getCapabilities?.();if(!capabilities?.logs?.canPersistRemote)return false;if(!window.ValoraFirebaseServices?.functions)return false;try{const fn=window.ValoraFirebaseServices.functions.httpsCallable('logServerEvent');await fn(sanitizeTelegramMessage(log));return true;}catch(_){return false;}}
async function sendTelegram(log){const capabilities=window.ValoraRuntime?.getCapabilities?.();if(!capabilities?.logs?.canPersistRemote)return false;try{if(!window.ValoraFirebaseServices?.functions)return false;const fn=window.ValoraFirebaseServices.functions.httpsCallable('sendTelegramAlert');await fn(sanitizeTelegramMessage({level:log.level,category:log.category,title:log.action,message:log.message,companyId:log.companyId,route:log.route,metadata:log.metadata,logId:log.id,isTest:log.isTest}));log.telegramSent=true;log.telegramSentAt=new Date().toISOString();return true;}catch(e){console.warn('[Valora Pulse] Telegram indisponível',e);return false;}}
function createSystemLog(event={}){const cfg=config();if(!cfg.enabled)return null;const state=window.ValoraState;const user=event.user||{};const level=LEVELS.includes(event.level)?event.level:'info';const category=CATEGORIES.includes(event.category)?event.category:'system';const companyId=event.companyId||user.companyId||'';const company=(state?.companies||[]).find(c=>c.id===companyId);
 const err=event.error||{};const log={id:event.id||uid('log'),level,category,action:String(event.action||'event').slice(0,120),message:String(event.message||err.message||event.action||'Evento registrado').slice(0,1000),companyId,companyName:event.companyName||company?.name||'',userId:event.userId||user.id||user.uid||'',userName:event.userName||user.name||'',userEmailMasked:maskEmail(event.userEmail||user.email||''),userRole:event.userRole||user.role||'',entity:event.entity||event.entityType||'',entityId:event.entityId||'',route:event.route||location.hash||location.pathname,environment:event.environment||cfg.environment||window.ValoraConfig?.STORAGE_MODE||'local',appVersion:event.appVersion||window.ValoraConfig?.APP_VERSION||'',metadata:sanitizeLogMetadata(event.metadata||event.detail||{}),errorCode:err.code||event.errorCode||'',errorMessage:String(err.message||event.errorMessage||'').slice(0,1000),stack:cfg.maskSensitiveData?String(err.stack||event.stack||'').replace(/(token|password|senha|secret)=([^\s&]+)/gi,'$1=***'):String(err.stack||event.stack||''),ip:event.ip||'',userAgent:event.userAgent||navigator.userAgent||'',telegramSent:false,telegramSentAt:'',isTest:!!event.isTest,createdAt:event.createdAt||new Date().toISOString()};
 if(shouldWriteConsole(level,cfg)){const m=`[Valora ${level}] ${category}.${log.action}: ${log.message}`;(level==='error'||level==='critical')?console.error(m,log):(level==='warn'||level==='security')?console.warn(m,log):console.info(m,log);}
 if(cfg.persistLogs&&state){state.logs=state.logs||[];state.logs.push(log);if(state.logs.length>(cfg.maxLocalLogs||3000))state.logs=state.logs.slice(-(cfg.maxLocalLogs||3000));}
 if(window.ValoraRuntime?.getCapabilities?.().logs.canPersistRemote)persistRemote(log);
 if(shouldTelegram(log,cfg)&&window.ValoraRuntime?.getCapabilities?.().logs.canPersistRemote)sendTelegram(log);return log;}
 const api={DEFAULT_CONFIG,maskEmail,maskDocument,maskToken,sanitizeLogMetadata,sanitizeTelegramMessage,createSystemLog,logDebug:e=>createSystemLog({...e,level:'debug'}),logInfo:e=>createSystemLog({...e,level:'info'}),logWarn:e=>createSystemLog({...e,level:'warn'}),logError:e=>createSystemLog({...e,level:'error'}),logCritical:e=>createSystemLog({...e,level:'critical'}),logAudit:e=>createSystemLog({...e,level:'audit'}),logSecurity:e=>createSystemLog({...e,level:'security',category:e?.category||'security'}),logTest:e=>createSystemLog({...e,level:e?.level||'test',category:'test',isTest:true})};
 window.ValoraLogs=api;window.ValoraLogger=window.ValoraLogger||{debug:api.logDebug,info:api.logInfo,warn:api.logWarn,error:api.logError,critical:api.logCritical,audit:api.logAudit,security:api.logSecurity,test:api.logTest,logEvent:api.createSystemLog,logError:api.logError,sanitizeMetadata:api.sanitizeLogMetadata,sanitizeExternalLogPayload:api.sanitizeTelegramMessage};
})();
