(function(){
'use strict';
const LEVELS=['debug','info','warn','error','critical','audit','security','test'];
const LOG_PRIORITY={debug:10,info:20,audit:25,warn:30,error:40,critical:50,security:40,test:20};
function shouldWriteConsole(level){const cfg=window.ValoraConfig?.observability||{};if(cfg.consoleEnabled!==true)return false;const configuredLevel=cfg.consoleLevel||'warn';return (LOG_PRIORITY[level]||20)>=(LOG_PRIORITY[configuredLevel]||30);}
const CATEGORIES=['system','auth','user','company','profile','permission','plan','module','form','survey','invitation','response','report','action_plan','notification','billing','integration','webhook','chatbot','support_chat','manual','firebase','telegram','test'];
function uid(p='log'){return `${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,9)}`;}
function maskEmail(email){const [n,d]=String(email||'').split('@');if(!d)return '';return `${n.slice(0,2)}***@${d.replace(/^(.).+(@?.*)?$/,'$1***')}`;}
function maskDocument(v){const d=String(v||'').replace(/\D/g,'');if(!d)return '';return d.length<=4?'***':`${d.slice(0,2)}***${d.slice(-2)}`;}
function maskToken(v){const s=String(v||'');return s.length>12?`${s.slice(0,4)}***${s.slice(-4)}`:'***';}
function sanitizeUrl(url){try{const u=new URL(String(url||''),location.origin);['token','rt','key','apiKey','secret','senha','password','authorization'].forEach(k=>{if(u.searchParams.has(k))u.searchParams.set(k,maskToken(u.searchParams.get(k)));});return u.toString();}catch(_){return String(url||'').replace(/(token|rt|key|secret|senha|password)=([^&\s]+)/gi,'$1=***');}}
function sanitizePrimitive(k,v){const key=String(k||'').toLowerCase();if(/password|senha|token|secret|api.?key|authorization|cookie|telegram/.test(key))return maskToken(v);if(/cpf|cnpj|document/.test(key))return maskDocument(v);if(/email/.test(key))return maskEmail(v);if(/url|link/.test(key))return sanitizeUrl(v);return v;}
function sanitizeMetadata(obj,depth=0){if(obj==null||depth>5)return obj;if(typeof obj!=='object')return obj;if(Array.isArray(obj))return obj.slice(0,50).map(v=>sanitizeMetadata(v,depth+1));const out={};Object.entries(obj).forEach(([k,v])=>{out[k]=typeof v==='object'?sanitizeMetadata(v,depth+1):sanitizePrimitive(k,v);});return out;}
function sanitizeError(error){if(!error)return {};return {errorCode:error.code||'',errorMessage:String(error.message||error).slice(0,1000),stack:String(error.stack||'').replace(/(token|password|senha|secret|api.?key)=([^\s&]+)/gi,'$1=***')};}
function context(event={}){const st=window.ValoraState||{},u=event.user||st.users?.find(x=>x.id===st.session?.userId)||{},cid=event.companyId||u.companyId||'',c=st.companies?.find(x=>x.id===cid)||{};return {companyId:cid,companyName:event.companyName||c.name||'',userId:event.userId||u.id||u.uid||'',userName:event.userName||u.name||'',userEmailMasked:maskEmail(event.userEmail||u.email||''),userRole:event.userRole||u.role||''};}
function normalize(event={}){const err=sanitizeError(event.error);const ctx=context(event);return {id:event.id||uid(),level:LEVELS.includes(event.level)?event.level:'info',category:CATEGORIES.includes(event.category)?event.category:'system',action:String(event.action||'event').slice(0,120),message:String(event.message||err.errorMessage||'Evento registrado').slice(0,1000),...ctx,entity:event.entity||event.entityType||'',entityId:event.entityId||'',route:event.route||window.currentRoute||location.hash||location.pathname,url:sanitizeUrl(event.url||location.href),environment:event.environment||window.ValoraConfig?.STORAGE_MODE||'local',appVersion:event.appVersion||window.ValoraConfig?.APP_VERSION||'',metadata:sanitizeMetadata(event.metadata||{}),errorCode:event.errorCode||err.errorCode,errorMessage:event.errorMessage||err.errorMessage,stack:event.stack||err.stack,createdAt:event.createdAt||new Date().toISOString(),source:event.source||'frontend',isTest:!!event.isTest,telegramSent:!!event.telegramSent};}
function sanitizeExternalLogPayload(log){const out=sanitizeMetadata({...log});delete out.stack;delete out.userId;return out;}
function logEvent(event){const log=normalize(event);const st=window.ValoraState;if(st){st.logs=st.logs||[];st.logs.push(log);if(st.logs.length>3000)st.logs=st.logs.slice(-3000);}const method=log.level==='error'||log.level==='critical'?'error':log.level==='warn'||log.level==='security'?'warn':'info';if(shouldWriteConsole(log.level))console[method]?.(`[Valora ${log.level}] ${log.category}.${log.action}`,log);return log;}
function logError(event){return logEvent({...event,level:event.level||'error'});}
function wrap(label,category,action,fn,options={}){return function(...args){try{logEvent({level:'debug',category,action,message:`Iniciando: ${label}`,metadata:options.metadata});const r=fn.apply(this,args);logEvent({level:'info',category,action,message:`Concluído: ${label}`,metadata:options.metadata});return r;}catch(error){logError({category,action,message:`Erro em: ${label}`,error,metadata:options.metadata});throw error;}};}
function wrapAsync(label,category,action,fn,options={}){return async function(...args){try{logEvent({level:'debug',category,action,message:`Iniciando: ${label}`,metadata:options.metadata});const r=await fn.apply(this,args);logEvent({level:'info',category,action,message:`Concluído: ${label}`,metadata:options.metadata});return r;}catch(error){logError({category,action,message:`Erro em: ${label}`,error,metadata:options.metadata});throw error;}};}
const api={debug:e=>logEvent({...e,level:'debug'}),info:e=>logEvent({...e,level:'info'}),warn:e=>logEvent({...e,level:'warn'}),error:e=>logEvent({...e,level:'error'}),critical:e=>logEvent({...e,level:'critical'}),audit:e=>logEvent({...e,level:'audit'}),security:e=>logEvent({...e,level:'security',category:e?.category||'security'}),test:e=>logEvent({...e,level:e?.level||'test',category:'test',isTest:true}),wrap,wrapAsync,logEvent,logError,maskEmail,maskDocument,maskToken,sanitizeUrl,sanitizeMetadata,sanitizeError,sanitizeExternalLogPayload,LEVELS,CATEGORIES};
window.ValoraLogger=api;window.ValoraLogs=window.ValoraLogs||{logDebug:api.debug,logInfo:api.info,logWarn:api.warn,logError:api.error,logCritical:api.critical,logAudit:api.audit,logSecurity:api.security,logTest:api.test,createSystemLog:api.logEvent,sanitizeLogMetadata:api.sanitizeMetadata,sanitizeTelegramMessage:api.sanitizeExternalLogPayload};
})();
