(function(){
'use strict';
const baseFaq=[{q:'Meus dados estão seguros?',a:'O Valora Pulse usa segregação por empresa, perfis, links com token e logs. Dados sensíveis não devem ser enviados em canais externos.'},{q:'Como peço ajuda?',a:'Use o ValoraBot ou o botão Falar com atendente para abrir atendimento com contexto.'}];
function manual(title,description,quickStart,sections,permissionsSummary,nextSteps){return {title,description,quickStart,sections:sections.map(s=>({...s,faq:[...(s.faq||[]),...baseFaq]})),commonQuestions:baseFaq,permissionsSummary,nextSteps};}
const PROFILE_MANUALS={
 public:manual('Ajuda e perguntas frequentes','Visão pública do Valora Pulse para visitantes e respondentes por link.',['Entenda o convite recebido.','Abra o link de pesquisa e confira a empresa responsável.','Leia o termo LGPD antes de responder.'],[{title:'Uso público',content:'O Valora Pulse apoia diagnósticos, pesquisas, resultados e planos de ação. Sem login, você acessa informações públicas, LGPD, planos e suporte.',steps:['Responder pesquisa por link seguro','Solicitar suporte','Conhecer planos em nível público'],relatedRoutes:['home','plans','lgpd']}],'Não há acesso a dados internos sem login.','Se precisar de ajuda, fale com o bot ou abra atendimento.'),
 admin_valora:manual('Manual Admin Valora','Administra a operação global, clientes, planos, módulos, financeiro, logs, backup, suporte e integrações.',['Revise dashboard global.','Cadastre cliente/plano/módulos.','Acompanhe logs e atendimentos.'],[{title:'Operação global',content:'Use as abas Clientes, Planos, Módulos, Financeiro, Logs, Integrações e Backup para governar a plataforma.',steps:['Criar cliente','Configurar plano','Ver logs','Testar Telegram'],relatedRoutes:['admin/clients','admin/plans','admin/logs','admin/support']}],'Acesso global e canHandleGlobalSupport.','Monitore logs críticos e fila de suporte.'),
 consultor_valora:manual('Manual Consultor Valora','Acompanha clientes, pesquisas, respostas, relatórios e suporte consultivo com limites operacionais.',['Abra clientes.','Analise respostas.','Apoie atendimentos permitidos.'],[{title:'Acompanhamento',content:'Consulte operação dos clientes e relatórios sem alterar configurações críticas.',steps:['Filtrar cliente','Ler pesquisas','Gerar relatório'],relatedRoutes:['admin/clients','admin/reports','admin/support']}],'Leitura ampla, sem financeiro/backup críticos.','Escalone alterações sensíveis ao Admin Valora.'),
 empresa_admin:manual('Manual Administrador da Empresa','Configura empresa, funcionários, perfis, questionários, pesquisas, convites, respostas, plano e suporte.',['Cadastre funcionários.','Crie formulário.','Crie pesquisa e envie convites.'],[{title:'Implantação',content:'Comece por usuários/funcionários, depois formulários, pesquisas, convites e relatórios.',steps:['Cadastrar funcionários','Escolher perfis','Criar pesquisa','Acompanhar respostas'],relatedRoutes:['empresa/users','empresa/forms','empresa/surveys','empresa/reports']}],'Administra a própria empresa e pode atender suporte da empresa.','Revise permissões e plano contratado.'),
 gestor_pesquisa:manual('Manual Gestor de Pesquisa','Cria formulários, configura perguntas, cria pesquisas, envia convites e acompanha resultados.',['Criar formulário.','Configurar pesos/dimensões.','Enviar convites.'],[{title:'Pesquisa',content:'Monte questionários com escala, opções, pesos e faixas; publique pesquisas com validade e LGPD.',steps:['Criar formulário','Criar pesquisa','Enviar convite','Acompanhar pendentes'],relatedRoutes:['empresa/forms','empresa/surveys']}],'Cria e envia pesquisas da própria empresa.','Peça ao admin ajustes de usuários ou plano.'),
 analista_resultados:manual('Manual Analista de Resultados','Consulta dashboards, filtros, respostas, dimensões, indicadores e exportações permitidas.',['Abra Respostas.','Aplique filtros.','Exporte conforme permissão.'],[{title:'Análise',content:'Use respostas e relatórios para interpretar dimensões e indicadores sem alterar pesquisas.',steps:['Filtrar respostas','Ver gráficos','Exportar relatório'],relatedRoutes:['empresa/responses','empresa/reports']}],'Leitura de respostas e relatórios.','Solicite novas pesquisas a um gestor.'),
 gestor_area:manual('Manual Gestor de Área','Acompanha respostas, relatórios e ações da própria área com escopo limitado.',['Veja dashboard da área.','Revise ações vencidas.','Acompanhe relatórios permitidos.'],[{title:'Área',content:'O acesso é restrito ao departamento/área vinculado ao perfil.',steps:['Abrir respostas da área','Acompanhar plano de ação','Reportar bloqueios'],relatedRoutes:['empresa/responses','empresa/actionPlans']}],'Restrito à área.','Procure o admin para ajustes de escopo.'),
 participante:manual('Manual Participante','Responde pesquisas, acompanha histórico, resultado individual, certificados e privacidade.',['Abra pesquisas disponíveis.','Responda com LGPD.','Baixe certificado quando liberado.'],[{title:'Participação',content:'Você não cria pesquisas; apenas responde e consulta histórico permitido.',steps:['Responder pesquisa','Ver resultado','Consultar LGPD'],relatedRoutes:['participante/available','participante/responses','participante/privacy']}],'Responde pesquisas e vê histórico permitido.','Fale com suporte se faltar convite.'),
 convidado_externo:manual('Manual Convidado Externo','Responde por link seguro, com privacidade e suporte quando necessário.',['Abra o link.','Leia LGPD.','Envie a resposta.'],[{title:'Link externo',content:'O convidado usa o link recebido e não acessa portal administrativo.',steps:['Validar empresa','Responder','Guardar resultado se exibido'],relatedRoutes:['lgpd']}],'Acesso limitado ao link recebido.','Abra atendimento se o link falhar.')
};
function getManualForUser(user){return PROFILE_MANUALS[user?.role]||PROFILE_MANUALS.public;}
function getContextualHelp(user,route){const m=getManualForUser(user);const sec=m.sections.find(s=>(s.relatedRoutes||[]).some(r=>String(route||'').includes(r.split('/')[0])))||m.sections[0];return {manual:m,section:sec};}
window.ValoraManuals={PROFILE_MANUALS,getManualForUser,getContextualHelp};
})();
