(function(global){
'use strict';
const A=()=>global.ValoraAnalytics||{};
const n=v=>Number.isFinite(Number(v))?Number(v):0;
const pct=(a,b)=>b?Math.round((a/b)*100):0;
const avg=a=>a.length?a.reduce((s,x)=>s+n(x),0)/a.length:0;
const dateOf=v=>v?.toDate?v.toDate():(v?.seconds?new Date(v.seconds*1000):new Date(v||Date.now()));
const br=v=>dateOf(v).toLocaleDateString('pt-BR');
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const byId=(arr,id)=>(arr||[]).find(x=>x.id===id)||null;
const planOf=(state,c)=>byId(state.plans,c?.planId)||{};
const activeSurvey=s=>String(s?.status||'active')==='active'&&(!s.expiresAt||dateOf(s.expiresAt)>=new Date());
function level(score){return score>=4.25?'Excelente':score>=3.5?'Bom':score>=2.5?'Atenção':score>0?'Crítico':'Sem dados';}
function buildExecutiveSummary(metrics={}){const m=n(metrics.normalized5||metrics.average),rate=n(metrics.responseRate),best=metrics.bestDimension?.label||metrics.bestDimension||'sem dimensão consolidada',worst=metrics.criticalDimension?.label||metrics.worstDimension||'sem dimensão consolidada',total=n(metrics.totalCompleted||metrics.responses||metrics.completed);if(!total)return 'Ainda não há respostas suficientes para gerar análise executiva. Mantenha a comunicação ativa e acompanhe a chegada dos primeiros dados.';let txt=`No período analisado, o resultado geral foi ${m.toFixed(2)}/5 (${level(m)}), com melhor desempenho em ${best} e maior oportunidade de melhoria em ${worst}. A taxa de resposta foi de ${rate}%, com ${total} resposta(s) concluída(s). `;if(rate<40)txt+='A adesão está abaixo do ideal e requer reforço de comunicação, reenvio de convites e eventual ampliação do prazo. ';if(metrics.criticalDimension&&n(metrics.criticalDimension.normalized5)<2.5)txt+=`A dimensão ${metrics.criticalDimension.label} apresenta baixa maturidade e deve receber plano de ação específico. `;if(m>=4)txt+='Os resultados indicam boa maturidade geral; recomenda-se manter acompanhamento periódico e aprofundar pontos finos de melhoria. ';if(total<5)txt+='O volume de respostas ainda é baixo; interprete os resultados como indicativos preliminares. ';return txt.trim();}
function recommendations(metrics={}){const out=[];if(!n(metrics.totalCompleted||metrics.responses||metrics.completed))out.push('Ainda não há respostas suficientes para gerar análise executiva.');if(n(metrics.sent)===0)out.push('Nenhum convite foi enviado no período analisado.');if(n(metrics.responseRate)<40&&n(metrics.sent)>0)out.push('A taxa de resposta está abaixo do ideal. Recomenda-se reenviar convites, ampliar o prazo e reforçar a comunicação interna.');if(metrics.criticalDimension&&n(metrics.criticalDimension.normalized5)<2.5)out.push(`A dimensão ${metrics.criticalDimension.label} apresenta baixa maturidade. Recomenda-se criar plano de ação específico, com responsáveis, prazos e indicadores de acompanhamento.`);if(n(metrics.normalized5||metrics.average)>4)out.push('Os resultados indicam boa maturidade geral. Recomenda-se manter acompanhamento periódico e aprofundar análise dos pontos de melhoria.');if(n(metrics.totalCompleted||metrics.responses||metrics.completed)>0&&n(metrics.totalCompleted||metrics.responses||metrics.completed)<5)out.push('O volume de respostas ainda é baixo. Os resultados devem ser interpretados como indicativos preliminares.');return out;}
function actionPlan(dimensions=[]){return [...dimensions].sort((a,b)=>n(a.normalized5)-n(b.normalized5)).slice(0,5).map((d,i)=>({priority:i<2?'Alta':'Média',dimension:d.label,problem:n(d.normalized5)<2.5?'Baixa maturidade':'Oportunidade de evolução',action:`Realizar workshop de ${d.label}, definir responsáveis, ritos de acompanhamento e indicador mensal.`,owner:'Liderança/RH',due:i<2?'30 dias':'60 dias'}));}

function actionPlansForReport(state,companyId){return (state.actionPlans||[]).filter(a=>!companyId||a.companyId===companyId).map(a=>({priority:a.priority,dimension:a.dimensionName||'—',action:a.title,owner:a.responsibleName||'A definir',due:a.dueDate||'',status:a.status,progress:a.progress||0,source:a.source}));}
function mergeActionPlan(suggested,created){return [...created,...suggested.map(a=>({priority:a.priority,dimension:a.dimension,action:a.action,owner:a.owner,due:a.due,status:'suggested',progress:0,source:'executive_report'}))];}
function base(state,filters={}){const resp=A().getResponseMetrics(state,filters), inv=A().getInvitationMetrics(state,filters.companyId), series=A().getTimeSeriesMetrics(state,filters);return {resp,inv,series,summary:buildExecutiveSummary({...resp,...inv}),recommendations:recommendations({...resp,...inv}),actionPlan:actionPlan(resp.dimensions),generatedAt:new Date().toISOString()};}
function rowsFromResponses(state,filters={}){return A().completedResponses(state,filters).map(r=>({participant:r.participant?.name||'',email:r.participant?.email||r.email||'',company:byId(state.companies,r.companyId)?.name||'',survey:byId(state.surveys,r.surveyId)?.title||'',date:br(r.createdAt),index:n(r.normalized5).toFixed(2),level:r.level?.label||level(r.normalized5)}));}
function buildCompanyExecutiveReport(state,companyId,filters={}){const company=byId(state.companies,companyId), b=base(state,{...filters,companyId}), usage=A().getPlanUsageMetrics(state,companyId);return {type:'company-executive',title:`Relatório Executivo — ${company?.name||'Empresa'}`,subtitle:`Período analisado: ${filters.from?br(filters.from):'início'} a ${filters.to?br(filters.to):br(new Date())}`,company,metrics:{employees:(state.users||[]).filter(u=>u.companyId===companyId&&u.role!=='empresa_admin').length,activeSurveys:(state.surveys||[]).filter(s=>s.companyId===companyId&&activeSurvey(s)).length,sent:b.inv.sent,completed:b.resp.totalCompleted,responseRate:b.inv.responseRate,average:b.resp.normalized5,bestDimension:b.resp.bestDimension,criticalDimension:b.resp.criticalDimension},summary:b.summary,recommendations:b.recommendations,actionPlan:mergeActionPlan(b.actionPlan,actionPlansForReport(state,companyId)),sections:{actionPlans:actionPlansForReport(state,companyId),dimensions:b.resp.dimensions,distribution:b.resp.distribution,series:b.series,usage:usage.items,responses:rowsFromResponses(state,{companyId})},generatedAt:b.generatedAt};}
function buildGlobalExecutiveReport(state,filters={}){const g=A().getGlobalDashboardMetrics(state), b=base(state,filters);const ranking=(state.companies||[]).map(c=>{const inv=A().getInvitationMetrics(state,c.id);return {company:c.name,plan:planOf(state,c).name||'Plano não identificado',responses:inv.completed,sent:inv.sent,responseRate:inv.responseRate};}).sort((a,b)=>b.responses-a.responses);return {type:'global-executive',title:'Relatório Executivo Global — Valora Pulse',subtitle:'Uso interno Valora Group',metrics:{totalClients:g.totalClients,activeClients:g.activeClients,onboardingClients:g.onboarding.filter(o=>o.status!=='implantado').length,stuckClients:g.stuck.length,mrr:money(g.mrr),topPlan:g.topPlan?.label||'—',monthResponses:g.responses.totalCompleted,averageResponseRate:g.invites.responseRate,activeSurveys:g.activeSurveys,nearLimit:g.nearLimit.length,noResponse:ranking.filter(r=>!r.responses).length},summary:b.summary,recommendations:[...b.recommendations,'Priorizar clientes travados, próximos do limite ou sem respostas para ação consultiva/comercial.'],actionPlan:mergeActionPlan(b.actionPlan,actionPlansForReport(state,'')),sections:{actionPlans:actionPlansForReport(state,''),ranking,plans:g.plans,onboarding:g.onboarding.map(o=>({company:o.company?.name,status:o.status,percent:o.percent})),alerts:ranking.filter(r=>!r.responses||r.responseRate<40)},generatedAt:b.generatedAt};}
function buildSurveyReport(state,surveyId,filters={}){const survey=byId(state.surveys,surveyId), form=byId(state.forms,survey?.formId), b=base(state,{...filters,surveyId});return {type:'survey',title:`Relatório por Pesquisa — ${survey?.title||'Pesquisa'}`,subtitle:`Formulário: ${form?.name||'não identificado'} • Status: ${survey?.status||'—'}`,survey,form,metrics:{sent:b.inv.sent,completed:b.resp.totalCompleted,responseRate:b.inv.responseRate,average:b.resp.normalized5},summary:b.summary,recommendations:b.recommendations,actionPlan:mergeActionPlan(b.actionPlan,actionPlansForReport(state,survey?.companyId)),sections:{actionPlans:actionPlansForReport(state,survey?.companyId).filter(a=>!surveyId||true),dimensions:b.resp.dimensions,distribution:b.resp.distribution,bestQuestions:[],worstQuestions:[],qualitative:A().completedResponses(state,{surveyId}).flatMap(r=>Object.values(r.answers||{}).filter(x=>typeof x==='string'))},generatedAt:b.generatedAt};}
function buildParticipantReport(state,responseId){const r=byId(state.responses,responseId), survey=byId(state.surveys,r?.surveyId);const dims=Object.entries(r?.byDimension||{}).map(([label,v])=>({label,normalized5:n(v.normalized5),percentage:n(v.percentage)}));return {type:'participant',title:`Relatório Individual — ${r?.participant?.name||'Participante'}`,subtitle:`${survey?.title||'Pesquisa'} • ${r?br(r.createdAt):''}`,metrics:{average:n(r?.normalized5),percentage:n(r?.percentage),level:r?.level?.label||level(r?.normalized5)},summary:buildExecutiveSummary({normalized5:r?.normalized5,totalCompleted:r?1:0,bestDimension:dims[0],criticalDimension:dims[dims.length-1]}),recommendations:[r?.level?.recommendation||'Use as dimensões com menor índice como prioridade individual.'],actionPlan:actionPlan(dims),sections:{dimensions:dims,qualitative:[]},generatedAt:new Date().toISOString()};}
function buildDimensionReport(state,companyId,dimensionId,filters={}){const b=base(state,{...filters,companyId});const dim=b.resp.dimensions.find(d=>d.label===dimensionId||d.id===dimensionId)||b.resp.dimensions[0];return {type:'dimension',title:`Relatório por Dimensão — ${dim?.label||'Dimensão'}`,subtitle:byId(state.companies,companyId)?.name||'',metrics:{average:n(dim?.normalized5),percentage:n(dim?.percentage),responses:n(dim?.count)},summary:buildExecutiveSummary({...b.resp,criticalDimension:dim}),recommendations:recommendations({...b.resp,criticalDimension:dim}),actionPlan:actionPlan(dim?[dim]:[]),sections:{dimension:dim,series:b.series,questions:[]},generatedAt:b.generatedAt};}
function buildOnboardingReport(state,companyId){const o=A().getOnboardingMetrics(state,companyId);return {type:'onboarding',title:`Relatório de Implantação — ${o.company?.name||'Empresa'}`,subtitle:`Status: ${o.status} • ${o.percent}% concluído`,metrics:{users:o.employees?.length||0,surveys:o.surveys?.length||0,activeSurveys:o.activeSurveys?.length||0,invitations:o.invitations?.length||0,responses:o.responses?.length||0},summary:`Implantação em status ${o.status}, com ${o.percent}% dos marcos concluídos. Próximo passo recomendado: avançar a primeira pendência operacional e remover travas de adoção.`,recommendations:['Confirmar responsável interno, concluir etapas pendentes e acompanhar primeira resposta.'],actionPlan:[],sections:o,generatedAt:new Date().toISOString()};}
function buildPlanUsageReport(state,companyId){const u=A().getPlanUsageMetrics(state,companyId), c=byId(state.companies,companyId);return {type:'plan-usage',title:`Relatório de Uso do Plano — ${c?.name||'Empresa'}`,subtitle:`Plano contratado: ${u.plan?.name||'Plano não identificado'}`,metrics:{plan:u.plan?.name||'Plano não identificado'},summary:u.items.some(i=>i.nearLimit)?'Há uso acima de 80% em ao menos um limite. Recomenda-se avaliar upgrade ou ajuste contratual.':'Uso dentro dos limites contratados no período.',recommendations:u.items.some(i=>i.nearLimit)?['Recomendação de upgrade por uso superior a 80% em limite contratado.']:['Manter acompanhamento mensal de uso.'],actionPlan:[],sections:{usage:u.items,modules:u.plan?.enabledModules||[]},generatedAt:new Date().toISOString()};}
global.ValoraReports={buildExecutiveSummary,buildGlobalExecutiveReport,buildCompanyExecutiveReport,buildSurveyReport,buildParticipantReport,buildDimensionReport,buildOnboardingReport,buildPlanUsageReport};
})(window);
