using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Valora.Application.Common;
using Valora.Application.Access;
using Valora.Application.Workspace;
using Valora.Application.ActionCenter;

namespace Valora.Api.Controllers;

[Authorize, ApiController, Route("api/v1")]
public sealed class WorkspaceController(IExecutiveWorkspaceService workspace, IMyDayService day, IExecutivePriorityService priorities,
    IGlobalSearchService search, IWorkspaceItemService items, IRecentItemsService recent, IQuickActionService actions,
    ICurrentRequestContext requestContext, PriorityActionService priorityActions, ActionPlanService actionPlans, ActionItemService actionItems, ILogger<WorkspaceController> logger) : ControllerBase {
    private CurrentRequestContext Context => requestContext.GetCurrent();
    private Guid OrganizationId => Context.EffectiveOrganizationId ?? Guid.Empty;
    private Guid UserId => Context.UserId ?? Guid.Empty;
    private bool OrganizationWide => Context.IsGlobalAdministrator || Context.Roles.Contains("admin_cliente", StringComparer.OrdinalIgnoreCase);
    private IActionResult MissingContext() => BadRequest(new { code = "ORGANIZATION_REQUIRED", message = "Selecione uma organização para abrir seu Workspace.", correlationId = HttpContext.TraceIdentifier });
    private IActionResult? InvalidContext() => OrganizationId == Guid.Empty ? MissingContext() : UserId == Guid.Empty ? Unauthorized(new { code = "USER_REQUIRED", message = "Sua sessão precisa ser renovada.", correlationId = HttpContext.TraceIdentifier }) : null;
    [HttpGet("workspace"), Authorize(Policy=ValoraPermissions.Priorities.Read)] public async Task<IActionResult> Get(CancellationToken ct) => InvalidContext() is { } error ? error : Ok(await workspace.GetAsync(OrganizationId, UserId, OrganizationWide, ct));
    [HttpGet("workspace/my-day")] public async Task<IActionResult> MyDay(CancellationToken ct) => InvalidContext() is { } error ? error : Ok(await day.GetAsync(OrganizationId, UserId, OrganizationWide, ct));
    [HttpGet("workspace/priorities"), Authorize(Policy=ValoraPermissions.Priorities.Read)] public async Task<IActionResult> Priorities([FromQuery] PriorityListQuery query,CancellationToken ct) => InvalidContext() is { } error ? error : Ok(await priorities.ListAsync(OrganizationId, UserId, OrganizationWide, query, ct));
    [HttpGet("workspace/priorities/{id:guid}"), Authorize(Policy=ValoraPermissions.Priorities.Read)] public async Task<IActionResult> Priority(Guid id,CancellationToken ct) { if(InvalidContext() is { } error)return error; var value=await priorities.GetAsync(OrganizationId,UserId,id,OrganizationWide,CanManage,ct); if(value is null)return NotFound(new{code="PRIORITY_NOT_FOUND",message="Prioridade não encontrada.",correlationId=HttpContext.TraceIdentifier}); try { await items.RecordOpenAsync(OrganizationId,UserId,id,OrganizationWide,ct); } catch(Exception ex) when(ex is not OperationCanceledException) { logger.LogWarning(ex,"Não foi possível registrar acesso recente à prioridade {PriorityId} na organização {OrganizationId}",id,OrganizationId); } return Ok(value); }
    [HttpGet("workspace/priorities/{id:guid}/activities"), Authorize(Policy=ValoraPermissions.Priorities.Read)] public async Task<IActionResult> PriorityActivities(Guid id,CancellationToken ct)=>InvalidContext() is { } error?error:Ok(await priorityActions.List(OrganizationId,id,UserId,OrganizationWide,ct));
    [HttpGet("workspace/action-plans"), Authorize(Policy="action.read")] public async Task<IActionResult> ActionPlans([FromQuery] OptionQuery query,CancellationToken ct=default) => InvalidContext() is { } error ? error : Ok(await actionPlans.Options(OrganizationId,UserId,OrganizationWide,query,ct));
    [HttpGet("workspace/action-items"), Authorize(Policy="action.read")] public async Task<IActionResult> ActionItems([FromQuery] OptionQuery query,CancellationToken ct=default) => InvalidContext() is { } error ? error : Ok(await actionItems.Options(OrganizationId,UserId,OrganizationWide,query,ct));
    [HttpPost("workspace/priorities/{id:guid}/activities/link"), Authorize(Policy="action.manage")] public async Task<IActionResult> LinkActivity(Guid id,[FromBody] LinkPriorityActionRequest request,CancellationToken ct){if(InvalidContext() is { } error)return error;if(!ModelState.IsValid)return ValidationProblem(ModelState);return Ok(new{id=await priorityActions.Link(OrganizationId,UserId,id,request,OrganizationWide,ct)});}
    [HttpPost("workspace/priorities/{id:guid}/activities"), Authorize(Policy="action.manage")] public async Task<IActionResult> CreateActivity(Guid id,[FromBody] CreatePriorityActionRequest request,CancellationToken ct){if(InvalidContext() is { } error)return error;if(!ModelState.IsValid)return ValidationProblem(ModelState);return Ok(new{id=await priorityActions.Create(OrganizationId,UserId,id,request,OrganizationWide,ct)});}
    [HttpGet("workspace/priority-owners"), Authorize(Policy=ValoraPermissions.Priorities.Manage)] public async Task<IActionResult> PriorityOwners([FromQuery] OptionQuery query,CancellationToken ct) => InvalidContext() is { } error?error:Ok(await priorities.OwnersAsync(OrganizationId,query,ct));
    [HttpGet("workspace/priority-sources"), Authorize(Policy=ValoraPermissions.Priorities.Manage)] public async Task<IActionResult> PrioritySources([FromQuery] OptionQuery query,CancellationToken ct) => InvalidContext() is { } error?error:Ok(await priorities.SourcesAsync(OrganizationId,UserId,OrganizationWide,query,ct));
    [HttpPost("workspace/priorities"), Authorize(Policy=ValoraPermissions.Priorities.Manage)] public async Task<IActionResult> CreatePriority([FromBody] CreatePriorityRequest request, CancellationToken ct) { if (InvalidContext() is { } error) return error; if (!ModelState.IsValid) return ValidationProblem(ModelState); var created=await priorities.CreateAsync(OrganizationId, UserId, request, ct); return CreatedAtAction(nameof(Priority),new{id=created.Id},created); }
    [HttpPut("workspace/priorities/{id:guid}"), Authorize(Policy=ValoraPermissions.Priorities.Manage)] public async Task<IActionResult> UpdatePriority(Guid id,[FromBody] UpdatePriorityRequest request,CancellationToken ct) { if(InvalidContext() is { } error)return error; if(!ModelState.IsValid)return ValidationProblem(ModelState); return Ok(await priorities.UpdateAsync(OrganizationId,UserId,id,request,ct)); }
    [HttpPost("workspace/priorities/{id:guid}/progress"), Authorize(Policy=ValoraPermissions.Priorities.Manage)] public async Task<IActionResult> Progress(Guid id,[FromBody] ProgressPriorityRequest request,CancellationToken ct) { if(InvalidContext() is { } error)return error; if(!ModelState.IsValid)return ValidationProblem(ModelState); return Ok(await priorities.ProgressAsync(OrganizationId,UserId,id,request,OrganizationWide,CanManage,ct)); }
    [HttpPost("workspace/priorities/{id:guid}/{command:regex(^(complete|cancel|reopen)$)}"), Authorize(Policy=ValoraPermissions.Priorities.Manage)] public async Task<IActionResult> Transition(Guid id,string command,[FromBody] TransitionPriorityRequest request,CancellationToken ct) { if(InvalidContext() is { } error)return error; if(!ModelState.IsValid)return ValidationProblem(ModelState); return Ok(await priorities.TransitionAsync(OrganizationId,UserId,id,command,request,OrganizationWide,CanManage,ct)); }
    [HttpGet("search/global")] public async Task<IActionResult> Search([FromQuery] string term, CancellationToken ct) => InvalidContext() is { } error ? error : Ok(await search.SearchAsync(OrganizationId, UserId, term ?? "", OrganizationWide, ct));
    [HttpPost("workspace/pins")] public async Task<IActionResult> Pin([FromBody] PinItemRequest request, CancellationToken ct) { if (OrganizationId == Guid.Empty) return MissingContext(); if (UserId == Guid.Empty) return Unauthorized(); if (request.ItemId == Guid.Empty) return ValidationProblem("Informe um item válido."); await items.PinAsync(OrganizationId, UserId, request.ItemId, OrganizationWide, ct); return NoContent(); }
    [HttpDelete("workspace/pins/{id:guid}")] public async Task<IActionResult> Unpin(Guid id, CancellationToken ct) { if (InvalidContext() is { } error) return error; if (id == Guid.Empty) return ValidationProblem("Informe um item válido."); await items.UnpinAsync(OrganizationId, UserId, id, ct); return NoContent(); }
    [HttpPost("workspace/items/{id:guid}/open")] public async Task<IActionResult> Open(Guid id,CancellationToken ct) { if(InvalidContext() is { } error)return error; await items.RecordOpenAsync(OrganizationId,UserId,id,OrganizationWide,ct); return NoContent(); }
    [HttpGet("workspace/recent")] public async Task<IActionResult> Recent(CancellationToken ct) => OrganizationId == Guid.Empty ? MissingContext() : UserId == Guid.Empty ? Unauthorized() : Ok(await recent.GetAsync(OrganizationId, UserId, OrganizationWide, ct));
    [HttpGet("workspace/quick-actions")] public async Task<IActionResult> Actions(CancellationToken ct) => InvalidContext() is { } error ? error : Ok(await actions.ListAsync(OrganizationId, ct));
    [HttpPost("workspace/quick-actions/{code}/execute")] public async Task<IActionResult> Execute(string code, CancellationToken ct) { if (InvalidContext() is { } error) return error; var action = await actions.ExecuteAsync(OrganizationId, UserId, code, ct); return action is null ? NotFound(new { message = "Atalho não disponível para este contexto." }) : Ok(action); }
    private bool CanManage => Context.IsGlobalAdministrator || Context.Permissions.Contains(ValoraPermissions.Priorities.Manage,StringComparer.OrdinalIgnoreCase);
}
