namespace Valora.Application.OrganizationalArchitecture;

public sealed class OrganizationUnitService(IOrganizationalArchitectureRepository repository) { public Task<IReadOnlyList<ArchitectureUnit>> ListAsync(Guid o,CancellationToken c)=>repository.UnitsAsync(o,c); public async Task<ArchitectureUnit> CreateAsync(Guid o,CreateUnitRequest r,string id,CancellationToken c){if(r.ParentUnitId.HasValue && !(await repository.UnitsAsync(o,c)).Any(x=>x.Id==r.ParentUnitId && x.Status!="archived")) throw new ArgumentException("A unidade pai não existe ou está arquivada."); return await repository.CreateUnitAsync(o,r,id,c);} }
public sealed class OrganizationPositionService(IOrganizationalArchitectureRepository r){public Task<IReadOnlyList<ArchitecturePosition>> ListAsync(Guid o,CancellationToken c)=>r.PositionsAsync(o,c);public Task<ArchitecturePosition>CreateAsync(Guid o,CreatePositionRequest x,string id,CancellationToken c)=>r.CreatePositionAsync(o,x,id,c);}
public sealed class PeopleProfileService(IOrganizationalArchitectureRepository repository);
public sealed class RoleAssignmentService(IOrganizationalArchitectureRepository repository);
public sealed class ResponsibilityMatrixService(IOrganizationalArchitectureRepository r){public Task<IReadOnlyList<ResponsibilityItem>>ListAsync(Guid o,CancellationToken c)=>r.ResponsibilitiesAsync(o,c);public Task<ResponsibilityItem>CreateAsync(Guid o,CreateResponsibilityRequest x,string id,CancellationToken c)=>r.CreateResponsibilityAsync(o,x,id,c);}
public sealed class BusinessProcessService(IOrganizationalArchitectureRepository r){public Task<IReadOnlyList<BusinessProcess>>ListAsync(Guid o,CancellationToken c)=>r.ProcessesAsync(o,c);public async Task<BusinessProcess>CreateAsync(Guid o,CreateProcessRequest x,string id,CancellationToken c){var unit=(await r.UnitsAsync(o,c)).SingleOrDefault(u=>u.Id==x.UnitId);if(unit is null||unit.Status=="archived")throw new ArgumentException("Processos ativos exigem uma unidade ativa.");return await r.CreateProcessAsync(o,x,id,c);}}
public sealed class ProcessStepService(IOrganizationalArchitectureRepository repository);
public sealed class DecisionRightService(IOrganizationalArchitectureRepository r){public Task<IReadOnlyList<DecisionRight>>ListAsync(Guid o,CancellationToken c)=>r.DecisionRightsAsync(o,c);public Task<DecisionRight>CreateAsync(Guid o,CreateDecisionRightRequest x,string id,CancellationToken c)=>r.CreateDecisionRightAsync(o,x,id,c);}
public sealed class OrganizationalDependencyService(IOrganizationalArchitectureRepository r){public Task<IReadOnlyList<OrganizationalDependency>>ListAsync(Guid o,CancellationToken c)=>r.DependenciesAsync(o,c);public Task<OrganizationalDependency>CreateAsync(Guid o,CreateDependencyRequest x,string id,CancellationToken c)=>r.CreateDependencyAsync(o,x,id,c);}
public sealed class ArchitectureSnapshotService(IOrganizationalArchitectureRepository r){public Task<ArchitectureSnapshot>CreateAsync(Guid o,Guid? a,string id,CancellationToken c)=>r.SnapshotAsync(o,a,id,c);}
public sealed class ArchitectureRiskService(IOrganizationalArchitectureRepository r){public Task<IReadOnlyList<ArchitectureRisk>>ListAsync(Guid o,CancellationToken c)=>r.RisksAsync(o,c);}
public sealed class ArchitectureOverviewService(IOrganizationalArchitectureRepository r){public Task<ArchitectureSummary>GetAsync(Guid o,CancellationToken c)=>r.SummaryAsync(o,c);}
