using Microsoft.Extensions.DependencyInjection;
using Valora.Application.Certificates;
using Valora.Application.Communication;
using Valora.Application.FreeDiagnostics;
using Valora.Application.Forms;
using Valora.Application.Results;
using Valora.Application.Services;
using Valora.Application.Security;
using Valora.Application.Contracts;
using Valora.Application.CompanyRegistration;
using Valora.Application.Access;
using Valora.Application.OperationalIntelligence;
using Valora.Application.Enterprise;
using Valora.Application.OrganizationalIntelligence;
using Valora.Application.ValoraBot;
using Valora.Application.Methodology;
using Valora.Application.DiagnosticWorkspace;
using Valora.Application.CommercialDelivery;
using Valora.Application.FormalDeliverables;
using Valora.Application.Integrations;
using Valora.Application.ValoraAi;
using Valora.Application.DecisionCenter;
using Valora.Application.ActionCenter;
using Valora.Application.Evolution;
using Valora.Application.Journey;
using Valora.Application.OneOnOne;
using Valora.Application.Subscriptions;
using Valora.Application.SuccessCenter;
using Valora.Application.Experience;
using Valora.Application.Intelligence;
using Valora.Application.GovernanceExecution;
using Valora.Application.Workspace;
using Valora.Application.OrganizationalArchitecture;
using Valora.Application.Knowledge;
using Valora.Application.Advisor;
using Valora.Application.Processes;
using Valora.Application.Benchmarks;

namespace Valora.Application.DependencyInjection;

public static class ApplicationServiceCollectionExtensions
{
    public static IServiceCollection AddApplicationServices(this IServiceCollection services)
    {
        services.AddScoped<BenchmarkCohortService>(); services.AddScoped<BenchmarkSnapshotService>();
        services.AddScoped<BenchmarkPrivacyService>(); services.AddScoped<BenchmarkComparisonService>();
        services.AddScoped<BenchmarkInsightService>(); services.AddScoped<BenchmarkExportService>();
        services.AddScoped<ProcessDefinitionService>();
        services.AddScoped<Valora.Application.Processes.ProcessStepService>();
        services.AddScoped<ProcessInstanceService>(); services.AddScoped<ProcessApprovalService>();
        services.AddScoped<ProcessSlaService>(); services.AddScoped<ProcessAutomationService>();
        services.AddScoped<ProcessBottleneckInsightService>(); services.AddScoped<ProcessTemplateService>();
        services.AddScoped<AdvisorConversationService>(); services.AddScoped<AdvisorMessageService>();
        services.AddScoped<AdvisorContextBuilderService>(); services.AddScoped<AdvisorEvidenceCitationService>();
        services.AddScoped<AdvisorPromptTemplateService>(); services.AddScoped<AdvisorGuardrailService>();
        services.AddScoped<AdvisorResponseComposerService>(); services.AddScoped<AdvisorRecommendationService>();
        services.AddScoped<AdvisorActionSuggestionService>(); services.AddScoped<AdvisorFeedbackService>();
        services.AddScoped<AdvisorUsageService>(); services.AddScoped<IAdvisorModelProvider, DisabledAdvisorModelProvider>();
        services.AddScoped<Valora.Application.Indicators.IndicatorService>(); services.AddScoped<Valora.Application.Indicators.IndicatorCategoryService>(); services.AddScoped<Valora.Application.Indicators.IndicatorSourceService>();
        services.AddScoped<Valora.Application.Indicators.IndicatorTargetService>(); services.AddScoped<Valora.Application.Indicators.IndicatorMeasurementService>(); services.AddScoped<Valora.Application.Indicators.IndicatorFormulaService>();
        services.AddScoped<Valora.Application.Indicators.IndicatorTrendService>(); services.AddScoped<Valora.Application.Indicators.IndicatorAlertRuleService>(); services.AddScoped<Valora.Application.Indicators.IndicatorAlertService>();
        services.AddScoped<Valora.Application.Indicators.ExecutiveScorecardService>(); services.AddScoped<Valora.Application.Indicators.AnalyticsSnapshotService>();
        services.AddScoped<KnowledgeOverviewService>(); services.AddScoped<KnowledgeCategoryService>(); services.AddScoped<KnowledgeArticleService>();
        services.AddScoped<KnowledgeArticleVersionService>(); services.AddScoped<KnowledgeReviewService>(); services.AddScoped<OrganizationalLessonService>();
        services.AddScoped<PlaybookService>(); services.AddScoped<PlaybookStepService>(); services.AddScoped<LearningPathService>();
        services.AddScoped<LearningProgressService>(); services.AddScoped<CognitiveDictionaryService>(); services.AddScoped<KnowledgeSearchService>();
        services.AddScoped<ArchitectureOverviewService>();
        services.AddScoped<OrganizationUnitService>(); services.AddScoped<OrganizationPositionService>();
        services.AddScoped<PeopleProfileService>(); services.AddScoped<RoleAssignmentService>();
        services.AddScoped<ResponsibilityMatrixService>(); services.AddScoped<BusinessProcessService>(); services.AddScoped<Valora.Application.OrganizationalArchitecture.ProcessStepService>();
        services.AddScoped<DecisionRightService>(); services.AddScoped<OrganizationalDependencyService>();
        services.AddScoped<ArchitectureSnapshotService>(); services.AddScoped<ArchitectureRiskService>();
        services.AddScoped<IExecutiveWorkspaceService, ExecutiveWorkspaceService>();
        services.AddScoped<IMyDayService, MyDayService>();
        services.AddScoped<IWorkspaceItemService, WorkspaceItemService>();
        services.AddScoped<IGlobalSearchService, GlobalSearchService>();
        services.AddScoped<IQuickActionService, QuickActionService>();
        services.AddScoped<IRecentItemsService, RecentItemsService>();
        services.AddScoped<IPinnedItemsService, PinnedItemsService>();
        services.AddScoped<IExecutivePriorityService, ExecutivePriorityService>();
        services.AddScoped<ICommandPaletteService, CommandPaletteService>();
        services.AddScoped<IIntelligenceAnalysisService, IntelligenceAnalysisService>();
        services.AddScoped<IGovernanceCycleService, GovernanceCycleService>();
        services.AddScoped<IGovernanceMeetingService, GovernanceMeetingService>();
        services.AddScoped<IGovernanceDecisionService, GovernanceDecisionService>();
        services.AddScoped<IDecisionEvidenceService, DecisionEvidenceService>();
        services.AddScoped<IActionPriorityService, ActionPriorityService>();
        services.AddScoped<IEvolutionMilestoneService, EvolutionMilestoneService>();
        services.AddScoped<IEvolutionMetricSnapshotService, EvolutionMetricSnapshotService>();
        services.AddScoped<IOrganizationalLearningService, OrganizationalLearningService>();
        services.AddScoped<IOneOnOneActionLinkService, OneOnOneActionLinkService>();
        services.AddScoped<IIndicatorTargetService, IndicatorTargetService>();
        services.AddScoped<IIndicatorMeasurementService, IndicatorMeasurementService>();
        services.AddScoped<IIndicatorTrendService, IndicatorTrendService>();
        services.AddScoped<IExecutiveReportComposerService, ExecutiveReportComposerService>();
        services.AddScoped<IExecutiveReportTemplateService, ExecutiveReportTemplateService>();
        services.AddScoped<IGovernanceReportService, GovernanceReportService>();
        services.AddScoped<EvidenceMatrixService>();
        services.AddScoped<InferenceEngineService>();
        services.AddScoped<CausalMapService>();
        services.AddScoped<RecommendationService>();
        services.AddScoped<DecisionSupportService>();
        services.AddScoped<RespondentPortalService>();
        services.AddScoped<RespondentSessionService>();
        services.AddScoped<Valora.Application.Experience.PublicResultPortalService>();
        services.AddScoped<PublicCertificateService>();
        services.AddScoped<DiagnosticInvitationExperienceService>();
        services.AddScoped<ExecutiveResultExperienceService>();
        services.AddScoped<CreateRespondentAccessTokenUseCase>();
        services.AddScoped<StartRespondentSessionUseCase>();
        services.AddScoped<SaveRespondentProgressUseCase>();
        services.AddScoped<CompleteRespondentSessionUseCase>();
        services.AddScoped<GeneratePublicResultViewUseCase>();
        services.AddScoped<Valora.Application.Experience.RegisterPublicResultAccessUseCase>();
        services.AddScoped<DownloadPublicCertificateUseCase>();
        services.AddScoped<CreateInvitationBatchUseCase>();
        services.AddScoped<GenerateExecutiveResultPortalUseCase>();
        services.AddScoped<OnboardingService>(); services.AddScoped<OrganizationHealthService>(); services.AddScoped<SuccessPlaybookService>();
        services.AddScoped<SupportTicketService>(); services.AddScoped<KnowledgeBaseService>(); services.AddScoped<ProductUsageService>(); services.AddScoped<FeatureAdoptionService>();
        services.AddScoped<GenerateOrganizationOnboardingUseCase>(); services.AddScoped<CompleteOnboardingStepUseCase>(); services.AddScoped<ReopenOnboardingStepUseCase>();
        services.AddScoped<CalculateOrganizationHealthScoreUseCase>(); services.AddScoped<CreateSupportTicketUseCase>(); services.AddScoped<ReplySupportTicketUseCase>(); services.AddScoped<ResolveSupportTicketUseCase>();
        services.AddScoped<CreateSuccessPlaybookUseCase>(); services.AddScoped<AssignPlaybookToOrganizationUseCase>(); services.AddScoped<RegisterProductUsageEventUseCase>(); services.AddScoped<GenerateFeatureAdoptionOverviewUseCase>();
        services.AddScoped<SubscriptionPlanService>();
        services.AddScoped<OrganizationSubscriptionService>();
        services.AddScoped<FeatureAccessService>();
        services.AddScoped<UsageLimitService>();
        services.AddScoped<UpgradeRequestService>();
        services.AddScoped<BillingContactService>();
        services.AddScoped<GetCurrentSubscriptionUseCase>();
        services.AddScoped<CheckFeatureAccessUseCase>();
        services.AddScoped<ValidateUsageLimitUseCase>();
        services.AddScoped<RegisterUsageEventUseCase>();
        services.AddScoped<RequestPlanUpgradeUseCase>();
        services.AddScoped<ChangeOrganizationPlanUseCase>();
        services.AddScoped<ApplyPlanLimitOverrideUseCase>();
        services.AddScoped<OneOnOneSessionService>(); services.AddScoped<OneOnOneAgendaService>(); services.AddScoped<OneOnOneCommitmentService>(); services.AddScoped<OneOnOneAiSuggestionService>(); services.AddScoped<LeadershipProfileService>(); services.AddScoped<LeadershipDevelopmentService>();
        services.AddScoped<CreateOneOnOneSessionUseCase>(); services.AddScoped<ScheduleOneOnOneSessionUseCase>(); services.AddScoped<CompleteOneOnOneSessionUseCase>(); services.AddScoped<GenerateOneOnOneAgendaUseCase>(); services.AddScoped<RegisterOneOnOneCommitmentUseCase>(); services.AddScoped<RegisterLeadershipFeedbackUseCase>(); services.AddScoped<GenerateLeadershipDevelopmentSnapshotUseCase>();
        services.AddScoped<IBenchmarkManagementService, BenchmarkManagementService>();
        services.AddScoped<Valora.Application.Heatmap.IHeatmapService, Valora.Application.Heatmap.HeatmapService>();
        services.AddScoped<Valora.Application.Heatmap.HeatmapCalculationService>();
        services.AddScoped<Valora.Application.Heatmap.HeatmapAiInterpretationService>();
        services.AddScoped<Valora.Application.Heatmap.HeatmapQueryService>();
        services.AddScoped<Valora.Application.Heatmap.GenerateHeatmapSnapshotUseCase>();
        services.AddScoped<Valora.Application.Heatmap.GetHeatmapOverviewUseCase>();
        services.AddScoped<Valora.Application.Benchmark.BenchmarkService>();
        services.AddScoped<Valora.Application.Benchmark.BenchmarkCalculationService>();
        services.AddScoped<Valora.Application.Benchmark.BenchmarkAiInsightService>();
        services.AddScoped<Valora.Application.Benchmark.BenchmarkQueryService>();
        services.AddScoped<Valora.Application.Benchmark.GenerateBenchmarkComparisonUseCase>();
        services.AddScoped<Valora.Application.Benchmark.GetBenchmarkDetailsUseCase>();
        services.AddScoped<Valora.Application.Benchmark.GenerateBenchmarkAiInsightUseCase>();
        services.AddScoped<DecisionCenterService>();
        services.AddScoped<ActionPlanService>(); services.AddScoped<ActionItemService>(); services.AddScoped<ActionProgressService>(); services.AddScoped<Valora.Application.ActionCenter.ActionRecommendationService>();
        services.AddScoped<GenerateActionPlanFromDiagnosticUseCase>(); services.AddScoped<CreateActionFromInsightUseCase>(); services.AddScoped<CreateActionFromAlertUseCase>(); services.AddScoped<CreateActionFromDecisionUseCase>(); services.AddScoped<UpdateActionProgressUseCase>(); services.AddScoped<CompleteActionUseCase>(); services.AddScoped<BlockActionUseCase>();
        services.AddScoped<EvolutionCycleService>(); services.AddScoped<IEvolutionCycleService>(sp => sp.GetRequiredService<EvolutionCycleService>()); services.AddScoped<EvolutionSnapshotService>(); services.AddScoped<EvolutionMeasurementService>(); services.AddScoped<OpenEvolutionCycleUseCase>(); services.AddScoped<CloseEvolutionCycleUseCase>(); services.AddScoped<GenerateEvolutionSnapshotUseCase>();
        services.AddScoped<Valora.Application.Journey.JourneyService>(); services.AddScoped<JourneyTimelineService>(); services.AddScoped<JourneyEventService>(); services.AddScoped<RegisterJourneyEventUseCase>(); services.AddScoped<GenerateJourneyTimelineUseCase>();
        services.AddSingleton<ISensitiveDataSanitizer, SensitiveDataSanitizer>();
        services.AddSingleton<ValoraInsightCalculator>();
        services.AddSingleton<ValoraInsightDevolutivaService>();
        services.AddSingleton<StrategicMaturityScoringService>();
        services.AddSingleton<MethodologicalScoringService>();
        services.AddScoped<CertificateService>();
        services.AddScoped<ICertificateService>(sp => sp.GetRequiredService<CertificateService>());
        services.AddSingleton<EmailService>();
        services.AddSingleton<EmailJobService>();
        services.AddScoped<ResultEmailService>();
        services.AddScoped<EmailQueueProcessor>();
        services.AddScoped<AuthService>();
        services.AddScoped<RegisterCompanyValidator>();
        services.AddScoped<RegisterCompanyHandler>();
        services.AddScoped<IAuthenticationSessionService, AuthenticationSessionService>();
        services.AddSingleton<IPasswordPolicy, PasswordPolicy>();
        services.AddScoped<AuditService>();
        services.AddScoped<FreeDiagnosticsAppService>();
        services.AddScoped<PlanEntitlementService>();
        services.AddScoped<IPlanEntitlementService>(sp => sp.GetRequiredService<PlanEntitlementService>());
        services.AddScoped<PublicAnswerNormalizer>();
        services.AddScoped<PublicAnswerScorer>();
        services.AddScoped<PublicSurveyValidator>();
        services.AddScoped<PublicSurveyAssembler>();
        services.AddScoped<PublicResponseTransactionService>();
        services.AddScoped<PublicSurveySubmitter>();
        services.AddScoped<IPublicSurveyService, PublicSurveyService>();
        services.AddScoped<PublicResultValidator>();
        services.AddScoped<PublicResultAssembler>();
        services.AddScoped<IPublicResultService, PublicResultService>();
        services.AddScoped<IEntitlementService, EntitlementService>();
        services.AddScoped<IModuleService, ModuleService>();
        services.AddScoped<ISubscriptionService, SubscriptionService>();
        services.AddScoped<IUsageService, UsageService>();
        services.AddScoped<ISubscriptionUsageService, SubscriptionUsageService>();
        services.AddScoped<IPermissionService, PermissionService>();
        services.AddScoped<IDashboardMetricsService, DashboardMetricsService>();
        services.AddScoped<IMenuService, MenuService>();
        services.AddScoped<ReportBuilderService>();
        services.AddScoped<IReportService, ReportService>();
        services.AddScoped<ICertificateOperationalService, CertificateOperationalService>();
        services.AddScoped<ICertificateValidationService, CertificateValidationService>();
        services.AddScoped<IExportService, ExportService>();
        services.AddScoped<ILgpdConsentService, LgpdConsentService>();
        services.AddScoped<IPrivacyRequestService, PrivacyRequestService>();
        services.AddScoped<IEmailTemplateService, OperationalEmailTemplateService>();
        services.AddScoped<IEmailQueueService, EmailQueueService>();
        services.AddScoped<IEmailSenderService, EmailSenderService>();
        services.AddScoped<IEmailStatusService, EmailStatusService>();
        services.AddScoped<IOrganizationAdministrationService, OrganizationAdministrationService>();
        services.AddScoped<IOrganizationStructureService, OrganizationStructureService>();
        services.AddScoped<IOrganizationBrandingService, OrganizationBrandingService>();
        services.AddScoped<IUserAdministrationService, UserAdministrationService>();
        services.AddScoped<IFormAdministrationService, FormAdministrationService>();
        services.AddScoped<IAccessAdministrationService, AccessAdministrationService>();
        services.AddScoped<AccountHealthService>();
        services.AddSingleton<ComparisonEntitlementPolicy>();
        services.AddScoped<EnterpriseService>();
        services.AddScoped<ApiKeyAuthenticator>();
        services.AddSingleton<ExternalImportValidator>();
        services.AddSingleton<ICnpjLookupService, DisabledCnpjLookupService>();
        services.AddSingleton<ICepLookupService, DisabledCepLookupService>();
        services.AddScoped<IOrganizationalIntelligenceService, OrganizationalIntelligenceService>();
        services.AddSingleton<IValoraIntelligenceEngine, ValoraIntelligenceEngine>();
        services.AddScoped<IEvidenceExtractionService, EvidenceExtractionService>();
        services.AddScoped<IMetricCalculationService, MetricCalculationService>();
        services.AddScoped<IValoraIndexCalculationService, ValoraIndexCalculationService>();
        services.AddScoped<IInferenceEngine, EvidenceInferenceEngine>();
        services.AddScoped<
            Valora.Application.OrganizationalIntelligence.IInsightGenerationService,
            Valora.Application.OrganizationalIntelligence.InsightGenerationService>();
        services.AddScoped<IActionRecommendationService, Valora.Application.OrganizationalIntelligence.ActionRecommendationService>();
        services.AddScoped<IEvolutionService, Valora.Application.OrganizationalIntelligence.EvolutionService>();
        services.AddScoped<IJourneyService, Valora.Application.OrganizationalIntelligence.JourneyService>();
        services.AddScoped<IHeatmapService, HeatmapService>();
        services.AddScoped<IRadarService, RadarService>();
        services.AddScoped<IBenchmarkService, BenchmarkService>();
        services.AddScoped<IExecutiveReportService, ExecutiveReportService>();
        services.AddScoped<INotificationService, Valora.Application.OrganizationalIntelligence.NotificationService>();
        services.AddScoped<IPlatformGovernanceService, PlatformGovernanceService>();
        services.AddScoped<IOrganizationalIntelligencePipeline, OrganizationalIntelligencePipeline>();
        services.AddScoped<IIntelligenceProcessingJobService, IntelligenceProcessingJobService>();
        services.AddScoped<IIntelligenceReprocessService>(sp => (IntelligenceProcessingJobService)sp.GetRequiredService<IIntelligenceProcessingJobService>());
        services.AddScoped<IIntelligenceStageLogger, IntelligenceStageLogger>();
        services.AddScoped<IIntelligenceProcessingOrchestrator, IntelligenceProcessingOrchestrator>();
        services.AddScoped<IValoraBotService, ValoraBotService>();
        services.AddScoped<IMethodologyService, MethodologyService>();
        services.AddScoped<MethodologyVersionService>();
        services.AddScoped<MethodologyValidationService>();
        services.AddScoped<MethodologyPublicationService>();
        services.AddScoped<MethodologyConceptService>();
        services.AddScoped<MethodologyDimensionService>();
        services.AddScoped<MaturityLevelService>();
        services.AddScoped<EvidenceCriteriaService>();
        services.AddScoped<ScoringRuleService>();
        services.AddScoped<IndicatorRuleService>();
        services.AddScoped<QuestionBankService>();
        services.AddScoped<DiagnosticTemplateService>();
        services.AddScoped<MethodologyIndexService>();
        services.AddScoped<MethodologyQuestionBankService>();
        services.AddScoped<MethodologyPromptTemplateService>();
        services.AddScoped<MethodologyGuardrailService>();
        services.AddScoped<CreateMethodologyVersionUseCase>();
        services.AddScoped<CloneMethodologyVersionUseCase>();
        services.AddScoped<PublishMethodologyVersionUseCase>();
        services.AddScoped<ValidateMethodologyConsistencyUseCase>();
        services.AddScoped<IDiagnosticWorkspaceService, DiagnosticWorkspaceService>();
        services.AddScoped<IDiagnosticCampaignService, DiagnosticCampaignService>();
        services.AddSingleton<ValoraInferenceEngine>();
        services.AddSingleton<IValoraEvidencePackBuilder, ValoraEvidencePackBuilder>();
        services.AddSingleton<IValoraPromptRenderer, ValoraPromptRenderer>();
        services.AddSingleton<IValoraAiGuardrailService, ValoraAiGuardrailService>();
        services.AddSingleton<IValoraAiProvider, DisabledValoraAiProvider>();
        services.AddScoped<IValoraAiOrchestrator, ValoraAiOrchestrator>();
        services.AddScoped<IValoraAiReviewService, ValoraAiReviewService>();
        services.AddScoped<IEvidencePackBuilderService, EvidencePackBuilderService>();
        services.AddScoped<IAiGuardrailValidationService, AiGuardrailValidationService>();
        services.AddScoped<
            Valora.Application.ValoraAi.IInsightGenerationService,
            Valora.Application.ValoraAi.InsightGenerationService>();
        services.AddScoped<IAiFeedbackService, AiFeedbackService>();
        services.AddScoped<ValoraAiRunService>();
        services.AddScoped<AiReviewService>();
        services.AddScoped<ValoraAiOrchestratorService>();
        services.AddScoped<GenerateInsightsFromResultUseCase>();
        services.AddScoped<BuildEvidencePackUseCase>();
        services.AddScoped<ReviewAiInsightUseCase>();
        services.AddScoped<ApproveAiInsightUseCase>();
        services.AddScoped<RejectAiInsightUseCase>();
        services.AddScoped<ConvertInsightToActionUseCase>();
        services.AddScoped<ConvertInsightToDecisionUseCase>();
        services.AddScoped<GenerateAiExecutiveSummaryUseCase>();

        services.AddScoped<Valora.Application.Contracts.ILegacyDataNormalizer, LegacyDataNormalizer>();
        services.AddScoped<Valora.Application.Contracts.ILegacyMappingService, LegacyMappingService>();
        services.AddScoped<IFirestoreExportReader, FirestoreExportReader>();
        services.AddScoped<ILocalStorageExportReader, LocalStorageExportReader>();
        services.AddScoped<IManualJsonReader, ManualJsonReader>();
        services.AddScoped<ILegacySourceReader>(sp => sp.GetRequiredService<IFirestoreExportReader>());
        services.AddScoped<ILegacySourceReader>(sp => sp.GetRequiredService<ILocalStorageExportReader>());
        services.AddScoped<ILegacySourceReader>(sp => sp.GetRequiredService<IManualJsonReader>());
        services.AddScoped<IMigrationDryRunService, MigrationDryRunService>();
        services.AddScoped<Valora.Application.Contracts.ILegacyImportService>(sp => (MigrationDryRunService)sp.GetRequiredService<IMigrationDryRunService>());
        services.AddScoped<IMigrationApplyService, MigrationApplyService>();
        services.AddScoped<IMigrationReconciliationService, MigrationReconciliationService>();
        services.AddScoped<IMigrationRollbackService, MigrationRollbackService>();
        services.AddScoped<ICutoverReadinessService, CutoverReadinessService>();
        services.AddScoped<IMigrationReportService, MigrationReportService>();
        services.AddSingleton<IResultTokenService, ResultTokenService>();
        services.AddScoped<PublicCommercialService>();
        services.AddSingleton<IExecutiveReportExportService, ExecutiveReportExportService>();
        services.AddScoped<IValoraDocumentService, ValoraDocumentService>();
        services.AddScoped<ISecureShareLinkService, SecureShareLinkService>();
        services.AddScoped<ExecutiveReportGenerationService>();
        services.AddScoped<CertificateGenerationService>();
        services.AddScoped<Valora.Application.FormalDeliverables.PublicResultPortalService>();
        services.AddScoped<DeliverableAuditService>();
        services.AddScoped<GenerateExecutiveReportUseCase>();
        services.AddScoped<GenerateCertificateUseCase>();
        services.AddScoped<CreateSecureShareLinkUseCase>();
        services.AddScoped<ValidateSecureShareLinkUseCase>();
        services.AddScoped<DownloadCertificateUseCase>();
        services.AddScoped<DownloadReportUseCase>();
        services.AddScoped<RevokeShareLinkUseCase>();
        services.AddScoped<Valora.Application.FormalDeliverables.RegisterPublicResultAccessUseCase>();
        services.AddScoped<Valora.Application.Communication.NotificationService>();
        services.AddScoped<NotificationTemplateService>();
        services.AddScoped<CommunicationOutboxService>();
        services.AddScoped<ReminderService>();
        services.AddScoped<CommunicationAuditService>();
        services.AddScoped<CreateNotificationUseCase>();
        services.AddScoped<MarkNotificationAsReadUseCase>();
        services.AddScoped<QueueEmailMessageUseCase>();
        services.AddScoped<ProcessCommunicationOutboxUseCase>();
        services.AddScoped<CreateReminderRuleUseCase>();
        services.AddScoped<SendDiagnosticInvitationUseCase>();
        services.AddScoped<SendReportLinkUseCase>();
        services.AddScoped<SendCertificateLinkUseCase>();
        return services;
    }
}
