using Microsoft.Extensions.DependencyInjection;
using Valora.Application.Certificates;
using Valora.Application.Communication;
using Valora.Application.FreeDiagnostics;
using Valora.Application.Forms;
using Valora.Application.Results;
using Valora.Application.Services;
using Valora.Application.Security;
using Valora.Application.Contracts;
using Valora.Application.CompanyRegistration;
using Valora.Application.Access;
using Valora.Application.OperationalIntelligence;
using Valora.Application.Enterprise;
using Valora.Application.OrganizationalIntelligence;
using Valora.Application.ValoraBot;
using Valora.Application.Methodology;
using Valora.Application.DiagnosticWorkspace;
using Valora.Application.CommercialDelivery;
using Valora.Application.FormalDeliverables;
using Valora.Application.Integrations;
using Valora.Application.ValoraAi;
using Valora.Application.DecisionCenter;
using Valora.Application.ActionCenter;
using Valora.Application.Evolution;
using Valora.Application.Journey;
using Valora.Application.OneOnOne;

namespace Valora.Application.DependencyInjection;

public static class ApplicationServiceCollectionExtensions
{
    public static IServiceCollection AddApplicationServices(this IServiceCollection services)
    {
        services.AddScoped<OneOnOneSessionService>(); services.AddScoped<OneOnOneAgendaService>(); services.AddScoped<OneOnOneCommitmentService>(); services.AddScoped<OneOnOneAiSuggestionService>(); services.AddScoped<LeadershipProfileService>(); services.AddScoped<LeadershipDevelopmentService>();
        services.AddScoped<CreateOneOnOneSessionUseCase>(); services.AddScoped<ScheduleOneOnOneSessionUseCase>(); services.AddScoped<CompleteOneOnOneSessionUseCase>(); services.AddScoped<GenerateOneOnOneAgendaUseCase>(); services.AddScoped<RegisterOneOnOneCommitmentUseCase>(); services.AddScoped<RegisterLeadershipFeedbackUseCase>(); services.AddScoped<GenerateLeadershipDevelopmentSnapshotUseCase>();
        services.AddScoped<IBenchmarkManagementService, BenchmarkManagementService>();
        services.AddScoped<Valora.Application.Heatmap.IHeatmapService, Valora.Application.Heatmap.HeatmapService>();
        services.AddScoped<Valora.Application.Heatmap.HeatmapCalculationService>();
        services.AddScoped<Valora.Application.Heatmap.HeatmapAiInterpretationService>();
        services.AddScoped<Valora.Application.Heatmap.HeatmapQueryService>();
        services.AddScoped<Valora.Application.Heatmap.GenerateHeatmapSnapshotUseCase>();
        services.AddScoped<Valora.Application.Heatmap.GetHeatmapOverviewUseCase>();
        services.AddScoped<Valora.Application.Benchmark.BenchmarkService>();
        services.AddScoped<Valora.Application.Benchmark.BenchmarkCalculationService>();
        services.AddScoped<Valora.Application.Benchmark.BenchmarkAiInsightService>();
        services.AddScoped<Valora.Application.Benchmark.BenchmarkQueryService>();
        services.AddScoped<Valora.Application.Benchmark.GenerateBenchmarkComparisonUseCase>();
        services.AddScoped<Valora.Application.Benchmark.GetBenchmarkDetailsUseCase>();
        services.AddScoped<Valora.Application.Benchmark.GenerateBenchmarkAiInsightUseCase>();
        services.AddScoped<DecisionCenterService>();
        services.AddScoped<ActionPlanService>(); services.AddScoped<ActionItemService>(); services.AddScoped<ActionProgressService>(); services.AddScoped<Valora.Application.ActionCenter.ActionRecommendationService>();
        services.AddScoped<GenerateActionPlanFromDiagnosticUseCase>(); services.AddScoped<CreateActionFromInsightUseCase>(); services.AddScoped<CreateActionFromAlertUseCase>(); services.AddScoped<CreateActionFromDecisionUseCase>(); services.AddScoped<UpdateActionProgressUseCase>(); services.AddScoped<CompleteActionUseCase>(); services.AddScoped<BlockActionUseCase>();
        services.AddScoped<Valora.Application.Evolution.EvolutionCycleService>(); services.AddScoped<EvolutionSnapshotService>(); services.AddScoped<EvolutionMeasurementService>(); services.AddScoped<OpenEvolutionCycleUseCase>(); services.AddScoped<CloseEvolutionCycleUseCase>(); services.AddScoped<GenerateEvolutionSnapshotUseCase>();
        services.AddScoped<Valora.Application.Journey.JourneyService>(); services.AddScoped<JourneyTimelineService>(); services.AddScoped<JourneyEventService>(); services.AddScoped<RegisterJourneyEventUseCase>(); services.AddScoped<GenerateJourneyTimelineUseCase>();
        services.AddSingleton<ISensitiveDataSanitizer, SensitiveDataSanitizer>();
        services.AddSingleton<ValoraInsightCalculator>();
        services.AddSingleton<ValoraInsightDevolutivaService>();
        services.AddSingleton<StrategicMaturityScoringService>();
        services.AddSingleton<MethodologicalScoringService>();
        services.AddScoped<CertificateService>();
        services.AddScoped<ICertificateService>(sp => sp.GetRequiredService<CertificateService>());
        services.AddSingleton<EmailService>();
        services.AddSingleton<EmailJobService>();
        services.AddScoped<ResultEmailService>();
        services.AddScoped<EmailQueueProcessor>();
        services.AddScoped<AuthService>();
        services.AddScoped<RegisterCompanyValidator>();
        services.AddScoped<RegisterCompanyHandler>();
        services.AddScoped<IAuthenticationSessionService, AuthenticationSessionService>();
        services.AddSingleton<IPasswordPolicy, PasswordPolicy>();
        services.AddScoped<AuditService>();
        services.AddScoped<FreeDiagnosticsAppService>();
        services.AddScoped<PlanEntitlementService>();
        services.AddScoped<IPlanEntitlementService>(sp => sp.GetRequiredService<PlanEntitlementService>());
        services.AddScoped<PublicAnswerNormalizer>();
        services.AddScoped<PublicAnswerScorer>();
        services.AddScoped<PublicSurveyValidator>();
        services.AddScoped<PublicSurveyAssembler>();
        services.AddScoped<PublicResponseTransactionService>();
        services.AddScoped<PublicSurveySubmitter>();
        services.AddScoped<IPublicSurveyService, PublicSurveyService>();
        services.AddScoped<PublicResultValidator>();
        services.AddScoped<PublicResultAssembler>();
        services.AddScoped<IPublicResultService, PublicResultService>();
        services.AddScoped<IEntitlementService, EntitlementService>();
        services.AddScoped<IModuleService, ModuleService>();
        services.AddScoped<ISubscriptionService, SubscriptionService>();
        services.AddScoped<IUsageService, UsageService>();
        services.AddScoped<ISubscriptionUsageService, SubscriptionUsageService>();
        services.AddScoped<IPermissionService, PermissionService>();
        services.AddScoped<IDashboardMetricsService, DashboardMetricsService>();
        services.AddScoped<IMenuService, MenuService>();
        services.AddScoped<ReportBuilderService>();
        services.AddScoped<IReportService, ReportService>();
        services.AddScoped<ICertificateOperationalService, CertificateOperationalService>();
        services.AddScoped<ICertificateValidationService, CertificateValidationService>();
        services.AddScoped<IExportService, ExportService>();
        services.AddScoped<ILgpdConsentService, LgpdConsentService>();
        services.AddScoped<IPrivacyRequestService, PrivacyRequestService>();
        services.AddScoped<IEmailTemplateService, OperationalEmailTemplateService>();
        services.AddScoped<IEmailQueueService, EmailQueueService>();
        services.AddScoped<IEmailSenderService, EmailSenderService>();
        services.AddScoped<IEmailStatusService, EmailStatusService>();
        services.AddScoped<IOrganizationAdministrationService, OrganizationAdministrationService>();
        services.AddScoped<IOrganizationStructureService, OrganizationStructureService>();
        services.AddScoped<IOrganizationBrandingService, OrganizationBrandingService>();
        services.AddScoped<IUserAdministrationService, UserAdministrationService>();
        services.AddScoped<IFormAdministrationService, FormAdministrationService>();
        services.AddScoped<IAccessAdministrationService, AccessAdministrationService>();
        services.AddScoped<AccountHealthService>();
        services.AddSingleton<ComparisonEntitlementPolicy>();
        services.AddScoped<EnterpriseService>();
        services.AddScoped<ApiKeyAuthenticator>();
        services.AddSingleton<ExternalImportValidator>();
        services.AddSingleton<ICnpjLookupService, DisabledCnpjLookupService>();
        services.AddSingleton<ICepLookupService, DisabledCepLookupService>();
        services.AddScoped<IOrganizationalIntelligenceService, OrganizationalIntelligenceService>();
        services.AddSingleton<IValoraIntelligenceEngine, ValoraIntelligenceEngine>();
        services.AddScoped<IEvidenceExtractionService, EvidenceExtractionService>();
        services.AddScoped<IMetricCalculationService, MetricCalculationService>();
        services.AddScoped<IValoraIndexCalculationService, ValoraIndexCalculationService>();
        services.AddScoped<IInferenceEngine, EvidenceInferenceEngine>();
        services.AddScoped<IInsightGenerationService, InsightGenerationService>();
        services.AddScoped<IActionRecommendationService, Valora.Application.OrganizationalIntelligence.ActionRecommendationService>();
        services.AddScoped<IEvolutionService, Valora.Application.OrganizationalIntelligence.EvolutionService>();
        services.AddScoped<IJourneyService, Valora.Application.OrganizationalIntelligence.JourneyService>();
        services.AddScoped<IHeatmapService, HeatmapService>();
        services.AddScoped<IRadarService, RadarService>();
        services.AddScoped<IBenchmarkService, BenchmarkService>();
        services.AddScoped<IExecutiveReportService, ExecutiveReportService>();
        services.AddScoped<INotificationService, NotificationService>();
        services.AddScoped<IPlatformGovernanceService, PlatformGovernanceService>();
        services.AddScoped<IOrganizationalIntelligencePipeline, OrganizationalIntelligencePipeline>();
        services.AddScoped<IIntelligenceProcessingJobService, IntelligenceProcessingJobService>();
        services.AddScoped<IIntelligenceReprocessService>(sp => (IntelligenceProcessingJobService)sp.GetRequiredService<IIntelligenceProcessingJobService>());
        services.AddScoped<IIntelligenceStageLogger, IntelligenceStageLogger>();
        services.AddScoped<IIntelligenceProcessingOrchestrator, IntelligenceProcessingOrchestrator>();
        services.AddScoped<IValoraBotService, ValoraBotService>();
        services.AddScoped<IMethodologyService, MethodologyService>();
        services.AddScoped<MethodologyVersionService>();
        services.AddScoped<MethodologyValidationService>();
        services.AddScoped<MethodologyPublicationService>();
        services.AddScoped<MethodologyConceptService>();
        services.AddScoped<MethodologyIndexService>();
        services.AddScoped<MethodologyQuestionBankService>();
        services.AddScoped<MethodologyPromptTemplateService>();
        services.AddScoped<MethodologyGuardrailService>();
        services.AddScoped<CreateMethodologyVersionUseCase>();
        services.AddScoped<CloneMethodologyVersionUseCase>();
        services.AddScoped<PublishMethodologyVersionUseCase>();
        services.AddScoped<ValidateMethodologyConsistencyUseCase>();
        services.AddScoped<IDiagnosticWorkspaceService, DiagnosticWorkspaceService>();
        services.AddScoped<IDiagnosticCampaignService, DiagnosticCampaignService>();
        services.AddSingleton<ValoraInferenceEngine>();
        services.AddSingleton<IValoraEvidencePackBuilder, ValoraEvidencePackBuilder>();
        services.AddSingleton<IValoraPromptRenderer, ValoraPromptRenderer>();
        services.AddSingleton<IValoraAiGuardrailService, ValoraAiGuardrailService>();
        services.AddSingleton<IValoraAiProvider, DisabledValoraAiProvider>();
        services.AddScoped<IValoraAiOrchestrator, ValoraAiOrchestrator>();
        services.AddScoped<IValoraAiReviewService, ValoraAiReviewService>();

        services.AddScoped<Valora.Application.Contracts.ILegacyDataNormalizer, LegacyDataNormalizer>();
        services.AddScoped<Valora.Application.Contracts.ILegacyMappingService, LegacyMappingService>();
        services.AddScoped<IFirestoreExportReader, FirestoreExportReader>();
        services.AddScoped<ILocalStorageExportReader, LocalStorageExportReader>();
        services.AddScoped<IManualJsonReader, ManualJsonReader>();
        services.AddScoped<ILegacySourceReader>(sp => sp.GetRequiredService<IFirestoreExportReader>());
        services.AddScoped<ILegacySourceReader>(sp => sp.GetRequiredService<ILocalStorageExportReader>());
        services.AddScoped<ILegacySourceReader>(sp => sp.GetRequiredService<IManualJsonReader>());
        services.AddScoped<IMigrationDryRunService, MigrationDryRunService>();
        services.AddScoped<Valora.Application.Contracts.ILegacyImportService>(sp => (MigrationDryRunService)sp.GetRequiredService<IMigrationDryRunService>());
        services.AddScoped<IMigrationApplyService, MigrationApplyService>();
        services.AddScoped<IMigrationReconciliationService, MigrationReconciliationService>();
        services.AddScoped<IMigrationRollbackService, MigrationRollbackService>();
        services.AddScoped<ICutoverReadinessService, CutoverReadinessService>();
        services.AddScoped<IMigrationReportService, MigrationReportService>();
        services.AddSingleton<IResultTokenService, ResultTokenService>();
        services.AddScoped<PublicCommercialService>();
        services.AddSingleton<IExecutiveReportExportService, ExecutiveReportExportService>();
        services.AddScoped<IValoraDocumentService, ValoraDocumentService>();
        services.AddScoped<ISecureShareLinkService, SecureShareLinkService>();
        services.AddScoped<ExecutiveReportGenerationService>();
        services.AddScoped<CertificateGenerationService>();
        services.AddScoped<PublicResultPortalService>();
        services.AddScoped<DeliverableAuditService>();
        services.AddScoped<GenerateExecutiveReportUseCase>();
        services.AddScoped<GenerateCertificateUseCase>();
        services.AddScoped<CreateSecureShareLinkUseCase>();
        services.AddScoped<ValidateSecureShareLinkUseCase>();
        services.AddScoped<DownloadCertificateUseCase>();
        services.AddScoped<DownloadReportUseCase>();
        services.AddScoped<RevokeShareLinkUseCase>();
        services.AddScoped<RegisterPublicResultAccessUseCase>();
        return services;
    }
}
