using Valora.Application.Contracts;
using Valora.Application.DTOs;

namespace Valora.Application.Services;
public sealed class AuthService(IOrganizationRepository orgs,IUserRepository users,IPlanRepository plans,IJwtTokenService jwt,IPasswordHasher hasher,AuditService audit){
 static string Slug(string s)=>new string(s.ToLowerInvariant().Select(c=>char.IsLetterOrDigit(c)?c:'-').ToArray()).Trim('-')+"-"+Guid.NewGuid().ToString("N")[..6];
 public async Task<AuthResponse> RegisterCompanyAsync(RegisterCompanyRequest r){ if(string.IsNullOrWhiteSpace(r.Email)||r.Password.Length<6||string.IsNullOrWhiteSpace(r.CompanyName)) throw new ArgumentException("Dados inválidos."); var existing=await users.GetByEmailAsync(r.Email); if(existing is not null) throw new InvalidOperationException("E-mail já cadastrado."); var orgId=await orgs.CreateAsync(r.CompanyName,r.Email,Slug(r.CompanyName),"free"); await plans.CreateSubscriptionAsync(orgId,"free"); var userId=await users.CreateAsync(orgId,r.Name,r.Email,hasher.Hash(r.Password),"empresa_admin"); await valorapesquisa.LogAsync(new(orgId,userId,"auth.register_company","organization",orgId.ToString(),"Empresa cadastrada via API.")); return new(jwt.CreateToken(userId,orgId,r.Email,"empresa_admin"),new { id=userId,name=r.Name,email=r.Email,role="empresa_admin"},new{id=orgId,name=r.CompanyName},await plans.GetByIdAsync("free")); }
 public async Task<AuthResponse> LoginAsync(LoginRequest r){ var u=await users.GetByEmailAsync(r.Email) ?? throw new UnauthorizedAccessException("Credenciais inválidas."); if(!hasher.Verify(r.Password,(string)u.password_hash)) throw new UnauthorizedAccessException("Credenciais inválidas."); await users.TouchLoginAsync((Guid)u.id); await valorapesquisa.LogAsync(new((Guid?)u.organization_id,(Guid)u.id,"auth.login","user",u.id.ToString(),"Login realizado.")); var org=(Guid?)u.organization_id is Guid oid? await orgs.GetAsync(oid):null; var plan=(Guid?)u.organization_id is Guid poid? await plans.GetByIdAsync(await plans.GetCurrentPlanIdAsync(poid)??"free"):null; return new(jwt.CreateToken((Guid)u.id,(Guid?)u.organization_id,(string)u.email,(string)u.role),new{id=u.id,name=u.name,email=u.email,role=u.role},org,plan); }
}
