const crypto=require('crypto');const {config}=require('../config');
let admin=null,db=null;function sha256(v){return crypto.createHash('sha256').update(String(v||'')).digest('hex')}
function init(){if(process.env.FIRESTORE_MOCK==='true')return null;if(db)return db;admin=require('firebase-admin');if(!admin.apps.length)admin.initializeApp({projectId:config.firebase.projectId||undefined});db=admin.firestore();return db}
function asDoc(snap){return snap&&snap.exists?{id:snap.id,...snap.data()}:null}
async function getDoc(col,id){const d=init();return asDoc(await d.collection(col).doc(id).get())}
async function loadResultContext(responseId,resultToken=''){if(process.env.FIRESTORE_MOCK==='true'){const response={id:responseId,surveyId:'survey_1',formId:'form_1',companyId:'company_1',participant:{name:'Maria Silva',email:'maria@email.com'},resultTokenHash:sha256('token'),rawScore:72,maxScore:125,percentage:57.6,level:{label:'Em estruturação'},byDimension:{Governança:{normalized5:2.4,percentage:48},Resultados:{normalized5:4.1,percentage:82}},createdAt:new Date().toISOString()};return {response,survey:{id:'survey_1',title:'Diagnóstico Valora Insight™',companyId:'company_1'},form:{id:'form_1',name:'Valora Insight™'},company:{id:'company_1',name:'Empresa Cliente'}};}
const response=await getDoc('responses',responseId);if(!response)throw Object.assign(new Error('Resposta não encontrada.'),{status:404,code:'response-not-found'});if(response.resultTokenHash&&resultToken&&response.resultTokenHash!==sha256(resultToken))throw Object.assign(new Error('Token de resultado inválido.'),{status:403,code:'invalid-result-token'});if(response.resultTokenHash&&!resultToken)throw Object.assign(new Error('Token de resultado obrigatório.'),{status:403,code:'missing-result-token'});const [survey,form,company]=await Promise.all([response.surveyId?getDoc('surveys',response.surveyId):null,response.formId?getDoc('forms',response.formId):null,response.companyId?getDoc('organizations',response.companyId):null]);return {response,survey:survey||{},form:form||{},company:company||{}};}
async function registerCommunication(row){if(process.env.FIRESTORE_MOCK==='true')return {id:`comm_${Date.now()}`};const d=init();const ref=d.collection('communications').doc();await ref.set({...row,id:ref.id,createdAt:new Date(),updatedAt:new Date()});return {id:ref.id};}
module.exports={loadResultContext,registerCommunication,sha256};
