const crypto=require('crypto');const {config}=require('../config');
let admin=null,db=null;function sha256(v){return crypto.createHash('sha256').update(String(v||'')).digest('hex')}
function init(){if(process.env.FIRESTORE_MOCK==='true')return null;if(db)return db;admin=require('firebase-admin');if(!admin.apps.length)admin.initializeApp({projectId:config.firebase.projectId||undefined});db=admin.firestore();return db}
function asDoc(snap){return snap&&snap.exists?{id:snap.id,...snap.data()}:null}
async function getDoc(col,id){const d=init();return asDoc(await d.collection(col).doc(id).get())}
async function loadResultContext(responseId,resultToken=''){if(process.env.FIRESTORE_MOCK==='true'){const response={id:responseId,surveyId:'survey_1',formId:'form_1',companyId:'company_1',participant:{name:'Maria Silva',email:'maria@email.com'},resultTokenHash:sha256('token'),rawScore:72,maxScore:125,percentage:57.6,level:{label:'Em estruturação'},byDimension:{Governança:{normalized5:2.4,percentage:48},Resultados:{normalized5:4.1,percentage:82}},createdAt:new Date().toISOString()};return {response,survey:{id:'survey_1',title:'Diagnóstico Valora Insight™',companyId:'company_1'},form:{id:'form_1',name:'Valora Insight™'},company:{id:'company_1',name:'Empresa Cliente'}};}
const response=await getDoc('responses',responseId);if(!response)throw Object.assign(new Error('Resposta não encontrada.'),{status:404,code:'response-not-found'});if(response.resultTokenHash&&resultToken&&response.resultTokenHash!==sha256(resultToken))throw Object.assign(new Error('Token de resultado inválido.'),{status:403,code:'invalid-result-token'});if(response.resultTokenHash&&!resultToken)throw Object.assign(new Error('Token de resultado obrigatório.'),{status:403,code:'missing-result-token'});const [survey,form,company]=await Promise.all([response.surveyId?getDoc('surveys',response.surveyId):null,response.formId?getDoc('forms',response.formId):null,response.companyId?getDoc('organizations',response.companyId):null]);return {response,survey:survey||{},form:form||{},company:company||{}};}
async function registerCommunication(row){if(process.env.FIRESTORE_MOCK==='true')return {id:`comm_${Date.now()}`};const d=init();const ref=d.collection('communications').doc();await ref.set({...row,id:ref.id,createdAt:new Date(),updatedAt:new Date()});return {id:ref.id};}

async function loadPublicSurveyContext(surveyId){
  if(process.env.FIRESTORE_MOCK==='true'){const survey={id:surveyId,title:'Diagnóstico Valora Insight™',formId:'form_1',companyId:'company_1',status:'active',token:'token_publico',publicToken:'token_publico',visibleOnHome:true};const form={id:'form_1',name:'Valora Insight™',questions:[{id:'q1',text:'Pergunta',type:'scale',required:true,maxScore:5,dimensionName:'Gestão e Governança'}],resultBands:[{from:0,to:5,label:'Em estruturação'}]};return {survey,form,company:{id:'company_1',name:'Empresa Cliente'}};}
  const [survey]=await Promise.all([getDoc('surveys',surveyId)]);
  if(!survey)throw Object.assign(new Error('Pesquisa não encontrada.'),{status:404,code:'survey-not-found'});
  const [form,company]=await Promise.all([survey.formId?getDoc('forms',survey.formId):null,survey.companyId?getDoc('organizations',survey.companyId):null]);
  return {survey,form:form||{},company:company||{}};
}
function calculateBasicResult(form={},answers={}){let rawScore=0,maxScore=0;for(const q of (form.questions||[])){const v=answers[q.id];let max=Number(q.maxScore||5),raw=0;if(q.type==='scale')raw=Math.max(0,Math.min(5,Number(v||0)))/5*max;else if(Array.isArray(q.options)){const opt=q.options.find(o=>o.id===v||o.value===v);raw=Number(opt?.score||0);max=max||Math.max(0,...q.options.map(o=>Number(o.score||0)));}else raw=String(v||'').trim()?Number(q.scoreWhenFilled||0):0;rawScore+=raw;maxScore+=max;}const normalized5=maxScore?rawScore/maxScore*5:0;const band=(form.resultBands||[]).find(b=>normalized5>=Number(b.from)&&normalized5<=Number(b.to))||{};return {rawScore,maxScore,normalized5,percentage:normalized5/5*100,level:{label:band.label||band.name||'Resultado gerado',description:band.description||'',recommendation:band.recommendation||''}};}
async function savePublicSurveyResponse({survey,form,payload,resultToken}){
  if(process.env.FIRESTORE_MOCK==='true')return {id:`resp_${Date.now()}`};
  const d=init();const ref=d.collection('responses').doc();const result=calculateBasicResult(form,payload.answers||{});
  await ref.set({id:ref.id,surveyId:survey.id,formId:form.id||survey.formId,companyId:survey.companyId||'',participant:payload.participant||{},answers:payload.answers||{},lgpdConsent:!!payload.lgpdConsent,communicationConsent:!!payload.communicationConsent,resultTokenHash:sha256(resultToken),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),publicSubmissionProvider:'external-api',emailStatus:'pending',...result});
  return {id:ref.id,result};
}
module.exports={loadResultContext,registerCommunication,sha256,loadPublicSurveyContext,savePublicSurveyResponse,calculateBasicResult};
