using Dapper;
using Valora.Application.Contracts;
using Valora.Application.Onboarding;

namespace Valora.Infrastructure.Onboarding;

public sealed class OnboardingRepository(IDbConnectionFactory db) : IOnboardingRepository
{
    public async Task EnsureDefaultFlowAsync(Guid organizationId, CancellationToken ct) { using var c = db.Create(); await c.ExecuteAsync(new CommandDefinition("SELECT valorapesquisa.ensure_success_onboarding(@organizationId)", new { organizationId }, cancellationToken: ct)); }
    public async Task<IReadOnlyList<OnboardingStepDto>> GetStepsAsync(Guid organizationId, CancellationToken ct) { using var c=db.Create(); const string sql="""SELECT p.id "Id",s.code "Code",s.title "Title",s.executive_guidance "Guidance",s.action_url "ActionUrl",s.is_required "IsRequired",p.status "Status",p.completed_at "CompletedAt",round(100.0*count(*) FILTER(WHERE p.status IN ('completed','skipped')) OVER()/NULLIF(count(*) OVER(),0),2) "ProgressPercentage" FROM valorapesquisa.organization_onboarding_progress p JOIN valorapesquisa.success_onboarding_steps s ON s.id=p.step_id WHERE p.organization_id=@organizationId AND p.deleted_at IS NULL ORDER BY s.display_order"""; return (await c.QueryAsync<OnboardingStepDto>(new CommandDefinition(sql,new{organizationId},cancellationToken:ct))).AsList(); }
    public async Task<bool> SetStepStatusAsync(Guid organizationId,Guid userId,Guid stepId,string status,string? evidence,CancellationToken ct) { using var c=db.Create(); const string sql="""WITH changed AS (UPDATE valorapesquisa.organization_onboarding_progress p SET status=@status,completed_by_user_id=@userId,completed_at=now(),updated_at=now() FROM valorapesquisa.organizations o WHERE p.id=@stepId AND p.organization_id=@organizationId AND o.id=p.organization_id AND o.status NOT IN ('blocked','suspended') RETURNING p.id) INSERT INTO valorapesquisa.onboarding_step_completions(organization_id,progress_id,step_id,user_id,status,evidence) SELECT @organizationId,id,@stepId,@userId,@status,@evidence FROM changed RETURNING id"""; return await c.ExecuteScalarAsync<Guid?>(new CommandDefinition(sql,new{organizationId,userId,stepId,status,evidence},cancellationToken:ct)) is not null; }
    public async Task<IReadOnlyList<ChecklistItemDto>> GetChecklistAsync(Guid organizationId,CancellationToken ct) { using var c=db.Create(); const string sql="""SELECT i.id "Id",i.item_code "Code",i.title "Title",i.is_required "IsRequired",i.completed_at IS NOT NULL "IsCompleted" FROM valorapesquisa.onboarding_checklist_items i JOIN valorapesquisa.onboarding_checklists c ON c.id=i.checklist_id WHERE c.organization_id=@organizationId ORDER BY i.display_order"""; return (await c.QueryAsync<ChecklistItemDto>(new CommandDefinition(sql,new{organizationId},cancellationToken:ct))).AsList(); }
    public async Task<bool> CompleteChecklistItemAsync(Guid organizationId,Guid userId,Guid itemId,CancellationToken ct) { using var c=db.Create(); const string sql="""UPDATE valorapesquisa.onboarding_checklist_items i SET completed_at=now(),completed_by_user_id=@userId,updated_at=now() FROM valorapesquisa.onboarding_checklists c,valorapesquisa.organizations o WHERE i.id=@itemId AND c.id=i.checklist_id AND c.organization_id=@organizationId AND o.id=c.organization_id AND o.status NOT IN ('blocked','suspended')"""; return await c.ExecuteAsync(new CommandDefinition(sql,new{organizationId,userId,itemId},cancellationToken:ct))>0; }
    public async Task<IReadOnlyList<AdoptionMetricDto>> GetAdoptionAsync(Guid organizationId,CancellationToken ct) { using var c=db.Create(); const string sql="""SELECT feature_code "FeatureCode",count(*) "Events",count(DISTINCT user_id) "ActiveUsers",max(occurred_at) "LastUsedAt" FROM valorapesquisa.product_usage_events WHERE organization_id=@organizationId GROUP BY feature_code ORDER BY count(*) DESC"""; return (await c.QueryAsync<AdoptionMetricDto>(new CommandDefinition(sql,new{organizationId},cancellationToken:ct))).AsList(); }
    public async Task<CustomerHealthScoreDto> CalculateHealthAsync(Guid organizationId,CancellationToken ct) { using var c=db.Create(); const string sql="""WITH m AS (SELECT least(100,count(DISTINCT e.occurred_at::date)*10)::numeric usage,least(100,count(DISTINCT e.feature_code)*15)::numeric adoption,(SELECT least(100,count(*)*20)::numeric FROM valorapesquisa.surveys WHERE organization_id=@organizationId) diagnostics,(SELECT least(100,count(*)*5)::numeric FROM valorapesquisa.responses r JOIN valorapesquisa.surveys s ON s.id=r.survey_id WHERE s.organization_id=@organizationId) engagement FROM valorapesquisa.product_usage_events e WHERE e.organization_id=@organizationId), score AS (SELECT round((usage+adoption+diagnostics+engagement)/4,2) value,* FROM m), saved AS (INSERT INTO valorapesquisa.customer_health_scores(organization_id,score,level,usage_score,adoption_score,diagnostic_score,engagement_score,risk_level,calculated_at) SELECT @organizationId,value,CASE WHEN value>=80 THEN 'healthy' WHEN value>=50 THEN 'attention' ELSE 'risk' END,usage,adoption,diagnostics,engagement,CASE WHEN value<50 THEN 'adoption_risk' ELSE 'none' END,now() FROM score RETURNING *) SELECT score "Score",level "Level",usage_score "Usage",adoption_score "Adoption",diagnostic_score "Diagnostics",engagement_score "Engagement",risk_level "Risk",calculated_at "CalculatedAt" FROM saved"""; return await c.QuerySingleAsync<CustomerHealthScoreDto>(new CommandDefinition(sql,new{organizationId},cancellationToken:ct)); }
    public async Task<Guid> CreateTaskAsync(Guid organizationId,Guid userId,CreateCustomerSuccessTaskRequest request,CancellationToken ct) { using var c=db.Create(); return await c.QuerySingleAsync<Guid>(new CommandDefinition("INSERT INTO valorapesquisa.customer_success_tasks(organization_id,title,description,due_at,created_by_user_id) VALUES(@organizationId,@Title,@Description,@DueAt,@userId) RETURNING id",new{organizationId,userId,request.Title,request.Description,request.DueAt},cancellationToken:ct)); }
    public async Task<Guid> CreateNoteAsync(Guid organizationId,Guid userId,CreateCustomerSuccessNoteRequest request,CancellationToken ct) { using var c=db.Create(); return await c.QuerySingleAsync<Guid>(new CommandDefinition("INSERT INTO valorapesquisa.customer_success_notes(organization_id,author_user_id,note_type,content) VALUES(@organizationId,@userId,@Type,@Content) RETURNING id",new{organizationId,userId,request.Type,request.Content},cancellationToken:ct)); }
}
