using Dapper;
using System.Data;
using System.Security.Cryptography;
using System.Text;
using Valora.Application.Exceptions;
using Valora.Application.ActionCenter;
using Valora.Application.Contracts;
using Valora.Application.Workspace;
namespace Valora.Infrastructure.Repositories;

public sealed class ActionPlanRepository(IDbConnectionFactory db, IDbTransactionFactory tx) : IActionPlanRepository {
    const string Projection = "SELECT p.id,p.title,p.summary,p.origin_type OriginType,p.status,p.priority,p.owner_user_id OwnerUserId,p.due_at DueAt,p.evidence_summary EvidenceSummary,p.expected_outcome ExpectedOutcome,CASE WHEN count(i.id) FILTER(WHERE i.status<>'canceled')=0 THEN 0 ELSE coalesce(round(avg(i.progress_percent) FILTER(WHERE i.status<>'canceled'))::int,0) END ProgressPercent,p.created_at CreatedAt,u.name OwnerName,count(i.id) FILTER(WHERE i.status NOT IN('completed','canceled'))::int ActiveItemCount,p.version Version,p.approved_at ApprovedAt,p.approved_version ApprovedVersion,p.actual_started_at ActualStartedAt,p.completed_at CompletedAt,p.completion_result CompletionResult,p.completion_evidence CompletionEvidence FROM valorapesquisa.action_plans p LEFT JOIN valorapesquisa.action_items i ON i.action_plan_id=p.id AND i.organization_id=p.organization_id AND i.deleted_at IS NULL LEFT JOIN valorapesquisa.users u ON u.id=p.owner_user_id AND u.organization_id=p.organization_id AND u.deleted_at IS NULL";
    const string Scope = "p.organization_id=@o AND p.deleted_at IS NULL AND EXISTS(SELECT 1 FROM valorapesquisa.organization_modules om_scope WHERE om_scope.organization_id=@o AND om_scope.module_code='organizational_intelligence' AND om_scope.enabled) AND (@wide OR p.owner_user_id IS NULL OR p.owner_user_id=@u OR EXISTS(SELECT 1 FROM valorapesquisa.action_items ai WHERE ai.action_plan_id=p.id AND ai.organization_id=p.organization_id AND ai.deleted_at IS NULL AND ai.responsible_user_id=@u))";
    public async Task<IReadOnlyList<ActionPlanDto>> List(Guid o, Guid u, bool wide, CancellationToken c) { using var x=db.Create(); return (await x.QueryAsync<ActionPlanDto>(new CommandDefinition(Projection+$" WHERE {Scope} GROUP BY p.id,u.name ORDER BY p.created_at DESC",new{o,u,wide},cancellationToken:c))).AsList(); }
    public async Task<PageResult<ActionPlanDto>> List(Guid o,Guid u,bool wide,ActionPlanListQuery query,CancellationToken c) {
        var page=query.ValidPage;var size=query.ValidPageSize;var offset=checked((page-1)*size);
        var search=string.IsNullOrWhiteSpace(query.Search)?null:query.Search.Trim();
        var status=ActionStatuses.Plan.Contains(query.Status??"")?query.Status:null;
        var priority=ActionStatuses.Priorities.Contains(query.Priority??"")?query.Priority:null;
        var due=query.Due is "overdue" or "today" or "upcoming" or "none"?query.Due:null;
        var filtered=Scope+" AND (@search IS NULL OR p.title ILIKE '%'||@search||'%' OR p.summary ILIKE '%'||@search||'%') AND (@status IS NULL OR p.status=@status) AND (@active=false OR p.status=ANY(@activeStatuses)) AND (@owner IS NULL OR p.owner_user_id=@owner) AND (@priority IS NULL OR p.priority=@priority) AND (@due IS NULL OR @due='overdue' AND (p.due_at AT TIME ZONE (SELECT time_zone FROM valorapesquisa.organizations WHERE id=@o))::date < (now() AT TIME ZONE (SELECT time_zone FROM valorapesquisa.organizations WHERE id=@o))::date OR @due='today' AND (p.due_at AT TIME ZONE (SELECT time_zone FROM valorapesquisa.organizations WHERE id=@o))::date = (now() AT TIME ZONE (SELECT time_zone FROM valorapesquisa.organizations WHERE id=@o))::date OR @due='upcoming' AND (p.due_at AT TIME ZONE (SELECT time_zone FROM valorapesquisa.organizations WHERE id=@o))::date > (now() AT TIME ZONE (SELECT time_zone FROM valorapesquisa.organizations WHERE id=@o))::date OR @due='none' AND p.due_at IS NULL)";
        var order=query.Sort switch{"title"=>"p.title,p.id","due"=>"p.due_at NULLS LAST,p.id",_=>"p.created_at DESC,p.id DESC"};
        var args=new{o,u,wide,search,status,active=query.Scope==ActionPlanScopeFilter.Active,activeStatuses=new[]{"approved","in_execution"},owner=query.OwnerUserId,priority,due,size,offset};
        using var x=db.Create();using var q=await x.QueryMultipleAsync(new CommandDefinition($"SELECT count(*)::int FROM valorapesquisa.action_plans p WHERE {filtered}; {Projection} WHERE {filtered} GROUP BY p.id,u.name ORDER BY {order} LIMIT @size OFFSET @offset",args,cancellationToken:c));
        var total=await q.ReadSingleAsync<int>();var rows=(await q.ReadAsync<ActionPlanDto>()).AsList();return new(rows,page,size,total);
    }
    public async Task<PageResult<ActionOptionDto>> Options(Guid o, Guid u, bool wide, OptionQuery query, CancellationToken c) {
        var page=query.ValidPage;var size=query.ValidPageSize;var offset=checked((page-1)*size);var args=OptionParameters(o,u,wide,query.Search,offset,size);
        const string scope="p.organization_id=@o AND p.deleted_at IS NULL AND p.status=ANY(@statuses) AND (@wide OR p.owner_user_id IS NULL OR p.owner_user_id=@u) AND (@search IS NULL OR p.title ILIKE '%'||@search||'%')";
        var sql=$"SELECT count(*)::int FROM valorapesquisa.action_plans p WHERE {scope}; SELECT p.id Id,p.title Title,p.status Status,p.priority Priority,p.summary Context,p.owner_user_id ResponsibleUserId,u2.name ResponsibleName FROM valorapesquisa.action_plans p LEFT JOIN valorapesquisa.users u2 ON u2.id=p.owner_user_id AND u2.organization_id=p.organization_id AND u2.deleted_at IS NULL WHERE {scope} ORDER BY p.title,p.id LIMIT @size OFFSET @offset;";
        using var x=db.Create();using var result=await x.QueryMultipleAsync(new CommandDefinition(sql,args,cancellationToken:c));var total=await result.ReadSingleAsync<int>();return new((await result.ReadAsync<ActionOptionDto>()).AsList(),page,size,total);
    }
    public async Task<ActionPlanDto?> Get(Guid o, Guid u, Guid id, bool wide, CancellationToken c) { using var x=db.Create();return await x.QuerySingleOrDefaultAsync<ActionPlanDto>(new CommandDefinition(Projection+$" WHERE {Scope} AND p.id=@id GROUP BY p.id,u.name",new{o,u,id,wide},cancellationToken:c)); }
    public async Task<ActionPlanClosureCheck?> ClosureCheck(Guid o,Guid u,Guid id,bool wide,CancellationToken c) {
        const string sql="SELECT p.expected_outcome ExpectedOutcome,p.completion_result CompletionResult,p.completion_evidence CompletionEvidence,p.evidence_summary EvidenceSummary,p.due_at DueAt,(p.owner_user_id IS NOT NULL AND EXISTS(SELECT 1 FROM valorapesquisa.users owner WHERE owner.id=p.owner_user_id AND owner.organization_id=p.organization_id AND owner.status='active' AND owner.deleted_at IS NULL)) OwnerEligible,count(i.id) FILTER(WHERE i.status NOT IN('completed','canceled'))::int OpenActivities,count(i.id) FILTER(WHERE i.status='blocked')::int BlockedActivities,count(i.id) FILTER(WHERE i.status='completed')::int CompletedActivities,count(i.id) FILTER(WHERE i.status='canceled')::int CanceledActivities,p.status FROM valorapesquisa.action_plans p LEFT JOIN valorapesquisa.action_items i ON i.action_plan_id=p.id AND i.organization_id=p.organization_id AND i.deleted_at IS NULL WHERE p.id=@id AND "+Scope+" GROUP BY p.id";
        using var x=db.Create();var row=await x.QuerySingleOrDefaultAsync<ClosureRow>(new CommandDefinition(sql,new{o,u,id,wide},cancellationToken:c));
        if(row is null)return null;
        var pending=new List<string>();
        var warnings=new List<string>();
        var destinations=new List<ActionPlanReadinessDestination>();
        if(row.Status=="draft"){
            if(!row.OwnerEligible){pending.Add("Defina um responsável ativo e elegível desta organização.");destinations.Add(new("owner","Definir responsável","responsavel"));}
            if(string.IsNullOrWhiteSpace(row.EvidenceSummary)){pending.Add("Complete a evidência de origem do plano.");destinations.Add(new("content","Revisar conteúdo","resumo"));}
            if(row.DueAt is null){pending.Add("Defina um prazo para o plano.");destinations.Add(new("due","Definir prazo","prazo"));}
        }else if(row.Status=="proposed"){
            warnings.Add("A avaliação da versão submetida está pendente; aprovação ou devolução dependem de perfil autorizado.");
            destinations.Add(new("evaluation","Acompanhar avaliação","etapa"));
        }else if(row.Status=="approved"){
            if(!row.OwnerEligible){pending.Add("O responsável aprovado não está mais elegível; corrija-o antes de iniciar.");destinations.Add(new("owner","Definir responsável","responsavel"));}
            warnings.Add("A aprovação está válida para o conteúdo avaliado; alterações materiais exigem nova avaliação.");
        }else if(row.Status=="in_execution"){
            if(!row.OwnerEligible){pending.Add("Defina um responsável ativo e elegível antes de encerrar.");destinations.Add(new("owner","Definir responsável","responsavel"));}
            if(string.IsNullOrWhiteSpace(row.EvidenceSummary)){pending.Add("Complete a evidência de origem antes de encerrar.");destinations.Add(new("content","Revisar conteúdo","resumo"));}
            if(row.DueAt is null){pending.Add("Defina o prazo do plano antes de encerrar.");destinations.Add(new("due","Definir prazo","prazo"));}
            if(row.OpenActivities>0){pending.Add($"Regularize {row.OpenActivities} atividade(s) aberta(s).");destinations.Add(new("activities","Consultar atividades abertas","atividades"));}
            if(row.CompletedActivities==0){pending.Add("Conclua ao menos uma atividade; se não houve execução, cancele o plano com justificativa.");destinations.Add(new("activities","Consultar atividades","atividades"));}
            if(row.BlockedActivities>0){warnings.Add($"Há {row.BlockedActivities} atividade(s) bloqueada(s) que precisam de decisão.");destinations.Add(new("blocked","Consultar bloqueios","atividades"));}
        }
        var allowed=AllowedLifecycleActions(row.Status);
        return new(row.Status,allowed,pending,warnings,destinations,row.OpenActivities+row.CompletedActivities+row.CanceledActivities,row.OpenActivities,row.BlockedActivities,row.CompletedActivities,row.CanceledActivities,row.ExpectedOutcome,row.CompletionResult,row.CompletionEvidence,pending.Count==0);
    }
    public async Task<PageResult<ActionPlanHistoryDto>> History(Guid o,Guid u,Guid id,bool wide,int page,string? operation,CancellationToken c) {
        page=Math.Max(1,page);const int size=10;var offset=checked((page-1)*size);
        var filter=operation is "edit" or "assign" or "reschedule" or "submit" or "return" or "approve" or "start" or "complete" or "cancel" or "approval_invalidated"?operation:null;
        const string access="p.organization_id=@o AND p.id=@id AND p.deleted_at IS NULL AND (@wide OR p.owner_user_id IS NULL OR p.owner_user_id=@u OR EXISTS(SELECT 1 FROM valorapesquisa.action_items ai WHERE ai.action_plan_id=p.id AND ai.organization_id=p.organization_id AND ai.deleted_at IS NULL AND ai.responsible_user_id=@u))";
        var sql=$"SELECT count(*)::int FROM valorapesquisa.action_plan_change_history h JOIN valorapesquisa.action_plans p ON p.id=h.action_plan_id WHERE {access} AND (@filter IS NULL OR h.operation=@filter); SELECT h.id,h.operation,h.from_value FromValue,h.to_value ToValue,h.reason,u2.name AuthorName,h.changed_at ChangedAt,h.intent_version IntentVersion FROM valorapesquisa.action_plan_change_history h JOIN valorapesquisa.action_plans p ON p.id=h.action_plan_id LEFT JOIN valorapesquisa.users u2 ON u2.id=h.changed_by_user_id AND u2.organization_id=p.organization_id WHERE {access} AND (@filter IS NULL OR h.operation=@filter) ORDER BY h.changed_at DESC,h.id DESC LIMIT @size OFFSET @offset";
        using var x=db.Create();using var q=await x.QueryMultipleAsync(new CommandDefinition(sql,new{o,u,id,wide,filter,size,offset},cancellationToken:c));
        var total=await q.ReadSingleAsync<int>();return new((await q.ReadAsync<ActionPlanHistoryDto>()).AsList(),page,size,total);
    }
    public async Task<ActionDashboardDto> Dashboard(Guid o, Guid u, bool wide, CancellationToken c) {
        var plans=(await List(o,u,wide,new ActionPlanListQuery(PageSize:6),c)).Items;using var x=db.Create();
        const string sql="""
        SELECT count(*) FILTER(WHERE i.priority='critical' AND i.status NOT IN('completed','canceled'))::int Critical,count(*) FILTER(WHERE (i.due_at AT TIME ZONE org.time_zone)::date < (now() AT TIME ZONE org.time_zone)::date AND i.status NOT IN('completed','canceled'))::int Overdue,count(*) FILTER(WHERE i.responsible_user_id IS NULL AND i.status NOT IN('completed','canceled'))::int Unassigned,count(*) FILTER(WHERE i.status='blocked')::int Blocked,(SELECT count(*)::int FROM valorapesquisa.action_plans ap WHERE ap.organization_id=@o AND ap.deleted_at IS NULL AND ap.status IN('approved','in_execution') AND (@wide OR ap.owner_user_id IS NULL OR ap.owner_user_id=@u OR EXISTS(SELECT 1 FROM valorapesquisa.action_items ai WHERE ai.action_plan_id=ap.id AND ai.organization_id=ap.organization_id AND ai.deleted_at IS NULL AND ai.responsible_user_id=@u))) ActivePlans
        FROM valorapesquisa.action_items i JOIN valorapesquisa.action_plans p ON p.id=i.action_plan_id AND p.organization_id=i.organization_id JOIN valorapesquisa.organizations org ON org.id=i.organization_id WHERE i.organization_id=@o AND i.deleted_at IS NULL AND p.deleted_at IS NULL AND EXISTS(SELECT 1 FROM valorapesquisa.organization_modules om_scope WHERE om_scope.organization_id=@o AND om_scope.module_code='organizational_intelligence' AND om_scope.enabled) AND (@wide OR i.responsible_user_id IS NULL OR i.responsible_user_id=@u OR p.owner_user_id=@u);
        SELECT i.id,i.action_plan_id ActionPlanId,i.title,i.description,i.origin_type OriginType,i.origin_id OriginId,i.related_dimension RelatedDimension,i.related_index_code RelatedIndexCode,i.priority,i.status,i.responsible_user_id ResponsibleUserId,i.due_at DueAt,i.completed_at CompletedAt,i.progress_percent ProgressPercent,i.evidence_summary EvidenceSummary,i.expected_outcome ExpectedOutcome,i.completion_evidence CompletionEvidence,i.ai_recommendation_summary AiRecommendationSummary,i.created_at CreatedAt,i.version Version,ru.name ResponsibleName,p.title PlanTitle,i.metadata_json->>'completionResult' CompletionResult
        FROM valorapesquisa.action_items i JOIN valorapesquisa.action_plans p ON p.id=i.action_plan_id AND p.organization_id=i.organization_id LEFT JOIN valorapesquisa.users ru ON ru.id=i.responsible_user_id AND ru.organization_id=i.organization_id AND ru.deleted_at IS NULL WHERE i.organization_id=@o AND i.deleted_at IS NULL AND p.deleted_at IS NULL AND EXISTS(SELECT 1 FROM valorapesquisa.organization_modules om_scope WHERE om_scope.organization_id=@o AND om_scope.module_code='organizational_intelligence' AND om_scope.enabled) AND i.status NOT IN('completed','canceled') AND (@wide OR i.responsible_user_id IS NULL OR i.responsible_user_id=@u OR p.owner_user_id=@u) ORDER BY i.due_at NULLS LAST,i.created_at DESC,i.id LIMIT 12;
        """;
        using var q=await x.QueryMultipleAsync(new CommandDefinition(sql,new{o,u,wide},cancellationToken:c));var totals=await q.ReadSingleAsync<DashboardTotals>();var items=(await q.ReadAsync<ActionItemDto>()).AsList();return new(totals.Critical,totals.Overdue,totals.Unassigned,totals.ActivePlans,totals.Blocked,items,plans);
    }
    private sealed record DashboardTotals(int Critical,int Overdue,int Unassigned,int Blocked,int ActivePlans);
    public async Task<Guid> Create(Guid o,Guid u,bool globalAdministrator,CreateActionPlanRequest r,CancellationToken c){
        if(o==Guid.Empty||u==Guid.Empty)throw new UnauthorizedAccessException("Sessão ou organização inválida.");
        var normalized=new{Title=r.Title.Trim(),Summary=r.Summary.Trim(),r.OriginType,r.OriginId,r.DiagnosticId,r.ResultId,r.GovernanceCycleId,r.Priority,r.OwnerUserId,StartsAt=r.StartsAt?.Date,DueAt=r.DueAt?.Date,EvidenceSummary=r.EvidenceSummary.Trim(),ExpectedOutcome=r.ExpectedOutcome.Trim()};
        var command=r.CommandId.Trim();var fingerprint=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(System.Text.Json.JsonSerializer.Serialize(new{organization=o,actor=u,operation="create-action-plan",payload=normalized})))).ToLowerInvariant();
        await using var z=await tx.BeginAsync(c);
        await z.Connection.ExecuteAsync(new CommandDefinition("SELECT pg_advisory_xact_lock(hashtextextended(@lockKey,0))",new{lockKey=$"{o:N}:{u:N}:create-action-plan:{command}"},z.Transaction,cancellationToken:c));
        var replay=await z.Connection.QuerySingleOrDefaultAsync<CreateReplay>(new CommandDefinition("SELECT request_hash RequestHash,result_id ResultId FROM valorapesquisa.action_plan_create_commands WHERE organization_id=@o AND created_by_user_id=@u AND operation='create-action-plan' AND command_id=@command",new{o,u,command},z.Transaction,cancellationToken:c));
        if(replay is not null){if(replay.RequestHash!=fingerprint)throw new ConcurrencyConflictException("A chave de criação já foi usada com outro conteúdo. Revise os campos antes de tentar novamente.");var allowed=await z.Connection.ExecuteScalarAsync<bool>(new CommandDefinition($"SELECT EXISTS(SELECT 1 FROM valorapesquisa.action_plans p WHERE p.id=@id AND {Scope})",new{o,u,wide=globalAdministrator,id=replay.ResultId},z.Transaction,cancellationToken:c));if(!allowed)throw new UnauthorizedAccessException("O resultado da criação não está mais acessível.");await z.CommitAsync();return replay.ResultId;}
        var id=Guid.NewGuid();var affected=await z.Connection.ExecuteAsync(new CommandDefinition("""
        INSERT INTO valorapesquisa.action_plans(id,organization_id,diagnostic_id,result_id,governance_cycle_id,title,summary,origin_type,origin_id,status,priority,owner_user_id,created_by_user_id,starts_at,due_at,evidence_summary,expected_outcome)
        SELECT @id,@o,@DiagnosticId,@ResultId,@GovernanceCycleId,@Title,@Summary,@OriginType,@OriginId,'draft',@Priority,@OwnerUserId,@u,
          CASE WHEN @StartsAt IS NULL THEN NULL ELSE (@StartsAt::date::timestamp AT TIME ZONE org.time_zone) END,
          CASE WHEN @DueAt IS NULL THEN NULL ELSE ((@DueAt::date + 1)::timestamp AT TIME ZONE org.time_zone) - interval '1 microsecond' END,@EvidenceSummary,@ExpectedOutcome
        FROM valorapesquisa.organizations org WHERE org.id=@o AND org.deleted_at IS NULL
          AND EXISTS(SELECT 1 FROM valorapesquisa.users actor WHERE actor.id=@u AND actor.status='active' AND actor.deleted_at IS NULL AND (actor.organization_id=@o OR @globalAdministrator))
          AND EXISTS(SELECT 1 FROM valorapesquisa.organization_modules om WHERE om.organization_id=@o AND om.module_code='organizational_intelligence' AND om.enabled)
          AND (@OwnerUserId IS NULL OR EXISTS(SELECT 1 FROM valorapesquisa.users usr WHERE usr.id=@OwnerUserId AND usr.organization_id=@o AND usr.status='active' AND usr.deleted_at IS NULL))
          AND (@DueAt IS NULL OR @DueAt::date >= (now() AT TIME ZONE org.time_zone)::date) AND (@StartsAt IS NULL OR @DueAt IS NULL OR @StartsAt::date<=@DueAt::date)
          AND (@DiagnosticId IS NULL OR EXISTS(SELECT 1 FROM valorapesquisa.diagnostics d WHERE d.id=@DiagnosticId AND d.organization_id=@o AND d.deleted_at IS NULL))
          AND (@ResultId IS NULL OR EXISTS(SELECT 1 FROM valorapesquisa.results rs WHERE rs.id=@ResultId AND rs.organization_id=@o))
          AND (@GovernanceCycleId IS NULL OR EXISTS(SELECT 1 FROM valorapesquisa.organizational_governance_cycles gc WHERE gc.id=@GovernanceCycleId AND gc.organization_id=@o AND gc.deleted_at IS NULL))
          AND ((@OriginType='manual' AND @OriginId IS NULL)
            OR (@OriginType='diagnostic' AND @OriginId=@DiagnosticId)
            OR (@OriginType='result' AND @OriginId=@ResultId)
            OR (@OriginType='ai_insight' AND EXISTS(SELECT 1 FROM valorapesquisa.valora_ai_insights vi WHERE vi.id=@OriginId AND vi.organization_id=@o AND vi.deleted_at IS NULL AND vi.status IN('reviewed','approved')))
            OR (@OriginType='alert' AND EXISTS(SELECT 1 FROM valorapesquisa.intelligent_alerts al WHERE al.id=@OriginId AND al.organization_id=@o AND al.deleted_at IS NULL AND al.status IN('open','acknowledged','in_progress')))
            OR (@OriginType='decision' AND EXISTS(SELECT 1 FROM valorapesquisa.organizational_decisions od WHERE od.id=@OriginId AND od.organization_id=@o AND od.deleted_at IS NULL AND od.status IN('approved','in_execution','completed'))))
        """,new{id,o,u,globalAdministrator,normalized.Title,normalized.Summary,normalized.OriginType,normalized.OriginId,normalized.DiagnosticId,normalized.ResultId,normalized.GovernanceCycleId,normalized.Priority,normalized.OwnerUserId,normalized.StartsAt,normalized.DueAt,normalized.EvidenceSummary,normalized.ExpectedOutcome},z.Transaction,cancellationToken:c));
        if(affected!=1)throw new ConflictAppException("Não foi possível criar o plano. Confira organização, módulo contratado, responsável, referências e prazo.");
        await z.Connection.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.action_plan_create_commands(organization_id,created_by_user_id,command_id,operation,request_hash,result_id) VALUES(@o,@u,@command,'create-action-plan',@fingerprint,@id)",new{o,u,command,fingerprint,id},z.Transaction,cancellationToken:c));
        await z.CommitAsync();return id;
    }
    public Task Edit(Guid o,Guid u,Guid id,bool wide,EditActionPlanRequest r,CancellationToken c)=>Modify(o,u,id,wide,r.Version,r.CommandId,"edit",r,null,c);
    public Task Assign(Guid o,Guid u,Guid id,bool wide,AssignResponsibleRequest r,CancellationToken c)=>Modify(o,u,id,wide,r.Version,r.CommandId,"assign",r,r.Reason,c);
    public Task Reschedule(Guid o,Guid u,Guid id,bool wide,RescheduleActionRequest r,CancellationToken c)=>Modify(o,u,id,wide,r.Version,r.CommandId,"reschedule",r,r.Reason,c);
    public Task Complete(Guid o,Guid u,Guid id,bool wide,CompleteActionPlanRequest r,CancellationToken c)=>TransitionCore(o,u,id,wide,"complete",r.Version,r.CommandId,r.Note,r.Result,r.Evidence,c);
    public Task Transition(Guid o,Guid u,Guid id,bool wide,string operation,PlanTransitionRequest r,CancellationToken c)=>TransitionCore(o,u,id,wide,operation,r.Version,r.CommandId,r.Note,null,null,c);
    private async Task TransitionCore(Guid o,Guid u,Guid id,bool wide,string operation,long version,string commandId,string? note,string? result,string? evidence,CancellationToken c){
        // Validação da intenção recebida.
        if(o==Guid.Empty||u==Guid.Empty)throw new UnauthorizedAccessException("Sessão ou organização inválida.");
        if(string.IsNullOrWhiteSpace(commandId))throw new ArgumentException("A chave da operação é obrigatória.",nameof(commandId));

        // Resolução da transição. Uma operação desconhecida falha antes de abrir a transação.
        (string From, string To) rule = operation switch
        {
            "submit" => ("draft", "proposed"),
            "return" => ("proposed", "draft"),
            "approve" => ("proposed", "approved"),
            "start" => ("approved", "in_execution"),
            "complete" => ("in_execution", "completed"),
            "cancel" => ("*", "canceled"),
            _ => throw new ArgumentException(
                "Operação de ciclo de vida inválida.",
                nameof(operation))
        };
        var intent=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(System.Text.Json.JsonSerializer.Serialize(new{o,u,id,version,operation,note=note?.Trim(),result=result?.Trim(),evidence=evidence?.Trim()})))).ToLowerInvariant();

        // Autorização, concorrência e replay são revalidados sob o mesmo lock do plano.
        await using var z=await tx.BeginAsync(c);await z.Connection.ExecuteAsync(new CommandDefinition("SELECT pg_advisory_xact_lock(hashtextextended(@key,0))",new{key=$"{o:N}:{id:N}:plan-lifecycle"},z.Transaction,cancellationToken:c));
        var current=await z.Connection.QuerySingleOrDefaultAsync<LifecycleState>(new CommandDefinition("SELECT p.status,p.version,p.title,p.summary,p.evidence_summary EvidenceSummary,p.expected_outcome ExpectedOutcome,p.owner_user_id OwnerUserId,p.starts_at StartsAt,p.due_at DueAt,p.approved_version ApprovedVersion FROM valorapesquisa.action_plans p WHERE p.id=@id AND "+Scope+" AND EXISTS(SELECT 1 FROM valorapesquisa.users actor WHERE actor.id=@u AND actor.status='active' AND actor.deleted_at IS NULL) FOR UPDATE OF p",new{o,u,id,wide},z.Transaction,cancellationToken:c));if(current is null)throw new KeyNotFoundException("Plano não encontrado no escopo autorizado.");
        var replay=await z.Connection.QuerySingleOrDefaultAsync<string>(new CommandDefinition("SELECT intent_hash FROM valorapesquisa.action_plan_change_history WHERE action_plan_id=@id AND command_id=@commandId",new{id,commandId},z.Transaction,cancellationToken:c));if(replay is not null){if(replay==intent){await z.CommitAsync();return;}throw new ConcurrencyConflictException("A chave da operação já foi usada com outra intenção.");}

        // Pré-condições do estado e do conteúdo atual.
        if(current.Version!=version)throw new ConcurrencyConflictException("O plano foi alterado. Consulte os dados atuais antes de reenviar.");if(current.Status is "completed" or "canceled")throw new ConflictAppException("Planos encerrados não podem mudar de estado.");if(rule.From!="*"&&current.Status!=rule.From)throw new ConflictAppException($"A transição de {ActionStatuses.Label(current.Status)} para {ActionStatuses.Label(rule.To)} não é permitida.");
        if(operation=="submit"&&(string.IsNullOrWhiteSpace(current.Title)||string.IsNullOrWhiteSpace(current.Summary)||string.IsNullOrWhiteSpace(current.ExpectedOutcome)||string.IsNullOrWhiteSpace(current.EvidenceSummary)||current.OwnerUserId is null||current.DueAt is null||(current.StartsAt.HasValue&&current.StartsAt>current.DueAt)))throw new ConflictAppException("Complete título, descrição, resultado esperado, evidência de origem, responsável e datas coerentes antes de submeter.");
        if(operation is "submit" or "start"){
            var ownerEligible=current.OwnerUserId.HasValue&&await z.Connection.ExecuteScalarAsync<bool>(new CommandDefinition("SELECT EXISTS(SELECT 1 FROM valorapesquisa.users owner WHERE owner.id=@owner AND owner.organization_id=@o AND owner.status='active' AND owner.deleted_at IS NULL)",new{o,owner=current.OwnerUserId},z.Transaction,cancellationToken:c));
            if(!ownerEligible)throw new ConflictAppException("O responsável está ausente, inativo ou não pertence à organização. Corrija a atribuição antes de continuar.");
        }
        if(operation=="complete"){
            var ownerEligible=current.OwnerUserId.HasValue&&await z.Connection.ExecuteScalarAsync<bool>(new CommandDefinition("SELECT EXISTS(SELECT 1 FROM valorapesquisa.users owner WHERE owner.id=@owner AND owner.organization_id=@o AND owner.status='active' AND owner.deleted_at IS NULL)",new{o,owner=current.OwnerUserId},z.Transaction,cancellationToken:c));
            if(!ownerEligible||string.IsNullOrWhiteSpace(current.EvidenceSummary)||current.DueAt is null)throw new ConflictAppException("Defina responsável elegível, evidência de origem e prazo antes de concluir o plano.");
        }
        // Alterações materiais mudam o estado para proposed e invalidam a aprovação;
        // alterações operacionais preservam o estado approved mesmo ao incrementar a versão.
        if(operation=="start"&&current.ApprovedVersion is null)throw new ConflictAppException("O conteúdo atual ainda não possui aprovação válida. Submeta-o novamente para avaliação.");
        var counts=await z.Connection.QuerySingleAsync<ActivityCounts>(new CommandDefinition("SELECT count(*) FILTER(WHERE status NOT IN('completed','canceled'))::int Open,count(*) FILTER(WHERE status='completed')::int Completed,count(*) FILTER(WHERE status='canceled')::int Canceled FROM valorapesquisa.action_items WHERE action_plan_id=@id AND organization_id=@o AND deleted_at IS NULL",new{o,id},z.Transaction,cancellationToken:c));
        if((operation is "complete" or "cancel")&&counts.Open>0)throw new ConflictAppException($"Regularize {counts.Open} atividade(s) aberta(s) antes de encerrar o plano.");if(operation=="complete"&&counts.Completed==0)throw new ConflictAppException("Conclua ao menos uma atividade antes de encerrar o plano; se não houve execução, cancele-o com justificativa.");

        // Persistência do estado e metadados de ciclo.
        var changed=await z.Connection.ExecuteAsync(new CommandDefinition("UPDATE valorapesquisa.action_plans SET status=@next,approved_by_user_id=CASE WHEN @operation='approve' THEN @u ELSE approved_by_user_id END,approved_at=CASE WHEN @operation='approve' THEN now() ELSE approved_at END,approved_version=CASE WHEN @operation='approve' THEN version+1 ELSE approved_version END,actual_started_at=CASE WHEN @operation='start' THEN now() ELSE actual_started_at END,completed_at=CASE WHEN @operation IN('complete','cancel') THEN now() ELSE completed_at END,completion_result=CASE WHEN @operation='complete' THEN @result ELSE completion_result END,completion_evidence=CASE WHEN @operation='complete' THEN @evidence ELSE completion_evidence END,version=version+1,updated_at=now() WHERE id=@id AND organization_id=@o AND version=@version",new{o,u,id,version,next=rule.To,operation,result=result?.Trim(),evidence=evidence?.Trim()},z.Transaction,cancellationToken:c));if(changed!=1)throw new ConcurrencyConflictException("O plano foi alterado durante a operação.");

        // Histórico pertence à mesma transação da mudança.
        await z.Connection.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.action_plan_change_history(action_plan_id,operation,from_value,to_value,reason,changed_by_user_id,command_id,intent_hash,intent_version) VALUES(@id,@operation,@from,@next,@note,@u,@commandId,@intent,@version)",new{id,operation,from=current.Status,next=rule.To,note=note?.Trim(),u,commandId,intent,version},z.Transaction,cancellationToken:c));await z.CommitAsync();
    }
    private async Task Modify(Guid o,Guid u,Guid id,bool wide,long version,string commandId,string operation,object request,string? reason,CancellationToken c){
        await using var z=await tx.BeginAsync(c);var hash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(System.Text.Json.JsonSerializer.Serialize(new{o,u,id,version,operation,request})))).ToLowerInvariant();
        await z.Connection.ExecuteAsync(new CommandDefinition("SELECT pg_advisory_xact_lock(hashtextextended(@key,0))",new{key=$"{o:N}:{id:N}:{commandId}"},z.Transaction,cancellationToken:c));
        var old=await z.Connection.QuerySingleOrDefaultAsync<PlanState>(new CommandDefinition("SELECT p.status,p.version,p.title,p.summary,p.priority,p.expected_outcome ExpectedOutcome,p.owner_user_id OwnerUserId,(p.due_at AT TIME ZONE org.time_zone)::date DueAt,u2.name OwnerName FROM valorapesquisa.action_plans p JOIN valorapesquisa.organizations org ON org.id=p.organization_id LEFT JOIN valorapesquisa.users u2 ON u2.id=p.owner_user_id AND u2.organization_id=p.organization_id WHERE p.id=@id AND "+Scope+" FOR UPDATE OF p",new{o,u,id,wide},z.Transaction,cancellationToken:c));if(old is null)throw new KeyNotFoundException("Plano não encontrado no escopo autorizado.");
        var replay=await z.Connection.QuerySingleOrDefaultAsync<string>(new CommandDefinition("SELECT intent_hash FROM valorapesquisa.action_plan_change_history WHERE action_plan_id=@id AND command_id=@commandId",new{id,commandId},z.Transaction,cancellationToken:c));if(replay is not null){if(replay==hash){await z.CommitAsync();return;}throw new ConcurrencyConflictException("A chave da operação já foi usada com outra intenção.");}if(old.Version!=version)throw new ConcurrencyConflictException("O plano foi alterado. Consulte os valores atuais antes de reenviar.");if(old.Status is "completed" or "canceled")throw new ConflictAppException("Planos concluídos ou cancelados não podem ser editados.");string before,after;int changed;
        if(request is EditActionPlanRequest edit){if(old.Status=="in_execution")throw new ConflictAppException("Conteúdo material não pode ser alterado durante a execução. Ajuste apenas responsável ou prazo.");before=System.Text.Json.JsonSerializer.Serialize(new{old.Title,old.Summary,old.Priority,old.ExpectedOutcome});after=System.Text.Json.JsonSerializer.Serialize(new{Title=edit.Title.Trim(),Summary=edit.Summary.Trim(),edit.Priority,ExpectedOutcome=edit.ExpectedOutcome.Trim()});if(before==after)throw new ConflictAppException("Nenhuma alteração foi informada.");changed=await z.Connection.ExecuteAsync(new CommandDefinition("UPDATE valorapesquisa.action_plans SET title=@Title,summary=@Summary,priority=@Priority,expected_outcome=@ExpectedOutcome,status=CASE WHEN status='approved' THEN 'proposed' ELSE status END,approved_by_user_id=CASE WHEN status='approved' THEN NULL ELSE approved_by_user_id END,approved_at=CASE WHEN status='approved' THEN NULL ELSE approved_at END,approved_version=CASE WHEN status='approved' THEN NULL ELSE approved_version END,version=version+1,updated_at=now() WHERE id=@id AND organization_id=@o AND version=@version",new{o,id,version,Title=edit.Title.Trim(),Summary=edit.Summary.Trim(),edit.Priority,ExpectedOutcome=edit.ExpectedOutcome.Trim()},z.Transaction,cancellationToken:c));}
        else if(request is AssignResponsibleRequest assign){if(old.OwnerUserId.HasValue&&string.IsNullOrWhiteSpace(assign.Reason))throw new ArgumentException("Justifique a substituição ou remoção do responsável atual.");var name=assign.ResponsibleUserId.HasValue?await z.Connection.QuerySingleOrDefaultAsync<string>(new CommandDefinition("SELECT name FROM valorapesquisa.users WHERE id=@responsible AND organization_id=@o AND status='active' AND deleted_at IS NULL",new{o,responsible=assign.ResponsibleUserId},z.Transaction,cancellationToken:c)):null;if(assign.ResponsibleUserId.HasValue&&name is null)throw new ConflictAppException("A pessoa selecionada não está ativa e elegível nesta organização.");if(old.OwnerUserId==assign.ResponsibleUserId)throw new ConflictAppException("O responsável selecionado já é o responsável atual.");before=old.OwnerName??"Sem responsável";after=name??"Sem responsável";changed=await z.Connection.ExecuteAsync(new CommandDefinition("UPDATE valorapesquisa.action_plans SET owner_user_id=@ResponsibleUserId,version=version+1,updated_at=now() WHERE id=@id AND organization_id=@o AND version=@version",new{o,id,version,assign.ResponsibleUserId},z.Transaction,cancellationToken:c));}
        else{var due=(RescheduleActionRequest)request;if(due.DueAt is null)throw new ArgumentException("Informe o novo prazo.");before=old.DueAt?.ToString("yyyy-MM-dd")??"Sem prazo";after=due.DueAt.Value.ToString("yyyy-MM-dd");if(before==after)throw new ConflictAppException("O novo prazo é igual ao prazo atual.");changed=await z.Connection.ExecuteAsync(new CommandDefinition("UPDATE valorapesquisa.action_plans p SET due_at=((@DueAt::date+1)::timestamp AT TIME ZONE org.time_zone)-interval '1 microsecond',version=version+1,updated_at=now() FROM valorapesquisa.organizations org WHERE p.id=@id AND p.organization_id=@o AND org.id=@o AND p.version=@version",new{o,id,version,due.DueAt},z.Transaction,cancellationToken:c));}
        if(changed!=1)throw new ConcurrencyConflictException("O plano foi alterado durante a operação.");
        await z.Connection.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.action_plan_change_history(action_plan_id,operation,from_value,to_value,reason,changed_by_user_id,command_id,intent_hash,intent_version) VALUES(@id,@operation,@before,@after,@reason,@u,@commandId,@hash,@version)",new{id,operation,before,after,reason=reason?.Trim(),u,commandId,hash,version},z.Transaction,cancellationToken:c));
        if(operation=="edit"&&old.Status=="approved")await z.Connection.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.action_plan_change_history(action_plan_id,operation,from_value,to_value,reason,changed_by_user_id,intent_version) VALUES(@id,'approval_invalidated','approved','proposed','Aprovação invalidada por alteração material do conteúdo.',@u,@version)",new{id,u,version},z.Transaction,cancellationToken:c));
        await z.CommitAsync();
    }
    private sealed record PlanState(string Status,long Version,string Title,string Summary,string Priority,string ExpectedOutcome,Guid? OwnerUserId,DateTime? DueAt,string? OwnerName);
    private sealed record LifecycleState(string Status,long Version,string Title,string Summary,string EvidenceSummary,string ExpectedOutcome,Guid? OwnerUserId,DateTime? StartsAt,DateTime? DueAt,long? ApprovedVersion);
    private sealed record ActivityCounts(int Open,int Completed,int Canceled);
    private sealed record ClosureRow(string Status,string ExpectedOutcome,string? CompletionResult,string? CompletionEvidence,string EvidenceSummary,DateTime? DueAt,bool OwnerEligible,int OpenActivities,int BlockedActivities,int CompletedActivities,int CanceledActivities);
    private sealed record CreateReplay(string RequestHash,Guid ResultId);
    private static DynamicParameters OptionParameters(Guid o,Guid u,bool wide,string? search,int offset,int size){var p=new DynamicParameters();p.Add("o",o,DbType.Guid);p.Add("u",u,DbType.Guid);p.Add("wide",wide);p.Add("search",string.IsNullOrWhiteSpace(search)?null:search.Trim());p.Add("statuses",new[]{"draft","proposed","approved","in_execution"});p.Add("offset",offset);p.Add("size",size);return p;}
    private static IReadOnlyList<string> AllowedLifecycleActions(string status)=>status switch{"draft"=>["submit","cancel"],"proposed"=>["return","approve","cancel"],"approved"=>["start","cancel"],"in_execution"=>["complete","cancel"],_=>[]};
}
