using Dapper;
using System.Data;
using Valora.Application.ActionCenter;
using Valora.Application.Contracts;
using Valora.Application.Workspace;
namespace Valora.Infrastructure.Repositories;

public sealed class ActionItemRepository(IDbConnectionFactory db, IDbTransactionFactory tx) : IActionItemRepository {
    internal const string Select = "SELECT id,action_plan_id ActionPlanId,title,description,origin_type OriginType,origin_id OriginId,related_dimension RelatedDimension,related_index_code RelatedIndexCode,priority,status,responsible_user_id ResponsibleUserId,due_at DueAt,completed_at CompletedAt,progress_percent ProgressPercent,evidence_summary EvidenceSummary,expected_outcome ExpectedOutcome,completion_evidence CompletionEvidence,ai_recommendation_summary AiRecommendationSummary,created_at CreatedAt FROM valorapesquisa.action_items";
    public async Task<IReadOnlyList<ActionItemDto>> List(Guid o, Guid? p, CancellationToken c) { using var x = db.Create(); return (await x.QueryAsync<ActionItemDto>(new CommandDefinition(Select + " WHERE organization_id=@o AND deleted_at IS NULL AND (@p IS NULL OR action_plan_id=@p) ORDER BY due_at NULLS LAST,created_at DESC", new { o, p }, cancellationToken: c))).ToList(); }
    public async Task<PageResult<ActionOptionDto>> Options(Guid o,Guid u,bool wide,OptionQuery query,CancellationToken c) {
        var page=query.ValidPage;var size=query.ValidPageSize;var args=OptionParameters(o,u,wide,query.Search,(page-1)*size,size);
        const string scope="i.organization_id=@o AND i.deleted_at IS NULL AND p.deleted_at IS NULL AND i.status=ANY(@itemStatuses) AND p.status=ANY(@planStatuses) AND (@wide OR i.responsible_user_id IS NULL OR i.responsible_user_id=@u OR p.owner_user_id=@u) AND (@search IS NULL OR i.title ILIKE '%'||@search||'%' OR p.title ILIKE '%'||@search||'%')";
        var sql=$"""SELECT count(*)::int FROM valorapesquisa.action_items i JOIN valorapesquisa.action_plans p ON p.id=i.action_plan_id AND p.organization_id=i.organization_id WHERE {scope};
            SELECT i.id Id,i.title Title,i.status Status,i.priority Priority,p.title Context,i.responsible_user_id ResponsibleUserId,u2.name ResponsibleName
            FROM valorapesquisa.action_items i JOIN valorapesquisa.action_plans p ON p.id=i.action_plan_id AND p.organization_id=i.organization_id
            LEFT JOIN valorapesquisa.users u2 ON u2.id=i.responsible_user_id AND u2.organization_id=i.organization_id AND u2.deleted_at IS NULL
            WHERE {scope} ORDER BY i.title,i.id LIMIT @size OFFSET @offset;""";
        using var x=db.Create();using var result=await x.QueryMultipleAsync(new CommandDefinition(sql,args,cancellationToken:c));var total=await result.ReadSingleAsync<int>();var rows=(await result.ReadAsync<ActionOptionDto>()).AsList();return new(rows,page,size,total);
    }
    public async Task<ActionItemDto?> Get(Guid o, Guid id, CancellationToken c) { using var x = db.Create(); return await x.QuerySingleOrDefaultAsync<ActionItemDto>(new CommandDefinition(Select + " WHERE organization_id=@o AND id=@id AND deleted_at IS NULL", new { o, id }, cancellationToken: c)); }
    public async Task<Guid> Create(Guid o, Guid u, CreateActionItemRequest r, CancellationToken c) { var id = Guid.NewGuid(); await using var z = await tx.BeginAsync(c); await z.Connection.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.action_items(id,organization_id,action_plan_id,diagnostic_id,result_id,title,description,origin_type,origin_id,related_dimension,related_index_code,priority,status,responsible_user_id,due_at,evidence_summary,expected_outcome,ai_recommendation_summary) VALUES(@id,@o,@ActionPlanId,@DiagnosticId,@ResultId,@Title,@Description,@OriginType,@OriginId,@RelatedDimension,@RelatedIndexCode,@Priority,'pending',@ResponsibleUserId,@DueAt,@EvidenceSummary,@ExpectedOutcome,@AiRecommendationSummary)", new { id, o, r.ActionPlanId, r.DiagnosticId, r.ResultId, r.Title, r.Description, r.OriginType, r.OriginId, r.RelatedDimension, r.RelatedIndexCode, r.Priority, r.ResponsibleUserId, r.DueAt, r.EvidenceSummary, r.ExpectedOutcome, r.AiRecommendationSummary }, z.Transaction, cancellationToken: c)); await Event(z, o, u, id, "action_created", r.Title, r.EvidenceSummary, c); await z.CommitAsync(); return id; }
    public async Task UpdateProgress(Guid o, Guid u, Guid id, int p, string? n, CancellationToken c) { await using var z = await tx.BeginAsync(c); await z.Connection.ExecuteAsync(new CommandDefinition("UPDATE valorapesquisa.action_items SET progress_percent=@p,status=CASE WHEN @p=0 THEN 'pending' ELSE 'in_progress' END,updated_at=now() WHERE id=@id AND organization_id=@o AND deleted_at IS NULL; INSERT INTO valorapesquisa.action_item_checkins(action_item_id,progress_percent,note,created_by_user_id) VALUES(@id,@p,@n,@u); INSERT INTO valorapesquisa.action_item_status_history(action_item_id,from_status,to_status,progress_percent,reason,changed_by_user_id) SELECT @id,status,CASE WHEN @p=0 THEN 'pending' ELSE 'in_progress' END,@p,@n,@u FROM valorapesquisa.action_items WHERE id=@id", new { o, u, id, p, n }, z.Transaction, cancellationToken: c)); await z.CommitAsync(); }
    public async Task Block(Guid o, Guid u, Guid id, string reason, CancellationToken c) { using var x = db.Create(); await x.ExecuteAsync(new CommandDefinition("WITH old AS(SELECT status FROM valorapesquisa.action_items WHERE id=@id AND organization_id=@o AND deleted_at IS NULL), upd AS(UPDATE valorapesquisa.action_items SET status='blocked',updated_at=now() WHERE id=@id AND organization_id=@o RETURNING id) INSERT INTO valorapesquisa.action_item_status_history(action_item_id,from_status,to_status,reason,changed_by_user_id) SELECT @id,old.status,'blocked',@reason,@u FROM old", new { o, u, id, reason }, cancellationToken: c)); }
    public async Task Complete(Guid o, Guid u, Guid id, string result, string evidence, CancellationToken c) { await using var z = await tx.BeginAsync(c); var title = await z.Connection.QuerySingleAsync<string>(new CommandDefinition("UPDATE valorapesquisa.action_items SET status='completed',progress_percent=100,completed_at=now(),completion_evidence=@evidence,metadata_json=metadata_json||jsonb_build_object('completionResult',@result),updated_at=now() WHERE id=@id AND organization_id=@o AND deleted_at IS NULL RETURNING title", new { o, id, result, evidence }, z.Transaction, cancellationToken: c)); await z.Connection.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.action_item_status_history(action_item_id,from_status,to_status,progress_percent,reason,changed_by_user_id) VALUES(@id,'in_progress','completed',100,@result,@u)", new { id, u, result }, z.Transaction, cancellationToken: c)); await Event(z, o, u, id, "action_completed", title, evidence, c); await z.CommitAsync(); }
    static Task Event(IUnitOfWork z, Guid o, Guid u, Guid id, string type, string title, string evidence, CancellationToken c) => z.Connection.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.journey_events(organization_id,event_type,title,description,source_type,source_id,impact_level,evidence_summary,occurred_at,created_by_user_id) VALUES(@o,@type,@title,'Registro automático da execução organizacional.','action',@id,'medium',@evidence,now(),@u)", new { o, u, id, type, title, evidence }, z.Transaction, cancellationToken: c));
    private static DynamicParameters OptionParameters(Guid o,Guid u,bool wide,string? search,int offset,int size) { var p=new DynamicParameters();p.Add("o",o,DbType.Guid);p.Add("u",u,DbType.Guid);p.Add("wide",wide,DbType.Boolean);p.Add("search",string.IsNullOrWhiteSpace(search)?null:search.Trim(),DbType.String);p.Add("itemStatuses",new[]{"pending","in_progress","blocked","overdue"});p.Add("planStatuses",new[]{"draft","proposed","approved","in_execution"});p.Add("offset",offset,DbType.Int32);p.Add("size",size,DbType.Int32);return p; }
}
