using Dapper;
using System.Data;
using Valora.Application.ActionCenter;
using Valora.Application.Contracts;
using Valora.Application.Workspace;
namespace Valora.Infrastructure.Repositories;

public sealed class ActionPlanRepository(IDbConnectionFactory db) : IActionPlanRepository {
    const string Projection = "SELECT p.id,p.title,p.summary,p.origin_type OriginType,p.status,p.priority,p.owner_user_id OwnerUserId,p.due_at DueAt,p.evidence_summary EvidenceSummary,p.expected_outcome ExpectedOutcome,coalesce(round(avg(i.progress_percent))::int,0) ProgressPercent,p.created_at CreatedAt,u.name OwnerName,count(i.id) FILTER(WHERE i.status NOT IN('completed','canceled'))::int ActiveItemCount FROM valorapesquisa.action_plans p LEFT JOIN valorapesquisa.action_items i ON i.action_plan_id=p.id AND i.organization_id=p.organization_id AND i.deleted_at IS NULL AND i.status<>'canceled' LEFT JOIN valorapesquisa.users u ON u.id=p.owner_user_id AND u.organization_id=p.organization_id AND u.deleted_at IS NULL";
    const string Scope = "p.organization_id=@o AND p.deleted_at IS NULL AND (@wide OR p.owner_user_id IS NULL OR p.owner_user_id=@u OR EXISTS(SELECT 1 FROM valorapesquisa.action_items ai WHERE ai.action_plan_id=p.id AND ai.organization_id=p.organization_id AND ai.deleted_at IS NULL AND ai.responsible_user_id=@u))";
    public async Task<IReadOnlyList<ActionPlanDto>> List(Guid o, Guid u, bool wide, CancellationToken c) { using var x=db.Create(); return (await x.QueryAsync<ActionPlanDto>(new CommandDefinition(Projection+$" WHERE {Scope} GROUP BY p.id,u.name ORDER BY p.created_at DESC",new{o,u,wide},cancellationToken:c))).AsList(); }
    public async Task<PageResult<ActionPlanDto>> List(Guid o,Guid u,bool wide,ActionPlanListQuery query,CancellationToken c) {
        var page=query.ValidPage;var size=query.ValidPageSize;var offset=checked((page-1)*size);
        var search=string.IsNullOrWhiteSpace(query.Search)?null:query.Search.Trim();
        var status=ActionStatuses.Plan.Contains(query.Status??"")?query.Status:null;
        var priority=ActionStatuses.Priorities.Contains(query.Priority??"")?query.Priority:null;
        var due=query.Due is "overdue" or "today" or "upcoming" or "none"?query.Due:null;
        var filtered=Scope+" AND (@search IS NULL OR p.title ILIKE '%'||@search||'%' OR p.summary ILIKE '%'||@search||'%') AND (@status IS NULL OR p.status=@status) AND (@owner IS NULL OR p.owner_user_id=@owner) AND (@priority IS NULL OR p.priority=@priority) AND (@due IS NULL OR @due='overdue' AND (p.due_at AT TIME ZONE (SELECT time_zone FROM valorapesquisa.organizations WHERE id=@o))::date < (now() AT TIME ZONE (SELECT time_zone FROM valorapesquisa.organizations WHERE id=@o))::date OR @due='today' AND (p.due_at AT TIME ZONE (SELECT time_zone FROM valorapesquisa.organizations WHERE id=@o))::date = (now() AT TIME ZONE (SELECT time_zone FROM valorapesquisa.organizations WHERE id=@o))::date OR @due='upcoming' AND (p.due_at AT TIME ZONE (SELECT time_zone FROM valorapesquisa.organizations WHERE id=@o))::date > (now() AT TIME ZONE (SELECT time_zone FROM valorapesquisa.organizations WHERE id=@o))::date OR @due='none' AND p.due_at IS NULL)";
        var order=query.Sort switch{"title"=>"p.title,p.id","due"=>"p.due_at NULLS LAST,p.id",_=>"p.created_at DESC,p.id DESC"};
        var args=new{o,u,wide,search,status,owner=query.OwnerUserId,priority,due,size,offset};
        using var x=db.Create();using var q=await x.QueryMultipleAsync(new CommandDefinition($"SELECT count(*)::int FROM valorapesquisa.action_plans p WHERE {filtered}; {Projection} WHERE {filtered} GROUP BY p.id,u.name ORDER BY {order} LIMIT @size OFFSET @offset",args,cancellationToken:c));
        var total=await q.ReadSingleAsync<int>();var rows=(await q.ReadAsync<ActionPlanDto>()).AsList();return new(rows,page,size,total);
    }
    public async Task<PageResult<ActionOptionDto>> Options(Guid o, Guid u, bool wide, OptionQuery query, CancellationToken c) {
        var page=query.ValidPage;var size=query.ValidPageSize;var offset=checked((page-1)*size);var args=OptionParameters(o,u,wide,query.Search,offset,size);
        const string scope="p.organization_id=@o AND p.deleted_at IS NULL AND p.status=ANY(@statuses) AND (@wide OR p.owner_user_id IS NULL OR p.owner_user_id=@u) AND (@search IS NULL OR p.title ILIKE '%'||@search||'%')";
        var sql=$"SELECT count(*)::int FROM valorapesquisa.action_plans p WHERE {scope}; SELECT p.id Id,p.title Title,p.status Status,p.priority Priority,p.summary Context,p.owner_user_id ResponsibleUserId,u2.name ResponsibleName FROM valorapesquisa.action_plans p LEFT JOIN valorapesquisa.users u2 ON u2.id=p.owner_user_id AND u2.organization_id=p.organization_id AND u2.deleted_at IS NULL WHERE {scope} ORDER BY p.title,p.id LIMIT @size OFFSET @offset;";
        using var x=db.Create();using var result=await x.QueryMultipleAsync(new CommandDefinition(sql,args,cancellationToken:c));var total=await result.ReadSingleAsync<int>();return new((await result.ReadAsync<ActionOptionDto>()).AsList(),page,size,total);
    }
    public async Task<ActionPlanDto?> Get(Guid o, Guid u, Guid id, bool wide, CancellationToken c) { using var x=db.Create();return await x.QuerySingleOrDefaultAsync<ActionPlanDto>(new CommandDefinition(Projection+$" WHERE {Scope} AND p.id=@id GROUP BY p.id,u.name",new{o,u,id,wide},cancellationToken:c)); }
    public async Task<ActionDashboardDto> Dashboard(Guid o, Guid u, bool wide, CancellationToken c) {
        var plans=(await List(o,u,wide,new ActionPlanListQuery(PageSize:6),c)).Items;using var x=db.Create();
        const string sql="""
        SELECT count(*) FILTER(WHERE i.priority='critical' AND i.status NOT IN('completed','canceled'))::int Critical,count(*) FILTER(WHERE i.due_at<now() AND i.status NOT IN('completed','canceled'))::int Overdue,count(*) FILTER(WHERE i.responsible_user_id IS NULL AND i.status NOT IN('completed','canceled'))::int Unassigned,count(*) FILTER(WHERE i.status='blocked')::int Blocked,(SELECT count(*)::int FROM valorapesquisa.action_plans ap WHERE ap.organization_id=@o AND ap.deleted_at IS NULL AND ap.status IN('approved','in_execution') AND (@wide OR ap.owner_user_id IS NULL OR ap.owner_user_id=@u OR EXISTS(SELECT 1 FROM valorapesquisa.action_items ai WHERE ai.action_plan_id=ap.id AND ai.organization_id=ap.organization_id AND ai.deleted_at IS NULL AND ai.responsible_user_id=@u))) ActivePlans
        FROM valorapesquisa.action_items i JOIN valorapesquisa.action_plans p ON p.id=i.action_plan_id AND p.organization_id=i.organization_id WHERE i.organization_id=@o AND i.deleted_at IS NULL AND p.deleted_at IS NULL AND (@wide OR i.responsible_user_id IS NULL OR i.responsible_user_id=@u OR p.owner_user_id=@u);
        SELECT i.id,i.action_plan_id ActionPlanId,i.title,i.description,i.origin_type OriginType,i.origin_id OriginId,i.related_dimension RelatedDimension,i.related_index_code RelatedIndexCode,i.priority,i.status,i.responsible_user_id ResponsibleUserId,i.due_at DueAt,i.completed_at CompletedAt,i.progress_percent ProgressPercent,i.evidence_summary EvidenceSummary,i.expected_outcome ExpectedOutcome,i.completion_evidence CompletionEvidence,i.ai_recommendation_summary AiRecommendationSummary,i.created_at CreatedAt,i.version Version,ru.name ResponsibleName,p.title PlanTitle,i.metadata_json->>'completionResult' CompletionResult
        FROM valorapesquisa.action_items i JOIN valorapesquisa.action_plans p ON p.id=i.action_plan_id AND p.organization_id=i.organization_id LEFT JOIN valorapesquisa.users ru ON ru.id=i.responsible_user_id AND ru.organization_id=i.organization_id AND ru.deleted_at IS NULL WHERE i.organization_id=@o AND i.deleted_at IS NULL AND p.deleted_at IS NULL AND i.status NOT IN('completed','canceled') AND (@wide OR i.responsible_user_id IS NULL OR i.responsible_user_id=@u OR p.owner_user_id=@u) ORDER BY i.due_at NULLS LAST,i.created_at DESC,i.id LIMIT 12;
        """;
        using var q=await x.QueryMultipleAsync(new CommandDefinition(sql,new{o,u,wide},cancellationToken:c));var totals=await q.ReadSingleAsync<DashboardTotals>();var items=(await q.ReadAsync<ActionItemDto>()).AsList();return new(totals.Critical,totals.Overdue,totals.Unassigned,totals.ActivePlans,totals.Blocked,items,plans);
    }
    private sealed record DashboardTotals(int Critical,int Overdue,int Unassigned,int Blocked,int ActivePlans);
    public async Task<Guid> Create(Guid o,Guid u,CreateActionPlanRequest r,CancellationToken c){var id=Guid.NewGuid();using var x=db.Create();var affected=await x.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.action_plans(id,organization_id,diagnostic_id,result_id,governance_cycle_id,title,summary,origin_type,origin_id,status,priority,owner_user_id,created_by_user_id,starts_at,due_at,evidence_summary,expected_outcome) SELECT @id,@o,@DiagnosticId,@ResultId,@GovernanceCycleId,@Title,@Summary,@OriginType,@OriginId,'draft',@Priority,@OwnerUserId,@u,@StartsAt,@DueAt,@EvidenceSummary,@ExpectedOutcome WHERE @OwnerUserId IS NULL OR EXISTS(SELECT 1 FROM valorapesquisa.users WHERE id=@OwnerUserId AND organization_id=@o AND status='active' AND deleted_at IS NULL)",new{id,o,u,r.DiagnosticId,r.ResultId,r.GovernanceCycleId,Title=r.Title.Trim(),r.Summary,r.OriginType,r.OriginId,r.Priority,r.OwnerUserId,r.StartsAt,r.DueAt,EvidenceSummary=r.EvidenceSummary.Trim(),ExpectedOutcome=r.ExpectedOutcome.Trim()},cancellationToken:c));if(affected!=1)throw new ArgumentException("O responsável deve ser um usuário ativo da organização.");return id;}
    private static DynamicParameters OptionParameters(Guid o,Guid u,bool wide,string? search,int offset,int size){var p=new DynamicParameters();p.Add("o",o,DbType.Guid);p.Add("u",u,DbType.Guid);p.Add("wide",wide);p.Add("search",string.IsNullOrWhiteSpace(search)?null:search.Trim());p.Add("statuses",new[]{"draft","proposed","approved","in_execution"});p.Add("offset",offset);p.Add("size",size);return p;}
}
