using Dapper;
using Valora.Application.Advisor;
using Valora.Application.Contracts;

namespace Valora.Infrastructure.Repositories;

public sealed class AdvisorRepository(IDbConnectionFactory db) : IAdvisorConversationRepository, IAdvisorMessageRepository,
    IAdvisorContextBundleRepository, IAdvisorPromptTemplateRepository, IAdvisorGuardrailRepository,
    IAdvisorFeedbackRepository, IAdvisorUsageRepository
{
    public async Task<IReadOnlyList<AdvisorConversationDto>> List(Guid organizationId,Guid userId,CancellationToken ct)
    { using var c=db.Create();const string q="SELECT id,objective,status,created_at,updated_at FROM valorapesquisa.advisor_conversations WHERE organization_id=@organizationId AND user_id=@userId ORDER BY updated_at DESC LIMIT 100";return (await c.QueryAsync<AdvisorConversationDto>(new CommandDefinition(q,new{organizationId,userId},cancellationToken:ct))).ToList(); }

    public async Task<AdvisorConversationDetailDto?> Get(Guid organizationId,Guid userId,Guid id,CancellationToken ct)
    {
        using var c=db.Create();const string q="""
        SELECT id,objective,status,created_at,updated_at FROM valorapesquisa.advisor_conversations WHERE organization_id=@organizationId AND user_id=@userId AND id=@id;
        SELECT id,conversation_id,role,content,confidence,limitations,created_at FROM valorapesquisa.advisor_messages WHERE organization_id=@organizationId AND conversation_id=@id ORDER BY created_at;
        SELECT c.id,c.message_id,c.source_type,c.source_id,c.title,c.excerpt,c.strength FROM valorapesquisa.advisor_evidence_citations c JOIN valorapesquisa.advisor_messages m ON m.id=c.message_id WHERE c.organization_id=@organizationId AND m.conversation_id=@id;
        """;
        using var grid=await c.QueryMultipleAsync(new CommandDefinition(q,new{organizationId,userId,id},cancellationToken:ct));var conversation=await grid.ReadSingleOrDefaultAsync<AdvisorConversationDto>();if(conversation is null)return null;var raw=(await grid.ReadAsync<MessageRow>()).ToList();var evidence=(await grid.ReadAsync<EvidenceRow>()).ToList();return new(conversation,raw.Select(m=>new AdvisorMessageDto(m.Id,m.ConversationId,m.Role,m.Content,m.Confidence,m.Limitations??[],m.CreatedAt,evidence.Where(e=>e.MessageId==m.Id).Select(e=>new AdvisorEvidenceDto(e.Id,e.SourceType,e.SourceId,e.Title,e.Excerpt,e.Strength)).ToArray())).ToArray());
    }

    public async Task<Guid> Create(Guid organizationId,Guid userId,CreateAdvisorConversationRequest request,CancellationToken ct)
    { using var c=db.Create();var id=Guid.NewGuid();const string q="INSERT INTO valorapesquisa.advisor_conversations(id,organization_id,user_id,objective,status) VALUES(@id,@organizationId,@userId,@Objective,'active')";await c.ExecuteAsync(new CommandDefinition(q,new{id,organizationId,userId,request.Objective},cancellationToken:ct));return id; }

    public async Task<Guid> AddUserMessage(Guid organizationId,Guid userId,Guid conversationId,string content,CancellationToken ct)
    { using var c=db.Create();var id=Guid.NewGuid();const string q="""INSERT INTO valorapesquisa.advisor_messages(id,organization_id,conversation_id,user_id,role,content,confidence,limitations) SELECT @id,@organizationId,@conversationId,@userId,'user',@content,'not_applicable',ARRAY[]::text[] WHERE EXISTS(SELECT 1 FROM valorapesquisa.advisor_conversations WHERE id=@conversationId AND organization_id=@organizationId AND user_id=@userId AND status='active'); UPDATE valorapesquisa.advisor_conversations SET updated_at=now() WHERE id=@conversationId AND organization_id=@organizationId AND user_id=@userId;""";var rows=await c.ExecuteAsync(new CommandDefinition(q,new{id,organizationId,userId,conversationId,content},cancellationToken:ct));if(rows==0)throw new KeyNotFoundException("Conversa não encontrada nesta organização.");return id; }

    public async Task<Guid> AddResponse(Guid organizationId,Guid conversationId,string content,string confidence,string[] limitations,IReadOnlyList<AdvisorContextOptionDto> evidence,CancellationToken ct)
    { using var c=db.Create();var id=Guid.NewGuid();const string q="""INSERT INTO valorapesquisa.advisor_messages(id,organization_id,conversation_id,role,content,confidence,limitations) SELECT @id,@organizationId,@conversationId,'advisor',@content,@confidence,@limitations WHERE EXISTS(SELECT 1 FROM valorapesquisa.advisor_conversations WHERE id=@conversationId AND organization_id=@organizationId); INSERT INTO valorapesquisa.advisor_evidence_citations(id,organization_id,message_id,source_type,source_id,title,excerpt,strength) SELECT gen_random_uuid(),@organizationId,@id,x.source_type,x.source_id,x.title,x.summary,'contextual' FROM unnest(@types::text[],@ids::uuid[],@titles::text[],@summaries::text[]) x(source_type,source_id,title,summary) WHERE EXISTS(SELECT 1 FROM valorapesquisa.advisor_messages WHERE id=@id AND organization_id=@organizationId);""";await c.ExecuteAsync(new CommandDefinition(q,new{id,organizationId,conversationId,content,confidence,limitations,types=evidence.Select(x=>x.SourceType).ToArray(),ids=evidence.Select(x=>x.SourceId).ToArray(),titles=evidence.Select(x=>x.Title).ToArray(),summaries=evidence.Select(x=>x.Summary).ToArray()},cancellationToken:ct));return id; }

    private const string ContextSql="""
        SELECT 'indicator' source_type,id source_id,name title,concat('Indicador ',name,'; unidade ',unit,'; status ',status) summary FROM valorapesquisa.indicators WHERE organization_id=@organizationId AND status='active'
        UNION ALL SELECT 'report',id,name,concat('Relatório com status ',status) FROM valorapesquisa.reports WHERE organization_id=@organizationId
        UNION ALL SELECT 'action',id,title,concat('Plano de ação com status ',status) FROM valorapesquisa.action_plans WHERE organization_id=@organizationId
        UNION ALL SELECT 'decision',id,title,concat('Decisão com status ',status,': ',context) FROM valorapesquisa.governance_decisions WHERE organization_id=@organizationId
        """;
    public async Task<IReadOnlyList<AdvisorContextOptionDto>> Options(Guid organizationId,CancellationToken ct){using var c=db.Create();return(await c.QueryAsync<AdvisorContextOptionDto>(new CommandDefinition(ContextSql+" ORDER BY title LIMIT 200",new{organizationId},cancellationToken:ct))).ToList();}
    public async Task<IReadOnlyList<AdvisorContextOptionDto>> Resolve(Guid organizationId,IReadOnlyList<AdvisorContextSelection> selections,CancellationToken ct){if(selections.Count==0)return[];using var c=db.Create();var types=selections.Select(x=>x.SourceType).ToArray();var ids=selections.Select(x=>x.SourceId).ToArray();const string filter=" SELECT s.* FROM sources s JOIN unnest(@types::text[],@ids::uuid[]) requested(source_type,source_id) USING(source_type,source_id)";return(await c.QueryAsync<AdvisorContextOptionDto>(new CommandDefinition("WITH sources AS ("+ContextSql+")"+filter,new{organizationId,types,ids},cancellationToken:ct))).ToList();}

    public async Task<IReadOnlyList<AdvisorTemplateDto>> List(Guid organizationId,CancellationToken ct){using var c=db.Create();const string q="""SELECT t.id,t.code,t.name,t.area,t.status,v.version,v.human_reviewed,v.content FROM valorapesquisa.advisor_prompt_templates t JOIN LATERAL(SELECT version,human_reviewed,content FROM valorapesquisa.advisor_prompt_template_versions WHERE template_id=t.id ORDER BY version DESC LIMIT 1)v ON true WHERE t.organization_id IS NULL OR t.organization_id=@organizationId ORDER BY t.name""";return(await c.QueryAsync<AdvisorTemplateDto>(new CommandDefinition(q,new{organizationId},cancellationToken:ct))).ToList();}
    public async Task<Guid> Create(Guid organizationId,Guid userId,CreateAdvisorTemplateRequest request,CancellationToken ct){using var c=db.Create();var id=Guid.NewGuid();const string q="""INSERT INTO valorapesquisa.advisor_prompt_templates(id,organization_id,code,name,area,status,created_by_user_id) VALUES(@id,@organizationId,@Code,@Name,@Area,'draft',@userId);INSERT INTO valorapesquisa.advisor_prompt_template_versions(id,organization_id,template_id,version,content,human_reviewed,created_by_user_id) VALUES(gen_random_uuid(),@organizationId,@id,1,@Content,false,@userId);""";await c.ExecuteAsync(new CommandDefinition(q,new{id,organizationId,userId,request.Code,request.Name,request.Area,request.Content},cancellationToken:ct));return id;}
    public async Task Record(Guid organizationId,Guid userId,Guid? conversationId,string rule,string reason,CancellationToken ct){using var c=db.Create();const string q="INSERT INTO valorapesquisa.advisor_guardrail_events(organization_id,user_id,conversation_id,rule_code,reason,context) VALUES(@organizationId,@userId,@conversationId,@rule,@reason,'{}')";await c.ExecuteAsync(new CommandDefinition(q,new{organizationId,userId,conversationId,rule,reason},cancellationToken:ct));}
    public async Task Create(Guid organizationId,Guid userId,Guid messageId,AdvisorFeedbackRequest request,CancellationToken ct){using var c=db.Create();const string q="INSERT INTO valorapesquisa.advisor_feedback(organization_id,user_id,message_id,useful,reason,improvement) SELECT @organizationId,@userId,@messageId,@Useful,@Reason,@Improvement WHERE EXISTS(SELECT 1 FROM valorapesquisa.advisor_messages WHERE id=@messageId AND organization_id=@organizationId) ON CONFLICT(organization_id,user_id,message_id) DO UPDATE SET useful=excluded.useful,reason=excluded.reason,improvement=excluded.improvement,updated_at=now()";await c.ExecuteAsync(new CommandDefinition(q,new{organizationId,userId,messageId,request.Useful,request.Reason,request.Improvement},cancellationToken:ct));}
    public async Task Record(Guid organizationId,Guid userId,string eventName,Guid? entityId,CancellationToken ct){using var c=db.Create();const string q="INSERT INTO valorapesquisa.advisor_usage_events(organization_id,user_id,event_name,entity_id) VALUES(@organizationId,@userId,@eventName,@entityId)";await c.ExecuteAsync(new CommandDefinition(q,new{organizationId,userId,eventName,entityId},cancellationToken:ct));}
    private sealed record MessageRow(Guid Id,Guid ConversationId,string Role,string Content,string Confidence,string[]? Limitations,DateTimeOffset CreatedAt);
    private sealed record EvidenceRow(Guid Id,Guid MessageId,string SourceType,Guid SourceId,string Title,string Excerpt,string Strength);
}
