using System.Data;
using Dapper;
using Microsoft.Extensions.Logging;
using Valora.Application.Contracts;
using Valora.Application.Security;

namespace Valora.Infrastructure.Repositories;

public sealed class CommunicationRepository(IDbConnectionFactory f, ILogger<CommunicationRepository> logger):ICommunicationRepository
{
 public async Task AddEmailJobAsync(Guid responseId,string toEmail,string status){await AddEmailJobAsync(null,responseId,toEmail,"Seu resultado Valora Pulse","result-ready",status,$"{{\"responseId\":\"{responseId}\"}}");}
 public async Task<Guid> AddEmailJobAsync(Guid? organizationId,Guid? responseId,string toEmail,string subject,string templateKey,string status,string payloadJson){try{using var c=f.Create(); return await c.ExecuteScalarAsync<Guid>("INSERT INTO valorapesquisa.email_jobs(organization_id,response_id,recipient_email,to_email,subject,body,template_key,status,payload_json) VALUES (@organizationId,@responseId,@toEmail,@toEmail,@subject,COALESCE(@payloadJson,''),@templateKey,@status,CAST(@payloadJson AS jsonb)) RETURNING id",new{organizationId,responseId,toEmail,subject,templateKey,status,payloadJson});}catch(Exception ex){logger.LogError(ex,"Erro ao criar job de e-mail. OrganizationId={OrganizationId} ResponseId={ResponseId} Recipient={Recipient} Template={TemplateKey}",organizationId,responseId,LogSanitizer.MaskEmail(toEmail),templateKey);throw;}}
 public async Task<IReadOnlyList<dynamic>> ListAsync(Guid? organizationId=null){try{using var c=f.Create(); return (await c.QueryAsync("SELECT * FROM valorapesquisa.communications WHERE (@organizationId IS NULL OR organization_id=@organizationId) ORDER BY created_at DESC LIMIT 100",new{organizationId})).ToList();}catch(Exception ex){logger.LogError(ex,"Erro ao listar comunicações. OrganizationId={OrganizationId}",organizationId);throw;}}
 public async Task<IReadOnlyList<dynamic>> ListEmailJobsAsync(string? status=null){try{using var c=f.Create(); return (await c.QueryAsync("SELECT id,organization_id,response_id,COALESCE(to_email,recipient_email) AS to_email,subject,status,attempts,last_error,created_at,updated_at,sent_at FROM valorapesquisa.email_jobs WHERE (@status IS NULL OR status=@status) ORDER BY created_at DESC LIMIT 100",new{status})).ToList();}catch(Exception ex){logger.LogError(ex,"Erro ao listar jobs de e-mail. Status={Status}",status);throw;}}
 public async Task<IReadOnlyList<dynamic>> GetPendingEmailJobsAsync(int batchSize){try{using var c=f.Create(); return (await c.QueryAsync("SELECT id,COALESCE(to_email,recipient_email) AS to_email,subject,COALESCE(body,payload_json::text,'') AS body,status,attempts FROM valorapesquisa.email_jobs WHERE status='pending' AND is_deleted=false ORDER BY created_at LIMIT @batchSize",new{batchSize=Math.Clamp(batchSize,1,100)})).ToList();}catch(Exception ex){logger.LogError(ex,"Erro ao buscar jobs pendentes.");throw;}}
 public async Task MarkProcessingAsync(Guid id)=> await ExecStatus(id,"processing",null);
 public async Task MarkSentAsync(Guid id){using var c=f.Create(); await c.ExecuteAsync("UPDATE valorapesquisa.email_jobs SET status='sent',sent_at=now(),updated_at=now() WHERE id=@id",new{id});}
 public async Task MarkFailedAsync(Guid id,string lastError,string status="failed"){using var c=f.Create(); await c.ExecuteAsync("UPDATE valorapesquisa.email_jobs SET status=@status,last_error=@lastError,updated_at=now() WHERE id=@id",new{id,status,lastError});}
 public async Task IncrementAttemptsAsync(Guid id){using var c=f.Create(); await c.ExecuteAsync("UPDATE valorapesquisa.email_jobs SET attempts=attempts+1,updated_at=now() WHERE id=@id",new{id});}
 async Task ExecStatus(Guid id,string status,string? error){using var c=f.Create(); await c.ExecuteAsync("UPDATE valorapesquisa.email_jobs SET status=@status,last_error=@error,processing_at=CASE WHEN @status='processing' THEN now() ELSE processing_at END,updated_at=now() WHERE id=@id",new{id,status,error});}
 public async Task CreateEmailJobAsync(Guid organizationId,Guid responseId,string recipientEmail,string status,IDbTransaction tx){try{await tx.Connection!.ExecuteAsync("INSERT INTO valorapesquisa.email_jobs(organization_id,response_id,recipient_email,to_email,subject,body,template_key,status,payload_json) VALUES (@organizationId,@responseId,@recipientEmail,@recipientEmail,'Valora Insight™ - Seu diagnóstico está pronto','Resultado Valora Pulse disponível.','result-ready',@status,jsonb_build_object('responseId',@responseId))",new{organizationId,responseId,recipientEmail,status},tx);}catch(Exception ex){logger.LogError(ex,"Erro ao criar job transacional de e-mail. OrganizationId={OrganizationId} ResponseId={ResponseId} Recipient={Recipient} Status={Status}",organizationId,responseId,LogSanitizer.MaskEmail(recipientEmail),status);throw;}}
 public async Task CreateCommunicationAsync(Guid organizationId,Guid surveyId,Guid responseId,string channel,string eventType,string status,string? recipientMasked,IDbTransaction tx){try{await tx.Connection!.ExecuteAsync("INSERT INTO valorapesquisa.communications(organization_id,survey_id,response_id,channel,event_type,status,recipient_masked) VALUES (@organizationId,@surveyId,@responseId,@channel,@eventType,@status,@recipientMasked)",new{organizationId,surveyId,responseId,channel,eventType,status,recipientMasked},tx);}catch(Exception ex){logger.LogError(ex,"Erro ao criar comunicação. OrganizationId={OrganizationId} SurveyId={SurveyId} ResponseId={ResponseId} Channel={Channel} EventType={EventType}",organizationId,surveyId,responseId,channel,eventType);throw;}}
}
