using Dapper;
using Valora.Application.Contracts;
using Valora.Application.DecisionCenter;

namespace Valora.Infrastructure.Repositories;

public sealed class DecisionCenterRepository(IDbConnectionFactory connections, IDbTransactionFactory transactions) : IDecisionCenterRepository
{
    public async Task<DecisionCenterOverviewDto> GetOverviewAsync(Guid organizationId, CancellationToken ct)
    {
        var alerts = await ListAlertsAsync(organizationId, null, null, ct); var decisions = await ListDecisionsAsync(organizationId, ct);
        var metrics = await ListMetricsAsync(organizationId, ct); var cycles = await ListCyclesAsync(organizationId, ct);
        using var c = connections.Create();
        var overdue = await c.ExecuteScalarAsync<int>(new CommandDefinition("SELECT count(*)::int FROM valorapesquisa.valora_actions WHERE organization_id=@organizationId AND deleted_at IS NULL AND status NOT IN ('completed','cancelled') AND due_at<now()", new { organizationId }, cancellationToken: ct));
        return new(alerts.Count(x => x.Severity == "critical" && x.Status != "resolved"), decisions.Count(x => x.Status is "draft" or "proposed" or "approved"), metrics.Count(x => x.Trend == "regression"), overdue, alerts.Take(6).ToList(), decisions.Take(6).ToList(), metrics.Take(8).ToList(), cycles.Where(x => x.Status == "active").Take(4).ToList());
    }
    public async Task<IReadOnlyList<IntelligentAlertDto>> ListAlertsAsync(Guid organizationId, string? severity, string? status, CancellationToken ct)
    { const string sql="""SELECT id,source_type SourceType,alert_type AlertType,severity,title,message,evidence_summary EvidenceSummary,status,assigned_to_user_id AssignedToUserId,acknowledged_at AcknowledgedAt,resolved_at ResolvedAt,created_at CreatedAt FROM valorapesquisa.intelligent_alerts WHERE organization_id=@organizationId AND deleted_at IS NULL AND (@severity IS NULL OR severity=@severity) AND (@status IS NULL OR status=@status) ORDER BY CASE severity WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 WHEN 'low' THEN 4 ELSE 5 END,created_at DESC"""; using var c=connections.Create(); return (await c.QueryAsync<IntelligentAlertDto>(new CommandDefinition(sql,new{organizationId,severity,status},cancellationToken:ct))).ToList(); }
    public async Task<IReadOnlyList<OrganizationalDecisionDto>> ListDecisionsAsync(Guid organizationId,CancellationToken ct)
    { using var c=connections.Create(); return (await c.QueryAsync<OrganizationalDecisionDto>(new CommandDefinition(DecisionSelect+" WHERE organization_id=@organizationId AND deleted_at IS NULL ORDER BY created_at DESC",new{organizationId},cancellationToken:ct))).ToList(); }
    public async Task<OrganizationalDecisionDto?> GetDecisionAsync(Guid organizationId,Guid id,CancellationToken ct)
    { using var c=connections.Create(); return await c.QuerySingleOrDefaultAsync<OrganizationalDecisionDto>(new CommandDefinition(DecisionSelect+" WHERE organization_id=@organizationId AND id=@id AND deleted_at IS NULL",new{organizationId,id},cancellationToken:ct)); }
    private const string DecisionSelect="SELECT id,diagnostic_id DiagnosticId,result_id ResultId,title,summary,decision_type DecisionType,priority,status,impact_level ImpactLevel,evidence_summary EvidenceSummary,expected_outcome ExpectedOutcome,responsible_user_id ResponsibleUserId,decided_by_user_id DecidedByUserId,decided_at DecidedAt,due_at DueAt,completed_at CompletedAt,metadata_json::text MetadataJson,created_at CreatedAt,updated_at UpdatedAt FROM valorapesquisa.organizational_decisions";
    public async Task<IReadOnlyList<MetricSnapshotDto>> ListMetricsAsync(Guid organizationId,CancellationToken ct)
    { const string sql="""SELECT DISTINCT ON(metric_code) id,metric_code MetricCode,metric_name MetricName,metric_group MetricGroup,score,previous_score PreviousScore,delta,level,trend,evidence_summary EvidenceSummary,coalesce(metadata_json->>'interpretation','Evidência registrada sem interpretação adicional.') Interpretation,coalesce(metadata_json->>'recommendation','Acompanhar no próximo ciclo comparável.') Recommendation,coalesce(metadata_json->>'confidenceLimit','A leitura depende da evidência disponível.') ConfidenceLimit,calculated_at CalculatedAt FROM valorapesquisa.metric_snapshots WHERE organization_id=@organizationId AND deleted_at IS NULL ORDER BY metric_code,calculated_at DESC"""; using var c=connections.Create(); return (await c.QueryAsync<MetricSnapshotDto>(new CommandDefinition(sql,new{organizationId},cancellationToken:ct))).ToList(); }
    public async Task<IReadOnlyList<GovernanceCycleDto>> ListCyclesAsync(Guid organizationId,CancellationToken ct)
    { const string sql="SELECT id,name,period_label PeriodLabel,status,learning_summary LearningSummary,opened_at OpenedAt,closed_at ClosedAt FROM valorapesquisa.organizational_governance_cycles WHERE organization_id=@organizationId AND deleted_at IS NULL ORDER BY opened_at DESC"; using var c=connections.Create(); return (await c.QueryAsync<GovernanceCycleDto>(new CommandDefinition(sql,new{organizationId},cancellationToken:ct))).ToList(); }
    public async Task<IReadOnlyList<GovernanceMeetingDto>> ListMeetingsAsync(Guid organizationId,CancellationToken ct)
    { const string sql="SELECT id,cycle_id CycleId,title,agenda,status,scheduled_at ScheduledAt,minutes_summary MinutesSummary,next_steps NextSteps FROM valorapesquisa.governance_meetings WHERE organization_id=@organizationId AND deleted_at IS NULL ORDER BY scheduled_at DESC"; using var c=connections.Create(); return (await c.QueryAsync<GovernanceMeetingDto>(new CommandDefinition(sql,new{organizationId},cancellationToken:ct))).ToList(); }
    public Task AcknowledgeAlertAsync(Guid organizationId,Guid id,Guid userId,CancellationToken ct)=>ChangeAlert(organizationId,id,userId,"acknowledged",ct);
    public Task ResolveAlertAsync(Guid organizationId,Guid id,Guid userId,CancellationToken ct)=>ChangeAlert(organizationId,id,userId,"resolved",ct);
    private async Task ChangeAlert(Guid organizationId,Guid id,Guid userId,string status,CancellationToken ct){ await using var u=await transactions.BeginAsync(ct); await u.Connection.ExecuteAsync(new CommandDefinition("UPDATE valorapesquisa.intelligent_alerts SET status=@status,assigned_to_user_id=coalesce(assigned_to_user_id,@userId),acknowledged_at=coalesce(acknowledged_at,now()),resolved_at=CASE WHEN @status='resolved' THEN now() ELSE resolved_at END,updated_at=now() WHERE id=@id AND organization_id=@organizationId AND deleted_at IS NULL",new{organizationId,id,userId,status},u.Transaction,cancellationToken:ct)); await u.Connection.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.intelligent_alert_events(alert_id,event_type,performed_by_user_id,evidence_summary) VALUES(@id,@status,@userId,'Alteração de estado registrada por decisão humana.')",new{id,userId,status},u.Transaction,cancellationToken:ct)); await u.CommitAsync(); }
    public async Task<Guid> CreateDecisionAsync(Guid organizationId,Guid userId,CreateDecisionRequest r,CancellationToken ct){var id=Guid.NewGuid(); await using var u=await transactions.BeginAsync(ct); await u.Connection.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.organizational_decisions(id,organization_id,title,summary,decision_type,priority,status,impact_level,evidence_summary,expected_outcome,responsible_user_id,due_at,metadata_json,created_at) VALUES(@id,@organizationId,@Title,@Summary,@DecisionType,@Priority,'draft',@ImpactLevel,@EvidenceSummary,@ExpectedOutcome,@ResponsibleUserId,@DueAt,jsonb_build_object('sourceAlertId',@SourceAlertId,'governanceCycleId',@GovernanceCycleId),now())",new{id,organizationId,r.Title,r.Summary,r.DecisionType,r.Priority,r.ImpactLevel,r.EvidenceSummary,r.ExpectedOutcome,r.ResponsibleUserId,r.DueAt,r.SourceAlertId,r.GovernanceCycleId},u.Transaction,cancellationToken:ct)); if(r.SourceAlertId.HasValue) await u.Connection.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.organizational_decision_evidence_links(decision_id,evidence_type,evidence_id,evidence_summary,created_by_user_id) VALUES(@id,'alert',@SourceAlertId,@EvidenceSummary,@userId)",new{id,r.SourceAlertId,r.EvidenceSummary,userId},u.Transaction,cancellationToken:ct)); await u.Connection.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.organizational_journey_events(organization_id,title,description,event_type,occurred_at,created_by) VALUES(@organizationId,'Decisão registrada',@Title,'decision_created',now(),@userId)",new{organizationId,r.Title,userId},u.Transaction,cancellationToken:ct)); await u.CommitAsync(); return id; }
    public async Task<Guid> CreateCycleAsync(Guid organizationId,Guid userId,CreateGovernanceCycleRequest r,CancellationToken ct){var id=Guid.NewGuid();using var c=connections.Create();await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.organizational_governance_cycles(id,organization_id,name,period_label,primary_diagnostic_id,status,opened_at,created_by_user_id) VALUES(@id,@organizationId,@Name,@PeriodLabel,@PrimaryDiagnosticId,'active',@OpenedAt,@userId)",new{id,organizationId,r.Name,r.PeriodLabel,r.PrimaryDiagnosticId,r.OpenedAt,userId},cancellationToken:ct));return id;}
    public async Task<Guid> RegisterMeetingAsync(Guid organizationId,Guid userId,RegisterGovernanceMeetingRequest r,CancellationToken ct){var id=Guid.NewGuid();using var c=connections.Create();await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.governance_meetings(id,organization_id,cycle_id,title,agenda,status,scheduled_at,participants_summary,evidence_summary,next_steps,created_by_user_id) VALUES(@id,@organizationId,@CycleId,@Title,@Agenda,'scheduled',@ScheduledAt,@ParticipantsSummary,@EvidenceSummary,@NextSteps,@userId)",new{id,organizationId,r.CycleId,r.Title,r.Agenda,r.ScheduledAt,r.ParticipantsSummary,r.EvidenceSummary,r.NextSteps,userId},cancellationToken:ct));return id;}
}
