using System.Text.Json;
using Dapper;
using Valora.Application.Contracts;
using Valora.Application.DiagnosticWorkspace;

namespace Valora.Infrastructure.Repositories;

public sealed class DiagnosticWorkspaceRepository(IDbConnectionFactory connections, IDbTransactionFactory transactions) : IDiagnosticWorkspaceRepository
{
    private static readonly IReadOnlyDictionary<string,string> Tables = new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase)
    {
        ["responses"]="responses",["metrics"]="metric_values",["indices"]="index_values",["inferences"]="inference_results",
        ["insights"]="insights",["heatmap"]="heatmap_snapshots",["radar"]="radar_snapshots",["evolution"]="evolution_cycles",
        ["journey"]="journey_events",["benchmark"]="benchmark_runs",["report"]="executive_reports",["governance"]="platform_governance_events"
    };
    public async Task<DiagnosticCycleDto?> GetCycleAsync(Guid organizationId, Guid id, CancellationToken ct)
    {
        const string sql="""
        SELECT coalesce(dc.id,s.id) Id,s.organization_id OrganizationId,s.id SurveyId,s.form_id FormId,s.title,
          s.description,coalesce(dc.cycle_number,1) CycleNumber,coalesce(dc.methodology_version,'1') MethodologyVersion,
          coalesce(dc.status,s.status) Status,coalesce(dc.opened_at,s.starts_at) OpenedAt,dc.published_at PublishedAt,
          coalesce(dc.closed_at,s.expires_at) ClosedAt,dc.processed_at ProcessedAt,dc.report_generated_at ReportGeneratedAt,
          (SELECT count(*)::int FROM valorapesquisa.responses r WHERE r.organization_id=s.organization_id AND r.survey_id=s.id AND coalesce(r.is_deleted,false)=false) ResponseCount,
          (SELECT count(*)::int FROM valorapesquisa.evidence_items e WHERE e.organization_id=s.organization_id AND e.survey_id=s.id AND e.deleted_at IS NULL) EvidenceCount,
          dc.confidence_level ConfidenceLevel,coalesce(dc.processing_status,'pending') ProcessingStatus,s.public_url PublicUrl,
          coalesce(dc.created_at,s.created_at) CreatedAt,coalesce(dc.updated_at,s.updated_at,s.created_at) UpdatedAt
        FROM valorapesquisa.surveys s LEFT JOIN valorapesquisa.diagnostic_cycles dc ON dc.survey_id=s.id AND dc.organization_id=s.organization_id AND dc.deleted_at IS NULL
        WHERE s.organization_id=@organizationId AND (s.id=@id OR dc.id=@id) AND coalesce(s.is_deleted,false)=false LIMIT 1
        """;
        using var c=connections.Create(); return await c.QuerySingleOrDefaultAsync<DiagnosticCycleDto>(new CommandDefinition(sql,new{organizationId,id},cancellationToken:ct));
    }
    public async Task<IReadOnlyList<DiagnosticWorkspaceEvidenceDto>> EvidenceAsync(Guid organizationId, Guid surveyId, CancellationToken ct)
    {
        const string sql="""SELECT id,response_id ResponseId,question_id QuestionId,concept_code ConceptCode,metric_code MetricCode,index_code IndexCode,evidence_type EvidenceType,normalized_value NormalizedValue,weight,confidence_weight ConfidenceWeight,coalesce(metadata_json->>'mappingStatus','pending') MappingStatus,CASE WHEN text_excerpt IS NULL THEN NULL ELSE regexp_replace(text_excerpt,'.(?=.{4})','•','g') END MaskedAnswer,created_at CreatedAt FROM valorapesquisa.evidence_items WHERE organization_id=@organizationId AND survey_id=@surveyId AND deleted_at IS NULL ORDER BY created_at DESC LIMIT 500""";
        using var c=connections.Create(); return (await c.QueryAsync<DiagnosticWorkspaceEvidenceDto>(new CommandDefinition(sql,new{organizationId,surveyId},cancellationToken:ct))).ToList();
    }
    public async Task<IReadOnlyList<DiagnosticWorkspaceItemDto>> ModuleAsync(Guid organizationId, Guid cycleId, Guid surveyId, string module, CancellationToken ct)
    {
        string sql;
        if (module.Equals("actions",StringComparison.OrdinalIgnoreCase)) sql="SELECT id,code,status,to_jsonb(x)::text DataJson,created_at CreatedAt,updated_at UpdatedAt FROM valorapesquisa.valora_actions x WHERE organization_id=@organizationId AND survey_id=@surveyId AND deleted_at IS NULL ORDER BY created_at DESC LIMIT 200";
        else if (module.Equals("alerts",StringComparison.OrdinalIgnoreCase)) sql="SELECT id,indicator_code code,status,to_jsonb(x)::text DataJson,created_at CreatedAt,updated_at UpdatedAt FROM valorapesquisa.intelligent_alerts x WHERE organization_id=@organizationId AND survey_id=@surveyId AND deleted_at IS NULL ORDER BY created_at DESC LIMIT 200";
        else if (module.Equals("participation",StringComparison.OrdinalIgnoreCase)) sql="SELECT id,'participation'::text code,status,to_jsonb(x)::text DataJson,created_at CreatedAt,updated_at UpdatedAt FROM valorapesquisa.diagnostic_participation_snapshots x WHERE organization_id=@organizationId AND (cycle_id=@cycleId OR survey_id=@surveyId) AND deleted_at IS NULL ORDER BY created_at DESC LIMIT 1";
        else if (module.Equals("responses",StringComparison.OrdinalIgnoreCase)) sql="SELECT id,NULL::text code,status,(to_jsonb(x)-'participant_email'-'participant_name')::text DataJson,created_at CreatedAt,coalesce(updated_at,created_at) UpdatedAt FROM valorapesquisa.responses x WHERE organization_id=@organizationId AND survey_id=@surveyId AND coalesce(is_deleted,false)=false ORDER BY created_at DESC LIMIT 200";
        else { if(!Tables.TryGetValue(module,out var table)) throw new ArgumentException("Módulo inválido.",nameof(module)); sql=$"SELECT id,code,status,to_jsonb(x)::text DataJson,created_at CreatedAt,updated_at UpdatedAt FROM valorapesquisa.{table} x WHERE organization_id=@organizationId AND (cycle_id=@cycleId OR survey_id=@surveyId) AND deleted_at IS NULL ORDER BY created_at DESC LIMIT 200"; }
        using var c=connections.Create(); var rows=await c.QueryAsync<Row>(new CommandDefinition(sql,new{organizationId,cycleId,surveyId},cancellationToken:ct));
        return rows.Select(x=>new DiagnosticWorkspaceItemDto(x.Id,x.Code,x.Status,JsonSerializer.Deserialize<JsonElement>(x.DataJson),x.CreatedAt,x.UpdatedAt)).ToList();
    }
    public async Task<DiagnosticWorkspaceItemDto?> LastJobAsync(Guid organizationId, Guid surveyId, CancellationToken ct)
    { using var c=connections.Create(); var x=await c.QuerySingleOrDefaultAsync<Row>(new CommandDefinition("SELECT id,trigger code,status,to_jsonb(x)::text DataJson,created_at CreatedAt,updated_at UpdatedAt FROM valorapesquisa.intelligence_processing_jobs x WHERE organization_id=@organizationId AND survey_id=@surveyId AND deleted_at IS NULL ORDER BY created_at DESC LIMIT 1",new{organizationId,surveyId},cancellationToken:ct)); return x is null?null:new(x.Id,x.Code,x.Status,JsonSerializer.Deserialize<JsonElement>(x.DataJson),x.CreatedAt,x.UpdatedAt); }
    public async Task<bool> HasActiveJobAsync(Guid o,Guid s,CancellationToken ct){using var c=connections.Create();return await c.ExecuteScalarAsync<bool>(new CommandDefinition("SELECT EXISTS(SELECT 1 FROM valorapesquisa.intelligence_processing_jobs WHERE organization_id=@o AND survey_id=@s AND status IN ('pending','running','retry_scheduled') AND deleted_at IS NULL)",new{o,s},cancellationToken:ct));}
    public async Task<Guid> MarkProcessingAsync(Guid o,DiagnosticCycleDto d,Guid user,string correlation,CancellationToken ct)
    { await using var u=await transactions.BeginAsync(ct); try { var cycle=await EnsureCycle(u.Connection,u.Transaction,o,d,ct); var job=Guid.NewGuid(); await u.Connection.ExecuteAsync(new CommandDefinition("UPDATE valorapesquisa.diagnostic_cycles SET status='processing',processing_status='pending',updated_at=now() WHERE id=@cycle AND organization_id=@o; INSERT INTO valorapesquisa.intelligence_processing_jobs(id,organization_id,survey_id,form_id,source_entity_id,trigger,status,idempotency_key,correlation_id) VALUES(@job,@o,@survey,@form,@cycle,'manual_recalculation','pending',@key,@correlation)",new{o,cycle,job,survey=d.SurveyId,form=d.FormId,key=$"diagnostic:{d.SurveyId}:manual:{DateTime.UtcNow:yyyyMMddHHmm}",correlation},u.Transaction,cancellationToken:ct)); await Audit(u,o,cycle,user,"diagnostic.processing.requested",ct); await u.CommitAsync(); return job;}catch{await u.RollbackAsync();throw;} }
    public async Task<DiagnosticWorkspaceCommandDto?> CloseAsync(Guid o,DiagnosticCycleDto d,Guid user,string correlation,CancellationToken ct)
    { if(d.Status is "draft" or "cancelled" or "archived") return new(d.Id,d.Status,"Publique o diagnóstico antes de encerrar o ciclo."); if(d.Status=="closed")return new(d.Id,"closed","Este ciclo já está encerrado."); await using var u=await transactions.BeginAsync(ct);try{var cycle=await EnsureCycle(u.Connection,u.Transaction,o,d,ct);var job=Guid.NewGuid();var limited=d.ResponseCount==0;await u.Connection.ExecuteAsync(new CommandDefinition("UPDATE valorapesquisa.diagnostic_cycles SET status='closed',closed_at=now(),processing_status='pending',metadata_json=metadata_json||jsonb_build_object('insufficientData',@limited),updated_at=now() WHERE id=@cycle AND organization_id=@o; UPDATE valorapesquisa.surveys SET status='closed',expires_at=now(),updated_at=now() WHERE id=@survey AND organization_id=@o; INSERT INTO valorapesquisa.intelligence_processing_jobs(id,organization_id,survey_id,form_id,source_entity_id,trigger,status,idempotency_key,correlation_id) VALUES(@job,@o,@survey,@form,@cycle,'diagnosis_closed','pending',@key,@correlation); INSERT INTO valorapesquisa.journey_events(organization_id,survey_id,cycle_id,code,status,data) VALUES(@o,@survey,@cycle,'diagnostic_closed','completed',jsonb_build_object('limited',@limited)); INSERT INTO valorapesquisa.platform_governance_events(organization_id,survey_id,cycle_id,code,status,data) VALUES(@o,@survey,@cycle,'diagnostic.closed','completed',jsonb_build_object('userId',@user)); INSERT INTO valorapesquisa.notifications(organization_id,user_id,title,body,message,type,related_module,related_entity_id) SELECT @o,id,'Ciclo diagnóstico encerrado','O processamento final foi enfileirado.','O processamento final foi enfileirado.','diagnostic_closed','diagnostic-workspace',@cycle FROM valorapesquisa.users WHERE organization_id=@o AND is_deleted=false",new{o,cycle,job,survey=d.SurveyId,form=d.FormId,user,limited,key=$"diagnostic:{d.SurveyId}:close",correlation},u.Transaction,cancellationToken:ct));await u.CommitAsync();return new(cycle,"closed",limited?"Ciclo encerrado sem respostas; a limitação foi registrada.":"Ciclo encerrado e processamento final enfileirado.",job,limited);}catch{await u.RollbackAsync();throw;}}
    public async Task<DiagnosticWorkspaceCommandDto> GenerateReportAsync(Guid o,DiagnosticCycleDto d,Guid user,bool preview,CancellationToken ct){await using var u=await transactions.BeginAsync(ct);try{var cycle=await EnsureCycle(u.Connection,u.Transaction,o,d,ct);var id=Guid.NewGuid();await u.Connection.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.executive_reports(id,organization_id,survey_id,cycle_id,code,status,data) VALUES(@id,@o,@survey,@cycle,@code,@status,jsonb_build_object('preview',@preview,'generatedBy',@user)); UPDATE valorapesquisa.diagnostic_cycles SET report_generated_at=CASE WHEN @preview THEN report_generated_at ELSE now() END,status=CASE WHEN @preview THEN status ELSE 'report_ready' END,updated_at=now() WHERE id=@cycle",new{id,o,survey=d.SurveyId,cycle,code=$"report-{d.CycleNumber}",status=preview?"preview":"generated",preview,user},u.Transaction,cancellationToken:ct));await Audit(u,o,cycle,user,preview?"report.previewed":"report.generated",ct);await u.CommitAsync();return new(cycle,preview?"preview":"report_ready",preview?"Preview executivo atualizado com os dados reais disponíveis.":"Snapshot do Executive Report™ salvo.");}catch{await u.RollbackAsync();throw;}}
    private static async Task<Guid> EnsureCycle(System.Data.IDbConnection c,System.Data.IDbTransaction tx,Guid o,DiagnosticCycleDto d,CancellationToken ct)=>await c.ExecuteScalarAsync<Guid>(new CommandDefinition("INSERT INTO valorapesquisa.diagnostic_cycles(organization_id,survey_id,form_id,title,description,status,methodology_version,created_by) VALUES(@o,@survey,@form,@Title,@Description,@Status,@MethodologyVersion,@user) ON CONFLICT(organization_id,survey_id) WHERE deleted_at IS NULL DO UPDATE SET updated_at=now() RETURNING id",new{o,survey=d.SurveyId,form=d.FormId,d.Title,d.Description,d.Status,d.MethodologyVersion,user=Guid.Empty},tx,cancellationToken:ct));
    private static async Task Audit(Valora.Application.Contracts.IUnitOfWork u,Guid o,Guid cycle,Guid user,string code,CancellationToken ct)=>await u.Connection.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.platform_governance_events(organization_id,cycle_id,code,status,data) VALUES(@o,@cycle,@code,'completed',jsonb_build_object('userId',@user))",new{o,cycle,user,code},u.Transaction,cancellationToken:ct));
    private sealed record Row(Guid Id,string? Code,string Status,string DataJson,DateTime CreatedAt,DateTime UpdatedAt);
}
