using Dapper;
using Valora.Application.Contracts;
using Valora.Application.Evolution;
namespace Valora.Infrastructure.Repositories;

public sealed class EvolutionRepository(IDbConnectionFactory db, IDbTransactionFactory tx) : IEvolutionRepository {
    const string Cycles = "SELECT id,title,summary,status,baseline_score BaselineScore,current_score CurrentScore,target_score TargetScore,baseline_level BaselineLevel,current_level CurrentLevel,trend,period_start PeriodStart,period_end PeriodEnd,evidence_summary EvidenceSummary,learning_summary LearningSummary,created_at CreatedAt FROM valorapesquisa.evolution_cycles";
    public async Task<IReadOnlyList<EvolutionCycleDto>> List(Guid o, CancellationToken c) { using var x = db.Create(); return (await x.QueryAsync<EvolutionCycleDto>(new CommandDefinition(Cycles + " WHERE organization_id=@o AND deleted_at IS NULL ORDER BY created_at DESC", new { o }, cancellationToken: c))).ToList(); }
    public async Task<EvolutionCycleDto?> Get(Guid o, Guid id, CancellationToken c) { using var x = db.Create(); return await x.QuerySingleOrDefaultAsync<EvolutionCycleDto>(new CommandDefinition(Cycles + " WHERE organization_id=@o AND id=@id AND deleted_at IS NULL", new { o, id }, cancellationToken: c)); }
    public async Task<IReadOnlyList<EvolutionSnapshotDto>> Snapshots(Guid o, Guid cycle, CancellationToken c) { const string q = "SELECT id,evolution_cycle_id EvolutionCycleId,snapshot_type SnapshotType,score,previous_score PreviousScore,delta,level,trend,completed_actions CompletedActions,delayed_actions DelayedActions,open_alerts OpenAlerts,evidence_summary EvidenceSummary,interpretation,recommendation,calculated_at CalculatedAt FROM valorapesquisa.evolution_snapshots WHERE organization_id=@o AND evolution_cycle_id=@cycle AND deleted_at IS NULL ORDER BY calculated_at DESC"; using var x = db.Create(); return (await x.QueryAsync<EvolutionSnapshotDto>(new CommandDefinition(q, new { o, cycle }, cancellationToken: c))).ToList(); }
    public async Task<Guid> Open(Guid o, Guid u, OpenEvolutionCycleRequest r, CancellationToken c) { var id = Guid.NewGuid(); using var x = db.Create(); await x.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.evolution_cycles(id,organization_id,diagnostic_id,result_id,governance_cycle_id,title,summary,status,baseline_score,current_score,target_score,baseline_level,current_level,trend,period_start,period_end,evidence_summary,created_by_user_id) VALUES(@id,@o,@DiagnosticId,@ResultId,@GovernanceCycleId,@Title,@Summary,'open',@BaselineScore,@BaselineScore,@TargetScore,@BaselineLevel,@BaselineLevel,'insufficient_sample',@PeriodStart,@PeriodEnd,@EvidenceSummary,@u)", new { id, o, u, r.DiagnosticId, r.ResultId, r.GovernanceCycleId, r.Title, r.Summary, r.BaselineScore, r.TargetScore, r.BaselineLevel, r.PeriodStart, r.PeriodEnd, r.EvidenceSummary }, cancellationToken: c)); return id; }
    public async Task<Guid> Snapshot(Guid o, Guid u, Guid cycle, string evidence, string interpretation, string recommendation, CancellationToken c) { var id = Guid.NewGuid(); await using var z = await tx.BeginAsync(c); var state=await z.Connection.QuerySingleOrDefaultAsync<string>(new CommandDefinition("SELECT status FROM valorapesquisa.evolution_cycles WHERE id=@cycle AND organization_id=@o AND deleted_at IS NULL FOR UPDATE",new{o,cycle},z.Transaction,cancellationToken:c)); if(state is null)throw new KeyNotFoundException("Ciclo não encontrado."); if(state is "closed" or "archived")throw new InvalidOperationException("Um ciclo encerrado não aceita novas leituras."); const string q = """WITH stats AS (SELECT count(*) FILTER(WHERE status='completed')::int completed,count(*) FILTER(WHERE due_at<now() AND status NOT IN('completed','canceled'))::int delayed FROM valorapesquisa.action_items WHERE organization_id=@o AND deleted_at IS NULL), alerts AS(SELECT count(*)::int opened FROM valorapesquisa.intelligent_alerts WHERE organization_id=@o AND deleted_at IS NULL AND status<>'resolved'), cyc AS(SELECT current_score,baseline_level FROM valorapesquisa.evolution_cycles WHERE id=@cycle AND organization_id=@o) INSERT INTO valorapesquisa.evolution_snapshots(id,organization_id,evolution_cycle_id,snapshot_type,score,previous_score,delta,level,trend,completed_actions,delayed_actions,open_alerts,evidence_summary,interpretation,recommendation,calculated_at,created_by_user_id) SELECT @id,@o,@cycle,'monitoring',cyc.current_score,NULL,NULL,cyc.baseline_level,'insufficient_sample',stats.completed,stats.delayed,alerts.opened,@evidence,@interpretation,@recommendation,now(),@u FROM stats CROSS JOIN alerts CROSS JOIN cyc"""; var inserted=await z.Connection.ExecuteAsync(new CommandDefinition(q, new { id, o, u, cycle, evidence, interpretation, recommendation }, z.Transaction, cancellationToken: c)); if(inserted!=1)throw new InvalidOperationException("Não foi possível preservar a leitura do ciclo."); await z.Connection.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.journey_events(organization_id,event_type,title,description,source_type,source_id,impact_level,evidence_summary,occurred_at,created_by_user_id) VALUES(@o,'evolution_snapshot','Snapshot de evolução registrado','Execução de ações registrada separadamente; não implica variação metodológica nem causalidade.','evolution',@id,'medium',@evidence,now(),@u)", new { id, o, u, evidence }, z.Transaction, cancellationToken: c)); await z.CommitAsync(); return id; }
    public async Task Close(Guid o, Guid u, Guid cycle, string learning, CancellationToken c) { using var x = db.Create(); await x.ExecuteAsync(new CommandDefinition("UPDATE valorapesquisa.evolution_cycles SET status='closed',learning_summary=@learning,period_end=coalesce(period_end,now()),updated_at=now() WHERE id=@cycle AND organization_id=@o AND deleted_at IS NULL", new { o, u, cycle, learning }, cancellationToken: c)); }
}
