using Dapper;
using Microsoft.Extensions.Logging;
using Valora.Application.Contracts;
using Valora.Application.ReadModels;
namespace Valora.Infrastructure.Repositories;

public sealed class FormRepository(IDbConnectionFactory f, ILogger<FormRepository> logger) : IFormRepository {
    public async Task<FormPublicReadModel?> GetAsync(Guid id) => await GetByIdAsync(id);
    public async Task<FormPublicReadModel?> GetByIdAsync(Guid id) { try { using var c = f.Create(); return await c.QuerySingleOrDefaultAsync<FormPublicReadModel>("SELECT id,name,description,time_min AS TimeMin FROM valorapesquisa.forms WHERE id=@id AND is_deleted=false", new { id }); } catch (Exception ex) { logger.LogError(ex, "Erro ao buscar formulário. FormId={FormId}", id); throw; } }
    public async Task<FormPublicReadModel?> GetPublishedVersionAsync(Guid formId, Guid formVersionId, Guid organizationId) { try { using var c = f.Create(); return await c.QuerySingleOrDefaultAsync<FormPublicReadModel>("SELECT f.id,f.name,f.description,f.time_min AS TimeMin FROM valorapesquisa.forms f JOIN valorapesquisa.form_versions fv ON fv.form_id=f.id WHERE f.id=@formId AND fv.id=@formVersionId AND fv.status='published' AND f.is_deleted=false AND (f.organization_id=@organizationId OR f.is_global=true OR f.organization_id IS NULL)", new { formId, formVersionId, organizationId }); } catch (Exception ex) { logger.LogError(ex, "Erro ao validar versão publicada. FormId={FormId} FormVersionId={FormVersionId}", formId, formVersionId); throw; } }
    public async Task<IReadOnlyList<FormDimensionReadModel>> GetDimensionsAsync(Guid formVersionId) { try { using var c = f.Create(); return (await c.QueryAsync<FormDimensionReadModel>("SELECT id,name,NULL::text AS Description,display_order AS DisplayOrder,max_score AS MaxScore FROM valorapesquisa.dimensions WHERE form_version_id=@formVersionId ORDER BY display_order,id", new { formVersionId })).ToList(); } catch (Exception ex) { logger.LogError(ex, "Erro ao buscar dimensões da versão. FormVersionId={FormVersionId}", formVersionId); throw; } }
    public async Task<IReadOnlyList<QuestionPublicReadModel>> GetQuestionsAsync(Guid formVersionId) { try { using var c = f.Create(); return (await c.QueryAsync<QuestionPublicReadModel>("SELECT q.id,fv.form_id AS FormId,d.id AS DimensionId,q.title AS Text,q.type,q.required,5::numeric AS MaxScore,(s.position*10000+q.position) AS DisplayOrder FROM valorapesquisa.question_versions q JOIN valorapesquisa.form_section_versions s ON s.id=q.section_id JOIN valorapesquisa.form_versions fv ON fv.id=s.form_version_id LEFT JOIN valorapesquisa.dimensions d ON d.form_version_id=fv.id AND d.code=q.dimension_code WHERE fv.id=@formVersionId AND fv.status='published' AND s.deleted_at IS NULL AND q.deleted_at IS NULL AND q.type NOT IN ('heading','description','separator') ORDER BY s.position,q.position,q.id", new { formVersionId })).ToList(); } catch (Exception ex) { logger.LogError(ex, "Erro ao buscar perguntas da versão. FormVersionId={FormVersionId}", formVersionId); throw; } }
    public async Task<IReadOnlyList<QuestionOptionPublicReadModel>> GetQuestionOptionsAsync(Guid formVersionId) { try { using var c = f.Create(); return (await c.QueryAsync<QuestionOptionPublicReadModel>("SELECT o.id,o.question_id AS QuestionId,o.label AS Text,o.score,o.position AS DisplayOrder FROM valorapesquisa.question_option_versions o JOIN valorapesquisa.question_versions q ON q.id=o.question_id JOIN valorapesquisa.form_section_versions s ON s.id=q.section_id JOIN valorapesquisa.form_versions fv ON fv.id=s.form_version_id WHERE fv.id=@formVersionId AND fv.status='published' AND s.deleted_at IS NULL AND q.deleted_at IS NULL AND o.deleted_at IS NULL ORDER BY s.position,q.position,o.position,o.id", new { formVersionId })).ToList(); } catch (Exception ex) { logger.LogError(ex, "Erro ao buscar opções da versão. FormVersionId={FormVersionId}", formVersionId); throw; } }

    public async Task<IReadOnlyList<dynamic>> ListAdminAsync(Guid organizationId) { try { using var c = f.Create(); return (await c.QueryAsync("SELECT id,organization_id,name,description,category,time_min,status,is_global,created_at,updated_at FROM valorapesquisa.forms WHERE is_deleted=false AND (organization_id=@organizationId OR is_global=true OR organization_id IS NULL) ORDER BY created_at DESC", new { organizationId })).ToList(); } catch (Exception ex) { logger.LogError(ex, "Erro ao listar formulários. OrganizationId={OrganizationId}", organizationId); throw; } }
    public async Task<Guid> CreateAdminAsync(Guid organizationId, string name, string? description, string status) { try { using var c = f.Create(); return await c.ExecuteScalarAsync<Guid>("INSERT INTO valorapesquisa.forms(organization_id,name,description,status) VALUES (@organizationId,@name,@description,@status) RETURNING id", new { organizationId, name, description, status }); } catch (Exception ex) { logger.LogError(ex, "Erro ao criar formulário. OrganizationId={OrganizationId}", organizationId); throw; } }
    public async Task UpdateAdminAsync(Guid organizationId, Guid formId, string? name, string? description, string? status) { try { using var c = f.Create(); await c.ExecuteAsync("UPDATE valorapesquisa.forms SET name=COALESCE(@name,name),description=COALESCE(@description,description),status=COALESCE(@status,status),updated_at=now() WHERE id=@formId AND organization_id=@organizationId AND is_deleted=false", new { organizationId, formId, name, description, status }); } catch (Exception ex) { logger.LogError(ex, "Erro ao atualizar formulário. OrganizationId={OrganizationId} FormId={FormId}", organizationId, formId); throw; } }

}
