using Dapper;
using Microsoft.Extensions.Logging;
using Valora.Application.Contracts;
using Valora.Application.ReadModels;
namespace Valora.Infrastructure.Repositories;
public sealed class FormRepository(IDbConnectionFactory f, ILogger<FormRepository> logger):IFormRepository
{
    public async Task<FormPublicReadModel?> GetAsync(Guid id)=>await GetByIdAsync(id);
    public async Task<FormPublicReadModel?> GetByIdAsync(Guid id){try{using var c=f.Create(); return await c.QuerySingleOrDefaultAsync<FormPublicReadModel>("SELECT id,name,description,time_min AS TimeMin FROM valorapesquisa.forms WHERE id=@id AND is_deleted=false",new{id});}catch(Exception ex){logger.LogError(ex,"Erro ao buscar formulário. FormId={FormId}",id);throw;}}
    public async Task<IReadOnlyList<FormDimensionReadModel>> GetDimensionsAsync(Guid formId){try{using var c=f.Create(); return (await c.QueryAsync<FormDimensionReadModel>("SELECT id,name,description,display_order AS DisplayOrder,max_score AS MaxScore FROM valorapesquisa.form_dimensions WHERE form_id=@formId ORDER BY display_order",new{formId})).ToList();}catch(Exception ex){logger.LogError(ex,"Erro ao buscar dimensões do formulário. FormId={FormId}",formId);throw;}}
    public async Task<IReadOnlyList<QuestionPublicReadModel>> GetQuestionsAsync(Guid formId){try{using var c=f.Create(); return (await c.QueryAsync<QuestionPublicReadModel>("SELECT id,form_id AS FormId,dimension_id AS DimensionId,text,type,required,COALESCE(max_score,5) AS MaxScore,display_order AS DisplayOrder FROM valorapesquisa.questions WHERE form_id=@formId ORDER BY display_order",new{formId})).ToList();}catch(Exception ex){logger.LogError(ex,"Erro ao buscar perguntas do formulário. FormId={FormId}",formId);throw;}}
    public async Task<IReadOnlyList<QuestionOptionPublicReadModel>> GetQuestionOptionsAsync(Guid formId){try{using var c=f.Create(); return (await c.QueryAsync<QuestionOptionPublicReadModel>("SELECT qo.id,qo.question_id AS QuestionId,qo.text,qo.score,qo.display_order AS DisplayOrder FROM valorapesquisa.question_options qo JOIN valorapesquisa.questions q ON q.id=qo.question_id WHERE q.form_id=@formId ORDER BY qo.display_order",new{formId})).ToList();}catch(Exception ex){logger.LogError(ex,"Erro ao buscar opções do formulário. FormId={FormId}",formId);throw;}}

    public async Task<IReadOnlyList<dynamic>> ListAdminAsync(Guid organizationId){try{using var c=f.Create(); return (await c.QueryAsync("SELECT id,organization_id,name,description,category,time_min,status,is_global,created_at,updated_at FROM valorapesquisa.forms WHERE is_deleted=false AND (organization_id=@organizationId OR is_global=true OR organization_id IS NULL) ORDER BY created_at DESC",new{organizationId})).ToList();}catch(Exception ex){logger.LogError(ex,"Erro ao listar formulários. OrganizationId={OrganizationId}",organizationId);throw;}}
    public async Task<Guid> CreateAdminAsync(Guid organizationId,string name,string? description,string status){try{using var c=f.Create(); return await c.ExecuteScalarAsync<Guid>("INSERT INTO valorapesquisa.forms(organization_id,name,description,status) VALUES (@organizationId,@name,@description,@status) RETURNING id",new{organizationId,name,description,status});}catch(Exception ex){logger.LogError(ex,"Erro ao criar formulário. OrganizationId={OrganizationId}",organizationId);throw;}}
    public async Task UpdateAdminAsync(Guid organizationId,Guid formId,string? name,string? description,string? status){try{using var c=f.Create(); await c.ExecuteAsync("UPDATE valorapesquisa.forms SET name=COALESCE(@name,name),description=COALESCE(@description,description),status=COALESCE(@status,status),updated_at=now() WHERE id=@formId AND organization_id=@organizationId AND is_deleted=false",new{organizationId,formId,name,description,status});}catch(Exception ex){logger.LogError(ex,"Erro ao atualizar formulário. OrganizationId={OrganizationId} FormId={FormId}",organizationId,formId);throw;}}

}
