using Dapper;
using Microsoft.Extensions.Logging;
using Valora.Application.Contracts;
using Valora.Application.DTOs.FreeDiagnostics;
using Valora.Application.Security;

namespace Valora.Infrastructure.Repositories;

public sealed class FreeDiagnosticsRepository(IDbConnectionFactory f, ILogger<FreeDiagnosticsRepository> logger) : IFreeDiagnosticsRepository
{
    const string BaseWhere = "r.is_deleted=false AND COALESCE(s.is_public,true)=true AND (@organizationId IS NULL OR r.organization_id=@organizationId) AND (@startDate IS NULL OR r.created_at>=@startDate) AND (@endDate IS NULL OR r.created_at<@endDate + interval '1 day') AND (@name IS NULL OR r.participant_name ILIKE '%'||@name||'%') AND (@email IS NULL OR r.participant_email ILIKE '%'||@email||'%') AND (@emailStatus IS NULL OR ej.status=@emailStatus) AND (@maturityLevel IS NULL OR rs.maturity_level=@maturityLevel) AND (@certificateStatus IS NULL OR c.status=@certificateStatus)";
    object Args(FreeDiagnosticFilter x, Guid? organizationId)=>new{organizationId,x.StartDate,x.EndDate,x.Name,x.Email,x.EmailStatus,x.MaturityLevel,x.CertificateStatus,offset=(Math.Max(x.Page,1)-1)*Math.Clamp(x.PageSize,1,100),limit=Math.Clamp(x.PageSize,1,100)};
    public async Task<IReadOnlyList<FreeDiagnosticListItemDto>> ListAsync(FreeDiagnosticFilter filter, Guid? organizationId){try{using var c=f.Create(); var sql=$@"SELECT r.id AS ResponseId,r.organization_id AS OrganizationId,o.name AS OrganizationName,s.title AS SurveyTitle,r.participant_name AS ParticipantName,CASE WHEN r.participant_email IS NULL THEN NULL ELSE regexp_replace(r.participant_email,'(^.).*(@.*$)','\1***\2') END AS ParticipantEmail,COALESCE(ej.status,'pending') AS EmailStatus,COALESCE(c.status,'not-generated') AS CertificateStatus,rs.maturity_level AS MaturityLevel,r.created_at AS CreatedAt,r.completed_at AS CompletedAt,COALESCE(ej.attempts,0) AS EmailAttempts,COALESCE(ej.resend_count,0) AS ResendCount,ej.last_resend_at AS LastResendAt,ej.reviewed_at AS ReviewedAt,LEFT(COALESCE(ej.last_error,''),180) AS LastError,('/results/'||r.id) AS ResultUrl,('/certificates/validate/'||c.certificate_code) AS CertificateUrl,NULL AS CorrelationId FROM valorapesquisa.responses r JOIN valorapesquisa.surveys s ON s.id=r.survey_id LEFT JOIN valorapesquisa.organizations o ON o.id=r.organization_id LEFT JOIN LATERAL (SELECT id,status,attempts,last_error,resend_count,last_resend_at,reviewed_at FROM valorapesquisa.email_jobs WHERE response_id=r.id AND is_deleted=false ORDER BY created_at DESC LIMIT 1) ej ON true LEFT JOIN valorapesquisa.certificates c ON c.response_id=r.id AND c.is_deleted=false LEFT JOIN valorapesquisa.result_scores rs ON rs.response_id=r.id WHERE {BaseWhere} ORDER BY r.created_at DESC LIMIT @limit OFFSET @offset"; return (await c.QueryAsync<FreeDiagnosticListItemDto>(sql,Args(filter,organizationId))).ToList();}catch(Exception ex){logger.LogError(ex,"Erro ao listar diagnósticos gratuitos. OrganizationId={OrganizationId}",organizationId);throw;}}
    public async Task<FreeDiagnosticSummaryDto> SummaryAsync(FreeDiagnosticFilter filter, Guid? organizationId){try{using var c=f.Create(); var sql=$@"SELECT COUNT(DISTINCT r.id)::int AS TotalResponses,COUNT(DISTINCT r.id) FILTER (WHERE r.created_at::date=now()::date)::int AS TodayResponses,COUNT(DISTINCT r.id) FILTER (WHERE date_trunc('month',r.created_at)=date_trunc('month',now()))::int AS MonthResponses,COUNT(DISTINCT ej.id) FILTER (WHERE ej.status='sent')::int AS EmailsSent,COUNT(DISTINCT ej.id) FILTER (WHERE ej.status='pending')::int AS EmailsPending,COUNT(DISTINCT ej.id) FILTER (WHERE ej.status='processing')::int AS EmailsProcessing,COUNT(DISTINCT ej.id) FILTER (WHERE ej.status='failed')::int AS EmailsFailed,COUNT(DISTINCT c.id)::int AS CertificatesGenerated,COUNT(DISTINCT al.id) FILTER (WHERE al.action='free_survey.whatsapp_cta_clicked')::int AS SharedLinks FROM valorapesquisa.responses r JOIN valorapesquisa.surveys s ON s.id=r.survey_id LEFT JOIN valorapesquisa.email_jobs ej ON ej.response_id=r.id AND ej.is_deleted=false LEFT JOIN valorapesquisa.certificates c ON c.response_id=r.id AND c.is_deleted=false LEFT JOIN valorapesquisa.result_scores rs ON rs.response_id=r.id LEFT JOIN valorapesquisa.audit_logs al ON al.entity_id=r.id::text WHERE {BaseWhere}"; return await c.QuerySingleAsync<FreeDiagnosticSummaryDto>(sql,Args(filter,organizationId));}catch(Exception ex){logger.LogError(ex,"Erro ao resumir diagnósticos gratuitos. OrganizationId={OrganizationId}",organizationId);throw;}}
    public async Task<FreeDiagnosticDetailDto?> DetailAsync(Guid responseId, Guid? organizationId){var list=await ListAsync(new FreeDiagnosticFilter(null,null,null,null,null,null,null,1,1),organizationId); var item=list.FirstOrDefault(x=>x.ResponseId==responseId); if(item is null){using var c=f.Create(); item=await c.QuerySingleOrDefaultAsync<FreeDiagnosticListItemDto>("SELECT r.id AS ResponseId,r.organization_id AS OrganizationId,o.name AS OrganizationName,s.title AS SurveyTitle,r.participant_name AS ParticipantName,regexp_replace(COALESCE(r.participant_email,''),'(^.).*(@.*$)','\\1***\\2') AS ParticipantEmail,COALESCE(ej.status,'pending') AS EmailStatus,COALESCE(cert.status,'not-generated') AS CertificateStatus,rs.maturity_level AS MaturityLevel,r.created_at AS CreatedAt,r.completed_at AS CompletedAt,COALESCE(ej.attempts,0) AS EmailAttempts,COALESCE(ej.resend_count,0) AS ResendCount,ej.last_resend_at AS LastResendAt,ej.reviewed_at AS ReviewedAt,LEFT(COALESCE(ej.last_error,''),180) AS LastError,('/results/'||r.id) AS ResultUrl,('/certificates/validate/'||cert.certificate_code) AS CertificateUrl,NULL AS CorrelationId FROM valorapesquisa.responses r JOIN valorapesquisa.surveys s ON s.id=r.survey_id LEFT JOIN valorapesquisa.organizations o ON o.id=r.organization_id LEFT JOIN LATERAL (SELECT status,attempts,last_error,resend_count,last_resend_at,reviewed_at FROM valorapesquisa.email_jobs WHERE response_id=r.id ORDER BY created_at DESC LIMIT 1) ej ON true LEFT JOIN valorapesquisa.certificates cert ON cert.response_id=r.id LEFT JOIN valorapesquisa.result_scores rs ON rs.response_id=r.id WHERE r.id=@responseId AND (@organizationId IS NULL OR r.organization_id=@organizationId)",new{responseId,organizationId});} return item is null?null:new(item.ResponseId,item.OrganizationId,item.OrganizationName,item.SurveyTitle,item.ParticipantName,item.ParticipantEmail,item.EmailStatus,item.CertificateStatus,item.MaturityLevel,item.CreatedAt,item.CompletedAt,item.EmailAttempts,item.ResendCount,item.LastResendAt,item.ReviewedAt,null,item.LastError,item.ResultUrl,item.CertificateUrl,null,item.CertificateUrl,new List<object>(),new List<object>());}
    public async Task<int> CountManualResendsLast24hAsync(Guid responseId){using var c=f.Create(); return await c.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM valorapesquisa.email_jobs WHERE response_id=@responseId AND template_key='result-ready-resend' AND created_at>=now()-interval '24 hours'",new{responseId});}
    public async Task CreateResendEmailJobAsync(Guid responseId, Guid? actorUserId, string justification){try{using var c=f.Create(); await c.ExecuteAsync("INSERT INTO valorapesquisa.email_jobs(organization_id,response_id,recipient_email,to_email,subject,body,template_key,status,payload_json,resend_count,last_resend_at,created_by) SELECT r.organization_id,r.id,r.participant_email,r.participant_email,'Valora Pulse - reenvio do diagnóstico','Resultado disponível no link oficial.','result-ready-resend','pending',jsonb_build_object('reason',@justification),COALESCE((SELECT max(resend_count) FROM valorapesquisa.email_jobs WHERE response_id=r.id),0)+1,now(),@actorUserId FROM valorapesquisa.responses r WHERE r.id=@responseId",new{responseId,actorUserId,justification});}catch(Exception ex){logger.LogError(ex,"Erro ao criar reenvio. ResponseId={ResponseId}",responseId);throw;}}
    public async Task RegenerateCertificateMetadataAsync(Guid responseId, Guid? actorUserId, string? layoutVersion){using var c=f.Create(); await c.ExecuteAsync("UPDATE valorapesquisa.certificates SET certificate_code=COALESCE(certificate_code,'VALORA-'||substring(@responseId::text,1,8)), validation_url='/certificates/validate/'||certificate_code, issued_at=now(), updated_at=now(), updated_by=@actorUserId WHERE response_id=@responseId",new{responseId,actorUserId,layoutVersion});}
    public async Task MarkReviewedAsync(Guid responseId, Guid? actorUserId, string reviewNote){using var c=f.Create(); await c.ExecuteAsync("UPDATE valorapesquisa.email_jobs SET status=CASE WHEN status='failed' THEN 'reviewed' ELSE status END, reviewed_at=now(), reviewed_by=@actorUserId, review_note=@reviewNote, updated_at=now() WHERE response_id=@responseId AND status IN ('failed','reviewed')",new{responseId,actorUserId,reviewNote});}
    public async Task AuditAsync(Guid? organizationId, Guid responseId, Guid? actorUserId, string eventType, string actorType, string metadataJson){using var c=f.Create(); await c.ExecuteAsync("INSERT INTO valorapesquisa.audit_logs(organization_id,user_id,action,entity_type,entity_id,message,metadata_json) VALUES (@organizationId,@actorUserId,@eventType,'free_diagnostic',@entityId,@actorType,CAST(@metadataJson AS jsonb))",new{organizationId,actorUserId,eventType,actorType,entityId=responseId.ToString(),metadataJson=Sanitize(metadataJson)});}
    static string Sanitize(string? value)=>string.IsNullOrWhiteSpace(value)?string.Empty:value.Replace("\r"," ").Replace("\n"," ")[..Math.Min(value.Replace("\r"," ").Replace("\n"," ").Length,500)];
}
