using Dapper;
using Valora.Application.Contracts;
using Valora.Application.Indicators;

namespace Valora.Infrastructure.Repositories;

public sealed class IndicatorRepository(IDbConnectionFactory db) : IIndicatorRepository
{
    private const string IndicatorSelect = """
        SELECT i.id,i.name,c.name category,i.unit,s.name source_name,i.responsible_user_id,i.periodicity,
        i.status,i.is_calculated,f.expression formula,i.created_at,
        count(m.id)::int measurement_count,(array_agg(m.value ORDER BY m.measured_at DESC) FILTER(WHERE m.id IS NOT NULL))[1] latest_value,
        max(m.measured_at) latest_measured_at
        FROM valorapesquisa.indicators i JOIN valorapesquisa.indicator_categories c ON c.id=i.category_id
        LEFT JOIN valorapesquisa.indicator_sources s ON s.id=i.source_id
        LEFT JOIN valorapesquisa.indicator_formulas f ON f.indicator_id=i.id AND f.is_active
        LEFT JOIN valorapesquisa.indicator_measurements m ON m.indicator_id=i.id
        """;
    private const string IndicatorGroup = " GROUP BY i.id,c.name,s.name,f.expression ";
    public async Task<IReadOnlyList<IndicatorDto>> List(Guid o,CancellationToken ct){using var c=db.Create();return (await c.QueryAsync<IndicatorDto>(new CommandDefinition(IndicatorSelect+" WHERE i.organization_id=@o "+IndicatorGroup+" ORDER BY i.name",new{o},cancellationToken:ct))).ToList();}
    public async Task<IndicatorDto?> Get(Guid o,Guid id,CancellationToken ct){using var c=db.Create();return await c.QuerySingleOrDefaultAsync<IndicatorDto>(new CommandDefinition(IndicatorSelect+" WHERE i.organization_id=@o AND i.id=@id "+IndicatorGroup,new{o,id},cancellationToken:ct));}
    public async Task<Guid> Create(Guid o,CreateIndicatorRequest r,CancellationToken ct){using var c=db.Create();var id=Guid.NewGuid();const string q="""WITH category AS (INSERT INTO valorapesquisa.indicator_categories(id,organization_id,name,code) VALUES(gen_random_uuid(),@o,@Category,lower(regexp_replace(@Category,'[^a-zA-Z0-9]+','-','g'))) ON CONFLICT(organization_id,code) DO UPDATE SET name=excluded.name RETURNING id), source AS (INSERT INTO valorapesquisa.indicator_sources(id,organization_id,name,source_type,reliability_status) VALUES(gen_random_uuid(),@o,@SourceName,'manual','declared') ON CONFLICT(organization_id,name) DO UPDATE SET name=excluded.name RETURNING id) INSERT INTO valorapesquisa.indicators(id,organization_id,name,category_id,unit,source_id,responsible_user_id,periodicity,status,is_calculated) SELECT @id,@o,@Name,category.id,@Unit,source.id,@ResponsibleUserId,@Periodicity,'active',@IsCalculated FROM category,source; INSERT INTO valorapesquisa.indicator_formulas(id,organization_id,indicator_id,expression,is_active) SELECT gen_random_uuid(),@o,@id,@Formula,true WHERE @IsCalculated AND nullif(trim(@Formula),'') IS NOT NULL; INSERT INTO valorapesquisa.indicator_events(organization_id,event_type,entity_id,metadata) VALUES(@o,'indicator.created',@id,jsonb_build_object('name',@Name));""";await c.ExecuteAsync(new CommandDefinition(q,new{id,o,r.Name,r.Category,r.Unit,r.SourceName,r.ResponsibleUserId,r.Periodicity,r.IsCalculated,r.Formula},cancellationToken:ct));return id;}
    public async Task Archive(Guid o,Guid id,CancellationToken ct){using var c=db.Create();await c.ExecuteAsync(new CommandDefinition("UPDATE valorapesquisa.indicators SET status='archived',archived_at=now(),updated_at=now() WHERE organization_id=@o AND id=@id AND status<>'archived'",new{o,id},cancellationToken:ct));}
    public async Task<IReadOnlyList<IndicatorTargetDto>> Targets(Guid o,Guid? indicatorId,CancellationToken ct){using var c=db.Create();const string q="SELECT id,indicator_id,target_value,period_start,period_end,comparison_rule,responsible_user_id,status FROM valorapesquisa.indicator_targets WHERE organization_id=@o AND (CAST(@indicatorId AS uuid) IS NULL OR indicator_id=CAST(@indicatorId AS uuid)) ORDER BY period_end DESC";return(await c.QueryAsync<IndicatorTargetDto>(new CommandDefinition(q,new{o,indicatorId},cancellationToken:ct))).ToList();}
    public async Task<Guid> CreateTarget(Guid o,Guid indicatorId,CreateTargetRequest r,CancellationToken ct){using var c=db.Create();var id=Guid.NewGuid();const string q="""INSERT INTO valorapesquisa.indicator_targets(id,organization_id,indicator_id,target_value,period_start,period_end,comparison_rule,responsible_user_id,status) SELECT @id,@o,@indicatorId,@TargetValue,@PeriodStart,@PeriodEnd,@ComparisonRule,@ResponsibleUserId,'active' WHERE EXISTS(SELECT 1 FROM valorapesquisa.indicators WHERE id=@indicatorId AND organization_id=@o AND status='active') AND NOT EXISTS(SELECT 1 FROM valorapesquisa.indicator_targets WHERE organization_id=@o AND indicator_id=@indicatorId AND status='active' AND daterange(period_start::date,period_end::date,'[]') && daterange(@PeriodStart::date,@PeriodEnd::date,'[]')); INSERT INTO valorapesquisa.indicator_events(organization_id,event_type,entity_id) SELECT @o,'indicator.target.created',@id WHERE EXISTS(SELECT 1 FROM valorapesquisa.indicator_targets WHERE id=@id);""";var rows=await c.ExecuteAsync(new CommandDefinition(q,new{id,o,indicatorId,r.TargetValue,r.PeriodStart,r.PeriodEnd,r.ComparisonRule,r.ResponsibleUserId},cancellationToken:ct));if(rows==0)throw new InvalidOperationException("Já existe meta ativa conflitante ou o indicador não está ativo.");return id;}
    public async Task<IReadOnlyList<IndicatorMeasurementDto>> Measurements(Guid o,Guid indicatorId,CancellationToken ct){using var c=db.Create();const string q="SELECT id,indicator_id,value,measured_at,source_name,responsible_user_id,justification,revision,data_hub_import_id FROM valorapesquisa.indicator_measurements WHERE organization_id=@o AND indicator_id=@indicatorId ORDER BY measured_at DESC,revision DESC";return(await c.QueryAsync<IndicatorMeasurementDto>(new CommandDefinition(q,new{o,indicatorId},cancellationToken:ct))).ToList();}
    public async Task<Guid> CreateMeasurement(Guid o,Guid indicatorId,CreateMeasurementRequest r,CancellationToken ct){using var c=db.Create();var id=Guid.NewGuid();const string q="""INSERT INTO valorapesquisa.indicator_measurements(id,organization_id,indicator_id,value,measured_at,source_name,responsible_user_id,justification,data_hub_import_id) SELECT @id,@o,@indicatorId,@Value,@MeasuredAt,@SourceName,@ResponsibleUserId,@Justification,@DataHubImportId WHERE EXISTS(SELECT 1 FROM valorapesquisa.indicators WHERE id=@indicatorId AND organization_id=@o AND status='active'); INSERT INTO valorapesquisa.indicator_events(organization_id,event_type,entity_id) SELECT @o,'indicator.measurement.created',@id WHERE EXISTS(SELECT 1 FROM valorapesquisa.indicator_measurements WHERE id=@id);""";try{var rows=await c.ExecuteAsync(new CommandDefinition(q,new{id,o,indicatorId,r.Value,r.MeasuredAt,r.SourceName,r.ResponsibleUserId,r.Justification,r.DataHubImportId},cancellationToken:ct));if(rows==0)throw new InvalidOperationException("Indicador inexistente ou arquivado não recebe medição.");return id;}catch(Npgsql.PostgresException e) when(e.SqlState=="23505"){throw new InvalidOperationException("Já existe uma medição neste período; registre uma revisão autorizada.",e);}}
    public async Task<IReadOnlyList<IndicatorAlertDto>> Alerts(Guid o,CancellationToken ct){using var c=db.Create();const string q="SELECT a.id,a.indicator_id,i.name indicator_name,a.severity,a.message,a.status,a.created_at,a.resolved_at FROM valorapesquisa.indicator_alerts a JOIN valorapesquisa.indicators i ON i.id=a.indicator_id WHERE a.organization_id=@o ORDER BY CASE a.severity WHEN 'critical' THEN 0 WHEN 'high' THEN 1 ELSE 2 END,a.created_at DESC";return(await c.QueryAsync<IndicatorAlertDto>(new CommandDefinition(q,new{o},cancellationToken:ct))).ToList();}
    public async Task ResolveAlert(Guid o,Guid id,Guid user,CancellationToken ct){using var c=db.Create();const string q="""WITH resolved AS (UPDATE valorapesquisa.indicator_alerts SET status='resolved',resolved_at=now(),resolved_by_user_id=@user WHERE organization_id=@o AND id=@id AND status<>'resolved' RETURNING id) INSERT INTO valorapesquisa.indicator_events(organization_id,event_type,entity_id,actor_user_id) SELECT @o,'indicator.alert.resolved',id,@user FROM resolved""";await c.ExecuteAsync(new CommandDefinition(q,new{o,id,user},cancellationToken:ct));}
    public async Task<IReadOnlyList<ExecutiveScorecardDto>> Scorecards(Guid o,CancellationToken ct){using var c=db.Create();const string q="SELECT s.id,s.name,s.objective,s.period_start,s.period_end,count(i.id)::int item_count,s.created_at FROM valorapesquisa.executive_scorecards s LEFT JOIN valorapesquisa.executive_scorecard_items i ON i.scorecard_id=s.id WHERE s.organization_id=@o GROUP BY s.id ORDER BY s.created_at DESC";return(await c.QueryAsync<ExecutiveScorecardDto>(new CommandDefinition(q,new{o},cancellationToken:ct))).ToList();}
    public async Task<Guid> CreateScorecard(Guid o,Guid user,CreateScorecardRequest r,CancellationToken ct){using var c=db.Create();var id=Guid.NewGuid();const string q="""INSERT INTO valorapesquisa.executive_scorecards(id,organization_id,name,objective,period_start,period_end,created_by_user_id) VALUES(@id,@o,@Name,@Objective,@PeriodStart,@PeriodEnd,@user); INSERT INTO valorapesquisa.executive_scorecard_items(id,organization_id,scorecard_id,indicator_id,display_order) SELECT gen_random_uuid(),@o,@id,x.indicator_id,x.ordinality FROM unnest(@IndicatorIds::uuid[]) WITH ORDINALITY x(indicator_id,ordinality) JOIN valorapesquisa.indicators i ON i.id=x.indicator_id AND i.organization_id=@o; INSERT INTO valorapesquisa.indicator_events(organization_id,event_type,entity_id,actor_user_id) VALUES(@o,'scorecard.created',@id,@user);""";await c.ExecuteAsync(new CommandDefinition(q,new{id,o,user,r.Name,r.Objective,r.PeriodStart,r.PeriodEnd,r.IndicatorIds},cancellationToken:ct));return id;}
    public async Task<IReadOnlyList<AnalyticsSnapshotDto>> Snapshots(Guid o,CancellationToken ct){using var c=db.Create();const string q="SELECT s.id,s.name,s.captured_at,s.limitation,count(i.id)::int item_count FROM valorapesquisa.analytics_snapshots s LEFT JOIN valorapesquisa.analytics_snapshot_items i ON i.snapshot_id=s.id WHERE s.organization_id=@o GROUP BY s.id ORDER BY s.captured_at DESC";return(await c.QueryAsync<AnalyticsSnapshotDto>(new CommandDefinition(q,new{o},cancellationToken:ct))).ToList();}
    public async Task<Guid> CreateSnapshot(Guid o,Guid user,string name,CancellationToken ct){using var c=db.Create();var id=Guid.NewGuid();const string q="""INSERT INTO valorapesquisa.analytics_snapshots(id,organization_id,name,limitation,created_by_user_id) VALUES(@id,@o,@name,'Leitura histórica; associação com ações não comprova causalidade.',@user); INSERT INTO valorapesquisa.analytics_snapshot_items(id,organization_id,snapshot_id,indicator_id,value,source_name,measurement_count) SELECT gen_random_uuid(),@o,@id,i.id,m.value,s.name,(SELECT count(*) FROM valorapesquisa.indicator_measurements z WHERE z.indicator_id=i.id) FROM valorapesquisa.indicators i LEFT JOIN valorapesquisa.indicator_sources s ON s.id=i.source_id LEFT JOIN LATERAL(SELECT value FROM valorapesquisa.indicator_measurements WHERE indicator_id=i.id ORDER BY measured_at DESC LIMIT 1)m ON true WHERE i.organization_id=@o AND i.status='active'; INSERT INTO valorapesquisa.indicator_events(organization_id,event_type,entity_id,actor_user_id) VALUES(@o,'analytics.snapshot.created',@id,@user);""";await c.ExecuteAsync(new CommandDefinition(q,new{id,o,user,name},cancellationToken:ct));return id;}
}
