using System.Text.Json;
using Dapper;
using Valora.Application.Contracts;
using Valora.Application.OrganizationalIntelligence;

namespace Valora.Infrastructure.Repositories;

public sealed class IntelligenceProcessingJobRepository(IDbConnectionFactory connections) : IIntelligenceProcessingJobRepository
{
    public async Task<Guid> EnqueueAsync(IntelligenceProcessingContext c, int maxAttempts, string correlationId, CancellationToken ct)
    {
        const string sql = """INSERT INTO valorapesquisa.intelligence_processing_jobs(organization_id,survey_id,response_id,form_id,source_entity_id,trigger,status,max_attempts,correlation_id,idempotency_key,metadata_json) VALUES(@OrganizationId,@SurveyId,@ResponseId,@FormId,@SourceEntityId,@Trigger,'pending',@maxAttempts,@correlationId,md5(@OrganizationId::text||':'||coalesce(@ResponseId::text,@SurveyId::text,@SourceEntityId::text,'all')||':'||@Trigger),jsonb_build_object('source','valora_pipeline')) ON CONFLICT (organization_id,idempotency_key) WHERE deleted_at IS NULL AND status IN ('pending','running','retry_scheduled') DO UPDATE SET updated_at=now() RETURNING id""";
        using var db=connections.Create(); return await db.ExecuteScalarAsync<Guid>(new CommandDefinition(sql,new { c.OrganizationId,c.SurveyId,c.ResponseId,c.FormId,c.SourceEntityId,c.Trigger,maxAttempts,correlationId},cancellationToken:ct));
    }
    public async Task<IReadOnlyList<IntelligenceProcessingJob>> GetPendingJobsAsync(int take, CancellationToken ct)
    { const string sql="""SELECT * FROM valorapesquisa.intelligence_processing_jobs WHERE deleted_at IS NULL AND status IN ('pending','retry_scheduled') AND scheduled_at<=now() AND coalesce(next_attempt_at,now())<=now() AND (locked_at IS NULL OR locked_at<now()-interval '10 minutes') ORDER BY priority,scheduled_at LIMIT @take"""; using var db=connections.Create(); return (await db.QueryAsync<IntelligenceProcessingJob>(new CommandDefinition(sql,new{take},cancellationToken:ct))).AsList(); }
    public async Task<bool> LockJobAsync(Guid id,string worker,CancellationToken ct)
    { const string sql="""UPDATE valorapesquisa.intelligence_processing_jobs SET locked_at=now(),locked_by=@worker,updated_at=now() WHERE id=@id AND status IN ('pending','retry_scheduled') AND (locked_at IS NULL OR locked_at<now()-interval '10 minutes')"""; using var db=connections.Create(); return await db.ExecuteAsync(new CommandDefinition(sql,new{id,worker},cancellationToken:ct))==1; }
    public Task MarkRunningAsync(Guid id,Guid runId,CancellationToken ct)=>Execute("UPDATE valorapesquisa.intelligence_processing_jobs SET status='running',started_at=coalesce(started_at,now()),attempts=attempts+1,run_id=@runId,updated_at=now() WHERE id=@id",new{id,runId},ct);
    public Task MarkCompletedAsync(Guid id,string status,CancellationToken ct)=>Execute("UPDATE valorapesquisa.intelligence_processing_jobs SET status=@status,completed_at=now(),locked_at=NULL,locked_by=NULL,error_code=NULL,error_message=NULL,updated_at=now() WHERE id=@id",new{id,status},ct);
    public Task MarkFailedAsync(Guid id,string code,string message,CancellationToken ct)=>Execute("UPDATE valorapesquisa.intelligence_processing_jobs SET status='failed',failed_at=now(),locked_at=NULL,locked_by=NULL,error_code=@code,error_message=@message,updated_at=now() WHERE id=@id",new{id,code,message},ct);
    public Task ScheduleRetryAsync(Guid id,DateTime next,string code,string message,CancellationToken ct)=>Execute("UPDATE valorapesquisa.intelligence_processing_jobs SET status='retry_scheduled',next_attempt_at=@next,locked_at=NULL,locked_by=NULL,error_code=@code,error_message=@message,updated_at=now() WHERE id=@id",new{id,next,code,message},ct);
    public async Task<bool> CancelAsync(Guid o,Guid id,Guid? user,CancellationToken ct)
    { const string sql="""WITH changed AS (UPDATE valorapesquisa.intelligence_processing_jobs SET status='cancelled',locked_at=NULL,locked_by=NULL,updated_at=now() WHERE id=@id AND organization_id=@o AND status IN ('pending','retry_scheduled') RETURNING id) INSERT INTO valorapesquisa.intelligence_reprocess_requests(organization_id,job_id,requested_by,request_type,status,metadata_json) SELECT @o,id,@user,'cancel','completed','{}'::jsonb FROM changed RETURNING true"""; using var db=connections.Create(); return await db.ExecuteScalarAsync<bool?>(new CommandDefinition(sql,new{o,id,user},cancellationToken:ct))??false; }
    public async Task<Guid?> ReprocessAsync(Guid o,Guid id,Guid? user,string correlationId,CancellationToken ct)
    { const string sql="""WITH source AS (SELECT * FROM valorapesquisa.intelligence_processing_jobs WHERE id=@id AND organization_id=@o AND deleted_at IS NULL), created AS (INSERT INTO valorapesquisa.intelligence_processing_jobs(organization_id,survey_id,response_id,form_id,source_entity_id,trigger,status,max_attempts,correlation_id,metadata_json,idempotency_key) SELECT organization_id,survey_id,response_id,form_id,source_entity_id,'reprocess:'||trigger,'pending',max_attempts,@correlationId,jsonb_build_object('reprocessedJobId',id),md5(id::text||':'||clock_timestamp()::text) FROM source RETURNING id) INSERT INTO valorapesquisa.intelligence_reprocess_requests(organization_id,job_id,requested_by,request_type,status,correlation_id,metadata_json) SELECT @o,id,@user,'job','pending',@correlationId,'{}'::jsonb FROM created RETURNING job_id"""; using var db=connections.Create(); return await db.ExecuteScalarAsync<Guid?>(new CommandDefinition(sql,new{o,id,user,correlationId},cancellationToken:ct)); }
    public async Task<IReadOnlyList<IntelligenceProcessingJob>> ListJobsAsync(Guid o,IntelligenceJobFilter f,CancellationToken ct)
    { const string sql="""SELECT * FROM valorapesquisa.intelligence_processing_jobs WHERE organization_id=@o AND deleted_at IS NULL AND (@Status IS NULL OR status=@Status) AND (@SurveyId IS NULL OR survey_id=@SurveyId) AND (@ResponseId IS NULL OR response_id=@ResponseId) AND (@Trigger IS NULL OR trigger=@Trigger) ORDER BY created_at DESC OFFSET @offset LIMIT @PageSize"""; using var db=connections.Create(); return (await db.QueryAsync<IntelligenceProcessingJob>(new CommandDefinition(sql,new{o,f.Status,f.SurveyId,f.ResponseId,f.Trigger,offset=(Math.Max(1,f.Page)-1)*Math.Clamp(f.PageSize,1,100),PageSize=Math.Clamp(f.PageSize,1,100)},cancellationToken:ct))).AsList(); }
    public async Task<IntelligenceProcessingJob?> GetJobAsync(Guid o,Guid id,CancellationToken ct) { using var db=connections.Create(); return await db.QuerySingleOrDefaultAsync<IntelligenceProcessingJob>(new CommandDefinition("SELECT * FROM valorapesquisa.intelligence_processing_jobs WHERE organization_id=@o AND id=@id AND deleted_at IS NULL",new{o,id},cancellationToken:ct)); }
    public async Task<IReadOnlyList<IntelligenceStageRun>> ListStageRunsAsync(Guid o,Guid id,CancellationToken ct) { using var db=connections.Create(); var rows=await db.QueryAsync<StageRow>(new CommandDefinition("SELECT *,evidence_ids::text EvidenceJson FROM valorapesquisa.intelligence_pipeline_stage_runs WHERE organization_id=@o AND job_id=@id ORDER BY started_at",new{o,id},cancellationToken:ct)); return rows.Select(x=>new IntelligenceStageRun(x.Id,x.JobId,x.RunId,x.Stage,x.Status,x.Records,x.SufficientEvidence,x.Message,x.StartedAt,x.CompletedAt,x.DurationMs,x.ErrorCode,x.ErrorMessage,JsonSerializer.Deserialize<List<Guid>>(x.EvidenceJson)??[])).ToList(); }
    public async Task<IntelligenceProcessingSummary> GetSummaryAsync(Guid o,CancellationToken ct) { const string sql="""SELECT count(*) FILTER(WHERE status='pending')::int Pending,count(*) FILTER(WHERE status='running')::int Running,count(*) FILTER(WHERE status='completed' AND completed_at::date=current_date)::int CompletedToday,count(*) FILTER(WHERE status='failed')::int Failed,count(*) FILTER(WHERE status='retry_scheduled')::int RetryScheduled,count(*) FILTER(WHERE status='insufficient_evidence')::int InsufficientEvidence,coalesce(avg(extract(epoch FROM(completed_at-started_at))*1000) FILTER(WHERE completed_at IS NOT NULL),0) AverageDurationMs,(SELECT stage FROM valorapesquisa.intelligence_pipeline_stage_runs s WHERE s.organization_id=@o AND s.status='failed' GROUP BY stage ORDER BY count(*) DESC LIMIT 1) MostFailedStage,max(completed_at) FILTER(WHERE trigger LIKE '%response%') LastResponseProcessedAt,max(completed_at) FILTER(WHERE trigger LIKE '%diagnosis%') LastDiagnosisProcessedAt FROM valorapesquisa.intelligence_processing_jobs WHERE organization_id=@o AND deleted_at IS NULL"""; using var db=connections.Create(); return await db.QuerySingleAsync<IntelligenceProcessingSummary>(new CommandDefinition(sql,new{o},cancellationToken:ct)); }
    public Task LogStageAsync(Guid o,Guid job,Guid run,ProcessingStageResult s,string status,DateTime from,DateTime to,CancellationToken ct)=>Execute("INSERT INTO valorapesquisa.intelligence_pipeline_stage_runs(organization_id,job_id,run_id,stage,status,records,sufficient_evidence,message,started_at,completed_at,duration_ms,evidence_ids,metadata_json) VALUES(@o,@job,@run,@Stage,@status,@Records,@SufficientEvidence,@Message,@from,@to,@duration,CAST(@evidence AS jsonb),'{}'::jsonb)",new{o,job,run,s.Stage,s.Records,s.SufficientEvidence,s.Message,from,to,duration=(long)(to-from).TotalMilliseconds,evidence=JsonSerializer.Serialize(s.EvidenceIds)},ct);
    private async Task Execute(string sql,object args,CancellationToken ct) { using var db=connections.Create(); await db.ExecuteAsync(new CommandDefinition(sql,args,cancellationToken:ct)); }
    private sealed record StageRow(Guid Id,Guid JobId,Guid RunId,string Stage,string Status,int Records,bool SufficientEvidence,string Message,DateTime StartedAt,DateTime? CompletedAt,long? DurationMs,string? ErrorCode,string? ErrorMessage,string EvidenceJson);
}
