using Dapper;
using Valora.Application.Contracts;
using Valora.Application.Knowledge;
namespace Valora.Infrastructure.Repositories;
public sealed class KnowledgeRepository(IDbConnectionFactory factory):IKnowledgeRepository
{
 public async Task<KnowledgeSummary>SummaryAsync(Guid o,CancellationToken ct){using var c=factory.Create();return await c.QuerySingleAsync<KnowledgeSummary>(new CommandDefinition("""SELECT (SELECT count(*) FROM valorapesquisa.knowledge_articles WHERE organization_id=@o AND status='published') PublishedArticles,(SELECT count(*) FROM valorapesquisa.knowledge_articles WHERE organization_id=@o AND status='review') ArticlesInReview,(SELECT count(*) FROM valorapesquisa.playbooks WHERE organization_id=@o AND status='published') ActivePlaybooks,(SELECT count(*) FROM valorapesquisa.organizational_lessons WHERE organization_id=@o AND created_at>=now()-interval '30 days') RecentLessons,(SELECT count(*) FROM valorapesquisa.learning_paths WHERE organization_id=@o AND status<>'archived') LearningPaths,(SELECT count(*) FROM valorapesquisa.cognitive_dictionary_terms WHERE organization_id=@o AND status<>'archived') DictionaryTerms""",new{o},cancellationToken:ct));}
 public Task<IReadOnlyList<KnowledgeCategory>>CategoriesAsync(Guid o,CancellationToken ct)=>List<KnowledgeCategory>("SELECT id,name,code FROM valorapesquisa.knowledge_categories WHERE organization_id=@o OR organization_id IS NULL ORDER BY name",new{o},ct);
 public Task<IReadOnlyList<KnowledgeArticle>>ArticlesAsync(Guid o,string? query,string? status,Guid? categoryId,CancellationToken ct)=>List<KnowledgeArticle>("""SELECT a.id,a.category_id,c.name category,a.title,a.status,a.content,a.responsible_user_id,a.ai_assisted,a.current_version version,a.updated_at FROM valorapesquisa.knowledge_articles a JOIN valorapesquisa.knowledge_categories c ON c.id=a.category_id WHERE a.organization_id=@o AND (@status IS NULL OR a.status=@status) AND (@categoryId IS NULL OR a.category_id=@categoryId) AND (@query IS NULL OR a.search_vector @@ websearch_to_tsquery('portuguese',@query) OR a.title ILIKE '%'||@query||'%') ORDER BY a.updated_at DESC""",new{o,query=Clean(query),status=Clean(status),categoryId},ct);
 public async Task<KnowledgeArticle?>ArticleAsync(Guid o,Guid id,CancellationToken ct){using var c=factory.Create();return await c.QuerySingleOrDefaultAsync<KnowledgeArticle>(new CommandDefinition("SELECT a.id,a.category_id,c.name category,a.title,a.status,a.content,a.responsible_user_id,a.ai_assisted,a.current_version version,a.updated_at FROM valorapesquisa.knowledge_articles a JOIN valorapesquisa.knowledge_categories c ON c.id=a.category_id WHERE a.organization_id=@o AND a.id=@id",new{o,id},cancellationToken:ct));}
 public async Task<KnowledgeArticle>CreateArticleAsync(Guid o,CreateArticleRequest r,Guid actor,string correlation,CancellationToken ct){using var c=factory.Create();c.Open();using var tx=c.BeginTransaction();var id=await c.ExecuteScalarAsync<Guid>(new CommandDefinition("INSERT INTO valorapesquisa.knowledge_articles(organization_id,category_id,title,status,content,responsible_user_id,ai_assisted,created_by_user_id) SELECT @o,@CategoryId,@Title,'draft',@Content,@ResponsibleUserId,@AiAssisted,@actor WHERE EXISTS(SELECT 1 FROM valorapesquisa.knowledge_categories WHERE id=@CategoryId AND (organization_id=@o OR organization_id IS NULL)) RETURNING id",new{o,r.CategoryId,r.Title,r.Content,r.ResponsibleUserId,r.AiAssisted,actor},tx,cancellationToken:ct));if(id==Guid.Empty)throw new ArgumentException("Selecione uma categoria válida.");await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.knowledge_article_versions(organization_id,article_id,version,title,content,created_by_user_id) VALUES(@o,@id,1,@Title,@Content,@actor)",new{o,id,r.Title,r.Content,actor},tx,cancellationToken:ct));await Event(c,tx,o,"knowledge.article.created","article",id,actor,correlation,ct);tx.Commit();return (await ArticleAsync(o,id,ct))!;}
 public async Task<KnowledgeArticle>TransitionArticleAsync(Guid o,Guid id,string status,Guid actor,string correlation,CancellationToken ct){using var c=factory.Create();var changed=await c.ExecuteAsync(new CommandDefinition("UPDATE valorapesquisa.knowledge_articles SET status=@status,published_at=CASE WHEN @status='published' THEN now() ELSE published_at END,archived_at=CASE WHEN @status='archived' THEN now() ELSE archived_at END,updated_at=now() WHERE organization_id=@o AND id=@id",new{o,id,status},cancellationToken:ct));if(changed==0)throw new KeyNotFoundException("Artigo não encontrado.");await Event(c,null,o,$"knowledge.article.{(status=="review"?"submitted_review":status)}","article",id,actor,correlation,ct);return(await ArticleAsync(o,id,ct))!;}
 public Task<IReadOnlyList<KnowledgeArticleVersion>>VersionsAsync(Guid o,Guid articleId,CancellationToken ct)=>List<KnowledgeArticleVersion>("SELECT id,article_id,version,title,content,created_by_user_id,created_at FROM valorapesquisa.knowledge_article_versions WHERE organization_id=@o AND article_id=@articleId ORDER BY version DESC",new{o,articleId},ct);
 public Task<IReadOnlyList<Playbook>>PlaybooksAsync(Guid o,CancellationToken ct)=>List<Playbook>("SELECT p.id,p.title,p.objective,p.area,p.status,count(s.id)::int step_count,p.updated_at FROM valorapesquisa.playbooks p LEFT JOIN valorapesquisa.playbook_steps s ON s.playbook_id=p.id WHERE p.organization_id=@o GROUP BY p.id ORDER BY p.updated_at DESC",new{o},ct);
 public async Task<Playbook>CreatePlaybookAsync(Guid o,CreatePlaybookRequest r,Guid actor,string correlation,CancellationToken ct){using var c=factory.Create();c.Open();using var tx=c.BeginTransaction();var id=await c.ExecuteScalarAsync<Guid>(new CommandDefinition("INSERT INTO valorapesquisa.playbooks(organization_id,title,objective,area,status,created_by_user_id) VALUES(@o,@Title,@Objective,@Area,'draft',@actor) RETURNING id",new{o,r.Title,r.Objective,r.Area,actor},tx,cancellationToken:ct));foreach(var s in r.Steps.OrderBy(x=>x.Order))await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.playbook_steps(organization_id,playbook_id,step_order,description,suggested_owner) VALUES(@o,@id,@Order,@Description,@SuggestedOwner)",new{o,id,s.Order,s.Description,s.SuggestedOwner},tx,cancellationToken:ct));await Event(c,tx,o,"playbook.created","playbook",id,actor,correlation,ct);tx.Commit();return new(id,r.Title,r.Objective,r.Area,"draft",r.Steps.Count,DateTimeOffset.UtcNow);}
 public Task<IReadOnlyList<OrganizationalLesson>>LessonsAsync(Guid o,CancellationToken ct)=>List<OrganizationalLesson>("SELECT id,title,learning,origin_type,origin_reference,impact,evidence,status,is_critical critical,created_at FROM valorapesquisa.organizational_lessons WHERE organization_id=@o ORDER BY created_at DESC",new{o},ct);
 public async Task<OrganizationalLesson>CreateLessonAsync(Guid o,CreateLessonRequest r,Guid actor,string correlation,CancellationToken ct){using var c=factory.Create();var id=await c.ExecuteScalarAsync<Guid>(new CommandDefinition("INSERT INTO valorapesquisa.organizational_lessons(organization_id,title,learning,origin_type,origin_reference,impact,evidence,is_critical,created_by_user_id) VALUES(@o,@Title,@Learning,@OriginType,@OriginReference,@Impact,@Evidence,@Critical,@actor) RETURNING id",new{o,r.Title,r.Learning,r.OriginType,r.OriginReference,r.Impact,r.Evidence,r.Critical,actor},cancellationToken:ct));await Event(c,null,o,"lesson.created","lesson",id,actor,correlation,ct);return new(id,r.Title,r.Learning,r.OriginType,r.OriginReference,r.Impact,r.Evidence,"proposed",r.Critical,DateTimeOffset.UtcNow);}
 public Task<IReadOnlyList<LearningPath>>LearningPathsAsync(Guid o,CancellationToken ct)=>List<LearningPath>("SELECT p.id,p.title,p.objective,p.status,count(DISTINCT i.id)::int item_count,count(DISTINCT a.id)::int assignment_count,COALESCE(avg(pr.progress_percent),0)::int completion_percent FROM valorapesquisa.learning_paths p LEFT JOIN valorapesquisa.learning_path_items i ON i.learning_path_id=p.id LEFT JOIN valorapesquisa.learning_path_assignments a ON a.learning_path_id=p.id LEFT JOIN valorapesquisa.learning_progress pr ON pr.assignment_id=a.id WHERE p.organization_id=@o GROUP BY p.id ORDER BY p.updated_at DESC",new{o},ct);
 public async Task<LearningPath>CreateLearningPathAsync(Guid o,CreateLearningPathRequest r,Guid actor,string correlation,CancellationToken ct){using var c=factory.Create();c.Open();using var tx=c.BeginTransaction();var id=await c.ExecuteScalarAsync<Guid>(new CommandDefinition("INSERT INTO valorapesquisa.learning_paths(organization_id,title,objective,created_by_user_id) VALUES(@o,@Title,@Objective,@actor) RETURNING id",new{o,r.Title,r.Objective,actor},tx,cancellationToken:ct));var n=0;foreach(var a in r.ArticleIds.Distinct()){n+=await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.learning_path_items(organization_id,learning_path_id,item_order,item_type,article_id) SELECT @o,@id,@order,'article',@a WHERE EXISTS(SELECT 1 FROM valorapesquisa.knowledge_articles WHERE organization_id=@o AND id=@a)",new{o,id,order=n+1,a},tx,cancellationToken:ct));}if(n==0)throw new ArgumentException("Selecione artigos válidos para a trilha.");await Event(c,tx,o,"learning_path.created","learning_path",id,actor,correlation,ct);tx.Commit();return new(id,r.Title,r.Objective,"draft",n,0,0);}
 public Task<IReadOnlyList<CognitiveTerm>>TermsAsync(Guid o,CancellationToken ct)=>List<CognitiveTerm>("SELECT id,code,name,definition,category,methodological_use,status,updated_at FROM valorapesquisa.cognitive_dictionary_terms WHERE organization_id=@o ORDER BY name",new{o},ct);
 public async Task<CognitiveTerm>CreateTermAsync(Guid o,CreateCognitiveTermRequest r,Guid actor,string correlation,CancellationToken ct){using var c=factory.Create();try{var id=await c.ExecuteScalarAsync<Guid>(new CommandDefinition("INSERT INTO valorapesquisa.cognitive_dictionary_terms(organization_id,code,name,definition,category,methodological_use,status,created_by_user_id,traceability_reference) VALUES(@o,lower(@Code),@Name,@Definition,@Category,@MethodologicalUse,'draft',@actor,@correlation) RETURNING id",new{o,r.Code,r.Name,r.Definition,r.Category,r.MethodologicalUse,actor,correlation},cancellationToken:ct));await Event(c,null,o,"dictionary.term.created","dictionary_term",id,actor,correlation,ct);return new(id,r.Code.ToLowerInvariant(),r.Name,r.Definition,r.Category,r.MethodologicalUse,"draft",DateTimeOffset.UtcNow);}catch(Npgsql.PostgresException e)when(e.SqlState=="23505"){throw new ArgumentException("Já existe um conceito com este código nesta organização.");}}
 private async Task<IReadOnlyList<T>>List<T>(string sql,object args,CancellationToken ct){using var c=factory.Create();return(await c.QueryAsync<T>(new CommandDefinition(sql,args,cancellationToken:ct))).AsList();}
 private static string?Clean(string? x)=>string.IsNullOrWhiteSpace(x)?null:x.Trim();
 private static Task<int>Event(System.Data.IDbConnection c,System.Data.IDbTransaction? tx,Guid o,string type,string entity,Guid id,Guid actor,string correlation,CancellationToken ct)=>c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.knowledge_events(organization_id,event_type,entity_type,entity_id,actor_user_id,correlation_id) VALUES(@o,@type,@entity,@id,@actor,@correlation)",new{o,type,entity,id,actor,correlation},tx,cancellationToken:ct));
}
