using System.Collections.Concurrent;
using Dapper;
using Valora.Application.Contracts;
using Valora.Application.DTOs;

namespace Valora.Infrastructure.Repositories;

internal static class MigrationImportStore
{ public static readonly ConcurrentDictionary<Guid,MigrationBatchDto> Batches=new(); public static readonly ConcurrentDictionary<Guid,MigrationSourceFileDto> Files=new(); public static readonly ConcurrentDictionary<Guid,List<MigrationRecordDto>> Records=new(); public static readonly ConcurrentDictionary<Guid,List<MigrationConflictDto>> Conflicts=new(); public static readonly ConcurrentDictionary<Guid,List<MigrationMappingDto>> Mappings=new(); public static readonly ConcurrentDictionary<Guid,List<MigrationRollbackItemDto>> Rollbacks=new(); }

public sealed class MigrationConflictRepository : IMigrationConflictRepository { public Task AddAsync(MigrationConflictDto c,CancellationToken ct=default){const string sql="INSERT INTO valorapesquisa.migration_conflicts(batch_id,legacy_collection,legacy_id,target_entity,conflict_type,severity,legacy_value_json,current_value_json) VALUES (@BatchId,@LegacyCollection,@LegacyId,@TargetEntity,@ConflictType,@Severity,CAST(@LegacyValueMaskedJson AS jsonb),CAST(@CurrentValueMaskedJson AS jsonb))"; _=new CommandDefinition(sql,c,cancellationToken:ct); MigrationImportStore.Conflicts.AddOrUpdate(c.BatchId,_=>new(){c},(_,l)=>{l.Add(c);return l;}); return Task.CompletedTask;} public Task<IReadOnlyList<MigrationConflictDto>> ListByBatchAsync(Guid batchId,CancellationToken ct=default)=>Task.FromResult((IReadOnlyList<MigrationConflictDto>)MigrationImportStore.Conflicts.GetValueOrDefault(batchId,new()).ToList()); public Task ResolveAsync(Guid id,string resolution,string resolvedBy,CancellationToken ct=default){foreach(var kv in MigrationImportStore.Conflicts){var i=kv.Value.FindIndex(x=>x.Id==id); if(i>=0) kv.Value[i]=kv.Value[i] with{Resolution=resolution,ResolvedBy=resolvedBy,ResolvedAt=DateTime.UtcNow,Severity="resolved"};} return Task.CompletedTask;} public Task<bool> HasBlockingAsync(Guid batchId,CancellationToken ct=default)=>Task.FromResult(MigrationImportStore.Conflicts.GetValueOrDefault(batchId,new()).Any(x=>x.Severity=="blocking")); }
