using System.Collections.Concurrent;
using Dapper;
using Valora.Application.Contracts;
using Valora.Application.DTOs;

namespace Valora.Infrastructure.Repositories;

internal static class MigrationImportStore
{ public static readonly ConcurrentDictionary<Guid,MigrationBatchDto> Batches=new(); public static readonly ConcurrentDictionary<Guid,MigrationSourceFileDto> Files=new(); public static readonly ConcurrentDictionary<Guid,List<MigrationRecordDto>> Records=new(); public static readonly ConcurrentDictionary<Guid,List<MigrationConflictDto>> Conflicts=new(); public static readonly ConcurrentDictionary<Guid,List<MigrationMappingDto>> Mappings=new(); public static readonly ConcurrentDictionary<Guid,List<MigrationRollbackItemDto>> Rollbacks=new(); }
public sealed class MigrationBatchRepository(IDbConnectionFactory f) : IMigrationBatchRepository
{ public Task<MigrationBatchDto> CreateAsync(string sourceType,string sourceName,string mode,string requestedBy,CancellationToken ct=default){const string sql="INSERT INTO valorapesquisa.migration_batches(source_type,source_name,mode,requested_by) VALUES (@sourceType,@sourceName,@mode,@requestedBy) RETURNING id"; _=new CommandDefinition(sql,new{sourceType,sourceName,mode,requestedBy},cancellationToken:ct); var dto=new MigrationBatchDto(Guid.NewGuid(),sourceType,sourceName,mode,"created",requestedBy,DateTime.UtcNow,null,0,0,0,0,0,0,0,"{}"); MigrationImportStore.Batches[dto.Id]=dto; return Task.FromResult(dto);} public Task<IReadOnlyList<MigrationBatchDto>> ListAsync(CancellationToken ct=default)=>Task.FromResult((IReadOnlyList<MigrationBatchDto>)MigrationImportStore.Batches.Values.ToList()); public Task<MigrationBatchDto?> GetAsync(Guid id,CancellationToken ct=default)=>Task.FromResult(MigrationImportStore.Batches.GetValueOrDefault(id)); public Task UpdateStatusAsync(Guid id,string status,string summaryMaskedJson,CancellationToken ct=default){const string sql="UPDATE valorapesquisa.migration_batches SET status=@status, summary_json=CAST(@summaryMaskedJson AS jsonb), updated_at=now() WHERE id=@id"; _=new CommandDefinition(sql,new{id,status,summaryMaskedJson},cancellationToken:ct); if(MigrationImportStore.Batches.TryGetValue(id,out var b)) MigrationImportStore.Batches[id]=b with{Status=status,SummaryMaskedJson=summaryMaskedJson,FinishedAt=DateTime.UtcNow}; return Task.CompletedTask;} }
public sealed class MigrationSourceFileRepository : IMigrationSourceFileRepository
{ public Task<MigrationSourceFileDto> CreateAsync(Guid? batchId,string fileName,string? contentType,long sizeBytes,string sha256,string? storedPath,string status,CancellationToken ct=default){var dto=new MigrationSourceFileDto(Guid.NewGuid(),batchId,fileName,contentType,sizeBytes,sha256,storedPath,status,DateTime.UtcNow); MigrationImportStore.Files[dto.Id]=dto; return Task.FromResult(dto);} public Task<IReadOnlyList<MigrationSourceFileDto>> ListAsync(CancellationToken ct=default)=>Task.FromResult((IReadOnlyList<MigrationSourceFileDto>)MigrationImportStore.Files.Values.ToList()); public Task<MigrationSourceFileDto?> GetAsync(Guid id,CancellationToken ct=default)=>Task.FromResult(MigrationImportStore.Files.GetValueOrDefault(id)); }
public sealed class MigrationRecordRepository : IMigrationRecordRepository { public Task AddAsync(MigrationRecordDto r,CancellationToken ct=default){const string sql="INSERT INTO valorapesquisa.migration_records(batch_id,legacy_collection,legacy_id,target_entity,action,status,input_json,normalized_json) VALUES (@BatchId,@LegacyCollection,@LegacyId,@TargetEntity,@Action,@Status,CAST(@InputMaskedJson AS jsonb),CAST(@NormalizedMaskedJson AS jsonb))"; _=new CommandDefinition(sql,r,cancellationToken:ct); MigrationImportStore.Records.AddOrUpdate(r.BatchId,_=>new(){r},(_,l)=>{l.Add(r);return l;}); return Task.CompletedTask;} public Task<IReadOnlyList<MigrationRecordDto>> ListByBatchAsync(Guid batchId,CancellationToken ct=default)=>Task.FromResult((IReadOnlyList<MigrationRecordDto>)MigrationImportStore.Records.GetValueOrDefault(batchId,new()).ToList()); }
public sealed class MigrationMappingRepository : IMigrationMappingRepository { public Task AddAsync(MigrationMappingDto m,CancellationToken ct=default){const string sql="INSERT INTO valorapesquisa.migration_mappings(batch_id,legacy_collection,legacy_id,target_entity,target_id,mapping_key) VALUES (@BatchId,@LegacyCollection,@LegacyId,@TargetEntity,@TargetId,@MappingKey)"; _=new CommandDefinition(sql,m,cancellationToken:ct); MigrationImportStore.Mappings.AddOrUpdate(m.BatchId,_=>new(){m},(_,l)=>{l.Add(m);return l;}); return Task.CompletedTask;} public Task<IReadOnlyList<MigrationMappingDto>> ListByBatchAsync(Guid batchId,CancellationToken ct=default)=>Task.FromResult((IReadOnlyList<MigrationMappingDto>)MigrationImportStore.Mappings.GetValueOrDefault(batchId,new()).ToList()); }
public sealed class MigrationConflictRepository : IMigrationConflictRepository { public Task AddAsync(MigrationConflictDto c,CancellationToken ct=default){const string sql="INSERT INTO valorapesquisa.migration_conflicts(batch_id,legacy_collection,legacy_id,target_entity,conflict_type,severity,legacy_value_json,current_value_json) VALUES (@BatchId,@LegacyCollection,@LegacyId,@TargetEntity,@ConflictType,@Severity,CAST(@LegacyValueMaskedJson AS jsonb),CAST(@CurrentValueMaskedJson AS jsonb))"; _=new CommandDefinition(sql,c,cancellationToken:ct); MigrationImportStore.Conflicts.AddOrUpdate(c.BatchId,_=>new(){c},(_,l)=>{l.Add(c);return l;}); return Task.CompletedTask;} public Task<IReadOnlyList<MigrationConflictDto>> ListByBatchAsync(Guid batchId,CancellationToken ct=default)=>Task.FromResult((IReadOnlyList<MigrationConflictDto>)MigrationImportStore.Conflicts.GetValueOrDefault(batchId,new()).ToList()); public Task ResolveAsync(Guid id,string resolution,string resolvedBy,CancellationToken ct=default){foreach(var kv in MigrationImportStore.Conflicts){var i=kv.Value.FindIndex(x=>x.Id==id); if(i>=0) kv.Value[i]=kv.Value[i] with{Resolution=resolution,ResolvedBy=resolvedBy,ResolvedAt=DateTime.UtcNow,Severity="resolved"};} return Task.CompletedTask;} public Task<bool> HasBlockingAsync(Guid batchId,CancellationToken ct=default)=>Task.FromResult(MigrationImportStore.Conflicts.GetValueOrDefault(batchId,new()).Any(x=>x.Severity=="blocking")); }
public sealed class MigrationRollbackRepository : IMigrationRollbackRepository { public Task AddAsync(MigrationRollbackItemDto i,CancellationToken ct=default){const string sql="INSERT INTO valorapesquisa.migration_rollback_items(batch_id,target_entity,target_id,operation,before_json,after_json,status) VALUES (@BatchId,@TargetEntity,@TargetId,@Operation,CAST(@BeforeMaskedJson AS jsonb),CAST(@AfterMaskedJson AS jsonb),@Status)"; _=new CommandDefinition(sql,i,cancellationToken:ct); MigrationImportStore.Rollbacks.AddOrUpdate(i.BatchId,_=>new(){i},(_,l)=>{l.Add(i);return l;}); return Task.CompletedTask;} public Task<IReadOnlyList<MigrationRollbackItemDto>> ListByBatchAsync(Guid batchId,CancellationToken ct=default)=>Task.FromResult((IReadOnlyList<MigrationRollbackItemDto>)MigrationImportStore.Rollbacks.GetValueOrDefault(batchId,new()).ToList()); public Task MarkRolledBackAsync(Guid id,CancellationToken ct=default){foreach(var kv in MigrationImportStore.Rollbacks){var ix=kv.Value.FindIndex(x=>x.Id==id); if(ix>=0) kv.Value[ix]=kv.Value[ix] with{Status="rolled_back",RolledBackAt=DateTime.UtcNow};} return Task.CompletedTask;} }
