using Dapper;
using Valora.Application.Contracts;
using Valora.Application.OneOnOne;

namespace Valora.Infrastructure.Repositories;

public sealed class OneOnOneRepository(IDbConnectionFactory db) : IOneOnOneRepository
{
    const string SessionProjection="s.id,s.organization_id OrganizationId,s.leader_user_id LeaderUserId,s.participant_user_id ParticipantUserId,coalesce(l.name,'Liderança') LeaderName,coalesce(p.name,'Participante') ParticipantName,s.diagnostic_id DiagnosticId,s.result_id ResultId,s.title,s.status,s.scheduled_at ScheduledAt,s.started_at StartedAt,s.completed_at CompletedAt,s.summary,s.evidence_summary EvidenceSummary,s.ai_summary AiSummary,s.created_by_user_id CreatedByUserId,s.created_at CreatedAt,(SELECT count(*) FROM valorapesquisa.one_on_one_commitments c WHERE c.session_id=s.id AND c.deleted_at IS NULL AND c.status IN ('pending','in_progress','overdue')) PendingCommitments";
    public async Task<IReadOnlyList<OneOnOneSessionDto>> List(Guid o,CancellationToken ct){using var c=db.Create();return(await c.QueryAsync<OneOnOneSessionDto>(new CommandDefinition($"SELECT {SessionProjection} FROM valorapesquisa.one_on_one_sessions s LEFT JOIN valorapesquisa.users l ON l.id=s.leader_user_id LEFT JOIN valorapesquisa.users p ON p.id=s.participant_user_id WHERE s.organization_id=@o AND s.deleted_at IS NULL ORDER BY s.scheduled_at DESC NULLS LAST,s.created_at DESC",new{o},cancellationToken:ct))).AsList();}
    public async Task<OneOnOneDetailsDto?> Get(Guid o,Guid id,Guid viewer,bool privateAccess,CancellationToken ct){using var c=db.Create();var s=await c.QuerySingleOrDefaultAsync<OneOnOneSessionDto>(new CommandDefinition($"SELECT {SessionProjection} FROM valorapesquisa.one_on_one_sessions s LEFT JOIN valorapesquisa.users l ON l.id=s.leader_user_id LEFT JOIN valorapesquisa.users p ON p.id=s.participant_user_id WHERE s.organization_id=@o AND s.id=@id AND s.deleted_at IS NULL",new{o,id},cancellationToken:ct));if(s is null)return null;var a=(await c.QueryAsync<OneOnOneAgendaItemDto>(new CommandDefinition("SELECT id,session_id SessionId,title,description,source_type SourceType,evidence,sort_order SortOrder,discussed FROM valorapesquisa.one_on_one_agenda_items WHERE session_id=@id AND deleted_at IS NULL ORDER BY sort_order",new{id},cancellationToken:ct))).AsList();var k=(await Commitments(c,o,id,ct)).AsList();var f=(await c.QueryAsync<OneOnOneFeedbackDto>(new CommandDefinition("SELECT id,session_id SessionId,from_user_id FromUserId,to_user_id ToUserId,feedback,evidence,created_at CreatedAt FROM valorapesquisa.one_on_one_feedbacks WHERE organization_id=@o AND session_id=@id AND deleted_at IS NULL ORDER BY created_at DESC",new{o,id},cancellationToken:ct))).AsList();var n=(await c.QueryAsync<PrivateNoteDto>(new CommandDefinition("SELECT id,session_id SessionId,created_by_user_id CreatedByUserId,note,created_at CreatedAt FROM valorapesquisa.one_on_one_private_notes WHERE organization_id=@o AND session_id=@id AND deleted_at IS NULL AND (created_by_user_id=@viewer OR @privateAccess)",new{o,id,viewer,privateAccess},cancellationToken:ct))).AsList();var ai=(await Suggestions(c,o,id,ct)).AsList();return new(s,a,k,f,n,ai);}
    public async Task<OneOnOneDashboardDto> Dashboard(Guid o,Guid viewer,bool privateAccess,CancellationToken ct){var all=await List(o,ct);using var c=db.Create();var now=DateTime.UtcNow;var commitments=(await Commitments(c,o,null,ct)).AsList();var leaders=(await c.QueryAsync<LeadershipProfileDto>(new CommandDefinition("SELECT lp.id,lp.user_id UserId,coalesce(u.name,'Liderança') DisplayName,lp.role_title RoleTitle,lp.development_summary DevelopmentSummary,lp.last_session_at LastSessionAt,(SELECT count(*) FROM valorapesquisa.one_on_one_commitments k JOIN valorapesquisa.one_on_one_sessions s ON s.id=k.session_id WHERE s.organization_id=@o AND s.leader_user_id=lp.user_id AND k.status IN('pending','in_progress','overdue') AND k.deleted_at IS NULL) PendingCommitments FROM valorapesquisa.leadership_profiles lp LEFT JOIN valorapesquisa.users u ON u.id=lp.user_id WHERE lp.organization_id=@o AND lp.deleted_at IS NULL",new{o},cancellationToken:ct))).AsList();var ai=(await Suggestions(c,o,null,ct)).AsList();return new(all.Where(x=>x.ScheduledAt>=now&&x.Status=="scheduled").Take(8).ToArray(),all.Where(x=>x.ScheduledAt<now&&x.Status=="scheduled").ToArray(),commitments,leaders,ai);}
    public async Task<Guid> Create(Guid o,Guid u,CreateOneOnOneSessionRequest r,CancellationToken ct){var id=Guid.NewGuid();using var c=db.Create();await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.one_on_one_sessions(id,organization_id,leader_user_id,participant_user_id,diagnostic_id,result_id,title,status,scheduled_at,evidence_summary,created_by_user_id) VALUES(@id,@o,@LeaderUserId,@ParticipantUserId,@DiagnosticId,@ResultId,@Title,CASE WHEN @ScheduledAt IS NULL THEN 'draft' ELSE 'scheduled' END,@ScheduledAt,coalesce(@EvidenceSummary,''),@u); INSERT INTO valorapesquisa.leadership_profiles(organization_id,user_id,last_session_at) VALUES(@o,@LeaderUserId,@ScheduledAt) ON CONFLICT(organization_id,user_id) DO UPDATE SET last_session_at=excluded.last_session_at,updated_at=now()",new{id,o,u,r.LeaderUserId,r.ParticipantUserId,r.DiagnosticId,r.ResultId,r.Title,r.ScheduledAt,r.EvidenceSummary},cancellationToken:ct));return id;}
    public async Task Schedule(Guid o,Guid id,DateTime at,CancellationToken ct){using var c=db.Create();var n=await c.ExecuteAsync(new CommandDefinition("UPDATE valorapesquisa.one_on_one_sessions SET status='scheduled',scheduled_at=@at,updated_at=now() WHERE organization_id=@o AND id=@id AND deleted_at IS NULL AND status='draft'",new{o,id,at},cancellationToken:ct));if(n==0)throw new InvalidOperationException("Sessão não encontrada ou não pode ser agendada.");}
    public async Task Complete(Guid o,Guid id,Guid u,CompleteOneOnOneSessionRequest r,CancellationToken ct){using var c=db.Create();c.Open();using var tx=c.BeginTransaction();var leader=await c.QuerySingleOrDefaultAsync<Guid?>("UPDATE valorapesquisa.one_on_one_sessions SET status='completed',completed_at=now(),summary=@Summary,evidence_summary=@EvidenceSummary,updated_at=now() WHERE organization_id=@o AND id=@id AND deleted_at IS NULL AND status IN('draft','scheduled') RETURNING leader_user_id",new{o,id,r.Summary,r.EvidenceSummary},tx)??throw new InvalidOperationException("Sessão não encontrada ou já finalizada.");await c.ExecuteAsync("INSERT INTO valorapesquisa.leadership_profiles(organization_id,user_id,last_session_at,development_summary) VALUES(@o,@leader,now(),@Summary) ON CONFLICT(organization_id,user_id) DO UPDATE SET last_session_at=now(),development_summary=excluded.development_summary,updated_at=now(); INSERT INTO valorapesquisa.leadership_development_snapshots(organization_id,leader_user_id,session_id,summary,evidence_summary,created_by_user_id) VALUES(@o,@leader,@id,@Summary,@EvidenceSummary,@u); INSERT INTO valorapesquisa.journey_events(organization_id,event_type,title,description,source_type,source_id,impact_level,evidence_summary,created_by_user_id) VALUES(@o,'one_on_one_completed','One-on-One concluído',@Summary,'one_on_one',@id,'medium',@EvidenceSummary,@u)",new{o,leader,id,u,r.Summary,r.EvidenceSummary},tx);tx.Commit();}
    public async Task AddAgenda(Guid o,Guid id,IReadOnlyList<OneOnOneAgendaItemDto> items,CancellationToken ct){using var c=db.Create();foreach(var x in items)await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.one_on_one_agenda_items(id,organization_id,session_id,title,description,source_type,evidence,sort_order) SELECT @Id,@o,@id,@Title,@Description,@SourceType,@Evidence,@SortOrder WHERE EXISTS(SELECT 1 FROM valorapesquisa.one_on_one_sessions WHERE id=@id AND organization_id=@o AND deleted_at IS NULL)",new{x.Id,o,id,x.Title,x.Description,x.SourceType,x.Evidence,x.SortOrder},cancellationToken:ct));}
    public async Task<Guid> AddCommitment(Guid o,Guid u,Guid session,Guid responsible,string title,string? description,DateTime due,bool action,CancellationToken ct){var id=Guid.NewGuid();using var c=db.Create();c.Open();using var tx=c.BeginTransaction();Guid? item=null;if(action){var plan=Guid.NewGuid();item=Guid.NewGuid();await c.ExecuteAsync("INSERT INTO valorapesquisa.action_plans(id,organization_id,title,summary,origin_type,origin_id,status,priority,owner_user_id,created_by_user_id,due_at,evidence_summary,expected_outcome) VALUES(@plan,@o,@title,@description,'one_on_one',@session,'in_execution','medium',@responsible,@u,@due,'Compromisso registrado em One-on-One','Acompanhamento no prazo'); INSERT INTO valorapesquisa.action_items(id,organization_id,action_plan_id,title,description,origin_type,origin_id,status,priority,responsible_user_id,due_at,evidence_summary,expected_outcome) VALUES(@item,@o,@plan,@title,@description,'one_on_one',@id,'pending','medium',@responsible,@due,'Compromisso registrado em One-on-One','Entrega acordada')",new{plan,item,o,title,description,session,responsible,u,due,id},tx);}await c.ExecuteAsync("INSERT INTO valorapesquisa.one_on_one_commitments(id,organization_id,session_id,responsible_user_id,title,description,due_at,status,action_item_id,created_by_user_id) VALUES(@id,@o,@session,@responsible,@title,@description,@due,'pending',@item,@u)",new{id,o,session,responsible,title,description,due,item,u},tx);tx.Commit();return id;}
    public async Task AddFeedback(Guid o,Guid u,Guid id,Guid to,string feedback,string evidence,CancellationToken ct){using var c=db.Create();await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.one_on_one_feedbacks(organization_id,session_id,from_user_id,to_user_id,feedback,evidence) VALUES(@o,@id,@u,@to,@feedback,@evidence)",new{o,id,u,to,feedback,evidence},cancellationToken:ct));}
    public async Task AddPrivateNote(Guid o,Guid u,Guid id,string note,CancellationToken ct){if(string.IsNullOrWhiteSpace(note))throw new ArgumentException("A nota não pode estar vazia.");using var c=db.Create();await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.one_on_one_private_notes(organization_id,session_id,created_by_user_id,note) VALUES(@o,@id,@u,@note)",new{o,id,u,note=note.Trim()},cancellationToken:ct));}
    static Task<IEnumerable<OneOnOneCommitmentDto>> Commitments(System.Data.IDbConnection c,Guid o,Guid? id,CancellationToken ct)=>c.QueryAsync<OneOnOneCommitmentDto>(new CommandDefinition("SELECT k.id,k.session_id SessionId,k.responsible_user_id ResponsibleUserId,k.title,k.description,k.due_at DueAt,CASE WHEN k.status IN('pending','in_progress') AND k.due_at<now() THEN 'overdue' ELSE k.status END status,k.action_item_id ActionItemId,k.created_at CreatedAt FROM valorapesquisa.one_on_one_commitments k JOIN valorapesquisa.one_on_one_sessions s ON s.id=k.session_id WHERE k.organization_id=@o AND (@id IS NULL OR k.session_id=@id) AND k.deleted_at IS NULL ORDER BY k.due_at",new{o,id},cancellationToken:ct));
    static Task<IEnumerable<AiSuggestionDto>> Suggestions(System.Data.IDbConnection c,Guid o,Guid? id,CancellationToken ct)=>c.QueryAsync<AiSuggestionDto>(new CommandDefinition("SELECT id,session_id SessionId,leader_user_id LeaderUserId,suggestion_type SuggestionType,observation,evidence,impact,recommendation,limitation,status,created_at CreatedAt FROM valorapesquisa.one_on_one_ai_suggestions WHERE organization_id=@o AND (@id IS NULL OR session_id=@id) AND deleted_at IS NULL AND status IN('proposed','accepted') ORDER BY created_at DESC LIMIT 20",new{o,id},cancellationToken:ct));
}

public sealed class LeadershipProfileRepository(IDbConnectionFactory db):ILeadershipProfileRepository
{public async Task<IReadOnlyList<LeadershipProfileDto>>List(Guid o,CancellationToken ct){using var c=db.Create();return(await c.QueryAsync<LeadershipProfileDto>(new CommandDefinition("SELECT lp.id,lp.user_id UserId,coalesce(u.name,'Liderança') DisplayName,lp.role_title RoleTitle,lp.development_summary DevelopmentSummary,lp.last_session_at LastSessionAt,0 PendingCommitments FROM valorapesquisa.leadership_profiles lp LEFT JOIN valorapesquisa.users u ON u.id=lp.user_id WHERE lp.organization_id=@o AND lp.deleted_at IS NULL ORDER BY u.name",new{o},cancellationToken:ct))).AsList();}public async Task<LeadershipProfileDto?>Get(Guid o,Guid id,CancellationToken ct){using var c=db.Create();return await c.QuerySingleOrDefaultAsync<LeadershipProfileDto>(new CommandDefinition("SELECT lp.id,lp.user_id UserId,coalesce(u.name,'Liderança') DisplayName,lp.role_title RoleTitle,lp.development_summary DevelopmentSummary,lp.last_session_at LastSessionAt,(SELECT count(*) FROM valorapesquisa.one_on_one_commitments k JOIN valorapesquisa.one_on_one_sessions s ON s.id=k.session_id WHERE s.leader_user_id=@id AND k.status IN('pending','in_progress','overdue')) PendingCommitments FROM valorapesquisa.leadership_profiles lp LEFT JOIN valorapesquisa.users u ON u.id=lp.user_id WHERE lp.organization_id=@o AND lp.user_id=@id AND lp.deleted_at IS NULL",new{o,id},cancellationToken:ct));}}
public sealed class LeadershipDevelopmentRepository(IDbConnectionFactory db):ILeadershipDevelopmentRepository
{public async Task<Guid>Snapshot(Guid o,Guid leader,Guid? session,Guid u,string evidence,CancellationToken ct){var id=Guid.NewGuid();using var c=db.Create();await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.leadership_development_snapshots(id,organization_id,leader_user_id,session_id,summary,evidence_summary,created_by_user_id) VALUES(@id,@o,@leader,@session,'Snapshot de desenvolvimento baseado em acompanhamento',@evidence,@u)",new{id,o,leader,session,evidence,u},cancellationToken:ct));return id;}}
