using Dapper;
using Valora.Application.Contracts;
using Valora.Application.OrganizationalArchitecture;

namespace Valora.Infrastructure.Repositories;

public sealed class OrganizationalArchitectureRepository(IDbConnectionFactory factory) : IOrganizationalArchitectureRepository
{
 public async Task<ArchitectureSummary> SummaryAsync(Guid o,CancellationToken ct){using var c=factory.Create();const string q="""SELECT (SELECT count(*) FROM valorapesquisa.organization_units WHERE organization_id=@o AND status='active') Units,(SELECT count(*) FROM valorapesquisa.business_processes WHERE organization_id=@o AND status='active') ActiveProcesses,(SELECT count(*) FROM valorapesquisa.business_processes WHERE organization_id=@o AND status='active' AND criticality='critical') CriticalProcesses,(SELECT count(*) FROM valorapesquisa.business_processes p WHERE p.organization_id=@o AND p.status='active' AND NOT EXISTS(SELECT 1 FROM valorapesquisa.responsibility_matrix_items r WHERE r.organization_id=p.organization_id AND r.process_id=p.id AND r.status='active' AND r.responsibility_type='Responsible')) UnownedResponsibilities,(SELECT count(*) FROM (SELECT responsible_person_id FROM valorapesquisa.decision_rights WHERE organization_id=@o AND status='active' GROUP BY responsible_person_id HAVING count(*)>=5)x) ConcentratedDecisions,(SELECT count(*) FROM valorapesquisa.organizational_dependencies WHERE organization_id=@o AND status='active' AND criticality='critical' AND NULLIF(trim(mitigation_plan),'') IS NULL) CriticalDependencies,(SELECT count(*) FROM valorapesquisa.architecture_risk_findings WHERE organization_id=@o AND status='open') OpenRisks""";var x=await c.QuerySingleAsync<Counts>(new CommandDefinition(q,new{o},cancellationToken:ct));var score=Math.Max(0,100-x.UnownedResponsibilities*8-x.CriticalDependencies*10-x.OpenRisks*5-x.ConcentratedDecisions*8);return new(x.Units,x.ActiveProcesses,x.CriticalProcesses,x.UnownedResponsibilities,x.ConcentratedDecisions,x.CriticalDependencies,x.OpenRisks,score);}
 public Task<IReadOnlyList<ArchitectureUnit>> UnitsAsync(Guid o,CancellationToken ct)=>List<ArchitectureUnit>("SELECT id,organization_id,parent_unit_id,name,unit_type,status,owner_user_id FROM valorapesquisa.organization_units WHERE organization_id=@o ORDER BY name",o,ct);
 public async Task<ArchitectureUnit>CreateUnitAsync(Guid o,CreateUnitRequest r,string correlation,CancellationToken ct){using var c=factory.Create();var id=await c.ExecuteScalarAsync<Guid>(new CommandDefinition("INSERT INTO valorapesquisa.organization_units(organization_id,parent_unit_id,name,unit_type,status,owner_user_id) VALUES(@o,@ParentUnitId,@Name,@UnitType,@Status,@OwnerUserId) RETURNING id",new{o,r.ParentUnitId,r.Name,r.UnitType,r.Status,r.OwnerUserId},cancellationToken:ct));await Event(c,o,"architecture.unit.created","unit",id,correlation,ct);return new(id,o,r.ParentUnitId,r.Name,r.UnitType,r.Status,r.OwnerUserId);}
 public Task<IReadOnlyList<ArchitecturePosition>>PositionsAsync(Guid o,CancellationToken ct)=>List<ArchitecturePosition>("SELECT id,organization_id,unit_id,title,status FROM valorapesquisa.organization_positions WHERE organization_id=@o ORDER BY title",o,ct);
 public async Task<ArchitecturePosition>CreatePositionAsync(Guid o,CreatePositionRequest r,string correlation,CancellationToken ct){using var c=factory.Create();var id=await c.ExecuteScalarAsync<Guid>(new CommandDefinition("INSERT INTO valorapesquisa.organization_positions(organization_id,unit_id,title) SELECT @o,@UnitId,@Title WHERE EXISTS(SELECT 1 FROM valorapesquisa.organization_units WHERE organization_id=@o AND id=@UnitId AND status='active') RETURNING id",new{o,r.UnitId,r.Title},cancellationToken:ct));if(id==Guid.Empty)throw new ArgumentException("Selecione uma unidade ativa.");await Event(c,o,"architecture.position.created","position",id,correlation,ct);return new(id,o,r.UnitId,r.Title,"active");}
 public Task<IReadOnlyList<ResponsibilityItem>>ResponsibilitiesAsync(Guid o,CancellationToken ct)=>List<ResponsibilityItem>("SELECT id,process_id,person_profile_id,unit_id,responsibility_type,status FROM valorapesquisa.responsibility_matrix_items WHERE organization_id=@o ORDER BY created_at DESC",o,ct);
 public async Task<ResponsibilityItem>CreateResponsibilityAsync(Guid o,CreateResponsibilityRequest r,string correlation,CancellationToken ct){using var c=factory.Create();var id=await c.ExecuteScalarAsync<Guid>(new CommandDefinition("INSERT INTO valorapesquisa.responsibility_matrix_items(organization_id,matrix_id,process_id,person_profile_id,unit_id,responsibility_type) VALUES(@o,@MatrixId,@ProcessId,@PersonProfileId,@UnitId,@ResponsibilityType) RETURNING id",new{o,r.MatrixId,r.ProcessId,r.PersonProfileId,r.UnitId,r.ResponsibilityType},cancellationToken:ct));await Event(c,o,"architecture.responsibility.assigned","responsibility",id,correlation,ct);return new(id,r.ProcessId,r.PersonProfileId,r.UnitId,r.ResponsibilityType,"active");}
 public Task<IReadOnlyList<BusinessProcess>>ProcessesAsync(Guid o,CancellationToken ct)=>List<BusinessProcess>("SELECT id,organization_id,unit_id,name,owner_person_id,status,criticality,indicator_reference,completeness_status FROM valorapesquisa.business_processes WHERE organization_id=@o ORDER BY name",o,ct);
 public async Task<BusinessProcess>CreateProcessAsync(Guid o,CreateProcessRequest r,string correlation,CancellationToken ct){using var c=factory.Create();var id=await c.ExecuteScalarAsync<Guid>(new CommandDefinition("INSERT INTO valorapesquisa.business_processes(organization_id,unit_id,name,owner_person_id,criticality,indicator_reference) VALUES(@o,@UnitId,@Name,@OwnerPersonId,@Criticality,@IndicatorReference) RETURNING id",new{o,r.UnitId,r.Name,r.OwnerPersonId,r.Criticality,r.IndicatorReference},cancellationToken:ct));await Event(c,o,"architecture.process.created","process",id,correlation,ct);return new(id,o,r.UnitId,r.Name,r.OwnerPersonId,"active",r.Criticality,r.IndicatorReference,"incomplete");}
 public Task<IReadOnlyList<DecisionRight>>DecisionRightsAsync(Guid o,CancellationToken ct)=>List<DecisionRight>("SELECT id,scope,decision_type,responsible_person_id,approver_person_id,decision_limit,status FROM valorapesquisa.decision_rights WHERE organization_id=@o ORDER BY scope",o,ct);
 public async Task<DecisionRight>CreateDecisionRightAsync(Guid o,CreateDecisionRightRequest r,string correlation,CancellationToken ct){using var c=factory.Create();var id=await c.ExecuteScalarAsync<Guid>(new CommandDefinition("INSERT INTO valorapesquisa.decision_rights(organization_id,scope,decision_type,responsible_person_id,approver_person_id,decision_limit) VALUES(@o,@Scope,@DecisionType,@ResponsiblePersonId,@ApproverPersonId,@DecisionLimit) RETURNING id",new{o,r.Scope,r.DecisionType,r.ResponsiblePersonId,r.ApproverPersonId,r.DecisionLimit},cancellationToken:ct));await Event(c,o,"architecture.decision_right.created","decision_right",id,correlation,ct);return new(id,r.Scope,r.DecisionType,r.ResponsiblePersonId,r.ApproverPersonId,r.DecisionLimit,"active");}
 public Task<IReadOnlyList<OrganizationalDependency>>DependenciesAsync(Guid o,CancellationToken ct)=>List<OrganizationalDependency>("SELECT id,source_unit_id,target_unit_id,source_process_id,target_process_id,dependency_type,impact,criticality,mitigation_plan,status FROM valorapesquisa.organizational_dependencies WHERE organization_id=@o ORDER BY criticality DESC",o,ct);
 public async Task<OrganizationalDependency>CreateDependencyAsync(Guid o,CreateDependencyRequest r,string correlation,CancellationToken ct){if(r.SourceUnitId is null&&r.SourceProcessId is null||r.TargetUnitId is null&&r.TargetProcessId is null)throw new ArgumentException("Informe origem e destino da dependência.");using var c=factory.Create();var id=await c.ExecuteScalarAsync<Guid>(new CommandDefinition("INSERT INTO valorapesquisa.organizational_dependencies(organization_id,source_unit_id,target_unit_id,source_process_id,target_process_id,dependency_type,impact,criticality,mitigation_plan) VALUES(@o,@SourceUnitId,@TargetUnitId,@SourceProcessId,@TargetProcessId,@DependencyType,@Impact,@Criticality,@MitigationPlan) RETURNING id",new{o,r.SourceUnitId,r.TargetUnitId,r.SourceProcessId,r.TargetProcessId,r.DependencyType,r.Impact,r.Criticality,r.MitigationPlan},cancellationToken:ct));await Event(c,o,"architecture.dependency.created","dependency",id,correlation,ct);return new(id,r.SourceUnitId,r.TargetUnitId,r.SourceProcessId,r.TargetProcessId,r.DependencyType,r.Impact,r.Criticality,r.MitigationPlan,"active");}
 public Task<IReadOnlyList<ArchitectureRisk>>RisksAsync(Guid o,CancellationToken ct)=>List<ArchitectureRisk>("SELECT id,risk_type,title,probable_cause,impact,evidence,recommended_action,severity,status,detected_at FROM valorapesquisa.architecture_risk_findings WHERE organization_id=@o ORDER BY detected_at DESC",o,ct);
 public async Task<ArchitectureSnapshot>SnapshotAsync(Guid o,Guid? actor,string correlation,CancellationToken ct){var summary=await SummaryAsync(o,ct);using var c=factory.Create();var id=await c.ExecuteScalarAsync<Guid>(new CommandDefinition("INSERT INTO valorapesquisa.organizational_architecture_snapshots(organization_id,maturity_score,payload,created_by_user_id,correlation_id) VALUES(@o,@score,CAST(@payload AS jsonb),@actor,@correlation) RETURNING id",new{o,score=summary.MaturityScore,payload=System.Text.Json.JsonSerializer.Serialize(summary),actor,correlation},cancellationToken:ct));await Event(c,o,"architecture.snapshot.created","snapshot",id,correlation,ct);return new(id,summary.MaturityScore,DateTimeOffset.UtcNow,correlation);}
 private async Task<IReadOnlyList<T>>List<T>(string sql,Guid o,CancellationToken ct){using var c=factory.Create();return(await c.QueryAsync<T>(new CommandDefinition(sql,new{o},cancellationToken:ct))).AsList();}
 private static async Task Event(System.Data.IDbConnection c,Guid o,string type,string entity,Guid id,string correlation,CancellationToken ct)=>await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.architecture_change_events(organization_id,event_type,entity_type,entity_id,correlation_id) VALUES(@o,@type,@entity,@id,@correlation)",new{o,type,entity,id,correlation},cancellationToken:ct));
 private sealed record Counts(int Units,int ActiveProcesses,int CriticalProcesses,int UnownedResponsibilities,int ConcentratedDecisions,int CriticalDependencies,int OpenRisks);
}
