using Dapper;
using Microsoft.Extensions.Logging;
using Valora.Application.Contracts;
using Valora.Application.DTOs;
namespace Valora.Infrastructure.Repositories;
public sealed class PlanRepository(IDbConnectionFactory f, ILogger<PlanRepository> logger):IPlanRepository
{
 public async Task<IReadOnlyList<PlanDto>> GetPublicPlansAsync(){try{using var c=f.Create(); var plans=(await c.QueryAsync<dynamic>("SELECT id,code,name,badge,monthly_price,annual_price,price_complement,display_order FROM valorapesquisa.plans WHERE visible_on_public_pricing=true AND status='active' ORDER BY display_order")).ToList(); var result=new List<PlanDto>(); foreach(var p in plans) result.Add(await Hydrate((Guid)p.id,(string)p.code,p)); return result;}catch(Exception ex){logger.LogError(ex,"Erro ao listar planos públicos.");throw;}}
 public async Task<PlanDto?> GetByIdAsync(string id){try{using var c=f.Create(); var p=await c.QuerySingleOrDefaultAsync<dynamic>("SELECT id,code,name,badge,monthly_price,annual_price,price_complement,display_order FROM valorapesquisa.plans WHERE code=@id",new{id}); return p is null?null:await Hydrate((Guid)p.id,(string)p.code,p);}catch(Exception ex){logger.LogError(ex,"Erro ao buscar plano. PlanId={PlanId}",id);throw;}}
 async Task<PlanDto> Hydrate(Guid planId,string code,dynamic p){try{using var c=f.Create(); var limitsRow=await c.QuerySingleOrDefaultAsync<dynamic>("SELECT active_surveys,responses_per_month,users,managers,forms,public_links,email_invites_per_month,storage_mb FROM valorapesquisa.plan_limits WHERE plan_id=@planId",new{planId}); var limits = limitsRow is null ? new Dictionary<string,int>() : new Dictionary<string,int>{{"active_surveys",(int)limitsRow.active_surveys},{"responses_per_month",(int)limitsRow.responses_per_month},{"users",(int)limitsRow.users},{"managers",(int)limitsRow.managers},{"forms",(int)limitsRow.forms},{"public_links",(int)limitsRow.public_links},{"email_invites_per_month",(int)limitsRow.email_invites_per_month},{"storage_mb",(int)limitsRow.storage_mb}}; var caps=(await c.QueryAsync<(string capability_code,bool enabled)>("SELECT capability_code,enabled FROM valorapesquisa.plan_capabilities WHERE plan_id=@planId",new{planId})).ToDictionary(x=>x.capability_code,x=>x.enabled?"enabled":"disabled"); var monthly=(decimal)p.monthly_price; var annual=(decimal)p.annual_price; var priceLabel=monthly==0 && annual==0?"Sob consulta":monthly.ToString("0.##"); return new(code,(string)p.name,(string?)p.badge,priceLabel,(string?)p.price_complement,(int)p.display_order,limits,caps);}catch(Exception ex){logger.LogError(ex,"Erro ao hidratar limites do plano. PlanId={PlanId}",code);throw;}}
 public async Task<string?> GetCurrentPlanIdAsync(Guid organizationId){try{using var c=f.Create(); return await c.ExecuteScalarAsync<string?>("SELECT p.code FROM valorapesquisa.subscriptions s JOIN valorapesquisa.plans p ON p.id=s.plan_id WHERE s.organization_id=@organizationId AND s.status='active' ORDER BY s.created_at DESC LIMIT 1",new{organizationId});}catch(Exception ex){logger.LogError(ex,"Erro ao buscar plano atual. OrganizationId={OrganizationId}",organizationId);throw;}}
 public async Task CreateSubscriptionAsync(Guid organizationId,string planId){try{using var c=f.Create(); await c.ExecuteAsync("INSERT INTO valorapesquisa.subscriptions(organization_id,plan_id) SELECT @organizationId,id FROM valorapesquisa.plans WHERE code=@planId ON CONFLICT (organization_id) DO UPDATE SET plan_id=EXCLUDED.plan_id,status='active',updated_at=now()",new{organizationId,planId});}catch(Exception ex){logger.LogError(ex,"Erro ao criar assinatura. OrganizationId={OrganizationId} PlanId={PlanId}",organizationId,planId);throw;}}
}
