using Dapper;
using Microsoft.Extensions.Logging;
using Valora.Application.Contracts;
using Valora.Application.DTOs;
namespace Valora.Infrastructure.Repositories;
public sealed class PlanRepository(IDbConnectionFactory f, ILogger<PlanRepository> logger):IPlanRepository
{
 public async Task<IReadOnlyList<PlanDto>> GetPublicPlansAsync(){try{using var c=f.Create(); var plans=(await c.QueryAsync<dynamic>("SELECT * FROM valorapesquisa.plans WHERE visible_on_public_pricing=true AND status='active' ORDER BY display_order")).ToList(); var result=new List<PlanDto>(); foreach(var p in plans) result.Add(await Hydrate((string)p.id,p)); return result;}catch(Exception ex){logger.LogError(ex,"Erro ao listar planos públicos.");throw;}}
 public async Task<PlanDto?> GetByIdAsync(string id){try{using var c=f.Create(); var p=await c.QuerySingleOrDefaultAsync<dynamic>("SELECT * FROM valorapesquisa.plans WHERE id=@id",new{id}); return p is null?null:await Hydrate(id,p);}catch(Exception ex){logger.LogError(ex,"Erro ao buscar plano. PlanId={PlanId}",id);throw;}}
 async Task<PlanDto> Hydrate(string id,dynamic p){try{using var c=f.Create(); var limits=(await c.QueryAsync<(string limit_key,int limit_value)>("SELECT limit_key,limit_value FROM valorapesquisa.plan_limits WHERE plan_id=@id",new{id})).ToDictionary(x=>x.limit_key,x=>x.limit_value); var caps=(await c.QueryAsync<(string capability_key,string capability_level)>("SELECT capability_key,capability_level FROM valorapesquisa.plan_capabilities WHERE plan_id=@id",new{id})).ToDictionary(x=>x.capability_key,x=>x.capability_level); return new(id,(string)p.name,(string?)p.badge,(string)p.price_label,(string?)p.price_complement,(int)p.display_order,limits,caps);}catch(Exception ex){logger.LogError(ex,"Erro ao hidratar limites do plano. PlanId={PlanId}",id);throw;}}
 public async Task<string?> GetCurrentPlanIdAsync(Guid organizationId){try{using var c=f.Create(); return await c.ExecuteScalarAsync<string?>("SELECT plan_id FROM valorapesquisa.subscriptions WHERE organization_id=@organizationId AND status='active' ORDER BY created_at DESC LIMIT 1",new{organizationId});}catch(Exception ex){logger.LogError(ex,"Erro ao buscar plano atual. OrganizationId={OrganizationId}",organizationId);throw;}}
 public async Task CreateSubscriptionAsync(Guid organizationId,string planId){try{using var c=f.Create(); await c.ExecuteAsync("INSERT INTO valorapesquisa.subscriptions(organization_id,plan_id) VALUES (@organizationId,@planId)",new{organizationId,planId});}catch(Exception ex){logger.LogError(ex,"Erro ao criar assinatura. OrganizationId={OrganizationId} PlanId={PlanId}",organizationId,planId);throw;}}
}
