using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Dapper;
using Valora.Application.ActionCenter;
using Valora.Application.Contracts;
namespace Valora.Infrastructure.Repositories;

public sealed class PriorityActionRepository(IDbConnectionFactory db, IDbTransactionFactory transactions) : IPriorityActionRepository {
    const string VisiblePriority = "SELECT id FROM valorapesquisa.executive_priorities WHERE id=@priority AND organization_id=@o AND deleted_at IS NULL AND (owner_user_id IS NULL OR owner_user_id=@u OR @wide)";
    public async Task<IReadOnlyList<PriorityActionDto>> List(Guid o, Guid priority, Guid u, bool wide, CancellationToken ct) { using var c=db.Create(); const string sql="""SELECT a.id ActionId,a.action_plan_id PlanId,p.title PlanTitle,a.title,a.status,a.priority,a.responsible_user_id ResponsibleUserId,a.due_at DueAt,a.progress_percent ProgressPercent,a.evidence_summary EvidenceSummary,a.expected_outcome ExpectedOutcome,a.completion_evidence CompletionEvidence,l.created_at LinkedAt FROM valorapesquisa.priority_action_links l JOIN valorapesquisa.action_items a ON a.id=l.action_item_id AND a.organization_id=l.organization_id AND a.deleted_at IS NULL JOIN valorapesquisa.action_plans p ON p.id=a.action_plan_id AND p.organization_id=l.organization_id AND p.deleted_at IS NULL WHERE l.organization_id=@o AND l.priority_id=@priority AND l.deleted_at IS NULL AND EXISTS("""+VisiblePriority+") ORDER BY l.created_at,a.id"; return (await c.QueryAsync<PriorityActionDto>(new CommandDefinition(sql,new{o,priority,u,wide},cancellationToken:ct))).AsList(); }
    public Task<Guid> Link(Guid o,Guid u,Guid priority,LinkPriorityActionRequest r,bool wide,CancellationToken ct)=>Execute(o,u,priority,r.CommandId,"link",new{r.ActionId},wide,async z=>{ var valid=await z.Connection.ExecuteScalarAsync<int>(new CommandDefinition("SELECT count(*) FROM valorapesquisa.action_items WHERE id=@ActionId AND organization_id=@o AND deleted_at IS NULL AND status<>'canceled'",new{o,r.ActionId},z.Transaction,cancellationToken:ct)); if(valid==0) throw new KeyNotFoundException("Atividade não encontrada ou cancelada."); await InsertLink(z,o,u,priority,r.ActionId,ct); return r.ActionId; },ct);
    public Task<Guid> Create(Guid o,Guid u,Guid priority,CreatePriorityActionRequest r,bool wide,CancellationToken ct)=>Execute(o,u,priority,r.CommandId,"create",r,wide,async z=>{ var plan=r.PlanId; if(r.CreatePlan){plan=Guid.NewGuid(); await z.Connection.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.action_plans(id,organization_id,title,summary,origin_type,origin_id,status,priority,owner_user_id,created_by_user_id,due_at,evidence_summary,expected_outcome) VALUES(@plan,@o,@PlanTitle,@Description,'priority',@priority,'draft',@Priority,@ResponsibleUserId,@u,@DueAt,@EvidenceSummary,@ExpectedOutcome)",new{plan,o,u,priority,r.PlanTitle,r.Description,r.Priority,r.ResponsibleUserId,r.DueAt,r.EvidenceSummary,r.ExpectedOutcome},z.Transaction,cancellationToken:ct));} else { var valid=await z.Connection.ExecuteScalarAsync<int>(new CommandDefinition("SELECT count(*) FROM valorapesquisa.action_plans WHERE id=@plan AND organization_id=@o AND deleted_at IS NULL AND status<>'canceled'",new{o,plan},z.Transaction,cancellationToken:ct)); if(valid==0)throw new KeyNotFoundException("Plano não encontrado ou cancelado."); } var action=Guid.NewGuid(); await z.Connection.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.action_items(id,organization_id,action_plan_id,title,description,origin_type,origin_id,priority,status,responsible_user_id,due_at,evidence_summary,expected_outcome) VALUES(@action,@o,@plan,@Title,@Description,'priority',@priority,@Priority,'pending',@ResponsibleUserId,@DueAt,@EvidenceSummary,@ExpectedOutcome)",new{action,o,plan,priority,r.Title,r.Description,r.Priority,r.ResponsibleUserId,r.DueAt,r.EvidenceSummary,r.ExpectedOutcome},z.Transaction,cancellationToken:ct)); await InsertLink(z,o,u,priority,action,ct); return action; },ct);
    async Task<Guid> Execute(Guid o,Guid u,Guid priority,string command,string operation,object payload,bool wide,Func<IUnitOfWork,Task<Guid>> work,CancellationToken ct){ var hash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(JsonSerializer.Serialize(payload)))); await using var z=await transactions.BeginAsync(ct); await z.Connection.ExecuteAsync(new CommandDefinition("SELECT pg_advisory_xact_lock(hashtextextended(@lockKey,0))",new{lockKey=o+":"+command},z.Transaction,cancellationToken:ct)); var visible=await z.Connection.ExecuteScalarAsync<int>(new CommandDefinition(VisiblePriority+" FOR UPDATE",new{o,u,priority,wide},z.Transaction,cancellationToken:ct)); if(visible==0)throw new KeyNotFoundException("Prioridade não encontrada ou sem acesso."); var prior=await z.Connection.QuerySingleOrDefaultAsync<(string Hash,Guid ResultId)>(new CommandDefinition("SELECT request_hash Hash,result_id ResultId FROM valorapesquisa.priority_action_commands WHERE organization_id=@o AND command_id=@command",new{o,command},z.Transaction,cancellationToken:ct)); if(prior!=default){if(prior.Hash!=hash)throw new InvalidOperationException("A chave da operação já foi usada com outro conteúdo."); return prior.ResultId;} var result=await work(z); await z.Connection.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.priority_action_commands(organization_id,command_id,operation,request_hash,result_id,created_by_user_id) VALUES(@o,@command,@operation,@hash,@result,@u)",new{o,u,command,operation,hash,result},z.Transaction,cancellationToken:ct)); await z.CommitAsync(); return result; }
    static Task InsertLink(IUnitOfWork z,Guid o,Guid u,Guid priority,Guid action,CancellationToken ct)=>z.Connection.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.priority_action_links(organization_id,priority_id,action_item_id,created_by_user_id) VALUES(@o,@priority,@action,@u) ON CONFLICT(organization_id,priority_id,action_item_id) WHERE deleted_at IS NULL DO NOTHING",new{o,u,priority,action},z.Transaction,cancellationToken:ct));
}
