using Dapper;
using Valora.Application.CommercialDelivery;
using Valora.Application.Contracts;

namespace Valora.Infrastructure.Repositories;

public sealed class PublicCommercialRepository(IDbConnectionFactory factory) : IPublicCommercialRepository
{
    public async Task<PublicLeadCreated> UpsertAndStartAsync(PublicLeadRequest r, string emailHash, string emailMasked, string? phoneHash, string? phoneMasked, string? ipHash, string? userAgentHash, CancellationToken ct)
    {
        using var c = factory.Create(); c.Open(); using var tx = c.BeginTransaction();
        var leadId = await c.ExecuteScalarAsync<Guid>(new CommandDefinition(@"INSERT INTO valorapesquisa.public_leads(name,email_hash,email_masked,phone_hash,phone_masked,company_name,segment,company_size,role_title,source,status,consent_version,consent_accepted_at,communication_consent)
VALUES (@Name,@emailHash,@emailMasked,@phoneHash,@phoneMasked,@CompanyName,@Segment,@CompanySize,@RoleTitle,@Source,'diagnostic_started','2026-08',now(),@CommunicationConsent)
ON CONFLICT(email_hash) DO UPDATE SET name=EXCLUDED.name,email_masked=EXCLUDED.email_masked,phone_hash=COALESCE(EXCLUDED.phone_hash,public_leads.phone_hash),phone_masked=COALESCE(EXCLUDED.phone_masked,public_leads.phone_masked),company_name=EXCLUDED.company_name,segment=EXCLUDED.segment,company_size=EXCLUDED.company_size,role_title=EXCLUDED.role_title,communication_consent=EXCLUDED.communication_consent,consent_accepted_at=now(),status=CASE WHEN public_leads.status IN ('converted','archived') THEN public_leads.status ELSE 'diagnostic_started' END,updated_at=now() RETURNING id", new { r.Name, emailHash, emailMasked, phoneHash, phoneMasked, r.CompanyName, r.Segment, r.CompanySize, r.RoleTitle, r.Source, r.CommunicationConsent }, tx, cancellationToken: ct));
        var sessionId = await c.ExecuteScalarAsync<Guid>(new CommandDefinition(@"INSERT INTO valorapesquisa.public_diagnostic_sessions(lead_id,template_code,status,started_at,ip_hash,user_agent_hash,source) VALUES (@leadId,'VALORA_STRATEGIC_MATURITY_V1','started',now(),@ipHash,@userAgentHash,@source) RETURNING id", new { leadId, ipHash, userAgentHash, source=r.Source }, tx, cancellationToken: ct));
        await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.public_lead_events(lead_id,session_id,event_type,message) VALUES (@leadId,@sessionId,'diagnostic_started','Diagnóstico público iniciado.')", new { leadId, sessionId }, tx, cancellationToken: ct));
        tx.Commit(); return new(leadId, sessionId, "started");
    }
    public async Task<Guid> CreateRequestAsync(CommercialRequestInput r, CancellationToken ct)
    {
        using var c=factory.Create(); c.Open(); using var tx=c.BeginTransaction();
        var id=await c.ExecuteScalarAsync<Guid>(new CommandDefinition(@"INSERT INTO valorapesquisa.commercial_contact_requests(lead_id,session_id,request_type,requested_plan,status,notes) VALUES(@LeadId,@SessionId,@RequestType,@RequestedPlan,'requested',@Notes) RETURNING id",r,tx,cancellationToken:ct));
        await c.ExecuteAsync(new CommandDefinition("UPDATE valorapesquisa.public_leads SET status='proposal_requested',plan_interest=COALESCE(@RequestedPlan,plan_interest),updated_at=now() WHERE id=@LeadId AND status NOT IN ('converted','archived')",r,tx,cancellationToken:ct));
        await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.public_lead_events(lead_id,session_id,event_type,message,metadata_json) VALUES(@LeadId,@SessionId,'commercial_request_created','Solicitação comercial registrada.',jsonb_build_object('requestId',@id,'type',@RequestType,'plan',@RequestedPlan))",new{r.LeadId,r.SessionId,r.RequestType,r.RequestedPlan,id},tx,cancellationToken:ct));
        tx.Commit(); return id;
    }
    public async Task<IReadOnlyList<CommercialLeadItem>> ListAsync(string? status,string? level,string? plan,int page,int pageSize,CancellationToken ct){using var c=factory.Create(); var rows=await c.QueryAsync<CommercialLeadItem>(new CommandDefinition(@"SELECT id,name,email_masked EmailMasked,phone_masked PhoneMasked,company_name CompanyName,segment,company_size CompanySize,status,last_result_level LastResultLevel,last_result_score LastResultScore,plan_interest PlanInterest,assigned_to AssignedTo,created_at CreatedAt FROM valorapesquisa.public_leads WHERE (@status IS NULL OR status=@status) AND (@level IS NULL OR last_result_level=@level) AND (@plan IS NULL OR plan_interest=@plan) ORDER BY created_at DESC LIMIT @pageSize OFFSET @offset",new{status,level,plan,pageSize,offset=(page-1)*pageSize},cancellationToken:ct));return rows.ToList();}
    public async Task<CommercialDashboard> DashboardAsync(CancellationToken ct){using var c=factory.Create();return await c.QuerySingleAsync<CommercialDashboard>(new CommandDefinition(@"SELECT count(*) FILTER(WHERE status='new')::int NewLeads,count(*) FILTER(WHERE status='diagnostic_started')::int DiagnosticsStarted,count(*) FILTER(WHERE status='diagnostic_completed')::int DiagnosticsCompleted,(SELECT count(*)::int FROM valorapesquisa.commercial_contact_requests WHERE request_type='contact') ContactRequests,(SELECT count(*)::int FROM valorapesquisa.commercial_contact_requests WHERE lower(requested_plan)='professional') ProfessionalRequests,(SELECT count(*)::int FROM valorapesquisa.commercial_contact_requests WHERE lower(requested_plan)='enterprise') EnterpriseRequests,count(*) FILTER(WHERE status='converted')::int Converted,count(*) FILTER(WHERE status='lost')::int Lost FROM valorapesquisa.public_leads",cancellationToken:ct));}
    public async Task<bool> UpdateStatusAsync(Guid id,string status,Guid? assignedTo,string? reason,CancellationToken ct){using var c=factory.Create();var n=await c.ExecuteAsync(new CommandDefinition(@"WITH changed AS (UPDATE valorapesquisa.public_leads SET status=@status,assigned_to=COALESCE(@assignedTo,assigned_to),converted_at=CASE WHEN @status='converted' THEN now() ELSE converted_at END,metadata_json=CASE WHEN @reason IS NULL THEN metadata_json ELSE metadata_json||jsonb_build_object('statusReason',@reason) END,updated_at=now() WHERE id=@id AND NOT(status='converted' AND @status='converted') RETURNING id) INSERT INTO valorapesquisa.public_lead_events(lead_id,event_type,message,metadata_json) SELECT id,'status_changed','Status comercial alterado.',jsonb_build_object('status',@status,'reason',@reason) FROM changed",new{id,status,assignedTo,reason},cancellationToken:ct));return n>0;}
}
