using Dapper;
using Valora.Application.Contracts;
using Valora.Application.SecurityCompliance;

namespace Valora.Infrastructure.Repositories;

public sealed class PrivacyConsentRepository(IDbConnectionFactory factory) : IPrivacyConsentRepository
{
 public async Task<PrivacyConsent> RegisterAsync(Guid o,Guid? u,Guid? r,string t,string v,string s,string? ip,string? ua,CancellationToken ct){using var c=factory.Create();const string q="""WITH consent AS (INSERT INTO valorapesquisa.privacy_consents(organization_id,user_id,respondent_id,consent_type,consent_version,status,granted_at,source,ip_address,user_agent) VALUES(@o,@u,@r,@t,@v,'granted',now(),@s,CAST(@ip AS inet),@ua) RETURNING *) INSERT INTO valorapesquisa.privacy_consent_events(organization_id,consent_id,event_type,actor_user_id,evidence_json) SELECT organization_id,id,'granted',@u,jsonb_build_object('version',consent_version,'source',source) FROM consent RETURNING consent_id;""";var id=await c.ExecuteScalarAsync<Guid>(new CommandDefinition(q,new{o,u,r,t,v,s,ip,ua},cancellationToken:ct));return new(id,o,u,r,t,v,"granted",DateTimeOffset.UtcNow,null,s,DateTimeOffset.UtcNow);}
 public async Task RevokeAsync(Guid o,Guid id,Guid actor,CancellationToken ct){using var c=factory.Create();const string q="""WITH changed AS (UPDATE valorapesquisa.privacy_consents SET status='revoked',revoked_at=now(),updated_at=now() WHERE organization_id=@o AND id=@id AND status='granted' RETURNING id) INSERT INTO valorapesquisa.privacy_consent_events(organization_id,consent_id,event_type,actor_user_id) SELECT @o,id,'revoked',@actor FROM changed""";if(await c.ExecuteAsync(new CommandDefinition(q,new{o,id,actor},cancellationToken:ct))==0)throw new InvalidOperationException("Consentimento ativo não encontrado na organização.");}
}
public sealed class DataSubjectRequestRepository(IDbConnectionFactory factory):IDataSubjectRequestRepository
{
 public async Task<DataSubjectRequest> CreateAsync(Guid o,Guid? u,string email,string type,string description,DateTimeOffset due,CancellationToken ct){using var c=factory.Create();const string q="""INSERT INTO valorapesquisa.data_subject_requests(organization_id,requester_user_id,requester_email,request_type,status,description,due_at) VALUES(@o,@u,@email,@type,'open',@description,@due) RETURNING id""";var id=await c.ExecuteScalarAsync<Guid>(new CommandDefinition(q,new{o,u,email,type,description,due},cancellationToken:ct));return new(id,o,email,type,"open",description,due,null,DateTimeOffset.UtcNow);}
 public async Task CompleteAsync(Guid o,Guid id,Guid handler,string summary,CancellationToken ct){using var c=factory.Create();var n=await c.ExecuteAsync(new CommandDefinition("UPDATE valorapesquisa.data_subject_requests SET status='completed',response_summary=@summary,handled_by_user_id=@handler,completed_at=now(),updated_at=now() WHERE organization_id=@o AND id=@id AND deleted_at IS NULL",new{o,id,handler,summary},cancellationToken:ct));if(n==0)throw new InvalidOperationException("Solicitação não encontrada na organização.");}
}
public sealed class DataRetentionRepository(IDbConnectionFactory factory):IDataRetentionRepository
{
 public async Task<RetentionPolicy> ConfigureAsync(Guid o,string category,int days,string action,Guid responsible,CancellationToken ct){using var c=factory.Create();const string q="""INSERT INTO valorapesquisa.data_retention_policies(organization_id,data_category,retention_days,expiration_action,responsible_user_id) VALUES(@o,@category,@days,@action,@responsible) ON CONFLICT(organization_id,data_category) DO UPDATE SET retention_days=EXCLUDED.retention_days,expiration_action=EXCLUDED.expiration_action,responsible_user_id=EXCLUDED.responsible_user_id,updated_at=now(),deleted_at=NULL RETURNING id""";var id=await c.ExecuteScalarAsync<Guid>(new CommandDefinition(q,new{o,category,days,action,responsible},cancellationToken:ct));return new(id,o,category,days,action,responsible,null);}
 public async Task<Guid> StartJobAsync(Guid o,Guid policy,CancellationToken ct){using var c=factory.Create();const string q="""INSERT INTO valorapesquisa.data_retention_jobs(organization_id,policy_id,status,evidence_json) SELECT @o,id,'pending',jsonb_build_object('requested_at',now()) FROM valorapesquisa.data_retention_policies WHERE organization_id=@o AND id=@policy AND is_active AND deleted_at IS NULL RETURNING id""";var id=await c.ExecuteScalarAsync<Guid?>(new CommandDefinition(q,new{o,policy},cancellationToken:ct));return id??throw new InvalidOperationException("Política não encontrada na organização.");}
}
public sealed class SecurityIncidentRepository(IDbConnectionFactory factory):ISecurityIncidentRepository
{
 public async Task<SecurityIncident> RegisterAsync(Guid o,string severity,string type,string title,string description,string evidence,Guid? assignee,CancellationToken ct){using var c=factory.Create();const string q="""WITH incident AS (INSERT INTO valorapesquisa.security_incidents(organization_id,severity,status,incident_type,title,description,evidence_summary,detected_at,assigned_to_user_id) VALUES(@o,@severity,'open',@type,@title,@description,@evidence,now(),@assignee) RETURNING id) INSERT INTO valorapesquisa.security_incident_events(organization_id,incident_id,event_type,actor_user_id,description,evidence_json) SELECT @o,id,'registered',@assignee,@description,jsonb_build_object('evidence',@evidence) FROM incident RETURNING incident_id""";var id=await c.ExecuteScalarAsync<Guid>(new CommandDefinition(q,new{o,severity,type,title,description,evidence,assignee},cancellationToken:ct));return new(id,o,severity,"open",type,title,evidence,DateTimeOffset.UtcNow);}
 public async Task ResolveAsync(Guid o,Guid id,Guid actor,string resolution,CancellationToken ct){using var c=factory.Create();c.Open();using var tx=c.BeginTransaction();var n=await c.ExecuteAsync(new CommandDefinition("UPDATE valorapesquisa.security_incidents SET status='resolved',resolution=@resolution,resolved_at=now(),updated_at=now() WHERE organization_id=@o AND id=@id AND deleted_at IS NULL",new{o,id,resolution},tx,cancellationToken:ct));if(n==0)throw new InvalidOperationException("Incidente não encontrado na organização.");await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.security_incident_events(organization_id,incident_id,event_type,actor_user_id,description) VALUES(@o,@id,'resolved',@actor,@resolution)",new{o,id,actor,resolution},tx,cancellationToken:ct));tx.Commit();}
}
public sealed class AccessReviewRepository(IDbConnectionFactory factory):IAccessReviewRepository
{
 public async Task<AccessReviewCycle> StartAsync(Guid o,string title,Guid actor,DateTimeOffset due,CancellationToken ct){using var c=factory.Create();var id=await c.ExecuteScalarAsync<Guid>(new CommandDefinition("INSERT INTO valorapesquisa.access_review_cycles(organization_id,title,status,started_by_user_id,due_at) VALUES(@o,@title,'open',@actor,@due) RETURNING id",new{o,title,actor,due},cancellationToken:ct));return new(id,o,title,"open",due);}
 public async Task CompleteAsync(Guid o,Guid id,Guid actor,CancellationToken ct){using var c=factory.Create();var n=await c.ExecuteAsync(new CommandDefinition("UPDATE valorapesquisa.access_review_cycles SET status='completed',completed_at=now(),updated_at=now() WHERE organization_id=@o AND id=@id AND deleted_at IS NULL",new{o,id,actor},cancellationToken:ct));if(n==0)throw new InvalidOperationException("Ciclo não encontrado na organização.");}
}
public sealed class ComplianceAuditRepository(IDbConnectionFactory factory):IComplianceAuditRepository
{
 public async Task AppendAsync(ComplianceAuditEvent e,CancellationToken ct){using var c=factory.Create();await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.compliance_audit_events(organization_id,actor_user_id,event_type,resource_type,resource_id,outcome,evidence_json,correlation_id) VALUES(@OrganizationId,@ActorUserId,@EventType,@ResourceType,@ResourceId,@Outcome,CAST(@EvidenceJson AS jsonb),@CorrelationId)",e,cancellationToken:ct));}
 public async Task LogSensitiveAccessAsync(Guid o,Guid? actor,string category,string rt,string id,string purpose,string decision,string? correlation,CancellationToken ct){using var c=factory.Create();await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.sensitive_data_access_logs(organization_id,actor_user_id,data_category,resource_type,resource_id,purpose,decision,correlation_id) VALUES(@o,@actor,@category,@rt,@id,@purpose,@decision,@correlation)",new{o,actor,category,rt,id,purpose,decision,correlation},cancellationToken:ct));}
}
