using Dapper;
using Valora.Application.Contracts;
using Valora.Application.SuccessCenter;

namespace Valora.Infrastructure.Repositories;

public sealed class SuccessCenterRepository(IDbConnectionFactory db) : ISuccessCenterRepository
{
    public async Task EnsureOnboarding(Guid o,CancellationToken ct){using var c=db.Create();await c.ExecuteAsync(new CommandDefinition("SELECT valorapesquisa.ensure_success_onboarding(@o)",new{o},cancellationToken:ct));}
    public async Task<IReadOnlyList<OnboardingStep>> GetOnboarding(Guid o,CancellationToken ct){using var c=db.Create();const string sql="""SELECT p.id "Id",s.code "Code",s.title "Title",p.status "Status",p.responsible_user_id "ResponsibleUserId",p.due_at "DueAt",p.evidence "Evidence",p.blocked_reason "BlockedReason",s.executive_guidance "Guidance",s.action_url "ActionUrl" FROM valorapesquisa.organization_onboarding_progress p JOIN valorapesquisa.success_onboarding_steps s ON s.id=p.step_id WHERE p.organization_id=@o AND p.deleted_at IS NULL ORDER BY s.display_order""";return(await c.QueryAsync<OnboardingStep>(new CommandDefinition(sql,new{o},cancellationToken:ct))).AsList();}
    public async Task SetStep(Guid o,Guid u,Guid id,bool complete,string? evidence,CancellationToken ct){using var c=db.Create();var status=complete?"completed":"pending";await c.ExecuteAsync(new CommandDefinition("UPDATE valorapesquisa.organization_onboarding_progress SET status=@status,evidence=@evidence,completed_by_user_id=CASE WHEN @complete THEN @u END,completed_at=CASE WHEN @complete THEN now() END,updated_at=now() WHERE id=@id AND organization_id=@o AND deleted_at IS NULL; INSERT INTO valorapesquisa.product_usage_events(organization_id,user_id,event_name,feature_code,context_json) VALUES(@o,@u,'onboarding.step.completed','onboarding',jsonb_build_object('step_id',@id,'status',@status))",new{o,u,id,status,evidence,complete},cancellationToken:ct));}
    public async Task<UsageEvidence> GetUsageEvidence(Guid o,CancellationToken ct){using var c=db.Create();const string sql="""SELECT (SELECT count(DISTINCT created_at::date) FROM valorapesquisa.audit_logs WHERE organization_id=@o AND created_at>now()-interval '30 days') "LoginDays",(SELECT count(*) FROM valorapesquisa.users WHERE organization_id=@o AND status='active' AND deleted_at IS NULL) "ActiveUsers",(SELECT count(*) FROM valorapesquisa.surveys WHERE organization_id=@o AND deleted_at IS NULL) "Diagnostics",(SELECT count(*) FROM valorapesquisa.responses r JOIN valorapesquisa.surveys s ON s.id=r.survey_id WHERE s.organization_id=@o) "Responses",(SELECT count(*) FROM valorapesquisa.reports WHERE organization_id=@o AND deleted_at IS NULL) "Reports",(SELECT count(*) FROM valorapesquisa.action_items WHERE organization_id=@o AND deleted_at IS NULL) "ActionsCreated",(SELECT count(*) FROM valorapesquisa.action_items WHERE organization_id=@o AND status='completed' AND deleted_at IS NULL) "ActionsCompleted",(SELECT count(*) FROM valorapesquisa.intelligent_alerts WHERE organization_id=@o AND status='open' AND deleted_at IS NULL) "PendingAlerts",(SELECT count(*) FROM valorapesquisa.product_usage_events WHERE organization_id=@o AND feature_code='ai') "AiUses",(SELECT count(*) FROM valorapesquisa.product_usage_events WHERE organization_id=@o AND feature_code IN ('journey','evolution')) "JourneyUses",(SELECT count(*) FROM valorapesquisa.support_tickets WHERE organization_id=@o AND status NOT IN ('resolved','closed') AND deleted_at IS NULL) "OpenTickets",(SELECT count(*) FROM valorapesquisa.organization_onboarding_progress WHERE organization_id=@o AND due_at<now() AND status<>'completed' AND deleted_at IS NULL) "OverdueOnboardingSteps""";return await c.QuerySingleAsync<UsageEvidence>(new CommandDefinition(sql,new{o},cancellationToken:ct));}
    public async Task SaveHealth(Guid o,HealthScore s,CancellationToken ct){using var c=db.Create();const string sql="""INSERT INTO valorapesquisa.organization_health_scores(organization_id,score,level,usage_score,adoption_score,support_score,diagnostic_score,engagement_score,risk_level,evidence_summary,calculated_at) VALUES(@o,@Score,@Level,@UsageScore,@AdoptionScore,@SupportScore,@DiagnosticScore,@EngagementScore,@RiskLevel,@EvidenceSummary,@CalculatedAt); INSERT INTO valorapesquisa.product_usage_events(organization_id,event_name,feature_code,context_json) VALUES(@o,'health_score.calculated','success_center',jsonb_build_object('score',@Score,'level',@Level))""";await c.ExecuteAsync(new CommandDefinition(sql,new{o,s.Score,s.Level,s.UsageScore,s.AdoptionScore,s.SupportScore,s.DiagnosticScore,s.EngagementScore,s.RiskLevel,s.EvidenceSummary,s.CalculatedAt},cancellationToken:ct));}
    public async Task<IReadOnlyList<SupportTicket>> GetTickets(Guid o,CancellationToken ct){using var c=db.Create();return(await c.QueryAsync<SupportTicket>(new CommandDefinition("SELECT id \"Id\",subject \"Subject\",description \"Description\",category \"Category\",priority \"Priority\",status \"Status\",opened_by_user_id \"OpenedByUserId\",assigned_to_user_id \"AssignedToUserId\",created_at \"CreatedAt\" FROM valorapesquisa.support_tickets WHERE organization_id=@o AND deleted_at IS NULL ORDER BY created_at DESC",new{o},cancellationToken:ct))).AsList();}
    public async Task<Guid> CreateTicket(Guid o,Guid u,CreateTicketCommand x,CancellationToken ct){var id=Guid.NewGuid();using var c=db.Create();const string sql="""INSERT INTO valorapesquisa.support_tickets(id,organization_id,opened_by_user_id,subject,description,category,priority,status,source) VALUES(@id,@o,@u,@Subject,@Description,@Category,@Priority,'open','portal'); INSERT INTO valorapesquisa.support_ticket_events(ticket_id,organization_id,user_id,event_type,to_status,evidence) VALUES(@id,@o,@u,'support.ticket.created','open',@Description)""";await c.ExecuteAsync(new CommandDefinition(sql,new{id,o,u,x.Subject,x.Description,x.Category,x.Priority},cancellationToken:ct));return id;}
    public async Task AddTicketMessage(Guid o,Guid u,Guid id,string message,CancellationToken ct){using var c=db.Create();await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.support_ticket_messages(ticket_id,organization_id,user_id,message) SELECT id,@o,@u,@message FROM valorapesquisa.support_tickets WHERE id=@id AND organization_id=@o AND deleted_at IS NULL",new{o,u,id,message},cancellationToken:ct));}
    public async Task SetTicketStatus(Guid o,Guid u,Guid id,string status,CancellationToken ct){using var c=db.Create();await c.ExecuteAsync(new CommandDefinition("WITH changed AS (UPDATE valorapesquisa.support_tickets SET status=@status,resolved_at=CASE WHEN @status='resolved' THEN now() ELSE resolved_at END,updated_at=now() WHERE id=@id AND organization_id=@o AND deleted_at IS NULL RETURNING id) INSERT INTO valorapesquisa.support_ticket_events(ticket_id,organization_id,user_id,event_type,to_status) SELECT id,@o,@u,CASE WHEN @status='resolved' THEN 'support.ticket.resolved' ELSE 'support.ticket.reopened' END,@status FROM changed",new{o,u,id,status},cancellationToken:ct));}
    public async Task<IReadOnlyList<KnowledgeArticle>> SearchKnowledge(Guid o,string? q,CancellationToken ct){using var c=db.Create();const string sql="""SELECT a.id "Id",a.title "Title",a.slug "Slug",a.summary "Summary",a.content "Content",a.visibility "Visibility",a.minimum_plan_code "MinimumPlan" FROM valorapesquisa.knowledge_base_articles a WHERE a.status='published' AND a.deleted_at IS NULL AND a.visibility='public' AND (@q IS NULL OR a.search_document @@ plainto_tsquery('portuguese',@q)) ORDER BY a.display_order,a.title""";return(await c.QueryAsync<KnowledgeArticle>(new CommandDefinition(sql,new{q=string.IsNullOrWhiteSpace(q)?null:q},cancellationToken:ct))).AsList();}
    public async Task RegisterArticleView(Guid o,Guid u,Guid id,CancellationToken ct)=>await RegisterUsage(o,u,"knowledge_base",id.ToString(),ct);
    public async Task<IReadOnlyList<Playbook>> GetPlaybooks(Guid o,CancellationToken ct){using var c=db.Create();return(await c.QueryAsync<Playbook>(new CommandDefinition("SELECT id \"Id\",name \"Name\",description \"Description\",status \"Status\" FROM valorapesquisa.success_playbooks WHERE deleted_at IS NULL AND status='active' ORDER BY name",cancellationToken:ct))).AsList();}
    public async Task AssignPlaybook(Guid o,Guid u,Guid id,CancellationToken ct){using var c=db.Create();await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.organization_playbook_assignments(organization_id,playbook_id,assigned_by_user_id) VALUES(@o,@id,@u) ON CONFLICT(organization_id,playbook_id) WHERE deleted_at IS NULL DO NOTHING",new{o,u,id},cancellationToken:ct));}
    public async Task RegisterUsage(Guid o,Guid u,string feature,string? context,CancellationToken ct){using var c=db.Create();await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.product_usage_events(organization_id,user_id,event_name,feature_code,context_json) VALUES(@o,@u,CASE WHEN @feature='knowledge_base' THEN 'knowledge_article.viewed' ELSE 'product_usage.registered' END,@feature,jsonb_build_object('context',@context))",new{o,u,feature,context},cancellationToken:ct));}
    public async Task<IReadOnlyList<FeatureAdoption>> GetAdoption(Guid o,CancellationToken ct){using var c=db.Create();return(await c.QueryAsync<FeatureAdoption>(new CommandDefinition("SELECT feature_code \"FeatureCode\",count(*) \"Events\",count(DISTINCT user_id) \"ActiveUsers\",max(created_at) \"LastUsedAt\" FROM valorapesquisa.product_usage_events WHERE organization_id=@o GROUP BY feature_code ORDER BY count(*) DESC",new{o},cancellationToken:ct))).AsList();}
}
