using Dapper;
using System.Data;
using Microsoft.Extensions.Logging;
using Valora.Application.Contracts;
using Valora.Application.DTOs;
using Valora.Application.ReadModels;
using Valora.Application.Security;
namespace Valora.Infrastructure.Repositories;

public sealed class SurveyRepository(IDbConnectionFactory f, ILogger<SurveyRepository> logger) : ISurveyRepository {
    public async Task<SurveyPublicReadModel?> GetPublicByTokenAsync(string token) { try { using var c = f.Create(); var tokenHash = HashToken(token); return await c.QuerySingleOrDefaultAsync<SurveyPublicReadModel>(BaseSql + " AND (s.token_hash=@tokenHash OR EXISTS (SELECT 1 FROM valorapesquisa.survey_links sl WHERE sl.survey_id=s.id AND sl.token_hash=@tokenHash AND sl.is_deleted=false AND sl.status='active' AND sl.revoked_at IS NULL AND (sl.expires_at IS NULL OR sl.expires_at>now() OR " + FreeOfficialSql + ")))", new { tokenHash }); } catch (Exception ex) { logger.LogError(ex, "Erro ao buscar pesquisa pública por token. Token={Token}", LogSanitizer.MaskToken(token)); throw; } }
    public async Task<SurveyPublicReadModel?> GetActivePublicSurveyAsync(Guid surveyId) { try { using var c = f.Create(); return await c.QuerySingleOrDefaultAsync<SurveyPublicReadModel>(BaseSql + " AND s.id=@surveyId", new { surveyId }); } catch (Exception ex) { logger.LogError(ex, "Erro ao buscar pesquisa pública ativa. SurveyId={SurveyId}", surveyId); throw; } }
    public async Task<SurveyPublicReadModel?> GetResultSurveyAsync(Guid surveyId) { try { using var c = f.Create(); return await c.QuerySingleOrDefaultAsync<SurveyPublicReadModel>(ResultSurveySql, new { surveyId }); } catch (Exception ex) { logger.LogError(ex, "Erro ao buscar a versão histórica do resultado. SurveyId={SurveyId}", surveyId); throw; } }
    public async Task<bool> LockEligibleForCompletionAsync(SurveyPublicReadModel survey, IDbConnection connection, IDbTransaction transaction) { try { var id = await connection.QuerySingleOrDefaultAsync<Guid?>("SELECT s.id FROM valorapesquisa.surveys s JOIN valorapesquisa.form_versions fv ON fv.id=s.form_version_id WHERE s.id=@Id AND s.organization_id=@OrganizationId AND s.form_version_id=@FormVersionId AND fv.form_id=@FormId AND fv.status='published' AND s.status IN ('active','published','open') AND s.is_deleted=false AND s.revoked_at IS NULL AND (s.starts_at IS NULL OR s.starts_at<=now()) AND (s.expires_at IS NULL OR s.expires_at>now()) FOR UPDATE OF s", survey, transaction); return id is not null; } catch (Exception ex) { logger.LogError(ex, "Erro ao bloquear elegibilidade da conclusão. SurveyId={SurveyId} FormVersionId={FormVersionId}", survey.Id, survey.FormVersionId); throw; } }
    public async Task<SurveyLinkReadModel?> GetPublicLinkAsync(Guid surveyId) { try { using var c = f.Create(); return await c.QuerySingleOrDefaultAsync<SurveyLinkReadModel>("SELECT sl.id,sl.survey_id AS SurveyId,sl.public_url AS PublicUrl,sl.status,sl.starts_at AS StartsAt,sl.expires_at AS ExpiresAt FROM valorapesquisa.survey_links sl JOIN valorapesquisa.surveys s ON s.id=sl.survey_id JOIN valorapesquisa.organizations o ON o.id=s.organization_id JOIN valorapesquisa.form_versions fv ON fv.id=s.form_version_id AND fv.status='published' JOIN valorapesquisa.forms fo ON fo.id=fv.form_id WHERE sl.survey_id=@surveyId AND sl.is_deleted=false AND sl.status='active' AND sl.revoked_at IS NULL AND s.is_deleted=false AND s.status IN ('active','published','open') AND o.is_deleted=false AND o.status='active' AND fo.is_deleted=false AND (sl.starts_at IS NULL OR sl.starts_at<=now()) AND (sl.expires_at IS NULL OR sl.expires_at>now() OR " + FreeOfficialSql + ") ORDER BY sl.created_at DESC LIMIT 1", new { surveyId }); } catch (Exception ex) { logger.LogError(ex, "Erro ao buscar link público ativo. SurveyId={SurveyId}", surveyId); throw; } }
    public async Task<bool> ValidatePublicTokenAsync(Guid surveyId, string token) { try { using var c = f.Create(); var tokenHash = HashToken(token); var ok = await c.ExecuteScalarAsync<int>("SELECT count(*) FROM valorapesquisa.survey_links sl JOIN valorapesquisa.surveys s ON s.id=sl.survey_id JOIN valorapesquisa.organizations o ON o.id=s.organization_id JOIN valorapesquisa.form_versions fv ON fv.id=s.form_version_id AND fv.status='published' JOIN valorapesquisa.forms fo ON fo.id=fv.form_id WHERE sl.survey_id=@surveyId AND sl.token_hash=@tokenHash AND sl.status='active' AND sl.is_deleted=false AND sl.revoked_at IS NULL AND s.is_deleted=false AND s.status IN ('active','published','open') AND o.is_deleted=false AND o.status='active' AND fo.is_deleted=false AND (sl.expires_at IS NULL OR sl.expires_at>now() OR " + FreeOfficialSql + ")", new { surveyId, tokenHash }); if (ok > 0) return true; return await c.ExecuteScalarAsync<int>("SELECT count(*) FROM valorapesquisa.surveys s JOIN valorapesquisa.organizations o ON o.id=s.organization_id JOIN valorapesquisa.form_versions fv ON fv.id=s.form_version_id AND fv.status='published' JOIN valorapesquisa.forms fo ON fo.id=fv.form_id WHERE s.id=@surveyId AND s.token_hash=@tokenHash AND s.is_deleted=false AND s.revoked_at IS NULL AND s.status IN ('active','published','open') AND o.is_deleted=false AND o.status='active' AND fo.is_deleted=false AND (s.expires_at IS NULL OR s.expires_at>now() OR " + FreeOfficialSql + ")", new { surveyId, tokenHash }) > 0; } catch (Exception ex) { logger.LogError(ex, "Erro ao validar token público. SurveyId={SurveyId} Token={Token}", surveyId, LogSanitizer.MaskToken(token)); throw; } }
    public async Task<Guid> SaveResponseAsync(Guid surveyId, SubmitResponseRequest request) { try { using var c = f.Create(); var survey = await GetActivePublicSurveyAsync(surveyId); if (survey is null) throw new InvalidOperationException("Pesquisa pública indisponível para submissão."); var id = Guid.NewGuid(); await c.ExecuteAsync("INSERT INTO valorapesquisa.responses(id,organization_id,survey_id,form_id,form_version_id,participant_name,participant_email,status,completed_at) VALUES (@id,@organizationId,@surveyId,@formId,@formVersionId,@participantName,@participantEmail,'completed',now())", new { id, organizationId = survey.OrganizationId, surveyId, formId = survey.FormId, formVersionId = survey.FormVersionId, participantName = request.ParticipantName, participantEmail = request.ParticipantEmail }); logger.LogInformation("Resposta pública salva por rota compatível. SurveyId={SurveyId} ResponseId={ResponseId}", surveyId, id); return id; } catch (Exception ex) { logger.LogError(ex, "Erro ao salvar resposta pública compatível. SurveyId={SurveyId} Email={Email}", surveyId, LogSanitizer.MaskEmail(request.ParticipantEmail)); throw; } }
    public async Task<int> CountActiveSurveysAsync(Guid organizationId) { try { using var c = f.Create(); return await c.ExecuteScalarAsync<int>("SELECT count(*) FROM valorapesquisa.surveys WHERE organization_id=@organizationId AND status='active' AND is_deleted=false", new { organizationId }); } catch (Exception ex) { logger.LogError(ex, "Erro ao contar pesquisas ativas. OrganizationId={OrganizationId}", organizationId); throw; } }
    public async Task<int> CountResponsesThisMonthAsync(Guid organizationId) { try { using var c = f.Create(); return await c.ExecuteScalarAsync<int>("SELECT count(*) FROM valorapesquisa.responses WHERE organization_id=@organizationId AND created_at >= date_trunc('month', now()) AND is_deleted=false", new { organizationId }); } catch (Exception ex) { logger.LogError(ex, "Erro ao contar respostas do mês. OrganizationId={OrganizationId}", organizationId); throw; } }
    private static bool IsFreeOfficialSurvey(bool isFree, string? planId, string? title) => isFree || string.Equals(planId, "free", StringComparison.OrdinalIgnoreCase) || (title?.Contains("Valora Insight", StringComparison.OrdinalIgnoreCase) ?? false) || (title?.Contains("Diagnóstico gratuito", StringComparison.OrdinalIgnoreCase) ?? false);
    const string FreeOfficialSql = "(s.is_free=true OR lower(coalesce(s.plan_id,''))='free' OR s.title ILIKE '%Valora Insight%' OR s.title ILIKE '%Diagnóstico gratuito%')";
    const string ResultSurveySql = "SELECT s.id,s.organization_id AS OrganizationId,fv.form_id AS FormId,s.form_version_id AS FormVersionId,fv.version AS FormVersionNumber,s.title,s.description,s.status,s.lgpd_required AS LgpdRequired,o.name AS OrganizationName,o.public_name AS PublicName,o.slug AS OrganizationSlug,s.starts_at AS StartsAt,s.expires_at AS ExpiresAt FROM valorapesquisa.surveys s JOIN valorapesquisa.organizations o ON o.id=s.organization_id JOIN valorapesquisa.form_versions fv ON fv.id=s.form_version_id JOIN valorapesquisa.forms fo ON fo.id=fv.form_id WHERE s.id=@surveyId AND s.form_version_id IS NOT NULL AND s.is_deleted=false AND o.is_deleted=false AND fo.is_deleted=false";
    const string BaseSql = "SELECT s.id,s.organization_id AS OrganizationId,fv.form_id AS FormId,s.form_version_id AS FormVersionId,fv.version AS FormVersionNumber,s.title,s.description,s.status,s.lgpd_required AS LgpdRequired,o.name AS OrganizationName,o.public_name AS PublicName,o.slug AS OrganizationSlug,s.starts_at AS StartsAt,s.expires_at AS ExpiresAt FROM valorapesquisa.surveys s JOIN valorapesquisa.organizations o ON o.id=s.organization_id JOIN valorapesquisa.form_versions fv ON fv.id=s.form_version_id AND fv.status='published' JOIN valorapesquisa.forms fo ON fo.id=fv.form_id WHERE s.form_version_id IS NOT NULL AND s.is_deleted=false AND s.revoked_at IS NULL AND s.status IN ('active','published','open') AND o.is_deleted=false AND o.status='active' AND fo.is_deleted=false AND (s.starts_at IS NULL OR s.starts_at<=now()) AND (s.expires_at IS NULL OR s.expires_at>now() OR " + FreeOfficialSql + ")";
    private static string HashToken(string token) => Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(System.Text.Encoding.UTF8.GetBytes(token))).ToLowerInvariant();

    public async Task<IReadOnlyList<dynamic>> ListAdminAsync(Guid organizationId) { try { using var c = f.Create(); return (await c.QueryAsync("SELECT s.id,s.organization_id,fv.form_id,s.form_version_id,fv.version AS form_version_number,s.title,s.description,s.status,s.public_slug,s.public_url,s.starts_at,s.expires_at,s.created_at,s.updated_at,f.name AS form_name,(SELECT count(*) FROM valorapesquisa.responses r WHERE r.survey_id=s.id AND r.status='completed' AND r.is_deleted=false) AS completed_responses FROM valorapesquisa.surveys s LEFT JOIN valorapesquisa.form_versions fv ON fv.id=s.form_version_id LEFT JOIN valorapesquisa.forms f ON f.id=fv.form_id WHERE s.organization_id=@organizationId AND s.is_deleted=false ORDER BY s.created_at DESC", new { organizationId })).ToList(); } catch (Exception ex) { logger.LogError(ex, "Erro ao listar pesquisas. OrganizationId={OrganizationId}", organizationId); throw; } }
    public async Task<dynamic?> GetAdminAsync(Guid organizationId, Guid surveyId) { try { using var c = f.Create(); return await c.QuerySingleOrDefaultAsync("SELECT s.id,s.organization_id,fv.form_id,s.form_version_id,fv.version AS form_version_number,s.title,s.description,s.status,s.public_slug,s.public_url,s.starts_at,s.expires_at,s.created_at,s.updated_at,f.name AS form_name FROM valorapesquisa.surveys s LEFT JOIN valorapesquisa.form_versions fv ON fv.id=s.form_version_id LEFT JOIN valorapesquisa.forms f ON f.id=fv.form_id WHERE s.id=@surveyId AND s.organization_id=@organizationId AND s.is_deleted=false", new { organizationId, surveyId }); } catch (Exception ex) { logger.LogError(ex, "Erro ao buscar pesquisa administrativa. OrganizationId={OrganizationId} SurveyId={SurveyId}", organizationId, surveyId); throw; } }
    public async Task<Guid> CreateAdminAsync(Guid organizationId, Guid formId, Guid formVersionId, string title, string? description, DateTimeOffset? startsAt, DateTimeOffset? expiresAt) { try { if (expiresAt is not null && startsAt is not null && expiresAt <= startsAt) throw new ArgumentException("O término deve ocorrer depois do início."); using var c = f.Create(); var tokenHash = Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(System.Text.Encoding.UTF8.GetBytes(Guid.NewGuid().ToString("N")))).ToLowerInvariant(); var id = await c.ExecuteScalarAsync<Guid?>("INSERT INTO valorapesquisa.surveys(organization_id,form_version_id,name,title,description,status,token_hash,starts_at,expires_at) SELECT @organizationId,fv.id,@title,@title,@description,'draft',@tokenHash,@startsAt,@expiresAt FROM valorapesquisa.form_versions fv JOIN valorapesquisa.forms f ON f.id=fv.form_id WHERE fv.id=@formVersionId AND fv.form_id=@formId AND fv.status='published' AND f.is_deleted=false AND (f.organization_id=@organizationId OR f.is_global=true OR f.organization_id IS NULL) RETURNING id", new { organizationId, formId, formVersionId, title, description, tokenHash, startsAt, expiresAt }); return id ?? throw new InvalidOperationException("A versão publicada informada não está disponível para esta organização."); } catch (Exception ex) { logger.LogError(ex, "Erro ao criar pesquisa. OrganizationId={OrganizationId} FormId={FormId} FormVersionId={FormVersionId}", organizationId, formId, formVersionId); throw; } }
    public async Task UpdateAdminAsync(Guid organizationId, Guid surveyId, Guid formId, Guid formVersionId, string? title, string? description, DateTimeOffset? startsAt, DateTimeOffset? expiresAt) { try { if (expiresAt is not null && startsAt is not null && expiresAt <= startsAt) throw new ArgumentException("O término deve ocorrer depois do início."); using var c = f.Create(); var changed = await c.ExecuteAsync("UPDATE valorapesquisa.surveys s SET form_version_id=@formVersionId,title=COALESCE(@title,s.title),name=COALESCE(@title,s.name),description=@description,starts_at=@startsAt,expires_at=@expiresAt,updated_at=now() FROM valorapesquisa.form_versions fv JOIN valorapesquisa.forms f ON f.id=fv.form_id WHERE s.id=@surveyId AND s.organization_id=@organizationId AND s.status='draft' AND s.is_deleted=false AND fv.id=@formVersionId AND fv.form_id=@formId AND fv.status='published' AND f.is_deleted=false AND (f.organization_id=@organizationId OR f.is_global=true OR f.organization_id IS NULL)", new { organizationId, surveyId, formId, formVersionId, title, description, startsAt, expiresAt }); if (changed != 1) throw new InvalidOperationException("O diagnóstico não é editável ou a versão publicada não pertence à organização."); } catch (Exception ex) { logger.LogError(ex, "Erro ao atualizar pesquisa. OrganizationId={OrganizationId} SurveyId={SurveyId}", organizationId, surveyId); throw; } }
    public async Task UpdateStatusAdminAsync(Guid organizationId, Guid surveyId, string status) { try { if (status is not ("active" or "closed")) throw new ArgumentException("Transição de situação não permitida."); using var c = f.Create(); var changed = await c.ExecuteAsync(@"UPDATE valorapesquisa.surveys s SET status=@status,updated_at=now()
FROM valorapesquisa.form_versions fv
WHERE s.id=@surveyId AND s.organization_id=@organizationId AND s.is_deleted=false
  AND fv.id=s.form_version_id AND fv.status='published'
  AND ((@status='active' AND s.status='draft' AND (s.expires_at IS NULL OR s.expires_at>now()))
    OR (@status='closed' AND s.status IN ('active','published','open')))", new { organizationId, surveyId, status }); if (changed != 1) throw new InvalidOperationException("A transição não é válida, a coleta expirou ou a versão publicada está inconsistente."); } catch (Exception ex) { logger.LogError(ex, "Erro ao atualizar status da pesquisa. OrganizationId={OrganizationId} SurveyId={SurveyId}", organizationId, surveyId); throw; } }
    public async Task<IReadOnlyList<dynamic>> ListLinksAdminAsync(Guid organizationId, Guid surveyId) { try { using var c = f.Create(); return (await c.QueryAsync("SELECT id,organization_id,survey_id,public_url,status,starts_at,expires_at,created_at,updated_at FROM valorapesquisa.survey_links WHERE organization_id=@organizationId AND survey_id=@surveyId AND is_deleted=false ORDER BY created_at DESC", new { organizationId, surveyId })).ToList(); } catch (Exception ex) { logger.LogError(ex, "Erro ao listar links. OrganizationId={OrganizationId} SurveyId={SurveyId}", organizationId, surveyId); throw; } }
    public async Task<Guid> CreateLinkAdminAsync(Guid organizationId, Guid surveyId, string tokenHash, string publicUrl, DateTimeOffset? expiresAt) { try { using var c = f.Create(); var id = await c.ExecuteScalarAsync<Guid?>("INSERT INTO valorapesquisa.survey_links(organization_id,survey_id,token_hash,public_url,expires_at,status) SELECT @organizationId,s.id,@tokenHash,@publicUrl,@expiresAt,'active' FROM valorapesquisa.surveys s JOIN valorapesquisa.form_versions fv ON fv.id=s.form_version_id WHERE s.id=@surveyId AND s.organization_id=@organizationId AND s.is_deleted=false AND s.status IN ('active','published','open') AND fv.status='published' AND (s.expires_at IS NULL OR s.expires_at>now()) RETURNING id", new { organizationId, surveyId, tokenHash, publicUrl, expiresAt }); return id ?? throw new InvalidOperationException("A coleta não está apta a gerar um link."); } catch (Exception ex) { logger.LogError(ex, "Erro ao criar link. OrganizationId={OrganizationId} SurveyId={SurveyId}", organizationId, surveyId); throw; } }
    public async Task UpdateLinkStatusAdminAsync(Guid organizationId, Guid linkId, string status) { try { using var c = f.Create(); await c.ExecuteAsync("UPDATE valorapesquisa.survey_links SET status=@status,revoked_at=CASE WHEN @status IN ('revoked','inactive') THEN now() ELSE revoked_at END,updated_at=now() WHERE id=@linkId AND organization_id=@organizationId AND is_deleted=false", new { organizationId, linkId, status }); } catch (Exception ex) { logger.LogError(ex, "Erro ao atualizar link. OrganizationId={OrganizationId} LinkId={LinkId}", organizationId, linkId); throw; } }

}
