using Dapper;using Valora.Application.Contracts;using Valora.Application.DTOs;
namespace Valora.Infrastructure.Repositories;
public sealed class UserAdministrationRepository(IDbConnectionFactory factory):IUserAdministrationRepository
{
 private const string Projection="""u.id Id,u.name Name,u.email Email,u.phone Phone,u.status Status,COALESCE((SELECT array_agg(r.code ORDER BY r.code) FROM valorapesquisa.user_roles ur JOIN valorapesquisa.roles r ON r.id=ur.role_id WHERE ur.user_id=u.id),ARRAY[]::text[]) RoleCodes,u.last_login_at LastLoginAt,u.created_at CreatedAt,u.updated_at UpdatedAt""";
 public async Task<(IReadOnlyList<UserAdministrationResponse> Items,long Total)> ListAsync(Guid org,UserListQuery q,CancellationToken ct=default){using var c=factory.Create();var scopeType=q.DepartmentId.HasValue?"department":q.UnitId.HasValue?"unit":q.LegalEntityId.HasValue?"legal_entity":q.BusinessGroupId.HasValue?"business_group":null;var scopeId=q.DepartmentId??q.UnitId??q.LegalEntityId??q.BusinessGroupId;var where="""u.organization_id=@org AND u.deleted_at IS NULL AND (@Search IS NULL OR u.name ILIKE '%'||@Search||'%' OR u.email ILIKE '%'||@Search||'%') AND (@Status IS NULL OR u.status=@Status) AND (@RoleCode IS NULL OR EXISTS(SELECT 1 FROM valorapesquisa.user_roles x JOIN valorapesquisa.roles r ON r.id=x.role_id WHERE x.user_id=u.id AND r.code=@RoleCode)) AND (@scopeId IS NULL OR EXISTS(SELECT 1 FROM valorapesquisa.user_scopes s WHERE s.organization_id=@org AND s.user_id=u.id AND s.scope_type=@scopeType AND s.scope_id=@scopeId AND s.deleted_at IS NULL))""";var order=q.SortBy.ToLowerInvariant() switch{"email"=>"u.email","status"=>"u.status","createdat"=>"u.created_at","lastloginat"=>"u.last_login_at",_=>"u.name"};var direction=q.SortDirection.Equals("desc",StringComparison.OrdinalIgnoreCase)?"DESC":"ASC";var p=new{org,q.Search,q.Status,q.RoleCode,scopeId,scopeType,offset=(q.Page-1)*q.PageSize,q.PageSize};var rows=(await c.QueryAsync<UserRow>(new CommandDefinition($"SELECT {Projection} FROM valorapesquisa.users u WHERE {where} ORDER BY {order} {direction},u.id LIMIT @PageSize OFFSET @offset",p,cancellationToken:ct))).AsList();var total=await c.ExecuteScalarAsync<long>(new CommandDefinition($"SELECT count(*) FROM valorapesquisa.users u WHERE {where}",p,cancellationToken:ct));var items=new List<UserAdministrationResponse>();foreach(var row in rows)items.Add(ToResponse(row,await Scopes(c,org,row.Id,ct)));return(items,total);}
 public async Task<UserAdministrationResponse?> GetAsync(Guid org,Guid id,CancellationToken ct=default){using var c=factory.Create();var r=await c.QuerySingleOrDefaultAsync<UserRow>(new CommandDefinition($"SELECT {Projection} FROM valorapesquisa.users u WHERE u.organization_id=@org AND u.id=@id AND u.deleted_at IS NULL",new{org,id},cancellationToken:ct));return r is null?null:ToResponse(r,await Scopes(c,org,id,ct));}
 public async Task<bool> UpdateAsync(Guid org,Guid id,UpdateUserRequest r,CancellationToken ct=default){using var c=factory.Create();return await c.ExecuteAsync(new CommandDefinition("UPDATE valorapesquisa.users SET name=trim(@Name),phone=@Phone,updated_at=now() WHERE organization_id=@org AND id=@id AND deleted_at IS NULL",new{org,id,r.Name,r.Phone},cancellationToken:ct))==1;}
 public async Task<bool> UpdateStatusAsync(Guid org,Guid id,string status,CancellationToken ct=default){using var c=factory.Create();return await c.ExecuteAsync(new CommandDefinition("UPDATE valorapesquisa.users SET status=@status,updated_at=now() WHERE organization_id=@org AND id=@id AND deleted_at IS NULL",new{org,id,status},cancellationToken:ct))==1;}
 public async Task<int> CountAdministratorsAsync(Guid org,CancellationToken ct=default){using var c=factory.Create();return await c.ExecuteScalarAsync<int>(new CommandDefinition("SELECT count(DISTINCT u.id) FROM valorapesquisa.users u JOIN valorapesquisa.user_roles ur ON ur.user_id=u.id JOIN valorapesquisa.roles r ON r.id=ur.role_id WHERE u.organization_id=@org AND u.status='active' AND u.deleted_at IS NULL AND r.code IN('admin_valora','admin_grupo','empresa_admin')",new{org},cancellationToken:ct));}
 public async Task<bool> IsAdministratorAsync(Guid org,Guid id,CancellationToken ct=default){using var c=factory.Create();return await c.ExecuteScalarAsync<bool>(new CommandDefinition("SELECT EXISTS(SELECT 1 FROM valorapesquisa.users u JOIN valorapesquisa.user_roles ur ON ur.user_id=u.id JOIN valorapesquisa.roles r ON r.id=ur.role_id WHERE u.organization_id=@org AND u.id=@id AND r.code IN('admin_valora','admin_grupo','empresa_admin'))",new{org,id},cancellationToken:ct));}
 public async Task ReplaceRolesAsync(Guid org,Guid id,IReadOnlyList<string> codes,CancellationToken ct=default){using var c=factory.Create();c.Open();using var tx=c.BeginTransaction();var exists=await c.ExecuteScalarAsync<bool>("SELECT EXISTS(SELECT 1 FROM valorapesquisa.users WHERE organization_id=@org AND id=@id AND deleted_at IS NULL)",new{org,id},tx);if(!exists)throw new InvalidOperationException("Usuário não encontrado.");var found=(await c.QueryAsync<Guid>("SELECT id FROM valorapesquisa.roles WHERE code=ANY(@codes) AND deleted_at IS NULL AND (organization_id IS NULL OR organization_id=@org)",new{org,codes=codes.ToArray()},tx)).AsList();if(found.Count!=codes.Count)throw new InvalidOperationException("Uma ou mais roles são inválidas.");await c.ExecuteAsync("DELETE FROM valorapesquisa.user_roles WHERE user_id=@id; INSERT INTO valorapesquisa.user_roles(user_id,role_id) SELECT @id,unnest(@found)",new{id,found=found.ToArray()},tx);tx.Commit();}
 public async Task ReplaceScopesAsync(Guid org,Guid id,IReadOnlyList<UserScopeRequest> scopes,CancellationToken ct=default){using var c=factory.Create();c.Open();using var tx=c.BeginTransaction();foreach(var s in scopes){var table=s.Type switch{"business_group"=>"business_groups","legal_entity"=>"legal_entities","unit"=>"units","department"=>"departments","organization"=>"organizations",_=>throw new InvalidOperationException("Tipo de escopo inválido.")};if(!await c.ExecuteScalarAsync<bool>($"SELECT EXISTS(SELECT 1 FROM valorapesquisa.{table} WHERE id=@Id AND {(table=="organizations"?"id":"organization_id") }=@org AND deleted_at IS NULL)",new{s.Id,org},tx))throw new InvalidOperationException("Escopo não pertence à organização.");}await c.ExecuteAsync("UPDATE valorapesquisa.user_scopes SET deleted_at=now() WHERE organization_id=@org AND user_id=@id AND deleted_at IS NULL",new{org,id},tx);foreach(var s in scopes)await c.ExecuteAsync("INSERT INTO valorapesquisa.user_scopes(organization_id,user_id,scope_type,scope_id) VALUES(@org,@id,@Type,@Id)",new{org,id,s.Type,s.Id},tx);tx.Commit();}
 private static async Task<IReadOnlyList<UserScopeResponse>> Scopes(System.Data.IDbConnection c,Guid org,Guid id,CancellationToken ct){const string sql="""SELECT s.scope_type Type,s.scope_id Id,CASE s.scope_type WHEN 'business_group' THEN bg.name WHEN 'legal_entity' THEN le.legal_name WHEN 'unit' THEN un.name WHEN 'department' THEN d.name ELSE o.public_name END Label,concat_ws(' › ',bg.name,le.trade_name,un.name,d.name) Breadcrumb FROM valorapesquisa.user_scopes s LEFT JOIN valorapesquisa.business_groups bg ON s.scope_type='business_group' AND bg.id=s.scope_id LEFT JOIN valorapesquisa.legal_entities le ON s.scope_type='legal_entity' AND le.id=s.scope_id LEFT JOIN valorapesquisa.units un ON s.scope_type='unit' AND un.id=s.scope_id LEFT JOIN valorapesquisa.departments d ON s.scope_type='department' AND d.id=s.scope_id LEFT JOIN valorapesquisa.organizations o ON s.scope_type='organization' AND o.id=s.scope_id WHERE s.organization_id=@org AND s.user_id=@id AND s.deleted_at IS NULL ORDER BY s.scope_type,Label""";return(await c.QueryAsync<UserScopeResponse>(new CommandDefinition(sql,new{org,id},cancellationToken:ct))).AsList();}
 private static UserAdministrationResponse ToResponse(UserRow x,IReadOnlyList<UserScopeResponse> scopes)=>new(x.Id,x.Name,x.Email,x.Phone,x.Status,x.RoleCodes,scopes,x.LastLoginAt,x.CreatedAt,x.UpdatedAt);
 private sealed record UserRow(Guid Id,string Name,string Email,string? Phone,string Status,string[] RoleCodes,DateTimeOffset? LastLoginAt,DateTimeOffset CreatedAt,DateTimeOffset? UpdatedAt);
}
