using Dapper;
using Valora.Application.Contracts.Database;
using Valora.Application.Workspace;

namespace Valora.Infrastructure.Repositories;

public sealed class WorkspaceRepository(IDbConnectionFactory connections) : IWorkspaceRepository
{
    private const string Columns = "w.id Id,w.item_type ItemType,w.title Title,w.summary Summary,w.status Status,w.priority Priority,w.due_at DueAt,w.owner_user_id OwnerUserId,w.source_type SourceType,w.source_id SourceId,w.route Route,w.created_at CreatedAt";
    public Task<IReadOnlyList<WorkspaceItemDto>> MyDayAsync(Guid o,Guid u,bool wide,CancellationToken ct)=>Query($"SELECT {Columns},EXISTS(SELECT 1 FROM valorapesquisa.user_pinned_items p WHERE p.organization_id=w.organization_id AND p.user_id=@u AND p.workspace_item_id=w.id) IsPinned FROM valorapesquisa.workspace_items w WHERE w.organization_id=@o AND w.status NOT IN ('completed','cancelled') AND (@wide OR w.owner_user_id=@u OR w.owner_user_id IS NULL) AND (w.due_at::date<=CURRENT_DATE OR w.priority='critical' OR w.item_type IN ('approval','evidence','governance_alert')) ORDER BY CASE w.priority WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END, w.due_at NULLS LAST LIMIT 100",o,u,ct);
    public Task<IReadOnlyList<WorkspaceItemDto>> RecentAsync(Guid o,Guid u,CancellationToken ct)=>Query($"SELECT {Columns},false IsPinned FROM valorapesquisa.user_recent_items r JOIN valorapesquisa.workspace_items w ON w.id=r.workspace_item_id AND w.organization_id=r.organization_id WHERE r.organization_id=@o AND r.user_id=@u ORDER BY r.opened_at DESC LIMIT 12",o,u,ct);
    public Task<IReadOnlyList<WorkspaceItemDto>> PinnedAsync(Guid o,Guid u,CancellationToken ct)=>Query($"SELECT {Columns},true IsPinned FROM valorapesquisa.user_pinned_items p JOIN valorapesquisa.workspace_items w ON w.id=p.workspace_item_id AND w.organization_id=p.organization_id WHERE p.organization_id=@o AND p.user_id=@u ORDER BY p.created_at DESC",o,u,ct);
    public async Task PinAsync(Guid o,Guid u,Guid id,CancellationToken ct){using var c=connections.Create();await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.user_pinned_items(organization_id,user_id,workspace_item_id) SELECT @o,@u,id FROM valorapesquisa.workspace_items WHERE id=@id AND organization_id=@o ON CONFLICT(organization_id,user_id,workspace_item_id) DO NOTHING",new{o,u,id},cancellationToken:ct));}
    public async Task UnpinAsync(Guid o,Guid u,Guid id,CancellationToken ct){using var c=connections.Create();await c.ExecuteAsync(new CommandDefinition("DELETE FROM valorapesquisa.user_pinned_items WHERE organization_id=@o AND user_id=@u AND workspace_item_id=@id",new{o,u,id},cancellationToken:ct));}
    private async Task<IReadOnlyList<WorkspaceItemDto>> Query(string sql,Guid o,Guid u,CancellationToken ct){using var c=connections.Create();return (await c.QueryAsync<WorkspaceItemDto>(new CommandDefinition(sql,new{o,u},cancellationToken:ct))).AsList();}
}

public sealed class GlobalSearchRepository(IDbConnectionFactory connections) : IGlobalSearchRepository
{
    public async Task<IReadOnlyList<SearchResultDto>> SearchAsync(Guid o,Guid u,string term,bool wide,CancellationToken ct){using var c=connections.Create();const string sql="SELECT id Id,result_type ResultType,title Title,description Description,route Route,updated_at UpdatedAt FROM valorapesquisa.global_search_index WHERE organization_id=@o AND search_vector @@ websearch_to_tsquery('simple',@term) AND (@wide OR allowed_user_id IS NULL OR allowed_user_id=@u) ORDER BY ts_rank(search_vector,websearch_to_tsquery('simple',@term)) DESC,updated_at DESC LIMIT 60";return(await c.QueryAsync<SearchResultDto>(new CommandDefinition(sql,new{o,u,term,wide},cancellationToken:ct))).AsList();}
    public async Task RecordAsync(Guid o,Guid u,string term,int count,CancellationToken ct){using var c=connections.Create();await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.global_search_events(organization_id,user_id,term,result_count) VALUES(@o,@u,@term,@count)",new{o,u,term,count},cancellationToken:ct));}
}
public sealed class QuickActionRepository(IDbConnectionFactory connections) : IQuickActionRepository
{
    public async Task<IReadOnlyList<QuickActionDto>> ListAsync(Guid o,CancellationToken ct){using var c=connections.Create();return(await c.QueryAsync<QuickActionDto>(new CommandDefinition("SELECT code Code,label Label,description Description,route Route,icon Icon,sort_order SortOrder FROM valorapesquisa.quick_actions WHERE enabled=true ORDER BY sort_order,code",cancellationToken:ct))).AsList();}
    public async Task RecordAsync(Guid o,Guid u,string code,CancellationToken ct){using var c=connections.Create();await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.quick_action_events(organization_id,user_id,action_code) VALUES(@o,@u,@code)",new{o,u,code},cancellationToken:ct));}
}
public sealed class ExecutivePriorityRepository(IDbConnectionFactory connections) : IExecutivePriorityRepository
{
    public async Task<IReadOnlyList<ExecutivePriorityDto>> ListAsync(Guid o,Guid u,bool wide,CancellationToken ct){using var c=connections.Create();const string sql="SELECT id Id,title Title,description Description,status Status,priority Priority,owner_user_id OwnerUserId,due_at DueAt,source_type SourceType,source_id SourceId,progress_percent ProgressPercent,updated_at UpdatedAt FROM valorapesquisa.executive_priorities WHERE organization_id=@o AND status NOT IN ('completed','cancelled') AND (@wide OR owner_user_id=@u OR owner_user_id IS NULL) ORDER BY CASE priority WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,due_at NULLS LAST";return(await c.QueryAsync<ExecutivePriorityDto>(new CommandDefinition(sql,new{o,u,wide},cancellationToken:ct))).AsList();}
    public async Task<ExecutivePriorityDto> CreateAsync(Guid o,Guid u,CreatePriorityRequest r,CancellationToken ct){using var c=connections.Create();const string sql="INSERT INTO valorapesquisa.executive_priorities(organization_id,title,description,priority,owner_user_id,due_at,source_type,source_id,created_by) VALUES(@o,@Title,@Description,@Priority,@OwnerUserId,@DueAt,@SourceType,@SourceId,@u) RETURNING id Id,title Title,description Description,status Status,priority Priority,owner_user_id OwnerUserId,due_at DueAt,source_type SourceType,source_id SourceId,progress_percent ProgressPercent,updated_at UpdatedAt";return await c.QuerySingleAsync<ExecutivePriorityDto>(new CommandDefinition(sql,new{o,u,r.Title,r.Description,r.Priority,r.OwnerUserId,r.DueAt,r.SourceType,r.SourceId},cancellationToken:ct));}
}
