using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Valora.Application.Contracts;
using Valora.Application.Forms;
using Valora.Infrastructure.Database;
using Valora.Infrastructure.Email;
using Valora.Infrastructure.Repositories;
using Valora.Infrastructure.Security;
using Valora.Application.Access;
using Valora.Application.Knowledge;
using Valora.Application.Enterprise;
using Valora.Application.OrganizationalIntelligence;
using Valora.Application.ValoraBot;
using Valora.Application.Methodology;
using Valora.Application.DiagnosticWorkspace;
using Valora.Application.Workspace;
using Valora.Application.CommercialDelivery;
using Valora.Application.Integrations;
using Valora.Application.DecisionCenter;
using Valora.Application.FormalDeliverables;
using Valora.Application.ValoraAi;
using Valora.Application.ActionCenter;
using Valora.Application.Evolution;
using Valora.Application.Journey;
using Valora.Application.OneOnOne;
using Valora.Infrastructure.FormalDeliverables;
using Valora.Application.Communication;
using Valora.Application.SecurityCompliance;
using Valora.Application.SuccessCenter;
using Valora.Application.Subscriptions;
using Valora.Infrastructure.Subscriptions;
using Valora.Application.Experience;
using Valora.Application.GovernanceExecution;
using Valora.Application.OrganizationalArchitecture;
using Valora.Application.Indicators;
using Valora.Application.Advisor;
using Valora.Application.Processes;
using Valora.Infrastructure.Processes;
using Valora.Application.Benchmarks;
using Valora.Infrastructure.Benchmarks;
using Valora.Application.People;
using Valora.Infrastructure.People;

namespace Valora.Infrastructure.DependencyInjection;

public static class InfrastructureServiceCollectionExtensions
{
    public static IServiceCollection AddInfrastructureServices(this IServiceCollection services, IConfiguration configuration)
    {
        services.AddScoped<PeopleRepository>();
        services.AddScoped<IPeopleProfileRepository>(sp=>sp.GetRequiredService<PeopleRepository>());
        services.AddScoped<IPeopleTeamRepository>(sp=>sp.GetRequiredService<PeopleRepository>());
        services.AddScoped<ICultureAssessmentRepository>(sp=>sp.GetRequiredService<PeopleRepository>());
        services.AddScoped<IEngagementSignalRepository>(sp=>sp.GetRequiredService<PeopleRepository>());
        services.AddScoped<ICompetencyRepository>(sp=>sp.GetRequiredService<PeopleRepository>());
        services.AddScoped<IDevelopmentPlanRepository>(sp=>sp.GetRequiredService<PeopleRepository>());
        services.AddScoped<IPeopleRiskSignalRepository>(sp=>sp.GetRequiredService<PeopleRepository>());
        services.AddScoped<BenchmarkRepository>();
        services.AddScoped<IBenchmarkCohortRepository>(sp=>sp.GetRequiredService<BenchmarkRepository>());
        services.AddScoped<IBenchmarkSnapshotRepository>(sp=>sp.GetRequiredService<BenchmarkRepository>());
        services.AddScoped<IBenchmarkMetricRepository>(sp=>sp.GetRequiredService<BenchmarkRepository>());
        services.AddScoped<IBenchmarkComparisonRepository>(sp=>sp.GetRequiredService<BenchmarkRepository>());
        services.AddScoped<IBenchmarkInsightRepository>(sp=>sp.GetRequiredService<BenchmarkRepository>());
        services.AddScoped<IBenchmarkPrivacyRepository>(sp=>sp.GetRequiredService<BenchmarkRepository>());
        services.AddScoped<IBenchmarkExportRepository>(sp=>sp.GetRequiredService<BenchmarkRepository>());
        services.AddScoped<ProcessRepository>();
        services.AddScoped<IProcessDefinitionRepository>(sp=>sp.GetRequiredService<ProcessRepository>());
        services.AddScoped<IProcessStepRepository>(sp=>sp.GetRequiredService<ProcessRepository>());
        services.AddScoped<IProcessInstanceRepository>(sp=>sp.GetRequiredService<ProcessRepository>());
        services.AddScoped<IProcessApprovalRepository>(sp=>sp.GetRequiredService<ProcessRepository>());
        services.AddScoped<IProcessSlaRepository>(sp=>sp.GetRequiredService<ProcessRepository>());
        services.AddScoped<IProcessAutomationRepository>(sp=>sp.GetRequiredService<ProcessRepository>());
        services.AddScoped<IProcessInsightRepository>(sp=>sp.GetRequiredService<ProcessRepository>());
        services.AddScoped<IProcessTemplateRepository>(sp=>sp.GetRequiredService<ProcessRepository>());
        services.AddScoped<AdvisorRepository>();
        services.AddScoped<IAdvisorConversationRepository>(sp => sp.GetRequiredService<AdvisorRepository>());
        services.AddScoped<IAdvisorMessageRepository>(sp => sp.GetRequiredService<AdvisorRepository>());
        services.AddScoped<IAdvisorContextBundleRepository>(sp => sp.GetRequiredService<AdvisorRepository>());
        services.AddScoped<IAdvisorPromptTemplateRepository>(sp => sp.GetRequiredService<AdvisorRepository>());
        services.AddScoped<IAdvisorGuardrailRepository>(sp => sp.GetRequiredService<AdvisorRepository>());
        services.AddScoped<IAdvisorFeedbackRepository>(sp => sp.GetRequiredService<AdvisorRepository>());
        services.AddScoped<IAdvisorUsageRepository>(sp => sp.GetRequiredService<AdvisorRepository>());
        services.AddScoped<IDbConnectionFactory, PostgresConnectionFactory>();
        services.AddScoped<IIndicatorRepository, IndicatorRepository>();
        services.AddScoped<IKnowledgeRepository, KnowledgeRepository>();
        services.AddScoped<IOrganizationalArchitectureRepository, OrganizationalArchitectureRepository>();
        services.AddScoped<IGovernanceExecutionStore, GovernanceExecutionStore>();
        services.AddScoped<IRespondentAccessTokenRepository, RespondentAccessTokenRepository>();
        services.AddScoped<IRespondentSessionRepository, RespondentSessionRepository>();
        services.AddScoped<IPublicResultViewRepository, PublicResultViewRepository>();
        services.AddScoped<IDiagnosticInvitationBatchRepository, DiagnosticInvitationBatchRepository>();
        services.AddScoped<IExecutiveResultPortalRepository, ExecutiveResultPortalRepository>();
        services.AddScoped<ISubscriptionPlanRepository, SubscriptionPlanRepository>();
        services.AddScoped<IOrganizationSubscriptionRepository, OrganizationSubscriptionRepository>();
        services.AddScoped<IUsageCounterRepository, UsageCounterRepository>();
        services.AddScoped<IUpgradeRequestRepository, UpgradeRequestRepository>();
        services.AddScoped<IDbTransactionFactory, DbTransactionFactory>();
        services.AddScoped<MigrationRunner>();
        services.AddScoped<SchemaContractValidator>();
        services.AddScoped<IOrganizationRepository, OrganizationRepository>();
        services.AddScoped<ISaasAdministrationRepository, SaasAdministrationRepository>();
        services.AddScoped<IOrganizationStructureRepository, OrganizationStructureRepository>();
        services.AddScoped<IOrganizationBrandingRepository, OrganizationBrandingRepository>();
        services.AddScoped<IUserAdministrationRepository, UserAdministrationRepository>();
        services.AddScoped<Valora.Application.CompanyRegistration.ICompanyRegistrationRepository, CompanyRegistrationRepository>();
        services.AddScoped<IUserRepository, UserRepository>();
        services.AddScoped<ISessionRepository, SessionRepository>();
        services.AddScoped<IRefreshTokenRepository, RefreshTokenRepository>();
        services.AddScoped<IPermissionRepository, PermissionRepository>();
        services.AddScoped<IAccessAdministrationRepository, AccessAdministrationRepository>();
        services.AddScoped<IPlanRepository, PlanRepository>();
        services.AddScoped<ISurveyRepository, SurveyRepository>();
        services.AddScoped<IResponseRepository, ResponseRepository>();
        services.AddScoped<IFormRepository, FormRepository>();
        services.AddScoped<IFormAdministrationRepository, FormAdministrationRepository>();
        services.AddScoped<IResultRepository, ResultRepository>();
        services.AddScoped<ICertificateRepository, CertificateRepository>();
        services.AddScoped<ICommunicationRepository, CommunicationRepository>();
        services.AddScoped<INotificationRepository, NotificationRepository>();
        services.AddScoped<INotificationTemplateRepository, NotificationTemplateRepository>();
        services.AddScoped<ICommunicationOutboxRepository, CommunicationOutboxRepository>();
        services.AddScoped<IReminderRepository, ReminderRepository>();
        services.AddScoped<ICommunicationAuditRepository, CommunicationAuditRepository>();
        services.AddScoped<IMigrationRepository, MigrationRepository>();
        services.AddScoped<IAuditRepository, AuditRepository>();
        services.AddScoped<IFreeDiagnosticsRepository, FreeDiagnosticsRepository>();
        services.AddScoped<IModuleRepository, ModuleRepository>();
        services.AddScoped<ISubscriptionRepository, SubscriptionRepository>();
        services.AddScoped<IUsageRepository, UsageRepository>();
        services.AddScoped<IDashboardMetricsRepository, DashboardMetricsRepository>();
        services.AddScoped<IReportRepository, ReportRepository>();
        services.AddScoped<ICertificateOperationalRepository, CertificateOperationalRepository>();
        services.AddScoped<IExportRepository, ExportRepository>();
        services.AddScoped<ILgpdRepository, LgpdRepository>();
        services.AddScoped<IEmailOperationalRepository, EmailOperationalRepository>();
        services.AddScoped<IMigrationBatchRepository, MigrationBatchRepository>();
        services.AddScoped<IMigrationSourceFileRepository, MigrationSourceFileRepository>();
        services.AddScoped<IMigrationRecordRepository, MigrationRecordRepository>();
        services.AddScoped<IMigrationMappingRepository, MigrationMappingRepository>();
        services.AddScoped<IMigrationConflictRepository, MigrationConflictRepository>();
        services.AddScoped<IMigrationRollbackRepository, MigrationRollbackRepository>();
        services.AddScoped<IJwtTokenService, JwtTokenService>();
        services.AddScoped<IPasswordHasher, BCryptPasswordHasher>();
        services.AddScoped<IEmailSender, SmtpEmailSender>();
        services.AddScoped<IEnterpriseRepository, EnterpriseRepository>();
        services.AddScoped<IIntegrationRepository, IntegrationRepository>();
        services.AddScoped<IOrganizationalIntelligenceRepository, OrganizationalIntelligenceRepository>();
        services.AddScoped<IDecisionCenterRepository, DecisionCenterRepository>();
        services.AddScoped<IActionPlanRepository, ActionPlanRepository>(); services.AddScoped<IActionItemRepository, ActionItemRepository>(); services.AddScoped<IRecommendationRepository, RecommendationRepository>(); services.AddScoped<IEvolutionRepository, EvolutionRepository>(); services.AddScoped<IJourneyRepository, JourneyRepository>();
        services.AddScoped<IOneOnOneRepository, OneOnOneRepository>(); services.AddScoped<ILeadershipProfileRepository, LeadershipProfileRepository>(); services.AddScoped<ILeadershipDevelopmentRepository, LeadershipDevelopmentRepository>();
        services.AddScoped<IIntelligencePipelineRepository, IntelligencePipelineRepository>();
        services.AddScoped<IBenchmarkRepository, BenchmarkRepository>();
        services.AddScoped<Valora.Application.Heatmap.IHeatmapRepository, HeatmapRepository>();
        services.AddScoped<IIntelligenceProcessingJobRepository, IntelligenceProcessingJobRepository>();
        services.AddScoped<IValoraBotRepository, ValoraBotRepository>();
        services.AddScoped<IMethodologyRepository, MethodologyRepository>();
        services.AddScoped<IMethodologyStudioRepository, MethodologyStudioRepository>();
        services.AddScoped<IDiagnosticWorkspaceRepository, DiagnosticWorkspaceRepository>();
        services.AddScoped<IWorkspaceRepository, WorkspaceRepository>();
        services.AddScoped<IGlobalSearchRepository, GlobalSearchRepository>();
        services.AddScoped<IQuickActionRepository, QuickActionRepository>();
        services.AddScoped<IExecutivePriorityRepository, ExecutivePriorityRepository>();
        services.AddScoped<IDiagnosticCampaignRepository, DiagnosticCampaignRepository>();
        services.AddScoped<IAssistedOperationsRepository, AssistedOperationsRepository>();
        services.AddScoped<ISuccessCenterRepository, SuccessCenterRepository>();
        services.AddScoped<IPublicCommercialRepository, PublicCommercialRepository>();
        services.AddAiAndFormalDeliverablePersistence();
        services.AddScoped<IDocumentAccessPolicy, DocumentAccessPolicy>();
        services.AddScoped<IDocumentStore, DocumentStore>();
        services.AddScoped<IPrivacyConsentRepository, PrivacyConsentRepository>();
        services.AddScoped<IDataSubjectRequestRepository, DataSubjectRequestRepository>();
        services.AddScoped<IDataRetentionRepository, DataRetentionRepository>();
        services.AddScoped<ISecurityIncidentRepository, SecurityIncidentRepository>();
        services.AddScoped<IAccessReviewRepository, AccessReviewRepository>();
        services.AddScoped<IComplianceAuditRepository, ComplianceAuditRepository>();
        services.AddScoped<PrivacyConsentService>(); services.AddScoped<DataSubjectRequestService>();
        services.AddScoped<DataRetentionService>(); services.AddScoped<SecurityIncidentService>();
        services.AddScoped<AccessReviewService>(); services.AddScoped<ComplianceAuditService>(); services.AddScoped<SensitiveAccessLogService>();
        services.AddScoped<RegisterPrivacyConsentUseCase>(); services.AddScoped<RevokePrivacyConsentUseCase>();
        services.AddScoped<CreateDataSubjectRequestUseCase>(); services.AddScoped<CompleteDataSubjectRequestUseCase>();
        services.AddScoped<ConfigureRetentionPolicyUseCase>(); services.AddScoped<RunRetentionJobUseCase>();
        services.AddScoped<RegisterSecurityIncidentUseCase>(); services.AddScoped<ResolveSecurityIncidentUseCase>();
        services.AddScoped<StartAccessReviewCycleUseCase>(); services.AddScoped<CompleteAccessReviewCycleUseCase>(); services.AddScoped<LogSensitiveDataAccessUseCase>();
        services.AddScoped<IExportAuditService, ExportAuditService>();
        return services;
    }

    private static IServiceCollection AddAiAndFormalDeliverablePersistence(this IServiceCollection services)
    {
        services.AddScoped<IValoraAiRunRepository, ValoraAiRunRepository>();
        services.AddScoped<IValoraAiEvidenceRepository, ValoraAiEvidenceRepository>();
        services.AddScoped<IValoraAiInsightRepository, ValoraAiInsightRepository>();
        services.AddScoped<IValoraAiReviewRepository, ValoraAiReviewRepository>();
        services.AddScoped<IValoraAiFeedbackRepository, ValoraAiFeedbackRepository>();
        services.AddScoped<IDiagnosisDocumentSnapshotProvider, DiagnosisDocumentSnapshotProvider>();
        services.AddScoped<IShareLinkRepository, ShareLinkRepository>();
        return services;
    }

    public static IServiceCollection AddValoraInfrastructure(this IServiceCollection services) => services;
}
