using Dapper;
using Valora.Application.Contracts;
using Valora.Application.People;

namespace Valora.Infrastructure.People;

public sealed class PeopleRepository(IDbConnectionFactory connections,IDbTransactionFactory transactions):IPeopleProfileRepository,IPeopleTeamRepository,ICultureAssessmentRepository,IEngagementSignalRepository,ICompetencyRepository,IDevelopmentPlanRepository,IPeopleRiskSignalRepository
{
    public async Task<IReadOnlyList<PeopleProfileDto>> List(Guid o,CancellationToken ct){const string sql="SELECT id,display_name DisplayName,status,role_title RoleTitle,created_at CreatedAt FROM valorapesquisa.people_profiles WHERE organization_id=@o AND deleted_at IS NULL ORDER BY display_name";using var c=connections.Create();return(await c.QueryAsync<PeopleProfileDto>(new CommandDefinition(sql,new{o},cancellationToken:ct))).ToList();}
    public async Task<Guid> Create(Guid o,Guid user,CreatePeopleProfileRequest r,CancellationToken ct){var id=Guid.NewGuid();using var c=connections.Create();await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.people_profiles(id,organization_id,display_name,role_title,status,created_by_user_id) VALUES(@id,@o,@DisplayName,@RoleTitle,'active',@user)",new{id,o,user,r.DisplayName,r.RoleTitle},cancellationToken:ct));await Event(c,o,id,user,"people.profile.created",ct);return id;}
    async Task<IReadOnlyList<PeopleTeamDto>> IPeopleTeamRepository.List(Guid o,CancellationToken ct){const string sql="SELECT t.id,t.name,t.responsible_profile_id ResponsibleProfileId,p.display_name ResponsibleName,count(m.id) FILTER(WHERE m.ended_at IS NULL)::int MemberCount,t.created_at CreatedAt FROM valorapesquisa.people_teams t JOIN valorapesquisa.people_profiles p ON p.id=t.responsible_profile_id AND p.organization_id=t.organization_id LEFT JOIN valorapesquisa.people_team_members m ON m.team_id=t.id AND m.organization_id=t.organization_id WHERE t.organization_id=@o AND t.deleted_at IS NULL GROUP BY t.id,p.display_name ORDER BY t.name";using var c=connections.Create();return(await c.QueryAsync<PeopleTeamDto>(new CommandDefinition(sql,new{o},cancellationToken:ct))).ToList();}
    public async Task<Guid> Create(Guid o,Guid user,CreatePeopleTeamRequest r,CancellationToken ct){var id=Guid.NewGuid();using var c=connections.Create();var n=await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.people_teams(id,organization_id,name,responsible_profile_id,created_by_user_id) SELECT @id,@o,@Name,@ResponsibleProfileId,@user FROM valorapesquisa.people_profiles p WHERE p.id=@ResponsibleProfileId AND p.organization_id=@o AND p.status='active' AND p.deleted_at IS NULL",new{id,o,user,r.Name,r.ResponsibleProfileId},cancellationToken:ct));if(n==0)throw new InvalidOperationException("A liderança selecionada não possui vínculo ativo nesta organização.");await Event(c,o,id,user,"people.team.created",ct);return id;}
    async Task<IReadOnlyList<CultureAssessmentDto>> ICultureAssessmentRepository.List(Guid o,CancellationToken ct){const string sql="SELECT a.id,d.name Dimension,a.source,a.evidence_summary EvidenceSummary,a.score,a.sample_size SampleSize,a.confidence,a.limitations,a.assessed_at AssessedAt FROM valorapesquisa.people_culture_assessments a JOIN valorapesquisa.people_culture_dimensions d ON d.id=a.dimension_id AND d.organization_id=a.organization_id WHERE a.organization_id=@o AND a.deleted_at IS NULL AND a.sample_size>=5 ORDER BY a.assessed_at DESC";using var c=connections.Create();return(await c.QueryAsync<CultureAssessmentDto>(new CommandDefinition(sql,new{o},cancellationToken:ct))).ToList();}
    public async Task<Guid>Create(Guid o,Guid user,CreateCultureAssessmentRequest r,string confidence,CancellationToken ct){var id=Guid.NewGuid();using var c=connections.Create();var n=await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.people_culture_assessments(id,organization_id,dimension_id,source,evidence_summary,score,sample_size,confidence,limitations,created_by_user_id) SELECT @id,@o,@DimensionId,@Source,@EvidenceSummary,@Score,@SampleSize,@confidence,coalesce(@Limitations,'A leitura é agregada e não deve ser usada para classificar indivíduos.'),@user FROM valorapesquisa.people_culture_dimensions d WHERE d.id=@DimensionId AND d.organization_id=@o AND d.deleted_at IS NULL",new{id,o,user,confidence,r.DimensionId,r.Source,r.EvidenceSummary,r.Score,r.SampleSize,r.Limitations},cancellationToken:ct));if(n==0)throw new InvalidOperationException("Dimensão cultural não encontrada nesta organização.");await Event(c,o,id,user,"people.culture.assessed",ct);return id;}
    async Task<IReadOnlyList<EngagementSignalDto>> IEngagementSignalRepository.List(Guid o,CancellationToken ct){const string sql="SELECT id,source,evidence_summary EvidenceSummary,score,confidence,limitations,observed_at ObservedAt FROM valorapesquisa.people_engagement_signals WHERE organization_id=@o AND deleted_at IS NULL ORDER BY observed_at DESC";using var c=connections.Create();return(await c.QueryAsync<EngagementSignalDto>(new CommandDefinition(sql,new{o},cancellationToken:ct))).ToList();}
    public async Task<Guid>Create(Guid o,Guid user,CreateEngagementSignalRequest r,string confidence,CancellationToken ct){var id=Guid.NewGuid();using var c=connections.Create();await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.people_engagement_signals(id,organization_id,source,evidence_summary,score,confidence,limitations,created_by_user_id) VALUES(@id,@o,@Source,@EvidenceSummary,@Score,@confidence,coalesce(@Limitations,'Sinal isolado; não representa conclusão sobre pessoas ou equipes.'),@user)",new{id,o,user,confidence,r.Source,r.EvidenceSummary,r.Score,r.Limitations},cancellationToken:ct));await Event(c,o,id,user,"people.engagement.signal_registered",ct);return id;}
    async Task<IReadOnlyList<CompetencyAssessmentDto>> ICompetencyRepository.List(Guid o,CancellationToken ct){const string sql="SELECT a.id,c.name Competency,a.subject_type SubjectType,a.expected_level ExpectedLevel,a.observed_level ObservedLevel,a.evidence_summary EvidenceSummary,a.human_reviewed HumanReviewed,a.assessed_at AssessedAt FROM valorapesquisa.people_competency_assessments a JOIN valorapesquisa.people_competencies c ON c.id=a.competency_id AND c.organization_id=a.organization_id WHERE a.organization_id=@o AND a.deleted_at IS NULL ORDER BY a.assessed_at DESC";using var c=connections.Create();return(await c.QueryAsync<CompetencyAssessmentDto>(new CommandDefinition(sql,new{o},cancellationToken:ct))).ToList();}
    public async Task<Guid>Assess(Guid o,Guid user,CreateCompetencyAssessmentRequest r,CancellationToken ct){var id=Guid.NewGuid();var type=r.ProfileId.HasValue?"person":"team";using var c=connections.Create();var n=await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.people_competency_assessments(id,organization_id,competency_id,subject_type,profile_id,team_id,expected_level,observed_level,evidence_summary,human_reviewed,reviewed_by_user_id,created_by_user_id) SELECT @id,@o,c.id,@type,@ProfileId,@TeamId,@ExpectedLevel,@ObservedLevel,@EvidenceSummary,true,@user,@user FROM valorapesquisa.people_competencies c WHERE c.id=@CompetencyId AND c.organization_id=@o AND ((@ProfileId IS NOT NULL AND EXISTS(SELECT 1 FROM valorapesquisa.people_profiles p WHERE p.id=@ProfileId AND p.organization_id=@o)) OR (@TeamId IS NOT NULL AND EXISTS(SELECT 1 FROM valorapesquisa.people_teams t WHERE t.id=@TeamId AND t.organization_id=@o)))",new{id,o,user,type,r.CompetencyId,r.ProfileId,r.TeamId,r.ExpectedLevel,r.ObservedLevel,r.EvidenceSummary},cancellationToken:ct));if(n==0)throw new InvalidOperationException("Competência ou vínculo não encontrado nesta organização.");await Event(c,o,id,user,"people.competency.assessed",ct);return id;}
    async Task<IReadOnlyList<DevelopmentPlanDto>> IDevelopmentPlanRepository.List(Guid o,CancellationToken ct){const string sql="SELECT d.id,d.subject_type SubjectType,coalesce(p.display_name,t.name) SubjectName,d.objective,r.display_name ResponsibleName,d.due_date DueDate,d.status,count(i.id) FILTER(WHERE i.status<>'completed')::int OpenItems,d.created_at CreatedAt FROM valorapesquisa.people_development_plans d LEFT JOIN valorapesquisa.people_profiles p ON p.id=d.profile_id LEFT JOIN valorapesquisa.people_teams t ON t.id=d.team_id JOIN valorapesquisa.people_profiles r ON r.id=d.responsible_profile_id LEFT JOIN valorapesquisa.people_development_plan_items i ON i.development_plan_id=d.id WHERE d.organization_id=@o AND d.deleted_at IS NULL GROUP BY d.id,p.display_name,t.name,r.display_name ORDER BY d.due_date";using var c=connections.Create();return(await c.QueryAsync<DevelopmentPlanDto>(new CommandDefinition(sql,new{o},cancellationToken:ct))).ToList();}
    public async Task<Guid>Create(Guid o,Guid user,CreateDevelopmentPlanRequest r,CancellationToken ct){var id=Guid.NewGuid();var type=r.ProfileId.HasValue?"person":"team";await using var u=await transactions.BeginAsync(ct);var n=await u.Connection.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.people_development_plans(id,organization_id,subject_type,profile_id,team_id,objective,responsible_profile_id,due_date,status,created_by_user_id) SELECT @id,@o,@type,@ProfileId,@TeamId,@Objective,@ResponsibleProfileId,@DueDate,'active',@user WHERE EXISTS(SELECT 1 FROM valorapesquisa.people_profiles x WHERE x.id=@ResponsibleProfileId AND x.organization_id=@o) AND ((@ProfileId IS NOT NULL AND EXISTS(SELECT 1 FROM valorapesquisa.people_profiles x WHERE x.id=@ProfileId AND x.organization_id=@o)) OR (@TeamId IS NOT NULL AND EXISTS(SELECT 1 FROM valorapesquisa.people_teams x WHERE x.id=@TeamId AND x.organization_id=@o)))",new{id,o,user,type,r.ProfileId,r.TeamId,r.Objective,r.ResponsibleProfileId,r.DueDate},u.Transaction,cancellationToken:ct));if(n==0)throw new InvalidOperationException("Pessoa, time ou responsável não pertence à organização selecionada.");foreach(var action in r.Actions.Where(x=>!string.IsNullOrWhiteSpace(x)))await u.Connection.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.people_development_plan_items(organization_id,development_plan_id,description,status) VALUES(@o,@id,@action,'open')",new{o,id,action=action.Trim()},u.Transaction,cancellationToken:ct));await Event(u.Connection,o,id,user,"people.development_plan.created",ct,u.Transaction);await u.CommitAsync();return id;}
    async Task<IReadOnlyList<PeopleRiskSignalDto>> IPeopleRiskSignalRepository.List(Guid o,CancellationToken ct){const string sql="SELECT id,signal_type SignalType,evidence_summary EvidenceSummary,confidence,limitations,status,human_reviewed HumanReviewed,created_at CreatedAt FROM valorapesquisa.people_risk_signals WHERE organization_id=@o AND deleted_at IS NULL ORDER BY created_at DESC";using var c=connections.Create();return(await c.QueryAsync<PeopleRiskSignalDto>(new CommandDefinition(sql,new{o},cancellationToken:ct))).ToList();}
    public async Task Review(Guid o,Guid user,ReviewPeopleRiskRequest r,CancellationToken ct){using var c=connections.Create();var n=await c.ExecuteAsync(new CommandDefinition("UPDATE valorapesquisa.people_risk_signals SET status=@Decision,review_notes=@ReviewNotes,human_reviewed=true,reviewed_by_user_id=@user,reviewed_at=now(),updated_at=now() WHERE id=@RiskSignalId AND organization_id=@o AND deleted_at IS NULL",new{o,user,r.RiskSignalId,r.Decision,r.ReviewNotes},cancellationToken:ct));if(n==0)throw new InvalidOperationException("Sinal de risco não encontrado nesta organização.");await Event(c,o,r.RiskSignalId,user,"people.risk_signal.reviewed",ct);}
    private static Task Event(System.Data.IDbConnection c,Guid o,Guid entity,Guid user,string type,CancellationToken ct,System.Data.IDbTransaction? tx=null)=>c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.people_culture_events(organization_id,event_type,entity_id,performed_by_user_id,evidence_summary) VALUES(@o,@type,@entity,@user,'Evento registrado com escopo organizacional e decisão humana preservada.')",new{o,type,entity,user},tx,cancellationToken:ct));
}
