using ValoraPesquisa.Application.Services;
using ValoraPesquisa.Domain.Entities;
namespace ValoraPesquisa.Tests;
public class FoundationTests{
 [Fact] public void Calculator_Covers_All_Types_Weights_And_Levels(){var qc=new QuestionScoreCalculator();var calc=new SurveyResultCalculator(qc);var q1=Q("scale",5,2);var q2=Q("single_choice",5,1,Opts(2,5));var q3=Q("multiple_choice",5,1,Opts(2,2));var q4=Q("short_text",5,1);var qs=new[]{q1,q2,q3,q4};var ans=new[]{A(q1,"5",null),A(q2,q2.Options[1].Id.ToString(),null),A(q3,string.Join(',',q3.Options.Select(o=>o.Id)),null),A(q4,null,"ok")};var r=calc.Calculate(Guid.NewGuid(),qs,ans);Assert.Equal("Avançado",r.Level);Assert.True(r.TotalScore>0);Assert.Equal(25,r.MaxScore);var low=calc.Calculate(Guid.NewGuid(),new[]{q1},new[]{A(q1,"1",null)});Assert.Equal("Inicial",low.Level);var mid=calc.Calculate(Guid.NewGuid(),new[]{q1},new[]{A(q1,"3",null)});Assert.Equal("Intermediário",mid.Level);} 
 [Fact] public void Api_Controllers_Do_Not_Return_Sensitive_Hashes(){var text=ReadAll("src/ValoraPesquisa.Api/Controllers")+ReadAll("src/ValoraPesquisa.Application/DTOs");Assert.DoesNotContain("password_hash",text);Assert.DoesNotContain("token_hash",text);Assert.DoesNotContain("result_token_hash",text);Assert.DoesNotContain("new{u.PasswordHash",text);Assert.DoesNotContain("new{u.TokenHash",text);Assert.DoesNotContain("new{u.ResultTokenHash",text);} 
 [Fact] public void Login_Invalid_Error_Does_Not_Expose_StackTrace(){var text=Read("src/ValoraPesquisa.Api/Middleware/ErrorHandlingMiddleware.cs");Assert.Contains("correlationId",text);Assert.DoesNotContain("StackTrace",text);} 
 [Fact] public void Sql_Has_All_Minimum_Tables_And_Indexes(){var sql=Read("database/postgresql/scriptbd_completo.sql");foreach(var t in new[]{"organizations","users","forms","questions","question_options","surveys","survey_links","responses","response_answers","result_scores","audit_logs"})Assert.Contains($"create table if not exists valorapesquisa.{t}",sql);foreach(var i in new[]{"ix_users_email","ix_users_organization_id","ix_organizations_slug","ix_forms_organization_id","ix_surveys_organization_id","ix_survey_links_survey_id","ix_survey_links_token_hash","ix_responses_organization_id","ix_responses_survey_id","ix_responses_result_token_hash","ix_audit_logs_organization_created_at"})Assert.Contains(i,sql);} 
 [Fact] public void Repositories_Use_Organization_Filters_And_Hash_Tokens(){var text=Read("src/ValoraPesquisa.Infrastructure/Repositories/SurveyLinkRepository.cs");Assert.Contains("organization_id=@OrganizationId",text);Assert.Contains("token_hash",text);Assert.Contains("result_token_hash",text);Assert.Contains("hasher.Hash(token)",text);Assert.Contains("Clean(metadata)",text);} 
 static string Read(string relative){var d=new DirectoryInfo(AppContext.BaseDirectory); while(d!=null&&!File.Exists(Path.Combine(d.FullName,"ValoraPesquisa.sln"))) d=d.Parent; if(d==null) throw new DirectoryNotFoundException("backend-v2 não encontrado."); return File.ReadAllText(Path.Combine(d.FullName,relative));}
 static string ReadAll(string relativeDir){var d=new DirectoryInfo(AppContext.BaseDirectory); while(d!=null&&!File.Exists(Path.Combine(d.FullName,"ValoraPesquisa.sln"))) d=d.Parent; if(d==null) throw new DirectoryNotFoundException("backend-v2 não encontrado."); return string.Join("\n",Directory.GetFiles(Path.Combine(d.FullName,relativeDir),"*.cs",SearchOption.AllDirectories).Select(File.ReadAllText));}
 static Question Q(string type,decimal max,decimal weight,List<QuestionOption>? opts=null){var id=Guid.NewGuid();return new(Guid.NewGuid(),Guid.NewGuid(),"Q",type,1,true,weight,max,opts??new());} static List<QuestionOption> Opts(params decimal[] scores){var qid=Guid.NewGuid();return scores.Select((s,i)=>new QuestionOption(Guid.NewGuid(),qid,"O"+i,s,i+1)).ToList();} static ResponseAnswer A(Question q,string? v,string? t)=>new(Guid.NewGuid(),Guid.NewGuid(),q.Id,v,t);
}
public class Sprint03SecurityAndSqlTests{
 [Fact] public void TokenHasher_And_BCrypt_Are_Configured(){var sec=Read("src/ValoraPesquisa.Infrastructure/Security/SecurityServices.cs");Assert.Contains("SHA256",sec);Assert.Contains("RandomNumberGenerator.GetBytes",sec);Assert.Contains("BCrypt",sec);}
 [Fact] public void Web_Does_Not_Render_Raw_Json_Or_Hashes(){var js=Read("src/ValoraPesquisa.Web/wwwroot/js/site.js");Assert.DoesNotContain("JSON.stringify(r)",js);Assert.DoesNotContain("password_hash",js);Assert.DoesNotContain("token_hash",js);Assert.DoesNotContain("result_token_hash",js);}
 [Fact] public void Split_Controller_And_Repository_Files_Exist(){foreach(var f in new[]{"ApiBase.cs","OrganizationsController.cs","UsersController.cs","FormsController.cs","SurveysController.cs","SurveyLinksController.cs","PublicSurveysController.cs","PublicResultsController.cs","ResponsesController.cs","AuditController.cs"})Assert.True(File.Exists(Path.Combine(Root,"src/ValoraPesquisa.Api/Controllers",f)),f);foreach(var f in new[]{"Scope.cs","AuditService.cs","OrganizationRepository.cs","UserRepository.cs","FormRepository.cs","SurveyRepository.cs","SurveyLinkRepository.cs","ResponseRepository.cs"})Assert.True(File.Exists(Path.Combine(Root,"src/ValoraPesquisa.Infrastructure/Repositories",f)),f);}
 [Fact] public void Sql_Seed_Is_Idempotent_And_Useful(){var sql=Read("database/postgresql/scriptbd_completo.sql");Assert.Contains("on conflict",sql);Assert.Contains("admin@valoragroup.com",sql);Assert.Contains("gestor@empresa.com",sql);Assert.Contains("Pesquisa demo publicada",sql);}
 static string Root{get{var d=new DirectoryInfo(AppContext.BaseDirectory); while(d!=null&&!File.Exists(Path.Combine(d.FullName,"ValoraPesquisa.sln"))) d=d.Parent; if(d==null) throw new DirectoryNotFoundException("backend-v2 não encontrado."); return d.FullName;}}
 static string Read(string relative)=>File.ReadAllText(Path.Combine(Root,relative));
}
