using ValoraPesquisa.Application.Contracts; using ValoraPesquisa.Application.DTOs; using ValoraPesquisa.Application.Services; using ValoraPesquisa.Domain.Enums;
namespace ValoraPesquisa.Tests;
public class Sprint04SaasTests{
 [Theory] [InlineData("admin_valora",SaasActions.ManagePlans,true)] [InlineData("consultor_valora",SaasActions.ViewReports,true)] [InlineData("empresa_admin",SaasActions.ManageUsers,true)] [InlineData("gestor_pesquisa",SaasActions.CreateSurveys,true)] [InlineData("analista_resultados",SaasActions.CreateSurveys,false)] [InlineData("gestor_area",SaasActions.ViewReports,true)] [InlineData("participante",SaasActions.AnswerSurveys,true)] [InlineData("convidado_externo",SaasActions.ManageUsers,false)] public void PermissionService_Covers_Legacy_Roles(string role,string action,bool allowed){var svc=new PermissionService();var user=new CurrentUser(Guid.NewGuid(),Guid.NewGuid(),role,"u@example.com");Assert.Equal(allowed,svc.Can(user,action,user.OrganizationId).Allowed);} 
 [Fact] public void Sql_Has_Saas_Tables_Indexes_And_Seeds(){var sql=Read("database/postgresql/scriptbd_completo.sql");foreach(var t in new[]{"plans","plan_limits","plan_capabilities","modules","organization_modules","subscriptions","usage_monthly"})Assert.Contains($"valorapesquisa.{t}",sql);foreach(var i in new[]{"ix_plans_code","ix_modules_code","ix_subscriptions_status","ix_usage_monthly_organization_month"})Assert.Contains(i,sql);foreach(var p in new[]{"'free'","'essential'","'growth'","'enterprise'"})Assert.Contains(p,sql);}
 [Fact] public void Saas_Controllers_Expose_Required_Endpoints(){var c=Read("src/ValoraPesquisa.Api/Controllers/SaasControllers.cs");foreach(var e in new[]{"Route(\"plans\")","Route(\"modules\")","subscription","usage","entitlements","dashboard","me/menu"})Assert.Contains(e,c);} 
 [Fact] public void Existing_Endpoints_Have_Commercial_Blocks_And_Audit(){foreach(var f in new[]{"FormsController.cs","SurveysController.cs","PublicSurveysController.cs","UsersController.cs"}){var text=Read("src/ValoraPesquisa.Api/Controllers/"+f);Assert.Contains("entitlements",text);Assert.Contains("commercial_",text);} }
 [Fact] public void Dashboard_And_Menu_Dtos_Avoid_Sensitive_Fields(){var dto=Read("src/ValoraPesquisa.Application/DTOs/SaasDtos.cs");Assert.DoesNotContain("PasswordHash",dto);Assert.DoesNotContain("TokenHash",dto);Assert.Contains("DashboardGlobalDto",dto);Assert.Contains("MenuItemDto",dto);} 
 static string Root{get{var d=new DirectoryInfo(AppContext.BaseDirectory);while(d!=null&&!File.Exists(Path.Combine(d.FullName,"ValoraPesquisa.sln")))d=d.Parent;if(d==null)throw new DirectoryNotFoundException("backend-v2 não encontrado.");return d.FullName;}} static string Read(string r)=>File.ReadAllText(Path.Combine(Root,r));
}
