namespace ValoraPesquisa.Tests;
public class V11PostPilotTests{
 [Fact] public void V11_Migration_Exists_And_Uses_Integrarp_Schema(){var sql=Read("database/migrations/0013_v11_form_builder_automations_reports.sql").ToLowerInvariant();Assert.Contains("create schema if not exists integrarp",sql);foreach(var t in new[]{"formulario_definicao","formulario_versao","formulario_secao","formulario_campo","automacao_regra","automacao_execucao","anexo_arquivo","notificacao","relatorio_definicao","relatorio_exportacao"})Assert.Contains($"integrarp.{t}",sql);Assert.Contains("create table if not exists",sql);Assert.Contains("create index if not exists",sql);Assert.Contains("create or replace view",sql);Assert.Contains("drop trigger if exists",sql);Assert.DoesNotContain("create table public.",sql);Assert.DoesNotContain("create table integra.",sql);}
 [Fact] public void Domain_V11_Does_Not_Reference_Infrastructure_Api_Web_Or_Dapper(){var text=ReadAll("src/ValoraPesquisa.Domain");foreach(var forbidden in new[]{"ValoraPesquisa.Infrastructure","ValoraPesquisa.Api","ValoraPesquisa.Web","Dapper","Npgsql","Microsoft.AspNetCore"})Assert.DoesNotContain(forbidden,text);}
 [Fact] public void Controllers_V11_Do_Not_Contain_Inline_Sql_Or_Dapper(){var text=ReadAll("src/ValoraPesquisa.Api/Controllers/V11");Assert.DoesNotContain("Dapper",text);Assert.DoesNotContain("select ",text.ToLowerInvariant());Assert.DoesNotContain("insert ",text.ToLowerInvariant());Assert.DoesNotContain("update ",text.ToLowerInvariant());Assert.Contains("Authorize",text);Assert.Contains("CancellationToken",text);}
 [Fact] public void V11_Web_Assets_And_Docs_Exist(){foreach(var f in new[]{"forms-builder.js","forms-preview.js","automation-rules.js","automation-executions.js","attachments.js","notifications.js","reports.js"})Assert.True(File.Exists(Path.Combine(Root,"src/ValoraPesquisa.Web/wwwroot/js",f)),f);foreach(var f in new[]{"forms-builder.css","automation.css","attachments.css","notifications.css","reports.css"})Assert.True(File.Exists(Path.Combine(Root,"src/ValoraPesquisa.Web/wwwroot/css",f)),f);foreach(var f in new[]{"v1.1-post-pilot-plan.md","form-builder-advanced.md","automation-rules.md","advanced-attachments.md","notifications.md","exportable-reports.md","v1.1-demo-script.md","release-notes-v1.1.md"})Assert.True(File.Exists(Path.Combine(Root,"docs",f)),f);}
 static string Root{get{var d=new DirectoryInfo(AppContext.BaseDirectory); while(d!=null&&!File.Exists(Path.Combine(d.FullName,"ValoraPesquisa.sln"))) d=d.Parent; if(d==null) throw new DirectoryNotFoundException("backend-v2 não encontrado."); return d.FullName;}}
 static string Read(string relative)=>File.ReadAllText(Path.Combine(Root,relative));
 static string ReadAll(string relativeDir)=>string.Join("\n",Directory.GetFiles(Path.Combine(Root,relativeDir),"*.cs",SearchOption.AllDirectories).Select(File.ReadAllText));
}
