using Dapper;
using Valora.Application.Contracts;
using Valora.Application.Processes;

namespace Valora.Infrastructure.Processes;

public sealed class ProcessRepository(IDbConnectionFactory connections, IDbTransactionFactory transactions) :
    IProcessDefinitionRepository,IProcessStepRepository,IProcessInstanceRepository,IProcessApprovalRepository,
    IProcessSlaRepository,IProcessAutomationRepository,IProcessInsightRepository,IProcessTemplateRepository
{
    private const string DefinitionSelect="""SELECT d.id,d.name,d.description,d.category,d.owner_user_id OwnerUserId,d.status,d.version_number VersionNumber,count(s.id)::int StepCount,d.created_at CreatedAt,d.updated_at UpdatedAt FROM valorapesquisa.process_definitions d LEFT JOIN valorapesquisa.process_steps s ON s.process_definition_id=d.id AND s.deleted_at IS NULL""";
    public async Task<IReadOnlyList<ProcessDefinitionDto>> List(Guid o,CancellationToken ct){using var c=connections.Create();return (await c.QueryAsync<ProcessDefinitionDto>(new CommandDefinition(DefinitionSelect+" WHERE d.organization_id=@o AND d.deleted_at IS NULL GROUP BY d.id ORDER BY d.updated_at DESC",new{o},cancellationToken:ct))).ToList();}
    public async Task<ProcessDefinitionDto?> Get(Guid o,Guid id,CancellationToken ct){using var c=connections.Create();return await c.QuerySingleOrDefaultAsync<ProcessDefinitionDto>(new CommandDefinition(DefinitionSelect+" WHERE d.organization_id=@o AND d.id=@id AND d.deleted_at IS NULL GROUP BY d.id",new{o,id},cancellationToken:ct));}
    public async Task<Guid> Create(Guid o,Guid userId,CreateProcessRequest r,CancellationToken ct){var id=Guid.NewGuid();using var c=connections.Create();await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.process_definitions(id,organization_id,name,description,category,owner_user_id,status,version_number,created_by_user_id) VALUES(@id,@o,@Name,@Description,@Category,@OwnerUserId,'draft',1,@userId)",new{id,o,userId,r.Name,r.Description,r.Category,r.OwnerUserId},cancellationToken:ct));return id;}
    public async Task Publish(Guid o,Guid id,Guid userId,CancellationToken ct){await using var u=await transactions.BeginAsync(ct);var changed=await u.Connection.ExecuteAsync(new CommandDefinition("UPDATE valorapesquisa.process_definitions SET status='published',published_at=now(),updated_at=now() WHERE id=@id AND organization_id=@o AND status='draft' AND deleted_at IS NULL",new{o,id},u.Transaction,cancellationToken:ct));if(changed==0)throw new InvalidOperationException("O processo não está disponível para publicação.");await Audit(u.Connection,u.Transaction,o,id,userId,"process.published",ct);await u.CommitAsync();}
    public async Task<Guid> NewVersion(Guid o,Guid id,Guid userId,CancellationToken ct){var newId=Guid.NewGuid();await using var u=await transactions.BeginAsync(ct);var changed=await u.Connection.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.process_definitions(id,organization_id,name,description,category,owner_user_id,status,version_number,parent_definition_id,metadata_json,created_by_user_id) SELECT @newId,organization_id,name,description,category,owner_user_id,'draft',version_number+1,id,metadata_json,@userId FROM valorapesquisa.process_definitions WHERE id=@id AND organization_id=@o AND status='published' AND deleted_at IS NULL",new{o,id,newId,userId},u.Transaction,cancellationToken:ct));if(changed==0)throw new InvalidOperationException("Somente processos publicados podem originar uma nova versão.");await u.Connection.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.process_steps(id,organization_id,process_definition_id,name,description,step_type,order_index,responsible_role_id,sla_hours,requires_approval,evidence_required,metadata_json) SELECT gen_random_uuid(),organization_id,@newId,name,description,step_type,order_index,responsible_role_id,sla_hours,requires_approval,evidence_required,metadata_json FROM valorapesquisa.process_steps WHERE process_definition_id=@id AND deleted_at IS NULL",new{id,newId},u.Transaction,cancellationToken:ct));await Audit(u.Connection,u.Transaction,o,newId,userId,"process.version.created",ct);await u.CommitAsync();return newId;}
    public async Task<IReadOnlyList<ProcessStepDto>> List(Guid o,Guid processId,CancellationToken ct){const string sql="SELECT id,process_definition_id ProcessDefinitionId,name,description,step_type StepType,order_index OrderIndex,responsible_role_id ResponsibleRoleId,sla_hours SlaHours,requires_approval RequiresApproval,evidence_required EvidenceRequired FROM valorapesquisa.process_steps WHERE organization_id=@o AND process_definition_id=@processId AND deleted_at IS NULL ORDER BY order_index";using var c=connections.Create();return(await c.QueryAsync<ProcessStepDto>(new CommandDefinition(sql,new{o,processId},cancellationToken:ct))).ToList();}
    public async Task<Guid> Create(Guid o,Guid processId,CreateProcessStepRequest r,CancellationToken ct){var id=Guid.NewGuid();using var c=connections.Create();await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.process_steps(id,organization_id,process_definition_id,name,description,step_type,order_index,responsible_role_id,sla_hours,requires_approval,evidence_required) VALUES(@id,@o,@processId,@Name,@Description,@StepType,@OrderIndex,@ResponsibleRoleId,@SlaHours,@RequiresApproval,@EvidenceRequired)",new{id,o,processId,r.Name,r.Description,r.StepType,r.OrderIndex,r.ResponsibleRoleId,r.SlaHours,r.RequiresApproval,r.EvidenceRequired},cancellationToken:ct));return id;}
    private const string InstanceSelect="""SELECT i.id,i.process_definition_id ProcessDefinitionId,d.name ProcessName,i.title,i.status,i.priority,i.current_step_id CurrentStepId,s.name CurrentStepName,i.responsible_user_id ResponsibleUserId,i.source_type SourceType,i.started_at StartedAt,i.due_at DueAt FROM valorapesquisa.process_instances i JOIN valorapesquisa.process_definitions d ON d.id=i.process_definition_id LEFT JOIN valorapesquisa.process_steps s ON s.id=i.current_step_id""";
    public async Task<IReadOnlyList<ProcessInstanceDto>> List(Guid o,CancellationToken ct){using var c=connections.Create();return(await c.QueryAsync<ProcessInstanceDto>(new CommandDefinition(InstanceSelect+" WHERE i.organization_id=@o AND i.deleted_at IS NULL ORDER BY i.updated_at DESC",new{o},cancellationToken:ct))).ToList();}
    public async Task<ProcessInstanceDto?> Get(Guid o,Guid id,CancellationToken ct){using var c=connections.Create();return await c.QuerySingleOrDefaultAsync<ProcessInstanceDto>(new CommandDefinition(InstanceSelect+" WHERE i.organization_id=@o AND i.id=@id AND i.deleted_at IS NULL",new{o,id},cancellationToken:ct));}
    public async Task<Guid> Create(Guid o,Guid userId,CreateProcessInstanceRequest r,CancellationToken ct){var id=Guid.NewGuid();await using var u=await transactions.BeginAsync(ct);var changed=await u.Connection.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.process_instances(id,organization_id,process_definition_id,source_type,source_id,title,status,priority,current_step_id,started_at,due_at,created_by_user_id,responsible_user_id) SELECT @id,@o,d.id,@SourceType,@SourceId,@Title,'running',@Priority,s.id,now(),CASE WHEN s.sla_hours IS NULL THEN NULL ELSE now()+make_interval(hours=>s.sla_hours) END,@userId,@ResponsibleUserId FROM valorapesquisa.process_definitions d JOIN LATERAL (SELECT id,sla_hours FROM valorapesquisa.process_steps WHERE process_definition_id=d.id AND step_type='initial' AND deleted_at IS NULL ORDER BY order_index LIMIT 1) s ON true WHERE d.id=@ProcessDefinitionId AND d.organization_id=@o AND d.status='published' AND d.deleted_at IS NULL",new{id,o,userId,r.ProcessDefinitionId,r.SourceType,r.SourceId,r.Title,r.Priority,r.ResponsibleUserId},u.Transaction,cancellationToken:ct));if(changed==0)throw new InvalidOperationException("Este processo não está publicado ou não possui etapa inicial.");await Audit(u.Connection,u.Transaction,o,id,userId,"process.instance.started",ct);await u.CommitAsync();return id;}
    public async Task ChangeState(Guid o,Guid id,Guid userId,string operation,bool evidenceProvided,CancellationToken ct){if(operation is not("advance" or "pause" or "complete" or "cancel"))throw new ArgumentException("Operação de processo inválida.");await using var u=await transactions.BeginAsync(ct);if(operation=="advance"){var current=await u.Connection.QuerySingleOrDefaultAsync<(bool EvidenceRequired,bool RequiresApproval)>(new CommandDefinition("SELECT s.evidence_required EvidenceRequired,s.requires_approval RequiresApproval FROM valorapesquisa.process_instances i JOIN valorapesquisa.process_steps s ON s.id=i.current_step_id WHERE i.id=@id AND i.organization_id=@o AND i.status='running'",new{o,id},u.Transaction,cancellationToken:ct));if(current.EvidenceRequired&&!evidenceProvided)throw new InvalidOperationException("Esta etapa exige evidência antes do avanço.");if(current.RequiresApproval&&await u.Connection.ExecuteScalarAsync<int>(new CommandDefinition("SELECT count(*)::int FROM valorapesquisa.process_approvals WHERE process_instance_id=@id AND step_id=(SELECT current_step_id FROM valorapesquisa.process_instances WHERE id=@id) AND status<>'approved'",new{id},u.Transaction,cancellationToken:ct))>0)throw new InvalidOperationException("A aprovação desta etapa ainda está pendente.");var changed=await u.Connection.ExecuteAsync(new CommandDefinition("UPDATE valorapesquisa.process_instances i SET current_step_id=n.id,due_at=CASE WHEN n.sla_hours IS NULL THEN NULL ELSE now()+make_interval(hours=>n.sla_hours) END,updated_at=now() FROM LATERAL (SELECT s.id,s.sla_hours FROM valorapesquisa.process_steps s JOIN valorapesquisa.process_steps current ON current.id=i.current_step_id WHERE s.process_definition_id=i.process_definition_id AND s.order_index>current.order_index AND s.deleted_at IS NULL ORDER BY s.order_index LIMIT 1)n WHERE i.id=@id AND i.organization_id=@o AND i.status='running'",new{o,id},u.Transaction,cancellationToken:ct));if(changed==0)throw new InvalidOperationException("Não há uma próxima etapa disponível.");}else{var state=operation switch{"pause"=>"paused","complete"=>"completed",_=>"cancelled"};await u.Connection.ExecuteAsync(new CommandDefinition("UPDATE valorapesquisa.process_instances SET status=@state,completed_at=CASE WHEN @state='completed' THEN now() ELSE completed_at END,updated_at=now() WHERE id=@id AND organization_id=@o AND deleted_at IS NULL",new{o,id,state},u.Transaction,cancellationToken:ct));}await Audit(u.Connection,u.Transaction,o,id,userId,operation=="advance"?"process.step.advanced":$"process.instance.{operation}d",ct);await u.CommitAsync();}
    public async Task<ProcessDashboardDto> Dashboard(Guid o,CancellationToken ct){using var c=connections.Create();const string sql="SELECT count(*) FILTER(WHERE status='published')::int ActiveProcesses,(SELECT count(*)::int FROM valorapesquisa.process_instances WHERE organization_id=@o AND status IN('running','paused') AND deleted_at IS NULL) RunningInstances,(SELECT count(*)::int FROM valorapesquisa.process_instances WHERE organization_id=@o AND status='running' AND due_at BETWEEN now() AND now()+interval '8 hours' AND deleted_at IS NULL) SlaAtRisk,(SELECT count(*)::int FROM valorapesquisa.process_instances WHERE organization_id=@o AND status='running' AND due_at<now() AND deleted_at IS NULL) SlaOverdue,(SELECT count(*)::int FROM valorapesquisa.process_approvals WHERE organization_id=@o AND status='pending' AND deleted_at IS NULL) PendingApprovals,(SELECT count(*)::int FROM valorapesquisa.process_bottleneck_insights WHERE organization_id=@o AND status='open' AND deleted_at IS NULL) Bottlenecks FROM valorapesquisa.process_definitions WHERE organization_id=@o AND deleted_at IS NULL";var m=await c.QuerySingleAsync<DashboardMetrics>(new CommandDefinition(sql,new{o},cancellationToken:ct));return new(m.ActiveProcesses,m.RunningInstances,m.SlaAtRisk,m.SlaOverdue,m.PendingApprovals,m.Bottlenecks,(await List(o,ct)).Take(6).ToList());}
    public async Task Decide(Guid o,Guid approvalId,Guid userId,string decision,ApprovalDecisionRequest r,CancellationToken ct){using var c=connections.Create();var changed=await c.ExecuteAsync(new CommandDefinition("UPDATE valorapesquisa.process_approvals SET status=@decision,decision_reason=@Justification,return_step_id=@ReturnStepId,decided_at=now(),decided_by_user_id=@userId,updated_at=now() WHERE id=@approvalId AND organization_id=@o AND approver_user_id=@userId AND status='pending' AND deleted_at IS NULL",new{o,approvalId,userId,decision,r.Justification,r.ReturnStepId},cancellationToken:ct));if(changed==0)throw new InvalidOperationException("Esta aprovação não está disponível para sua decisão.");}
    public async Task<IReadOnlyList<ProcessSlaDto>> List(Guid o,CancellationToken ct){const string sql="SELECT i.id InstanceId,d.name ProcessName,i.title InstanceTitle,s.name StepName,coalesce(u.name,'Responsável não identificado') ResponsibleName,i.due_at DueAt,CASE WHEN i.due_at<now() THEN 'overdue' WHEN i.due_at<now()+interval '8 hours' THEN 'at_risk' ELSE 'on_track' END Risk FROM valorapesquisa.process_instances i JOIN valorapesquisa.process_definitions d ON d.id=i.process_definition_id JOIN valorapesquisa.process_steps s ON s.id=i.current_step_id LEFT JOIN valorapesquisa.users u ON u.id=i.responsible_user_id WHERE i.organization_id=@o AND i.status='running' AND i.due_at IS NOT NULL AND i.deleted_at IS NULL ORDER BY i.due_at";using var c=connections.Create();return(await c.QueryAsync<ProcessSlaDto>(new CommandDefinition(sql,new{o},cancellationToken:ct))).ToList();}
    public async Task RecordExecution(Guid o,Guid ruleId,string status,string? technicalMessage,CancellationToken ct){using var c=connections.Create();await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.process_automation_executions(organization_id,automation_rule_id,status,technical_message,started_at,completed_at) VALUES(@o,@ruleId,@status,@technicalMessage,now(),now())",new{o,ruleId,status,technicalMessage},cancellationToken:ct));}
    public async Task<IReadOnlyList<ProcessInsightDto>> List(Guid o,CancellationToken ct){const string sql="SELECT i.id,i.process_definition_id ProcessDefinitionId,d.name ProcessName,i.step_id StepId,s.name StepName,i.insight_type InsightType,i.evidence_summary EvidenceSummary,i.average_duration_hours AverageDurationHours,i.occurrence_count OccurrenceCount FROM valorapesquisa.process_bottleneck_insights i JOIN valorapesquisa.process_definitions d ON d.id=i.process_definition_id LEFT JOIN valorapesquisa.process_steps s ON s.id=i.step_id WHERE i.organization_id=@o AND i.deleted_at IS NULL ORDER BY i.detected_at DESC";using var c=connections.Create();return(await c.QueryAsync<ProcessInsightDto>(new CommandDefinition(sql,new{o},cancellationToken:ct))).ToList();}
    public async Task<IReadOnlyList<ProcessTemplateDto>> ListTemplates(Guid o,CancellationToken ct)=>await ((IProcessTemplateRepository)this).List(o,ct);
    async Task<IReadOnlyList<ProcessTemplateDto>> IProcessTemplateRepository.List(Guid o,CancellationToken ct){const string sql="SELECT id,name,description,category,status FROM valorapesquisa.process_templates WHERE deleted_at IS NULL AND (organization_id IS NULL OR organization_id=@o) ORDER BY name";using var c=connections.Create();return(await c.QueryAsync<ProcessTemplateDto>(new CommandDefinition(sql,new{o},cancellationToken:ct))).ToList();}
    private sealed record DashboardMetrics(int ActiveProcesses,int RunningInstances,int SlaAtRisk,int SlaOverdue,int PendingApprovals,int Bottlenecks);
    private static Task Audit(System.Data.IDbConnection c,System.Data.IDbTransaction t,Guid o,Guid entityId,Guid userId,string eventType,CancellationToken ct)=>c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.process_audit_events(organization_id,entity_type,entity_id,event_type,performed_by_user_id,summary) VALUES(@o,'process',@entityId,@eventType,@userId,'Mudança registrada com decisão humana preservada.')",new{o,entityId,eventType,userId},t,cancellationToken:ct));
}
