\set ON_ERROR_STOP on
\i database/migrations/001_initial_schema.sql
\i database/migrations/002_users_clients.sql
\i database/migrations/003_habits.sql
\i database/migrations/004_reports.sql
\i database/migrations/005_notifications.sql
\i database/migrations/006_audit.sql
\i database/migrations/007_plans.sql
\i database/migrations/008_billing.sql
\i database/migrations/009_subscriptions.sql
\i database/migrations/010_entitlements.sql
\i database/migrations/011_superadmin.sql
\i database/migrations/012_support.sql
\i database/migrations/013_communications.sql
\i database/migrations/014_customer_success.sql
\i database/migrations/015_user_invites.sql
\i database/migrations/016_habit_library.sql
\i database/migrations/017_payment_transactions.sql
\i database/migrations/018_payment_webhooks.sql
\i database/migrations/019_billing_status_jobs.sql
\i database/migrations/020_billing_communication_jobs.sql
\i database/migrations/021_clients_management.sql
\i database/migrations/022_financial_dashboard.sql
\i database/migrations/023_admin_billing.sql
\i database/migrations/024_admin_support.sql
\i database/migrations/025_lgpd_audit.sql
\i database/migrations/026_operational_notifications.sql
\i database/migrations/027_customer_health.sql
\i database/migrations/028_client_onboarding.sql
\i database/migrations/029_operational_completeness_v61.sql
