using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Valora.Application.Access;
using Valora.Application.ActionCenter;
using Valora.Application.Common;
using Valora.Application.Exceptions;
using Valora.Application.Workspace;
namespace Valora.Web.Controllers;

[Authorize(Policy=ValoraPermissions.Action.Read), Route("ActionCenter")]
public sealed class ActionCenterController(ActionPlanService plans,ActionItemService items,ActionProgressService progress,ICurrentRequestContext requestContext) : Controller {
    private CurrentRequestContext Context=>requestContext.GetCurrent();
    private bool Wide=>Context.IsGlobalAdministrator||Context.Roles.Contains("admin_cliente",StringComparer.OrdinalIgnoreCase);
    private bool Manage=>Context.IsGlobalAdministrator||Context.Permissions.Contains(ValoraPermissions.Action.Manage,StringComparer.OrdinalIgnoreCase);
    private bool CompletePermission=>Context.IsGlobalAdministrator||Context.Permissions.Contains(ValoraPermissions.Action.Complete,StringComparer.OrdinalIgnoreCase);
    private bool TryScope(out Guid o,out Guid u){var x=Context;o=x.EffectiveOrganizationId??Guid.Empty;u=x.UserId??Guid.Empty;return o!=Guid.Empty&&u!=Guid.Empty;}
    [HttpGet("")] public async Task<IActionResult> Index(CancellationToken c){if(!TryScope(out var o,out var u))return View("MissingOrganization");return View(new ActionDashboardPageViewModel(await plans.Dashboard(o,u,Wide,c),Manage));}
    [HttpGet("Plans")] public async Task<IActionResult> Plans([FromQuery] ActionPlanListQuery query,CancellationToken c){if(!TryScope(out var o,out var u))return View("MissingOrganization");return View(new ActionPlanListViewModel(await plans.List(o,u,Wide,query,c),query,CurrentUrl(),Manage));}
    [HttpGet("Plans/Create"),Authorize(Policy=ValoraPermissions.Action.Manage)] public IActionResult CreatePlan(string? originType,Guid? originId)=>TryScope(out _,out _)?View(new CreateActionPlanRequest("","",originType=="ai_insight"?originType:"manual",originType=="ai_insight"?originId:null,null,null,null,"medium",null,null,null,"","",Guid.NewGuid().ToString("N"))):View("MissingOrganization");
    [ValidateAntiForgeryToken,HttpPost("Plans/Create"),Authorize(Policy=ValoraPermissions.Action.Manage)] public async Task<IActionResult> CreatePlan(CreateActionPlanRequest r,CancellationToken c){if(!TryScope(out var o,out var u))return Forbid();if(!ModelState.IsValid)return View(r);try{var id=await plans.Create(o,u,Context.IsGlobalAdministrator,r,c);TempData["ActionSuccess"]="Plano criado com sucesso.";return RedirectToAction(nameof(PlanDetails),new{id});}catch(Exception e)when(e is ArgumentException or ConflictAppException or ConcurrencyConflictException){ModelState.AddModelError("",e.Message);return View(r);}catch(UnauthorizedAccessException){return Forbid();}}
    [HttpGet("Plans/Details/{id:guid}")] public async Task<IActionResult> PlanDetails(Guid id,int itemPage=1,string? returnUrl=null,CancellationToken c=default){if(!TryScope(out var o,out var u))return Forbid();return await PlanPage(o,u,id,itemPage,null,null,SafeReturnUrl(returnUrl,"/ActionCenter/Plans","/ActionCenter","/ActionCenter/Plans"),c);}
    [ValidateAntiForgeryToken,HttpPost("Items/Create"),Authorize(Policy=ValoraPermissions.Action.Manage)] public async Task<IActionResult> CreateItem(CreateActionItemRequest r,int itemPage=1,string? returnUrl=null,CancellationToken c=default){if(!TryScope(out var o,out var u))return Forbid();var listReturn=SafeReturnUrl(returnUrl,"/ActionCenter/Plans","/ActionCenter","/ActionCenter/Plans");var planReturn=Url.Action(nameof(PlanDetails),new{id=r.ActionPlanId,itemPage=Math.Max(1,itemPage),returnUrl=listReturn})!;if(ModelState.IsValid)try{var id=await items.Create(o,u,r,c);return RedirectToAction(nameof(ItemDetails),new{id,returnUrl=planReturn});}catch(ConcurrencyConflictException e){ModelState.AddModelError("",e.Message);}catch(Exception e)when(e is ArgumentException or ConflictAppException){ModelState.AddModelError("",e.Message);}catch(UnauthorizedAccessException){return Forbid();}return await PlanPage(o,u,r.ActionPlanId,itemPage,r,"create-item-dialog",listReturn,c);}
    [HttpGet("Items")] public async Task<IActionResult> Items([FromQuery] ActionItemListQuery query,CancellationToken c=default){if(!TryScope(out var o,out var u))return View("MissingOrganization");return View(new ActionItemListViewModel(await items.List(o,u,null,Wide,query,c),query,CurrentUrl()));}
    [HttpGet("Items/Details/{id:guid}")] public async Task<IActionResult> ItemDetails(Guid id,int historyPage=1,string? returnUrl=null,CancellationToken c=default){if(!TryScope(out var o,out var u))return Forbid();return await ItemPage(o,u,id,historyPage,null,null,SafeReturnUrl(returnUrl,"/ActionCenter/Items","/ActionCenter","/ActionCenter/Items","/ActionCenter/Plans/Details/"),c);}
    [HttpGet("ResponsibleOptions"),Authorize(Policy=ValoraPermissions.Action.Manage)] public async Task<IActionResult> ResponsibleOptions([FromQuery] OptionQuery query,CancellationToken c=default){if(!TryScope(out var o,out _))return Forbid();return Json(await items.ResponsibleOptions(o,query,c));}
    [HttpGet("VisibleResponsibleOptions")] public async Task<IActionResult> VisibleResponsibleOptions([FromQuery] OptionQuery query,CancellationToken c=default){if(!TryScope(out var o,out var u))return Forbid();return Json(await items.VisibleResponsibleOptions(o,u,Wide,query,c));}
    [ValidateAntiForgeryToken,HttpPost("Items/{id:guid}/Progress"),Authorize(Policy=ValoraPermissions.Action.Manage)] public Task<IActionResult> Update(Guid id,ProgressActionRequest request,ActionNavigationContext navigation,CancellationToken c)=>ExecuteCommand(id,"progress-dialog",request,navigation,()=>progress.Update(Context.RequireOrganizationId(),Context.RequireUserId(),id,Wide,request,c),c);
    [ValidateAntiForgeryToken,HttpPost("Items/{id:guid}/Block"),Authorize(Policy=ValoraPermissions.Action.Manage)] public Task<IActionResult> Block(Guid id,TransitionActionRequest request,ActionNavigationContext navigation,CancellationToken c)=>ExecuteCommand(id,"block-dialog",request,navigation,()=>progress.Block(Context.RequireOrganizationId(),Context.RequireUserId(),id,Wide,request,c),c);
    [ValidateAntiForgeryToken,HttpPost("Items/{id:guid}/Resume"),Authorize(Policy=ValoraPermissions.Action.Manage)] public Task<IActionResult> Resume(Guid id,TransitionActionRequest request,ActionNavigationContext navigation,CancellationToken c)=>ExecuteCommand(id,"resume-dialog",request,navigation,()=>progress.Resume(Context.RequireOrganizationId(),Context.RequireUserId(),id,Wide,request,c),c);
    [ValidateAntiForgeryToken,HttpPost("Items/{id:guid}/Complete"),Authorize(Policy=ValoraPermissions.Action.Complete)] public Task<IActionResult> Complete(Guid id,CompleteActionRequest request,ActionNavigationContext navigation,CancellationToken c)=>ExecuteCommand(id,"complete-dialog",request,navigation,()=>progress.Complete(Context.RequireOrganizationId(),Context.RequireUserId(),id,Wide,request,c),c);
    [ValidateAntiForgeryToken,HttpPost("Items/{id:guid}/Edit"),Authorize(Policy=ValoraPermissions.Action.Manage)] public Task<IActionResult> EditItem(Guid id,EditActionItemRequest request,ActionNavigationContext navigation,CancellationToken c)=>ExecuteCommand(id,"edit-dialog",request,navigation,()=>items.Edit(Context.RequireOrganizationId(),Context.RequireUserId(),id,Wide,request,c),c,"Atividade editada com sucesso.");
    [ValidateAntiForgeryToken,HttpPost("Items/{id:guid}/Assign"),Authorize(Policy=ValoraPermissions.Action.Manage)] public Task<IActionResult> AssignItem(Guid id,AssignResponsibleRequest request,ActionNavigationContext navigation,CancellationToken c)=>ExecuteCommand(id,"assign-dialog",request,navigation,()=>items.Assign(Context.RequireOrganizationId(),Context.RequireUserId(),id,Wide,request,c),c,"Responsável da atividade alterado com sucesso.");
    [ValidateAntiForgeryToken,HttpPost("Items/{id:guid}/Reschedule"),Authorize(Policy=ValoraPermissions.Action.Manage)] public Task<IActionResult> RescheduleItem(Guid id,RescheduleActionRequest request,ActionNavigationContext navigation,CancellationToken c)=>ExecuteCommand(id,"reschedule-dialog",request,navigation,()=>items.Reschedule(Context.RequireOrganizationId(),Context.RequireUserId(),id,Wide,request,c),c,"Prazo da atividade reagendado com sucesso.");
    [HttpGet("Plans/{id:guid}/Edit"),Authorize(Policy=ValoraPermissions.Action.Manage)] public async Task<IActionResult> EditPlan(Guid id,string? returnUrl=null,CancellationToken c=default){if(!TryScope(out var o,out var u))return Forbid();var plan=await plans.Get(o,u,id,Wide,c);if(plan is null)return NotFound();return View(new ActionPlanEditPageViewModel(plan,new EditActionPlanRequest{Title=plan.Title,Summary=plan.Summary,Priority=plan.Priority,ExpectedOutcome=plan.ExpectedOutcome,Version=plan.Version,CommandId=Guid.NewGuid().ToString("N")},SafeReturnUrl(returnUrl,$"/ActionCenter/Plans/Details/{id}","/ActionCenter","/ActionCenter/Plans")));}
    [ValidateAntiForgeryToken,HttpPost("Plans/{id:guid}/Edit"),Authorize(Policy=ValoraPermissions.Action.Manage)] public async Task<IActionResult> EditPlan(Guid id,EditActionPlanRequest request,string? returnUrl,CancellationToken c){if(!TryScope(out var o,out var u))return Forbid();var back=SafeReturnUrl(returnUrl,$"/ActionCenter/Plans/Details/{id}","/ActionCenter","/ActionCenter/Plans");if(ModelState.IsValid)try{await plans.Edit(o,u,id,Wide,request,c);TempData["ActionSuccess"]="Plano editado com sucesso.";return LocalRedirect(back);}catch(ConcurrencyConflictException e){ModelState.AddModelError("",e.Message+" Consulte os dados atuais antes de reenviar.");}catch(Exception e)when(e is ConflictAppException or ArgumentException){ModelState.AddModelError("",e.Message);}var plan=await plans.Get(o,u,id,Wide,c);return plan is null?NotFound():View(new ActionPlanEditPageViewModel(plan,request,back));}
    [ValidateAntiForgeryToken,HttpPost("Plans/{id:guid}/Assign"),Authorize(Policy=ValoraPermissions.Action.Manage)] public Task<IActionResult> AssignPlan(Guid id,AssignResponsibleRequest request,ActionNavigationContext navigation,CancellationToken c)=>ExecutePlanCommand(id,"assign-plan-dialog",request,navigation,()=>plans.Assign(Context.RequireOrganizationId(),Context.RequireUserId(),id,Wide,request,c),c,"Responsável do plano alterado com sucesso.");
    [ValidateAntiForgeryToken,HttpPost("Plans/{id:guid}/Reschedule"),Authorize(Policy=ValoraPermissions.Action.Manage)] public Task<IActionResult> ReschedulePlan(Guid id,RescheduleActionRequest request,ActionNavigationContext navigation,CancellationToken c)=>ExecutePlanCommand(id,"reschedule-plan-dialog",request,navigation,()=>plans.Reschedule(Context.RequireOrganizationId(),Context.RequireUserId(),id,Wide,request,c),c,"Prazo do plano reagendado sem alterar os prazos das atividades.");
    private async Task<IActionResult> ExecutePlanCommand(Guid id,string dialog,object request,ActionNavigationContext navigation,Func<Task> command,CancellationToken c,string success){if(!TryScope(out var o,out var u))return Forbid();var returnUrl=SafeReturnUrl(navigation.ReturnUrl,"/ActionCenter/Plans","/ActionCenter","/ActionCenter/Plans");if(ModelState.IsValid)try{await command();TempData["ActionSuccess"]=success;return RedirectToAction(nameof(PlanDetails),new{id,returnUrl});}catch(ConcurrencyConflictException e){ModelState.AddModelError("",e.Message+" Consulte os dados atuais antes de reenviar.");}catch(Exception e)when(e is ConflictAppException or ArgumentException){ModelState.AddModelError("",e.Message);}catch(KeyNotFoundException){return NotFound();}return await PlanPage(o,u,id,1,null,dialog,returnUrl,c,request);}
    private async Task<IActionResult> ExecuteCommand(Guid id,string dialog,object request,ActionNavigationContext navigation,Func<Task> command,CancellationToken c,string success="Registro atualizado com sucesso."){if(!TryScope(out var o,out var u))return Forbid();var returnUrl=SafeReturnUrl(navigation.ReturnUrl,"/ActionCenter/Items","/ActionCenter","/ActionCenter/Items","/ActionCenter/Plans/Details/");var historyPage=Math.Max(1,navigation.HistoryPage);if(ModelState.IsValid)try{await command();TempData["ActionSuccess"]=success;return RedirectToAction(nameof(ItemDetails),new{id,historyPage,returnUrl});}catch(ConcurrencyConflictException e){ModelState.AddModelError("",e.Message+" Consulte os dados atuais antes de reenviar.");}catch(Exception e)when(e is ConflictAppException or ArgumentException){ModelState.AddModelError("",e.Message);}catch(KeyNotFoundException){return NotFound();}return await ItemPage(o,u,id,historyPage,request,dialog,returnUrl,c);}
    private async Task<IActionResult> ItemPage(Guid o,Guid u,Guid id,int page,object? command,string? dialog,string returnUrl,CancellationToken c){var detail=await items.Details(o,u,id,Wide,Manage,CompletePermission,page,c);return detail is null?NotFound():View("ItemDetails",new ActionItemPageViewModel(detail,command,dialog,returnUrl));}
    private async Task<IActionResult> PlanPage(Guid o,Guid u,Guid id,int page,CreateActionItemRequest? command,string? dialog,string returnUrl,CancellationToken c,object? operationCommand=null){var plan=await plans.Get(o,u,id,Wide,c);if(plan is null)return NotFound();var activities=await items.List(o,u,id,Wide,new ActionItemListQuery(Page:page,PageSize:10),c);return View("PlanDetails",new ActionPlanDetailsViewModel(plan,activities,await items.ResponsibleOptions(o,new OptionQuery(PageSize:20,IncludeId:command?.ResponsibleUserId),c),Manage,operationCommand??command,dialog,returnUrl));}
    private string CurrentUrl()=>Request.Path+Request.QueryString;
    private string SafeReturnUrl(string? value,string fallback,params string[] allowedPaths){if(string.IsNullOrWhiteSpace(value)||!Url.IsLocalUrl(value))return fallback;var path=value.Split('?',2)[0];return allowedPaths.Any(allowed=>allowed.EndsWith('/')?path.StartsWith(allowed,StringComparison.OrdinalIgnoreCase):path.Equals(allowed,StringComparison.OrdinalIgnoreCase))?value:fallback;}
}
[Authorize] public sealed class ActionPlansController:Controller{[HttpGet("ActionPlans")][HttpGet("ValoraAction")]public IActionResult Index()=>Redirect("/ActionCenter/Plans");}
public sealed record ActionPlanEditPageViewModel(ActionPlanDto Plan,EditActionPlanRequest Command,string ReturnUrl);
public sealed record ActionDashboardPageViewModel(ActionDashboardDto Dashboard,bool CanManage);
public sealed record ActionPlanDetailsViewModel(ActionPlanDto Plan,PageResult<ActionItemDto> Activities,PageResult<ActionOptionDto> ResponsibleOptions,bool CanCreate,object? Command,string? OpenDialog,string ReturnUrl);
public sealed record ActionItemPageViewModel(ActionItemDetailsDto Details,object? Command,string? OpenDialog,string ReturnUrl);
public sealed record ActionItemListViewModel(PageResult<ActionItemDto> Page,ActionItemListQuery Query,string CurrentUrl);
public sealed record ActionPlanListViewModel(PageResult<ActionPlanDto> Page,ActionPlanListQuery Query,string CurrentUrl,bool CanCreate);
public sealed record ActionNavigationContext(string? ReturnUrl=null,int HistoryPage=1);
