using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Valora.Application.Access;
using Valora.Application.ActionCenter;
using Valora.Application.Common;
using Valora.Application.Exceptions;
using Valora.Application.Workspace;
namespace Valora.Web.Controllers;

[Authorize(Policy=ValoraPermissions.Action.Read), Route("ActionCenter")]
public sealed class ActionCenterController(ActionPlanService plans,ActionItemService items,ActionProgressService progress,ICurrentRequestContext requestContext) : Controller {
    private CurrentRequestContext Context=>requestContext.GetCurrent();
    private bool Wide=>Context.IsGlobalAdministrator||Context.Roles.Contains("admin_cliente",StringComparer.OrdinalIgnoreCase);
    private bool Manage=>Context.IsGlobalAdministrator||Context.Permissions.Contains(ValoraPermissions.Action.Manage,StringComparer.OrdinalIgnoreCase);
    private bool Approve=>Context.IsGlobalAdministrator||Context.Permissions.Contains(ValoraPermissions.Action.Approve,StringComparer.OrdinalIgnoreCase);
    private bool CompletePermission=>Context.IsGlobalAdministrator||Context.Permissions.Contains(ValoraPermissions.Action.Complete,StringComparer.OrdinalIgnoreCase);
    private bool TryScope(out Guid o,out Guid u){var x=Context;o=x.EffectiveOrganizationId??Guid.Empty;u=x.UserId??Guid.Empty;return o!=Guid.Empty&&u!=Guid.Empty;}
    [HttpGet("")] public async Task<IActionResult> Index(CancellationToken c){if(!TryScope(out var o,out var u))return View("MissingOrganization");return View(new ActionDashboardPageViewModel(await plans.Dashboard(o,u,Wide,c),Manage));}
    [HttpGet("Plans")] public async Task<IActionResult> Plans([FromQuery] ActionPlanListQuery query,CancellationToken c){if(!TryScope(out var o,out var u))return View("MissingOrganization");return View(new ActionPlanListViewModel(await plans.List(o,u,Wide,query,c),query,CurrentUrl(),Manage,Approve));}
    [HttpGet("Plans/Create"),Authorize(Policy=ValoraPermissions.Action.Manage)] public IActionResult CreatePlan(string? originType,Guid? originId)=>TryScope(out _,out _)?View(new CreateActionPlanRequest("","",originType=="ai_insight"?originType:"manual",originType=="ai_insight"?originId:null,null,null,null,"medium",null,null,null,"","",Guid.NewGuid().ToString("N"))):View("MissingOrganization");
    [ValidateAntiForgeryToken,HttpPost("Plans/Create"),Authorize(Policy=ValoraPermissions.Action.Manage)] public async Task<IActionResult> CreatePlan(CreateActionPlanRequest r,CancellationToken c){if(!TryScope(out var o,out var u))return Forbid();if(!ModelState.IsValid)return View(r);try{var id=await plans.Create(o,u,Context.IsGlobalAdministrator,r,c);TempData["ActionSuccess"]="Plano criado com sucesso.";return RedirectToAction(nameof(PlanDetails),new{id});}catch(Exception e)when(e is ArgumentException or ConflictAppException or ConcurrencyConflictException){ModelState.AddModelError("",e.Message);return View(r);}catch(UnauthorizedAccessException){return Forbid();}}
    [HttpGet("Plans/Details/{id:guid}")] public async Task<IActionResult> PlanDetails(Guid id,int itemPage=1,int historyPage=1,string? historyType=null,string? returnUrl=null,CancellationToken c=default){if(!TryScope(out var o,out var u))return Forbid();return await PlanPage(o,u,id,itemPage,null,null,SafeReturnUrl(returnUrl,"/ActionCenter/Plans","/ActionCenter","/ActionCenter/Plans"),c,historyPage,historyType);}
    [HttpGet("Plans/{id:guid}/Closure"),Authorize(Policy=ValoraPermissions.Action.Complete)] public async Task<IActionResult> ReviewClosure(Guid id,int activityPage=1,string? activityStatus=null,string? returnUrl=null,CancellationToken c=default){if(!TryScope(out var o,out var u))return Forbid();var plan=await plans.Get(o,u,id,Wide,c);if(plan is null)return NotFound();if(plan.Status!="in_execution")return RedirectToAction(nameof(PlanDetails),new{id,returnUrl});var back=SafeReturnUrl(returnUrl,$"/ActionCenter/Plans/Details/{id}","/ActionCenter","/ActionCenter/Plans/Details/");return View(await ClosurePage(o,u,plan,new CompleteActionPlanRequest{Version=plan.Version,CommandId=Guid.NewGuid().ToString("N")},activityPage,activityStatus,back,c));}
    [ValidateAntiForgeryToken,HttpPost("Plans/{id:guid}/Closure"),Authorize(Policy=ValoraPermissions.Action.Complete)] public async Task<IActionResult> ReviewClosure(Guid id,[Bind(Prefix="Command")] CompleteActionPlanRequest request,int activityPage=1,string? activityStatus=null,string? returnUrl=null,CancellationToken c=default){if(!TryScope(out var o,out var u))return Forbid();var back=SafeReturnUrl(returnUrl,$"/ActionCenter/Plans/Details/{id}","/ActionCenter","/ActionCenter/Plans/Details/");var plan=await plans.Get(o,u,id,Wide,c);if(plan is null)return NotFound();var versionConflict=false;if(ModelState.IsValid)try{await plans.Complete(o,u,id,Wide,request,c);TempData["ActionSuccess"]="Plano concluído. O resultado e a evidência foram registrados.";TempData["ClosureDraftKey"]=ClosureDraftKey(o,u,id);return RedirectToAction(nameof(PlanDetails),new{id,returnUrl=back});}catch(ConcurrencyConflictException){versionConflict=true;ModelState.Remove("Command.Confirmed");request=new CompleteActionPlanRequest{Result=request.Result,Evidence=request.Evidence,Note=request.Note,Version=request.Version,CommandId=request.CommandId,Confirmed=false};ModelState.AddModelError("","O plano mudou desde o início desta revisão. Seus textos e a versão enviada foram mantidos. Consulte as alterações e revise a versão atual antes de criar uma nova intenção de conclusão.");}catch(Exception e)when(e is ConflictAppException or ArgumentException){ModelState.AddModelError("",e.Message);}catch(KeyNotFoundException){return NotFound();}return View(await ClosurePage(o,u,plan,request,activityPage,activityStatus,back,c,versionConflict));}
    [HttpGet("Plans/{id:guid}/Print")] public async Task<IActionResult> PrintPlan(Guid id,string scope="summary",CancellationToken c=default){if(!TryScope(out var o,out var u))return Forbid();var plan=await plans.Get(o,u,id,Wide,c);if(plan is null)return NotFound();if(plan.Status is not "completed" and not "canceled")return NotFound();var detailed=scope=="detail";const int activityLimit=200,historyLimit=250;var activities=detailed?await LoadActivities(o,u,id,activityLimit,c):await items.List(o,u,id,Wide,new ActionItemListQuery(PageSize:1),c);var history=detailed?await LoadHistory(o,u,id,historyLimit,c):await LoadRelevantHistory(o,u,id,c);return View(new ActionPlanPrintViewModel(plan,activities,history,DateTimeOffset.UtcNow,detailed,activityLimit,historyLimit));}
    [ValidateAntiForgeryToken,HttpPost("Items/Create"),Authorize(Policy=ValoraPermissions.Action.Manage)] public async Task<IActionResult> CreateItem(CreateActionItemRequest r,int itemPage=1,string? returnUrl=null,CancellationToken c=default){if(!TryScope(out var o,out var u))return Forbid();var listReturn=SafeReturnUrl(returnUrl,"/ActionCenter/Plans","/ActionCenter","/ActionCenter/Plans");var planReturn=Url.Action(nameof(PlanDetails),new{id=r.ActionPlanId,itemPage=Math.Max(1,itemPage),returnUrl=listReturn})!;if(ModelState.IsValid)try{var id=await items.Create(o,u,r,c);return RedirectToAction(nameof(ItemDetails),new{id,returnUrl=planReturn});}catch(ConcurrencyConflictException e){ModelState.AddModelError("",e.Message);}catch(Exception e)when(e is ArgumentException or ConflictAppException){ModelState.AddModelError("",e.Message);}catch(UnauthorizedAccessException){return Forbid();}return await PlanPage(o,u,r.ActionPlanId,itemPage,r,"create-item-dialog",listReturn,c);}
    [HttpGet("Items")] public async Task<IActionResult> Items([FromQuery] ActionItemListQuery query,CancellationToken c=default){if(!TryScope(out var o,out var u))return View("MissingOrganization");return View(new ActionItemListViewModel(await items.List(o,u,null,Wide,query,c),query,CurrentUrl()));}
    [HttpGet("Items/Details/{id:guid}")] public async Task<IActionResult> ItemDetails(Guid id,int historyPage=1,string? returnUrl=null,CancellationToken c=default){if(!TryScope(out var o,out var u))return Forbid();return await ItemPage(o,u,id,historyPage,null,null,SafeReturnUrl(returnUrl,"/ActionCenter/Items","/ActionCenter","/ActionCenter/Items","/ActionCenter/Plans/Details/"),c);}
    [HttpGet("ResponsibleOptions"),Authorize(Policy=ValoraPermissions.Action.Manage)] public async Task<IActionResult> ResponsibleOptions([FromQuery] OptionQuery query,CancellationToken c=default){if(!TryScope(out var o,out _))return Forbid();return Json(await items.ResponsibleOptions(o,query,c));}
    [HttpGet("VisibleResponsibleOptions")] public async Task<IActionResult> VisibleResponsibleOptions([FromQuery] OptionQuery query,CancellationToken c=default){if(!TryScope(out var o,out var u))return Forbid();return Json(await items.VisibleResponsibleOptions(o,u,Wide,query,c));}
    [ValidateAntiForgeryToken,HttpPost("Items/{id:guid}/Progress"),Authorize(Policy=ValoraPermissions.Action.Manage)] public Task<IActionResult> Update(Guid id,ProgressActionRequest request,ActionNavigationContext navigation,CancellationToken c)=>ExecuteCommand(id,"progress-dialog",request,navigation,()=>progress.Update(Context.RequireOrganizationId(),Context.RequireUserId(),id,Wide,request,c),c);
    [ValidateAntiForgeryToken,HttpPost("Items/{id:guid}/Block"),Authorize(Policy=ValoraPermissions.Action.Manage)] public Task<IActionResult> Block(Guid id,TransitionActionRequest request,ActionNavigationContext navigation,CancellationToken c)=>ExecuteCommand(id,"block-dialog",request,navigation,()=>progress.Block(Context.RequireOrganizationId(),Context.RequireUserId(),id,Wide,request,c),c);
    [ValidateAntiForgeryToken,HttpPost("Items/{id:guid}/Resume"),Authorize(Policy=ValoraPermissions.Action.Manage)] public Task<IActionResult> Resume(Guid id,TransitionActionRequest request,ActionNavigationContext navigation,CancellationToken c)=>ExecuteCommand(id,"resume-dialog",request,navigation,()=>progress.Resume(Context.RequireOrganizationId(),Context.RequireUserId(),id,Wide,request,c),c);
    [ValidateAntiForgeryToken,HttpPost("Items/{id:guid}/Cancel"),Authorize(Policy=ValoraPermissions.Action.Manage)] public Task<IActionResult> CancelItem(Guid id,TransitionActionRequest request,ActionNavigationContext navigation,CancellationToken c)=>ExecuteCommand(id,"cancel-dialog",request,navigation,()=>progress.Cancel(Context.RequireOrganizationId(),Context.RequireUserId(),id,Wide,request,c),c,"Atividade cancelada com justificativa.");
    [ValidateAntiForgeryToken,HttpPost("Items/{id:guid}/Complete"),Authorize(Policy=ValoraPermissions.Action.Complete)] public Task<IActionResult> Complete(Guid id,CompleteActionRequest request,ActionNavigationContext navigation,CancellationToken c)=>ExecuteCommand(id,"complete-dialog",request,navigation,()=>progress.Complete(Context.RequireOrganizationId(),Context.RequireUserId(),id,Wide,request,c),c);
    [ValidateAntiForgeryToken,HttpPost("Items/{id:guid}/Edit"),Authorize(Policy=ValoraPermissions.Action.Manage)] public Task<IActionResult> EditItem(Guid id,EditActionItemRequest request,ActionNavigationContext navigation,CancellationToken c)=>ExecuteCommand(id,"edit-dialog",request,navigation,()=>items.Edit(Context.RequireOrganizationId(),Context.RequireUserId(),id,Wide,request,c),c,"Atividade editada com sucesso.");
    [ValidateAntiForgeryToken,HttpPost("Items/{id:guid}/Assign"),Authorize(Policy=ValoraPermissions.Action.Manage)] public Task<IActionResult> AssignItem(Guid id,AssignResponsibleRequest request,ActionNavigationContext navigation,CancellationToken c)=>ExecuteCommand(id,"assign-dialog",request,navigation,()=>items.Assign(Context.RequireOrganizationId(),Context.RequireUserId(),id,Wide,request,c),c,"Responsável da atividade alterado com sucesso.");
    [ValidateAntiForgeryToken,HttpPost("Items/{id:guid}/Reschedule"),Authorize(Policy=ValoraPermissions.Action.Manage)] public Task<IActionResult> RescheduleItem(Guid id,RescheduleActionRequest request,ActionNavigationContext navigation,CancellationToken c)=>ExecuteCommand(id,"reschedule-dialog",request,navigation,()=>items.Reschedule(Context.RequireOrganizationId(),Context.RequireUserId(),id,Wide,request,c),c,"Prazo da atividade reagendado com sucesso.");
    [HttpGet("Plans/{id:guid}/Edit"),Authorize(Policy=ValoraPermissions.Action.Manage)] public async Task<IActionResult> EditPlan(Guid id,string? returnUrl=null,CancellationToken c=default){if(!TryScope(out var o,out var u))return Forbid();var plan=await plans.Get(o,u,id,Wide,c);if(plan is null)return NotFound();return View(new ActionPlanEditPageViewModel(plan,new EditActionPlanRequest{Title=plan.Title,Summary=plan.Summary,Priority=plan.Priority,ExpectedOutcome=plan.ExpectedOutcome,Version=plan.Version,CommandId=Guid.NewGuid().ToString("N")},SafeReturnUrl(returnUrl,$"/ActionCenter/Plans/Details/{id}","/ActionCenter","/ActionCenter/Plans")));}
    [ValidateAntiForgeryToken,HttpPost("Plans/{id:guid}/Edit"),Authorize(Policy=ValoraPermissions.Action.Manage)] public async Task<IActionResult> EditPlan(Guid id,[Bind(Prefix="Command")] EditActionPlanRequest request,string? returnUrl,CancellationToken c){if(!TryScope(out var o,out var u))return Forbid();var back=SafeReturnUrl(returnUrl,$"/ActionCenter/Plans/Details/{id}","/ActionCenter","/ActionCenter/Plans");if(ModelState.IsValid)try{await plans.Edit(o,u,id,Wide,request,c);TempData["ActionSuccess"]="Plano editado com sucesso.";return LocalRedirect(back);}catch(ConcurrencyConflictException e){ModelState.AddModelError("",e.Message+" Consulte os dados atuais antes de reenviar.");}catch(Exception e)when(e is ConflictAppException or ArgumentException){ModelState.AddModelError("",e.Message);}var plan=await plans.Get(o,u,id,Wide,c);return plan is null?NotFound():View(new ActionPlanEditPageViewModel(plan,request,back));}
    [ValidateAntiForgeryToken,HttpPost("Plans/{id:guid}/Assign"),Authorize(Policy=ValoraPermissions.Action.Manage)] public Task<IActionResult> AssignPlan(Guid id,AssignResponsibleRequest request,ActionNavigationContext navigation,CancellationToken c)=>ExecutePlanCommand(id,"assign-plan-dialog",request,navigation,()=>plans.Assign(Context.RequireOrganizationId(),Context.RequireUserId(),id,Wide,request,c),c,"Responsável do plano alterado com sucesso.");
    [ValidateAntiForgeryToken,HttpPost("Plans/{id:guid}/Reschedule"),Authorize(Policy=ValoraPermissions.Action.Manage)] public Task<IActionResult> ReschedulePlan(Guid id,RescheduleActionRequest request,ActionNavigationContext navigation,CancellationToken c)=>ExecutePlanCommand(id,"reschedule-plan-dialog",request,navigation,()=>plans.Reschedule(Context.RequireOrganizationId(),Context.RequireUserId(),id,Wide,request,c),c,"Prazo do plano reagendado sem alterar os prazos das atividades.");
    [ValidateAntiForgeryToken,HttpPost("Plans/{id:guid}/Submit"),Authorize(Policy=ValoraPermissions.Action.Manage)] public Task<IActionResult> SubmitPlan(Guid id,PlanTransitionRequest request,ActionNavigationContext navigation,CancellationToken c)=>ExecutePlanCommand(id,"submit-plan-dialog",request,navigation,()=>plans.Submit(Context.RequireOrganizationId(),Context.RequireUserId(),id,Wide,request,c),c,"Plano submetido para avaliação.");
    [ValidateAntiForgeryToken,HttpPost("Plans/{id:guid}/Return"),Authorize(Policy=ValoraPermissions.Action.Approve)] public Task<IActionResult> ReturnPlan(Guid id,PlanTransitionRequest request,ActionNavigationContext navigation,CancellationToken c)=>ExecutePlanCommand(id,"return-plan-dialog",request,navigation,()=>plans.Return(Context.RequireOrganizationId(),Context.RequireUserId(),id,Wide,request,c),c,"Plano devolvido para ajustes.");
    [ValidateAntiForgeryToken,HttpPost("Plans/{id:guid}/Approve"),Authorize(Policy=ValoraPermissions.Action.Approve)] public Task<IActionResult> ApprovePlan(Guid id,PlanTransitionRequest request,ActionNavigationContext navigation,CancellationToken c)=>ExecutePlanCommand(id,"approve-plan-dialog",request,navigation,()=>plans.Approve(Context.RequireOrganizationId(),Context.RequireUserId(),id,Wide,request,c),c,"Plano aprovado.");
    [ValidateAntiForgeryToken,HttpPost("Plans/{id:guid}/Start"),Authorize(Policy=ValoraPermissions.Action.Manage)] public Task<IActionResult> StartPlan(Guid id,PlanTransitionRequest request,ActionNavigationContext navigation,CancellationToken c)=>ExecutePlanCommand(id,"start-plan-dialog",request,navigation,()=>plans.Start(Context.RequireOrganizationId(),Context.RequireUserId(),id,Wide,request,c),c,"Execução iniciada.");
    [ValidateAntiForgeryToken,HttpPost("Plans/{id:guid}/Complete"),Authorize(Policy=ValoraPermissions.Action.Complete)] public Task<IActionResult> CompletePlan(Guid id,CompleteActionPlanRequest request,ActionNavigationContext navigation,CancellationToken c)=>ExecutePlanCommand(id,"complete-plan-dialog",request,navigation,()=>plans.Complete(Context.RequireOrganizationId(),Context.RequireUserId(),id,Wide,request,c),c,"Plano concluído com evidências.");
    [ValidateAntiForgeryToken,HttpPost("Plans/{id:guid}/Cancel"),Authorize(Policy=ValoraPermissions.Action.Manage)] public Task<IActionResult> CancelPlan(Guid id,PlanTransitionRequest request,ActionNavigationContext navigation,CancellationToken c)=>ExecutePlanCommand(id,"cancel-plan-dialog",request,navigation,()=>plans.Cancel(Context.RequireOrganizationId(),Context.RequireUserId(),id,Wide,request,c),c,"Plano cancelado.");
    private async Task<ActionPlanClosurePageViewModel> ClosurePage(Guid o,Guid u,ActionPlanDto plan,CompleteActionPlanRequest command,int page,string? status,string returnUrl,CancellationToken c,bool versionConflict=false){status=status=="open"||ActionStatuses.Item.Contains(status??"")?status:null;var activities=await items.List(o,u,plan.Id,Wide,new ActionItemListQuery(Page:Math.Max(1,page),PageSize:20,Status:status=="open"?null:status,Scope:status=="open"?ActionItemScopeFilter.Open:null),c);var readiness=await plans.ClosureCheck(o,u,plan.Id,Wide,c)??throw new KeyNotFoundException();return new(plan,activities,readiness,command,returnUrl,status,ClosureDraftKey(o,u,plan.Id),versionConflict);}
    private static string ClosureDraftKey(Guid organizationId,Guid userId,Guid planId){var context=System.Text.Encoding.UTF8.GetBytes($"{organizationId:N}:{userId:N}");var scope=Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(context)).ToLowerInvariant()[..24];return $"valora:plan-closure:{scope}:{planId:N}";}
    private async Task<PageResult<ActionItemDto>> LoadActivities(Guid o,Guid u,Guid id,int limit,CancellationToken c){var rows=new List<ActionItemDto>();PageResult<ActionItemDto>? page=null;for(var number=1;rows.Count<limit;number++){page=await items.List(o,u,id,Wide,new ActionItemListQuery(Page:number,PageSize:50),c);rows.AddRange(page.Items.Take(limit-rows.Count));if(!page.HasNext)break;}return new(rows,1,limit,page?.Total??0);}
    private async Task<PageResult<ActionPlanHistoryDto>> LoadHistory(Guid o,Guid u,Guid id,int limit,CancellationToken c){var rows=new List<ActionPlanHistoryDto>();PageResult<ActionPlanHistoryDto>? page=null;for(var number=1;rows.Count<limit;number++){page=await plans.History(o,u,id,Wide,number,null,c);rows.AddRange(page.Items.Take(limit-rows.Count));if(!page.HasNext)break;}return new(rows,1,limit,page?.Total??0);}
    private async Task<PageResult<ActionPlanHistoryDto>> LoadRelevantHistory(Guid o,Guid u,Guid id,CancellationToken c){var rows=new List<ActionPlanHistoryDto>();foreach(var operation in new[]{"approve","start","complete","cancel"}){var page=await plans.History(o,u,id,Wide,1,operation,c);rows.AddRange(page.Items.Take(1));}rows=rows.OrderBy(x=>x.ChangedAt).ToList();return new(rows,1,rows.Count==0?1:rows.Count,rows.Count);}
    private async Task<IActionResult> ExecutePlanCommand(Guid id,string dialog,object request,ActionNavigationContext navigation,Func<Task> command,CancellationToken c,string success){if(!TryScope(out var o,out var u))return Forbid();var returnUrl=SafeReturnUrl(navigation.ReturnUrl,"/ActionCenter/Plans","/ActionCenter","/ActionCenter/Plans");if(ModelState.IsValid)try{await command();TempData["ActionSuccess"]=success;return RedirectToAction(nameof(PlanDetails),new{id,historyPage=navigation.HistoryPage,historyType=navigation.HistoryType,returnUrl});}catch(ConcurrencyConflictException e){ModelState.AddModelError("",e.Message+" Consulte os dados atuais antes de reenviar.");}catch(Exception e)when(e is ConflictAppException or ArgumentException){ModelState.AddModelError("",e.Message);}catch(KeyNotFoundException){return NotFound();}return await PlanPage(o,u,id,1,null,dialog,returnUrl,c,navigation.HistoryPage,navigation.HistoryType,request);}
    private async Task<IActionResult> ExecuteCommand(Guid id,string dialog,object request,ActionNavigationContext navigation,Func<Task> command,CancellationToken c,string success="Registro atualizado com sucesso."){if(!TryScope(out var o,out var u))return Forbid();var returnUrl=SafeReturnUrl(navigation.ReturnUrl,"/ActionCenter/Items","/ActionCenter","/ActionCenter/Items","/ActionCenter/Plans/Details/");var historyPage=Math.Max(1,navigation.HistoryPage);if(ModelState.IsValid)try{await command();TempData["ActionSuccess"]=success;return RedirectToAction(nameof(ItemDetails),new{id,historyPage,returnUrl});}catch(ConcurrencyConflictException e){ModelState.AddModelError("",e.Message+" Consulte os dados atuais antes de reenviar.");}catch(Exception e)when(e is ConflictAppException or ArgumentException){ModelState.AddModelError("",e.Message);}catch(KeyNotFoundException){return NotFound();}return await ItemPage(o,u,id,historyPage,request,dialog,returnUrl,c);}
    private async Task<IActionResult> ItemPage(Guid o,Guid u,Guid id,int page,object? command,string? dialog,string returnUrl,CancellationToken c){var detail=await items.Details(o,u,id,Wide,Manage,CompletePermission,page,c);return detail is null?NotFound():View("ItemDetails",new ActionItemPageViewModel(detail,command,dialog,returnUrl));}
    private async Task<IActionResult> PlanPage(Guid o,Guid u,Guid id,int page,CreateActionItemRequest? command,string? dialog,string returnUrl,CancellationToken c,int historyPage=1,string? historyType=null,object? operationCommand=null){var plan=await plans.Get(o,u,id,Wide,c);if(plan is null)return NotFound();var activities=await items.List(o,u,id,Wide,new ActionItemListQuery(Page:page,PageSize:10),c);var history=await plans.History(o,u,id,Wide,historyPage,historyType,c);var readiness=await plans.ClosureCheck(o,u,id,Wide,c);var capabilities=new ActionPlanCapabilities(Manage&&(plan.Status is "draft" or "proposed" or "approved"),Manage&&(plan.Status is not "completed" and not "canceled"),Manage&&(plan.Status is not "completed" and not "canceled"),Manage&&plan.Status=="draft",Approve&&plan.Status=="proposed",Approve&&plan.Status=="proposed",Manage&&plan.Status=="approved",CompletePermission&&plan.Status=="in_execution",Manage&&(plan.Status is not "completed" and not "canceled"));return View("PlanDetails",new ActionPlanDetailsViewModel(plan,activities,history,await items.ResponsibleOptions(o,new OptionQuery(PageSize:20,IncludeId:command?.ResponsibleUserId),c),capabilities,readiness,operationCommand??command,dialog,returnUrl,historyType));}
    private string CurrentUrl()=>Request.Path+Request.QueryString;
    private string SafeReturnUrl(string? value,string fallback,params string[] allowedPaths){if(string.IsNullOrWhiteSpace(value)||!Url.IsLocalUrl(value))return fallback;var path=value.Split('?',2)[0];return allowedPaths.Any(allowed=>allowed.EndsWith('/')?path.StartsWith(allowed,StringComparison.OrdinalIgnoreCase):path.Equals(allowed,StringComparison.OrdinalIgnoreCase))?value:fallback;}
}
[Authorize] public sealed class ActionPlansController:Controller{[HttpGet("ActionPlans")][HttpGet("ValoraAction")]public IActionResult Index()=>Redirect("/ActionCenter/Plans");}
public sealed record ActionPlanEditPageViewModel(ActionPlanDto Plan,EditActionPlanRequest Command,string ReturnUrl);
public sealed record ActionDashboardPageViewModel(ActionDashboardDto Dashboard,bool CanManage);
public sealed record ActionPlanCapabilities(bool CanEditContent,bool CanAssign,bool CanReschedule,bool CanSubmit,bool CanReturn,bool CanApprove,bool CanStart,bool CanComplete,bool CanCancel);
public sealed record ActionPlanDetailsViewModel(ActionPlanDto Plan,PageResult<ActionItemDto> Activities,PageResult<ActionPlanHistoryDto> History,PageResult<ActionOptionDto> ResponsibleOptions,ActionPlanCapabilities Capabilities,ActionPlanClosureCheck? Closure,object? Command,string? OpenDialog,string ReturnUrl,string? HistoryType);
public sealed record ActionPlanClosurePageViewModel(ActionPlanDto Plan,PageResult<ActionItemDto> Activities,ActionPlanClosureCheck Readiness,CompleteActionPlanRequest Command,string ReturnUrl,string? ActivityStatus,string DraftKey,bool VersionConflict);
public sealed record ActionPlanPrintViewModel(ActionPlanDto Plan,PageResult<ActionItemDto> Activities,PageResult<ActionPlanHistoryDto> History,DateTimeOffset IssuedAt,bool Detailed,int ActivityLimit,int HistoryLimit);
public sealed record ActionItemPageViewModel(ActionItemDetailsDto Details,object? Command,string? OpenDialog,string ReturnUrl);
public sealed record ActionItemListViewModel(PageResult<ActionItemDto> Page,ActionItemListQuery Query,string CurrentUrl);
public sealed record ActionPlanListViewModel(PageResult<ActionPlanDto> Page,ActionPlanListQuery Query,string CurrentUrl,bool CanCreate,bool CanEvaluate);
public sealed record ActionNavigationContext(string? ReturnUrl=null,int HistoryPage=1,string? HistoryType=null);
