using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Valora.Application.Benchmarks; using Valora.Application.Common; using Valora.Web.Models.ViewModels;
namespace Valora.Web.Controllers;
[Authorize] public sealed class BenchmarksController(ICurrentOrganizationProvider current,BenchmarkSnapshotService snapshots,BenchmarkCohortService cohorts,BenchmarkInsightService insights,BenchmarkPrivacyService privacy,BenchmarkComparisonService comparisons):Controller {
 private Guid? Scope(){var x=current.GetCurrent();return x.IsResolved&&x.OrganizationId!=Guid.Empty?x.OrganizationId:null;} private Guid UserId=>Guid.TryParse(User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value,out var id)?id:Guid.Empty;
 private async Task<IActionResult> Page(string section,CancellationToken ct){var o=Scope();if(o is null)return View("NoOrganization");var history=await snapshots.List(o.Value,ct);return View(section,new BenchmarksViewModel(history.FirstOrDefault(),history,await cohorts.List(o.Value,ct),await insights.List(o.Value,ct),await privacy.Get(o.Value,ct),section));}
 [HttpGet] public Task<IActionResult> Index(CancellationToken ct)=>Page("Index",ct); [HttpGet] public Task<IActionResult> Cohorts(CancellationToken ct)=>Page("Cohorts",ct); [HttpGet] public Task<IActionResult> Compare(CancellationToken ct)=>Page("Compare",ct); [HttpGet] public Task<IActionResult> Insights(CancellationToken ct)=>Page("Insights",ct); [HttpGet] public Task<IActionResult> Privacy(CancellationToken ct)=>Page("Privacy",ct);
 [HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> CreateCohort(BenchmarkCohortForm form,CancellationToken ct){if(!ModelState.IsValid){TempData["BenchmarkError"]="Revise os campos obrigatórios e mantenha amostra mínima de 5.";return RedirectToAction(nameof(Cohorts));}var o=Scope();if(o is null)return View("NoOrganization");await cohorts.Create(o.Value,UserId,new(){Name=form.Name,Description=form.Description,Segment=form.Segment,Industry=form.Industry,CompanySizeRange=form.CompanySizeRange,Region=form.Region,MinimumSampleSize=form.MinimumSampleSize},ct);TempData["BenchmarkMessage"]="Coorte criada com proteção de amostra configurada.";return RedirectToAction(nameof(Cohorts));}
 [HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> Compare(BenchmarkCompareForm form,CancellationToken ct){if(!ModelState.IsValid){TempData["BenchmarkError"]="Informe tipo, período, segmento e critério válidos.";return RedirectToAction(nameof(Compare));}var o=Scope();if(o is null)return View("NoOrganization");var result=await comparisons.Compare(o.Value,UserId,new(){ComparisonType=form.ComparisonType,CohortId=form.CohortId,Segment=form.Segment,Criterion=form.Criterion,PeriodStart=form.PeriodStart,PeriodEnd=form.PeriodEnd,Dimension=form.Dimension,Indicator=form.Indicator},ct);TempData["BenchmarkMessage"]=result.IsAvailable?"Comparação concluída com base agregada.":result.Limitations.FirstOrDefault();return RedirectToAction(nameof(Compare));}
}
