using Dapper;
using Valora.Application.Contracts;
using Valora.Application.RiskCompliance;

namespace Valora.Infrastructure.RiskCompliance;

public sealed class RiskComplianceRepository(IDbConnectionFactory connections,IDbTransactionFactory transactions):IRiskComplianceRepository
{
    public async Task<RiskComplianceDashboardDto> Dashboard(Guid o,CancellationToken ct)
    {
        const string sql="""SELECT count(*) FILTER(WHERE r.criticality>=15 AND r.status<>'closed')::int CriticalRisks,count(*) FILTER(WHERE r.evidence_count=0 AND r.status<>'closed')::int LowConfidenceRisks,(SELECT count(*)::int FROM valorapesquisa.risk_controls c WHERE c.organization_id=@o AND c.state IN('designed','ineffective') AND c.deleted_at IS NULL) FragileControls,(SELECT count(*)::int FROM valorapesquisa.non_conformities n WHERE n.organization_id=@o AND n.status<>'closed' AND n.deleted_at IS NULL) OpenNonConformities,(SELECT count(*)::int FROM valorapesquisa.mitigation_plans m WHERE m.organization_id=@o AND m.status<>'completed' AND m.due_at<now() AND m.deleted_at IS NULL) OverdueMitigations,(SELECT round(100.0*count(*) FILTER(WHERE a.result='conformant')/NULLIF(count(*) FILTER(WHERE a.result<>'not_assessed'),0),2) FROM valorapesquisa.compliance_assessments a WHERE a.organization_id=@o AND a.deleted_at IS NULL) EvidenceBasedAdherence FROM (SELECT r.*,count(e.id)::int evidence_count FROM valorapesquisa.organizational_risks r LEFT JOIN valorapesquisa.risk_evidences e ON e.risk_id=r.id AND e.deleted_at IS NULL WHERE r.organization_id=@o AND r.deleted_at IS NULL GROUP BY r.id) r""";
        using var c=connections.Create();return await c.QuerySingleAsync<RiskComplianceDashboardDto>(new CommandDefinition(sql,new{o},cancellationToken:ct));
    }
    public async Task<IReadOnlyList<RiskDto>> Risks(Guid o,CancellationToken ct)
    {
        const string sql="""SELECT r.id,r.title,c.name Category,r.probability,r.impact,r.criticality,CASE WHEN count(e.id)=0 THEN 'hypothesis' WHEN count(e.id)=1 THEN 'low' ELSE 'evidence_supported' END Confidence,coalesce(u.name,'Responsável indisponível') OwnerName,r.status,count(e.id)::int EvidenceCount,r.created_at CreatedAt FROM valorapesquisa.organizational_risks r JOIN valorapesquisa.risk_categories c ON c.id=r.category_id AND c.organization_id=r.organization_id LEFT JOIN valorapesquisa.users u ON u.id=r.owner_user_id LEFT JOIN valorapesquisa.risk_evidences e ON e.risk_id=r.id AND e.organization_id=r.organization_id AND e.deleted_at IS NULL WHERE r.organization_id=@o AND r.deleted_at IS NULL GROUP BY r.id,c.name,u.name ORDER BY r.criticality DESC,r.updated_at DESC""";
        using var c=connections.Create();return (await c.QueryAsync<RiskDto>(new CommandDefinition(sql,new{o},cancellationToken:ct))).ToList();
    }
    public async Task<Guid> CreateRisk(Guid o,Guid actor,CreateRiskRequest r,CancellationToken ct)
    {
        var id=Guid.NewGuid();await using var u=await transactions.BeginAsync(ct);var changed=await u.Connection.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.organizational_risks(id,organization_id,category_id,title,description,probability,impact,criticality,owner_user_id,status,created_by_user_id) SELECT @id,@o,c.id,@Title,@Description,@Probability,@Impact,@Probability*@Impact,@OwnerUserId,@Status,@actor FROM valorapesquisa.risk_categories c WHERE c.id=@CategoryId AND c.organization_id=@o AND c.deleted_at IS NULL",new{id,o,actor,r.Title,r.Description,r.Probability,r.Impact,r.OwnerUserId,r.Status,r.CategoryId},u.Transaction,cancellationToken:ct));if(changed==0)throw new InvalidOperationException("Categoria de risco indisponível para esta organização.");await Event(u,o,id,actor,"risk.created","Risco registrado como hipótese até receber evidências.",ct);await u.CommitAsync();return id;
    }
    public async Task UpdateRisk(Guid o,Guid id,CreateRiskRequest r,CancellationToken ct)
    {
        using var c=connections.Create();var changed=await c.ExecuteAsync(new CommandDefinition("UPDATE valorapesquisa.organizational_risks SET category_id=@CategoryId,title=@Title,description=@Description,probability=@Probability,impact=@Impact,criticality=@Probability*@Impact,owner_user_id=@OwnerUserId,status=@Status,updated_at=now() WHERE id=@id AND organization_id=@o AND deleted_at IS NULL AND EXISTS(SELECT 1 FROM valorapesquisa.risk_categories WHERE id=@CategoryId AND organization_id=@o AND deleted_at IS NULL)",new{o,id,r.CategoryId,r.Title,r.Description,r.Probability,r.Impact,r.OwnerUserId,r.Status},cancellationToken:ct));if(changed==0)throw new KeyNotFoundException("Risco não encontrado nesta organização.");
    }
    public async Task AssessRisk(Guid o,Guid id,Guid actor,AssessRiskRequest r,CancellationToken ct)
    {
        await using var u=await transactions.BeginAsync(ct);var evidenceIds=r.EvidenceIds.Distinct().ToArray();var valid=await u.Connection.ExecuteScalarAsync<int>(new CommandDefinition("SELECT count(*)::int FROM valorapesquisa.risk_evidences WHERE organization_id=@o AND risk_id=@id AND id=ANY(@evidenceIds) AND deleted_at IS NULL",new{o,id,evidenceIds},u.Transaction,cancellationToken:ct));if(valid!=evidenceIds.Length)throw new InvalidOperationException("Uma ou mais evidências não pertencem ao risco e à organização atuais.");var adjustment=valid>=2?1.0m:valid==1?0.95m:0.85m;var assessmentId=Guid.NewGuid();var changed=await u.Connection.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.risk_assessments(id,organization_id,risk_id,probability,impact,base_score,evidence_adjustment,adjusted_score,confidence,rationale,assessed_by_user_id) SELECT @assessmentId,@o,id,@Probability,@Impact,@Probability*@Impact,@adjustment,@Probability*@Impact*@adjustment,CASE WHEN @valid=0 THEN 'hypothesis' WHEN @valid=1 THEN 'low' ELSE 'evidence_supported' END,@Rationale,@actor FROM valorapesquisa.organizational_risks WHERE id=@id AND organization_id=@o AND deleted_at IS NULL",new{assessmentId,o,id,actor,r.Probability,r.Impact,r.Rationale,adjustment,valid},u.Transaction,cancellationToken:ct));if(changed==0)throw new KeyNotFoundException("Risco não encontrado nesta organização.");await u.Connection.ExecuteAsync(new CommandDefinition("UPDATE valorapesquisa.organizational_risks SET probability=@Probability,impact=@Impact,criticality=@Probability*@Impact*@adjustment,status='assessed',updated_at=now() WHERE id=@id AND organization_id=@o",new{o,id,r.Probability,r.Impact,adjustment},u.Transaction,cancellationToken:ct));await Event(u,o,id,actor,"risk.assessed",valid==0?"Avaliação sem evidência; confiança classificada como hipótese.":"Avaliação vinculada a evidências verificáveis.",ct);await u.CommitAsync();
    }
    public async Task<IReadOnlyList<ControlDto>> Controls(Guid o,CancellationToken ct){const string sql="SELECT c.id,c.name,c.risk_id RiskId,c.requirement_id RequirementId,c.state,coalesce(u.name,'Responsável indisponível') OwnerName,(SELECT t.result FROM valorapesquisa.control_tests t WHERE t.control_id=c.id AND t.deleted_at IS NULL ORDER BY t.tested_at DESC LIMIT 1) LastTestResult,c.created_at CreatedAt FROM valorapesquisa.risk_controls c LEFT JOIN valorapesquisa.users u ON u.id=c.owner_user_id WHERE c.organization_id=@o AND c.deleted_at IS NULL ORDER BY c.updated_at DESC";using var c=connections.Create();return(await c.QueryAsync<ControlDto>(new CommandDefinition(sql,new{o},cancellationToken:ct))).ToList();}
    public async Task<Guid> CreateControl(Guid o,Guid actor,CreateControlRequest r,CancellationToken ct){var id=Guid.NewGuid();using var c=connections.Create();var changed=await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.risk_controls(id,organization_id,risk_id,requirement_id,name,description,state,owner_user_id,created_by_user_id) SELECT @id,@o,@RiskId,@RequirementId,@Name,@Description,@State,@OwnerUserId,@actor WHERE (@RiskId IS NOT NULL AND EXISTS(SELECT 1 FROM valorapesquisa.organizational_risks WHERE id=@RiskId AND organization_id=@o AND deleted_at IS NULL)) OR (@RequirementId IS NOT NULL AND EXISTS(SELECT 1 FROM valorapesquisa.compliance_requirements WHERE id=@RequirementId AND organization_id=@o AND deleted_at IS NULL))",new{id,o,actor,r.RiskId,r.RequirementId,r.Name,r.Description,r.State,r.OwnerUserId},cancellationToken:ct));if(changed==0)throw new InvalidOperationException("O vínculo do controle não pertence à organização atual.");return id;}
    public async Task TestControl(Guid o,Guid id,Guid actor,TestControlRequest r,CancellationToken ct){await using var u=await transactions.BeginAsync(ct);var evidenceIds=r.EvidenceIds.Distinct().ToArray();var changed=await u.Connection.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.control_tests(organization_id,control_id,result,notes,responsible_user_id,evidence_ids,tested_by_user_id) SELECT @o,id,@Result,@Notes,@ResponsibleUserId,@evidenceIds,@actor FROM valorapesquisa.risk_controls WHERE id=@id AND organization_id=@o AND deleted_at IS NULL",new{o,id,actor,r.Result,r.Notes,r.ResponsibleUserId,evidenceIds},u.Transaction,cancellationToken:ct));if(changed==0)throw new KeyNotFoundException("Controle não encontrado nesta organização.");await u.Connection.ExecuteAsync(new CommandDefinition("UPDATE valorapesquisa.risk_controls SET state=CASE WHEN @Result='ineffective' THEN 'ineffective' ELSE 'tested' END,updated_at=now() WHERE id=@id AND organization_id=@o",new{o,id,r.Result},u.Transaction,cancellationToken:ct));await Event(u,o,id,actor,"control.tested","Teste registrado com responsável e evidências.",ct);await u.CommitAsync();}
    public async Task<IReadOnlyList<FrameworkDto>> Frameworks(Guid o,CancellationToken ct){const string sql="SELECT f.id,f.name,f.version,f.status,count(r.id)::int RequirementCount,round(100.0*count(a.id) FILTER(WHERE a.result='conformant')/NULLIF(count(a.id) FILTER(WHERE a.result<>'not_assessed'),0),2) Adherence FROM valorapesquisa.compliance_frameworks f LEFT JOIN valorapesquisa.compliance_requirements r ON r.framework_id=f.id AND r.deleted_at IS NULL LEFT JOIN LATERAL(SELECT result,id FROM valorapesquisa.compliance_assessments WHERE requirement_id=r.id AND deleted_at IS NULL ORDER BY assessed_at DESC LIMIT 1)a ON true WHERE f.organization_id=@o AND f.deleted_at IS NULL GROUP BY f.id ORDER BY f.name";using var c=connections.Create();return(await c.QueryAsync<FrameworkDto>(new CommandDefinition(sql,new{o},cancellationToken:ct))).ToList();}
    public async Task AssessCompliance(Guid o,Guid actor,ComplianceAssessmentRequest r,CancellationToken ct){using var c=connections.Create();var changed=await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.compliance_assessments(organization_id,requirement_id,result,rationale,evidence_ids,assessed_by_user_id) SELECT @o,id,@Result,@Rationale,@evidenceIds,@actor FROM valorapesquisa.compliance_requirements WHERE id=@RequirementId AND organization_id=@o AND deleted_at IS NULL",new{o,actor,r.RequirementId,r.Result,r.Rationale,evidenceIds=r.EvidenceIds.Distinct().ToArray()},cancellationToken:ct));if(changed==0)throw new KeyNotFoundException("Requisito não encontrado nesta organização.");}
    public async Task<IReadOnlyList<NonConformityDto>> NonConformities(Guid o,CancellationToken ct){const string sql="SELECT n.id,n.title,n.severity,n.status,(SELECT id FROM valorapesquisa.mitigation_plans WHERE non_conformity_id=n.id AND deleted_at IS NULL ORDER BY created_at DESC LIMIT 1) MitigationPlanId,n.detected_at DetectedAt FROM valorapesquisa.non_conformities n WHERE n.organization_id=@o AND n.deleted_at IS NULL ORDER BY n.detected_at DESC";using var c=connections.Create();return(await c.QueryAsync<NonConformityDto>(new CommandDefinition(sql,new{o},cancellationToken:ct))).ToList();}
    public async Task<Guid> CreateMitigation(Guid o,Guid actor,CreateMitigationPlanRequest r,CancellationToken ct){var id=Guid.NewGuid();using var c=connections.Create();var changed=await c.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.mitigation_plans(id,organization_id,non_conformity_id,title,responsible_user_id,due_at,priority,status,created_by_user_id) SELECT @id,@o,id,@Title,@ResponsibleUserId,@DueAt,@Priority,'planned',@actor FROM valorapesquisa.non_conformities WHERE id=@NonConformityId AND organization_id=@o AND deleted_at IS NULL",new{id,o,actor,r.NonConformityId,r.Title,r.ResponsibleUserId,r.DueAt,r.Priority},cancellationToken:ct));if(changed==0)throw new KeyNotFoundException("Não conformidade não encontrada nesta organização.");return id;}
    public async Task<IReadOnlyList<HeatmapPointDto>> Heatmap(Guid o,CancellationToken ct){const string sql="SELECT r.id RiskId,r.title,r.probability,r.impact,r.criticality,CASE WHEN EXISTS(SELECT 1 FROM valorapesquisa.risk_evidences e WHERE e.risk_id=r.id AND e.organization_id=@o AND e.deleted_at IS NULL) THEN 'evidence_supported' ELSE 'hypothesis' END Confidence FROM valorapesquisa.organizational_risks r WHERE r.organization_id=@o AND r.deleted_at IS NULL AND r.status<>'closed' ORDER BY r.criticality DESC";using var c=connections.Create();return(await c.QueryAsync<HeatmapPointDto>(new CommandDefinition(sql,new{o},cancellationToken:ct))).ToList();}
    private static Task Event(IUnitOfWork u,Guid o,Guid entityId,Guid actor,string eventType,string summary,CancellationToken ct)=>u.Connection.ExecuteAsync(new CommandDefinition("INSERT INTO valorapesquisa.risk_events(organization_id,entity_type,entity_id,event_type,actor_user_id,summary) VALUES(@o,'risk_compliance',@entityId,@eventType,@actor,@summary)",new{o,entityId,eventType,actor,summary},u.Transaction,cancellationToken:ct));
}
