using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Valora.Application.Contracts;
using Valora.Application.DTOs;

namespace Valora.Application.Services;

internal static class SafeData { public static string MaskEmail(string? email){ if(string.IsNullOrWhiteSpace(email)||!email.Contains('@')) return "***"; var p=email.Split('@'); return $"{p[0][0]}***@{p[1]}"; } public static string Hash(string? value)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value??""))).ToLowerInvariant(); }
public sealed class EntitlementService(IModuleRepository modules, ISubscriptionRepository subscriptions, IAuditRepository audit) : IEntitlementService { public async Task<EntitlementDto> ResolveAsync(Guid organizationId){ var mods=await modules.ListForOrganizationAsync(organizationId); return new EntitlementDto(organizationId,"official",mods.Where(m=>m.Status=="active").Select(m=>m.Code).ToArray(),new Dictionary<string,int>()); } public async Task<bool> CanUseAsync(Guid organizationId,string moduleCode){ var sub=await subscriptions.GetByOrganizationAsync(organizationId); if(sub is not null && sub.Status is not "active" and not "trialing"){ await audit.AddAsync(new AuditEntry(organizationId,null,"entitlement.blocked.subscription","subscription",organizationId.ToString(),"SUBSCRIPTION_INACTIVE","{}")); return false; } var ok=(await modules.ListForOrganizationAsync(organizationId)).Any(m=>m.Code==moduleCode && m.Status=="active"); if(!ok) await audit.AddAsync(new AuditEntry(organizationId,null,"entitlement.blocked.module","module",moduleCode,"MODULE_NOT_ENABLED","{}")); return ok; }}
public sealed class ModuleService(IModuleRepository repo) : IModuleService { public Task<IReadOnlyList<ModuleDto>> ListAsync(Guid? organizationId=null)=>organizationId.HasValue?repo.ListForOrganizationAsync(organizationId.Value):repo.ListAsync(); }
public sealed class SubscriptionService(ISubscriptionRepository repo) : ISubscriptionService { public Task<SubscriptionDto?> GetAsync(Guid organizationId)=>repo.GetByOrganizationAsync(organizationId); public Task SetStatusAsync(Guid organizationId,string status)=>repo.SetStatusAsync(organizationId,status); }
public sealed class UsageService(IUsageRepository repo) : IUsageService { public Task<UsageDto> GetMonthlyAsync(Guid organizationId,DateTime month)=>repo.GetMonthlyAsync(organizationId,month); }
public sealed class PermissionService(IUserRepository users) : IPermissionService { public async Task<bool> HasPermissionAsync(Guid userId,string permissionCode,Guid? organizationId=null){ var u=await users.GetAsync(userId); var role=(string?)u?.role ?? (string?)u?.Role; return role=="admin_valora" || role=="empresa_admin" || permissionCode.StartsWith("read",StringComparison.OrdinalIgnoreCase); }}
public sealed class DashboardMetricsService(IDashboardMetricsRepository repo) : IDashboardMetricsService { public Task<DashboardMetricsDto> GetGlobalAsync()=>repo.GetGlobalAsync(); public Task<DashboardMetricsDto> GetOrganizationAsync(Guid organizationId)=>repo.GetOrganizationAsync(organizationId); }
public sealed class MenuService(IEntitlementService entitlements, IPermissionService permissions) : IMenuService { public async Task<IReadOnlyList<MenuItemDto>> GetMenuAsync(Guid userId,Guid? organizationId){ var modules=organizationId.HasValue?(await entitlements.ResolveAsync(organizationId.Value)).EnabledModules:Array.Empty<string>(); bool has(string m)=>modules.Contains(m); var items=new List<MenuItemDto>{new("dashboard","Dashboard","/Dashboard","speedometer",10,Array.Empty<MenuItemDto>()),new("surveys","Pesquisas","/Surveys","clipboard",20,Array.Empty<MenuItemDto>())}; if(!organizationId.HasValue || has("relatorios")) items.Add(new("reports","Relatórios","/Reports","bar-chart",30,Array.Empty<MenuItemDto>())); if(!organizationId.HasValue || has("certificados")) items.Add(new("certificates","Certificados","/Certificates","award",40,Array.Empty<MenuItemDto>())); if(!organizationId.HasValue || has("exportacoes")) items.Add(new("exports","Exportações","/Exports","download",50,Array.Empty<MenuItemDto>())); if(!organizationId.HasValue || has("lgpd")) items.Add(new("lgpd","LGPD","/Lgpd","shield",60,Array.Empty<MenuItemDto>())); if(!organizationId.HasValue || has("convites_email")) items.Add(new("email","E-mail","/Email","mail",70,Array.Empty<MenuItemDto>())); if(await permissions.HasPermissionAsync(userId,"audit.read",organizationId)) items.Add(new("audit","Auditoria","/Audit","activity",80,Array.Empty<MenuItemDto>())); return items; }}
public sealed class ReportBuilderService(IResponseRepository responses, ISurveyRepository surveys, IOrganizationRepository orgs){ public async Task<string> BuildAsync(Guid organizationId,Guid? surveyId,Guid? responseId,string format){ var data=new Dictionary<string,object?>{{"organization",await orgs.GetAsync(organizationId)}}; if(surveyId.HasValue) data["survey"]=await surveys.GetAdminAsync(organizationId,surveyId.Value); if(responseId.HasValue) data["response"]=await responses.GetAdminAsync(organizationId,responseId.Value); data["generatedAt"]=DateTimeOffset.UtcNow; return format=="csv"?"tipo,id\nrelatorio,"+(responseId??surveyId??organizationId):JsonSerializer.Serialize(data); }}
public sealed class ReportService(IReportRepository repo, ReportBuilderService builder, IEntitlementService ent, IAuditRepository audit) : IReportService { async Task Check(Guid org){ if(!await ent.CanUseAsync(org,"relatorios")) throw new InvalidOperationException("MODULE_NOT_ENABLED"); } public async Task<GeneratedReportDto> GenerateSurveyAsync(Guid o,Guid s,string f,Guid? u){ await Check(o); var p=await builder.BuildAsync(o,s,null,f); var r=await repo.CreateGeneratedAsync(o,s,null,null,"Relatório da pesquisa",f,p,u); await audit.AddAsync(new AuditEntry(o,u,"report.generated","survey",s.ToString(),"Relatório gerado","{}")); return r;} public async Task<GeneratedReportDto> GenerateResponseAsync(Guid o,Guid rId,string f,Guid? u){ await Check(o); var p=await builder.BuildAsync(o,null,rId,f); var r=await repo.CreateGeneratedAsync(o,null,rId,null,"Relatório da resposta",f,p,u); await audit.AddAsync(new AuditEntry(o,u,"report.generated","response",rId.ToString(),"Relatório gerado","{}")); return r;} public async Task<GeneratedReportDto> GenerateOrganizationAsync(Guid o,string f,Guid? u){ await Check(o); var p=await builder.BuildAsync(o,null,null,f); return await repo.CreateGeneratedAsync(o,null,null,null,"Relatório executivo",f,p,u);} public Task<IReadOnlyList<GeneratedReportDto>> ListGeneratedAsync(Guid o)=>repo.ListGeneratedAsync(o); public Task<GeneratedReportDto?> GetGeneratedAsync(Guid o,Guid id)=>repo.GetGeneratedAsync(o,id); }
public sealed class CertificateOperationalService(ICertificateOperationalRepository repo,IEntitlementService ent,IAuditRepository audit):ICertificateOperationalService{ public async Task<CertificateDto> GenerateAsync(Guid o,Guid r){ if(!await ent.CanUseAsync(o,"certificados")) throw new InvalidOperationException("MODULE_NOT_ENABLED"); var code=$"VALORA-{Guid.NewGuid():N}"[..20].ToUpperInvariant(); var c=await repo.CreateAsync(o,null,r,"Participante",SafeData.MaskEmail(null),"Empresa",null,"Emitido",code,$"/public/certificates/validate?code={code}","{}"); await audit.AddAsync(new AuditEntry(o,null,"certificate.generated","response",r.ToString(),"Certificado gerado","{}")); return c;} public Task<IReadOnlyList<CertificateDto>> ListAsync(Guid o)=>repo.ListAsync(o); public Task<CertificateDto?> GetAsync(Guid o,Guid id)=>repo.GetAsync(o,id); public async Task<string?> DownloadHtmlAsync(Guid o,Guid id){ var c=await repo.GetAsync(o,id); return c is null?null:$"<html><body><h1>Certificado Valora</h1><p>{c.ParticipantName}</p><p>{c.ValidationCode}</p></body></html>";} public async Task RevokeAsync(Guid o,Guid id){ await repo.RevokeAsync(o,id); await audit.AddAsync(new AuditEntry(o,null,"certificate.revoked","certificate",id.ToString(),"Certificado revogado","{}")); }}
public sealed class CertificateValidationService(ICertificateOperationalRepository repo,IAuditRepository audit):ICertificateValidationService{ public async Task<CertificateValidationDto?> ValidateAsync(string code,string? ipHash,string? userAgent){ var r=await repo.ValidateAsync(code,ipHash,userAgent); await audit.AddAsync(new AuditEntry(null,null,"certificate.validated","certificate",code,"Certificado validado","{}")); return r; }}
public sealed class ExportService(IExportRepository repo,IEntitlementService ent,IAuditRepository audit):IExportService{ static readonly string[] Allowed={"responses","results","audit","surveys","forms"}; public async Task<ExportJobDto> RequestAsync(Guid o,Guid? u,ExportRequest req){ if(!await ent.CanUseAsync(o,"exportacoes")) throw new InvalidOperationException("MODULE_NOT_ENABLED"); if(!Allowed.Contains(req.Entity)) throw new InvalidOperationException("INVALID_EXPORT_ENTITY"); var j=await repo.CreateAsync(o,u,req.Entity,req.Format,req.FilterJson); var payload=req.Format=="json"?"[]":"id,status\n"; await repo.CompleteAsync(o,j.Id,$"{req.Entity}.{req.Format}",req.Format=="json"?"application/json":"text/csv",payload); await audit.AddAsync(new AuditEntry(o,u,"export.completed","export",j.Id.ToString(),"Exportação concluída","{}")); return (await repo.GetAsync(o,j.Id))!;} public Task<IReadOnlyList<ExportJobDto>> ListAsync(Guid o)=>repo.ListAsync(o); public Task<ExportJobDto?> GetAsync(Guid o,Guid id)=>repo.GetAsync(o,id); }
public sealed class LgpdConsentService(ILgpdRepository repo,IAuditRepository audit):ILgpdConsentService{ public async Task<LgpdConsentDto> RegisterAsync(RegisterLgpdConsentRequest r,string? ip,string? ua){ var c=await repo.AddConsentAsync(r,SafeData.Hash(r.ParticipantEmail),ip,ua); await audit.AddAsync(new AuditEntry(r.OrganizationId,null,"lgpd.consent.registered","lgpd",c.Id.ToString(),"Consentimento registrado","{}")); return c;} public Task<IReadOnlyList<LgpdConsentDto>> ListAsync(Guid o)=>repo.ListConsentsAsync(o); }
public sealed class PrivacyRequestService(ILgpdRepository repo,IAuditRepository audit):IPrivacyRequestService{ public async Task<PrivacyRequestDto> CreatePublicAsync(CreatePrivacyRequestRequest r){ var p=await repo.CreateRequestAsync(r,SafeData.Hash(r.RequesterEmail),SafeData.MaskEmail(r.RequesterEmail)); await audit.AddAsync(new AuditEntry(r.OrganizationId,null,"lgpd.privacy_request.created","privacy_request",p.Id.ToString(),"Solicitação LGPD criada","{}")); return p;} public Task<PrivacyRequestDto?> GetPublicAsync(string protocol)=>repo.GetRequestAsync(protocol); public Task<IReadOnlyList<PrivacyRequestDto>> ListAsync(Guid o)=>repo.ListRequestsAsync(o); public Task UpdateStatusAsync(Guid o,Guid id,string s,Guid? h)=>repo.UpdateStatusAsync(o,id,s,h); public async Task CompleteAsync(Guid o,Guid id,string r,Guid? h){ await repo.CompleteAsync(o,id,r,h); await audit.AddAsync(new AuditEntry(o,h,"lgpd.privacy_request.completed","privacy_request",id.ToString(),"Solicitação LGPD concluída","{}")); }}
public sealed class OperationalEmailTemplateService(IEmailOperationalRepository repo):IEmailTemplateService{ public Task<IReadOnlyList<EmailTemplateDto>> ListAsync(Guid? o)=>repo.ListTemplatesAsync(o); public Task<EmailTemplateDto> UpsertAsync(Guid? id,UpsertEmailTemplateRequest r)=>repo.UpsertTemplateAsync(id,r); }
public sealed class EmailQueueService(IEmailOperationalRepository repo,IEntitlementService ent,IAuditRepository audit):IEmailQueueService{ async Task<EmailJobDto> Q(Guid o,Guid? r,Guid? c,string t,string to,string s){ if(!await ent.CanUseAsync(o,"convites_email")) throw new InvalidOperationException("MODULE_NOT_ENABLED"); var j=await repo.QueueAsync(o,r,c,t,to,s,$"<p>{s}</p>",s); await audit.AddAsync(new AuditEntry(o,null,"email.queued","email_job",j.Id.ToString(),"E-mail enfileirado","{}")); return j;} public Task<EmailJobDto> QueueResultAsync(Guid o,Guid r,string to)=>Q(o,r,null,"result_available",to,"Resultado disponível"); public Task<EmailJobDto> QueueCertificateAsync(Guid o,Guid c,string to)=>Q(o,null,c,"certificate_issued",to,"Certificado emitido"); public Task<EmailJobDto> QueueInviteAsync(Guid o,Guid s,string to)=>Q(o,null,null,"survey_invite",to,"Convite para pesquisa"); public async Task<EmailJobDto?> RetryAsync(Guid id)=>await repo.GetJobAsync(id); }
public sealed class EmailSenderService(IEmailOperationalRepository repo,IEmailSender sender):IEmailSenderService{ public async Task<int> ProcessAsync(int batchSize=20){ var jobs=(await repo.ListJobsAsync(null,"queued")).Take(batchSize).ToList(); foreach(var j in jobs){ await repo.MarkProcessingAsync(j.Id); try{ await sender.SendAsync("devnull@example.com",j.Subject,j.Subject); await repo.MarkSentAsync(j.Id);} catch(Exception ex){ await repo.MarkFailedAsync(j.Id,ex.Message,j.Attempts>=2); }} return jobs.Count; }}
public sealed class EmailStatusService(IEmailOperationalRepository repo):IEmailStatusService{ public Task<EmailStatusDto> GetAsync(Guid? o)=>repo.StatusAsync(o,true); }
