using System.Text.Json;
using Dapper;
using ValoraPesquisa.Application.Contracts;
using ValoraPesquisa.Application.DTOs;
using ValoraPesquisa.Domain.Entities;
using ValoraPesquisa.Infrastructure.Database;
namespace ValoraPesquisa.Infrastructure.Repositories;
public static class Scope{ public static void DemandOrg(CurrentUser u,Guid org){ if(!u.IsAdminValora && u.OrganizationId!=org) throw new UnauthorizedAccessException("Acesso negado para esta organização."); } }
public sealed class AuditService(PostgresConnectionFactory db):IAuditService{
 static string Clean(object? metadata){ var json=JsonSerializer.Serialize(metadata??new{}); foreach(var word in new[]{"password","senha","token","hash","secret","segredo"}) json=json.Replace(word,"redacted",StringComparison.OrdinalIgnoreCase); return json; }
 public async Task RecordAsync(Guid? orgId,Guid? userId,string action,string entity,Guid? entityId,string correlationId,object? metadata=null){ using var c=db.Create(); await c.ExecuteAsync("insert into valorapesquisa.audit_logs(id,organization_id,user_id,action,entity,entity_id,correlation_id,metadata,created_at) values(gen_random_uuid(),@orgId,@userId,@action,@entity,@entityId,@correlationId,cast(@metadata as jsonb),now())",new{orgId,userId,action,entity,entityId,correlationId,metadata=Clean(metadata)}); }
 public async Task<IReadOnlyList<AuditEventDto>> ListAsync(CurrentUser u){ using var c=db.Create(); return (await c.QueryAsync<AuditEventDto>(u.IsAdminValora?"select id,organization_id OrganizationId,user_id UserId,action,entity,entity_id EntityId,correlation_id CorrelationId,metadata::text Metadata,created_at CreatedAt from valorapesquisa.audit_logs order by created_at desc limit 200":"select id,organization_id OrganizationId,user_id UserId,action,entity,entity_id EntityId,correlation_id CorrelationId,metadata::text Metadata,created_at CreatedAt from valorapesquisa.audit_logs where organization_id=@OrganizationId order by created_at desc limit 200",u)).ToList(); }}
public sealed class OrganizationRepository(PostgresConnectionFactory db):IOrganizationRepository{
 const string cols="id,name,public_name PublicName,slug,document,email,phone,status,plan_code PlanCode,created_at CreatedAt,updated_at UpdatedAt";
 public async Task<IReadOnlyList<OrganizationDto>> ListAsync(CurrentUser u){ using var c=db.Create(); var sql=u.IsAdminValora?$"select {cols} from valorapesquisa.organizations where is_deleted=false order by name":$"select {cols} from valorapesquisa.organizations where id=@OrganizationId and is_deleted=false"; return (await c.QueryAsync<OrganizationDto>(sql,u)).ToList(); }
 public async Task<OrganizationDto?> FindByIdAsync(Guid id,CurrentUser? u=null){ if(u!=null)Scope.DemandOrg(u,id); using var c=db.Create(); return await c.QuerySingleOrDefaultAsync<OrganizationDto>($"select {cols} from valorapesquisa.organizations where id=@id and is_deleted=false",new{id}); }
 public async Task<Organization?> FindEntityByIdAsync(Guid id){ using var c=db.Create(); return await c.QuerySingleOrDefaultAsync<Organization>("select * from valorapesquisa.organizations where id=@id and is_deleted=false",new{id}); }
 public async Task<OrganizationDto?> FindBySlugAsync(string slug){ using var c=db.Create(); return await c.QuerySingleOrDefaultAsync<OrganizationDto>($"select {cols} from valorapesquisa.organizations where slug=@slug and is_deleted=false",new{slug}); }
 public async Task<OrganizationDto> CreateAsync(Organization o){ using var c=db.Create(); await c.ExecuteAsync("insert into valorapesquisa.organizations(id,name,public_name,slug,document,email,phone,status,plan_code,created_at,created_by,updated_by,is_deleted) values(@Id,@Name,@PublicName,@Slug,@Document,@Email,@Phone,@Status,@PlanCode,@CreatedAt,@CreatedBy,@UpdatedBy,false)",o); return (await FindByIdAsync(o.Id))!; }
 public async Task<OrganizationDto> UpdateAsync(Guid id,string name,string publicName,string slug,string? document,string email,string? phone,string status,string planCode,CurrentUser u){ Scope.DemandOrg(u,id); using var c=db.Create(); await c.ExecuteAsync("update valorapesquisa.organizations set name=@name,public_name=@publicName,slug=@slug,document=@document,email=@email,phone=@phone,status=@status,plan_code=@planCode,updated_at=now(),updated_by=@UserId where id=@id and is_deleted=false",new{id,name,publicName,slug,document,email,phone,status,planCode,UserId=u.Id}); return (await FindByIdAsync(id,u))!; }}
public sealed class UserRepository(PostgresConnectionFactory db):IUserRepository{
 const string dto="id,organization_id OrganizationId,name,email,role,status,phone,last_login_at LastLoginAt,created_at CreatedAt,updated_at UpdatedAt";
 public async Task<User?> FindByEmailAsync(string email){using var c=db.Create(); return await c.QuerySingleOrDefaultAsync<User>("select * from valorapesquisa.users where lower(email)=lower(@email) and is_deleted=false",new{email});}
 public async Task<User?> FindByIdAsync(Guid id){using var c=db.Create(); return await c.QuerySingleOrDefaultAsync<User>("select * from valorapesquisa.users where id=@id and is_deleted=false",new{id});}
 public async Task<IReadOnlyList<UserDto>> ListAsync(CurrentUser u){using var c=db.Create(); return (await c.QueryAsync<UserDto>(u.IsAdminValora?$"select {dto} from valorapesquisa.users where is_deleted=false order by name":$"select {dto} from valorapesquisa.users where organization_id=@OrganizationId and is_deleted=false order by name",u)).ToList();}
 public async Task<UserDto> CreateAsync(User u){using var c=db.Create(); await c.ExecuteAsync("insert into valorapesquisa.users(id,organization_id,name,email,password_hash,role,status,phone,created_at,is_deleted) values(@Id,@OrganizationId,@Name,@Email,@PasswordHash,@Role,@Status,@Phone,@CreatedAt,false)",u); return (await c.QuerySingleAsync<UserDto>($"select {dto} from valorapesquisa.users where id=@Id",u));}
 public async Task<UserDto> UpdateAsync(Guid id,string name,string email,string? phone,string role,Guid? organizationId,CurrentUser u){ if(!u.IsAdminValora && organizationId!=u.OrganizationId) throw new UnauthorizedAccessException("Acesso negado."); using var c=db.Create(); await c.ExecuteAsync("update valorapesquisa.users set name=@name,email=@email,phone=@phone,role=@role,organization_id=@organizationId,updated_at=now() where id=@id and is_deleted=false",new{id,name,email,phone,role,organizationId}); return await c.QuerySingleAsync<UserDto>($"select {dto} from valorapesquisa.users where id=@id",new{id});}
 public async Task SetStatusAsync(Guid id,string status,CurrentUser u){ var target=await FindByIdAsync(id)??throw new ArgumentException("Usuário não encontrado."); if(target.OrganizationId.HasValue)Scope.DemandOrg(u,target.OrganizationId.Value); using var c=db.Create(); await c.ExecuteAsync("update valorapesquisa.users set status=@status,updated_at=now() where id=@id",new{id,status});}
 public async Task UpdateLastLoginAsync(Guid id){using var c=db.Create(); await c.ExecuteAsync("update valorapesquisa.users set last_login_at=now() where id=@id",new{id});}}
public sealed class FormRepository(PostgresConnectionFactory db):IFormRepository{
 public async Task<IReadOnlyList<FormDto>> ListAsync(CurrentUser u){ using var c=db.Create(); return (await c.QueryAsync<FormDto>(u.IsAdminValora?"select id,organization_id OrganizationId,title,description,status,created_at CreatedAt,updated_at UpdatedAt from valorapesquisa.forms where is_deleted=false order by created_at desc":"select id,organization_id OrganizationId,title,description,status,created_at CreatedAt,updated_at UpdatedAt from valorapesquisa.forms where organization_id=@OrganizationId and is_deleted=false order by created_at desc",u)).ToList(); }
 public async Task<FormDto?> GetAsync(Guid id,CurrentUser u){ using var c=db.Create(); var f=await c.QuerySingleOrDefaultAsync<Form>("select * from valorapesquisa.forms where id=@id and is_deleted=false",new{id}); if(f==null)return null; Scope.DemandOrg(u,f.OrganizationId); return await Load(f.Id); }
 public async Task<FormDto?> GetPublicAsync(Guid id,Guid org){ using var c=db.Create(); var f=await c.QuerySingleOrDefaultAsync<Form>("select * from valorapesquisa.forms where id=@id and organization_id=@org and is_deleted=false",new{id,org}); return f==null?null:await Load(id); }
 async Task<FormDto?> Load(Guid id){ using var c=db.Create(); var form=await c.QuerySingleOrDefaultAsync<FormDto>("select id,organization_id OrganizationId,title,description,status,created_at CreatedAt,updated_at UpdatedAt from valorapesquisa.forms where id=@id",new{id}); if(form==null)return null; var qs=(await c.QueryAsync<QuestionDto>("select id,text,type,position,required,weight,max_score MaxScore from valorapesquisa.questions where form_id=@id order by position",new{id})).ToList(); var all=(await c.QueryAsync<QuestionOptionDto>("select id,question_id QuestionId,text,score,position from valorapesquisa.question_options where question_id=any(@ids) order by position",new{ids=qs.Select(q=>q.Id).ToArray()})).ToList(); return form with { Questions=qs.Select(q=>q with {Options=all.Where(o=>o.QuestionId==q.Id).ToList()}).ToList()}; }
 public async Task<FormDto> SaveAsync(Form f,CurrentUser u){ Scope.DemandOrg(u,f.OrganizationId); if(string.IsNullOrWhiteSpace(f.Title))throw new ArgumentException("Título obrigatório."); if(f.Questions.Count==0)throw new ArgumentException("Informe ao menos uma pergunta."); using var c=db.Create(); c.Open(); using var tx=c.BeginTransaction(); await c.ExecuteAsync("insert into valorapesquisa.forms(id,organization_id,title,description,status,created_at,is_deleted) values(@Id,@OrganizationId,@Title,@Description,@Status,@CreatedAt,false) on conflict(id) do update set title=@Title,description=@Description,status=@Status,updated_at=now()",f,tx); await c.ExecuteAsync("delete from valorapesquisa.question_options where question_id in (select id from valorapesquisa.questions where form_id=@Id); delete from valorapesquisa.questions where form_id=@Id",f,tx); foreach(var q in f.Questions){ await c.ExecuteAsync("insert into valorapesquisa.questions(id,form_id,text,type,position,required,weight,max_score) values(@Id,@FormId,@Text,@Type,@Position,@Required,@Weight,@MaxScore)",q,tx); foreach(var o in q.Options) await c.ExecuteAsync("insert into valorapesquisa.question_options(id,question_id,text,score,position) values(@Id,@QuestionId,@Text,@Score,@Position)",o,tx);} tx.Commit(); return (await Load(f.Id))!; }
 public async Task<bool> HasQuestionsAsync(Guid formId,Guid org){ using var c=db.Create(); return await c.ExecuteScalarAsync<bool>("select exists(select 1 from valorapesquisa.forms f join valorapesquisa.questions q on q.form_id=f.id where f.id=@formId and f.organization_id=@org and f.is_deleted=false)",new{formId,org}); }}
public sealed class SurveyRepository(PostgresConnectionFactory db,IFormRepository forms):ISurveyRepository{
 const string dto="id,organization_id OrganizationId,form_id FormId,title,description,status,starts_at StartsAt,expires_at ExpiresAt,show_result ShowResult,allow_repeat AllowRepeat,created_at CreatedAt,updated_at UpdatedAt";
 public async Task<IReadOnlyList<SurveyDto>> ListAsync(CurrentUser u){using var c=db.Create();return(await c.QueryAsync<SurveyDto>(u.IsAdminValora?$"select {dto} from valorapesquisa.surveys where is_deleted=false order by created_at desc":$"select {dto} from valorapesquisa.surveys where organization_id=@OrganizationId and is_deleted=false order by created_at desc",u)).ToList();}
 public async Task<SurveyDto?> GetAsync(Guid id,CurrentUser? u=null){using var c=db.Create();var s=await c.QuerySingleOrDefaultAsync<SurveyDto>($"select {dto} from valorapesquisa.surveys where id=@id and is_deleted=false",new{id}); if(s!=null&&u!=null)Scope.DemandOrg(u,s.OrganizationId); return s;}
 public async Task<Survey?> GetEntityAsync(Guid id){using var c=db.Create(); return await c.QuerySingleOrDefaultAsync<Survey>("select * from valorapesquisa.surveys where id=@id and is_deleted=false",new{id});}
 public async Task<SurveyDto> SaveAsync(Survey s,CurrentUser u){Scope.DemandOrg(u,s.OrganizationId); if(!await forms.HasQuestionsAsync(s.FormId,s.OrganizationId))throw new ArgumentException("Formulário inválido ou sem perguntas."); using var c=db.Create(); await c.ExecuteAsync("insert into valorapesquisa.surveys(id,organization_id,form_id,title,description,status,starts_at,expires_at,show_result,allow_repeat,created_at,is_deleted) values(@Id,@OrganizationId,@FormId,@Title,@Description,@Status,@StartsAt,@ExpiresAt,@ShowResult,@AllowRepeat,@CreatedAt,false) on conflict(id) do update set title=@Title,description=@Description,status=@Status,starts_at=@StartsAt,expires_at=@ExpiresAt,show_result=@ShowResult,allow_repeat=@AllowRepeat,updated_at=now()",s); return (await GetAsync(s.Id,u))!;}
 public async Task SetStatusAsync(Guid id,string status,CurrentUser u){var s=await GetAsync(id,u)??throw new ArgumentException("Pesquisa não encontrada."); if(status=="published"&&!await forms.HasQuestionsAsync(s.FormId,s.OrganizationId))throw new ArgumentException("Só é possível publicar formulário com perguntas."); using var c=db.Create(); await c.ExecuteAsync("update valorapesquisa.surveys set status=@status,updated_at=now() where id=@id",new{id,status});}}
public sealed class SurveyLinkRepository(PostgresConnectionFactory db,ITokenHasher hasher):ISurveyLinkRepository{
 const string dto="id,survey_id SurveyId,organization_id OrganizationId,public_url PublicUrl,status,expires_at ExpiresAt,revoked_at RevokedAt,created_at CreatedAt,updated_at UpdatedAt";
 public async Task<IReadOnlyList<SurveyLinkDto>> ListAsync(Guid surveyId,CurrentUser u){using var c=db.Create(); var s=await c.QuerySingleAsync<Guid>("select organization_id from valorapesquisa.surveys where id=@surveyId",new{surveyId}); Scope.DemandOrg(u,s); return (await c.QueryAsync<SurveyLinkDto>($"select {dto} from valorapesquisa.survey_links where survey_id=@surveyId order by created_at desc",new{surveyId})).ToList();}
 public async Task<CreatedSurveyLinkDto> CreateAsync(SurveyLink l,string token){using var c=db.Create(); await c.ExecuteAsync("insert into valorapesquisa.survey_links(id,survey_id,organization_id,token_hash,public_url,status,expires_at,created_at) values(@Id,@SurveyId,@OrganizationId,@TokenHash,@PublicUrl,@Status,@ExpiresAt,@CreatedAt)",l); return new(l.Id,l.SurveyId,l.OrganizationId,l.PublicUrl,token,l.Status,l.ExpiresAt);}
 public async Task<SurveyLink?> FindValidAsync(Guid surveyId,string slug,string token){using var c=db.Create(); var hash=hasher.Hash(token); return await c.QuerySingleOrDefaultAsync<SurveyLink>("select l.* from valorapesquisa.survey_links l join valorapesquisa.organizations o on o.id=l.organization_id join valorapesquisa.surveys s on s.id=l.survey_id where l.survey_id=@surveyId and o.slug=@slug and l.token_hash=@hash and l.status='active' and l.revoked_at is null and (l.expires_at is null or l.expires_at>now()) and s.status='published' and o.is_deleted=false",new{surveyId,slug,hash});}
 public async Task SetStatusAsync(Guid id,string status,CurrentUser u){using var c=db.Create(); var org=await c.QuerySingleAsync<Guid>("select organization_id from valorapesquisa.survey_links where id=@id",new{id}); Scope.DemandOrg(u,org); await c.ExecuteAsync("update valorapesquisa.survey_links set status=@status,revoked_at=case when @status in ('revoked','inactive') then now() else revoked_at end,updated_at=now() where id=@id",new{id,status});}}
public sealed class ResponseRepository(PostgresConnectionFactory db,ITokenHasher hasher):IResponseRepository{
 public async Task<SubmitSurveyResponseResult> CreateAsync(SurveyResponse r,ResultScore score,string token){using var c=db.Create(); c.Open(); using var tx=c.BeginTransaction(); await c.ExecuteAsync("insert into valorapesquisa.responses(id,organization_id,survey_id,form_id,participant_name,participant_email,status,completed_at,result_token_hash,created_at) values(@Id,@OrganizationId,@SurveyId,@FormId,@ParticipantName,@ParticipantEmail,@Status,@CompletedAt,@ResultTokenHash,@CreatedAt)",r,tx); foreach(var a in r.Answers) await c.ExecuteAsync("insert into valorapesquisa.response_answers(id,response_id,question_id,answer_value,answer_text) values(@Id,@ResponseId,@QuestionId,@AnswerValue,@AnswerText)",a,tx); await c.ExecuteAsync("insert into valorapesquisa.result_scores(id,response_id,total_score,max_score,percentage,normalized5,level,result_json,created_at) values(@Id,@ResponseId,@TotalScore,@MaxScore,@Percentage,@Normalized5,@Level,cast(@ResultJson as jsonb),@CreatedAt)",score,tx); tx.Commit(); return new(r.Id,token,score.TotalScore,score.Percentage,score.Normalized5,score.Level);}
 public async Task<PublicResultDto?> GetResultAsync(Guid id,string token){using var c=db.Create(); var hash=hasher.Hash(token); return await c.QuerySingleOrDefaultAsync<PublicResultDto>("select r.id ResponseId,r.survey_id SurveyId,rs.total_score TotalScore,rs.max_score MaxScore,rs.percentage,rs.normalized5,rs.level,rs.result_json::text ResultJson,rs.created_at CreatedAt from valorapesquisa.responses r join valorapesquisa.result_scores rs on rs.response_id=r.id where r.id=@id and r.result_token_hash=@hash",new{id,hash});}
 public async Task<IReadOnlyList<ResponseDto>> ListAsync(CurrentUser u){using var c=db.Create();return(await c.QueryAsync<ResponseDto>(u.IsAdminValora?"select id,organization_id OrganizationId,survey_id SurveyId,form_id FormId,participant_name ParticipantName,participant_email ParticipantEmail,status,completed_at CompletedAt,created_at CreatedAt from valorapesquisa.responses order by created_at desc":"select id,organization_id OrganizationId,survey_id SurveyId,form_id FormId,participant_name ParticipantName,participant_email ParticipantEmail,status,completed_at CompletedAt,created_at CreatedAt from valorapesquisa.responses where organization_id=@OrganizationId order by created_at desc",u)).ToList();}
 public async Task<SurveyResponse?> GetDetailAsync(Guid id,CurrentUser u){using var c=db.Create(); var r=await c.QuerySingleOrDefaultAsync<SurveyResponse>("select * from valorapesquisa.responses where id=@id",new{id}); if(r!=null)Scope.DemandOrg(u,r.OrganizationId); return r;}}
