using System.Text.Json;
using Dapper;
using ValoraPesquisa.Application.Contracts;
using ValoraPesquisa.Application.DTOs;
using ValoraPesquisa.Domain.Entities;
using ValoraPesquisa.Infrastructure.Database;

namespace ValoraPesquisa.Infrastructure.Repositories;
public sealed class FormRepository(PostgresConnectionFactory db):IFormRepository{
 public async Task<IReadOnlyList<FormDto>> ListAsync(CurrentUser u){ using var c=db.Create(); return (await c.QueryAsync<FormDto>(u.IsAdminValora?"select id,organization_id OrganizationId,title,description,status,created_at CreatedAt,updated_at UpdatedAt from valorapesquisa.forms where is_deleted=false order by created_at desc":"select id,organization_id OrganizationId,title,description,status,created_at CreatedAt,updated_at UpdatedAt from valorapesquisa.forms where organization_id=@OrganizationId and is_deleted=false order by created_at desc",u)).ToList(); }
 public async Task<FormDto?> GetAsync(Guid id,CurrentUser u){ using var c=db.Create(); var f=await c.QuerySingleOrDefaultAsync<Form>("select * from valorapesquisa.forms where id=@id and is_deleted=false",new{id}); if(f==null)return null; Scope.DemandOrg(u,f.OrganizationId); return await Load(f.Id); }
 public async Task<FormDto?> GetPublicAsync(Guid id,Guid org){ using var c=db.Create(); var f=await c.QuerySingleOrDefaultAsync<Form>("select * from valorapesquisa.forms where id=@id and organization_id=@org and is_deleted=false",new{id,org}); return f==null?null:await Load(id); }
 async Task<FormDto?> Load(Guid id){ using var c=db.Create(); var form=await c.QuerySingleOrDefaultAsync<FormDto>("select id,organization_id OrganizationId,title,description,status,created_at CreatedAt,updated_at UpdatedAt from valorapesquisa.forms where id=@id",new{id}); if(form==null)return null; var qs=(await c.QueryAsync<QuestionDto>("select id,text,type,position,required,weight,max_score MaxScore from valorapesquisa.questions where form_id=@id order by position",new{id})).ToList(); var all=(await c.QueryAsync<QuestionOptionDto>("select id,question_id QuestionId,text,score,position from valorapesquisa.question_options where question_id=any(@ids) order by position",new{ids=qs.Select(q=>q.Id).ToArray()})).ToList(); return form with { Questions=qs.Select(q=>q with {Options=all.Where(o=>o.QuestionId==q.Id).ToList()}).ToList()}; }
 public async Task<FormDto> SaveAsync(Form f,CurrentUser u){ Scope.DemandOrg(u,f.OrganizationId); if(string.IsNullOrWhiteSpace(f.Title))throw new ArgumentException("Título obrigatório."); if(f.Questions.Count==0)throw new ArgumentException("Informe ao menos uma pergunta."); using var c=db.Create(); c.Open(); using var tx=c.BeginTransaction(); await c.ExecuteAsync("insert into valorapesquisa.forms(id,organization_id,title,description,status,created_at,is_deleted) values(@Id,@OrganizationId,@Title,@Description,@Status,@CreatedAt,false) on conflict(id) do update set title=@Title,description=@Description,status=@Status,updated_at=now()",f,tx); await c.ExecuteAsync("delete from valorapesquisa.question_options where question_id in (select id from valorapesquisa.questions where form_id=@Id); delete from valorapesquisa.questions where form_id=@Id",f,tx); foreach(var q in f.Questions){ await c.ExecuteAsync("insert into valorapesquisa.questions(id,form_id,text,type,position,required,weight,max_score) values(@Id,@FormId,@Text,@Type,@Position,@Required,@Weight,@MaxScore)",q,tx); foreach(var o in q.Options) await c.ExecuteAsync("insert into valorapesquisa.question_options(id,question_id,text,score,position) values(@Id,@QuestionId,@Text,@Score,@Position)",o,tx);} tx.Commit(); return (await Load(f.Id))!; }
 public async Task<bool> HasQuestionsAsync(Guid formId,Guid org){ using var c=db.Create(); return await c.ExecuteScalarAsync<bool>("select exists(select 1 from valorapesquisa.forms f join valorapesquisa.questions q on q.form_id=f.id where f.id=@formId and f.organization_id=@org and f.is_deleted=false)",new{formId,org}); }}
