using System.Text.Json;
using Dapper;
using ValoraPesquisa.Application.Contracts;
using ValoraPesquisa.Application.DTOs;
using ValoraPesquisa.Domain.Entities;
using ValoraPesquisa.Infrastructure.Database;

namespace ValoraPesquisa.Infrastructure.Repositories;
public sealed class ResponseRepository(PostgresConnectionFactory db,ITokenHasher hasher):IResponseRepository{
 public async Task<SubmitSurveyResponseResult> CreateAsync(SurveyResponse r,ResultScore score,string token){using var c=db.Create(); c.Open(); using var tx=c.BeginTransaction(); await c.ExecuteAsync("insert into valorapesquisa.responses(id,organization_id,survey_id,form_id,participant_name,participant_email,status,completed_at,result_token_hash,created_at) values(@Id,@OrganizationId,@SurveyId,@FormId,@ParticipantName,@ParticipantEmail,@Status,@CompletedAt,@ResultTokenHash,@CreatedAt)",r,tx); foreach(var a in r.Answers) await c.ExecuteAsync("insert into valorapesquisa.response_answers(id,response_id,question_id,answer_value,answer_text) values(@Id,@ResponseId,@QuestionId,@AnswerValue,@AnswerText)",a,tx); await c.ExecuteAsync("insert into valorapesquisa.result_scores(id,response_id,total_score,max_score,percentage,normalized5,level,result_json,created_at) values(@Id,@ResponseId,@TotalScore,@MaxScore,@Percentage,@Normalized5,@Level,cast(@ResultJson as jsonb),@CreatedAt)",score,tx); tx.Commit(); return new(r.Id,token,score.TotalScore,score.Percentage,score.Normalized5,score.Level);}
 public async Task<PublicResultDto?> GetResultAsync(Guid id,string token){using var c=db.Create(); var hash=hasher.Hash(token); return await c.QuerySingleOrDefaultAsync<PublicResultDto>("select r.id ResponseId,r.survey_id SurveyId,rs.total_score TotalScore,rs.max_score MaxScore,rs.percentage,rs.normalized5,rs.level,rs.result_json::text ResultJson,rs.created_at CreatedAt from valorapesquisa.responses r join valorapesquisa.result_scores rs on rs.response_id=r.id where r.id=@id and r.result_token_hash=@hash",new{id,hash});}
 public async Task<IReadOnlyList<ResponseDto>> ListAsync(CurrentUser u){using var c=db.Create();return(await c.QueryAsync<ResponseDto>(u.IsAdminValora?"select id,organization_id OrganizationId,survey_id SurveyId,form_id FormId,participant_name ParticipantName,participant_email ParticipantEmail,status,completed_at CompletedAt,created_at CreatedAt from valorapesquisa.responses order by created_at desc":"select id,organization_id OrganizationId,survey_id SurveyId,form_id FormId,participant_name ParticipantName,participant_email ParticipantEmail,status,completed_at CompletedAt,created_at CreatedAt from valorapesquisa.responses where organization_id=@OrganizationId order by created_at desc",u)).ToList();}
 public async Task<SurveyResponse?> GetDetailAsync(Guid id,CurrentUser u){using var c=db.Create(); var r=await c.QuerySingleOrDefaultAsync<SurveyResponse>("select * from valorapesquisa.responses where id=@id",new{id}); if(r!=null)Scope.DemandOrg(u,r.OrganizationId); return r;}}
