(function(root){
'use strict';
const forbidden=['SMTP_PASS','SMTP_PASSWORD','GATEWAY_API_TOKEN','WHATSAPP_ACCESS_TOKEN','FIREBASE_PRIVATE_KEY','serviceAccount','private_key'];
const firebaseRequired=['apiKey','authDomain','projectId','storageBucket','messagingSenderId','appId'];
function hasValue(v){return v!==undefined&&v!==null&&String(v).trim()!=='';}
function validateConfig(cfg,source='config'){const errors=[];function req(k){if(!hasValue(cfg[k]))errors.push(`${source}: ${k} obrigatório`);}['RUNTIME_ENV','APP_PUBLIC_URL','STORAGE_MODE','EMAIL_TRANSPORT','WHATSAPP_TRANSPORT'].forEach(req);if(!cfg.COMMUNICATION_GATEWAY||typeof cfg.COMMUNICATION_GATEWAY!=='object')errors.push(`${source}: COMMUNICATION_GATEWAY obrigatório`);if(!cfg.observability||typeof cfg.observability!=='object')errors.push(`${source}: observability obrigatório`);const env=cfg.RUNTIME_ENV;if(env==='production'){if(cfg.STORAGE_MODE!=='firebase')errors.push('produção: STORAGE_MODE deve ser firebase');if(cfg.FIREBASE_ENABLED!==true)errors.push('produção: FIREBASE_ENABLED deve ser true');firebaseRequired.forEach(k=>{if(!hasValue(cfg.FIREBASE_CONFIG?.[k]))errors.push(`produção: FIREBASE_CONFIG.${k} obrigatório`);});if(cfg.LOCAL_API_ENABLED!==false)errors.push('produção: LOCAL_API_ENABLED deve ser false');if(!['external-api','disabled'].includes(cfg.EMAIL_TRANSPORT))errors.push('produção: EMAIL_TRANSPORT inválido');if(cfg.EMAIL_TRANSPORT==='external-api'&&!hasValue(cfg.EXTERNAL_API_BASE_URL))errors.push('produção: EXTERNAL_API_BASE_URL obrigatório');if(cfg.COMMUNICATION_GATEWAY?.enabled!==true)errors.push('produção: gateway deve estar enabled');if(cfg.observability?.consoleEnabled!==false)errors.push('produção: consoleEnabled deve ser false');if(cfg.observability?.legacyTraceEnabled!==false)errors.push('produção: legacyTraceEnabled deve ser false');}
if(env==='local-firebase'){if(cfg.STORAGE_MODE!=='firebase')errors.push('local-firebase: STORAGE_MODE deve ser firebase');firebaseRequired.forEach(k=>{if(!hasValue(cfg.FIREBASE_CONFIG?.[k]))errors.push(`local-firebase: FIREBASE_CONFIG.${k} obrigatório`);});}
return {ok:errors.length===0,errors,forbidden};}
if(typeof module!=='undefined')module.exports={validateConfig,forbidden,firebaseRequired};else root.ValoraConfigSchema={validateConfig,forbidden,firebaseRequired};
})(typeof window!=='undefined'?window:globalThis);
