namespace Valora.Application.Knowledge;

public sealed class KnowledgeCategoryService(IKnowledgeRepository repository) { public Task<IReadOnlyList<KnowledgeCategory>> ListAsync(Guid o,CancellationToken ct)=>repository.CategoriesAsync(o,ct); }
public sealed class KnowledgeArticleService(IKnowledgeRepository repository) {
 public Task<IReadOnlyList<KnowledgeArticle>> ListAsync(Guid o,string? q,string? s,Guid? c,CancellationToken ct)=>repository.ArticlesAsync(o,q,s,c,ct);
 public Task<KnowledgeArticle> CreateAsync(Guid o,CreateArticleRequest r,Guid actor,string correlation,CancellationToken ct)=>repository.CreateArticleAsync(o,r,actor,correlation,ct);
 public async Task<KnowledgeArticle> SubmitReviewAsync(Guid o,Guid id,Guid actor,string correlation,CancellationToken ct){var a=await Required(o,id,ct);if(a.Status!=KnowledgeStatuses.Draft)throw new InvalidOperationException("Somente rascunhos podem ser enviados para revisão.");return await repository.TransitionArticleAsync(o,id,KnowledgeStatuses.Review,actor,correlation,ct);}
 public async Task<KnowledgeArticle> PublishAsync(Guid o,Guid id,Guid actor,string correlation,CancellationToken ct){var a=await Required(o,id,ct);if(a.CategoryId==Guid.Empty)throw new InvalidOperationException("Escolha uma categoria antes de publicar.");if(a.Status!=KnowledgeStatuses.Review)throw new InvalidOperationException(a.AiAssisted?"Conteúdo apoiado por IA exige revisão humana antes da publicação.":"Envie o artigo para revisão antes de publicar.");return await repository.TransitionArticleAsync(o,id,KnowledgeStatuses.Published,actor,correlation,ct);}
 public async Task<KnowledgeArticle> ArchiveAsync(Guid o,Guid id,Guid actor,string correlation,CancellationToken ct){await Required(o,id,ct);return await repository.TransitionArticleAsync(o,id,KnowledgeStatuses.Archived,actor,correlation,ct);}
 private async Task<KnowledgeArticle> Required(Guid o,Guid id,CancellationToken ct)=>await repository.ArticleAsync(o,id,ct)??throw new KeyNotFoundException("Artigo não encontrado nesta organização.");
}
public sealed class KnowledgeArticleVersionService(IKnowledgeRepository r){public Task<IReadOnlyList<KnowledgeArticleVersion>>ListAsync(Guid o,Guid a,CancellationToken ct)=>r.VersionsAsync(o,a,ct);}
public sealed class KnowledgeReviewService(KnowledgeArticleService articles){public Task<KnowledgeArticle>SubmitAsync(Guid o,Guid a,Guid u,string c,CancellationToken ct)=>articles.SubmitReviewAsync(o,a,u,c,ct);}
public sealed class OrganizationalLessonService(IKnowledgeRepository r){public Task<IReadOnlyList<OrganizationalLesson>>ListAsync(Guid o,CancellationToken ct)=>r.LessonsAsync(o,ct);public Task<OrganizationalLesson>CreateAsync(Guid o,CreateLessonRequest x,Guid a,string c,CancellationToken ct){if(x.Critical&&string.IsNullOrWhiteSpace(x.Evidence))throw new ArgumentException("Uma lição crítica exige evidência ou justificativa humana.");return r.CreateLessonAsync(o,x,a,c,ct);}}
public sealed class PlaybookService(IKnowledgeRepository r){public Task<IReadOnlyList<Playbook>>ListAsync(Guid o,CancellationToken ct)=>r.PlaybooksAsync(o,ct);public Task<Playbook>CreateAsync(Guid o,CreatePlaybookRequest x,Guid a,string c,CancellationToken ct){if(x.Steps.Count==0)throw new ArgumentException("Inclua ao menos um passo no playbook.");if(x.Steps.Select(s=>s.Order).Distinct().Count()!=x.Steps.Count)throw new ArgumentException("A ordem dos passos não pode se repetir.");return r.CreatePlaybookAsync(o,x,a,c,ct);}}
public sealed class PlaybookStepService(IKnowledgeRepository repository);
public sealed class LearningPathService(IKnowledgeRepository r){public Task<IReadOnlyList<LearningPath>>ListAsync(Guid o,CancellationToken ct)=>r.LearningPathsAsync(o,ct);public Task<LearningPath>CreateAsync(Guid o,CreateLearningPathRequest x,Guid a,string c,CancellationToken ct){if(x.ArticleIds.Count==0)throw new ArgumentException("A trilha precisa ter ao menos um item.");return r.CreateLearningPathAsync(o,x,a,c,ct);}}
public sealed class LearningProgressService(IKnowledgeRepository repository);
public sealed class CognitiveDictionaryService(IKnowledgeRepository r){public Task<IReadOnlyList<CognitiveTerm>>ListAsync(Guid o,CancellationToken ct)=>r.TermsAsync(o,ct);public Task<CognitiveTerm>CreateAsync(Guid o,CreateCognitiveTermRequest x,Guid a,string c,CancellationToken ct)=>r.CreateTermAsync(o,x,a,c,ct);}
public sealed class KnowledgeSearchService(IKnowledgeRepository r){public Task<IReadOnlyList<KnowledgeArticle>>SearchAsync(Guid o,string query,CancellationToken ct)=>r.ArticlesAsync(o,query,KnowledgeStatuses.Published,null,ct);}
public sealed class KnowledgeOverviewService(IKnowledgeRepository r){public Task<KnowledgeSummary>GetAsync(Guid o,CancellationToken ct)=>r.SummaryAsync(o,ct);}
