namespace Valora.Application.ActionCenter;

public sealed class ActionPlanService(IActionPlanRepository repository) { public Task<ActionDashboardDto> Dashboard(Guid o, CancellationToken c) => repository.Dashboard(o, c); public Task<IReadOnlyList<ActionPlanDto>> List(Guid o, CancellationToken c) => repository.List(o, c); public Task<Valora.Application.Workspace.PageResult<ActionOptionDto>> Options(Guid o, Guid u, bool wide, Valora.Application.Workspace.OptionQuery q, CancellationToken c) => repository.Options(o,u,wide,q,c); public Task<ActionPlanDto?> Get(Guid o, Guid id, CancellationToken c) => repository.Get(o, id, c); public Task<Guid> Create(Guid o, Guid u, CreateActionPlanRequest r, CancellationToken c) { Validate(r.Title, r.EvidenceSummary, r.Priority); return repository.Create(o, u, r, c); } internal static void Validate(string? title, string? evidence, string? priority) { if (string.IsNullOrWhiteSpace(title)) throw new ArgumentException("Título é obrigatório."); if (string.IsNullOrWhiteSpace(evidence)) throw new ArgumentException("A ação precisa indicar sua base de evidência."); if (string.IsNullOrWhiteSpace(priority) || !ActionStatuses.Priorities.Contains(priority)) throw new ArgumentException("Prioridade inválida."); } }
public sealed class ActionItemService(IActionItemRepository repository) { public Task<IReadOnlyList<ActionItemDto>> List(Guid o, Guid? p, CancellationToken c) => repository.List(o, p, c); public Task<Valora.Application.Workspace.PageResult<ActionOptionDto>> Options(Guid o, Guid u, bool wide, Valora.Application.Workspace.OptionQuery q, CancellationToken c) => repository.Options(o,u,wide,q,c); public Task<ActionItemDto?> Get(Guid o, Guid id, CancellationToken c) => repository.Get(o, id, c); public Task<ActionItemDetailsDto?> Details(Guid o, Guid id, int page, CancellationToken c) => repository.Details(o,id,page,c); public Task<Guid> Create(Guid o, Guid u, CreateActionItemRequest r, CancellationToken c) { ActionPlanService.Validate(r.Title, r.EvidenceSummary, r.Priority); return repository.Create(o, u, r, c); } }
public sealed class PriorityActionService(IPriorityActionRepository repository) {
    public Task<IReadOnlyList<PriorityActionDto>> List(Guid o, Guid priority, Guid u, bool wide, CancellationToken c) => repository.List(o, priority, u, wide, c);
    public Task<Guid> Link(Guid o, Guid u, Guid priority, LinkPriorityActionRequest r, bool wide, CancellationToken c) { if (r.ActionId==Guid.Empty || string.IsNullOrWhiteSpace(r.CommandId)) throw new ArgumentException("Informe a atividade e a chave da operação."); return repository.Link(o,u,priority,r,wide,c); }
    public Task<Guid> Create(Guid o, Guid u, Guid priority, CreatePriorityActionRequest r, bool wide, CancellationToken c) { ActionPlanService.Validate(r.Title,r.EvidenceSummary,r.Priority); if(string.IsNullOrWhiteSpace(r.ExpectedOutcome)) throw new ArgumentException("Informe o resultado esperado."); if(r.CreatePlan==r.PlanId.HasValue) throw new ArgumentException("Selecione um plano existente ou crie um novo."); if(r.CreatePlan&&string.IsNullOrWhiteSpace(r.PlanTitle)) throw new ArgumentException("Informe o nome do novo plano."); if(string.IsNullOrWhiteSpace(r.CommandId)) throw new ArgumentException("Informe a chave da operação."); return repository.Create(o,u,priority,r,wide,c); }
}
public sealed class ActionProgressService(IActionItemRepository repository) { public Task Update(Guid o, Guid u, Guid id, ProgressActionRequest r, CancellationToken c) { if (r.ProgressPercent is < 0 or > 99) throw new ArgumentOutOfRangeException(nameof(r.ProgressPercent), "O acompanhamento aceita de 0 a 99%. Use Concluir para registrar 100%."); return repository.UpdateProgress(o,u,id,r,c); } public Task Block(Guid o, Guid u, Guid id, TransitionActionRequest r, CancellationToken c) { if (string.IsNullOrWhiteSpace(r.Reason)) throw new ArgumentException("Informe o bloqueio."); return repository.Block(o,u,id,r,c); } public Task Complete(Guid o, Guid u, Guid id, CompleteActionRequest r, CancellationToken c) { if (string.IsNullOrWhiteSpace(r.Result) || r.Result.Trim().Length < 10) throw new ArgumentException("Descreva o resultado alcançado (mínimo de 10 caracteres)."); if (string.IsNullOrWhiteSpace(r.Evidence)) throw new ArgumentException("Evidência de conclusão é obrigatória."); return repository.Complete(o,u,id,r,c); } }
public sealed class ActionRecommendationService(IRecommendationRepository repository) { public Task<IReadOnlyList<ActionRecommendationDto>> List(Guid o, CancellationToken c) => repository.List(o, c); public Task<Guid> Suggest(Guid o, Guid u, ActionRecommendationDto r, CancellationToken c) { if (string.IsNullOrWhiteSpace(r.Evidence) || string.IsNullOrWhiteSpace(r.Limitation)) throw new ArgumentException("Sugestões de IA exigem evidência e limitação."); return repository.Enqueue(o, u, r with { Status = "proposed" }, c); } }
public sealed class GenerateActionPlanFromDiagnosticUseCase(ActionPlanService service) { public Task<Guid> Execute(Guid o, Guid u, CreateActionPlanRequest r, CancellationToken c) => service.Create(o, u, r with { OriginType = "diagnostic" }, c); }
public sealed class CreateActionFromInsightUseCase(ActionItemService s) { public Task<Guid> Execute(Guid o, Guid u, CreateActionItemRequest r, CancellationToken c) => s.Create(o, u, r with { OriginType = "ai_insight" }, c); }
public sealed class CreateActionFromAlertUseCase(ActionItemService s) { public Task<Guid> Execute(Guid o, Guid u, CreateActionItemRequest r, CancellationToken c) => s.Create(o, u, r with { OriginType = "alert" }, c); }
public sealed class CreateActionFromDecisionUseCase(ActionItemService s) { public Task<Guid> Execute(Guid o, Guid u, CreateActionItemRequest r, CancellationToken c) => s.Create(o, u, r with { OriginType = "decision" }, c); }
public sealed class UpdateActionProgressUseCase(ActionProgressService s) { public Task Execute(Guid o, Guid u, Guid id, ProgressActionRequest r, CancellationToken c) => s.Update(o,u,id,r,c); }
public sealed class CompleteActionUseCase(ActionProgressService s) { public Task Execute(Guid o, Guid u, Guid id, CompleteActionRequest r, CancellationToken c) => s.Complete(o,u,id,r,c); }
public sealed class BlockActionUseCase(ActionProgressService s) { public Task Execute(Guid o, Guid u, Guid id, TransitionActionRequest r, CancellationToken c) => s.Block(o,u,id,r,c); }
