namespace Valora.Application.ActionCenter;
public sealed class ActionPlanService(IActionPlanRepository repository){public Task<ActionDashboardDto> Dashboard(Guid o,CancellationToken c)=>repository.Dashboard(o,c);public Task<IReadOnlyList<ActionPlanDto>> List(Guid o,CancellationToken c)=>repository.List(o,c);public Task<ActionPlanDto?> Get(Guid o,Guid id,CancellationToken c)=>repository.Get(o,id,c);public Task<Guid>Create(Guid o,Guid u,CreateActionPlanRequest r,CancellationToken c){Validate(r.Title,r.EvidenceSummary,r.Priority);return repository.Create(o,u,r,c);}internal static void Validate(string title,string evidence,string priority){if(string.IsNullOrWhiteSpace(title))throw new ArgumentException("Título é obrigatório.");if(string.IsNullOrWhiteSpace(evidence))throw new ArgumentException("A ação precisa indicar sua base de evidência.");if(!ActionStatuses.Priorities.Contains(priority))throw new ArgumentException("Prioridade inválida.");}}
public sealed class ActionItemService(IActionItemRepository repository){public Task<IReadOnlyList<ActionItemDto>>List(Guid o,Guid? p,CancellationToken c)=>repository.List(o,p,c);public Task<ActionItemDto?>Get(Guid o,Guid id,CancellationToken c)=>repository.Get(o,id,c);public Task<Guid>Create(Guid o,Guid u,CreateActionItemRequest r,CancellationToken c){ActionPlanService.Validate(r.Title,r.EvidenceSummary,r.Priority);return repository.Create(o,u,r,c);}}
public sealed class ActionProgressService(IActionItemRepository repository){public Task Update(Guid o,Guid u,Guid id,int progress,string? note,CancellationToken c){if(progress is <0 or >100)throw new ArgumentOutOfRangeException(nameof(progress));return repository.UpdateProgress(o,u,id,progress,note,c);}public Task Block(Guid o,Guid u,Guid id,string reason,CancellationToken c){if(string.IsNullOrWhiteSpace(reason))throw new ArgumentException("Informe o bloqueio.");return repository.Block(o,u,id,reason,c);}public Task Complete(Guid o,Guid u,Guid id,string result,string evidence,CancellationToken c){if(result.Trim().Length<10)throw new ArgumentException("Descreva o resultado alcançado (mínimo de 10 caracteres).");if(string.IsNullOrWhiteSpace(evidence))throw new ArgumentException("Evidência de conclusão é obrigatória.");return repository.Complete(o,u,id,result,evidence,c);}}
public sealed class ActionRecommendationService(IRecommendationRepository repository){public Task<IReadOnlyList<ActionRecommendationDto>>List(Guid o,CancellationToken c)=>repository.List(o,c);public Task<Guid>Suggest(Guid o,Guid u,ActionRecommendationDto r,CancellationToken c){if(string.IsNullOrWhiteSpace(r.Evidence)||string.IsNullOrWhiteSpace(r.Limitation))throw new ArgumentException("Sugestões de IA exigem evidência e limitação.");return repository.Enqueue(o,u,r with{Status="proposed"},c);}}
public sealed class GenerateActionPlanFromDiagnosticUseCase(ActionPlanService service){public Task<Guid>Execute(Guid o,Guid u,CreateActionPlanRequest r,CancellationToken c)=>service.Create(o,u,r with{OriginType="diagnostic"},c);}
public sealed class CreateActionFromInsightUseCase(ActionItemService s){public Task<Guid>Execute(Guid o,Guid u,CreateActionItemRequest r,CancellationToken c)=>s.Create(o,u,r with{OriginType="ai_insight"},c);}
public sealed class CreateActionFromAlertUseCase(ActionItemService s){public Task<Guid>Execute(Guid o,Guid u,CreateActionItemRequest r,CancellationToken c)=>s.Create(o,u,r with{OriginType="alert"},c);}
public sealed class CreateActionFromDecisionUseCase(ActionItemService s){public Task<Guid>Execute(Guid o,Guid u,CreateActionItemRequest r,CancellationToken c)=>s.Create(o,u,r with{OriginType="decision"},c);}
public sealed class UpdateActionProgressUseCase(ActionProgressService s){public Task Execute(Guid o,Guid u,Guid id,int p,string? n,CancellationToken c)=>s.Update(o,u,id,p,n,c);}public sealed class CompleteActionUseCase(ActionProgressService s){public Task Execute(Guid o,Guid u,Guid id,string r,string e,CancellationToken c)=>s.Complete(o,u,id,r,e,c);}public sealed class BlockActionUseCase(ActionProgressService s){public Task Execute(Guid o,Guid u,Guid id,string r,CancellationToken c)=>s.Block(o,u,id,r,c);}
