namespace Valora.Application.Evolution;
public sealed record EvolutionCycleDto(Guid Id,string Title,string Summary,string Status,decimal? BaselineScore,decimal? CurrentScore,decimal? TargetScore,string? BaselineLevel,string? CurrentLevel,string Trend,DateTime PeriodStart,DateTime? PeriodEnd,string EvidenceSummary,string? LearningSummary,DateTime CreatedAt);
public sealed record EvolutionSnapshotDto(Guid Id,Guid EvolutionCycleId,string SnapshotType,decimal? Score,decimal? PreviousScore,decimal? Delta,string? Level,string Trend,int CompletedActions,int DelayedActions,int OpenAlerts,string EvidenceSummary,string Interpretation,string Recommendation,DateTime CalculatedAt);
public sealed record OpenEvolutionCycleRequest(Guid? DiagnosticId,Guid? ResultId,Guid? GovernanceCycleId,string Title,string Summary,decimal? BaselineScore,decimal? TargetScore,string? BaselineLevel,DateTime PeriodStart,DateTime? PeriodEnd,string EvidenceSummary);
public interface IEvolutionRepository{Task<IReadOnlyList<EvolutionCycleDto>>List(Guid o,CancellationToken c);Task<EvolutionCycleDto?>Get(Guid o,Guid id,CancellationToken c);Task<IReadOnlyList<EvolutionSnapshotDto>>Snapshots(Guid o,Guid cycle,CancellationToken c);Task<Guid>Open(Guid o,Guid u,OpenEvolutionCycleRequest r,CancellationToken c);Task<Guid>Snapshot(Guid o,Guid u,Guid cycle,string evidence,string interpretation,string recommendation,CancellationToken c);Task Close(Guid o,Guid u,Guid cycle,string learning,CancellationToken c);}
public interface IEvolutionCycleService{Task<IReadOnlyList<EvolutionCycleDto>>List(Guid o,CancellationToken c);Task<EvolutionCycleDto?>Get(Guid o,Guid id,CancellationToken c);Task<Guid>Open(Guid o,Guid u,OpenEvolutionCycleRequest x,CancellationToken c);Task Close(Guid o,Guid u,Guid id,string learning,CancellationToken c);}
public sealed class EvolutionCycleService(IEvolutionRepository r):IEvolutionCycleService{public Task<IReadOnlyList<EvolutionCycleDto>>List(Guid o,CancellationToken c)=>r.List(o,c);public Task<EvolutionCycleDto?>Get(Guid o,Guid id,CancellationToken c)=>r.Get(o,id,c);public Task<Guid>Open(Guid o,Guid u,OpenEvolutionCycleRequest x,CancellationToken c){if(string.IsNullOrWhiteSpace(x.EvidenceSummary))throw new ArgumentException("Baseline exige evidência.");return r.Open(o,u,x,c);}public Task Close(Guid o,Guid u,Guid id,string learning,CancellationToken c)=>r.Close(o,u,id,learning,c);}
public sealed class EvolutionSnapshotService(IEvolutionRepository r){public Task<IReadOnlyList<EvolutionSnapshotDto>>List(Guid o,Guid id,CancellationToken c)=>r.Snapshots(o,id,c);public Task<Guid>Generate(Guid o,Guid u,Guid id,string evidence,string interpretation,string recommendation,CancellationToken c){if(string.IsNullOrWhiteSpace(evidence))throw new ArgumentException("Snapshot exige evidência verificável.");return r.Snapshot(o,u,id,evidence,interpretation,recommendation,c);}}
public sealed class EvolutionMeasurementService{public static string Trend(decimal? previous,decimal? current,int evidenceCount){if(evidenceCount<2||previous is null||current is null)return "insufficient_sample";var d=current-previous;return d>=5?"consistent_evolution":d>0?"gradual_evolution":d==0?"stability":d<=-3?"regression":"oscillation";}}
public sealed class OpenEvolutionCycleUseCase(EvolutionCycleService s){public Task<Guid>Execute(Guid o,Guid u,OpenEvolutionCycleRequest r,CancellationToken c)=>s.Open(o,u,r,c);}public sealed class CloseEvolutionCycleUseCase(EvolutionCycleService s){public Task Execute(Guid o,Guid u,Guid id,string l,CancellationToken c)=>s.Close(o,u,id,l,c);}public sealed class GenerateEvolutionSnapshotUseCase(EvolutionSnapshotService s){public Task<Guid>Execute(Guid o,Guid u,Guid id,string e,string i,string r,CancellationToken c)=>s.Generate(o,u,id,e,i,r,c);}
