namespace Valora.Application.Evolution;

public sealed record EvolutionCycleDto(Guid Id, string Title, string Summary, string Status, decimal? BaselineScore, decimal? CurrentScore, decimal? TargetScore, string? BaselineLevel, string? CurrentLevel, string Trend, DateTime PeriodStart, DateTime? PeriodEnd, string EvidenceSummary, string? LearningSummary, DateTime CreatedAt);
public sealed record EvolutionSnapshotDto(Guid Id, Guid EvolutionCycleId, string SnapshotType, decimal? Score, decimal? PreviousScore, decimal? Delta, string? Level, string Trend, int CompletedActions, int DelayedActions, int OpenAlerts, string EvidenceSummary, string Interpretation, string Recommendation, DateTime CalculatedAt);
public sealed record OpenEvolutionCycleRequest(Guid? DiagnosticId, Guid? ResultId, Guid? GovernanceCycleId, string Title, string Summary, decimal? BaselineScore, decimal? TargetScore, string? BaselineLevel, DateTime PeriodStart, DateTime? PeriodEnd, string EvidenceSummary);
public interface IEvolutionRepository { Task<IReadOnlyList<EvolutionCycleDto>> List(Guid o, CancellationToken c); Task<EvolutionCycleDto?> Get(Guid o, Guid id, CancellationToken c); Task<IReadOnlyList<EvolutionSnapshotDto>> Snapshots(Guid o, Guid cycle, CancellationToken c); Task<Guid> Open(Guid o, Guid u, OpenEvolutionCycleRequest r, CancellationToken c); Task<Guid> Snapshot(Guid o, Guid u, Guid cycle, string evidence, string interpretation, string recommendation, CancellationToken c); Task Close(Guid o, Guid u, Guid cycle, string learning, CancellationToken c); }
public interface IEvolutionCycleService { Task<IReadOnlyList<EvolutionCycleDto>> List(Guid o, CancellationToken c); Task<EvolutionCycleDto?> Get(Guid o, Guid id, CancellationToken c); Task<Guid> Open(Guid o, Guid u, OpenEvolutionCycleRequest x, CancellationToken c); Task Close(Guid o, Guid u, Guid id, string learning, CancellationToken c); }
public sealed class EvolutionCycleService(IEvolutionRepository r) : IEvolutionCycleService { public Task<IReadOnlyList<EvolutionCycleDto>> List(Guid o, CancellationToken c) => r.List(o, c); public Task<EvolutionCycleDto?> Get(Guid o, Guid id, CancellationToken c) => r.Get(o, id, c); public Task<Guid> Open(Guid o, Guid u, OpenEvolutionCycleRequest x, CancellationToken c) { if(o==Guid.Empty||u==Guid.Empty)throw new UnauthorizedAccessException("Organização e autor são obrigatórios.");if(string.IsNullOrWhiteSpace(x.Title)||x.Title.Trim().Length is <3 or >160)throw new ArgumentException("O nome do ciclo deve ter entre 3 e 160 caracteres.");if(string.IsNullOrWhiteSpace(x.Summary)||x.Summary.Trim().Length>1000)throw new ArgumentException("O objetivo do ciclo é obrigatório e aceita até 1.000 caracteres.");if(string.IsNullOrWhiteSpace(x.EvidenceSummary)||x.EvidenceSummary.Trim().Length>2000) throw new ArgumentException("Baseline exige evidência com até 2.000 caracteres.");if(x.PeriodEnd<x.PeriodStart)throw new ArgumentException("A data final deve ser posterior à data inicial.");if(x.BaselineScore is <0 or >100||x.TargetScore is <0 or >100)throw new ArgumentException("Baseline e meta devem estar entre 0 e 100.");return r.Open(o,u,x with{Title=x.Title.Trim(),Summary=x.Summary.Trim(),EvidenceSummary=x.EvidenceSummary.Trim()},c); } public Task Close(Guid o, Guid u, Guid id, string learning, CancellationToken c) => r.Close(o, u, id, learning, c); }
public sealed class EvolutionSnapshotService(IEvolutionRepository r) { public Task<IReadOnlyList<EvolutionSnapshotDto>> List(Guid o, Guid id, CancellationToken c) => r.Snapshots(o, id, c); public Task<Guid> Generate(Guid o, Guid u, Guid id, string evidence, string interpretation, string recommendation, CancellationToken c) { if (o==Guid.Empty||u==Guid.Empty) throw new UnauthorizedAccessException("Organização e autor são obrigatórios."); if (string.IsNullOrWhiteSpace(evidence)||string.IsNullOrWhiteSpace(interpretation)||string.IsNullOrWhiteSpace(recommendation)) throw new ArgumentException("Evidência, interpretação e próximo passo são obrigatórios."); if (evidence.Trim().Length>2000||interpretation.Trim().Length>2000||recommendation.Trim().Length>2000) throw new ArgumentException("Evidência, interpretação e recomendação aceitam até 2.000 caracteres."); return r.Snapshot(o, u, id, evidence.Trim(), interpretation.Trim(), recommendation.Trim(), c); } }
public sealed class EvolutionMeasurementService { public static string Trend(decimal? previous, decimal? current, int evidenceCount) { if (evidenceCount < 2 || previous is null || current is null) return "insufficient_sample"; var d = current - previous; return d >= 5 ? "consistent_evolution" : d > 0 ? "gradual_evolution" : d == 0 ? "stability" : d <= -3 ? "regression" : "oscillation"; } }

public sealed record EvolutionComparisonBasis(string MethodologyVersion, string DimensionSignature, string ScaleSignature, string CalculationCriteria, string PopulationSignature, bool DataAvailable);
public sealed record EvolutionComparisonResult(bool IsComparable, decimal? AbsoluteVariation, string Limitation);
public static class EvolutionComparisonService {
    public static EvolutionComparisonResult Compare(decimal? baseline, EvolutionComparisonBasis baselineBasis, decimal? current, EvolutionComparisonBasis currentBasis) {
        if (!baselineBasis.DataAvailable || !currentBasis.DataAvailable || baseline is null || current is null)
            return new(false, null, "Os resultados não estão disponíveis para comparação.");
        var differences = new List<string>();
        if (!Same(baselineBasis.MethodologyVersion,currentBasis.MethodologyVersion)) differences.Add("versão metodológica");
        if (!Same(baselineBasis.DimensionSignature,currentBasis.DimensionSignature)) differences.Add("dimensões");
        if (!Same(baselineBasis.ScaleSignature,currentBasis.ScaleSignature)) differences.Add("escala");
        if (!Same(baselineBasis.CalculationCriteria,currentBasis.CalculationCriteria)) differences.Add("critérios de cálculo");
        if (!Same(baselineBasis.PopulationSignature,currentBasis.PopulationSignature)) differences.Add("população ou recorte");
        return differences.Count==0
            ? new(true,current-baseline,"Variação absoluta observada; não demonstra causalidade do plano.")
            : new(false,null,$"Comparação indisponível: diferem {string.Join(", ",differences)}. Os resultados devem ser analisados separadamente.");
    }
    private static bool Same(string left,string right)=>!string.IsNullOrWhiteSpace(left)&&string.Equals(left.Trim(),right.Trim(),StringComparison.OrdinalIgnoreCase);
}
public sealed class OpenEvolutionCycleUseCase(EvolutionCycleService s) { public Task<Guid> Execute(Guid o, Guid u, OpenEvolutionCycleRequest r, CancellationToken c) => s.Open(o, u, r, c); }
public sealed class CloseEvolutionCycleUseCase(EvolutionCycleService s) { public Task Execute(Guid o, Guid u, Guid id, string l, CancellationToken c) => s.Close(o, u, id, l, c); }
public sealed class GenerateEvolutionSnapshotUseCase(EvolutionSnapshotService s) { public Task<Guid> Execute(Guid o, Guid u, Guid id, string e, string i, string r, CancellationToken c) => s.Generate(o, u, id, e, i, r, c); }
