using System.Dynamic;
using Valora.Application.Contracts;
using Valora.Application.DTOs;
using Valora.Application.Results;
namespace Valora.Application.Services;
public sealed class PublicSurveyService(ISurveyRepository surveys,IFormRepository forms,IResponseRepository responses,IResultRepository results,ICertificateRepository certificates,ICommunicationRepository communications,IAuditRepository audit,IDbConnectionFactory db,IResultTokenService tokens,ValoraInsightCalculator calculator):IPublicSurveyService{
 public async Task<ValidateSurveyResponse> ValidateAsync(Guid surveyId,ValidateSurveyRequest request){var survey=await surveys.GetActivePublicSurveyAsync(surveyId)??throw new InvalidOperationException("Pesquisa pública não encontrada, expirada ou indisponível."); if(string.IsNullOrWhiteSpace(request.Token)||!await surveys.ValidatePublicTokenAsync(surveyId,request.Token)) throw new UnauthorizedAccessException("Token público inválido."); var form=await forms.GetByIdAsync((Guid)survey.form_id)??throw new InvalidOperationException("Formulário não encontrado."); var dims=await forms.GetDimensionsAsync((Guid)survey.form_id); var qs=await forms.GetQuestionsAsync((Guid)survey.form_id); var opts=await forms.GetQuestionOptionsAsync((Guid)survey.form_id); return new ValidateSurveyResponse(true,MapSurvey(survey),MapForm(form,dims,qs,opts),new PublicCompanyDto((Guid)survey.organization_id,(string?)survey.organization_name,(string?)survey.public_name,(string?)survey.organization_slug),new { text="Ao prosseguir, você autoriza o tratamento dos dados para emissão do diagnóstico, resultado e certificado conforme a LGPD."});}
 public async Task<SubmitSurveyResponseResult> SubmitAsync(Guid surveyId,SubmitSurveyResponseRequest request){if(!request.LgpdConsent) throw new InvalidOperationException("Consentimento LGPD obrigatório."); var validate=await ValidateAsync(surveyId,new ValidateSurveyRequest(request.Token,null)); using var c=db.Create(); c.Open(); using var tx=c.BeginTransaction(); try{var survey=await surveys.GetActivePublicSurveyAsync(surveyId)??throw new InvalidOperationException("Pesquisa indisponível."); var name=Val(request.Participant,"name"); var email=Val(request.Participant,"email"); var phone=Val(request.Participant,"phone"); var resultToken=tokens.CreateToken(); var responseId=await responses.CreateResponseAsync((Guid)survey.organization_id,surveyId,(Guid)survey.form_id,name,email,phone,tokens.HashToken(resultToken),tx); var qs=await forms.GetQuestionsAsync((Guid)survey.form_id); var dims=await forms.GetDimensionsAsync((Guid)survey.form_id); var scored=ScoreAnswers(qs,dims,request.Answers); await responses.AddAnswersAsync(responseId,scored.Select(x=>new {x.QuestionId,x.AnswerText,x.Score,x.MaxScore}),tx); var calc=calculator.Calculate(scored.Select(x=>new AnswerScore(x.DimensionName,x.Score))); var dimDtos=BuildDims(scored); await results.SaveResultAsync((Guid)survey.organization_id,responseId,calc.TotalScore,calc.MaxScore,Math.Round(calc.TotalScore/calc.MaxScore*100,2),calc.Level,"Radar calculado com respostas reais por dimensão.",calc.StrategicTruth,calc.Risk,calc.NextLevel,tx); await results.SaveDimensionScoresAsync((Guid)survey.organization_id,responseId,dimDtos.Select(d=>new {d.DimensionName,d.Score,d.MaxScore,d.Percentage,d.LevelLabel}),tx); var code=$"VAL-{responseId:N}"[..14]; await certificates.CreateMetadataAsync((Guid)survey.organization_id,responseId,code,name,"Valora Pulse™",(string)survey.title,calc.Level,tx); var emailStatus=request.CommunicationConsent&&!string.IsNullOrWhiteSpace(email)?"pending":"cancelled"; if(emailStatus=="pending"){await communications.CreateEmailJobAsync((Guid)survey.organization_id,responseId,email!,emailStatus,tx); await communications.CreateCommunicationAsync((Guid)survey.organization_id,surveyId,responseId,"email","result-ready",emailStatus,Mask(email),tx);} await audit.LogAsync(new AuditEntry((Guid)survey.organization_id,null,"public_survey.submit","response",responseId.ToString(),"Resposta pública real recebida e calculada pela API PostgreSQL."),tx); tx.Commit(); return new SubmitSurveyResponseResult(true,responseId,resultToken,emailStatus,new CertificateMetadataDto(responseId,code,"metadata-ready",name,"Valora Pulse™",(string)survey.title,DateTime.UtcNow),MapResult(calc,dimDtos));}catch{tx.Rollback();throw;}}
 static string? Val(Dictionary<string,object>? d,string k)=>d!=null&&d.TryGetValue(k,out var v)?v?.ToString():null; static string? Mask(string? e)=>string.IsNullOrWhiteSpace(e)?null:e[0]+"***@"+e.Split('@').Last();
 static PublicSurveyDto MapSurvey(dynamic s)=>new((Guid)s.id,(string)s.title,(string?)s.description,(string)s.status,(bool)s.lgpd_required); static PublicFormDto MapForm(dynamic f,IReadOnlyList<dynamic> dims,IReadOnlyList<dynamic> qs,IReadOnlyList<dynamic> opts)=>new((Guid)f.id,(string)f.name,(string?)f.description,(int?)f.time_min,qs.Select(q=>new PublicQuestionDto((Guid)q.id,(string)q.text,(string)q.type,(bool)q.required,(decimal)q.max_score,Name(dims,(Guid?)q.dimension_id),(int)q.display_order,opts.Where(o=>(Guid)o.question_id==(Guid)q.id).Select(o=>new PublicQuestionOptionDto((Guid)o.id,(string)o.text,(decimal?)o.score,(int)o.display_order)).ToList())).ToList()); static string? Name(IReadOnlyList<dynamic>d,Guid? id)=>id is null?null:(string?)d.FirstOrDefault(x=>(Guid)x.id==id)?.name;
 static List<(Guid QuestionId,string DimensionName,string? AnswerText,decimal Score,decimal MaxScore)> ScoreAnswers(IReadOnlyList<dynamic> qs,IReadOnlyList<dynamic> dims,Dictionary<string,object>? ans){var list=new List<(Guid,string,string?,decimal,decimal)>(); foreach(var q in qs){var raw=Val(ans,((Guid)q.id).ToString())??Val(ans,$"q{(int)q.display_order}"); if((bool)q.required&&string.IsNullOrWhiteSpace(raw)) throw new InvalidOperationException($"Pergunta obrigatória sem resposta: {q.text}"); var max=(decimal)q.max_score; var score=decimal.TryParse(raw,out var n)?Math.Clamp(n,0,max):0; list.Add(((Guid)q.id,Name(dims,(Guid?)q.dimension_id)??"Sem dimensão",raw,score,max));} return list;}
 static List<DimensionScoreDto> BuildDims(IEnumerable<(Guid QuestionId,string DimensionName,string? AnswerText,decimal Score,decimal MaxScore)> scored)=>scored.GroupBy(x=>x.DimensionName).Select(g=>new DimensionScoreDto(g.Key,g.Sum(x=>x.Score),g.Sum(x=>x.MaxScore),Math.Round(g.Sum(x=>x.Score)/Math.Max(1,g.Sum(x=>x.MaxScore))*100,2),g.Sum(x=>x.Score) switch{<=11=>"Crítico",<=17=>"Em estruturação",<=22=>"Estruturada",_=>"Alta maturidade"})).ToList(); static ResultScoreDto MapResult(ValoraInsightResult r,IReadOnlyList<DimensionScoreDto>d)=>new(r.TotalScore,r.MaxScore,Math.Round(r.TotalScore/r.MaxScore*100,2),r.Level,d.OrderByDescending(x=>x.Score).FirstOrDefault()?.DimensionName,d.OrderBy(x=>x.Score).FirstOrDefault()?.DimensionName,"Radar calculado com respostas reais por dimensão.",r.StrategicTruth,r.Risk,r.NextLevel);
}
