using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Logging;

namespace Valora.Application.People;

public sealed record PeopleProfileDto(Guid Id,string DisplayName,string Status,string? RoleTitle,DateTimeOffset CreatedAt);
public sealed record PeopleTeamDto(Guid Id,string Name,Guid ResponsibleProfileId,string ResponsibleName,int MemberCount,DateTimeOffset CreatedAt);
public sealed record CultureAssessmentDto(Guid Id,string Dimension,string Source,string EvidenceSummary,decimal Score,int SampleSize,string Confidence,string Limitations,DateTimeOffset AssessedAt);
public sealed record EngagementSignalDto(Guid Id,string Source,string EvidenceSummary,decimal? Score,string Confidence,string Limitations,DateTimeOffset ObservedAt);
public sealed record CompetencyAssessmentDto(Guid Id,string Competency,string SubjectType,decimal ExpectedLevel,decimal ObservedLevel,string EvidenceSummary,bool HumanReviewed,DateTimeOffset AssessedAt);
public sealed record DevelopmentPlanDto(Guid Id,string SubjectType,string SubjectName,string Objective,string ResponsibleName,DateOnly DueDate,string Status,int OpenItems,DateTimeOffset CreatedAt);
public sealed record PeopleRiskSignalDto(Guid Id,string SignalType,string EvidenceSummary,string Confidence,string Limitations,string Status,bool HumanReviewed,DateTimeOffset CreatedAt);
public sealed record PeopleDashboardDto(int Profiles,int Teams,IReadOnlyList<CultureAssessmentDto> Culture,IReadOnlyList<EngagementSignalDto> Engagement,IReadOnlyList<CompetencyAssessmentDto> Competencies,IReadOnlyList<DevelopmentPlanDto> DevelopmentPlans,IReadOnlyList<PeopleRiskSignalDto> Risks,string ResponsibleUseNotice);

public sealed class CreatePeopleProfileRequest { [Required,StringLength(120,MinimumLength=2)] public string DisplayName {get;set;}=""; [StringLength(120)] public string? RoleTitle {get;set;} }
public sealed class CreatePeopleTeamRequest { [Required,StringLength(120,MinimumLength=2)] public string Name {get;set;}=""; [Required] public Guid ResponsibleProfileId {get;set;} }
public sealed class CreateCultureAssessmentRequest { [Required] public Guid DimensionId {get;set;} [Required,StringLength(80)] public string Source {get;set;}=""; [Required,StringLength(2000,MinimumLength=10)] public string EvidenceSummary {get;set;}=""; [Range(0,100)] public decimal Score {get;set;} [Range(1,100000)] public int SampleSize {get;set;} [StringLength(1000)] public string? Limitations {get;set;} }
public sealed class CreateEngagementSignalRequest { [Required,StringLength(80)] public string Source {get;set;}=""; [Required,StringLength(2000,MinimumLength=10)] public string EvidenceSummary {get;set;}=""; [Range(0,100)] public decimal? Score {get;set;} [StringLength(1000)] public string? Limitations {get;set;} }
public sealed class CreateCompetencyAssessmentRequest { [Required] public Guid CompetencyId {get;set;} public Guid? ProfileId {get;set;} public Guid? TeamId {get;set;} [Range(0,5)] public decimal ExpectedLevel {get;set;} [Range(0,5)] public decimal ObservedLevel {get;set;} [Required,StringLength(2000,MinimumLength=10)] public string EvidenceSummary {get;set;}=""; public bool HumanReviewed {get;set;} }
public sealed class CreateDevelopmentPlanRequest { public Guid? ProfileId {get;set;} public Guid? TeamId {get;set;} [Required,StringLength(500,MinimumLength=5)] public string Objective {get;set;}=""; [Required] public Guid ResponsibleProfileId {get;set;} [Required] public DateOnly DueDate {get;set;} [Required,MinLength(1)] public List<string> Actions {get;set;}=[]; }
public sealed class ReviewPeopleRiskRequest { [Required] public Guid RiskSignalId {get;set;} [Required,StringLength(30)] public string Decision {get;set;}=""; [Required,StringLength(2000,MinimumLength=10)] public string ReviewNotes {get;set;}=""; public bool HumanConfirmation {get;set;} }

public interface IPeopleProfileRepository { Task<IReadOnlyList<PeopleProfileDto>> List(Guid o,CancellationToken ct); Task<Guid> Create(Guid o,Guid user,CreatePeopleProfileRequest r,CancellationToken ct); }
public interface IPeopleTeamRepository { Task<IReadOnlyList<PeopleTeamDto>> List(Guid o,CancellationToken ct); Task<Guid> Create(Guid o,Guid user,CreatePeopleTeamRequest r,CancellationToken ct); }
public interface ICultureAssessmentRepository { Task<IReadOnlyList<CultureAssessmentDto>> List(Guid o,CancellationToken ct); Task<Guid> Create(Guid o,Guid user,CreateCultureAssessmentRequest r,string confidence,CancellationToken ct); }
public interface IEngagementSignalRepository { Task<IReadOnlyList<EngagementSignalDto>> List(Guid o,CancellationToken ct); Task<Guid> Create(Guid o,Guid user,CreateEngagementSignalRequest r,string confidence,CancellationToken ct); }
public interface ICompetencyRepository { Task<IReadOnlyList<CompetencyAssessmentDto>> List(Guid o,CancellationToken ct); Task<Guid> Assess(Guid o,Guid user,CreateCompetencyAssessmentRequest r,CancellationToken ct); }
public interface IDevelopmentPlanRepository { Task<IReadOnlyList<DevelopmentPlanDto>> List(Guid o,CancellationToken ct); Task<Guid> Create(Guid o,Guid user,CreateDevelopmentPlanRequest r,CancellationToken ct); }
public interface IPeopleRiskSignalRepository { Task<IReadOnlyList<PeopleRiskSignalDto>> List(Guid o,CancellationToken ct); Task Review(Guid o,Guid user,ReviewPeopleRiskRequest r,CancellationToken ct); }

internal static class PeopleValidation { public static void Scope(Guid o){if(o==Guid.Empty)throw new ValidationException("Selecione uma organização para continuar.");} public static void Evidence(string value){if(string.IsNullOrWhiteSpace(value)||value.Trim().Length<10)throw new ValidationException("Registre evidência suficiente e verificável.");} }
public sealed class PeopleProfileService(IPeopleProfileRepository repo,ILogger<PeopleProfileService> log){public Task<IReadOnlyList<PeopleProfileDto>> List(Guid o,CancellationToken ct){PeopleValidation.Scope(o);return repo.List(o,ct);}public Task<Guid>Create(Guid o,Guid u,CreatePeopleProfileRequest r,CancellationToken ct){PeopleValidation.Scope(o);if(string.IsNullOrWhiteSpace(r.DisplayName))throw new ValidationException("Informe o nome de exibição.");log.LogInformation("Criando perfil People na organização {OrganizationId}",o);return repo.Create(o,u,r,ct);}}
public sealed class PeopleTeamService(IPeopleTeamRepository repo,ILogger<PeopleTeamService> log){public Task<IReadOnlyList<PeopleTeamDto>>List(Guid o,CancellationToken ct){PeopleValidation.Scope(o);return repo.List(o,ct);}public Task<Guid>Create(Guid o,Guid u,CreatePeopleTeamRequest r,CancellationToken ct){PeopleValidation.Scope(o);if(r.ResponsibleProfileId==Guid.Empty)throw new ValidationException("Selecione uma liderança responsável válida.");log.LogInformation("Criando time People na organização {OrganizationId}",o);return repo.Create(o,u,r,ct);}}
public sealed class CultureAssessmentService(ICultureAssessmentRepository repo,ILogger<CultureAssessmentService> log){public Task<IReadOnlyList<CultureAssessmentDto>>List(Guid o,CancellationToken ct){PeopleValidation.Scope(o);return repo.List(o,ct);}public Task<Guid>Create(Guid o,Guid u,CreateCultureAssessmentRequest r,CancellationToken ct){PeopleValidation.Scope(o);PeopleValidation.Evidence(r.EvidenceSummary);var confidence=r.SampleSize<5?"low":r.SampleSize<15?"medium":"high";log.LogInformation("Avaliação cultural agregada registrada com confiança {Confidence}",confidence);return repo.Create(o,u,r,confidence,ct);}}
public sealed class EngagementSignalService(IEngagementSignalRepository repo,ILogger<EngagementSignalService> log){public Task<IReadOnlyList<EngagementSignalDto>>List(Guid o,CancellationToken ct){PeopleValidation.Scope(o);return repo.List(o,ct);}public Task<Guid>Create(Guid o,Guid u,CreateEngagementSignalRequest r,CancellationToken ct){PeopleValidation.Scope(o);PeopleValidation.Evidence(r.EvidenceSummary);log.LogInformation("Sinal de engajamento registrado como evidência, não conclusão");return repo.Create(o,u,r,"low",ct);}}
public sealed class CompetencyFrameworkService(ICompetencyRepository repo){public Task<IReadOnlyList<CompetencyAssessmentDto>>List(Guid o,CancellationToken ct){PeopleValidation.Scope(o);return repo.List(o,ct);}}
public sealed class CompetencyAssessmentService(ICompetencyRepository repo,ILogger<CompetencyAssessmentService> log){public Task<Guid>Assess(Guid o,Guid u,CreateCompetencyAssessmentRequest r,CancellationToken ct){PeopleValidation.Scope(o);PeopleValidation.Evidence(r.EvidenceSummary);if((r.ProfileId is null)==(r.TeamId is null))throw new ValidationException("Selecione uma pessoa ou um time.");if(!r.HumanReviewed)throw new ValidationException("A avaliação exige revisão humana explícita.");log.LogInformation("Avaliação de competência revisada por pessoa registrada");return repo.Assess(o,u,r,ct);}}
public sealed class DevelopmentPlanService(IDevelopmentPlanRepository repo,ILogger<DevelopmentPlanService> log){public Task<IReadOnlyList<DevelopmentPlanDto>>List(Guid o,CancellationToken ct){PeopleValidation.Scope(o);return repo.List(o,ct);}public Task<Guid>Create(Guid o,Guid u,CreateDevelopmentPlanRequest r,CancellationToken ct){PeopleValidation.Scope(o);if((r.ProfileId is null)==(r.TeamId is null))throw new ValidationException("Selecione uma pessoa ou um time.");if(r.DueDate<=DateOnly.FromDateTime(DateTime.UtcNow)||r.Actions.Count==0)throw new ValidationException("Informe prazo futuro e ao menos uma ação acompanhável.");log.LogInformation("Plano de desenvolvimento criado com {ActionCount} ações",r.Actions.Count);return repo.Create(o,u,r,ct);}}
public sealed class PeopleRiskSignalService(IPeopleRiskSignalRepository repo,ILogger<PeopleRiskSignalService> log){public Task<IReadOnlyList<PeopleRiskSignalDto>>List(Guid o,CancellationToken ct){PeopleValidation.Scope(o);return repo.List(o,ct);}public Task Review(Guid o,Guid u,ReviewPeopleRiskRequest r,CancellationToken ct){PeopleValidation.Scope(o);PeopleValidation.Evidence(r.ReviewNotes);if(!r.HumanConfirmation)throw new ValidationException("A revisão exige confirmação humana.");log.LogInformation("Sinal de risco revisado por decisão humana");return repo.Review(o,u,r,ct);}}
public sealed class PeopleInsightService(PeopleProfileService profiles,PeopleTeamService teams,CultureAssessmentService culture,EngagementSignalService engagement,CompetencyFrameworkService competencies,DevelopmentPlanService plans,PeopleRiskSignalService risks){public async Task<PeopleDashboardDto>Get(Guid o,CancellationToken ct){PeopleValidation.Scope(o);var p=await profiles.List(o,ct);var t=await teams.List(o,ct);return new(p.Count,t.Count,await culture.List(o,ct),await engagement.List(o,ct),await competencies.List(o,ct),await plans.List(o,ct),await risks.List(o,ct),"Sinais apoiam acompanhamento preventivo; não classificam pessoas nem substituem decisão humana.");}}
