const express=require('express');const {config}=require('../config');const {jsonError}=require('../security');const {validateResultPayload}=require('../validators');const {sendResultEmail,sendSimpleTestEmail,buildPayloadFromFirestore}=require('../email-service');const {appendCommunicationLog}=require('../storage/communication-log');const {loadResultContext,registerCommunication,loadPublicSurveyContext,savePublicSurveyResponse}=require('../firebase/firestore-service');const {enqueueEmailJob,getQueueStatus,key}=require('../queue/email-queue');const router=express.Router();
function emailStatus(){return {enabled:config.smtp.enabled,configured:config.emailConfigured,provider:'smtp',fromName:config.smtp.fromName,fromEmail:config.smtp.fromEmail,queue:config.emailQueue.enabled}}
router.get('/communication/status',async(_,res)=>res.json({ok:true,email:emailStatus(),queue:await getQueueStatus(),gateway:{mode:'server-validated'}}));
router.post('/communication/email/test',async(req,res)=>{const to=String(req.body?.to||'').trim();if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(to))return jsonError(res,400,'invalid-email','Destinatário inválido.');if(!config.emailConfigured)return jsonError(res,503,'smtp-not-configured','SMTP do gateway não configurado.');try{const r=await sendSimpleTestEmail(to,config);return res.json({ok:true,status:'sent',messageId:r.messageId})}catch(e){return res.status(502).json({ok:false,status:'failed',message:e.message||'Falha ao testar SMTP.',code:'smtp-test-failed'})}});
router.post('/communication/result/send',async(req,res)=>{const body=req.body||{};const errors=validateResultPayload(body);if(errors.length)return jsonError(res,400,'invalid-payload',`Payload inválido: ${errors.join(', ')}`);try{const ctx=await loadResultContext(body.responseId,body.resultToken||'');const payload=buildPayloadFromFirestore(ctx,config);if(!body.channels?.email)return res.json({ok:true,status:'skipped',message:'Nenhum canal automático solicitado.'});if(!payload.participant?.email){await appendCommunicationLog(payload,{status:'missing-recipient',error:'Participante sem e-mail.'});return res.json({ok:true,status:'missing-recipient',message:'Não encontramos um e-mail para envio automático.'})}if(!config.emailConfigured)return jsonError(res,503,'smtp-not-configured','SMTP do gateway não configurado.');const idempotencyKey=key('survey-result',payload.responseId,'email');const queued=await enqueueEmailJob({idempotencyKey,responseId:payload.responseId,surveyId:payload.surveyId,companyId:payload.companyId,participantEmail:payload.participant.email,maxAttempts:config.emailQueue.maxAttempts});if(queued.status==='already-sent')return res.json({ok:true,status:'already-sent',message:'Resultado já enviado por e-mail.'});if(queued.status==='already-queued')return res.json({ok:true,status:'already-queued',message:'Envio já está em processamento.'});try{const result=await sendResultEmail(payload,config);const sentAt=new Date().toISOString();const {markJobAsSent}=require('../queue/email-queue');await markJobAsSent(idempotencyKey,result.messageId);await appendCommunicationLog(payload,{...result,status:'sent'});await registerCommunication({...payload,channel:'email',status:'sent',idempotencyKey,providerMessageId:result.messageId,sentAt});return res.json({ok:true,channel:'email',status:'sent',message:'Resultado enviado por e-mail.',messageId:result.messageId,sentAt})}catch(error){const {markJobAsFailed}=require('../queue/email-queue');const job=await markJobAsFailed(idempotencyKey,error);await appendCommunicationLog(payload,{status:job?.status||'failed',error:error.message});await registerCommunication({...payload,channel:'email',status:job?.status||'failed',idempotencyKey,errorMessage:error.message});return res.status(502).json({ok:false,status:job?.status||'failed',message:error.message||'Não foi possível enviar o e-mail.',code:'smtp-send-failed'})}}catch(error){const status=error.status||502;await appendCommunicationLog({responseId:body.responseId,participant:{}},{status:'failed',error:error.message});return res.status(status).json({ok:false,status:'failed',message:error.message||'Não foi possível enviar o e-mail.',code:error.code||'gateway-error'});}});


router.get('/public/surveys/:surveyId',async(req,res)=>{
  try{const surveyId=String(req.params.surveyId||'').trim();const token=String(req.query.token||'');const ctx=await loadPublicSurveyContext(surveyId);const survey=ctx.survey||{},form=ctx.form||{};const status=String(survey.status||'').toLowerCase();if(!['active','published','open'].includes(status))return jsonError(res,403,'survey-closed','Pesquisa indisponível.');if(survey.expiresAt&&new Date(survey.expiresAt)<new Date())return jsonError(res,403,'survey-expired','Pesquisa expirada.');const validToken=survey.token||survey.publicToken||survey.accessToken;if(validToken&&validToken!==token)return jsonError(res,403,'invalid-token','Token inválido.');return res.json({ok:true,survey:{id:survey.id,title:survey.title||survey.name,companyId:survey.companyId,formId:survey.formId,lgpdRequired:survey.lgpdRequired!==false,requireIdentification:survey.requireIdentification!==false,allowRepeat:survey.allowRepeat!==false,status:survey.status,expiresAt:survey.expiresAt},form:{id:form.id,name:form.name||form.title||'Pesquisa',description:form.description||'',timeMin:form.timeMin||5,questions:form.questions||[],resultBands:form.resultBands||[]},company:{id:ctx.company?.id||'',name:ctx.company?.publicName||ctx.company?.name||'Valora Group'},lgpd:{text:ctx.company?.settings?.lgpdText||''}});}
  catch(error){return res.status(error.status||502).json({ok:false,message:error.message||'Pesquisa indisponível.',code:error.code||'public-survey-failed'});}
});
router.post('/public/surveys/:surveyId/responses',async(req,res)=>{
  const surveyId=String(req.params.surveyId||'').trim();const body=req.body||{};
  try{
    if(!surveyId)return jsonError(res,400,'missing-survey','Pesquisa obrigatória.');
    if(!body.participant?.email||!body.participant?.name)return jsonError(res,400,'invalid-participant','Nome e e-mail são obrigatórios.');
    const ctx=await loadPublicSurveyContext(surveyId);const survey=ctx.survey||{},form=ctx.form||{};
    const status=String(survey.status||'').toLowerCase();if(!['active','published','open'].includes(status))return jsonError(res,403,'survey-closed','Pesquisa indisponível.');
    if(survey.expiresAt&&new Date(survey.expiresAt)<new Date())return jsonError(res,403,'survey-expired','Pesquisa expirada.');
    const validToken=survey.token||survey.publicToken||survey.accessToken; if(validToken&&validToken!==body.token)return jsonError(res,403,'invalid-token','Token inválido.');
    for(const q of (form.questions||[])){const v=(body.answers||{})[q.id];if(q.required&&(v===undefined||v===null||v===''||(Array.isArray(v)&&!v.length)))return jsonError(res,400,'required-answer',`Pergunta obrigatória sem resposta: ${q.text||q.id}`);}
    const crypto=require('crypto');const resultToken=`rt_${crypto.randomBytes(24).toString('base64url')}`;
    const saved=await savePublicSurveyResponse({survey,form,payload:body,resultToken});
    let emailStatus='pending';
    if(!body.communicationConsent)emailStatus='pending'; else if(!body.participant?.email)emailStatus='missing-recipient'; else {
      try{const payload=buildPayloadFromFirestore({response:{id:saved.id,surveyId:survey.id,formId:form.id,companyId:survey.companyId,participant:body.participant,resultToken, ...(saved.result||{})},survey,form,company:ctx.company},config); if(config.emailConfigured){const sent=await sendResultEmail(payload,config);emailStatus='sent';await registerCommunication({...payload,channel:'email',status:'sent',providerMessageId:sent.messageId,sentAt:new Date().toISOString()});}else emailStatus='pending';}
      catch(e){emailStatus='failed';await registerCommunication({responseId:saved.id,surveyId:survey.id,companyId:survey.companyId,participantEmail:body.participant.email,participantName:body.participant.name,channel:'email',status:'failed',errorMessage:e.message});}
    }
    const base=config.appPublicUrl||'https://valoragroup.mnsoft.com.br';const u=new URL(base);u.searchParams.set('result',saved.id);u.searchParams.set('rt',resultToken);
    return res.json({ok:true,responseId:saved.id,resultToken,emailStatus,resultUrl:u.toString()});
  }catch(error){return res.status(error.status||502).json({ok:false,status:'failed',message:error.message||'Não foi possível enviar a pesquisa.',code:error.code||'public-submit-failed'});}
});
router.post('/communication/queue/process',async(_,res)=>{const {processEmailQueue}=require('../queue/email-queue');const results=await processEmailQueue(async job=>{const ctx=await loadResultContext(job.responseId,'');const payload=buildPayloadFromFirestore(ctx,config);const r=await sendResultEmail(payload,config);await appendCommunicationLog(payload,{...r,status:'sent'});await registerCommunication({...payload,channel:'email',status:'sent',providerMessageId:r.messageId,sentAt:new Date().toISOString()});return r});res.json({ok:true,processed:results,queue:await getQueueStatus()})});
router.post('/communication/email/send',(_,res)=>res.status(501).json({ok:false,status:'not-implemented',message:'Use /communication/result/send para e-mails de resultado.',code:'not-implemented'}));
router.post('/communication/whatsapp/send',(_,res)=>res.status(501).json({ok:false,status:'not-implemented',message:'WhatsApp automático depende de provedor externo configurado.',code:'not-implemented'}));
module.exports=router;
