const fs=require('fs');const path=require('path');const {config}=require('../config');const {maskEmail}=require('../logger');
const inFlight=new Set();function queueFile(){return path.join(config.logDir,'email-queue.json')}async function ensure(){await fs.promises.mkdir(config.logDir,{recursive:true})}
async function readQueue(){try{return JSON.parse(await fs.promises.readFile(queueFile(),'utf8'))}catch{return []}}
async function writeQueue(q){await ensure();await fs.promises.writeFile(queueFile(),JSON.stringify(q,null,2))}
function key(type,responseId,channel='email'){return `${type}:${responseId}:${channel}`}
async function enqueueEmailJob(input={}){const now=new Date().toISOString();const q=await readQueue();const idempotencyKey=input.idempotencyKey||key(input.type||'survey-result',input.responseId,'email');const existing=q.find(j=>j.idempotencyKey===idempotencyKey);if(existing?.status==='sent')return {ok:true,status:'already-sent',job:existing};if(existing&&['pending','processing'].includes(existing.status))return {ok:true,status:'already-queued',job:existing};const job={id:existing?.id||`email_${Date.now()}_${Math.random().toString(36).slice(2,8)}`,idempotencyKey,type:input.type||'survey-result',responseId:input.responseId||'',surveyId:input.surveyId||'',companyId:input.companyId||'',participantEmailMasked:maskEmail(input.participantEmail||''),status:'pending',attempts:existing?.attempts||0,maxAttempts:Number(input.maxAttempts||config.emailQueue.maxAttempts||3),nextAttemptAt:now,lastError:'',providerMessageId:'',createdAt:existing?.createdAt||now,updatedAt:now,sentAt:''};if(existing)q[q.indexOf(existing)]=job;else q.push(job);await writeQueue(q);return {ok:true,status:'queued',job}}
async function markJobAsSent(id,providerMessageId=''){const q=await readQueue();const j=q.find(x=>x.id===id||x.idempotencyKey===id);if(j){j.status='sent';j.providerMessageId=providerMessageId;j.sentAt=new Date().toISOString();j.updatedAt=j.sentAt;j.lastError='';await writeQueue(q)}return j}
async function markJobAsFailed(id,error){const q=await readQueue();const j=q.find(x=>x.id===id||x.idempotencyKey===id);if(j){j.attempts=(j.attempts||0)+1;j.lastError=String(error?.message||error||'Falha SMTP').slice(0,500);j.status=j.attempts>=j.maxAttempts?'failed':'pending';j.nextAttemptAt=new Date(Date.now()+Number(config.emailQueue.retryMinutes||5)*60000).toISOString();j.updatedAt=new Date().toISOString();await writeQueue(q)}return j}
async function processEmailQueue(processor){const q=await readQueue();const now=Date.now();const jobs=q.filter(j=>['pending','processing'].includes(j.status)&&Date.parse(j.nextAttemptAt||0)<=now);const results=[];for(const j of jobs){if(inFlight.has(j.idempotencyKey))continue;inFlight.add(j.idempotencyKey);j.status='processing';j.updatedAt=new Date().toISOString();await writeQueue(q);try{const r=await processor(j);await markJobAsSent(j.id,r?.messageId||'');results.push({id:j.id,status:'sent'})}catch(e){const failed=await markJobAsFailed(j.id,e);results.push({id:j.id,status:failed?.status||'failed',error:e.message})}finally{inFlight.delete(j.idempotencyKey)}}return results}
async function retryFailedJobs(){const q=await readQueue();for(const j of q.filter(x=>x.status==='failed'&&(x.attempts||0)<(x.maxAttempts||3))){j.status='pending';j.nextAttemptAt=new Date().toISOString();j.updatedAt=j.nextAttemptAt}await writeQueue(q);return q.filter(j=>j.status==='pending').length}
async function getQueueStatus(){const q=await readQueue();return {ok:true,total:q.length,pending:q.filter(j=>j.status==='pending').length,processing:q.filter(j=>j.status==='processing').length,sent:q.filter(j=>j.status==='sent').length,failed:q.filter(j=>j.status==='failed').length,jobs:q.slice(-100).reverse()}}
module.exports={enqueueEmailJob,processEmailQueue,retryFailedJobs,markJobAsSent,markJobAsFailed,getQueueStatus,key};
