#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const https = require('https');
const http = require('http');
const { URL } = require('url');

const root = path.resolve(__dirname, '..');
const reportsDir = path.join(root, 'publish', 'reports');
const stamp = new Date().toISOString().replace(/[-:T]/g, '').slice(0, 12);
const okTypes = { js: ['application/javascript', 'text/javascript', 'application/x-javascript', 'application/ecmascript', 'text/ecmascript'], css: ['text/css'] };
const report = { date: new Date().toISOString(), url: '', project: '', status: 'PENDING', checks: [], errors: [], warnings: [], recommendations: [] };

function parseArgs(argv) { const out = { timeout: 15000, report: true }; for (let i = 0; i < argv.length; i++) { const a = argv[i]; if (!a.startsWith('--')) continue; const k = a.slice(2).replace(/-([a-z])/g, (_, c) => c.toUpperCase()); if (['json','report','checkFirebase','checkFirestore','checkFunctions','checkPublicSurvey'].includes(k)) out[k] = true; else out[k] = argv[++i]; } out.timeout = Number(out.timeout || 15000); return out; }
const args = parseArgs(process.argv.slice(2)); report.url = args.url || ''; report.project = args.project || '';
function add(name, status, details = '', meta = {}) { report.checks.push({ name, status, details, ...meta }); if (status === 'FAIL') report.errors.push(`${name}: ${details}`); if (status === 'WARN') report.warnings.push(`${name}: ${details}`); }
function failRec(text) { if (!report.recommendations.includes(text)) report.recommendations.push(text); }
function req(url, timeout = args.timeout) { return new Promise(resolve => { const u = new URL(url); const lib = u.protocol === 'https:' ? https : http; const r = lib.request(u, { method: 'GET', timeout, rejectUnauthorized: true, headers: { 'user-agent': 'valora-prd-healthcheck/1.0' } }, res => { const chunks = []; res.on('data', d => chunks.push(d)); res.on('end', () => resolve({ ok: true, url, status: res.statusCode, headers: res.headers, body: Buffer.concat(chunks) })); }); r.on('timeout', () => { r.destroy(new Error(`Timeout após ${timeout}ms`)); }); r.on('error', err => resolve({ ok: false, url, status: 0, headers: {}, body: Buffer.alloc(0), error: err })); r.end(); }); }
function joinUrl(base, ref) { return new URL(ref.replace(/^\//, ''), base.endsWith('/') ? base : `${base}/`).toString(); }
function refs(html, ext) { return [...html.matchAll(/(?:src|href)=["']([^"']+\.(?:js|css)(?:\?[^"']*)?)["']/gi)].map(m => m[1]).filter(x => ext ? new URL(x, 'https://x/').pathname.endsWith(`.${ext}`) : true); }
function isHtml(buf, type) { return /text\/html/i.test(type || '') || /^\s*</.test(buf.toString('utf8', 0, Math.min(80, buf.length))); }
function checkStatusSymptoms(res) { const body = res.body.toString('utf8').slice(0, 3000); if (res.status === 500 && /500\.19|web\.config|configuration/i.test(body)) { add('IIS/web.config', 'FAIL', 'web.config inválido ou módulo não suportado (sintoma 500.19).'); failRec('Corrigir web.config no IIS ou remover módulos não suportados antes de republicar.'); } if (res.status === 403 && /403\.14|directory listing|default document/i.test(body)) { add('IIS/index.html', 'FAIL', 'index.html ausente ou Default Document não configurado (sintoma 403.14).'); failRec('Confirmar index.html no diretório publicado e Default Document do IIS.'); } }
async function checkAsset(base, ref, kind) { const url = joinUrl(base, ref); const res = await req(url); const type = String(res.headers['content-type'] || '').split(';')[0].toLowerCase(); const min = kind === 'js' ? 10 * 1024 : 1024; if (!res.ok || res.status !== 200) { add(`Asset ${kind.toUpperCase()} ${ref}`, 'FAIL', 'Asset JS/CSS não encontrado ou retornando erro. Provável publicação inconsistente: index.html de um build e assets de outro.'); return null; } if (isHtml(res.body, type)) { add(`MIME ${kind.toUpperCase()} ${ref}`, 'FAIL', 'Asset JS/CSS não encontrado ou retornando HTML. Provável publicação inconsistente: index.html de um build e assets de outro.'); return res; } if (!okTypes[kind].some(t => type.includes(t))) add(`MIME ${kind.toUpperCase()} ${ref}`, 'FAIL', `Content-Type inválido: ${type || 'vazio'}.`); else add(`MIME ${kind.toUpperCase()} ${ref}`, 'PASS', type);
 if (res.body.length <= min) add(`Tamanho ${kind.toUpperCase()} ${ref}`, 'FAIL', `Arquivo menor que ${min} bytes.`); else add(`Tamanho ${kind.toUpperCase()} ${ref}`, 'PASS', `${res.body.length} bytes`); return res; }
function checkFirebaseConfig(html, assetsText) { const all = `${html}\n${assetsText}`; const enabled = /FIREBASE_ENABLED\s*[:=]\s*true/.test(all); const storageFirebase = /STORAGE_MODE\s*[:=]\s*['"]firebase['"]/.test(all); const projectOk = new RegExp(`projectId\\s*[:=]\\s*['"]${args.project || '[^\'\"]+'}['"]`).test(all) || all.includes(args.project || '');
 if (!args.checkFirebase && !enabled && !storageFirebase) { add('Firebase config', 'WARN', 'Firebase não parece habilitado no frontend publicado.'); return; }
 if (enabled && (!storageFirebase || !projectOk)) { add('Firebase config', 'FAIL', 'Firebase habilitado sem STORAGE_MODE firebase ou projectId esperado.'); failRec('Publicar config.js/build com FIREBASE_ENABLED=true, STORAGE_MODE="firebase" e FIREBASE_CONFIG.projectId correto.'); } else add('Firebase config', 'PASS', `STORAGE_MODE=firebase e projectId=${args.project || 'detectado'}`);
 if (!/ValoraFirebaseServices|firebase\.initializeApp|initializeApp|window\.firebase/.test(all)) add('Firebase SDK', enabled ? 'FAIL' : 'WARN', 'Firebase habilitado, mas SDK/serviços não foram detectados no HTML/JS.'); else add('Firebase SDK', 'PASS', 'Referências ao SDK/serviços detectadas.'); }
function sparkFunctionsDisabledText(){try{return fs.readFileSync(path.join(root,'config.js'),'utf8').includes('ENABLE_CLOUD_FUNCTIONS:false');}catch(_){return false;}}
async function checkFunctions() { if (sparkFunctionsDisabledText()) { add('Functions getEmailStatus', 'PASS', 'Cloud Functions desabilitadas no plano Spark; getEmailStatus não é obrigatório.'); return; } if (!args.checkFunctions || !args.project) return; const url = `https://us-central1-${args.project}.cloudfunctions.net/getEmailStatus`; const res = await req(url); if (res.status === 404) add('Functions getEmailStatus', 'FAIL', `${url} não encontrado.`); else add('Functions getEmailStatus', res.ok ? 'WARN' : 'FAIL', `HTTP ${res.status}. Se for onCall, não deve ser validada por fetch comum; teste real deve usar Firebase SDK para evitar falso CORS.`); }
async function checkFirestoreAdmin() { if (!args.checkFirestore) return; try { const admin = require('firebase-admin'); if (!admin.apps.length) admin.initializeApp({ projectId: args.project }); const db = admin.firestore(); const cols = ['plans','modules','organizations','users','forms','surveys','settings','knowledgeBase']; const counts = {}; for (const c of cols) { const s = await db.collection(c).limit(10).get(); counts[c] = s.size; add(`Firestore ${c}`, s.empty && ['plans','modules','organizations','users','forms','surveys'].includes(c) ? 'FAIL' : 'PASS', `${s.size} documento(s) amostrados`); }
 const users = await db.collection('users').where('role','==','admin_valora').limit(1).get(); add('Auth/Admin Valora', users.empty ? 'FAIL' : 'PASS', users.empty ? 'Nenhum usuário admin_valora no Firestore.' : 'admin_valora encontrado no Firestore.'); if (users.empty) failRec('Firestore PRD está sem dados-base. Execute o bootstrap/importação local -> Firebase antes de publicar.');
 const survey = await db.collection('surveys').where('status','==','active').limit(1).get(); if (!survey.empty) { const data = survey.docs[0].data(); add('Pesquisa pública', data.formId && data.tokenHash ? 'PASS' : 'WARN', data.formId ? 'Survey ativa possui formId; token bruto não é exigido quando há hash.' : 'Survey ativa sem formId.'); } else add('Pesquisa pública', 'WARN', 'Nenhuma survey ativa para validar.');
 } catch (err) { add('Firestore/Admin SDK', 'FAIL', `Não foi possível validar Firestore/Auth: ${err.message}`); } }
async function checkPlaywright(base) { try { require.resolve('@playwright/test'); } catch (_) { add('Navegador/Playwright', 'WARN', 'Playwright não instalado; validação visual opcional não executada.'); return; }
 let browser; try { const { chromium } = require('@playwright/test'); browser = await chromium.launch({ headless: true }); const errors = []; for (const viewport of [{ width: 1366, height: 768 }, { width: 360, height: 800 }]) { const page = await browser.newPage({ viewport }); page.on('console', m => { const t = m.text(); if (/MIME type|CORS policy|Firebase não configurado|Failed to load resource.*404|Serviço de autenticação indisponível/i.test(t)) errors.push(t); }); page.on('pageerror', e => errors.push(e.message)); await page.goto(base, { waitUntil: 'domcontentloaded', timeout: args.timeout }); const botButton = page.locator('[data-action="toggleBot"], .public-bot-button, .float-help').first(); const bot = await botButton.count(); add(`ValoraBot ${viewport.width}x${viewport.height}`, bot ? 'PASS' : 'FAIL', bot ? 'Botão público encontrado.' : 'ValoraBot não disponível para público.'); if (bot) { await botButton.click({ timeout: 3000 }).catch(() => {}); const panel = page.locator('#botPanel.open, #botPanel[aria-hidden="false"]'); const opened = await panel.count(); add(`ValoraBot abre ${viewport.width}x${viewport.height}`, opened ? 'PASS' : 'FAIL', opened ? 'Painel abriu.' : 'Painel não abriu.'); const greeting = await page.locator('#botMessages').textContent({ timeout: 3000 }).catch(() => ''); add(`ValoraBot saudação ${viewport.width}x${viewport.height}`, /Olá|ValoraBot|diagnóstico|planos/i.test(greeting||'') ? 'PASS' : 'FAIL', (greeting||'').slice(0,120)); const input = page.locator('form[data-form="bot"] input[name="message"]'); await input.fill('quais são os planos?').catch(() => {}); await page.locator('form[data-form="bot"] button').click().catch(() => {}); await page.waitForTimeout(450); const planAnswer = await page.locator('#botMessages').textContent().catch(() => ''); add(`ValoraBot responde planos ${viewport.width}x${viewport.height}`, /Grátis|Essencial|Profissional|Corporativo|Enterprise|planos/i.test(planAnswer||'') ? 'PASS' : 'FAIL', (planAnswer||'').slice(-180)); await input.fill('como interpretar meu resultado?').catch(() => {}); await page.locator('form[data-form="bot"] button').click().catch(() => {}); await page.waitForTimeout(450); const resultAnswer = await page.locator('#botMessages').textContent().catch(() => ''); add(`ValoraBot responde resultado ${viewport.width}x${viewport.height}`, /maturidade|devolutiva|resultado|dimensão|estratégica/i.test(resultAnswer||'') ? 'PASS' : 'FAIL', (resultAnswer||'').slice(-180)); add(`ValoraBot suporte humano ${viewport.width}x${viewport.height}`, /Falar com atendente|atendimento humano|suporte/i.test(resultAnswer||'') ? 'PASS' : 'FAIL', 'Ação de suporte humano verificada nas respostas.'); } await page.locator('a[href*="#plans"], [data-action*="plans"], text=Planos').first().click({ timeout: 2000 }).catch(() => {}); }
 if (errors.length) add('Console navegador', 'FAIL', [...new Set(errors)].slice(0, 10).join(' | ')); else add('Console navegador', 'PASS', 'Sem erros críticos MIME/CORS/Firebase/assets detectados.'); }
 catch (err) { add('Navegador/Playwright', 'WARN', `Validação visual opcional não executada: ${err.message}`); }
 finally { if (browser) await browser.close().catch(() => {}); } }
async function main() { if (!args.url) throw new Error('--url é obrigatório.'); const home = await req(args.url); checkStatusSymptoms(home); if (!home.ok || home.status !== 200) add('HTML principal', 'FAIL', `HTTP ${home.status || home.error?.message}`); else add('HTML principal', /text\/html/i.test(home.headers['content-type'] || '') ? 'PASS' : 'FAIL', `HTTP 200, content-type=${home.headers['content-type'] || 'vazio'}`);
 const html = home.body.toString('utf8'); if (!/<script/i.test(html)) add('HTML scripts', 'FAIL', 'HTML não contém <script>.'); else add('HTML scripts', 'PASS'); if (!/<link/i.test(html)) add('HTML links', 'FAIL', 'HTML não contém <link>.'); else add('HTML links', 'PASS');
 const jsRefs = refs(html, 'js').filter(x => /assets\/app\..+\.js/i.test(x)); const cssRefs = refs(html, 'css').filter(x => /assets\/style\..+\.css/i.test(x)); add('Referências JS', jsRefs.length ? 'PASS' : 'FAIL', jsRefs.join(', ') || 'Nenhum assets/app.*.js encontrado no HTML.'); add('Referências CSS', cssRefs.length ? 'PASS' : 'FAIL', cssRefs.join(', ') || 'Nenhum assets/style.*.css encontrado no HTML.');
 let assetsText = ''; for (const r of [...jsRefs, ...cssRefs]) { const kind = r.endsWith('.css') ? 'css' : 'js'; const res = await checkAsset(args.url, r, kind); if (res && kind === 'js') assetsText += `\n${res.body.toString('utf8')}`; }
 const combined = `${html}\n${assetsText}`; add('Devolutiva Estratégica',/DEVOLUTIVA ESTRATÉGICA/.test(combined)?'PASS':'FAIL','Texto obrigatório da devolutiva estratégica no build.'); add('Resultado sem undefined',/undefined/.test(combined.replace(/undefined\s*[:=]/g,''))?'WARN':'PASS','Build verificado contra undefined em conteúdo renderizado.'); add('Resultado sem NaN',/NaN/.test(combined)?'WARN':'PASS','Build verificado contra NaN.'); add('Resultado sem [object Object]',/\[object Object\]/.test(combined)?'FAIL':'PASS','Build verificado contra serialização indevida.'); add('Valora Insight máximo 125',/maxScore[^\n]{0,40}135|135[^\n]{0,40}Valora Insight/i.test(combined)?'FAIL':'PASS','Nenhum indício de Valora Insight com 135 pontos no build.'); add('Radar textual Valora',/renderRadarBar|Radar Organizacional|insight-radar/.test(combined)?'PASS':'FAIL','Radar textual detectado.'); add('Verdade estratégica',/Verdade estratégica|strategicTruth/.test(combined)?'PASS':'FAIL','Verdade estratégica detectada.'); add('CTA Valora Insight',/Fale com o Valora Group|99254-5353|Falar com especialista|Baixar relatório estratégico/.test(combined)?'PASS':'FAIL','CTA de contato/relatório detectado.'); add('Spark sem Cloud Functions obrigatórias',/ENABLE_CLOUD_FUNCTIONS\s*[:=]\s*false/.test(combined)||sparkFunctionsDisabledText()?'PASS':'WARN','Se ENABLE_CLOUD_FUNCTIONS=false, getEmailStatus não será exigida.');
 checkFirebaseConfig(html, assetsText); await checkFunctions(); await checkFirestoreAdmin(); if (args.checkPublicSurvey && args.publicSurveyUrl) { const p = await req(args.publicSurveyUrl); add('URL pesquisa pública', p.status === 200 && /text\/html/i.test(p.headers['content-type'] || '') ? 'PASS' : 'FAIL', `HTTP ${p.status}`); } else if (args.checkPublicSurvey) add('URL pesquisa pública', 'WARN', 'Informe --public-survey-url para validar link seguro real sem descobrir tokenHash.');
 await checkPlaywright(args.url); report.status = report.errors.length ? 'FAIL' : 'PASS'; writeReports(); if (args.json) console.log(JSON.stringify(report, null, 2)); else print(); process.exit(report.status === 'PASS' ? 0 : 1); }
function writeReports() { if (!args.report) return; fs.mkdirSync(reportsDir, { recursive: true }); const md = [`# Health Check PRD Valora Pulse`, ``, `- Data: ${report.date}`, `- URL: ${report.url}`, `- Projeto Firebase: ${report.project || 'não informado'}`, `- Status geral: ${report.status}`, ``, `## Checks`, ...report.checks.map(c => `- ${c.status}: ${c.name}${c.details ? ` — ${c.details}` : ''}`), ``, `## Erros encontrados`, report.errors.map(e => `- ${e}`).join('\n') || '- Nenhum', ``, `## Ações recomendadas`, report.recommendations.map(e => `- ${e}`).join('\n') || '- Nenhuma', ``].join('\n'); fs.writeFileSync(path.join(reportsDir, `healthcheck-prd-${stamp}.md`), md); fs.writeFileSync(path.join(reportsDir, `healthcheck-prd-${stamp}.json`), JSON.stringify(report, null, 2)); }
function print() { console.log(`Health Check PRD: ${report.status}`); for (const c of report.checks) console.log(`[${c.status}] ${c.name}${c.details ? ` - ${c.details}` : ''}`); if (report.errors.length) console.error(`\nErros:\n- ${report.errors.join('\n- ')}`); }
main().catch(err => { add('Execução', 'FAIL', err.message); report.status = 'FAIL'; writeReports(); console.error(err.message); process.exit(1); });
