'use strict';
function productionPlans(){
  const baseModules=['formularios','pesquisas','respostas','relatorios','certificados','valorabot','support','lgpd','exportacoes','actionPlans'];
  return [
    {id:'free',name:'Grátis',price:0,priceLabel:'R$ 0',priceComplement:'sem mensalidade',badge:'Para começar',publicSubtitle:'Primeiro contato com o diagnóstico.',description:'Para testar o Valora Insight™ em uma experiência inicial de maturidade organizacional.',features:['1 pesquisa ativa','Até 10 respostas','Resultado individual','Devolutiva resumida','Certificado simples'],maxActiveSurveys:1,maxResponsesMonth:10,maxManagers:1,maxCompanies:1,highlighted:false,highlight:false,recommended:false,visibleOnPublicPricing:true,internalOnly:false,isDemo:false,ctaLabel:'Começar grátis',displayOrder:1,enabledModules:['formularios','pesquisas','respostas','relatorios','certificados','lgpd']},
    {id:'essential',name:'Essencial',price:697,priceLabel:'R$ 697',priceComplement:'por mês',badge:'Início estruturado',publicSubtitle:'Para pequenas empresas e equipes.',description:'Para iniciar uma leitura estruturada de maturidade com mais respostas, gestão e relatório.',features:['3 pesquisas ativas','Até 150 respostas/mês','2 gestores','Devolutiva estratégica','Relatório básico'],maxActiveSurveys:3,maxResponsesMonth:150,maxManagers:2,maxCompanies:1,highlighted:false,highlight:false,recommended:false,visibleOnPublicPricing:true,internalOnly:false,isDemo:false,ctaLabel:'Começar diagnóstico',displayOrder:2,default:true,enabledModules:['formularios','pesquisas','respostas','relatorios','certificados','valorabot','lgpd','exportacoes'],allowReports:true,allowStrategicReport:false,allowActionPlans:false,allowWhiteLabel:false,allowValoraBot:true},
    {id:'professional',name:'Profissional',price:1497,priceLabel:'R$ 1.497',priceComplement:'por mês',badge:'Mais escolhido',publicSubtitle:'Para empresas em crescimento.',description:'Para acompanhar cultura, governança, liderança e crescimento com relatórios executivos.',features:['12 pesquisas ativas','Até 1.000 respostas/mês','8 gestores','Relatório executivo','Plano de ação'],maxActiveSurveys:12,maxResponsesMonth:1000,maxManagers:8,maxCompanies:1,highlighted:true,highlight:true,recommended:true,visibleOnPublicPricing:true,internalOnly:false,isDemo:false,ctaLabel:'Evoluir maturidade',displayOrder:3,enabledModules:baseModules,allowReports:true,allowStrategicReport:true,allowActionPlans:true,allowWhiteLabel:false,allowValoraBot:true},
    {id:'corporate',name:'Corporativo',price:3997,priceLabel:'R$ 3.997',priceComplement:'por mês',badge:'Governança avançada',publicSubtitle:'Para múltiplas áreas e unidades.',description:'Para organizações que precisam consolidar diagnósticos, indicadores e planos de evolução.',features:['Pesquisas ilimitadas','Até 10.000 respostas/mês','50 gestores','Múltiplas unidades','Relatórios consolidados'],maxActiveSurveys:-1,maxResponsesMonth:10000,maxManagers:50,maxCompanies:5,highlighted:false,highlight:false,recommended:false,visibleOnPublicPricing:true,internalOnly:false,isDemo:false,ctaLabel:'Estruturar operação',displayOrder:4,enabledModules:[...baseModules,'whiteLabel'],allowReports:true,allowStrategicReport:true,allowActionPlans:true,allowWhiteLabel:true,allowValoraBot:true},
    {id:'enterprise',name:'Enterprise',price:null,priceLabel:'Sob consulta',priceComplement:'projeto consultivo',badge:'Sob medida',publicSubtitle:'Para projetos estratégicos.',description:'Para grupos, redes e consultorias que precisam de implantação assistida e acompanhamento executivo.',features:['Ambiente personalizado','Múltiplas empresas','Reunião estratégica','Relatórios consultivos','Acompanhamento executivo'],maxActiveSurveys:-1,maxResponsesMonth:-1,maxManagers:-1,maxCompanies:-1,highlighted:false,highlight:false,recommended:false,visibleOnPublicPricing:true,internalOnly:false,isDemo:false,requiresConsultativeSale:true,ctaLabel:'Falar com especialista',displayOrder:5,enabledModules:[...baseModules,'whiteLabel'],allowReports:true,allowStrategicReport:true,allowActionPlans:true,allowWhiteLabel:true,allowValoraBot:true}
  ];
}
module.exports={productionPlans};
