namespace Valora.Application.Journey;
public static class JourneyEventTypes{public static readonly IReadOnlySet<string> All=new HashSet<string>(["diagnostic_created","result_calculated","insight_generated","alert_generated","decision_created","action_created","action_completed","evolution_snapshot","report_generated","governance_meeting","cycle_closed","manual_note"]);}
public sealed record JourneyEventDto(Guid Id,string EventType,string Title,string Description,string SourceType,Guid? SourceId,string ImpactLevel,string? RelatedDimension,string? RelatedIndexCode,string EvidenceSummary,DateTime OccurredAt,DateTime CreatedAt);
public sealed record JourneyFilter(DateTime? From,DateTime? To,string? SourceType,string? RelatedDimension,string? RelatedIndexCode,string? ImpactLevel);
public sealed record RegisterJourneyEventRequest(Guid? DiagnosticId,Guid? ResultId,Guid? GovernanceCycleId,string EventType,string Title,string Description,string SourceType,Guid? SourceId,string ImpactLevel,string? RelatedDimension,string? RelatedIndexCode,string EvidenceSummary,DateTime? OccurredAt);
public interface IJourneyRepository{Task<IReadOnlyList<JourneyEventDto>>Timeline(Guid o,JourneyFilter f,CancellationToken c);Task<JourneyEventDto?>Get(Guid o,Guid id,CancellationToken c);Task<Guid>Register(Guid o,Guid u,RegisterJourneyEventRequest r,CancellationToken c);}
public sealed class JourneyService(IJourneyRepository r){public Task<IReadOnlyList<JourneyEventDto>>Timeline(Guid o,JourneyFilter f,CancellationToken c)=>r.Timeline(o,f,c);public Task<JourneyEventDto?>Get(Guid o,Guid id,CancellationToken c)=>r.Get(o,id,c);}
public sealed class JourneyTimelineService(JourneyService s){public Task<IReadOnlyList<JourneyEventDto>>Generate(Guid o,JourneyFilter f,CancellationToken c)=>s.Timeline(o,f,c);}
public sealed class JourneyEventService(IJourneyRepository r){public Task<Guid>Create(Guid o,Guid u,RegisterJourneyEventRequest x,CancellationToken c){if(!JourneyEventTypes.All.Contains(x.EventType))throw new ArgumentException("Tipo de evento inválido.");if(string.IsNullOrWhiteSpace(x.EvidenceSummary))throw new ArgumentException("O evento deve resumir sua evidência.");return r.Register(o,u,x,c);}}
public sealed class RegisterJourneyEventUseCase(JourneyEventService s){public Task<Guid>Execute(Guid o,Guid u,RegisterJourneyEventRequest r,CancellationToken c)=>s.Create(o,u,r,c);}public sealed class GenerateJourneyTimelineUseCase(JourneyTimelineService s){public Task<IReadOnlyList<JourneyEventDto>>Execute(Guid o,JourneyFilter f,CancellationToken c)=>s.Generate(o,f,c);}
