CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE SCHEMA IF NOT EXISTS valora;
CREATE SCHEMA IF NOT EXISTS audit;
CREATE SCHEMA IF NOT EXISTS billing;
CREATE SCHEMA IF NOT EXISTS communication;

CREATE TABLE IF NOT EXISTS valora.organizations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, public_name text, legal_name text, slug text UNIQUE, tax_id text, plan_id text, status text NOT NULL DEFAULT 'active', brand jsonb NOT NULL DEFAULT '{}'::jsonb, settings jsonb NOT NULL DEFAULT '{}'::jsonb, firebase_id text UNIQUE, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_by uuid, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS valora.roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code text NOT NULL UNIQUE, name text NOT NULL, permissions jsonb NOT NULL DEFAULT '[]'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_by uuid, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS valora.users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid REFERENCES valora.organizations(id), firebase_uid text UNIQUE, email text NOT NULL UNIQUE, name text NOT NULL, phone text, position text, department text, role_id uuid REFERENCES valora.roles(id), role_code text, password_hash text, status text NOT NULL DEFAULT 'active', preferences jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_by uuid, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS valora.units (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES valora.organizations(id), name text NOT NULL, code text, status text NOT NULL DEFAULT 'active', metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_by uuid, is_deleted boolean NOT NULL DEFAULT false);

CREATE TABLE IF NOT EXISTS billing.plans (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code text NOT NULL UNIQUE, name text NOT NULL, description text, price_monthly numeric(12,2), currency char(3) NOT NULL DEFAULT 'BRL', display_order int NOT NULL DEFAULT 0, is_public boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_by uuid, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS billing.plan_limits (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), plan_id uuid NOT NULL REFERENCES billing.plans(id), limit_key text NOT NULL, limit_value int NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_by uuid, is_deleted boolean NOT NULL DEFAULT false, UNIQUE(plan_id, limit_key));
CREATE TABLE IF NOT EXISTS billing.plan_capabilities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), plan_id uuid NOT NULL REFERENCES billing.plans(id), capability_key text NOT NULL, enabled boolean NOT NULL DEFAULT false, config jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_by uuid, is_deleted boolean NOT NULL DEFAULT false, UNIQUE(plan_id, capability_key));
CREATE TABLE IF NOT EXISTS billing.subscriptions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES valora.organizations(id), plan_id uuid NOT NULL REFERENCES billing.plans(id), status text NOT NULL DEFAULT 'active', starts_at timestamptz NOT NULL DEFAULT now(), ends_at timestamptz, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_by uuid, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS billing.usage_monthly (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES valora.organizations(id), period_month date NOT NULL, metric_key text NOT NULL, metric_value int NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_by uuid, is_deleted boolean NOT NULL DEFAULT false, UNIQUE(organization_id, period_month, metric_key));

CREATE TABLE IF NOT EXISTS valora.forms (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid REFERENCES valora.organizations(id), title text NOT NULL, description text, is_global boolean NOT NULL DEFAULT false, status text NOT NULL DEFAULT 'draft', firebase_id text UNIQUE, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_by uuid, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS valora.form_dimensions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid REFERENCES valora.organizations(id), form_id uuid NOT NULL REFERENCES valora.forms(id), code text NOT NULL, name text NOT NULL, display_order int NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_by uuid, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS valora.questions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid REFERENCES valora.organizations(id), form_id uuid NOT NULL REFERENCES valora.forms(id), dimension_id uuid REFERENCES valora.form_dimensions(id), text text NOT NULL, question_type text NOT NULL DEFAULT 'scale', weight numeric(8,2) NOT NULL DEFAULT 1, display_order int NOT NULL DEFAULT 0, required boolean NOT NULL DEFAULT true, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_by uuid, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS valora.question_options (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid REFERENCES valora.organizations(id), question_id uuid NOT NULL REFERENCES valora.questions(id), label text NOT NULL, value text NOT NULL, score numeric(8,2), display_order int NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_by uuid, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS valora.surveys (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES valora.organizations(id), form_id uuid NOT NULL REFERENCES valora.forms(id), title text NOT NULL, description text, status text NOT NULL DEFAULT 'draft', starts_at timestamptz, expires_at timestamptz, allow_repeat boolean NOT NULL DEFAULT false, show_result boolean NOT NULL DEFAULT true, lgpd_required boolean NOT NULL DEFAULT true, firebase_id text UNIQUE, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_by uuid, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS valora.survey_links (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES valora.organizations(id), survey_id uuid NOT NULL REFERENCES valora.surveys(id), token_hash text NOT NULL UNIQUE, status text NOT NULL DEFAULT 'active', expires_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_by uuid, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS valora.responses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES valora.organizations(id), survey_id uuid NOT NULL REFERENCES valora.surveys(id), form_id uuid NOT NULL REFERENCES valora.forms(id), participant_user_id uuid REFERENCES valora.users(id), participant_name text, participant_email text, department text, status text NOT NULL DEFAULT 'completed', total_score numeric(10,2), result_level text, result_token_hash text, firebase_id text UNIQUE, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_by uuid, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS valora.response_answers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES valora.organizations(id), response_id uuid NOT NULL REFERENCES valora.responses(id), question_id uuid REFERENCES valora.questions(id), answer_value text, answer_json jsonb, score numeric(10,2), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_by uuid, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS valora.result_scores (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES valora.organizations(id), response_id uuid NOT NULL REFERENCES valora.responses(id), total_score numeric(10,2) NOT NULL, max_score numeric(10,2) NOT NULL DEFAULT 125, level_code text NOT NULL, radar jsonb NOT NULL DEFAULT '{}'::jsonb, strategic_truth text, risk text, next_level text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_by uuid, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS valora.dimension_scores (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES valora.organizations(id), response_id uuid NOT NULL REFERENCES valora.responses(id), dimension_id uuid REFERENCES valora.form_dimensions(id), dimension_code text, score numeric(10,2) NOT NULL, max_score numeric(10,2) NOT NULL DEFAULT 25, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_by uuid, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS valora.certificates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES valora.organizations(id), response_id uuid NOT NULL REFERENCES valora.responses(id), validation_code text NOT NULL UNIQUE, pdf_url text, png_url text, status text NOT NULL DEFAULT 'issued', issued_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_by uuid, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS valora.reports (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES valora.organizations(id), survey_id uuid REFERENCES valora.surveys(id), report_type text NOT NULL, status text NOT NULL DEFAULT 'pending', file_url text, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_by uuid, is_deleted boolean NOT NULL DEFAULT false);

CREATE TABLE IF NOT EXISTS communication.email_jobs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid REFERENCES valora.organizations(id), response_id uuid REFERENCES valora.responses(id), to_email text NOT NULL, subject text NOT NULL, template_key text, payload jsonb NOT NULL DEFAULT '{}'::jsonb, status text NOT NULL DEFAULT 'pending', attempts int NOT NULL DEFAULT 0, last_error text, scheduled_at timestamptz NOT NULL DEFAULT now(), sent_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_by uuid, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS communication.whatsapp_jobs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid REFERENCES valora.organizations(id), response_id uuid REFERENCES valora.responses(id), phone text NOT NULL, template_key text, payload jsonb NOT NULL DEFAULT '{}'::jsonb, status text NOT NULL DEFAULT 'pending', attempts int NOT NULL DEFAULT 0, last_error text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_by uuid, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS communication.communications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid REFERENCES valora.organizations(id), response_id uuid REFERENCES valora.responses(id), channel text NOT NULL, recipient text NOT NULL, status text NOT NULL, attempts int NOT NULL DEFAULT 0, last_error text, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_by uuid, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS audit.audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid REFERENCES valora.organizations(id), actor_user_id uuid REFERENCES valora.users(id), action text NOT NULL, resource_type text NOT NULL, resource_id uuid, ip_address inet, user_agent text, before_data jsonb, after_data jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_by uuid, is_deleted boolean NOT NULL DEFAULT false);
