CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS valorapesquisa.organizations (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, public_name text, slug text NOT NULL UNIQUE, document text, email text, phone text, status text NOT NULL DEFAULT 'active', plan_code text NOT NULL DEFAULT 'free', settings_json jsonb NOT NULL DEFAULT '{}'::jsonb, brand_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_by uuid, is_deleted boolean NOT NULL DEFAULT false, deleted_at timestamptz, deleted_by uuid);
CREATE TABLE IF NOT EXISTS valorapesquisa.users (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NULL REFERENCES valorapesquisa.organizations(id), name text NOT NULL, email text NOT NULL UNIQUE, password_hash text NOT NULL, role text NOT NULL, status text NOT NULL DEFAULT 'active', phone text, last_login_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_by uuid, is_deleted boolean NOT NULL DEFAULT false, deleted_at timestamptz, deleted_by uuid);
CREATE INDEX IF NOT EXISTS ix_users_organization ON valorapesquisa.users(organization_id);

CREATE TABLE IF NOT EXISTS valorapesquisa.units (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES valorapesquisa.organizations(id), name text NOT NULL, slug text, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_by uuid, is_deleted boolean NOT NULL DEFAULT false, deleted_at timestamptz, deleted_by uuid);
ALTER TABLE valorapesquisa.users ADD COLUMN IF NOT EXISTS role_id uuid NULL;
ALTER TABLE valorapesquisa.users ADD COLUMN IF NOT EXISTS phone text NULL;
ALTER TABLE valorapesquisa.users ADD COLUMN IF NOT EXISTS name text NULL;
CREATE TABLE IF NOT EXISTS valorapesquisa.organization_settings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL UNIQUE REFERENCES valorapesquisa.organizations(id), settings jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_by uuid, is_deleted boolean NOT NULL DEFAULT false, deleted_at timestamptz, deleted_by uuid);
