namespace Valora.Application.Workspace;

public sealed class MyDayService(IWorkspaceRepository repository) : IMyDayService { public Task<IReadOnlyList<WorkspaceItemDto>> GetAsync(Guid o, Guid u, bool wide, CancellationToken ct) => repository.MyDayAsync(o,u,wide,ct); }
public sealed class WorkspaceItemService(IWorkspaceRepository repository) : IWorkspaceItemService { public Task PinAsync(Guid o,Guid u,Guid id,CancellationToken ct)=>repository.PinAsync(o,u,id,ct); public Task UnpinAsync(Guid o,Guid u,Guid id,CancellationToken ct)=>repository.UnpinAsync(o,u,id,ct); }
public sealed class RecentItemsService(IWorkspaceRepository repository) : IRecentItemsService { public Task<IReadOnlyList<WorkspaceItemDto>> GetAsync(Guid o,Guid u,CancellationToken ct)=>repository.RecentAsync(o,u,ct); }
public sealed class PinnedItemsService(IWorkspaceRepository repository) : IPinnedItemsService { public Task<IReadOnlyList<WorkspaceItemDto>> GetAsync(Guid o,Guid u,CancellationToken ct)=>repository.PinnedAsync(o,u,ct); }
public sealed class GlobalSearchService(IGlobalSearchRepository repository) : IGlobalSearchService { public async Task<IReadOnlyList<SearchResultDto>> SearchAsync(Guid o,Guid u,string term,bool wide,CancellationToken ct) { term=term.Trim(); if(term.Length<2)return []; var rows=await repository.SearchAsync(o,u,term,wide,ct); await repository.RecordAsync(o,u,term,rows.Count,ct); return rows; } }
public sealed class QuickActionService(IQuickActionRepository repository) : IQuickActionService { public Task<IReadOnlyList<QuickActionDto>> ListAsync(Guid o,CancellationToken ct)=>repository.ListAsync(o,ct); public async Task<QuickActionDto?> ExecuteAsync(Guid o,Guid u,string code,CancellationToken ct){var action=(await repository.ListAsync(o,ct)).FirstOrDefault(x=>x.Code.Equals(code,StringComparison.OrdinalIgnoreCase));if(action is null)return null;await repository.RecordAsync(o,u,action.Code,ct);return action;} }
public sealed class CommandPaletteService(IQuickActionRepository repository) : ICommandPaletteService { public Task<IReadOnlyList<QuickActionDto>> ListAsync(Guid o,CancellationToken ct)=>repository.ListAsync(o,ct); }
public sealed class ExecutivePriorityService(IExecutivePriorityRepository repository) : IExecutivePriorityService { public Task<IReadOnlyList<ExecutivePriorityDto>> ListAsync(Guid o,Guid u,bool wide,CancellationToken ct)=>repository.ListAsync(o,u,wide,ct); public Task<ExecutivePriorityDto> CreateAsync(Guid o,Guid u,CreatePriorityRequest r,CancellationToken ct)=>repository.CreateAsync(o,u,r,ct); }
public sealed class ExecutiveWorkspaceService(IMyDayService day,IExecutivePriorityService priorities,IRecentItemsService recent,IPinnedItemsService pinned,IQuickActionService actions) : IExecutiveWorkspaceService
{ public async Task<ExecutiveWorkspaceDto> GetAsync(Guid o,Guid u,bool wide,CancellationToken ct)=>new(await day.GetAsync(o,u,wide,ct),await priorities.ListAsync(o,u,wide,ct),await recent.GetAsync(o,u,ct),await pinned.GetAsync(o,u,ct),await actions.ListAsync(o,ct)); }
