using Valora.Application.Exceptions;

namespace Valora.Application.Workspace;

public sealed class MyDayService(IWorkspaceRepository repository) : IMyDayService { public Task<IReadOnlyList<WorkspaceItemDto>> GetAsync(Guid o, Guid u, bool wide, CancellationToken ct) => repository.MyDayAsync(o, u, wide, ct); }
public sealed class WorkspaceItemService(IWorkspaceRepository repository) : IWorkspaceItemService { public Task PinAsync(Guid o, Guid u, Guid id, bool wide, CancellationToken ct) { ArgumentOutOfRangeException.ThrowIfEqual(id, Guid.Empty); return repository.PinAsync(o, u, id, wide, ct); } public Task UnpinAsync(Guid o, Guid u, Guid id, CancellationToken ct) { ArgumentOutOfRangeException.ThrowIfEqual(id, Guid.Empty); return repository.UnpinAsync(o, u, id, ct); } public Task RecordOpenAsync(Guid o, Guid u, Guid id, bool wide, CancellationToken ct) { ArgumentOutOfRangeException.ThrowIfEqual(id, Guid.Empty); return repository.RecordOpenAsync(o, u, id, wide, ct); } }
public sealed class RecentItemsService(IWorkspaceRepository repository) : IRecentItemsService { public Task<IReadOnlyList<WorkspaceItemDto>> GetAsync(Guid o, Guid u, bool wide, CancellationToken ct) => repository.RecentAsync(o, u, wide, ct); }
public sealed class PinnedItemsService(IWorkspaceRepository repository) : IPinnedItemsService { public Task<IReadOnlyList<WorkspaceItemDto>> GetAsync(Guid o, Guid u, bool wide, CancellationToken ct) => repository.PinnedAsync(o, u, wide, ct); }
public sealed class GlobalSearchService(IGlobalSearchRepository repository) : IGlobalSearchService { public async Task<IReadOnlyList<SearchResultDto>> SearchAsync(Guid o, Guid u, string term, bool wide, CancellationToken ct) { term = term.Trim(); if (term.Length < 2) return []; var rows = await repository.SearchAsync(o, u, term, wide, ct); await repository.RecordAsync(o, u, term, rows.Count, ct); return rows; } }
public sealed class QuickActionService(IQuickActionRepository repository) : IQuickActionService { public Task<IReadOnlyList<QuickActionDto>> ListAsync(Guid o, CancellationToken ct) => repository.ListAsync(o, ct); public async Task<QuickActionDto?> ExecuteAsync(Guid o, Guid u, string code, CancellationToken ct) { var action = (await repository.ListAsync(o, ct)).FirstOrDefault(x => x.Code.Equals(code, StringComparison.OrdinalIgnoreCase)); if (action is null) return null; await repository.RecordAsync(o, u, action.Code, ct); return action; } }
public sealed class CommandPaletteService(IQuickActionRepository repository) : ICommandPaletteService { public Task<IReadOnlyList<QuickActionDto>> ListAsync(Guid o, CancellationToken ct) => repository.ListAsync(o, ct); }
public sealed class ExecutivePriorityService(IExecutivePriorityRepository repository) : IExecutivePriorityService {
    public Task<IReadOnlyList<ExecutivePriorityDto>> ListAsync(Guid o, Guid u, bool wide, CancellationToken ct) => repository.ListAsync(o, u, wide, ct);
    public Task<PageResult<ExecutivePriorityDto>> ListAsync(Guid o, Guid u, bool wide, PriorityListQuery query, CancellationToken ct) { if(query.Status is not (null or "" or "active" or "completed" or "cancelled") || query.Priority is not (null or "" or "critical" or "high" or "medium" or "low") || query.Due is not (null or "" or "overdue" or "today" or "none")) throw new ValidationAppException("Filtro de prioridades inválido."); return repository.ListAsync(o, u, wide, query, ct); }
    public Task<PriorityDetailsDto?> GetAsync(Guid o, Guid u, Guid id, bool wide, bool manage, CancellationToken ct) => repository.GetAsync(o, u, id, wide, manage, ct);
    public Task<ExecutivePriorityDto> CreateAsync(Guid o, Guid u, CreatePriorityRequest r, CancellationToken ct) { Validate(r); return repository.CreateAsync(o, u, r, ct); }
    public Task<ExecutivePriorityDto> UpdateAsync(Guid o, Guid u, Guid id, UpdatePriorityRequest r, CancellationToken ct) { Validate(r); if(r.ExpectedUpdatedAt==default) throw new ValidationAppException("Informe a versão da prioridade."); return repository.UpdateAsync(o, u, id, r, ct); }
    public Task<PriorityDetailsDto> ProgressAsync(Guid o, Guid u, Guid id, ProgressPriorityRequest r, bool wide, bool manage, CancellationToken ct) { if(r.ProgressPercent is < 0 or > 99 || string.IsNullOrWhiteSpace(r.Note) || r.Note.Trim().Length<2) throw new ValidationAppException("Informe progresso de 0 a 99 e uma observação."); ValidateCommand(r.CommandId,r.ExpectedUpdatedAt); return repository.ProgressAsync(o, u, id, r, wide, manage, ct); }
    public Task<PriorityDetailsDto> TransitionAsync(Guid o, Guid u, Guid id, string command, TransitionPriorityRequest r, bool wide, bool manage, CancellationToken ct) { if(command is not ("complete" or "cancel" or "reopen") || string.IsNullOrWhiteSpace(r.Justification) || r.Justification.Trim().Length<3) throw new ValidationAppException("Informe uma justificativa válida para a transição."); ValidateCommand(r.CommandId,r.ExpectedUpdatedAt); return repository.TransitionAsync(o, u, id, command, r, wide, manage, ct); }
    public Task<PageResult<PriorityOptionDto>> OwnersAsync(Guid o, OptionQuery query, CancellationToken ct) => repository.OwnersAsync(o, query, ct);
    public Task<PageResult<PrioritySourceOptionDto>> SourcesAsync(Guid o, Guid u, bool wide, OptionQuery query, CancellationToken ct) => repository.SourcesAsync(o, u, wide, query, ct);
    private static void ValidateCommand(string commandId,DateTimeOffset expected) { if(string.IsNullOrWhiteSpace(commandId) || commandId.Length>80 || expected==default) throw new ValidationAppException("Identificação e versão do comando são obrigatórias."); }
    private static void Validate(CreatePriorityRequest request) {
        if(string.IsNullOrWhiteSpace(request.Title) || request.Title.Trim().Length is < 3 or > 180) throw new ValidationAppException("O título deve ter entre 3 e 180 caracteres.");
        if(request.Description?.Length>2000) throw new ValidationAppException("A descrição deve ter até 2.000 caracteres.");
        if(request.Priority is not ("critical" or "high" or "medium" or "low")) throw new ValidationAppException("Nível de prioridade inválido.");
        if(request.SourceId.HasValue != !string.IsNullOrWhiteSpace(request.SourceType)) throw new ValidationAppException("Informe tipo e recurso de origem em conjunto.");
    }
}
public sealed class ExecutiveWorkspaceService(IMyDayService day, IExecutivePriorityService priorities, IRecentItemsService recent, IPinnedItemsService pinned, IQuickActionService actions) : IExecutiveWorkspaceService { public async Task<ExecutiveWorkspaceDto> GetAsync(Guid o, Guid u, bool wide, CancellationToken ct) => new(await day.GetAsync(o, u, wide, ct), await priorities.ListAsync(o, u, wide, ct), await recent.GetAsync(o, u, wide, ct), await pinned.GetAsync(o, u, wide, ct), await actions.ListAsync(o, ct)); }
