namespace Valora.Application.SecurityCompliance;

public sealed record PrivacyConsent(Guid Id, Guid OrganizationId, Guid? UserId, Guid? RespondentId, string ConsentType, string ConsentVersion, string Status, DateTimeOffset? GrantedAt, DateTimeOffset? RevokedAt, string Source, DateTimeOffset CreatedAt);
public sealed record DataSubjectRequest(Guid Id, Guid OrganizationId, string RequesterEmail, string RequestType, string Status, string Description, DateTimeOffset DueAt, Guid? HandledByUserId, DateTimeOffset CreatedAt);
public sealed record RetentionPolicy(Guid Id, Guid OrganizationId, string DataCategory, int RetentionDays, string ExpirationAction, Guid? ResponsibleUserId, DateTimeOffset? LastRunAt);
public sealed record SecurityIncident(Guid Id, Guid OrganizationId, string Severity, string Status, string IncidentType, string Title, string EvidenceSummary, DateTimeOffset DetectedAt);
public sealed record AccessReviewCycle(Guid Id, Guid OrganizationId, string Title, string Status, DateTimeOffset DueAt);
public sealed record ComplianceAuditEvent(Guid OrganizationId, Guid? ActorUserId, string EventType, string? ResourceType, string? ResourceId, string Outcome, string EvidenceJson, string? CorrelationId);

public interface IPrivacyConsentRepository { Task<PrivacyConsent> RegisterAsync(Guid organizationId, Guid? userId, Guid? respondentId, string type, string version, string source, string? ipAddress, string? userAgent, CancellationToken ct); Task RevokeAsync(Guid organizationId, Guid consentId, Guid actorUserId, CancellationToken ct); }
public interface IDataSubjectRequestRepository { Task<DataSubjectRequest> CreateAsync(Guid organizationId, Guid? requesterUserId, string requesterEmail, string requestType, string description, DateTimeOffset dueAt, CancellationToken ct); Task CompleteAsync(Guid organizationId, Guid requestId, Guid handlerUserId, string summary, CancellationToken ct); }
public interface IDataRetentionRepository { Task<RetentionPolicy> ConfigureAsync(Guid organizationId, string category, int days, string action, Guid responsibleUserId, CancellationToken ct); Task<Guid> StartJobAsync(Guid organizationId, Guid policyId, CancellationToken ct); }
public interface ISecurityIncidentRepository { Task<SecurityIncident> RegisterAsync(Guid organizationId, string severity, string type, string title, string description, string evidence, Guid? assignee, CancellationToken ct); Task ResolveAsync(Guid organizationId, Guid incidentId, Guid actorUserId, string resolution, CancellationToken ct); }
public interface IAccessReviewRepository { Task<AccessReviewCycle> StartAsync(Guid organizationId, string title, Guid actorUserId, DateTimeOffset dueAt, CancellationToken ct); Task CompleteAsync(Guid organizationId, Guid cycleId, Guid actorUserId, CancellationToken ct); }
public interface IComplianceAuditRepository { Task AppendAsync(ComplianceAuditEvent auditEvent, CancellationToken ct); Task LogSensitiveAccessAsync(Guid organizationId, Guid? actorUserId, string category, string resourceType, string resourceId, string purpose, string decision, string? correlationId, CancellationToken ct); }

public sealed class PrivacyConsentService(IPrivacyConsentRepository repository) { public Task<PrivacyConsent> RegisterAsync(Guid org, Guid? user, Guid? respondent, string type, string version, string source, string? ip, string? ua, CancellationToken ct=default) { RequireOrg(org); if(string.IsNullOrWhiteSpace(type)||string.IsNullOrWhiteSpace(version)) throw new ArgumentException("Tipo e versão do consentimento são obrigatórios."); return repository.RegisterAsync(org,user,respondent,type,version,source,ip,ua,ct); } public Task RevokeAsync(Guid org, Guid id, Guid actor, CancellationToken ct=default) { RequireOrg(org); return repository.RevokeAsync(org,id,actor,ct); } private static void RequireOrg(Guid id) { if(id==Guid.Empty) throw new ArgumentException("Organização é obrigatória."); } }
public sealed class DataSubjectRequestService(IDataSubjectRequestRepository repository) { private static readonly HashSet<string> Types=["access","correction","erasure","anonymization","portability"]; public Task<DataSubjectRequest> CreateAsync(Guid org,Guid? user,string email,string type,string description,int dueDays=15,CancellationToken ct=default){if(org==Guid.Empty||!Types.Contains(type)||string.IsNullOrWhiteSpace(email))throw new ArgumentException("Solicitação LGPD inválida."); return repository.CreateAsync(org,user,email.Trim(),type,description,DateTimeOffset.UtcNow.AddDays(Math.Clamp(dueDays,1,30)),ct);} public Task CompleteAsync(Guid org,Guid id,Guid handler,string summary,CancellationToken ct=default)=>repository.CompleteAsync(org,id,handler,summary,ct); }
public sealed class DataRetentionService(IDataRetentionRepository repository) { private static readonly HashSet<string> Actions=["anonymize","archive","soft_delete"]; public Task<RetentionPolicy> ConfigureAsync(Guid org,string category,int days,string action,Guid responsible,CancellationToken ct=default){if(org==Guid.Empty||days<1||!Actions.Contains(action))throw new ArgumentException("Política de retenção inválida.");return repository.ConfigureAsync(org,category,days,action,responsible,ct);} public Task<Guid> RunAsync(Guid org,Guid policy,CancellationToken ct=default)=>repository.StartJobAsync(org,policy,ct); }
public sealed class SecurityIncidentService(ISecurityIncidentRepository repository) { private static readonly HashSet<string> Severities=["critical","high","medium","low","info"]; public Task<SecurityIncident> RegisterAsync(Guid org,string severity,string type,string title,string description,string evidence,Guid? assignee,CancellationToken ct=default){if(!Severities.Contains(severity)||string.IsNullOrWhiteSpace(evidence))throw new ArgumentException("Severidade e evidência válida são obrigatórias.");return repository.RegisterAsync(org,severity,type,title,description,evidence,assignee,ct);} public Task ResolveAsync(Guid org,Guid id,Guid actor,string resolution,CancellationToken ct=default)=>repository.ResolveAsync(org,id,actor,resolution,ct); }
public sealed class AccessReviewService(IAccessReviewRepository repository) { public Task<AccessReviewCycle> StartAsync(Guid org,string title,Guid actor,DateTimeOffset due,CancellationToken ct=default)=>repository.StartAsync(org,title,actor,due,ct); public Task CompleteAsync(Guid org,Guid id,Guid actor,CancellationToken ct=default)=>repository.CompleteAsync(org,id,actor,ct); }
public sealed class ComplianceAuditService(IComplianceAuditRepository repository) { public Task LogAsync(ComplianceAuditEvent value,CancellationToken ct=default)=>repository.AppendAsync(value,ct); }
public sealed class SensitiveAccessLogService(IComplianceAuditRepository repository) { public Task LogAsync(Guid org,Guid? actor,string category,string resourceType,string resourceId,string purpose,bool allowed,string? correlationId,CancellationToken ct=default)=>repository.LogSensitiveAccessAsync(org,actor,category,resourceType,resourceId,purpose,allowed?"allowed":"denied",correlationId,ct); }

public sealed class RegisterPrivacyConsentUseCase(PrivacyConsentService service) { public Task<PrivacyConsent> ExecuteAsync(Guid o,Guid? u,Guid? r,string t,string v,string s,string? ip,string? ua,CancellationToken ct=default)=>service.RegisterAsync(o,u,r,t,v,s,ip,ua,ct); }
public sealed class RevokePrivacyConsentUseCase(PrivacyConsentService service) { public Task ExecuteAsync(Guid o,Guid id,Guid actor,CancellationToken ct=default)=>service.RevokeAsync(o,id,actor,ct); }
public sealed class CreateDataSubjectRequestUseCase(DataSubjectRequestService service) { public Task<DataSubjectRequest> ExecuteAsync(Guid o,Guid? u,string e,string t,string d,CancellationToken ct=default)=>service.CreateAsync(o,u,e,t,d,15,ct); }
public sealed class CompleteDataSubjectRequestUseCase(DataSubjectRequestService service) { public Task ExecuteAsync(Guid o,Guid id,Guid actor,string summary,CancellationToken ct=default)=>service.CompleteAsync(o,id,actor,summary,ct); }
public sealed class ConfigureRetentionPolicyUseCase(DataRetentionService service) { public Task<RetentionPolicy> ExecuteAsync(Guid o,string c,int d,string a,Guid r,CancellationToken ct=default)=>service.ConfigureAsync(o,c,d,a,r,ct); }
public sealed class RunRetentionJobUseCase(DataRetentionService service) { public Task<Guid> ExecuteAsync(Guid o,Guid p,CancellationToken ct=default)=>service.RunAsync(o,p,ct); }
public sealed class RegisterSecurityIncidentUseCase(SecurityIncidentService service) { public Task<SecurityIncident> ExecuteAsync(Guid o,string s,string t,string title,string d,string e,Guid? a,CancellationToken ct=default)=>service.RegisterAsync(o,s,t,title,d,e,a,ct); }
public sealed class ResolveSecurityIncidentUseCase(SecurityIncidentService service) { public Task ExecuteAsync(Guid o,Guid id,Guid actor,string r,CancellationToken ct=default)=>service.ResolveAsync(o,id,actor,r,ct); }
public sealed class StartAccessReviewCycleUseCase(AccessReviewService service) { public Task<AccessReviewCycle> ExecuteAsync(Guid o,string t,Guid a,DateTimeOffset due,CancellationToken ct=default)=>service.StartAsync(o,t,a,due,ct); }
public sealed class CompleteAccessReviewCycleUseCase(AccessReviewService service) { public Task ExecuteAsync(Guid o,Guid id,Guid a,CancellationToken ct=default)=>service.CompleteAsync(o,id,a,ct); }
public sealed class LogSensitiveDataAccessUseCase(SensitiveAccessLogService service) { public Task ExecuteAsync(Guid o,Guid? a,string c,string rt,string id,string p,bool allowed,string? correlation,CancellationToken ct=default)=>service.LogAsync(o,a,c,rt,id,p,allowed,correlation,ct); }
