namespace Valora.Application.DTOs;
public record RegisterCompanyRequest(string Name,string CompanyName,string Email,string Password);
public record LoginRequest(string Email,string Password);
public record AuthResponse(string Token, object User, object? Organization, object? Plan);
public record PlanDto(string Id,string Name,string? Badge,string PriceLabel,string? PriceComplement,int DisplayOrder,Dictionary<string,int> Limits,Dictionary<string,string> Capabilities);
public record UsageDto(int ActiveSurveys,int ResponsesThisMonth,int Managers,Dictionary<string,int> Limits);
public record PlanEntitlements(string PlanId,Dictionary<string,int> Limits,Dictionary<string,string> Capabilities);
public record LimitCheckResult(bool Allowed,string LimitKey,int LimitValue,int CurrentUsage,int RequestedAmount);
public record AuditEntry(Guid? OrganizationId,Guid? UserId,string Action,string? EntityType,string? EntityId,string? Message,string MetadataJson="{}");
public record UpdateOrganizationRequest(string? PublicName,string? Phone,string? Document);
public record SubmitResponseRequest(string? ParticipantName,string? ParticipantEmail,Dictionary<string,object>? Answers);
