namespace Valora.Application.DTOs;
public sealed record EntitlementCheckResult(bool Allowed,string? Code,string Message);
public sealed record ReportDefinitionDto(Guid Id,string Code,string Name,string? Description,string ReportType,string RequiredModuleCode,string? MinimumPlanCode,string Status);
public sealed record GeneratedReportDto(Guid Id,Guid OrganizationId,Guid? SurveyId,Guid? ResponseId,string Title,string Format,string Status,string PayloadJson,string? FileName,string? MimeType,DateTimeOffset CreatedAt);
public sealed record GenerateReportRequest(string Format = "html", Guid? ReportDefinitionId = null);
public sealed record CertificateDto(Guid Id,Guid OrganizationId,Guid? SurveyId,Guid ResponseId,string? ParticipantName,string? ParticipantEmailMasked,string? CompanyName,decimal? TotalScore,string? Level,string ValidationCode,string? ValidationUrl,string Status,DateTimeOffset? IssuedAt,string PayloadJson);
public sealed record CertificateValidationDto(bool Valid,string Status,string ValidationCode,string? ParticipantName,string? CompanyName,string? Level,DateTimeOffset? IssuedAt);
public sealed record ExportJobDto(Guid Id,Guid OrganizationId,Guid? RequestedBy,string Entity,string Format,string Status,string? ResultFileName,string? ResultMimeType,string? ResultPayload,DateTimeOffset CreatedAt,DateTimeOffset? CompletedAt,string? ErrorMessage);
public sealed record ExportRequest(string Entity,string Format = "csv", string? FilterJson = null);
public sealed record LgpdConsentDto(Guid Id,Guid? OrganizationId,Guid? SurveyId,Guid? ResponseId,string ConsentVersion,bool Accepted,DateTimeOffset? AcceptedAt,DateTimeOffset CreatedAt);
public sealed record RegisterLgpdConsentRequest(Guid? OrganizationId,Guid? SurveyId,Guid? ResponseId,string? ParticipantEmail,string ConsentText,string ConsentVersion,bool Accepted);
public sealed record PrivacyRequestDto(Guid Id,Guid? OrganizationId,string RequesterEmailMasked,string RequestType,string Protocol,string Status,string? Description,Guid? ResponseId,DateTimeOffset RequestedAt,DateTimeOffset? CompletedAt,string? ResultJson);
public sealed record CreatePrivacyRequestRequest(Guid? OrganizationId,string RequesterEmail,string RequestType,string? Description,Guid? ResponseId);
public sealed record UpdatePrivacyRequestStatusRequest(string Status);
public sealed record CompletePrivacyRequestRequest(string ResultJson);
public sealed record EmailTemplateDto(Guid Id,Guid? OrganizationId,string Code,string Name,string Subject,string BodyHtml,string? BodyText,string Status);
public sealed record UpsertEmailTemplateRequest(Guid? OrganizationId,string Code,string Name,string Subject,string BodyHtml,string? BodyText,string Status = "active");
public sealed record EmailJobDto(Guid Id,Guid? OrganizationId,Guid? ResponseId,Guid? CertificateId,string TemplateCode,string FromEmail,string FromName,string ToEmailMasked,string Subject,string Status,int Attempts,DateTimeOffset? NextAttemptAt,DateTimeOffset? LastAttemptAt,DateTimeOffset? SentAt,string? DeadLetterReason,DateTimeOffset CreatedAt);
public sealed record EmailStatusDto(int Queued,int Processing,int Sent,int Failed,int DeadLetter,bool DevelopmentOutbox);
