namespace Valora.Web.Navigation;

// Bloco B — consolidação de navegação: 7 áreas do cliente + ADMINISTRAÇÃO GLOBAL.
// Reuso canônico: uma URL canônica por funcionalidade; itens removidos do menu
// passam a existir apenas como redirects GET seguros nos controladores
// (registro das remoções em EVO_A1_STABILIZATION_REGISTER.md §11).
// Menu oculto ≠ autorização: a visibilidade aqui é UX; a autorização segue
// server-side (policies/papéis dos controladores), inalterada.
public sealed class NavigationCatalog {
    private static readonly IReadOnlySet<string> Administrators = Roles("admin_valora", "consultor_valora", "empresa_admin");
    private static readonly IReadOnlySet<string> Diagnostics = Roles("admin_valora", "consultor_valora", "empresa_admin", "gestor_pesquisa");
    private static readonly IReadOnlySet<string> Results = Roles("admin_valora", "consultor_valora", "empresa_admin", "gestor_pesquisa", "analista_resultados", "gestor_area");

    public IReadOnlyList<NavigationSection> Sections { get; } =
    [
        Section("executive", "Visão Executiva", 10,
            Item("valora.overview", "Visão Geral Valora", "Carteira, CRM e operação SaaS", "Enterprise", "sparkles", null, null, "enterprise", null, 0, Roles("admin_valora")),
            Item("executive.overview", "Visão Geral", "Indicadores e prioridades da organização", "Dashboard", "layout-dashboard", null, null, "dashboard", null, 10, Results),
            ItemAction("workspace.overview", "Workspace", "Seu centro de comando executivo diário", "Workspace", "Index", "layout-dashboard", "dashboard", 20, Results),
            ItemAction("workspace.my-day", "Meu Dia", "Prazos, aprovações e sinais que pedem atenção", "Workspace", "MyDay", "check-circle", "dashboard", 30, Results),
            ItemAction("execution.priorities", "Prioridades", "Compromissos executivos, responsáveis, prazos e vínculos com a execução", "Workspace", "Priorities", "activity", "dashboard", 40, Results),
            ItemAction("executive.cockpit", "Cockpit Executivo", "Riscos, tendências e prioridades da alta gestão", "Experience", "Cockpit", "chart-radar", "results", 50, Results),
            ItemAction("workspace.search", "Busca Global", "Encontre evidências e entregáveis no contexto autorizado", "Search", "Index", "search", "dashboard", 60, Results)),
        Section("diagnostics", "Diagnóstico", 20,
            ItemAction("diagnostics.onboarding", "Onboarding", "Configuração guiada da organização e do primeiro ciclo", "Onboarding", "Index", "building", "organization", 0, Administrators),
            ItemAction("diagnostics.new", "Novo Diagnóstico", "Assistente para configurar o próximo ciclo", "Diagnostics", "New", "plus", "forms", 10, Diagnostics),
            ItemAction("diagnostics.cycles", "Ciclos Diagnósticos", "Coleta, processamento e workspace", "Diagnostics", "Index", "activity", "surveys", 20, Diagnostics),
            Item("diagnostics.forms", "Formulários", "Crie e publique diagnósticos", "Forms", "file-text", null, "forms", "forms", "organization", 30, Diagnostics),
            Item("diagnostics.surveys", "Pesquisas", "Configure campanhas, períodos e distribuição", "Surveys", "file-question", null, "surveys", "surveys", "organization", 40, Diagnostics),
            ItemAction("diagnostics.campaigns", "Campanhas", "Envio, adesão e lembretes", "Experience", "Campaigns", "message-circle", "surveys", 50, Diagnostics),
            ItemAction("structure.audiences", "Públicos e Segmentações", "Privacidade e públicos dos diagnósticos", "Diagnostics", "Audiences", "users", "surveys", 60, Diagnostics),
            Item("diagnostics.responses", "Respostas", "Acompanhe a participação", "Responses", "activity", "canViewResponses", "responses", "responses", "organization", 70, Results),
            ItemAction("diagnostics.templates", "Templates", "Biblioteca oficial Valora", "Experience", "Templates", "layers", "forms", 80, Diagnostics)),
        Section("results", "Resultados", 30,
            Item("intelligence.results", "Resultados", "Devolutivas e análises executivas", "Results", "chart-radar", null, "results", "results", "organization", 10, Results),
            ItemAction("intelligence.comparisons", "Comparativos", "Evolução entre ciclos e áreas", "OperationalIntelligence", "Comparisons", "activity", "results", 20, Results),
            ItemAction("intelligence.historical", "Evolução Histórica", "Variações reais entre diagnósticos", "Intelligence", "Evolution", "activity", "organizational_intelligence", 30, Results),
            ItemAction("intelligence.recommendations", "Recomendações", "Prioridades orientadas por evidências", "OperationalIntelligence", "Recommendations", "sparkles", "results", 40, Results),
            ItemAction("intelligence.executive-report", "Executive Reports™", "Preview executivo rastreável", "Intelligence", "ExecutiveReport", "file-text", "organizational_intelligence", 50, Results),
            Item("intelligence.reports", "Relatórios", "Central de entregas executivas", "Reports", "file-text", null, null, "reports", "organization", 60, Results),
            Item("intelligence.certificates", "Certificados", "Emissão e reimpressão", "Certificates", "certificate", null, "certificates", "certificates", "organization", 70, Results)),
        Section("intelligence", "Inteligência", 40,
            ItemAction("people.overview", "People", "Cultura, liderança e desenvolvimento baseados em evidências", "People", "Index", "users", "organizational_intelligence", 0, Results),
            ItemAction("people.teams", "Teams", "Times, vínculos e lideranças responsáveis", "People", "Teams", "users", "organizational_intelligence", 1, Results),
            ItemAction("people.culture", "Culture", "Dimensões agregadas, fontes e limitações", "People", "Culture", "activity", "organizational_intelligence", 2, Results),
            ItemAction("people.engagement", "Engagement", "Sinais agregados sem conclusões individuais", "People", "Engagement", "chart-radar", "organizational_intelligence", 3, Results),
            ItemAction("people.competencies", "Competencies", "Lacunas com evidência e revisão humana", "People", "Competencies", "layers", "organizational_intelligence", 4, Results),
            ItemAction("people.development", "Development Plans", "Ações, responsáveis, prazos e evidências", "People", "DevelopmentPlans", "check-circle", "organizational_intelligence", 5, Results),
            ItemAction("people.risks", "Risks", "Sinais preventivos com revisão humana", "People", "Risks", "shield", "organizational_intelligence", 6, Results),
            ItemAction("intelligence.knowledge", "Knowledge Center", "Conhecimento, playbooks e aprendizagem organizacional", "Knowledge", "Index", "book-open", "organizational_intelligence", 10, Results),
            ItemAction("intelligence.advisor", "Valora Advisor™", "Inteligência organizacional baseada em evidências", "Advisor", "Index", "sparkles", "organizational_intelligence", 11, Results),
            ItemAction("intelligence.architecture", "Architecture Studio", "Áreas, processos, decisões e dependências como sistema vivo", "Architecture", "Index", "layers", "organizational_intelligence", 12, Results),
            Item("intelligence.organizational", "Inteligência Organizacional", "Dashboard, Heatmap, Evolution, Journey e Action Valora™", "Intelligence", "brain", "organizational_intelligence.read", "organizational_intelligence", "organizational_intelligence", "organization", 15, Results),
            ItemAction("intelligence.hub-generate", "Gerar análise IA", "Evidence pack e interpretação revisável", "Intelligence", "Generate", "sparkles", "intelligence", 16, Results),
            ItemAction("intelligence.hub-review", "Revisão de IA", "Fila de validação humana e guardrails", "Intelligence", "Review", "shield", "intelligence", 17, Results),
            ItemAction("intelligence.methodology-mappings", "Mapeamento Metodológico", "Cobertura de perguntas, Metrics e Índices", "Methodology", "Mappings", "layers", "organizational_intelligence", 18, Diagnostics),
            ItemAction("intelligence.processing", "Centro de Processamento", "Fila, etapas, falhas e reprocessamentos", "Intelligence", "Processing", "activity", "organizational_intelligence", 19, Administrators),
            ItemAction("intelligence.evidence", "Evidências", "Origem verificável das leituras", "Intelligence", "Evidence", "activity", "organizational_intelligence", 20, Results),
            ItemAction("intelligence.metrics", "Metrics™", "Indicadores com contexto e evidência", "Intelligence", "Metrics", "chart-radar", "organizational_intelligence", 21, Results),
            ItemAction("intelligence.indices", "Índices Valora™", "Índices oficiais e composição", "Intelligence", "Indices", "layers", "organizational_intelligence", 22, Results),
            ItemAction("intelligence.inference", "Motor de Inferência", "Hipóteses e regras rastreáveis", "Intelligence", "Inference", "brain", "organizational_intelligence", 23, Results),
            ItemAction("intelligence.insights", "Insights IA™", "Leituras sustentadas por evidências", "Intelligence", "Insights", "sparkles", "organizational_intelligence", 24, Results),
            ItemAction("intelligence.radar", "Radar™", "Equilíbrio sistêmico", "Intelligence", "Radar", "chart-radar", "organizational_intelligence", 25, Results),
            ItemAction("intelligence.heatmap", "Heatmap™", "Mapa de atenção", "Intelligence", "Heatmap", "layout-dashboard", "organizational_intelligence", 26, Results),
            ItemAction("intelligence.benchmark", "Benchmark", "Maturidade e posicionamento estratégico", "Intelligence", "Benchmark", "activity", "organizational_intelligence", 27, Results),
            ItemAction("intelligence.one-on-one", "One-on-One™", "Conversas e compromissos responsáveis", "OneOnOne", "Index", "users", "organizational_intelligence", 28, Results),
            ItemAction("intelligence.leadership", "Lideranças", "Desenvolvimento baseado em evidências", "Leadership", "Index", "users", "organizational_intelligence", 29, Results)),
        Section("execution", "Execução & Evolução", 50,
            ItemAction("execution.action-center", "Central de ações", "Riscos, prazos e execução rastreável", "ActionCenter", "Index", "activity", "organizational_intelligence", 10, Results),
            ItemAction("execution.plans", "Planos de Ação", "Planos sustentados por evidências", "ActionCenter", "Plans", "layers", "organizational_intelligence", 20, Results),
            ItemAction("execution.items", "Ações", "Compromissos, responsáveis e check-ins", "ActionCenter", "Items", "shield", "organizational_intelligence", 30, Results),
            ItemAction("intelligence.actions", "Valora Action™", "Compromissos conectados a capacidade, indicador e evidência", "Intelligence", "Action", "layers", "organizational_intelligence", 40, Results),
            ItemAction("execution.evolution", "Evolução", "Capacidade e mudança de padrão", "Evolution", "Index", "chart-radar", "organizational_intelligence", 50, Results),
            ItemAction("execution.cycles", "Ciclos de Evolução", "Baselines e snapshots preservados", "Evolution", "Cycles", "activity", "organizational_intelligence", 60, Results),
            ItemAction("execution.journey", "Histórico", "Memória executiva da organização", "Journey", "Index", "file-text", "organizational_intelligence", 70, Results)),
        Section("governance", "Risco & Governança", 60,
            ItemAction("risk.overview", "Risk & Compliance", "Centro executivo de riscos, controles e conformidade", "RiskCompliance", "Index", "shield", "organizational_intelligence", 10, Results),
            ItemAction("risk.risks", "Risks", "Registro de riscos e confiança das evidências", "RiskCompliance", "Risks", "activity", "organizational_intelligence", 11, Results),
            ItemAction("risk.heatmap", "Heatmap", "Probabilidade, impacto e criticidade", "RiskCompliance", "Heatmap", "chart-radar", "organizational_intelligence", 12, Results),
            ItemAction("risk.controls", "Controls", "Controles internos e testes de efetividade", "RiskCompliance", "Controls", "check-circle", "organizational_intelligence", 13, Results),
            ItemAction("risk.compliance", "Compliance", "Frameworks, requisitos e aderência evidenciada", "RiskCompliance", "Compliance", "shield", "organizational_intelligence", 14, Results),
            ItemAction("risk.nonconformities", "Non-Conformities", "Causas, impactos e correções rastreáveis", "RiskCompliance", "NonConformities", "activity", "organizational_intelligence", 15, Results),
            ItemAction("risk.mitigation", "Mitigation Plans", "Responsáveis, prazos, ações e evidências", "RiskCompliance", "MitigationPlans", "layers", "organizational_intelligence", 16, Results),
            ItemAction("risk.audits", "Audits", "Revisões, achados e recomendações", "RiskCompliance", "Audits", "file-text", "organizational_intelligence", 17, Results),
            ItemAction("decision.center", "Decision Center", "Visão executiva de alertas, decisões e evolução", "DecisionCenter", "Index", "layout-dashboard", "organizational_intelligence", 30, Results),
            ItemAction("decision.alerts", "Alertas Inteligentes", "Sinais sustentados por evidências", "DecisionCenter", "Alerts", "activity", "organizational_intelligence", 31, Results),
            ItemAction("decision.decisions", "Decisões", "Decisões humanas rastreáveis", "Decisions", "Index", "shield", "organizational_intelligence", 32, Results),
            ItemAction("decision.indicators", "Indicadores", "Estratégicos, táticos e operacionais", "Indicators", "Index", "chart-radar", "organizational_intelligence", 33, Results),
            ItemAction("decision.cycles", "Ciclos de Governança", "Do diagnóstico à aprendizagem", "Governance", "Cycles", "layers", "organizational_intelligence", 34, Results),
            ItemAction("decision.meetings", "Reuniões de Governança", "Pautas, decisões e próximos passos", "Governance", "Meetings", "users", "organizational_intelligence", 35, Results),
            ItemAction("benchmarks.overview", "Benchmarks", "Inteligência comparativa anônima e auditável", "Benchmarks", "Index", "chart-radar", "organizational_intelligence", 50, Results),
            ItemAction("benchmarks.compare", "Compare", "Histórico, unidades e coortes anônimas", "Benchmarks", "Compare", "activity", "organizational_intelligence", 51, Results),
            ItemAction("benchmarks.cohorts", "Cohorts", "Segmentos, portes e amostras protegidas", "Benchmarks", "Cohorts", "users", "organizational_intelligence", 52, Administrators),
            ItemAction("benchmarks.insights", "Insights comparativos", "Oportunidades sustentadas por evidência", "Benchmarks", "Insights", "sparkles", "organizational_intelligence", 53, Results),
            ItemAction("benchmarks.privacy", "Privacy", "Anonimização, bloqueios e auditoria", "Benchmarks", "Privacy", "shield", "organizational_intelligence", 54, Administrators),
            ItemAction("processes.overview", "Processes", "Processos executáveis, auditáveis e monitoráveis", "Processes", "Index", "layers", "organizational_intelligence", 60, Results),
            ItemAction("processes.definitions", "Definitions", "Catálogo, versões e responsáveis", "Processes", "Definitions", "file-text", "organizational_intelligence", 61, Results),
            ItemAction("processes.builder", "Builder", "Etapas, transições, SLA e evidências", "Processes", "Builder", "layers", "organizational_intelligence", 62, Administrators),
            ItemAction("processes.instances", "Instances", "Execuções e prazos em andamento", "Processes", "Instances", "activity", "organizational_intelligence", 63, Results),
            ItemAction("processes.approvals", "Approvals", "Decisões humanas pendentes", "Processes", "Approvals", "check-circle", "organizational_intelligence", 64, Results),
            ItemAction("processes.sla", "SLA", "Riscos e atrasos por processo", "Processes", "Sla", "activity", "organizational_intelligence", 65, Results),
            ItemAction("processes.insights", "Insights", "Gargalos sustentados por histórico", "Processes", "Insights", "sparkles", "organizational_intelligence", 66, Results),
            ItemAction("processes.templates", "Templates", "Modelos adaptáveis à organização", "Processes", "Templates", "layers", "organizational_intelligence", 67, Administrators)),
        Section("organization", "Organização & Segurança", 70,
            ItemAction("admin.hub", "Admin Hub", "Organizações, unidades, usuários, acessos e governança", "AdminHub", "Index", "shield", "operations", 0, Administrators),
            ItemAction("structure.tree", "Estrutura Organizacional", "Unidades, áreas, departamentos e lideranças", "Organization", "Structure", "layers", "organization", 10, Administrators),
            ItemAction("administration.users", "Usuários", "Contas, vínculos e situação de acesso", "Users", "Index", "users", "users", 20, Administrators),
            ItemAction("administration.roles", "Perfis e papéis", "Responsabilidades e conjuntos de acesso", "Users", "Roles", "shield", "users", 21, Administrators),
            ItemAction("administration.permissions", "Permissões e acessos", "Permissões efetivas por papel e escopo", "Users", "Permissions", "shield", "users", 22, Administrators),
            ItemAction("administration.benchmark", "Configuração de Benchmark", "Amostra mínima, referências e anonimização", "Intelligence", "BenchmarkAdministration", "activity", "organizational_intelligence", 30, Administrators),
            ItemAction("security.overview", "Segurança e Compliance", "LGPD, auditoria e governança de dados", "SecurityCompliance", "Index", "shield", "identity", 40, Administrators),
            ItemAction("security.privacy", "Privacidade e LGPD", "Consentimentos e configurações", "SecurityCompliance", "Privacy", "shield", "identity", 41, Administrators),
            ItemAction("security.requests", "Solicitações de Titulares", "Direitos dos titulares", "SecurityCompliance", "DataRequests", "users", "identity", 42, Administrators),
            ItemAction("security.retention", "Retenção de Dados", "Políticas e execuções", "SecurityCompliance", "Retention", "layers", "identity", 43, Administrators),
            ItemAction("security.audit", "Auditoria de Compliance", "Eventos e evidências", "SecurityCompliance", "Audit", "activity", "identity", 44, Administrators),
            ItemAction("security.incidents", "Incidentes de Segurança", "Resposta e resolução", "SecurityCompliance", "Incidents", "activity", "identity", 45, Administrators),
            ItemAction("security.reviews", "Revisão de Acessos", "Ciclos periódicos", "SecurityCompliance", "AccessReviews", "users", "identity", 46, Administrators),
            ItemAction("security.sensitive", "Acessos Sensíveis", "Finalidade e decisão", "SecurityCompliance", "SensitiveAccess", "shield", "identity", 47, Administrators),
            ItemAction("security.api-keys", "Chaves de API", "Credenciais, escopos e revogação", "SecurityCompliance", "ApiKeys", "key", "identity", 48, Administrators),
            Item("administration.plans", "Planos e Uso", "Recursos, limites e consumo atual", "Plans", "credit-card", null, null, "plans", "organization", 55, Administrators),
            Item("administration.communications", "Communication Center", "Notificações, templates, outbox, entregas e lembretes", "Communications", "message-circle", "communication.read", "operations", "communications", "organization", 60, Administrators),
            Item("administration.audit", "Auditoria", "Histórico de atividades", "Audit", "activity", null, null, "audit", "organization", 65, Roles("admin_valora", "consultor_valora")),
            Item("administration.settings", "Configurações", "Preferências da plataforma", "Settings", "settings", null, null, "settings", "organization", 70, Administrators),
            ItemAction("support.help", "Ajuda", "Guias rápidos e atendimento", "Experience", "Help", "file-question", "organization", 80, Results)),
        Section("global-administration", "ADMINISTRAÇÃO GLOBAL", 90,
            ItemAction("saas.overview", "SaaS Admin", "Controle global de clientes, planos e cobrança", "SaasAdmin", "Index", "layout-dashboard", "operations", 0, Roles("admin_valora")),
            ItemAction("saas.customers", "Clientes", "Clientes, uso e situação contratual", "SaasAdmin", "Clients", "building", "operations", 1, Roles("admin_valora")),
            ItemAction("saas.billing", "Cobrança", "Faturas e pagamentos rastreáveis", "SaasAdmin", "Billing", "credit-card", "operations", 2, Roles("admin_valora")),
            ItemAction("saas.modules", "Módulos", "Módulos, flags e limites contratados", "SaasAdmin", "Modules", "layers", "operations", 3, Roles("admin_valora")),
            ItemAction("saas.audit", "Auditoria SaaS", "Ações administrativas críticas", "SaasAdmin", "Audit", "shield", "operations", 4, Roles("admin_valora")),
            ItemAction("master.overview", "Visão Geral", "Central administrativa master", "Administration", "Index", "layout-dashboard", "dashboard", 10, Roles("admin_valora")),
            ItemAction("master.plans", "Planos e Assinaturas", "Central administrativa master", "Administration", "Plans", "credit-card", "organization", 11, Roles("admin_valora")),
            ItemAction("master.flags", "Feature Flags", "Central administrativa master", "Administration", "FeatureFlags", "layers", "settings", 12, Roles("admin_valora")),
            ItemAction("master.diagnostics", "Diagnósticos", "Central administrativa master", "Administration", "Diagnostics", "activity", "surveys", 13, Roles("admin_valora")),
            ItemAction("master.questions", "Questionários e Perguntas", "Central administrativa master", "Administration", "Questions", "file-question", "forms", 14, Roles("admin_valora")),
            ItemAction("master.responses", "Respostas", "Central administrativa master", "Administration", "Responses", "activity", "responses", 15, Roles("admin_valora")),
            ItemAction("master.results", "Resultados", "Central administrativa master", "Administration", "Results", "chart-radar", "results", 16, Roles("admin_valora")),
            ItemAction("master.reports", "Relatórios", "Central administrativa master", "Administration", "Reports", "file-text", "reports", 17, Roles("admin_valora")),
            ItemAction("master.certificates", "Certificados", "Central administrativa master", "Administration", "Certificates", "certificate", "certificates", 18, Roles("admin_valora")),
            ItemAction("master.ai", "Inteligência Organizacional", "Central administrativa master", "Administration", "Intelligence", "brain", "organizational_intelligence", 19, Roles("admin_valora")),
            ItemAction("master.benchmark", "Benchmark", "Central administrativa master", "Administration", "Benchmark", "chart-radar", "organizational_intelligence", 20, Roles("admin_valora")),
            ItemAction("master.one", "One-on-One", "Central administrativa master", "Administration", "OneOnOne", "users", "organizational_intelligence", 21, Roles("admin_valora")),
            ItemAction("master.notifications", "Notificações", "Central administrativa master", "Administration", "NotificationsAdmin", "message-circle", "operations", 22, Roles("admin_valora")),
            ItemAction("master.audit", "Auditoria", "Central administrativa master", "Administration", "Audit", "shield", "audit", 23, Roles("admin_valora")),
            ItemAction("master.jobs", "Jobs e Processamentos", "Central administrativa master", "Administration", "Jobs", "activity", "operations", 24, Roles("admin_valora")),
            ItemAction("master.logs", "Logs do Sistema", "Central administrativa master", "Administration", "Logs", "file-text", "operations", 25, Roles("admin_valora")),
            ItemAction("master.settings", "Configurações", "Central administrativa master", "Administration", "Settings", "settings", "settings", 26, Roles("admin_valora")),
            ItemAction("master.branding", "Aparência e Marca", "Central administrativa master", "Administration", "Branding", "sparkles", "settings", 27, Roles("admin_valora")),
            ItemAction("master.support", "Suporte", "Central administrativa master", "Administration", "Support", "message-circle", "operations", 28, Roles("admin_valora")),
            ItemAction("methodology.overview", "Visão Geral", "Governança da base oficial versionada", "Methodology", "Overview", "sparkles", "organizational_intelligence", 40, Roles("admin_valora")),
            ItemAction("methodology.versions", "Versões", "Draft, publicação e preservação histórica", "Methodology", "Versions", "shield", "organizational_intelligence", 41, Roles("admin_valora")),
            ItemAction("methodology.dimensions", "Dimensões", "Eixos oficiais de maturidade", "Methodology", "Dimensions", "layers", "organizational_intelligence", 42, Roles("admin_valora")),
            ItemAction("methodology.concepts", "Dicionário Cognitivo", "Conceitos oficiais Valora™", "Methodology", "Dictionary", "file-text", "organizational_intelligence", 43, Roles("admin_valora")),
            ItemAction("methodology.map", "Mapa Cognitivo", "Relações e regras de interpretação", "Methodology", "CognitiveMap", "brain", "organizational_intelligence", 44, Roles("admin_valora")),
            ItemAction("methodology.indexes", "Índices", "Escalas e classificações oficiais", "Methodology", "Indexes", "chart-radar", "organizational_intelligence", 45, Roles("admin_valora")),
            ItemAction("methodology.questions", "Perguntas Oficiais", "Banco versionado e rastreável", "Methodology", "Questions", "file-question", "forms", 46, Roles("admin_valora")),
            ItemAction("methodology.prompts", "Prompts IA", "Templates oficiais e schemas", "Methodology", "Prompts", "brain", "organizational_intelligence", 47, Roles("admin_valora")),
            ItemAction("methodology.guardrails", "Guardrails", "Proteções metodológicas", "Methodology", "Guardrails", "shield", "organizational_intelligence", 48, Roles("admin_valora")),
            ItemAction("methodology.validation", "Validação", "Consistência antes da publicação", "Methodology", "Validation", "activity", "organizational_intelligence", 49, Roles("admin_valora")),
            ItemAction("methodology.templates", "Templates", "Diagnósticos oficiais por público", "Methodology", "Templates", "layers", "forms", 50, Roles("admin_valora")),
            ItemAction("methodology.scoring", "Scoring", "Pesos, normalização e maturidade", "Methodology", "Scoring", "chart-radar", "results", 51, Roles("admin_valora")),
            ItemAction("methodology.recommendations", "Recomendações", "Catálogo orientado por evidências", "Methodology", "Recommendations", "activity", "results", 52, Roles("admin_valora")),
            ItemAction("solution-packs.marketplace", "Solution Packs", "Marketplace setorial, versionado e auditável", "SolutionPacks", "Index", "layers", "organizational_intelligence", 60, Administrators),
            ItemAction("solution-packs.builder", "Marketplace Builder", "Crie pacotes privados a partir de templates", "SolutionPacks", "Builder", "sparkles", "organizational_intelligence", 61, Administrators),
            ItemAction("solution-packs.installations", "Pack Installations", "Instalações, updates e rollback", "SolutionPacks", "Installations", "activity", "organizational_intelligence", 62, Administrators),
            ItemAction("solution-packs.updates", "Pack Updates", "Novas versões disponíveis", "SolutionPacks", "Updates", "activity", "organizational_intelligence", 63, Administrators),
            ItemAction("operation.support", "Suporte", "Chamados, comentários e resoluções", "AssistedOperations", "Support", "message-circle", "organization", 70, Administrators),
            ItemAction("operation.feedback", "Feedback", "Experiência e melhorias solicitadas", "AssistedOperations", "Feedback", "sparkles", "organization", 71, Administrators),
            ItemAction("operation.customer-success", "Customer Success", "Saúde e riscos da carteira", "AssistedOperations", "CustomerSuccess", "users", "organization", 72, Administrators),
            ItemAction("operation.usage", "Métricas de Adoção", "Uso real por organização", "AssistedOperations", "Usage", "chart-radar", "organization", 73, Administrators),
            ItemAction("operation.onboarding", "Onboarding", "Checklist operacional pós-venda", "AssistedOperations", "Onboarding", "file-text", "organization", 74, Administrators),
            ItemAction("operation.upgrades", "Solicitações Comerciais", "Upgrade, limites e consultoria", "AssistedOperations", "Upgrades", "activity", "organization", 75, Administrators),
            ItemAction("operation.incidents", "Incidentes", "Investigação e mitigação", "AssistedOperations", "Incidents", "activity", "organization", 76, Administrators),
            ItemAction("operation.releases", "Release Notes", "Evolução controlada do produto", "AssistedOperations", "Releases", "layers", "organization", 77, Administrators),
            ItemAction("success.overview", "Visão Geral", "Ativação, saúde e próximos passos", "SuccessCenter", "Index", "layout-dashboard", "organization", 80, Administrators),
            ItemAction("success.onboarding", "Onboarding", "Checklist de implantação baseado em evidências", "SuccessCenter", "Onboarding", "file-text", "organization", 81, Administrators),
            ItemAction("success.health", "Saúde da Conta", "Score explicável e riscos comprovados", "SuccessCenter", "Health", "activity", "organization", 82, Administrators),
            ItemAction("success.support", "Chamados", "Atendimento com histórico completo", "SuccessCenter", "Support", "message-circle", "organization", 83, Administrators),
            ItemAction("success.knowledge", "Base de Conhecimento", "Orientações para operar com autonomia", "SuccessCenter", "KnowledgeBase", "file-question", "organization", 84, Administrators),
            ItemAction("success.playbooks", "Playbooks", "Jornadas de implantação e recuperação", "SuccessCenter", "Playbooks", "layers", "organization", 85, Administrators),
            ItemAction("success.usage", "Uso do Produto", "Adoção real por funcionalidade", "SuccessCenter", "Usage", "chart-radar", "organization", 86, Administrators),
            ItemAction("subscriptions.marketplace", "Marketplace de Módulos", "Contratação, benefícios e preços por módulo", "Saas", "Marketplace", "layers", "organization", 90, Administrators),
            ItemAction("subscriptions.usage", "Limites e Uso", "Consumo mensal e limites preservados", "Saas", "Usage", "activity", "organization", 91, Administrators),
            ItemAction("administration.platform-governance", "Governança da Plataforma", "Rastreabilidade, integridade e controle", "Intelligence", "PlatformGovernance", "activity", "organizational_intelligence", 100, Administrators),
            ItemAction("administration.health", "Saúde do Sistema", "API, banco, BFF, workers e jobs", "SystemHealth", "Index", "activity", "operations", 101, Administrators),
            ItemAction("administration.backup", "Backup e Restore", "Status e runbook das operações assistidas", "AssistedOperations", "Backup", "layers", "organization", 102, Administrators),
            ItemAction("administration.maintenance", "Modo de Manutenção", "Bloqueios e comunicação operacional", "AssistedOperations", "Maintenance", "activity", "organization", 103, Administrators),
            ItemAction("data.hub", "Data Hub", "Importações, qualidade e rastreabilidade", "Intelligence", "Integrations", "layers", "operations", 110, Administrators))
    ];

    private static NavigationSection Section(string code, string label, int order, params NavigationItem[] items) => new(code, label, order, items);

    private static NavigationItem Item(string code, string label, string description, string controller, string icon,
        string? permission, string? capability, string moduleCode, string? scope, int order, IReadOnlySet<string> roles) =>
        new(code, label, description, NavigationDestination.Mvc(controller), icon, permission, capability, moduleCode, scope, order, null, roles);

    private static NavigationItem ItemAction(string code, string label, string description, string controller, string action,
        string icon, string moduleCode, int order, IReadOnlySet<string> roles) =>
        new(code, label, description, NavigationDestination.Mvc(controller, action), icon, null, null, moduleCode, "organization", order, null, roles);

    private static IReadOnlySet<string> Roles(params string[] values) => new HashSet<string>(values, StringComparer.OrdinalIgnoreCase);
}
