namespace Valora.Domain.Entities;

public sealed class ReportDefinition { public Guid Id { get; set; } public string Code { get; set; } = ""; public string Name { get; set; } = ""; public string? Description { get; set; } public string ReportType { get; set; } = "response"; public string RequiredModuleCode { get; set; } = "relatorios"; public string? MinimumPlanCode { get; set; } public string Status { get; set; } = "active"; public DateTimeOffset CreatedAt { get; set; } public DateTimeOffset? UpdatedAt { get; set; } public bool IsDeleted { get; set; } }
public sealed class GeneratedReport { public Guid Id { get; set; } public Guid OrganizationId { get; set; } public Guid? SurveyId { get; set; } public Guid? ResponseId { get; set; } public Guid? ReportDefinitionId { get; set; } public string Title { get; set; } = ""; public string Format { get; set; } = "html"; public string Status { get; set; } = "generated"; public Guid? GeneratedBy { get; set; } public DateTimeOffset? GeneratedAt { get; set; } public string PayloadJson { get; set; } = "{}"; public string? FileName { get; set; } public string? MimeType { get; set; } public DateTimeOffset CreatedAt { get; set; } }
public sealed class CertificateValidation { public Guid Id { get; set; } public Guid CertificateId { get; set; } public string ValidationCode { get; set; } = ""; public string Status { get; set; } = "valid"; public DateTimeOffset? ValidatedAt { get; set; } public string? ValidationIpHash { get; set; } public string? UserAgent { get; set; } public DateTimeOffset CreatedAt { get; set; } }
public sealed class ExportJob { public Guid Id { get; set; } public Guid OrganizationId { get; set; } public Guid? RequestedBy { get; set; } public string Entity { get; set; } = "responses"; public string Format { get; set; } = "csv"; public string Status { get; set; } = "queued"; public string? FilterJson { get; set; } public string? ResultFileName { get; set; } public string? ResultMimeType { get; set; } public string? ResultPayload { get; set; } public DateTimeOffset CreatedAt { get; set; } public DateTimeOffset? CompletedAt { get; set; } public string? ErrorMessage { get; set; } }
public sealed class LgpdConsent { public Guid Id { get; set; } public Guid? OrganizationId { get; set; } public Guid? SurveyId { get; set; } public Guid? ResponseId { get; set; } public string ParticipantEmailHash { get; set; } = ""; public string ConsentText { get; set; } = ""; public string ConsentVersion { get; set; } = "v1"; public bool Accepted { get; set; } public DateTimeOffset? AcceptedAt { get; set; } public string? IpHash { get; set; } public string? UserAgent { get; set; } public DateTimeOffset CreatedAt { get; set; } }
public sealed class PrivacyRequest { public Guid Id { get; set; } public Guid? OrganizationId { get; set; } public string RequesterEmailHash { get; set; } = ""; public string RequesterEmailMasked { get; set; } = ""; public string RequestType { get; set; } = "data_export"; public string Protocol { get; set; } = ""; public string Status { get; set; } = "open"; public string? Description { get; set; } public Guid? ResponseId { get; set; } public DateTimeOffset RequestedAt { get; set; } public DateTimeOffset? CompletedAt { get; set; } public Guid? HandledBy { get; set; } public string? ResultJson { get; set; } public DateTimeOffset CreatedAt { get; set; } public DateTimeOffset? UpdatedAt { get; set; } }
public sealed class EmailTemplate { public Guid Id { get; set; } public Guid? OrganizationId { get; set; } public string Code { get; set; } = ""; public string Name { get; set; } = ""; public string Subject { get; set; } = ""; public string BodyHtml { get; set; } = ""; public string? BodyText { get; set; } public string Status { get; set; } = "active"; public DateTimeOffset CreatedAt { get; set; } public DateTimeOffset? UpdatedAt { get; set; } public bool IsDeleted { get; set; } }
