using ValoraPesquisa.Application.DTOs;
using ValoraPesquisa.Domain.Entities;
namespace ValoraPesquisa.Application.Contracts;
public record CurrentUser(Guid Id,Guid? OrganizationId,string Role,string Email){ public bool IsAdminValora=>Role=="admin_valora"; }
public interface IAuditService { Task RecordAsync(Guid? orgId,Guid? userId,string action,string entity,Guid? entityId,string correlationId,object? metadata=null); Task<IReadOnlyList<AuditEventDto>> ListAsync(CurrentUser user); }
public interface IPasswordHasher { string Hash(string password); bool Verify(string password,string hash); }
public interface ITokenHasher { string NewToken(); string Hash(string token); bool Verify(string token,string hash); }
public interface IUserRepository { Task<User?> FindByEmailAsync(string email); Task<User?> FindByIdAsync(Guid id); Task<IReadOnlyList<UserDto>> ListAsync(CurrentUser user); Task<UserDto> CreateAsync(User user); Task<UserDto> UpdateAsync(Guid id,string name,string email,string? phone,string role,Guid? organizationId,CurrentUser user); Task SetStatusAsync(Guid id,string status,CurrentUser user); Task UpdateLastLoginAsync(Guid id); }
public interface IOrganizationRepository { Task<IReadOnlyList<OrganizationDto>> ListAsync(CurrentUser user); Task<OrganizationDto?> FindByIdAsync(Guid id,CurrentUser? user=null); Task<Organization?> FindEntityByIdAsync(Guid id); Task<OrganizationDto?> FindBySlugAsync(string slug); Task<OrganizationDto> CreateAsync(Organization org); Task<OrganizationDto> UpdateAsync(Guid id,string name,string publicName,string slug,string? document,string email,string? phone,string status,string planCode,CurrentUser user); }
public interface IFormRepository { Task<IReadOnlyList<FormDto>> ListAsync(CurrentUser user); Task<FormDto?> GetAsync(Guid id,CurrentUser user); Task<FormDto?> GetPublicAsync(Guid id,Guid organizationId); Task<FormDto> SaveAsync(Form form,CurrentUser user); Task<bool> HasQuestionsAsync(Guid formId,Guid organizationId); }
public interface ISurveyRepository { Task<IReadOnlyList<SurveyDto>> ListAsync(CurrentUser user); Task<SurveyDto?> GetAsync(Guid id,CurrentUser? user=null); Task<Survey?> GetEntityAsync(Guid id); Task<SurveyDto> SaveAsync(Survey survey,CurrentUser user); Task SetStatusAsync(Guid id,string status,CurrentUser user); }
public interface ISurveyLinkRepository { Task<IReadOnlyList<SurveyLinkDto>> ListAsync(Guid surveyId,CurrentUser user); Task<CreatedSurveyLinkDto> CreateAsync(SurveyLink link,string publicToken); Task<SurveyLink?> FindValidAsync(Guid surveyId,string orgSlug,string token); Task SetStatusAsync(Guid linkId,string status,CurrentUser user); }
public interface IResponseRepository { Task<SubmitSurveyResponseResult> CreateAsync(SurveyResponse response, ResultScore score,string resultToken); Task<PublicResultDto?> GetResultAsync(Guid responseId,string resultToken); Task<IReadOnlyList<ResponseDto>> ListAsync(CurrentUser user); Task<SurveyResponse?> GetDetailAsync(Guid responseId,CurrentUser user); }
public interface IPlanRepository { Task<IReadOnlyList<PlanDto>> ListAsync(); Task<PlanDto?> GetByCodeAsync(string code); Task<PlanDto?> GetByIdAsync(Guid id); Task<PlanDto> CreateAsync(Plan plan); Task<PlanDto> UpdateAsync(Plan plan); Task<PlanLimitDto?> GetLimitsAsync(string planCode); Task<IReadOnlyList<PlanCapabilityDto>> GetCapabilitiesAsync(string planCode); }
public interface IModuleRepository { Task<IReadOnlyList<ModuleDto>> ListAsync(); Task<ModuleDto?> GetByCodeAsync(string code); Task<IReadOnlyList<OrganizationModuleDto>> ListByOrganizationAsync(Guid organizationId); Task<OrganizationModuleDto> SetOrganizationModuleAsync(Guid organizationId,string moduleCode,bool enabled,string source); }
public interface ISubscriptionRepository { Task<SubscriptionDto?> GetCurrentAsync(Guid organizationId); Task<SubscriptionDto> ChangePlanAsync(Guid organizationId,string planCode); Task<SubscriptionDto> ChangeStatusAsync(Guid organizationId,string status,string billingStatus); Task<SubscriptionDto> CreateInitialAsync(Guid organizationId,string planCode); }
public interface IUsageRepository { Task<UsageMonthlyDto> GetMonthlyAsync(Guid organizationId,DateTime? month=null); Task<UsageMonthlyDto> RecalculateAsync(Guid organizationId,DateTime? month=null); Task IncrementResponsesAsync(Guid organizationId,DateTime? month=null); Task<int> CountActiveSurveysAsync(Guid organizationId); Task<int> CountFormsAsync(Guid organizationId); Task<int> CountUsersAsync(Guid organizationId); Task<int> CountManagersAsync(Guid organizationId); Task<int> CountPublicLinksAsync(Guid organizationId); }
public interface IPermissionService { EntitlementResultDto Can(CurrentUser user,string action,Guid? organizationId=null); IReadOnlyList<string> ActionsForRole(string role); }
public interface IEntitlementService { Task<EntitlementResultDto> CanUseModuleAsync(Guid organizationId,string moduleCode); Task<EntitlementResultDto> CanCreateSurveyAsync(Guid organizationId,bool publishing=false); Task<EntitlementResultDto> CanCreateFormAsync(Guid organizationId); Task<EntitlementResultDto> CanCreateUserAsync(Guid organizationId,bool manager=false); Task<EntitlementResultDto> CanCreateLinkAsync(Guid organizationId); Task<EntitlementResultDto> CanRegisterResponseAsync(Guid organizationId); Task<EntitlementResultDto> HasActiveSubscriptionAsync(Guid organizationId); }
public interface IPlanService { Task<IReadOnlyList<PlanDto>> ListAsync(); Task<PlanDto?> GetAsync(string code); Task<PlanDto> CreateAsync(Plan plan,CurrentUser user); Task<PlanDto> UpdateAsync(Plan plan,CurrentUser user); Task<PlanLimitDto?> LimitsAsync(string code); Task<IReadOnlyList<PlanCapabilityDto>> CapabilitiesAsync(string code); }
public interface IModuleService { Task<IReadOnlyList<ModuleDto>> ListAsync(); Task<IReadOnlyList<OrganizationModuleDto>> ForOrganizationAsync(Guid organizationId); Task<OrganizationModuleDto> SetForOrganizationAsync(Guid organizationId,string moduleCode,bool enabled,string source,CurrentUser user); }
public interface ISubscriptionService { Task<SubscriptionDto?> CurrentAsync(Guid organizationId); Task<SubscriptionDto> ChangePlanAsync(Guid organizationId,string planCode,CurrentUser user); Task<SubscriptionDto> ChangeStatusAsync(Guid organizationId,string status,string billingStatus,CurrentUser user); }
public interface IUsageService { Task<UsageMonthlyDto> CurrentAsync(Guid organizationId); Task<UsageMonthlyDto> RecalculateAsync(Guid organizationId); }
public interface IDashboardMetricsService { Task<DashboardGlobalDto> GlobalAsync(CurrentUser user); Task<DashboardOrganizationDto> OrganizationAsync(CurrentUser user,Guid? organizationId=null); }
public interface IMenuService { Task<IReadOnlyList<MenuItemDto>> GetMenuAsync(CurrentUser user); }
