using ValoraPesquisa.Application.DTOs;
using ValoraPesquisa.Domain.Entities;
namespace ValoraPesquisa.Application.Contracts;
public record CurrentUser(Guid Id,Guid? OrganizationId,string Role,string Email){ public bool IsAdminValora=>Role=="admin_valora"; }
public interface IAuditService { Task RecordAsync(Guid? orgId,Guid? userId,string action,string entity,Guid? entityId,string correlationId,object? metadata=null); Task<IReadOnlyList<AuditEventDto>> ListAsync(CurrentUser user); }
public interface IPasswordHasher { string Hash(string password); bool Verify(string password,string hash); }
public interface ITokenHasher { string NewToken(); string Hash(string token); bool Verify(string token,string hash); }
public interface IUserRepository { Task<User?> FindByEmailAsync(string email); Task<User?> FindByIdAsync(Guid id); Task<IReadOnlyList<UserDto>> ListAsync(CurrentUser user); Task<UserDto> CreateAsync(User user); Task<UserDto> UpdateAsync(Guid id,string name,string email,string? phone,string role,Guid? organizationId,CurrentUser user); Task SetStatusAsync(Guid id,string status,CurrentUser user); Task UpdateLastLoginAsync(Guid id); }
public interface IOrganizationRepository { Task<IReadOnlyList<OrganizationDto>> ListAsync(CurrentUser user); Task<OrganizationDto?> FindByIdAsync(Guid id,CurrentUser? user=null); Task<Organization?> FindEntityByIdAsync(Guid id); Task<OrganizationDto?> FindBySlugAsync(string slug); Task<OrganizationDto> CreateAsync(Organization org); Task<OrganizationDto> UpdateAsync(Guid id,string name,string publicName,string slug,string? document,string email,string? phone,string status,string planCode,CurrentUser user); }
public interface IFormRepository { Task<IReadOnlyList<FormDto>> ListAsync(CurrentUser user); Task<FormDto?> GetAsync(Guid id,CurrentUser user); Task<FormDto?> GetPublicAsync(Guid id,Guid organizationId); Task<FormDto> SaveAsync(Form form,CurrentUser user); Task<bool> HasQuestionsAsync(Guid formId,Guid organizationId); }
public interface ISurveyRepository { Task<IReadOnlyList<SurveyDto>> ListAsync(CurrentUser user); Task<SurveyDto?> GetAsync(Guid id,CurrentUser? user=null); Task<Survey?> GetEntityAsync(Guid id); Task<SurveyDto> SaveAsync(Survey survey,CurrentUser user); Task SetStatusAsync(Guid id,string status,CurrentUser user); }
public interface ISurveyLinkRepository { Task<IReadOnlyList<SurveyLinkDto>> ListAsync(Guid surveyId,CurrentUser user); Task<CreatedSurveyLinkDto> CreateAsync(SurveyLink link,string publicToken); Task<SurveyLink?> FindValidAsync(Guid surveyId,string orgSlug,string token); Task SetStatusAsync(Guid linkId,string status,CurrentUser user); }
public interface IResponseRepository { Task<SubmitSurveyResponseResult> CreateAsync(SurveyResponse response, ResultScore score,string resultToken); Task<PublicResultDto?> GetResultAsync(Guid responseId,string resultToken); Task<IReadOnlyList<ResponseDto>> ListAsync(CurrentUser user); Task<SurveyResponse?> GetDetailAsync(Guid responseId,CurrentUser user); }
